### ISSUE TITLE
babel: \babeltags broken

### ISSUE THREAD

**Issue by lemzwerg** [latex3/latex2e#10]
[babel 3.16]

Have a look at the following example.

```latex
\documentclass{article}

\usepackage[italian, ngerman]{babel}
\babeltags{italian=italian}

\begin{document}
"~foo

\foreignlanguage{italian}{bar}

"~foo

\italian{bar}

"~foo
\end{document}
```

which gives the following output.

![mwe](https://user-images.githubusercontent.com/1630245/34919899-5d75e13a-f96a-11e7-9083-ea35bb028c72.png)

According to the documentation, the `\italian` command defined by `\babeltags` should be equivalent to `\foreignlanguage`.  As can be seen, this is not the case: shorthands are not properly respected.  It's even worse since the deactivation of the shorthands is not local to the scope of `\italian`.

**Comment by blefloch** [comment]
As far as I can tell the right use of `\italian` is `{\italian bar}` or `\begin{italian}bar\end{italian}`.  That seems to work.

**Comment by lemzwerg** [comment]
Ah, ok.  Right.  I misread the documentation.  It's a bit terse (examples would be nice), but concise.

Closing.  Sorry for the noise.
