### ISSUE TITLE
package doc v3: remind users `\PrintDescribeMacro` may be reset at `begindocument/before`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1000]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

With `\usepackage{doc}[=v2]`, users can safely redefine `\PrintDescribeMacro` and friends in preamble. Since `doc` v3, by default these redefinitions are overwritten at `\begin{document}`.

The cause is the package option `hyperref` enabled by default. It resets `\PrintDescribeMacro` and friends at hook `begindocument/before`, after loading `hypdoc` package. [Relevant lines in `doc.dtx`](https://github.com/latex3/latex2e/blob/147851740fd3bfe645d95a6235bee63928f7c80f/base/doc.dtx#L5425-L5463).

This changed behavior caused problem in `thmtools` manual, see https://github.com/muzimuzhi/thmtools/issues/33. Hence I suggest to add a reminder in `doc` manual, for example "the (new) safe way is to put those redefinitions in `begindocument` hook". This will help more package authors/maintainers to use `doc` v3 and its future versions, instead of sticking to v2.
https://github.com/latex3/latex2e/blob/147851740fd3bfe645d95a6235bee63928f7c80f/base/doc.dtx#L620-L636

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{doc}

\renewcommand{\PrintDescribeMacro}[1]{}

\AddToHook{begindocument/before}{\show\PrintDescribeMacro}

\begin{document}
\DescribeMacro{\mycmd}          % marginpar still typesets "\mycmd"
abc abc
\end{document}

```
In log
```tex
> \PrintDescribeMacro=macro:
#1->{\MacroFont \string #1}.
\__hook_toplevel begindocument/before ...ibeMacro 
                                                  
l.11 \begin{document}
```

PS: Aha, coincidentally I opened the 1000th ticket.

**Comment by mrpiggi** [comment]
I think, the more convenient solution would be to check the current definition when the hook is executed and raise a warning, when it was changed in the preamble with an appropriate message what to do instead.
