### ISSUE TITLE
Sort the change history in reverse chronological order

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex2e#1001]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

Currently `\PrintChanges` in the `doc` package prints the change history in chronological order (i.e. the oldest version comes first). But more commonly it should be in *reverse* chronological order, as in the `changes.txt` files in this repo. Hopefully the default behaviour can be changed, or there can be an option to have control over the order.

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{doc}

\begin{document}

% Now the changes are in chronological order
\PrintChanges

\end{document}
```

**Comment by FrankMittelbach** [comment]
The doc package is doing nothing but writing glossary entries into a file which is then sorted externally by a separate program. The result of that sorting is then read in by `\PrintChanges`. By default that external program for sorting is MakeIndex and  that can only do alphabetic search not reverse alphabetic search.

Of course, it would be possible in theory to do  the sorting in TeX itself but this is nothing I plan to do.
