### ISSUE TITLE
Overlapping columns with nested multicol environments

### ISSUE THREAD

**Issue by Virgil121** [latex3/latex2e#1002]
## Brief outline of the bug

I wanted to use the multicols environment to make a multicolumn itemize environment. The problem is I'm already using the multicols* environment in my main document and nesting them seems to break things when a page break occurs at a very specific place: The columns in the first page seem to align with the ones in the nested environment.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{multicol}
\usepackage{lipsum}

\begin{document}
\begin{multicols*}{2}

\lipsum[1-5]

Test

Test

Test

First question:
\begin{multicols}{2}
First

Second
\end{multicols}
There should be an itemize environment here but the bug happens even without it.

\lipsum[1-3]

\end{multicols*}
\end{document}
```

## Log file (required) and possibly PDF file  

[multicolBug.log](https://github.com/latex3/latex2e/files/10793530/multicolBug.log)

[multicolBug.pdf](https://github.com/latex3/latex2e/files/10793531/multicolBug.pdf)

**Comment by davidcarlisle** [comment]
see also https://tex.stackexchange.com/questions/675943/weird-behaviour-with-nested-multicol-environments/675946

**Comment by davidcarlisle** [comment]
8878b0f3 adds a testfile for this, if I run it by hand with public pdflatex, or pdflatex-dev, or with a local format made from develop branch it fails as described and produces

````
This is a generated file for the LaTeX2e validation system.
Don't change this file in any respect.
A: 25593118
B: 31409438
```

showing a narrow first page due to overlapping columns.

But when run from the l3build test harness it produces

````
A: 31409438
B: 31409438
```

and no overlap.

Further investigation required, the test suite passing this test was not the expected outcome.

**Comment by FrankMittelbach** [comment]
exactly my problem :-(  --- can't make it fail in the test suite ... I have a fix but I like to it failing first

**Comment by u-fischer** [comment]
it fails for me, when I update the lipsum package, more exactly if I use the newest lipsum.ltd.tex.

**Comment by davidcarlisle** [comment]
@u-fischer  ah bingo! we have a frozen `lipsum` package in the latex2e/support

**Comment by u-fischer** [comment]
yes, the texts are changed. I have now an example without lipsum but it requires \usepackage[latin]{babel} ...

**Comment by davidcarlisle** [comment]
@u-fischer  now we know how many linees are requred we can probably use `a\\a\\a\\a` and drop the mock latin

**Comment by u-fischer** [comment]
yes, shortening by one line allowed me to remove latin.
