### ISSUE TITLE
Error context lines in log and console output in case of duplicate destination

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#1003]
## Brief outline of the bug

Not sure at all where to report this.

I encountered a situation where the subsection counter had been reset [1]  Then hyperref warns about duplicate destination, which is not unexpected at all, but the manner it does is demonstrative, especially with `\errorcontextlines` not zero.  The log contains typical trace one sees when TeX encounters an error, but the `pdflatex` run has zero status on exit.  This surprised me.

.. [1] with `scrartcl` an unnumbered section resets the subsection counter; the  article class does not, and TL2019 scrarcl did not.  Took me some time to understand my problems came from this `scrartcl` behavior but below I give sample file using `article` where the triggering is manually done.

console output without increased `\errorcontexlines`:

```
pdfTeX warning (ext4): destination with the same identifier (name{subsection.1.
1}) has been already used, duplicate ignored
<argument> ...shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...
l.39 \end{document}
                   ] (./other_koma_starsect.aux)
```

I am reporting because I have seen lots of time pdfTeX warning about duplicate destinations but none with  a TeX error look like above.

This is without setting `\errorcontexlines`, when it is set what one gets  (this is with the `article` class example) with a non-zero setting:

```
pdfTeX warning (ext4): destination with the same identifier (name{subsection.1.
1}) has been already used, duplicate ignored
<argument> ...shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...

\use_ii:nn #1#2->#2
                   
<argument> ...rotect \hook_use:n {shipout/after}}}
                                                  \cs_set_eq:NN \protect \__...

\use_ii:nn #1#2->#2
                   
<to be read again> \__shipout_execute_cont: 
                                            \endgroup \set@typeset@protect 
\@outputpage ...width {\@thefoot }\color@endbox }}
                                                  \global \let \if@newlist \...

\@opcol ...te@singlecol@structures@@ \@outputpage 
                                                  \fi \global \@mparbottom \...
<output> ...specialoutput \else \@makecol \@opcol 
                                                  \@startcolumn \@whilesw \i...

\newpage ...prevdepth \fi \fi \vfil \penalty -\@M 
                                                  
\clearpage ...opskip \hbox {}\fi \fi \fi \newpage 
                                                  \write \m@ne {}\vbox {}\pe...

\enddocument ...t \@checkend {document}\clearpage 
                                                  \UseOneTimeHook {enddocume...

\end  ...ook {env/#1/end}}\csname end#1\endcsname 
                                                  \@checkend {#1}\expandafte...
l.40 \end{document}
                   ] (./other_hyper_duplicate.aux)
```

source file with `scrartcl`

```
\documentclass{scrartcl}
\listfiles
\usepackage{hyperref}
\begin{document}

% \errorcontextlines20

\section{foo}

\subsection{subfoo1}

\typeout{thesubsection: \thesubsection}

\section*{Test}

\subsection{subfoo2}

\typeout{thesubsection: \thesubsection}

\end{document}
```

Here is input using `article` class

```
\documentclass{article}
\listfiles
\usepackage{hyperref}
\begin{document}

\errorcontextlines20

\section{foo}

\subsection{subfoo1}

\typeout{thesubsection: \thesubsection}

%\section*{Test}
\setcounter{subsection}{0}

\subsection{subfoo2}

\typeout{thesubsection: \thesubsection}

\end{document}
```

and the log file is attached.
[other_hyper_duplicate.log](https://github.com/latex3/latex2e/files/10815680/other_hyper_duplicate.log)

**Comment by u-fischer** [comment]
This warnings are from the backend. You get similar warning in plain:

~~~~
x \pdfdest name {abc} fit x \pdfdest name {abc} fit \bye 
~~~~

The warnings are issued during the shipout that's why you see some context of shipout commands. 

I don't think that such warnings should give exist status 1.  Imho there are not errors but similar to multiplied defined labels.

**Comment by muzimuzhi** [comment]
(just to share)

From [git blame on the mirrorred texlive repo](https://github.com/TeX-Live/texlive-source/blame/a2e3a356353f78b0efe7c8bcb53cebfcbdc1b209/texk/web2c/pdftexdir/pdftex.web#L34955), the behavior of such warning in pdftex has been like this for at least 17 years.
https://github.com/TeX-Live/texlive-source/blob/a2e3a356353f78b0efe7c8bcb53cebfcbdc1b209/texk/web2c/pdftexdir/pdftex.web#L34949-L34967
```pascal
@<Declare procedures needed in |pdf_hlist_out|, |pdf_vlist_out|@>=
procedure warn_dest_dup(id: integer; byname: small_number; s1, s2: str_number);
begin
    if pdf_suppress_warning_dup_dest > 0 then
        return;
    pdf_warning(s1, "destination with the same identifier (", true, false);
    if byname > 0 then begin
        print("name");
        print_mark(id);
    end
    else begin
        print("num");
        print_int(id);
    end;
    print(") ");
    print(s2);
    print_ln;
    show_context;
end;
```
https://github.com/TeX-Live/texlive-source/blob/a2e3a356353f78b0efe7c8bcb53cebfcbdc1b209/texk/web2c/pdftexdir/pdftex.web#L7977-L7983
```
@ Thus, the ``current input state'' can be very complicated indeed; there
can be many levels and each level can arise in a variety of ways. The
|show_context| procedure, which is used by \TeX's error-reporting routine to
print out the current input state on all levels down to the most recent
line of characters from an input file, illustrates most of these conventions.
The global variable |base_ptr| contains the lowest level that was
displayed by this procedure.
```

**Comment by jfbu** [comment]
@muzimuzhi well, clearly I forgot to test my non-koma example with TL2019 or I would have seen indeed the console output, in a different form then:
```
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
                                                  \fi \fi 
```
Somehow I felt I had seen many many duplicate destination reports from pdfTeX over the years but not like this.
Obviously I must have been wrong... 

Proposing to close...

**Comment by jfbu** [comment]
> I don't think that such warnings should give exist status 1. Imho there are not errors but similar to multiplied defined labels.

I feel the same.  I don't know why I got suddenly preoccupied by these things (amplified by my `\errorcontexlines` setting).

**Comment by muzimuzhi** [comment]
BTW, setting `\pdfsuppresswarningdupdest` to positive will suppress such "warnings". This primitive is supported since pdftex 1.40.13, texlive 2012 (or 2013?) https://github.com/TeX-Live/texlive-source/commit/03a98fe87b3350511df55dafa40ef0b6deee3659
