### ISSUE TITLE
Provide a test for l3kernel date

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1004]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

Although the LaTeX3 programming layer (expl3) is bundled into the LaTeX2e format since Feb, 2020, the LaTeX3 (or, l3kernel) has its own version, is upgraded independently and more frequently, hence there's the need to test for its date.

## Minimal example showing the current behaviour

As of LaTeX2e 2022-11-01, there's no public command for this.

## Minimal example showing the desired new behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\makeatletter
\def\IfExplAtLeastTF{%
  \@ifl@t@r\ExplLoaderFileDate}
\makeatother

\begin{document}
\IfExplAtLeastTF{2023-02-02}TF % T

\IfExplAtLeastTF{2100-01-01}TF % F
\end{document}
```

One use case is to make example files testing against latex3 bugs/new features work for both old and new latex3 releases.
```tex
\IfExplAtLeastTF{<date>}{<patch code or empty>}{<empty or patch code>}
```

It seems l3kernel need a similar test as well, especially for non-LaTeX users. But since in LaTeX there's already a helper `\@ifl@t@r`.

**Comment by muzimuzhi** [comment]
Perhaps also provide a test/tester for `l3backend` date, see https://github.com/latex3/latex3/issues/1177#issuecomment-1457584599.

Currently there's no specific macro holding that date, but in `latex2e` once the backend is loaded its date is stored at the beginning of `\cs{ver@l3backend- \c_sys_backend_str .def}`.

```tex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\ExplSyntaxOn
\msg_new:nnn { kernel } { backend-not-loaded }
  { l3backend~ not~ yet~ loaded }

\cs_new:Npn \IfExplBackendAtLeastTF
  {
    \bool_lazy_and:nnTF
      { \cs_if_exist_p:N \c_sys_backend_str }
      { \cs_if_exist_p:c { ver@l3backend- \c_sys_backend_str .def }}
      {
        \exp_args:cc { @ifl@t@r } { ver@l3backend- \c_sys_backend_str .def }
      }{
        % make sure \IfExplBackendAtLeastTF is expandable
        \msg_expandable_error:nnn{ kernel } { backend-not-loaded } {}
        \use_none:nnn
      }
  }
\ExplSyntaxOff

% without \usepackage{expl3} and \DocumentMetadata{...}, backend is loaded just 
% before hook begindocument
\IfExplBackendAtLeastTF{2023-01-01}TF    % throw error

\AddToHook{begindocument/before}{%
  \IfExplBackendAtLeastTF{2023-01-01}TF%   throw error
}

\AddToHook{begindocument}{%
  \IfExplBackendAtLeastTF{2023-01-16}TF%   leave T
  \IfExplBackendAtLeastTF{2100-01-01}TF%   leave F
}

\begin{document}
% "TF" is typeset
\end{document}
```

**Comment by josephwright** [comment]
I've prodded the team about this :)

**Comment by josephwright** [comment]
We've decided that `\IfExplAtLeastTF` is indeed the best name: I'll sort a PR later today
