### ISSUE TITLE
font is incorrect compiled in Tex Live 2023

### ISSUE THREAD

**Issue by Conan1985** [latex3/latex2e#1024]
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  \begin{rSection}{Skills}
	
	I can fly. 
	
\end{rSection}


\begin{document}

  In Line 101 of attached resume.cls file (in a zip file), only the title of `rSection` is defined as bold font. However, after compiling using the latest TEK Live 2023, every font in the `rSection` is bold. The same issue doesn't exist in the previous TEK Live (< 2022).
  
\end{document}
```

## Log file (required) 
and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/11064398/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/11064400/test.pdf)
[resume.cls.zip](https://github.com/latex3/latex2e/files/11064404/resume.cls.zip)

**Comment by davidcarlisle** [comment]
I am sorry but the posted document just gives an undefined error for rSection

The log is from a different document using resume class, but that class is contributed software not maintained by the core latex project, you would need to report any issues to its maintainer.

**Comment by u-fischer** [comment]
this is related to https://github.com/latex3/latex2e/issues/1021: The class uses \MakeUppercase and the bold font leaks. This will be resolved in the next LaTeX version.
