### ISSUE TITLE
bm does not handle localmathalphabets

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#1028]
## Brief outline of the bug

If the math alphabet allocations are undone, bm gets confused and the mapping of math alphabets gets corrupted.
`\mathsf{Q2}` is made bold by use of `\bm` elsewhere in the same expression.

Should be fixable, but a workaround is to disable localmathalphabets although of course you may then run out of math alphabets, which is particularly likely with bm.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}


\DeclareSymbolFont{symbols1}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols2}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols3}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols4}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols5}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols6}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols7}     {OMS}{cmsy}{m}{n}

\usepackage{bm}

%\setcounter{localmathalphabets}{0}

\begin{document}

\showoutput

$\mathsf{Q1}$

$\mathsf{Q2}+\bm{\mathsf{Q3}}$

$\mathsf{Q4}$

\end{document}
```

## Log file (required) and possibly PDF file  

[bmlocal.log](https://github.com/latex3/latex2e/files/11119903/bmlocal.log)

**Comment by davidcarlisle** [comment]
@FrankMittelbach 

I can reproduce  this without `bm` . for math alphabets, bm does essentially `\boldsymbol` ie a mathchoice around `\mbox{\boldmath$...` 

```
\RequirePackage{latexbug}
\documentclass{article}


\DeclareSymbolFont{symbols1}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols2}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols3}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols4}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols5}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols6}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols7}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols8}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols9}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols10}     {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{symbols11}     {OMS}{cmsy}{m}{n}


%\setcounter{localmathalphabets}{0}


\begin{document}

\showoutput

$\mathsf{Q1}$

$\mathsf{Q2}+\mbox{\boldmath $\mathsf{Q3}$}$

$\mathsf{Q4}$

\end{document}
```

**Comment by davidcarlisle** [comment]
I think if you locally set the frozen one (if it has been defined) when switching groups it should be OK.
At the top level that would be a no-op as any previous mv@reset would have made them the same already
but within  a nested math it allows reset  to current state. Still some global assignments that I haven't really checked.


```
$
\mathsf{Q2}+
\mbox{%
%
\ifcsname mv@\math@version @frozen\endcsname
  \expandafter\let
    \csname mv@\math@version @frozen\expandafter\endcsname
    \csname mv@\math@version\endcsname
\fi
\boldmath
$\mathsf{Q3}$}
$
```

**Comment by FrankMittelbach** [comment]
I think that'll do the trick and it only needs to be executed in \mathversion.
