### ISSUE TITLE
Case conversions (\uppercase etc) are completely broken in UTF-8

### ISSUE THREAD

**Issue by ilyaza** [latex3/latex2e#103]
## Brief outline of the bug
Case conversions (`\uppercase` etc) are completely broken in UTF-8 (both with default, and with
`\usepackage[utf8x]{inputenc}`).  It seems that the conversions are actually applied twice: once to the bytestream (**sic!**), then to the Unicode codepoints.

This makes `\section{}` unusable with styles which uppercase running headers (such as `AmS`).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
% \usepackage[utf8x]{inputenc}

%\usepackage[latin1,utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}

This would fail without tuneup: (omitted: \verb|\uppercase{|“asdf” æà\verb|}|)  (while æà would be uppercased, quotes would trigger UTF-8 errors).

% \uccode`\⽠\⥥
\uccode 226=226\relax  % 226 is one of the bytes (the leading one) in UTF-8 representation of U-2000–U-0x2FFF

With codepoint 226 corrected, this succeeds: \uppercase{“asdf” æà}

\makeatletter
{\def\T{128}%
  \@whilenum \T<256\do{\global\uccode \T=\T\relax\edef\T{\the\numexpr1+\T}}%
}\makeatother

With all codepoints $\ge\texttt{0x80}$ corrected, quotes work, but alphabetical letters are not uppercased: \uppercase{“asdf” æà}.

\end{document}
```

## Log file (required) and possibly PDF file  
[my-utf8-test-a.pdf](https://github.com/latex3/latex2e/files/2717440/my-utf8-test-a.pdf)
[my-utf8-test-a.log](https://github.com/latex3/latex2e/files/2717442/my-utf8-test-a.log)

**Comment by josephwright** [comment]
The primitives have very well-defined if perhaps not that useful behaviour, and that is outside the control of the LaTeX team. The kernel provides `\MakeUppercase`, or you might look at the `expl3` function `\tl_upper_case:n`, _etc._

**Comment by josephwright** [comment]
All that said, I guess a change to the upper half of the 8-bit range would be handy ... @davidcarlisle  and @FrankMittelbach  are the best placed to decide.

**Comment by ilyaza** [comment]
Defined **where**?  Does this include double-conversion?!  At least, this was not in the original TeXBook!

Anyway, this has nothing to do with primitives, but with the setup of `\uccode` etc., and them matching the switches in the current encoding.

**Comment by davidcarlisle** [comment]
The uppercase/lowercase table in tex (unfortunately) is tied to the _font_ encoding (as it is used for hyphenation) so it is fixed based on the T1 font encoding, whatever input encoding is used. This means that \uppercase and \lowercase never work reliably on anything other than ascii text, and latex2e has always provided \MakeUppercase which is (slightly)  better in the face of accented characters.

If you do \uppercase {utf-8 encoded text} then it will uppercase the byte stream based on the T1 font table and so produce essentially arbitrarily broken text it may or may not be valid UTF-8 at all but teh inputenc active character definitions will try to decode it as UTF-8.

**Comment by ilyaza** [comment]
A slight clarification of what David wrote:

in `latex.ltx`  primitives `\uppercase` and `\lowercase` are used ***only*** for catcode manipulations, and to implement `\MakeUppercase` and `\MakeLowercase`.  Other packages should proceed likewise.

E.g., `𝒜ᴍ𝒮` classes include the lines like `\@ifundefined{MakeUppercase}{\let\MakeUppercase\uppercase}{}%`, but still they use `\uppercase` where `\MakeUppercase` needs to be used.  This should be fixed!  (I did not try to check all LaTeX’s classes likewise; however, `article` is OK.)
