### ISSUE TITLE
Documentation bug in ltplain.dtx

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1031]
In ltplain.dtx, line 920, a "% \end{oldcomments}" (and later a "% \begin{oldcomments}", possibly even further "% \end{oldcomments} ... \begin{oldcomments}") are missing. Thus in the output the source code is printed verbatim, see the source2e.pdf, page 25: "In the past \LaTeX{} used the default value of \texttt{1} for \cs{tracinglostchars} because this was the best it could do." ...

File b: ltplain.dtx Date: 2022/01/25 Version v2.3h

**Comment by FrankMittelbach** [comment]
yeah, there are some of those leftovers ... I decided to drop the "oldcomments" rather than adding more of them in this file.
