### ISSUE TITLE
Loading `ucmtt.fd` typesets `<->sub*cmtt/m/n`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1037]
## Brief outline of the bug

Loading `ucmtt.fd` will typeset `<->sub*cmtt/m/n`, which is caused by a stray line `{<->sub*cmtt/m/n}{}` in `ucmtt.fd` (line 79 in `ucmtt.fd` or line 1053 in `cmfonts.fdd`, see below).
```tex
% ucmtt.fd in LaTeX2e 2022-11-01 PL1, lines 77--82
\DeclareFontShape{U}{cmtt}{bx}{it}%
  {<->sub*cmtt/m/it}{}
  {<->sub*cmtt/m/n}{}             % <<< stray line
\DeclareFontShape{U}{cmtt}{bx}{ui}%
  {<->sub*cmtt/m/it}{}
\endinput
```

It seems to me the root cause is a missing `\DeclareFontShape{U}{cmtt}{bx}{sl}` line (right after line 1052 below) in `cmfonts.fdd`.  Relative lines were added in commit a78ac53d (initial code for nfss axes, 2019-10-07).
https://github.com/latex3/latex2e/blob/d93b8c3bdd7922813bab84c4900cdad383190e4a/base/cmfonts.fdd#L1050-L1058

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\begin{document}
\usefont{U}{cmtt}{m}{n}
\end{document}
```

- Expected: Nothing is typeset.
- Actual: `<->sub*cmtt/m/n` is typeset.

## Log file (required) and possibly PDF file  

[latex2e-stray-line-in-ucmtt.fd-.log](https://github.com/latex3/latex2e/files/11223027/latex2e-stray-line-in-ucmtt.fd-.log)

**Proposal**
```diff
diff --git a/base/cmfonts.fdd b/base/cmfonts.fdd
index fd7a14ae..c94833ff 100644
--- a/base/cmfonts.fdd
+++ b/base/cmfonts.fdd
@@ -67,7 +67,7 @@
 %<*driver,  >
              \ProvidesFile{cmfonts.drv}
 %</driver,  >
-        [2022/07/10 v2.5l Standard LaTeX font definitions]
+        [2023/04/13 v2.5m Standard LaTeX font definitions]
 %
 %<*driver>
 \documentclass{ltxdoc}
@@ -1049,7 +1049,9 @@
 %
 % \changes{v2.5j}{2019/12/16}{Provide substitutions for cmtt/bx/sl}
 %    \begin{macrocode}
+% \changes{v2.5m}{2023/04/13}{Add missing substitution for U/cmtt/bx/sl}
 %<+OT1cmtt>\DeclareFontShape{OT1}{cmtt}{bx}{sl}
+%<+Ucmtt>\DeclareFontShape{U}{cmtt}{bx}{sl}
 %<-nowarn>  {<->sub*cmtt/m/n}{}
 %<+nowarn>  {<->ssub*cmtt/m/n}{}
 %<+OT1cmtt>\DeclareFontShape{OT1}{cmtt}{bx}{ui}
```

**Comment by davidcarlisle** [comment]
Thanks,  your suggested fix looks correct to me.

**Comment by FrankMittelbach** [comment]
@davidcarlisle are you going to update?

**Comment by davidcarlisle** [comment]
yes I'll sort it

**Comment by davidcarlisle** [comment]
thanks, fix added as in your diff except I moved the `\changes` out of  `macrode`  I also loaded all the u*fd files in base in the test file, just in case:-)

**Comment by muzimuzhi** [comment]
> fix added as in your diff except I moved the `\changes` out of `macrode`

Ah yes, thanks!
