### ISSUE TITLE
Feature request: The review button should have a red indicator of open issues

### ISSUE THREAD

**Issue by w4iei** [latex3/latex2e#1040]
Situation: 
My reviewer added a bunch of comments, but I was unaware that he had done so. A UI indicator would have been helpful

**Comment by daleif** [comment]
(1) comments how/where? (2) UI are not really LaTeX related.

Thus be a bit more specific as to what exactly you are writing about and how this is related to LaTeX and friends

**Comment by FrankMittelbach** [comment]
This repository is only concerned with the core LaTeX macros but with any user interface program to edit or runLaTeX documents. If you have an issue with the UI you use (of which there are many) you need to address your problem to the people who maintain or develop that UI.
