### ISSUE TITLE
\inserts assigned twice

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1041]
## Brief outline of the bug

LuaLaTeX assigns inserts down from about 200 down to ... where there is no room due to already used count/box/..., then it starts at insert about 252 down to about 201 and then from about 65534 down to... - it does not stop! Inserts about 252 down to where no more room for a counter is, are assigned twice. There a stop must be inserted before reaching the classical 0-255 range.
DC's fix makes the compilation stop after \insert308 instead of \insert256 ? "204" instead "\@ccclvi" runs until \insert256, but why?

Subject: 	Re: [Dev-luatex] Possible double use of inserts
Date: 	Wed, 5 Apr 2023 14:34:21 +0100
From: 	David Carlisle <###>

This, I think, to stop \extrafloats reaching down in to the "classic" range 0-255.
I just added the line marked.

\documentclass{minimal}
\makeatletter
\def\extrafloats#1{%
\ifnum#1>\z@
\count@\numexpr\float@count-1\relax
   \ifnum\count@<\@cclvi \ch@ck0\m@ne\insert\fi%<<<<<<<<<<<<
   \ch@ck0\count@\count
   \ch@ck1\count@\dimen
   \ch@ck2\count@\skip
   \ch@ck4\count@\box
\global\e@alloc@chardef\float@count\count@
\global\expandafter\e@alloc@chardef
             \csname bx@\the\float@count\endcsname\float@count
\@cons\@freelist{\csname bx@\the\float@count\endcsname}%
\expandafter
\extrafloats\expandafter{\numexpr#1-1\relax}%
\fi}%

\newcommand{\stressInsert}[1]{%
   \@tempcnta=0\relax%
   \@whilenum\the\@tempcnta<#1\do%
    {\advance\@tempcnta +1\relax%
     \expandafter\newinsert\csname TestInsert\the\@tempcnta\endcsname%
     \message{insert \the\@tempcnta:  \number\csname TestInsert\the\@tempcnta\endcsname,  \the\allocationnumber^^J}%
    }%
   }
\makeatother
\stressInsert{70000}
\begin{document}
\end{document}

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{minimal}
\makeatletter
\newcommand{\stressInsert}[1]{%
  \@tempcnta=0\relax%
  \@whilenum\the\@tempcnta<#1\do%
   {\advance\@tempcnta +1\relax%
    \expandafter\newinsert\csname TestInsert\the\@tempcnta\endcsname%
    \message{insert \the\@tempcnta: \the\allocationnumber^^J}%
   }%
  }
\makeatother
\stressInsert{70000}
\begin{document}
\end{document}
```

## Log file (required) and possibly PDF file  
[insert-example.log](https://github.com/latex3/latex2e/files/11230812/insert-example.log)

**Comment by davidcarlisle** [comment]
Yes thanks I'd planned to make an issue for this but hadn't done it yet.

Not directly related (as it is not changed by the above) but while looking at this I noticed

```
\expandafter
\extrafloats\expandafter{\numexpr
```

is not unwinding the stack as intended as `\numexpr`  is not expandable, so  in luatex `\extrafloats{2000}` will always give

```
! error:  (tex): \*expr can only be nested 1000 deep
```

A more complete fix is

```
\documentclass{article}
\makeatletter
\def\extrafloats#1{%
\ifnum#1>\z@
\count@\numexpr\float@count-1\relax
  \ifnum\count@<266 \ch@ck0\m@ne\insert\fi%<<<<<<<<<<<<
  \ch@ck0\count@\count
  \ch@ck1\count@\dimen
  \ch@ck2\count@\skip
  \ch@ck4\count@\box
\global\e@alloc@chardef\float@count\count@
\global\expandafter\e@alloc@chardef
            \csname bx@\the\float@count\endcsname\float@count
\@cons\@freelist{\csname bx@\the\float@count\endcsname}%
\expandafter
\extrafloats\expandafter{\the\numexpr#1-1\expandafter}%
\fi}%


\extrafloats{2000}

\begin{document}

\end{document}
```

For the original issue. extra floats are allocated "from the top" they check that they do not clash with normal register allocations, but if counts have not been allocated past the classic range, the extrafloat allocations would over-write the reserved counts255-265 the extra line added checks for this case.

This was only an issue in luatex as in other engines `\insert` can only use classic registers.

Both issues can only occur if you have thousands of pending floats.
