### ISSUE TITLE
Make GitHub aware of special tex extensions

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1045]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

Some TeX files in current repo is not recognized by GitHub.  By adding lines like `*.def linguist-language=tex` to `.gitattributes`, I did an attempt in https://github.com/muzimuzhi/latex2e/commit/a48a2872e41fd79882947b283155b186d396d702.

Other repos may need similar improvements, but I think it could start from `latex2e`, for its authoritativeness and traffic.

Compare the code highlighting on GitHub without and with this <s>PR</s> change ("after" links may need a manual refresh):
| Extension | Example file | Before (bc373e81b2cf8f2d1fb895f46ad9719c1202daae) | After (https://github.com/muzimuzhi/latex2e/commit/a48a2872e41fd79882947b283155b186d396d702) |
|--------|--------|--------|--------|
| `.def` | `texmf/tex/latex/graphics-def/luatex.def` | [before](https://github.com/latex3/latex2e/blob/bc373e81b2cf8f2d1fb895f46ad9719c1202daae/texmf/tex/latex/graphics-def/luatex.def) | [after](https://github.com/muzimuzhi/latex2e/blob/a48a2872e41fd79882947b283155b186d396d702/texmf/tex/latex/graphics-def/luatex.def) |
| `.fdd` | `base/cmfonts.fdd` | [before](https://github.com/latex3/latex2e/blob/bc373e81b2cf8f2d1fb895f46ad9719c1202daae/base/cmfonts.fdd) | [after](https://github.com/muzimuzhi/latex2e/blob/a48a2872e41fd79882947b283155b186d396d702/base/cmfonts.fdd) |
| `.ini` | `texmf/tex/latex/latexconfig/latex.ini` | [before](https://github.com/latex3/latex2e/blob/bc373e81b2cf8f2d1fb895f46ad9719c1202daae/texmf/tex/latex/latexconfig/latex.ini) | [after](https://github.com/muzimuzhi/latex2e/blob/a48a2872e41fd79882947b283155b186d396d702/texmf/tex/latex/latexconfig/latex.ini) (or [this link](https://github.com/muzimuzhi/latex2e/blob/add-linguist-lang/texmf/tex/latex/latexconfig/latex.ini)) |
| `.lvt` | `base/testfiles/tlb0001.lvt` | [before](https://github.com/latex3/latex2e/blob/bc373e81b2cf8f2d1fb895f46ad9719c1202daae/base/testfiles/tlb0001.lvt) | [after](https://github.com/muzimuzhi/latex2e/blob/a48a2872e41fd79882947b283155b186d396d702/base/testfiles/tlb0001.lvt) |
| `.pvt` | `required/latex-lab/testfiles-OR-luatex/test1.pvt` | [before](https://github.com/latex3/latex2e/blob/bc373e81b2cf8f2d1fb895f46ad9719c1202daae/required/latex-lab/testfiles-OR-luatex/test1.pvt) | [after](https://github.com/muzimuzhi/latex2e/blob/a48a2872e41fd79882947b283155b186d396d702/required/latex-lab/testfiles-OR-luatex/test1.pvt) |

- Doc for `linguist-language=<lang>` https://github.com/github/linguist/blob/master/docs/overrides.md
- List of TeX file extensions already known to GitHub
  https://github.com/github/linguist/blob/5a0c74277548122267d84283910abd5e0b89380e/lib/linguist/languages.yml#L6834-L6859

**Comment by josephwright** [comment]
Feel free to put in a PR ;) Though I'm not sure this is a major issue  ...
