### ISSUE TITLE
Tomba kanssa 

### ISSUE THREAD

**Issue by 622333371** [latex3/latex2e#1048]
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here

\begin{document}

  % Demonstration of issue here
  
\end{document}
```

## Log file (required) and possibly PDF file  

@misc{ enwiki:1148294040, auteur = "{contributeurs Wikipédia}", title = "Tomba Kanssa --- {Wikipédia}{,} L'Encyclopédie Libre", année = "2023", URL = "https://en.wikipedia.org/w/index.php?title=Tomba_Kanssa&oldid=1148294040", note = "[En ligne ; consulté le 16 avril 2023]" }

**Comment by PhelypeOleinik** [comment]
What's the issue?
