### ISSUE TITLE
Missing documentation for `\DeclareFontShapeChangeRule`, `\fontseriesforce`, and `\fontshapeforce`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1051]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

2020-02-02 release introduced several new commands related to font declaration. Thanks to @dr-scsi, some (or, most) of them are already documented in `fntguide`, see
- https://github.com/latex3/latex2e/pull/347
- https://github.com/latex3/latex2e/pull/349
- 213516d (updated documentation on \updefault and \ulcdefault, 2020-11-17)
- https://github.com/latex3/latex2e/issues/717 resolved by https://github.com/latex3/latex2e/pull/720

or the git history of [`base/doc/fntguide.tex`](https://github.com/latex3/latex2e/commits/develop/base/doc/fntguide.tex).

I find `\DeclareFontShapeChangeRule`, `\fontseriesforce`, and `\fontshapeforce` are undocumented yet.

**Comment by FrankMittelbach** [comment]
@muzimuzhi that's a good argument ... well if it stays long enough and you have trouble with that then eventually ... but if you make an attempt that would help

**Comment by FrankMittelbach** [comment]
@muzimuzhi still on point to produce a first doc draft?

**Comment by josephwright** [comment]
@muzimuzhi  Status here?

**Comment by dr-scsi** [comment]
In order to get this rolling, I suggest to start with:

```
diff --git a/base/doc/fntguide.tex b/base/doc/fntguide.tex
index 7cf5d239..0c8ef7cc 100644
--- a/base/doc/fntguide.tex
+++ b/base/doc/fntguide.tex
@@ -1997,6 +1997,55 @@ For example,
 would use |sb| (semi-bold) when |\rmfamily\bfseries| is requested in
 document.

+\subsection{Handling of current and requested font series and shape}
+
+In the original NFSS implementation, the series was a single attribute
+stored in |\f@series| and so one always had to specify both weight and
+width together.  Hence, it was impossible to typeset a paragraph in a
+condensed font and inside have a few words in bold weight (but still
+condensed) without doing this manually by requesting
+|\fontseries{bc}\selectfont|.
+
+\NEWfeature{2020/02/02}
+The new implementation now works differently by looking both at the
+current value of |\f@series| and the requested new series and out of
+that combination selects a resulting series value.  Thus, if the current
+series is |c| and we ask for |b|, we now get |bc|.  This is done by
+consulting a simple lookup table where entries can be added or changed
+with |\DeclareFontSeriesChangeRule|:
+\begin{decl}
+  |\DeclareFontSeriesChangeRule| %
+  \arg{current series} \arg{requested series} \\
+  \leavevmode\hfill    \arg{result} \arg{alternative result}
+\end{decl}
+
+\arg{current series} is the value currently stored |\f@series|,
+\arg{requested series} is the new series requested, \arg{result} is the
+combined value if it exists for the given font family, and
+\arg{alternative result} is a fallback in case \arg{result} doesn't
+exist.  The example above now looks like this:
+\begin{verbatim}
+   \DeclareFontSeriesChangeRule{c}{b}{bc}{}
+\end{verbatim}
+which means: Deliever |bc| series if |c| is current and |b| is
+additionally requested, and do nothing if the current font doesn't have
+the combination.
+
+A special value is |m| which is used to reset both weight and width.  In
+order to reset just the width, |?m| is provided and |m?| to reset just
+the weight, e.g.:
+\begin{verbatim}
+   \DeclareFontSeriesChangeRule{c}{m?}{c}{}
+\end{verbatim}
+
+The corresponding macro |\DeclareFontShapeChangeRule| is also provided
+for setting database entries for font shapes:
+\begin{decl}
+  |\DeclareFontShapeChangeRule| %
+  \arg{current shape} \arg{requested shape} \\
+  \leavevmode\hfill    \arg{result} \arg{alternative result}
+\end{decl}
+
 \subsection{Handling of nested emphasis}

 \begin{decl}
```

Just let me know if this is going in the right direction, and I will make a proper PR for discussion etc.  TIA.

**Comment by FrankMittelbach** [comment]
Yes, looks nice to me, there are some typos and probably some different wordings that I would make, but yes, please go ahead and turn it into a PR - thanks.

To random comments:
```
+\arg{current series} is the value currently stored |\f@series|,
```
better:
```
The \arg{current series} is the value currently stored in |\f@series|,
```

```
+which means: Deliever |bc| series if |c| is current and |b| is
+additionally requested, and do nothing if the current font doesn't have
+the combination.
```
Deliver

however, better might be  "switch to the |bc| series ...(additionally) requested, ..."

From that example it is not so clear, what the fourth argument really does, perhaps better to use one that actually contains a value there (or even use 2 examples, because usually there is no alt value).

**Comment by dr-scsi** [comment]
@FrankMittelbach - Thanks for your comments.  PR #1303 is available for discussion.

**Comment by FrankMittelbach** [comment]
now done, thanks to @dr-scsi
