### ISSUE TITLE
Rendering of ß, SS, and ẞ

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1057]
## Brief outline of the bug
\ss, ß, \SS, and ẞ are not correctly translated to ß and ẞ. OK, if the font does not have the capital ẞ, it cannot be printed, but at least the replacement "SS" could be used. (Which fonts do contain ẞ?)

## Minimal example showing the bug

```
\RequirePackage{latexbug}
\documentclass{article}
\setlength{\parindent}{0pt}
\begin{document}
small \verb|\ss| \ss{} -- capital \verb|\SS| \SS{} -- small UTF8 ß -- capital UTF8 ẞ{}\bigskip

\verb|\MakeUppercase|:

\MakeUppercase{small }\verb|\ss|\MakeUppercase{ \ss{} -- capital }\verb|\SS|\MakeUppercase{ \SS{} -- small UTF8 ß -- capital UTF8 ẞ{}}\bigskip

\verb|\uppercase|:

\uppercase{small }\verb|\ss|\uppercase{ \ss{} -- capital }\verb|\SS|\uppercase{ \SS{} -- small UTF8 ß -- capital ẞ{}%
}\bigskip

\verb|\textsc|:

\textsc{small }\verb|\ss|\textsc{ \ss{} -- capital }\verb|\SS|\textsc{ \SS{} -- small UTF8 ß -- capital UTF8 ẞ{}}\bigskip

\verb|\sc|:

{\sc small }\verb|\ss|{\sc\  \ss{} -- capital }\verb|\SS|{\sc\  \SS{} -- small UTF8 ß -- capital UTF8 ẞ{}}
\end{document}
```
## Log file (required) and possibly PDF file  

latex.log:
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=latex 2023.4.22)  24 APR 2023 16:13
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**eszett.tex
(./eszett.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-04-20> (m:/2023/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2022/06/14 v1.0n Bug-classification
)
(m:/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(m:/2023/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2022/07/02 v1.4n Standard LaTeX file (size option)
)
\c@part=\count185
\c@section=\count186
\c@subsection=\count187
\c@subsubsection=\count188
\c@paragraph=\count189
\c@subparagraph=\count190
\c@figure=\count191
\c@table=\count192
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen140
) (m:/2023/texmf-dist/tex/latex/l3backend/l3backend-dvips.def
File: l3backend-dvips.def 2023-04-19 L3 backend support: dvips
\l__pdf_internal_box=\box51
\g__pdf_backend_object_int=\count193
\l__pdf_backend_content_box=\box52
\l__pdf_backend_model_box=\box53
\g__pdf_backend_annotation_int=\count194
\g__pdf_backend_link_int=\count195
\g__pdf_backend_link_sf_int=\count196
)
No file eszett.aux.
\openout1 = `eszett.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

! LaTeX Error: Invalid UTF-8 byte "C1.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 }
      \bigskip
? 

! LaTeX Error: Invalid UTF-8 byte "9A.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 }
      \bigskip
? 
! Missing \endcsname inserted.
<to be read again> 
                   \protect 
l.14 }\bigskip
              
? 

! LaTeX Error: Invalid UTF-8 byte sequence (Ð\endcsname).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.14 }\bigskip
              
? 
[1

] (./eszett.aux) ) 
Here is how much of TeX's memory you used:
 1769 strings out of 476002
 42157 string characters out of 5797215
 1853065 words of memory out of 5000000
 22324 multiletter control sequences out of 15000+600000
 512756 words of font info for 34 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 32749
 34i,5n,45p,198b,1309s stack positions out of 10000i,1000n,20000p,200000b,200000s

Output written on eszett.dvi (1 page, 816 bytes).

pdflatex.log

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023) (preloaded format=pdflatex 2023.4.22)  24 APR 2023 16:05
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**Namenlos-1.tex
(./Namenlos-1.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-04-20> (m:/2023/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2022/06/14 v1.0n Bug-classification
)
(m:/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(m:/2023/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2022/07/02 v1.4n Standard LaTeX file (size option)
)
\c@part=\count185
\c@section=\count186
\c@subsection=\count187
\c@subsubsection=\count188
\c@paragraph=\count189
\c@subparagraph=\count190
\c@figure=\count191
\c@table=\count192
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen140
) (m:/2023/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
File: l3backend-pdftex.def 2023-04-19 L3 backend support: PDF output (pdfTeX)
\l__color_backend_stack_int=\count193
\l__pdf_internal_box=\box51
)
(./Namenlos-1.aux)
\openout1 = `Namenlos-1.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.

! LaTeX Error: Invalid UTF-8 byte "C1.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 }
      \bigskip
? 

! LaTeX Error: Invalid UTF-8 byte "9A.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 }
      \bigskip
? 
! Missing \endcsname inserted.
<to be read again> 
                   \protect 
l.20 }\bigskip
              
? 

! LaTeX Error: Invalid UTF-8 byte sequence (Ð\endcsname).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 }\bigskip
              
? 
[1

{m:/2023/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./Namenlos-1.aux) ) 
Here is how much of TeX's memory you used:
 1768 strings out of 476001
 41989 string characters out of 5797189
 1852068 words of memory out of 5000000
 22320 multiletter control sequences out of 15000+600000
 512756 words of font info for 34 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 32749
 34i,5n,45p,202b,1309s stack positions out of 10000i,1000n,20000p,200000b,200000s
<m:/2023/texmf-dist/fonts/type1/public/amsfonts/c
m/cmcsc10.pfb><m:/2023/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb><m:/2023/texmf-dist/fonts/type1/public/amsfonts/cm
/cmtt10.pfb>
Output written on Namenlos-1.pdf (1 page, 38201 bytes).
PDF statistics:
 23 PDF objects out of 1000 (max. 8388607)
 13 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

lualatex.log

This is LuaHBTeX, Version 1.16.0 (TeX Live 2023)  (format=lualatex 2023.4.22)  24 APR 2023 16:18
 restricted system commands enabled.
**eszett.tex
(./eszett.tex
LaTeX2e <2022-11-01> patch level 1
Lua module: luaotfload 2022-10-03 3.23 Lua based OpenType font support
Lua module: lualibs 2022-10-04 2.75 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2022-10-04 2.75 ConTeXt Lua libraries -- extended collection.
luaotfload | conf : Root cache directory is "M:/2023/texmf-var/luatex-cache/generic/names".
luaotfload | init : Loading fontloader "fontloader-2022-10-03.lua" from kpse-resolved path "m:/2023/texmf-dist/tex/luatex/luao
tfload/fontloader-2022-10-03.lua".
Lua-only attribute luaotfload@noligature = 1
luaotfload | init : Context OpenType loader version 3.120
Inserting `luaotfload.node_processor' in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' in `hpack_filter'.
Inserting `luaotfload.glyph_stream' in `glyph_stream_provider'.
Inserting `luaotfload.define_font' in `define_font'.
Lua-only attribute luaotfload_color_attribute = 2
luaotfload | conf : Root cache directory is "M:/2023/texmf-var/luatex-cache/generic/names".
Inserting `luaotfload.harf.strip_prefix' in `find_opentype_file'.
Inserting `luaotfload.harf.strip_prefix' in `find_truetype_file'.
Removing  `luaotfload.glyph_stream' from `glyph_stream_provider'.
Inserting `luaotfload.harf.glyphstream' in `glyph_stream_provider'.
Inserting `luaotfload.harf.finalize_vlist' in `post_linebreak_filter'.
Inserting `luaotfload.harf.finalize_hlist' in `hpack_filter'.
Inserting `luaotfload.cleanup_files' in `wrapup_run'.
Inserting `luaotfload.harf.finalize_unicode' in `finish_pdffile'.
Inserting `luaotfload.glyphinfo' in `glyph_info'.
Lua-only attribute luaotfload.letterspace_done = 3
Inserting `luaotfload.aux.set_sscale_dimens' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_font_index' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.patch_cambria_domh' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.fixup_fontdata' in `luaotfload.patch_font_unsafe'.
Inserting `luaotfload.aux.set_capheight' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_xheight' in `luaotfload.patch_font'.
Inserting `luaotfload.rewrite_fontname' in `luaotfload.patch_font'. L3 programming layer <2023-04-20>
Inserting `tracingstacklevels' in `input_level_string'. (m:/2023/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2022/06/14 v1.0n Bug-classification
)
(m:/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(m:/2023/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2022/07/02 v1.4n Standard LaTeX file (size option)
luaotfload | db : Font names database loaded from M:/2023/texmf-var/luatex-cache/generic/names/luaotfload-names.luc.gz)
\c@part=\count183
\c@section=\count184
\c@subsection=\count185
\c@subsubsection=\count186
\c@paragraph=\count187
\c@subparagraph=\count188
\c@figure=\count189
\c@table=\count190
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen139
) (m:/2023/texmf-dist/tex/latex/l3backend/l3backend-luatex.def
File: l3backend-luatex.def 2023-04-19 L3 backend support: PDF output (LuaTeX)
\l__color_backend_stack_int=\count191
Inserting `l3color' in `luaotfload.parse_color'.
\l__pdf_internal_box=\box51
) (./eszett.aux)
\openout1 = eszett.aux

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 4.
LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 4.

(m:/2023/texmf-dist/tex/latex/base/ts1cmr.fd
File: ts1cmr.fd 2022/07/10 v2.5l Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
 [1

{m:/2023/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./eszett.aux))

Here is how much of LuaTeX's memory you used:
 1826 strings out of 478263
 100000,1977958 words of node,token memory allocated
 411 words of node memory still in use:
   3 hlist, 1 vlist, 1 rule, 2 glue, 3 kern, 1 glyph, 4 attribute, 49 glue_spec, 4 attribute_list, 1 write nodes
   avail lists: 2:159,3:20,4:2,5:35,6:18,7:904,9:78,10:1,11:40
 22116 multiletter control sequences out of 65536+600000
 17 fonts using 980087 bytes
 33i,5n,39p,198b,1309s stack positions out of 10000i,1000n,20000p,200000b,200000s
<m:/2023/texmf-dist/fonts/opentype/public/lm/lmromancaps10-regular.otf><m:/2023/texmf-dist/fonts/opentype/public/lm/lmmono10-r
egular.otf><m:/2023/texmf-dist/fonts/opentype/public/lm/lmroman10-regular.otf>
Output written on eszett.pdf (1 page, 11110 bytes).

PDF statistics: 29 PDF objects out of 1000 (max. 8388607)
 16 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 131072)
 1 words of extra memory for PDF output out of 10000 (max. 100000000)

xelatex.log

This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex 2023.4.22)  24 APR 2023 16:21
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**eszett.tex
(./eszett.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-04-20> (m:/2023/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2022/06/14 v1.0n Bug-classification
)
(m:/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(m:/2023/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2022/07/02 v1.4n Standard LaTeX file (size option)
)
\c@part=\count181
\c@section=\count182
\c@subsection=\count183
\c@subsubsection=\count184
\c@paragraph=\count185
\c@subparagraph=\count186
\c@figure=\count187
\c@table=\count188
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen140
) (m:/2023/texmf-dist/tex/latex/l3backend/l3backend-xetex.def
File: l3backend-xetex.def 2023-04-19 L3 backend support: XeTeX
\g__graphics_track_int=\count189
\l__pdf_internal_box=\box51
\g__pdf_backend_object_int=\count190
\g__pdf_backend_annotation_int=\count191
\g__pdf_backend_link_int=\count192
) (./eszett.aux)
\openout1 = `eszett.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 4.
LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 4.

(m:/2023/texmf-dist/tex/latex/base/ts1cmr.fd
File: ts1cmr.fd 2022/07/10 v2.5l Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmromancaps10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmromancaps10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmromancaps10-regular]:mapping=tex-text;!
Missing character: There is no ẞ (U+1E9E) in font [lmromancaps10-regular]:mapping=tex-text;!
[1

] (./eszett.aux) ) 
Here is how much of TeX's memory you used:
 1803 strings out of 476660
 43366 string characters out of 5810308
 1845698 words of memory out of 5000000
 22143 multiletter control sequences out of 15000+600000
 512311 words of font info for 35 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 32749
 33i,5n,39p,195b,1309s stack positions out of 10000i,1000n,20000p,200000b,200000s

Output written on eszett.pdf (1 page).

**Comment by u-fischer** [comment]
There is no bug here.

In pdflatex you can declare missing unicode chars. E.g. after

~~~~
\DeclareUnicodeCharacter{1E9E}{\SS}
~~~~

the ẞ input will work.


`\uppercase` is a tex primitive, don't use it. 

lualatex will use ẞ if the font supports it and fall back to SS if not. Xelatex will report a missing character.
