### ISSUE TITLE
ignoring space after \eqno

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#1059]
## Brief outline of the bug

```
$$ x \eqno 1$$
N
```

is not really latex syntax but it previously more or less worked but recent additions to `\everymath`  hide the end of line from the implicit ignore spaces of `$$`.

## Minimal example showing the bug

```latex
% https://tex.stackexchange.com/q/68420

\RequirePackage{latexbug}
\documentclass{article}
\makeatletter
\begin{document}

$$x$$
N\\N1


$$x \hbox{$1$} $$
N\\N2


$$x \eqno 1$$
N\\N3


$$x \leqno 1$$
N\\N4

%%%
\let\xxeqno\eqno

% Plan A add extra \ignorespaces
\protected\def\eqno{\xxeqno\aftergroup\ignorespaces}

$$x \eqno 1$$
N\\N5


% Plan B arrange that \everymath doesn't add \@ignorefalse in this case?

\end{document}

```

## Log file (required) and possibly PDF file  

[eqno.log](https://github.com/latex3/latex2e/files/11361272/eqno.log)
[eqno.pdf](https://github.com/latex3/latex2e/files/11361274/eqno.pdf)

**Comment by davidcarlisle** [comment]
The suggested change causes problems for amsmath (as shown in test suite failures in branch gh1059)

```
\documentclass{article}

\let\xxeqno\eqno
\protected\def\eqno{\xxeqo\aftergroup\ignorespaces}
\usepackage{amsmath}
\show\veqno
\begin{document}

\begin{equation}
  x=y 
\end{equation}

\end{document}
```

amsmath detects `\eqno` is not primitve so declines to save it as `\@@eqno`

```
! LaTeX Error: Unable to properly define \@@eqno; primitive \eqno no longer pri
mitive.
```

However if you scroll past that it defines `\veqno` to be `\@@eqno`  and uses that so `equation` gives

```
! Undefined control sequence.
\endmathdisplay@a ...\df@tag \@empty \else \veqno 
```

We could update `amsmath`  in latex-dev to match but is that the right thing or should we look to adding the \ignorespaces via \everymath, and avoid changing `\eqno`?

**Comment by davidcarlisle** [comment]
In the branch I adjusted amsmath:

```
+% \changes{v2.17o}{2023/05/13}{Do not error if \cs{eqno} not primitive}
 %    \begin{macrocode}
-\@saveprimitive\leqno\@@leqno
-\@saveprimitive\eqno\@@eqno
+\let\@@eqno\eqno
+\let\@@leqno\leqno
```

**Comment by PhelypeOleinik** [comment]
> We could update `amsmath`  in latex-dev to match but is that the right thing or should we look to adding the \ignorespaces via \everymath, and avoid changing `\eqno`?

Not changing `\eqno` would be better, but is it possible? How would you detect `\eqno` from within `\everymath` to issue `\ignorespaces`?

**Comment by davidcarlisle** [comment]
@PhelypeOleinik  "Not changing \eqno would be better" that was my initial thought too but actually as amsmath has always had `\def\eqno{\@@eqno\let\eqno\relax\let\leqno\relax}` without any bad effects making it non-primitve in the kernel seems safe enough, apart from the explicit test for being a primitve in amsmath (now) removed by this PR
