### ISSUE TITLE
New xr.dtx results in ! LaTeX Error: Missing \begin{document}.

### ISSUE THREAD

**Issue by shartge** [latex3/latex2e#106]
## Brief outline of the bug

First I have to apologize for the title, but at the moment I have no clue what the core problem is. Please retitle as you see fit.

The two following changes
https://github.com/latex3/latex2e/commit/bcccc7c42356b000ade01f457f409bf9d825be9a
https://github.com/latex3/latex2e/commit/b2b32f2af1d73f1577c57c4119ca0d01fd0a5cc1
somehow break creation of the documentation of the backup
tool Bacula (https://bacula.org/git/cgit.cgi/docs/?h=Branch-9.4), a Debian Bug has been
filed about this issue at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917654

Relevent output from the bug here, complete log at the end.
```
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/float/float.sty) (./bacula.sty
(/usr/share/texlive/texmf-dist/tex/latex/carlisle/ltxtable.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/tabularx.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty))
(/usr/share/texlive/texmf-dist/tex/latex/tools/varioref.sty)
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/switch.def)
(/usr/share/texlive/texmf-dist/tex/generic/babel-english/english.ldf
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def))))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/xr-hyper.sty

Package xr-hyper Warning: Load package `hyperref' after `xr-hyper'.

) (/usr/share/texlive/texmf-dist/tex/latex/tools/xr.sty)
(../../../latex/external-references.tex

Package xr Warning: 
No file ../main/sqlite.aux
LABELS NOT IMPORTED.
 on input line 30.


! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.41 \externaldocument[main-]{../main/main}
                                           
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ../pdf-and-html/utility/utility.log.
```
If I replace xr.sty with a version derived from before the above mentioned commits, everything works again.

I also tried restructuring the source documents to fix "Warning: Load package `hyperref' after `xr-hyper'." but this was a Red Herring, making sure to include xr-hyper before hyperref does not fix the error about the external-references mentioned here.

It is entirely possible the source document is broken and needs to be fixed, but then again: it worked until recently.

## Minimal example showing the bug

I have to apologize again, because of the complexity of the source document and my lack of knowledge with respect to external-references I have not been able to create a minimal example demonstrating the issue.

## Log file (required) and possibly PDF file  

[utility.log](https://github.com/latex3/latex2e/files/2725631/utility.log)

**Comment by FrankMittelbach** [comment]
not sure this throws some light on the issue but could you please  add the file `../main/main.aux` to for inspection?

**Comment by shartge** [comment]
Sure, no problem. I had gzip it to get GitHub to accept it.
[main.aux.gz](https://github.com/latex3/latex2e/files/2725672/main.aux.gz)

**Comment by davidcarlisle** [comment]
I tried to reconstruct a test file from the log but didn't get the error, is it possible to zip up the tex files in a way that `pdflatex utility.tex` gives the error without us needing to set up a build environment fro the whole tool? Don't worry too much about minimizing the example,

**Comment by shartge** [comment]
I'll see what I can do. This may take some minutes to put together.

**Comment by davidcarlisle** [comment]
On Fri, 4 Jan 2019 at 00:49, Sven Hartge <notifications@github.com> wrote:

> I'll see what I can do. This may take some minutes to put together.
>

No rush: it's 1 in the morning here (and 2 for Frank) so I guess it'll be
tomorrow (or at least later today) before we look at this:-)

David

**Comment by shartge** [comment]
I could ZIP the stuff together, but in the end it will be just a ZIP of the Docs GIT of Bacula. Would it suffice if I provide instruction on what to clone and what commands to run to get to the state I am in right now?

**Comment by shartge** [comment]
In the end it boils down to these commands (the git clone takes about a minute to finish):

```
git clone http://git.bacula.org/docs.git --single-branch Branch-9.4
cd Branch-9.4/docs
make distclean
make
```

**Comment by davidcarlisle** [comment]
OK I had to grab a copy of html.sty from somewhere but I can reproduce the
error, too late to look now, will look this evening.

**Comment by shartge** [comment]
I am relieved you are able to reproduce the problem, because sometimes during my experiments the error vanished for me, resulting from an unclean environment left over from earlier tests.

I look forward to any results your investigation will produce.

**Comment by davidcarlisle** [comment]
Sorry I broke xr with the last update, could you try the following.

The pdf build then works for me (the makefile then died building the web version but I think that was unrelated missing dependencies)
It is just changing three occurrences of \XR@next to \XR@tempa  at the end of the file.

If that looks OK I'll get an update to the latex/tools bundle pushed out asap.


```
%%
%% This is file `xr.sty',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% xr.dtx  (with options: `package')
%% 
%% This is a generated file.
%% 
%% The source is maintained by the LaTeX Project team and bug
%% reports for it can be opened at https://latex-project.org/bugs/
%% (but please observe conditions on bug reports sent to that address!)
%% 
%% 
%% Copyright 1993-2017
%% The LaTeX3 Project and any individual authors listed elsewhere
%% in this file.
%% 
%% This file was generated from file(s) of the Standard LaTeX `Tools Bundle'.
%% --------------------------------------------------------------------------
%% 
%% It may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License, either version 1.3c
%% of this license or (at your option) any later version.
%% The latest version of this license is in
%%    https://www.latex-project.org/lppl.txt
%% and version 1.3c or later is part of all distributions of LaTeX
%% version 2005/12/01 or later.
%% 
%% This file may only be distributed together with a copy of the LaTeX
%% `Tools Bundle'. You may however distribute the LaTeX `Tools Bundle'
%% without such generated files.
%% 
%% The list of all files belonging to the LaTeX `Tools Bundle' is
%% given in the file `manifest.txt'.
%% 
%% File: xr.dtx Copyright (C) 1994-1994 2018 David Carlisle
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{xr}
         [2019/01/05 v5.04 eXternal References (DPC)]
\def\externaldocument{\@ifnextchar[\XR@{\XR@[]}}
\def\XR@[#1]#2{{%
  \makeatletter
  \def\XR@prefix{#1}%
  \XR@next#2.aux\relax\\}}
\def\XR@next#1\relax#2\\{%
  \edef\XR@list{#2}%
  \XR@loop{#1}}
\def\XR@aux{%
  \ifx\XR@list\@empty\else\expandafter\XR@explist\fi}

\def\XR@explist{\expandafter\XR@next\XR@list\\}
\def\XR@loop#1{\openin\@inputcheck#1\relax
  \ifeof\@inputcheck
    \PackageWarning{xr}{^^JNo file #1^^JLABELS NOT IMPORTED.^^J}%
    \expandafter\XR@aux
  \else
    \PackageInfo{xr}{IMPORTING LABELS FROM #1}%
    \expandafter\XR@read\fi}
\def\XR@read{%
  \read\@inputcheck to\XR@line
  \expandafter\XR@test\XR@line...\XR@}
\long\def\XR@test#1#2#3#4\XR@{%
  \let\XR@tempa\@gobbletwo
  \ifx#1\newlabel
    \let\XR@tempa\@firstoftwo%
  \else\ifx#1\@input
     \let\XR@tempa\@secondoftwo
  \fi\fi
   \XR@tempa{\newlabel{\XR@prefix#2}{#3}}{\edef\XR@list{\XR@list#2\relax}}%
  \ifeof\@inputcheck\expandafter\XR@aux
  \else\expandafter\XR@read\fi}

\endinput
%%
%% End of file `xr.sty'.
```

**Comment by shartge** [comment]
Yes, that new xr.sty fixes the build problems for me.

I can also confirm that the files generated by the 5.02 and 5.04 xr.sty are identical, so no other regressions occured here, at least in the confines of bacula-docs.

Thank you, for your fast reply and fix!

**Comment by davidcarlisle** [comment]
OK thanks for the confirmation, I'll get a new tools release packaged up this weekend.

**Comment by davidcarlisle** [comment]
A new tools bundle has been installed at CTAN so will be distributed to texlive/miktex mirrors over the next few days.

Thanks for the report.
