### ISSUE TITLE
Extend \NewDocumentCommand to support regex argument types

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#1065]
## Brief outline of the enhancement

As in title: discussed in https://github.com/latex3/latex3/issues/820, re-reporting here after the `ltcmd` move and focussing in on what is doable _now_.

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here

\begin{document}

  % Demonstration of issue here
  
\end{document}
```

## Minimal example showing the desired new behaviour

```latex
\documentclass{article}
\NewDocumentCommand\rating
  { x{[A-Fa-f]} x{\+*|\-*} }
  {\texttt{#1}\textsuperscript{#2}}
\begin{document}
\rating A+++
\rating F-
\end{document}
```

**Comment by josephwright** [comment]
I have a working implementation: may be a few days before I have time to check in properly.

**Comment by car222222** [comment]
This is a very way-out extension of the idea of a document command with typed arguments.

**Comment by josephwright** [comment]
@car222222 Well yes, and honestly I suspect we will say 'no', but I'd like a decision with some discussion, and the best way to get that is to work on the issue :)

**Comment by car222222** [comment]
@josephwright Sure, that makes sense.

Maybe the result will be that all types of non-mandatory args will be implemented via regexps??? :-).

**Comment by josephwright** [comment]
```latex
\documentclass{article}
\ExplSyntaxOn
\cs_set_protected:Npn \__cmd_tmp:w #1
  {
    \cs_new_protected:Npn \__cmd_normalize_type_x:w ##1
      {
        \quark_if_recursion_tail_stop_do:nn {##1} { \__cmd_bad_arg_spec:wn }
        \__cmd_normalize_type_X:w {##1} {#1}
      }
}
\exp_args:No \__cmd_tmp:w { \c_novalue_tl }
 
\cs_new_protected:Npn \__cmd_normalize_type_X:w #1#2
  {
    \quark_if_recursion_tail_stop_do:nn {#2} { \__cmd_bad_arg_spec:wn }
    \bool_set_false:N \l__cmd_grab_expandably_bool
    \__cmd_add_arg_spec_mandatory:n { X {#1} {#2} }
    \__cmd_normalize_arg_spec_loop:n
  }
\cs_new_protected:Npn \__cmd_add_type_X:w #1#2
  {
    \__cmd_flush_m_args:
    \__cmd_add_default:
    \__cmd_add_grabber:N X
    \tl_put_right:Nn \l__cmd_signature_tl { {#1} {#2} }
    \__cmd_prepare_signature:N
  }
\cs_new_protected:Npn \__cmd_grab_X:w #1#2#3 \__cmd_run_code:
  { \__cmd_grab_X_aux:nnNn {#1} {#2} \cs_set_protected_nopar:Npn {#3} }
\cs_new_protected:Npn \__cmd_grab_X_aux:nnNn #1#2#3#4
  {
    \tl_set:Nn \l__cmd_signature_tl {#4}
    \exp_after:wN #3 \l__cmd_fn_tl
      {
        \peek_regex_replace_once:nnTF {#1} { { \0 } }
          { \__cmd_add_arg:n }
          { \__cmd_add_arg:n {#2} }
      }
    \l__cmd_fn_tl
  }

\ExplSyntaxOff
\NewDocumentCommand\rating
  {x{[A-Fa-f]} x{[\+\-]*}}
  {%
    \showtokens{#1:#2}%
    \texttt{#1}\textsuperscript{#2}%
  }
\begin{document}

\rating A+++
\rating F-
\rating G*
\end{document}
````

**Comment by josephwright** [comment]
The above extract would implement the suggestion. However, like @car222222  I think that when you look at this in the round, and the steps we took with `g`, `u` and `l` types, it doesn't fit into the 'focussed' `ltcmd` space. A user could define their own command anyway, with only a slight amount of work. But really if you want something non-standard then probably you are coding your own interface (cf. `pgf`).

So my suggestion is to close as no further action: thoughts from others welcome.

**Comment by davidcarlisle** [comment]
I would agree with not adding this

**Comment by josephwright** [comment]
OK, it looks like we have a decision: @car222222, @davidcarlisle, @FrankMittelbach  and I feel that on reflection this is outside of what we want to see in `ltcmd`. That matches the decisions made about `g`, `u` and `l` types, and the fact that `ltcmd` is mean to be about 'LaTeX-like' document syntax. 

I'll therefore close here: we have a record of the decision process.
