### ISSUE TITLE
\makebox with test for alignment

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex2e#1072]
## Brief outline of the enhancement

Current LaTeX does not check an existing second optional argument for the alignment of `\makebox`. It can be any
character or empty. In such a case the third argument will be ignored.

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

% set to true for a check of \bm@#2
\iffalse
\makeatletter
\long\def\@imakebox[#1][#2]#3{%
	\@begin@tempboxa\hbox{#3}%
	\setlength\@tempdima{#1}%       support calc
	\@ifundefined{bm@#2}{%
		\@latex@warning{unknown align `#2` for makebox, using c}%
		\hb@xt@\@tempdima{\bm@c}}%
	  {\hb@xt@\@tempdima{\csname bm@#2\endcsname}}%
	\@end@tempboxa}
\makeatother
\fi
\begin{document}
	
\makebox[1cm][1]{foo} bar
	
\makebox[1cm][X]{foo} bar

\makebox[1cm][]{foo} bar

\makebox[1cm][l]{foo} bar

\end{document}
```

Up-to-date TL23

**Comment by davidcarlisle** [comment]
For better or worse most similar alignment options accept anything and act as `c` for example
` \begin{tabular}[X]`  is silently accepted as ` \begin{tabular}[c]`  so it might be more consistent
to use `\bm@c` if `\csname bm@#2\endcsname` is `\relax` ?

**Comment by FrankMittelbach** [comment]
true @davidcarlisle. On the other hand we have fixed it at least in amsmath in one case, so may think of doing the same elsewhere (not really that important but also not quite right as often -- like here -- it works incorrectly without any error or warning).

**Comment by davidcarlisle** [comment]
@FrankMittelbach  we migh want to check the argument not just check the csname is defined...

```
\documentclass{article}

\usepackage{bm}

\begin{document}

\makebox[1cm][end]{xxx}
\end{document}
```

**Comment by FrankMittelbach** [comment]
@davidcarlisle as the argument is constructed it is a) faster and b) pretty safe to just check for the constructed name, don't you think?

**Comment by FrankMittelbach** [comment]
even given your example :-)

**Comment by davidcarlisle** [comment]
> @davidcarlisle as the argument is constructed it is a) faster and b) pretty safe to just check for the constructed name, don't you think?

yes but as we are making a change anyway  to fix the text vanishing with no warning we could perhaps change the csname prefix not to clash with bm (or change bm package not to clash with this)

**Comment by FrankMittelbach** [comment]
agreed, that wouldn't hurt :-)

**Comment by davidcarlisle** [comment]
This came up agan today at stack exchange and I had forgotten about this issue but proposed essentially the same change in an answer

https://tex.stackexchange.com/questions/699544/applying-makeuppercase-on-makebox-makes-text-disappear/699561#699561

I think we should probably fix this this time. Silently ignoring bad option wouldn't be so bad, but discarding the content inthat case is not good.
