### ISSUE TITLE
Diacritics over i and j inconsistently remove the dots

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1075]
Using \i and \j to get a dotless i and a dotless j and then placing something above them works. (Thus: not bug report but enhancement request.) If dotted i and j are used with diacritics over them, LaTeX even automatically removes the dot - sometimes, but not always. And LuaLaTeX and XeLaTeX do not remove the dots in the same cases as LaTeX. Suggestion: Automatic removal of the dot should be done more consistent. So, LaTeX should remove the dot in as much cases as possible. Would for LuaLaTeX and XeLaTeX separate enhancement requests be necessary, or would this "carry" from LaTeX?

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug} 
\documentclass{article}
\begin{document}
\LaTeX

\'i=í=\'\i=\'{ı} acute

\`i=ì=\`\i=\`{ı} grave

\^i=î=\^\i=\^{ı} circumflex

\v i$\neq$ǐ=\v\i=\v{ı} caron

\~i$\neq$ĩ=\~\i=\~{ı} tilde

\.i=i=\.\i=\.{ı} one overdot

\"i=ï=\"\i=\"{ı} two overdots

\u i$\neq$ĭ=\u\i=\u{ı} breve

\= i$\neq$ī=\=\i=\={ı} bar

Do the letters \H{\i} \r{\i} even exist? If they do not exist, they do not need to be regarded. \H{i} -- \r{i}

For j:

\'j$\neq$\'\j

\`j$\neq$\`\j

\^j$\neq$\^\j

\v j$\neq$\v\j

\~j$\neq$\~\j

\.j$\neq$\.\j

\"j$\neq$\"\j

\u j$\neq$\u\j

\= j$\neq$\=\j

--

Lua\LaTeX

\'i=í=\'\i$\neq$\'{ı} acute (last always off-center)

\`i=ì=\`\i$\neq$\`{ı} grave

\^i=î=\^\i$\neq$\^{ı} circumflex

\v i=ǐ=\v\i$\neq$\v{ı} caron

\~i=ĩ=\~\i=\~{ı} tilde

\.i$\neq$i$\neq$\.\i=\.{ı} one overdot

\"i=ï=\"\i$\neq$\"{ı} two overdots

\u i=ĭ=\u\i$\neq$\u{ı} breve

\= i=ī=\=\i$\neq$\={ı} bar


Do the letters \H{\i} \r{\i} [off-center again] even exist? If they do not exist, they do not need to be regarded. \H{i} -- \r{i} [dot not removed]

For j:

\'j$\neq$\'\j

\`j$\neq$\`\j

\^j=\^\j

\v j=\v\j

\~j$\neq$\~\j

\.j$\neq$\.\j

\"j=\"\j

\u j$\neq$\u\j

\= j$\neq$\=\j

--

Xe\LaTeX

\'i=í=\'\i$\neq$\'{ı} acute (last always off-center)

\`i=ì=\`\i$\neq$\`{ı} grave

\^i=î=\^\i$\neq$\^{ı} circumflex

\v i=ǐ=\v\i$\neq$\v{ı} caron

\~i=ĩ=\~\i=\~{ı} tilde

\.i$\neq$i$\neq$\.\i=\.{ı} one overdot

\"i=ï=\"\i$\neq$\"{ı} two overdots

\u i=ĭ=\u\i$\neq$\u{ı} breve

\= i=ī=\=\i$\neq$\={ı} bar

Do the letters \H{\i} \r{\i} [off-center again] even exist? If they do not exist, they do not need to be regarded. \H{i} -- \r{i} [dot not removed]

For j:

\'j$\neq$\'\j

\`j$\neq$\`\j

\^j=\^\j

\v j=\v\j

\~j$\neq$\~\j

\.j$\neq$\.\j

\"j=\"\j

\u j$\neq$\u\j

\= j$\neq$\=\j

\end{document}
```

**Comment by zauguin** [comment]
For LuaLaTeX (and XeLaTeX) this is not controlled by LaTeX but by the font. So to get this fixed with the default font we would have to get this corrected in Latin Modern.

For LuaLaTeX we could consider patching if necessary...

**Comment by FrankMittelbach** [comment]
Patching in in the font loader for lualatex doesn't sound like a viable option but really only a last resort approach so I think the right way here is to report it to the font people in GUST (or TeX Gyre).

For pdfTeX would could add the two or three missing mappings I guess.

**Comment by eg9** [comment]
In pdflatex the missing composites are
```
\v{i} \~{i} \u{i} \={i}
```
which also correspond to Unicode points.

For `j` basically all are missing, but Unicode only has J WITH CARON and J WITH CIRCUMFLEX.

We might provide also the other composites, as good fonts (not including Latin Modern) remove the dot altogether when a combining accent follows, even if there's no precomposed. However, placement is not always correct, but this depends on the font.

If I use Junicode, the LuaLaTeX part looks as follows

![Screen Shot 2023-11-07 at 14 11 41](https://github.com/latex3/latex2e/assets/302839/654e77eb-dfda-497d-a13f-57f7341065df)

Thus it would also make sense to add also `\H{i} \r{i} \H{j} \r{j}` as fonts seem to respect it in (Lua|Xe)LaTeX

![Screen Shot 2023-11-07 at 14 14 41](https://github.com/latex3/latex2e/assets/302839/7b03540d-d84f-4d21-bee0-24e4d64486b0)

The same picture as the first one but with STIX2

![Screen Shot 2023-11-07 at 14 17 30](https://github.com/latex3/latex2e/assets/302839/2e27c8c6-9ab9-4284-9c41-e19b3420edb2)

I guess that whoever wants to use such nonstandard accents will choose a font that correctly supports composite accents. Unfortunately this cannot really be expected. For instance `\.{i}` with Latin Modern has an offset dot (apparently the dotless i has a bad anchor for combining characters)

We should perhaps look better in the code for `\.{i}`: should it produce `i` anyway?

**Comment by josephwright** [comment]
Really needs a font fix: closing.
