### ISSUE TITLE
\graphicspath and trailing /

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#1076]
In the past it was not necessary to have an explicit / at the end of the elements of \graphicspath. As of the latest releases (not sure exactly when or what), it doesn't work unless the / is given. The documentation is not exactly clear on whether it's theoretically required, but since it's always worked before (I think). Trivial example:

```
\documentclass{article}
\usepackage{graphicx}
\graphicspath{{somedir}}
\begin{document}
\includegraphics{somefig}% with or without extension
\end{document}
```
will not find somefig.{jpg,png,pdf} in somedir.

**Comment by josephwright** [comment]
I think this will be the dev release. I know what the reason will be. A bit of work but addressable.

**Comment by josephwright** [comment]
Ah, no, something arising from an earlier change. Anyway, I'll fix.

**Comment by josephwright** [comment]
Note that I’ll fix in expl3

**Comment by josephwright** [comment]
Right, that should sort it: I'll wait for some team colleagues to take a look, and then aim for an `expl3` release before the final LaTeX2e 2023-06-01 one.

**Comment by davidcarlisle** [comment]
@josephwright I've no objection to making this work without a trailing `/` but I'm surprised it worked before, certainly it did not work originally, but perhaps the changes around spaces in filenames added that as a side effect.

`grfguide` uses `/` in all examples and documents that it's `\input@path` syntax which is

https://github.com/latex3/latex2e/blob/develop/base/ltdirchk.dtx#L121

so documented as explicitly needing `/`

**Comment by davidcarlisle** [comment]
I tested this, `\graphicspath{{aaa}}` with no `/` fails in texlive 2020 and older but it has worked since texlive 2021

**Comment by josephwright** [comment]
> @josephwright I've no objection to making this work without a trailing `/` but I'm surprised it worked before, certainly it did not work originally, but perhaps the changes around spaces in filenames added that as a side effect.
> 
> `grfguide` uses `/` in all examples and documents that it's `\input@path` syntax which is
> 
> https://github.com/latex3/latex2e/blob/develop/base/ltdirchk.dtx#L121
> 
> so documented as explicitly needing `/`

I thought that was the case, but couldn't pin it down :)

When I adjusted the `expl3` code recently to avoid duplicating `/` tokens in some cases, I went with relying on '`\input@path` requires a trailing `/`', but I was a bit worried as the `expl3` equivalent doesn't. I can see arguments both ways for a trailing `/`, so switching to code where it's optional seemed a low barrier decision.

**Comment by davidcarlisle** [comment]
the reason it was mandatory in 1993 was to avoid run time checking on how to combine directory and filename, but vms, atari, ... less of an issue now, so it's probably safe to insert a `/`

**Comment by FrankMittelbach** [comment]
If the trailing / was required in the past and documented as requiring it, I wonder if we should make it more flexible if that means runtime checks throughout. The case is special enough in my opinion that a strict syntax is not a problem (and the fact that it worked for a little while neither). Just my 2 cents.

**Comment by FrankMittelbach** [comment]
just looked, making it flexible doesn't see so clostly, so I take it back.

**Comment by josephwright** [comment]
> If the trailing / was required in the past and documented as requiring it, I wonder if we should make it more flexible if that means runtime checks throughout. The case is special enough in my opinion that a strict syntax is not a problem (and the fact that it worked for a little while neither). Just my 2 cents.

My original thinking was it was more effort than it was worth, but then @kberry popped up :) It's only a short loop and a quark test, I think we can live with it.

**Comment by kberry** [comment]
I guess it was my (and your) misfortune to have a need for \graphicspath
during that window when it worked without slashes.

The documentation in grfguide does (did) not unambiguously state that
/'s are required, or that they're optional. Sure, the example there uses
/'s, but that is not the same as a clear statement, one way or the
other. "A list of directories" does not imply trailing slashes are
required. 

So adding a sentence to that description in grfguide would be helpful,
IMHO. Sorry if already done, I didn't check dev sources. --best, karl.

**Comment by josephwright** [comment]
The `expl3` side is fixed and released, and once we finalise LaTeX2e 2023-06-01 this will be sorted: I'm marking fixed-in-dev.
