### ISSUE TITLE
Management of hook env/document/after

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1077]
`\AddToHook{env/document/after}{ <something> }`

is possible, but `<something>` is never executed, of course. No info (lest warning or even error) about this is given. Because I know that I make mistakes, I have in my document

```
\AddToHook{enddocument/end}{%
  \IfHookEmptyTF{env/document/after}{\relax}{%
    \LogHook{env/document/after}%
    \@latex@error{%
      Hook env/document/after not empty!\MessageBreak%
      The hook env/document/after AFTER the END of the document\MessageBreak%
      is never executed. Do not add code to that hook.\MessageBreak%
      Maybe use the earlier hook 'enddocument/end' instead.%
    }{Press Return now to see the content of the hook, which is NOT executed!%
     }%
   \ShowHook{env/document/after}%
   }%
  \DisableGenericHook{env/document/after}%
  }
```

But, of course, if the `\AddToHook{env/document/after}{...}` happens after my `\AddToHook{enddocument/end}{...}` (and `\ActivateGenericHook` of the hook), then the test never sees that.

Thus I would like to either have the kernel to throw an error when trying to use `\AddToHook{env/document/after}{...}`, or have the check placed immediately behind `enddocument/end`, thus no document/package/class can place anything behind it.
(Alternative: Tell me to remember to not make that mistake...)

**Comment by u-fischer** [comment]
It is by design that `\AddToHook` doesn't check if the hook is used at all. Why should it single out `env/document/after`? See also the discussion in https://github.com/latex3/latex2e/issues/835

**Comment by PhelypeOleinik** [comment]
As Ulrike said, it's by design, and it's documented (`lthooks-doc`, section **3.3 Hooks provided by `\end{document}`**):

![image](https://github.com/latex3/latex2e/assets/12678598/f2d7b2f5-99cc-4931-a042-6c278a60fba1)

To forbid using `\AddToHook{env/document/after}{...}`, we would have to explicitly check for that one hook in all usages of `\AddToHook`, making every other hook a bit slower.  I don't think it's a good tradeoff.

**Comment by car222222** [comment]
@PhelypeOleinik But what about the other suggestion? --

have the check placed immediately behind enddocument/end

That would avoid major inefficiency, would it not?

**Comment by PhelypeOleinik** [comment]
@car222222 Yes, it would be minimal (in both cases, really), but then this goes in the direction of the discussion in #835 that Ulrike mentioned:  using `env/document/after` is as wrong as using `cmd/foo/end`:  both are hooks that you can add code to, but will never be executed.  My opinion is to not change.

**Comment by Rimole** [comment]
> \DisableGenericHook{env/document/after}

Yes, good idea! I will just put that quite at the top of my document, issue solved, thank you!
