### ISSUE TITLE
Documentation error: wrong term for font encoding in usrguide.pdf

### ISSUE THREAD

**Issue by gmilde** [latex3/latex2e#1083]
## Brief outline of the bug

The new version of usrguide.pdf adds documentation of the case changing commands.
Following sentence is not fully correct:

> The full range of Unicode UTF-8 input can be supported, with the proviso that at present the characters set up with 8-bit engines match those available in standard input encodings (T1, T2, LGR).

* T1, T2, and LGR are _font_ encodings, not _input_ encodings. 
* LGR it *not* a standard font encoding. (The "encguide" reserves the term "standard font encoding" and provides a strict definitions of compliance.)

Suggestion: change to

> The full range of Unicode UTF-8 input can be supported, with the proviso that at present the characters set up with 8-bit engines match those available in the font encodings T1, T2, or LGR (cf. [encguide.pdf](http://mirrors.ctan.org/macros/latex/base/encguide.pdf)) .

Maybe explain for users that T1, T2, and LGR comprise characters for the Latin, Cyrillic, and Greek script.
Caveat: I did not test, which subset of Cyrillic (T2A, T2B, T2C, X2) is actually supported.

**Comment by FrankMittelbach** [comment]
correct is that all characters from  any "font encoding" (standard or otherwise :-)) that has a corresponding `.dfu` file is supported (provided the font encoding is actually loaded in the document).

**Comment by josephwright** [comment]
I recall now that the switch to full-Unicode for 8-bit engines means that at the _input_ side there's (almost) no restriction, so I've adjusted again to remove the caveat line.
