### ISSUE TITLE
Support tabs in \verb*

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#1085]
## Brief outline of the enhancement

Currently, LaTeX2e treats tabs as spaces generally, but in `\verb*` they remain as normal spaces not visible ones.

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
M\verb*|	|M\verb*| |M * % First is tab, second is space
\end{document}
```

![image](https://github.com/latex3/latex2e/assets/4047173/34d35a63-2c94-4e2f-a259-79d1cb87b0cd)

## Minimal example showing the desired new behaviour

Both should be shown.

**Comment by car222222** [comment]
The behaviour of `\verb*` is weird, but I guess that no one cares about it.  

If this needs to change (at this late stage) then a new, good, representation of "visible tab" will be needed. 

A 'true verbatim' treatment of tabs may be useful for some cases, but has anyone ever asked for it?

**Comment by josephwright** [comment]
> The behaviour of `\verb*` is weird, but I guess that no one cares about it.

Yes, it's odd

> If this needs to change (at this late stage) then a new, good, representation of "visible tab" will be needed.

I'm going to push a suggestion shortly: as tabs are normally treated as spaces, I think they should do the same inside `\verb*` so give the 'visible space' *but with a mechanism to alter this*.

> A 'true verbatim' treatment of tabs may be useful for some cases, but has anyone ever asked for it?

Not in the kernel, but it is available for example in `listings`. Moreover, the idea of a change here is to have something consistent between `\verb` and `+v` from `ltcmd`, and I'd like to start with 'something that I feel I can logically document'.

**Comment by FrankMittelbach** [comment]
> The behaviour of `\verb*` is weird, but I guess that no one cares about it.

I guess yes, nobody cares about it (not if it comes to core LaTeX `\verb*` or `verbatim*`). The situation is different though if you look at `listings` or `fancyvrb`. There people do and there is code to handle TABs properly.

> If this needs to change (at this late stage) then a new, good, representation of "visible tab" will be needed.

if you take the position that core LaTeX just treats TAB = space then we don't need a "visible tab" because
TAB --> you meant space, right? --> make a visible space if you are in `\verb*`
 
> A 'true verbatim' treatment of tabs may be useful for some cases, but has anyone ever asked for it?

as Joseph already said, yes a few packages provide proper  support for this for a long time.

--------

I'm fine with interpreting TAB = space in core LaTeX and consider the `\verb*` a defect. It is a breaking change (in theory) for existing documents, but I doubt anybody had added a TAB in `\verb*` to get a space and not a visible space.

**Comment by car222222** [comment]
Done, see Pull Request #1087.

**Comment by muzimuzhi** [comment]
> Done, see Pull Request #1087.

@car222222 PR #1087 is not merged, hence current issue is not fixed (even in dev) yet.

**Comment by car222222** [comment]
@muzimuzhi This is true.

So was I wrong to close this issue?
Or was I just wrong in (maybe) implying that #1087 has been completed (which it has not).

**Comment by muzimuzhi** [comment]
IMO, both. #1087 is not completed, hence current issue should be reopen.

**Comment by car222222** [comment]
Sorry, I had no intention of implying that #1087 had been completed. 

What is the reason for keeping this issue open?

**Comment by FrankMittelbach** [comment]
> What is the reason for keeping this issue open?

@car222222 the team convention is to keep issues upen until we have distributed them at least as a -dev format to CTAN. What we do when something is fixed in dev but not yet distributed is that we mark it with the label "fixed in dev".

**Comment by car222222** [comment]
Nearly there!

**Comment by car222222** [comment]
At last!  

Do we need to add a comment that #1087 is still open?
