### ISSUE TITLE
Rolling back to 2022-11-01 throws error undefined cs `\__hook_post_initialization_defs:`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1088]
## Brief outline of the bug

Rolling back to any date before 2023-06-01 and after 2020-09-30 (both exclusive) reproduces the problem.

The error is not found by the test suite because each of `tlb-latexrelease-rollback-<date>.lvt` doesn't contain `document` environment, but the error is thrown at the beginning of document.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\RequirePackage[2022-11-01]{latexrelease}
\documentclass{article}

\begin{document}
\end{document}
```
throws (using a larger value for `texmf` variable `half_error_line`)
```tex
! Undefined control sequence.
\@expl@@@initialize@all@@ ...ne:Nn \g__hook_used_prop {\iow_term:x {
 ##1 -> \cs_replacement_spec:c {__hook ##1} }}}\__hook_post_initialization_defs: 
                                                                                                                                                      
l.5 \begin{document}
```

## Log file (required) and possibly PDF file  

[rollback-undefined-cs.log](https://github.com/latex3/latex2e/files/11760498/rollback-undefined-cs.log)

**Comment by muzimuzhi** [comment]
Seems the cause is,
- first `\@expl@@@initialize@all@@` is let to `\__hook_initialize_all:` in latex2e 2023-06-01
- then `\__hook_initialize_all:` is rolled back, which leaves `\@expl@@@initialize@all@@` unchanged.

**Comment by josephwright** [comment]
@muzimuzhi  Fancy writing a PR?

**Comment by josephwright** [comment]
Will we need PL1 for this? I guess it means adjusting the `.lvt` files as well as fixing the issue

**Comment by FrankMittelbach** [comment]
> The error is not found by the test suite because each of `tlb-latexrelease-rollback-<date>.lvt` doesn't contain `document` environment, but the error is thrown at the beginning of document.

ah, I wondered why this was not caught. Guess we should update all these rollback tests then to start a bit earlier!

**Comment by FrankMittelbach** [comment]
> Will we need PL1 for this? I guess it means adjusting the `.lvt` files as well as fixing the issue

I guess so, but  we can wait a few days to see if anything else comes up

**Comment by muzimuzhi** [comment]
> @muzimuzhi Fancy writing a PR?

@josephwright Working on it.

**Comment by muzimuzhi** [comment]
BTW, for a short-time workaround, one can use
```tex
\RequirePackage[2022-11-01]{latexrelease}
\ExplSyntaxOn
\cs_gset_eq:cN {@expl@@@initialize@all@@} \__hook_initialize_all:
\ExplSyntaxOff
```
