### ISSUE TITLE
\InputIfFileExists{foo}{\input{bar}}{} loads bar.tex twice, but does not load foo.tex

### ISSUE THREAD

**Issue by gabor-braun** [latex3/latex2e#109]
## Brief outline of the bug
By the documentation of \InputIfFileExists, the following code
```latex
\InputIfFileExists{foo}{\input{bar}}{...}
```
should load bar.tex and then foo.tex if the latter exists.
However, instead it loads bar.tex twice, as can be seen in the log file output below:
`(./bar.tex) (./bar.tex)`.
There should be `(./bar.tex) (./foo.tex)` instead.

## Minimal example showing the bug
foo.tex, bar.tex: empty auxiliary files

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\InputIfFileExists{foo}{\input{bar}}{\message{No foo.}}
\stop
```

## Log file (required) and possibly PDF file  

```log
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=latex 2018.12.21)  7 JAN 2019 15:54
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**test
(./test.tex
LaTeX2e <2018-12-01>
(/usr/share/texlive/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2017/10/12 v1.0d Bug-classification
) (./bar.tex)
(./bar.tex) ) 
Here is how much of TeX's memory you used:
 511 strings out of 493818
 10264 string characters out of 6156362
 59116 words of memory out of 5000000
 4327 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 417 hyphenation exceptions out of 8191
 11i,1n,8p,170b,486s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.
```

## Possible cause of bug

I think the problem is in the definition of \InputIfFileExists:
```latex
\long\def \InputIfFileExists#1#2{%
  \IfFileExists{#1}% 
    {#2\@addtofilelist{#1}\@@input \@filef@und}}
```
The second argument `#2` might redefine `\@filef@und` causing the wrong file to be loaded.
The redefenition can be achieved by eg `\input`, `\IfFileExists` without the use of internal macros.

**Comment by davidcarlisle** [comment]
Thanks for the report, I don't think that has changed since 1993, but your analysis is I think correct.

**Comment by davidcarlisle** [comment]
Not really tested, but I think it may be possible (without breaking existing code) to expand `\file@f@und` before executing `#2`:

```
\begin{filecontents}{\jobname-1}
\typeout{file 1}
\end{filecontents}
\begin{filecontents}{\jobname-2}
\typeout{file 2}
\end{filecontents}

\makeatletter
\long\def \InputIfFileExists#1#2{%
  \IfFileExists{#1}%
    {%
  \expandafter\swap@args\expandafter
  {\@filef@und}{#2\@addtofilelist{#1}\@@input}}}

\def\swap@args#1#2{#2#1}

\InputIfFileExists{\jobname-1}{\input{\jobname-2}}{\message{No \jobname-1.}}

\stop
```

**Comment by gabor-braun** [comment]
The fix looks good to me.

**Comment by FrankMittelbach** [comment]
well, \swap@args is probably better \long

**Comment by aminophen** [comment]
Is the author of filehook.sty (Martin Schar­rer) aware of the change in \InputIfFileExists?

```
! Package filehook Error: Detected unknown definition of \InputIfFileExists.
Use the 'force' option of 'filehook' to overwrite it..
```

I hope filehook.sty will be updated before the new LaTeX release.

**Comment by josephwright** [comment]
He's been tipped off: I believe an update should be available.

**Comment by aminophen** [comment]
@josephwright Thanks ;-)
