### ISSUE TITLE
\input with pipes gives file not found error

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#1092]
## Brief outline of the bug

Input commands using the pipe operator no longer work

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{book}
\begin{document}
\input{|kpsewhich article.cls}
\end{document}
```

This compiles e..g in texlive 2022 and prints 

![image](https://github.com/latex3/latex2e/assets/4047173/397f3ece-1ecc-4076-920f-5e6135e54ae6)

With the new LaTeX it errors:

~~~~
! LaTeX Error: File `|kpsewhich article.cls' not found.
~~~~

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/11770275/test-utf8.log)

**Comment by josephwright** [comment]
I can see why: using file size doesn't work for things that are not files. I guess we could query the first character of the 'name' and branch?

**Comment by dbitouze** [comment]
> I guess we could query the first character of the 'name' and branch?

Ignoring leading spaces?

**Comment by u-fischer** [comment]
Yes probably. How would one use pipes on the L3 level?

**Comment by josephwright** [comment]
@u-fischer E.g. `\sys_get_shell:nnN`.

**Comment by fmitha** [comment]
This is failing again with the dev versions of PDFLaTeX and LuaLaTeX here, namely `pdflatex-dev` and `lualatex-dev`. I tested with Ulrike's example code. The usual `pdflatex` and `lualatex` still work.

I'm getting

    ! LaTeX Error: File `|kpsewhich article.cls' not found.

as before. LaTeX is reporting the version as

    LaTeX2e <2023-11-01> pre-release-0 (develop 2023-6-21 branch)
    L3 programming layer <2023-06-16>

**Comment by muzimuzhi** [comment]
@fmitha The fix for current issue, commit d5a057995541eb1c8c3f8fa65d09f4e2af6c3610, is only contained in [2023-06-01 patch level 1](https://github.com/latex3/latex2e/releases/tag/release-2023-06-01-PL1), not in [2023-11-01 pre-release-0](https://github.com/latex3/latex2e/releases/tag/dev-2023-11-01-0). It would be contained in the next dev release.

I don't know if the convention is to update dev version every time when a patch level release is out, so latest dev always not lags behind (latest) PL release.

**Comment by FrankMittelbach** [comment]
> I don't know if the convention is to update dev version every time when a patch level release is out, so latest dev always not lags behind (latest) PL release.

it depends. The problem is that making a release of something as big as LaTeX means a sizeable amount of work for a number of people: the LaTeX team, the CTAN team and finally the TeXLive distribution team. For that reason, dev sometimes lags behind.

**Comment by josephwright** [comment]
Normally, I only do a  pre-release when there is something 'substantive' in the piperline, other than for PR0 as that matches the first main release. If there is some significant blocker, we look at this, but the issues here don't prevent most testing.
