### ISSUE TITLE
LaTeX2e wrapper for `\exp_args_generate:n`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1097]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

LaTeX2e 2022-06-01 adds `\ExpandArgs{<spec>}` which expands to `\exp_args:N<spec>` if the latter is already defined. But there're cases when the expected/required `\exp_args:N<spec>` function is not yet defined.  Providing a LaTeX2e wrapper for `\exp_args_generate:n` can make `\ExpandArgs` more powerful.

Since `\ExpandArgs` itself is expandable (although `\exp_args:N<spec>` may be unexpandable if `<spec>` contains `x`) and the action to generate new `\exp_args:N<spec>` functions is unexpandable, the task has to be done by a new (user) command.

- About name: I don't have a good name for the new command. `\NewArgsExpander`? At least starting from `\New...` is not a bad idea.
- About syntax: `\exp_args_generate:n` accepts a clist of `<spec>`, but perhaps we want the new command to accept only a single `<spec>` at a time.

## Minimal example showing the desired new behaviour

I did encounter the restriction of `\ExpandArgs` before but can't recall it now... . One (poor) example is, `\exp_args:Neo` is undefined but a proper use case for it is not made up yet.

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here
  % TODO

\begin{document}

  % Demonstration of issue here
  % TODO
  
\end{document}
```

**Comment by josephwright** [comment]
We have discussed this and feel that at the document level this is overkill. The vast majority of cases are already covered, and for those that are not, the user can step into `expl3`.
