### ISSUE TITLE
Overlapping text with multicol

### ISSUE THREAD

**Issue by polysyllabic** [latex3/latex2e#11]
## Brief outline of the bug
The final page of a multicols environment winds up with overlapping text when there are forced \columnbreaks on both the penultimate and the final page of the multicols and the columns on the penultimate page are short. If I fill the columns on the penultimate page, the problem does not occur.

[Slightly more context here](https://tex.stackexchange.com/questions/411758/multicol-results-in-superimposed-text-under-some-conditions-how-can-i-avoid-thi)
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[debugshow]{multicol}
\usepackage{lipsum}

\raggedbottom
\raggedcolumns

\setlength\columnsep{0.5in}
\setlength\columnseprule{.5pt}

\begin{document}
\begin{multicols}{2}

\lipsum[4]
% Uncommenting either this rule or the one in the next column
% balances the columns on the last page
%\rule{1pt}{350pt}

\columnbreak

\lipsum[4]

%\rule{1pt}{350pt}

\columnbreak

\lipsum[1]

\columnbreak

\lipsum[4]

\end{multicols}
And some concluding text
\end{document}
```

## Log file (required) and possibly PDF file  
[multicol overstrike.log](https://github.com/latex3/latex2e/files/1657784/multicol.overstrike.log)
[multicol overstrike.pdf](https://github.com/latex3/latex2e/files/1657785/multicol.overstrike.pdf)

**Comment by FrankMittelbach** [comment]
@polysyllabic wil have a look tomorrow (or rather today :-) )

**Comment by FrankMittelbach** [comment]
I attempted a fix but it needs further testing and of course integration into the package eventually. 
I leave this issue open until that is done

See https://tex.stackexchange.com/a/411910/10109

**Comment by FrankMittelbach** [comment]
should now be fixed in the development sources and will update with the next ctan release in spring.
