### ISSUE TITLE
ltluatex: add more info on 'kerning' and 'ligaturing' callbacks

### ISSUE THREAD

**Issue by lemzwerg** [latex3/latex2e#1111]
`ltluatex.dtx` should mention that the 'kerning' and 'ligaturing' callbacks only have an effect on kerning and ligaturing, respectively, if 'luaotfload' is using `mode=base` for rendering.

See https://tug.org/pipermail/luatex/2023-July/007844.html for more.

**Comment by zauguin** [comment]
I don't think that this should be in ltluatex.dtx, since it's a part of ltluatex but of luaotfload. In other formats ltluatex is sometimes used without luaotfload, so there it would be misleading.

Closing in favour of the linked luaotfload issue.
