### ISSUE TITLE
ltluatex: Wrong type for `post_mlist_to_hlist_filter`?

### ISSUE THREAD

**Issue by lemzwerg** [latex3/latex2e#1116]
Comparing the implementation of ltluatex with optex, I see that the former has [type 'list' for `post_mlist_to_hlist_filter`](https://github.com/latex3/latex2e/blob/develop/base/ltluatex.dtx#L2155), while the latter has ['reverselist'](https://github.com/olsak/OpTeX/blob/master/optex/base/optex.lua#L348).  Looks like a bug in ltluatex...

**Comment by davidcarlisle** [comment]
@josephwright  there was some discussion on this before, which I can't find and it's reversed at

https://github.com/latex3/latex3/blob/8b70fbb7b38137adf461e295772dc82fe258c8ab/texmf/tex/latex/base/ltluatex.lua#L301

I defer to @zauguin

**Comment by zauguin** [comment]
There was some discussion about introducing `reverselist`, but I think `post_mlist_to_hlist_filter` clearly makes sense to have this type. And it used to, but it was accidentally changed back when introducing shared callbacks.

So I restored the type now

**Comment by muzimuzhi** [comment]
Commit 31e606f altered the wrong callback. It should be `post_mlist_to_hlist_filter`, but the (type of) pairing `pre_...` callback was changed instead. I opened #1120 to correct this.

**Comment by zauguin** [comment]
Oops, thanks for catching that.
