### ISSUE TITLE
Suggestion for lthooks manual

### ISSUE THREAD

**Issue by daleif** [latex3/latex2e#1119]
In the lthooks manual it is listed that class/package writers are recommended to use `classname/hookname` and that you can use `.\hookname` for things like `\NewHook` and `\AddToHook` (within the class/package). Additionally it is explicitly mentioned that `./` __cannot__ be used used with say `\UseHook`.

It might be an idea to explicitly mention that it is recommended that class/package writers use say

```
\UseHook{classname/hookname}
```

in their code. If you are just using the manual as a quick reference, it is rather easy to overlook the paragraph after \NewHook

**Comment by FrankMittelbach** [comment]
Well, it is difficult to see where to put that so that it is *not* overlooked. So what I done is to add a marginal note in the section that explains the dot-syntax, hope this solves it for those who overlook the statement  next to each command.

**Comment by daleif** [comment]
I think my intent was more to have a comment with say `\UseHook` saying something like

```
As mentioned earlier, package/class writers are encouraged to use packagename/hookname for naming their hook, and since ./ cannot be used in user land packagename have to be written in full (or stored in  a macro).
```

**Comment by FrankMittelbach** [comment]
and where should that go?

**Comment by daleif** [comment]
I would add it at the start of section 2.1.3. Then that margin note might not be needed.

Of course feel free to rephrase appropriately.
