### ISSUE TITLE
[bm] Problem with \ref and \bm

### ISSUE THREAD

**Issue by ThexXTURBOXx** [latex3/latex2e#1122]
## Brief outline of the bug

When using any kind of reference inside `\bm`, compilation fails.
I noticed this in conjunction with `hyperref`, `cleveref` and `glossaries(-extra)` (both of which use `hyperref`).
However, the same issue also exists using only `\ref`, which can be seen in the MWE.

The reason I need this is because I want to use a math symbol using `\gls{symbolname}`, but it should be bold in some places.
Hence, I would write something like `$\bm{\gls{symbolname}}$` which fails.

It should be mentioned that this issue is fundamentally different from #55 since there, the problem is that `\bm` is used in a section title and not that there is a reference _within_ `\bm`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{bm}

\begin{document}

\section{Test}
\label{sec:test}

$\bm{\ref{sec:test}}$

\end{document}
```

## Log file (required) and possibly PDF file  

[output.log](https://github.com/latex3/latex2e/files/12267441/output.log)

Cannot provide PDF file as it is not generated

**Comment by davidcarlisle** [comment]
as documented in the bm package documentation you need extra `{}` to force `\bm` to drop back to the `\boldsymbol` mechanism which would (more or less accidentally) make nested math expressions bold here, and make the number from ref bold..

```
\documentclass{article}

\usepackage{bm}

\begin{document}

\section{Test}
\label{sec:test}

$\bm{{\ref{sec:test}}}$
${\ref{sec:test}}$


\end{document}
```

**Comment by ThexXTURBOXx** [comment]
Thank you very much, that really did the trick!
I searched for "ref" in the documentation and could only find two occurrences, both of which had nothing to do with this issue.
Maybe, it might be worth documenting?
Anyways, this is not an issue then!

**Comment by davidcarlisle** [comment]
No sorry, there is no code specific to `\ref` and the fact that `\ref` works at all in math mode (never mind inside `\bm`) is mostly by luck not design. It works here as `\ref` is just returning a digit, and digits by default are set upright, but `\ref` could easily return tokens that error, or typeset inappropriately, in math. So I can't list every command that may get used, this is covered by

>% ...   for more  
> % complicated expressions, and anything inside a |{ }| group, |\bm|  
> % forces bold fonts by essentially the same (slow) technique used by the  
> % AMS |\boldsymbol| command

**Comment by FrankMittelbach** [comment]
@davidcarlisle you could perhaps make this slightly clearer by additionally stating something like "If you have an expression that breaks inside `\bm` you can therefore add additional braces around it inside the argument to force `\bm` to use the slow method that has a better chance to succeed." or some such more action oriented statement.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  

> `% \subsection{Strange failures}`
>  .... 
> `% However if some command does fail to work inside |\bm|`   
> `% you should always be able to surround it with an extra set of braces`  
> `% |\bm{{\cmd}}| rather than |\bm{\cmd}|.`

:-)

**Comment by FrankMittelbach** [comment]
If that is already there, then I don't know why it was overlooked by the OP.

but you could still strengthen that with  

However if some command does fail to work inside |\bm| (which can happen for more complicated expressions) ...

**Comment by davidcarlisle** [comment]
`$\bm{\gls{symbolname}}$ `  it would be more natural to not use bm or math and use:  
`{\boldmath\gls{symbolname}}`
