### ISSUE TITLE
showkeys adds extra box level to \@labels box

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#1123]
## Brief outline of the bug

Normally the internal structure of the pending item label box, `\@labels`, does not matter but `amsthm` unboxes it to allow line breaking in, or after, theorem heads. `showkeys` adds the visible `\label` but leaves the original box. This proposes to `\unhbox` so the `\newline` from the theorem style remains at the top level of the box.

First reported by @daleif on sx chat

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsthm}% required to demonstrate issue
\usepackage[notcite,notref]{showkeys}
\newtheoremstyle{mystyle}
{}%
{}%
{\itshape}%
{}%
{\bfseries}%
{.}%
{\newline}% <--- is ignored if showkeys is active
{}%

\theoremstyle{mystyle}
\newtheorem{theorem}{Theorem}


\begin{document}
\begin{theorem}[Our hero]
\label{firstlabel}%
We expect this to start on the next line.
\end{theorem}


\makeatletter
\def\SK@@label#1>#2\SK@{%
  \gdef\SK@lab{\smash{\SK@labelcolor\showkeyslabelformat{#2}}}%
  \ifvmode
    \if@inlabel
      \global\setbox\@labels\hbox{%
        \llap{\SK@lab\SK@lab@relax
              \kern\@totalleftmargin\kern\marginparsep}%
        \unhbox\@labels}%<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< un added
    \else
      \dimen@\prevdepth
      \nointerlineskip
      \ifinner
        \skip@\lastskip\unskip
        \advance\skip@\lastskip\unskip
        \setbox\z@\lastbox
        \ifvoid\z@
          \llap{\SK@lab\SK@lab@relax\kern\marginparsep}%
        \else
          \hbox{\box\z@\rlap{\kern\marginparsep\SK@labx}}%
        \fi
        \vskip\skip@
      \else
        \llap{\SK@lab\SK@lab@relax\kern\marginparsep}%
      \fi
      \prevdepth\dimen@
    \fi
  \else
    \csname SK@\@currenvir\endcsname
    \ifSK@equation\else
      \ifmmode
        \SK@labx
      \else
        \ifinner
          \rlap\SK@lab
      \else
          \vadjust{\llap{\SK@lab\kern\marginparsep}}%
        \fi
        \SK@lab@relax
      \fi
    \fi
  \fi}
\makeatother


\begin{theorem}[Our hero]
\label{secondlabel}%
We expect this to start on the next line.
\end{theorem}

\end{document}
```

## Log file (required) and possibly PDF file  

[gh-showkeys.log](https://github.com/latex3/latex2e/files/12267688/gh-showkeys.log)

**Comment by FrankMittelbach** [comment]
Careful, there have been reasons why you don't want to do this generally. I don't remember the details (it is all long ago), but there is also some discussion around this in enumitem if I remember correctly, and Javier too came to the conclusion that this could be only "optionally" be supported. Could be that in case of amsthm it is the right thing to do, but one would need to verify first why in the general case it is probably not.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  yes I worried about that a bit as well, but here the end result is not that I have unboxed `\@labels` but that I added the showkeys text without adding an extra box around the existing text. So it may be a bit risky that enumitem or amsthm later unbox this but the change here isn't making that more risky

**Comment by FrankMittelbach** [comment]
ah, misread that, yes so your are most likely right.
