### ISSUE TITLE
lthooks documentation typo

### ISSUE THREAD

**Issue by gusbrs** [latex3/latex2e#1124]
## Brief outline of the bug

Currently, `lthooks-doc.pdf` documents the `begindocument` hook as:

> This hook is added to when using \AtBeginDocument and it is executed after the .aux file as be read in and most initialization are done [...]

Isn't it something like "after the .aux file has been read and most initialization"?

**Comment by FrankMittelbach** [comment]
yes thanks. (read or read in should be both correct I think)

**Comment by gusbrs** [comment]
Thanks. I took a look at the commit, and there's still part remaining though: "has been" instead of "as been".

**Comment by car222222** [comment]
Also, this wording would be better:

"This hook is added to by using . . . "

**Comment by FrankMittelbach** [comment]
Not really I think: both are wrong ... the hook is added --- not the hook is added, something is added to the hook

**Comment by FrankMittelbach** [comment]
Yes maybe "added by" but that is only one of the possibilities to add to it, so I guess it should be something like
```
%      This hook is added to by using \cs{AddToHook}\texttt{\{begindocument\}} or
%      when using \cs{AtBeginDocument} and it is
%      executed after the \texttt{.aux} file has been read and most
```

**Comment by car222222** [comment]
Yes, much clearer now.  
But even better  ". . . or by using . . . " :-)!

**Comment by jfbu** [comment]
Maybe worthwile to document somewhere that the "preamble only" restrictions are done *after* the at begin document user added stuff.  So that any redefinition of a "preamble only" LaTeX command done via `\AtBeginDocument` fails.
