### ISSUE TITLE
xparse: Provide command to check if command was defined with xparse

### ISSUE THREAD

**Issue by ysalmon** [latex3/latex2e#1125]
## Brief outline of the enhancement

xparse (integrated into the Latex2e format) provides commands (inter alia ``\GetDocumentCommandArgSpec``) to get the argument specification of an xparse-defined command. Of course these fail on commands defined with ``\newcommand`` or ``\def``.

However, there does not seem to be an official way for a package to detect whether a command was defined with ``\NewDocumentCommand`` or otherwise. This makes it difficult to implement the following use case : where we need the argspec of a command (because we're doing hackery with it), we want to get it automatically from xparse when possible, and have to request it through an optional parameter when it is not ; we therefore want to emit an error when a command is not xparse-defined and an argspec was not given "by hand".

Internally, ``\GetDocumentCommandArgSpec`` uses ``\__kernel_cmd_if_xparse:NTF``, which seems to fit that need exactly, but is not part of the documented interface.

I propose it be added, maybe as ``\IfDocumentCommandIsXparseTF`` or ``\IfCommandIsDocumentCommandTF``, or some variation.

Of course the same applies to environments.

**Comment by josephwright** [comment]
We have discussed this and as you'll see feel that `\GetDocumentCommandArgSpec` was sending the wrong message: it's suggesting programmers rely on implementation detail. As such, we are removing it in the next release and will not be providing a mechanism to tell if commands come from `ltcmd`.
