### ISSUE TITLE
longtable handles the strut at the begin of p-columns differently than array

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#1128]
## Brief outline of the bug

In general `longtable` follows `array` usage but didn't implement the change in array (in 1992) to use `\everypar` for the strut at the begin of p-columns. 
This means that code at the begin of a p-column is handled differently to tabular.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{longtable,color,array}
\LTleft=\parindent
\begin{document}

\begin{tabular}{lp{1cm}}
\hline 
color & \color{red}xxx
\end{tabular}

\begin{longtable}{lp{1cm}}
\hline 
color & \color{red}xxx
\end{longtable}

\begin{tabular}{lp{1cm}}
\hline 
medskip & \medskip xxx
\end{tabular}

\begin{longtable}{lp{1cm}}
\hline 
medskip & \medskip xxx
\end{longtable}

\begin{tabular}{lp{1cm}}
\hline 
par & \relax\par xxx
\end{tabular}

\begin{longtable}{lp{1cm}}
\hline 
par & \relax\par xxx
\end{longtable}

\end{document} 
```

![image](https://github.com/latex3/latex2e/assets/4047173/4bf68914-4a62-46f4-80bf-055282ff88bd)

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/12438490/test-utf8.log)

**Comment by muzimuzhi** [comment]
This issue can/should be closed.

The fix (#1129) for it is merged 2 days ago hence will be part of the coming Fall 2023 release.
