### ISSUE TITLE
mark values are not correct after forcing columnbreak in multicol

### ISSUE THREAD

**Issue by Sophanatprime** [latex3/latex2e#1130]
## Brief outline of the bug

Update mark after using `\columnbreak`, the value of `\botmark` is not correct.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{multicol}
\makeatletter
\def\@oddhead{\firstmark\hfil\botmark}
\let\@evenhead\@oddhead
\begin{document}

\begin{multicols}{2}
A. \mark{{.}{A}}

\columnbreak % remove this, head will be correct

B. \mark{{.}{B}}
\end{multicols}

\end{document}
```

## Log file (required) and possibly PDF file  
[demo.log](https://github.com/latex3/latex2e/files/12494706/demo8.log)

## My understanding

According to my understanding, `multicol` is using `\get@keptmarks` to extract marks, if the vbox contains a force-break and a mark after this, then the mark would lost.

**Comment by u-fischer** [comment]
You are using primitive (TeX) mark commands which shouldn't be used because of such problems. See ltmarks-doc.pdf for a discussion of suitable LaTeX interfaces.  An example with a new mark class:

~~~~
\documentclass{article}
\usepackage{multicol}
\makeatletter
\NewMarkClass{mymarkclass}
\def\@oddhead{\FirstMark{mymarkclass}\hfil\LastMark{mymarkclass}}
\let\@evenhead\@oddhead
\begin{document}

\begin{multicols}{2}
A. \InsertMark{mymarkclass}{{.}{A}}

\columnbreak %

B. \InsertMark{mymarkclass}{{.}{B}}
\end{multicols}

\end{document}
~~~~

**Comment by Sophanatprime** [comment]
@u-fischer Is `multicol` now support mark class? I ran your code after updating all my packages and still got the wrong head.
Actually, it was when I tried to write some patches for `multicol` to let it support the mark class that I found the feature.
Now Frank labels this "work as designed", I just take it as a feature.

**Comment by u-fischer** [comment]
@Sophanatprime  I get the expected header A B from my example:

![image](https://github.com/latex3/latex2e/assets/4047173/f36e421e-082f-47e4-9a44-f91c5e2620d1)

Apart from this: if you think that you found a bug in multicol you shouldn't try to patch it but make a proper bug report which uses the LaTeX interfaces and not low-level TeX commands.

**Comment by Sophanatprime** [comment]
I'm afraid what you've got is the body, not the head. I am sorry to make them so similar.
I use these codes but I have no head.
```tex
\documentclass{article}
\usepackage{multicol}
\makeatletter
\NewMarkClass{mymarkclass}
\def\@oddhead{\FirstMark{mymarkclass}\hfil\LastMark{mymarkclass}}
\let\@evenhead\@oddhead
\begin{document}

\begin{multicols}{2}
A. \InsertMark{mymarkclass}{1}

\columnbreak %

B. \InsertMark{mymarkclass}{2}
\end{multicols}

\end{document}
```

> Apart from this: if you think that you found a bug in multicol you shouldn't try to patch it but make a proper bug report which uses the LaTeX interfaces and not low-level TeX commands.

I read the `ltmarks.dtx` and it reads
<img width="699" alt="image" src="https://github.com/latex3/latex2e/assets/55335597/14beb64c-66c6-43e0-a5dc-46242d5abe11">
It looks like supporting `multicol` is undone, so I just try to write my own patches before LaTeX updates. (And another function the patch is making `multicol` in a box still can get the right marks.)

**Comment by u-fischer** [comment]
ah right, sorry I had forgotten that multicol still needs an update.

**Comment by FrankMittelbach** [comment]
> Now Frank labels this "work as designed", I just take it as a feature.

that was related to using the low-level TeX comments, there aren't supported and have never been (or say only in the sense that you use them through LaTeX interfaces. However, you are right that multicol is not yet supporting the new extend mark mechanism (which it eventually will).

**Comment by FrankMittelbach** [comment]
given that multicol still needs to be updated, I keep this open to remind me of that.

**Comment by FrankMittelbach** [comment]
I now put an update into the development branch, so it should show up with the next distribution of latex-dev and eventually with 2024-06 (or earlier in a tools bundle release if there is one).

What remains doing is to provide support for the new mark mechanism in multicols.
