### ISSUE TITLE
Outdated definition of T1 \k (in example)

### ISSUE THREAD

**Issue by ivankokan** [latex3/latex2e#1148]
https://github.com/latex3/latex2e/blob/de8ca4a2b3a982055a7ccee9556901024d2a2c98/base/doc/fntguide.tex#L1462-L1467

The definition is not up-to-date. Not really important but still...

On top of this, I was looking at L7x which uses the former definition:
```latex
\DeclareTextCommand{\k}{L7x}[1]{\oalign{\null#1\crcr\hidewidth\char12}}
```

Should the L7x maintainers consider updating their definition as well?

**Comment by FrankMittelbach** [comment]
Can't remember the reason why we changed to `\hmode@bgroup`all over the place, but it must have been because of some bug. So yes I think any other encodings should follow too.

**Comment by ivankokan** [comment]
True indeed: a0c7180, the initial commit here already uses `\hmode@bgroup`.

**Comment by ivankokan** [comment]
> Can't remember the reason why we changed to `\hmode@bgroup`all over the place, but it must have been because of some bug. So yes I think any other encodings should follow too.

It seems that many other encodings are affected (T2A, T2B, T2C, but the list goes on - based on my complete TeX Live 2023 installation), and it might be that other commands (not only `\k`) should be treated as well.

Not sure how to proceed with this, it might be tedious to address all maintainers individually (@yannis1962 for L7x is one of them, will this mention reach him?).

**Comment by FrankMittelbach** [comment]
I'll keep this open because at some point we want to fix the T2 encodings too ... but not for this release.

**Comment by FrankMittelbach** [comment]
> Not sure how to proceed with this, it might be tedious to address all maintainers individually (@yannis1962 for L7x is one of them, will this mention reach him?).

This is tedious, I know. But if these things should get fixed that is about the only way to proceed. I have now done it for Cyrillic (will show up in the next release), but I'm not going to look after other third-party encodings --- too many other topics to look after. And we can't really track them here either.
