### ISSUE TITLE
\PrependToHook

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#1156]
## Brief outline of the enhancement

The reverse status only applies to labels.
`\PrependToHook` would allow to apply the concept at the code chunk level

```
\NewReversedHooks{A}{B}
\AddToHook{A}{<A_1>}
\PrependToHook{B}{<B_1>}
...
\AddToHook{A}{<A_2>}
\PrependToHook{B}{<B_2>}
```
would result in A containing <A_1><A_2> and B containing <B_2><B_1> 

Of course the same effect can be achieved with private rules, but this would expose implementation details and pollute significantly the state for no good reason.

**Comment by PhelypeOleinik** [comment]
It kinda makes sense one would want to do that. However, one label is supposed to be used by one package only, and within that package, the package writer should have (in theory) complete control over the order of the code, so prepending should be (in theory) unnecessary.

However, I think the main reason that doesn't exist, it that it passers the wrong message: the idea of lthooks is to solve problems of code ordering by using the sorting rules. Doing that, you are back to the ordering issues. Furthermore, you can easily do what you want by creating a new code label, then using a rule `\DeclareHookRule{<hook>}{mypkg/before}{before}{mypkg}`.

Maybe others think differently, so thoughts are welcome.

**Comment by jlaurens** [comment]
@PhelypeOleinik you forgot to mention that the idea of lthooks is also to solve _reverse_ code ordering issues. And what I am asking for concerns reverse code ordering.

Here is an example of what I have used in practice, `<...>` denotes some package name
```
\tl_new:c { g__my_package_env/<...>/begin_tl }
\tl_new:c { g__my_package_env/<...>/end_tl   }
...
\tl_gput_right:cn { g__my_package_env/<...>/begin_tl } {<A_1>}
\tl_gput_left:cn  { g__my_package_env/<...>/end_tl   } {<B_1>}
...
\tl_gput_right:cn { g__my_package_env/<...>/begin_tl } {<A_2>}
\tl_gput_left:cn  { g__my_package_env/<...>/end_tl   } {<B_2>}
...
\tl_gput_right:cn { g__my_package_env/<...>/begin_tl } {<A_3>}
\tl_gput_left:cn  { g__my_package_env/<...>/end_tl   } {<B_3>}
...
\exp_args:Nnv \AddToHook { env/<...>/begin } { g__my_package_env/<...>/begin_tl }
\exp_args:Nnv \AddToHook { env/<...>/end   } { g__my_package_env/<...>/end_tl   }
```
With hooks, it is a less verbose but evidently slower:
```
\NewMirroredHookPair{./private/env/<...>/begin}{./private/env/<...>/end}
\AddToHook{env/<...>/begin}{\useHook{./private/env/<...>/begin}}
\AddToHook{env/<...>/end}  {\useHook{./private/env/<...>/end}}

\AddToHook{./private/env/<...>/begin}[1]{<A_1>}
\AddToHook{./private/env/<...>/end}  [1]{<B_1>}
...
\AddToHook{./private/env/<...>/begin}[2]{<A_2>}
\AddToHook{./private/env/<...>/end}  [2]{<B_2>}
...
\AddToHook{./private/env/<...>/begin}[3]{<A_3>}
\AddToHook{./private/env/<...>/end}  [3]{<B_3>}
...
```
The solution I see with rules is:
```
\AddHookRule{env/<...>/begin}{./1}{before}{./2}
\AddHookRule{env/<...>/end}  {./1}{before}{./2}
\AddHookRule{env/<...>/begin}{./2}{before}{./3}
\AddHookRule{env/<...>/end}  {./2}{before}{./3}
...
\AddToHook{env/<...>/begin}[./1]{<A_1>}
\AddToHook{env/<...>/end}  [./1]{<B_1>}
...
\AddToHook{myPackage/env/<...>/begin}[2]{<A_2>}
\AddToHook{myPackage/env/<...>/end}  [2]{<B_2>}
...
\AddToHook{myPackage/env/<...>/begin}[3]{<A_3>}
\AddToHook{myPackage/env/<...>  /end}[3]{<B_3>}
...
```
This goes against the weak rule Phelype has mentioned for public hooks: one package, one label.

Compare all this with
```
\AddToHook    {env/<...>/begin}{<A_1>}
\PrependToHook{env/<...>/end}  {<B_1>}
...
\AddToHook    {env/<...>/begin}{<A_2>}
\PrependToHook{env/<...>/end}  {<B_2>}
...
\AddToHook    {env/<...>/begin}{<A_3>}
\PrependToHook{env/<...>/end}  {<B_3>}
```

The other solutions with hooks execute much more code than fundamentally necessary.
Also, if you consider that codes might be added to hooks conditionally, or that code addition can be reordered while refactoring, you can see that what I am asking for much more powerful than the other solutions.

I also have the impression that the implementation of such a feature does not cost that much, more than a simple copy paste of course but a piece of cake for one who knows its matter.

**Comment by FrankMittelbach** [comment]
We have thought about such a command and decided against it.  

The normal/intended situation is that package that have hooks in their code have them to allow other packages to add code in this place. For that \PrepToHook is not needed and in fact strongly giving the wrong message. This is starting to look then as if you have ordering possibilities that you should use in your code and that is precisely not what we want to offer. It would probably even give people the idea that in that case you can prepend code to foreign labels "just to solve a problem".

If these hooks are used to add package code into their own hooks then it is not complicated to to that in one go (or if necessary order the addition with in the package).

Using  \AddToHook with the same hook and the same label twice is something that has to have a reaction. We could have made it an error (which would perhaps have been the cleanest solution), but we decided that appending (within package code) is "ok". If you then look at the hook usage for one label within the package you can immediately see the order of the code.  With "add" + "pre" it becomes quitely blury.

For your use case I would not suggest to use several labels and order those (that is indeed inefficient). If you really would want to build the hook code yourself in bits and pieces because it is really complicated to build, I would do it in a separate tl and at the very end add the content of that tl into the hook under one label.

**Comment by u-fischer** [comment]
Sorry but like Frank I don't think that we should do this. You are showing here examples with only a small number of hook chunks added only by one package. There the order you get can still be explained, but already with your example with the three hooks I have difficulties to visualize which order you get if someone adds a rule, and I can't imagine what should happen if various packages add various hooks with both variants and then add rules.  

Generally I think hooks should be viewed as code where the chunks can more or less be executed in arbitrary order (with the exception of connected begin/end rules where you typically want mirroring) and rules should be used only sparingly to resolve a problem between two independant packages. If you fine tune your own code with lots of rules you are imho doing something wrong.

**Comment by jlaurens** [comment]
Thanks for these very interesting answers with very good points. Unfortunately I also see a significative amount of subjectivity, which is not very convincing. Anyways, the actual documentation misses many of the important points mentioned above.

I am not very fond of the "bad message sent" argument. For me, this kind of arguments  is a direct consequence of an incomplete documentation. In particular, the documentation misses an explicit "good practice" point of view that is clearly pointed out.

Here is how I see the LaTeX hooking management system: we all know <hooks>, <labels>, <code chunks> and <rules>.
I explicitely add some explicit usage limitations (one time hooks are a bit different)

1. a hook can be either private or public
2. private hooks are entirely managed by only one object (document, class, package, class, possibly an ecosystem).
3. Explicit modification or use of private hooks by 3rd party is not supported (and should never occur in production code).
4. one public hook, one semantics
5. the semantics of a public hook is defined by one object, the "owner" of the hook
6. the `\UseHook` consumer can be a package, a class or a document, before or after the preamble.
7. Some public hooks allow 3rd party to `\UseHook`
8. Some public hooks do not allow 3rd party to `\UseHook` (and this should never occur in production code)
9. all labels in public hooks are de facto public
10. one label of one given hook is "owned" by only one object,
11. Modification of labeled code chunk by 3rd party is not supported (and should never occur in production code).
12. one owner can own different labels of the same hook (for less circular rules)

Anymore usage limitations?

I still have some little problem with `\AddToHook` because it serves 2 different purposes with very different semantics
1. add a key/value to a property list
2. modify a value of a property list
This is the chosen design. In the actual state of the documentation, it already allows anyone to modify the code chunk for any label by appending some code, thus already "sending a bad message". Allowing to prepend code is not different.
Anyways, I understand that adding a `\PrependToHook` feature does not worth the cost, but the documentation should definitely be amended to compensate.

Finally, are there official plans to write a better documentation ?

Additional remarks:

- what people do with their own private hooks is private. If they find that using rules to fine tune their code is better, nothing wrong here. 
- If the code chunk for a label is intrinsically complex, the source code will be "blury", whether you use `\tl_put_left...` and `\tl_put_right...` or `\PrependToHook` and `\AddToHook`. The only difference is, at first glance, that the latter is shorter and easier to read.
- A `\AddToHook` after a similar `\AddToHook` could have been designed to be a replace action instead of an append action. This is not the case, no need to discuss more.

**Comment by josephwright** [comment]
The team have discussed this and our view is that this is really a documentation issue. Inside a package, adding to a 'hook' is entirely under the control of the code author, and so does not need the hooks mechanism. It is only interaction _between_ packages where the hook system comes in, and there we really do not want to suggest any ordering beyond explicit rules.

I note there are two other open issues about documentation (#410 and #1155): we feel that the necessary material will be covered in addressing those.
