### ISSUE TITLE
command \verb and package verbatim

### ISSUE THREAD

**Issue by AntoineLatex** [latex3/latex2e#1160]
##  VERBATIM package and new implementation for the \verb command.
It seems the VERBATIM PACKAGE (that I'm using for its 'comment' environment) has to be updated. 
Since new implementaton for \verb command in the kernel (ltnews38) If loaded, \verb has the same behaviour as \verb*

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass[]{article}

\usepackage{verbatim}   % Bug disappears if non loaded

\begin{document}


Hello,

\verb*=starred verb command=

\verb=NON starred verb command= 

If package VERBATIM loaded, the non starred command produces visibles spaces too.


\end{document}
```

## Log file (required) and possibly PDF file  

[testVerbatim.log](https://github.com/latex3/latex2e/files/13257118/testVerbatim.log)
[testVerbatim.pdf](https://github.com/latex3/latex2e/files/13257120/testVerbatim.pdf)

**Comment by davidcarlisle** [comment]
Thank you for the report, we'll sort out a fix and update ctan.

**Comment by muzimuzhi** [comment]
After merge of PR #1136, `\@vobeyspaces` set both space and tab (through `\@vobeytabs`) to active chars and in `\@@sverb` `\@setupverbvisiblespace` is called if any of space or tab is active.

`verbatim` package overwrites `\@vobeyspaces` which then make the catcode check in `\@@sverb` always true, hence `\@setupverbvisiblespace` is always called.
https://github.com/latex3/latex2e/blob/2e8322164b5b50ffb92d3a9ac5b6b287fb5909aa/base/ltmiscen.dtx#L1259-L1270
https://github.com/latex3/latex2e/blob/2e8322164b5b50ffb92d3a9ac5b6b287fb5909aa/base/ltmiscen.dtx#L1630-L1637

An aggressive proposal is to drop [redefinition of `\@vobeyspaces`](https://github.com/latex3/latex2e/blob/2e8322164b5b50ffb92d3a9ac5b6b287fb5909aa/required/tools/verbatim.dtx#L545-L556) in `verbatim` package, either unconditionally or only when LaTeX2e format date is at least 2023-11-01.

A softer change would be to add `\@vobeytabs` to `\@vobeyspaces` if format date is at least 2023-11-01.

```tex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{verbatim}

\makeatletter
{\catcode`\ =\active%
  % \IfFormatAtLeastTF needs latex2e 2020-10-01 or newer
  \@ifl@t@r\fmtversion{2023-11-01}%
    {\gdef\@vobeyspaces{\catcode`\ \active\let \@xobeysp\@vobeytabs}}% new def
    {\gdef\@vobeyspaces{\catcode`\ \active\let \@xobeysp}}% old def
}
\makeatother

\begin{document}
\verb*=starred verb command=

\verb=NON starred verb command=

% test tabs and spaces
\verb|xtab	tab,sp sp|

\verb*|tab	tab,sp sp|

\begin{verbatim}
space space
xtab	tab
\end{verbatim}

\begin{verbatim*}
space space
xtab	tab
\end{verbatim*}
\end{document}
```

![image](https://github.com/latex3/latex2e/assets/6376638/cef66420-6755-40b7-bdf1-dadd53c64f0a)

**Comment by josephwright** [comment]
Both suggestions look reasonable to me: who wants to take this?

**Comment by FrankMittelbach** [comment]
implemented in main and develop. Will be distributed during the next days

**Comment by muzimuzhi** [comment]
It seems to me this issue can be closed with appropriate label added, as it has been fixed in `verbatim` v1.5v (2023-11-06) shipped with release [`tools-2023-11-01c`](https://github.com/latex3/latex2e/releases/tag/tools-2023-11-01c).

**Comment by daleif** [comment]
I was wondering while you are fixing `\verb*` vs TABs and fixing the concompatability in the `verbatim` package. Why not also fix `\verbatiminput*` in the `verbatim` package. As it sits right now, it only marks sapces not TABs, so its behaviour is not compatible with `\verb*`.  

Should I open a separate issue for this?

**Comment by josephwright** [comment]
@daleif  Please do

**Comment by FrankMittelbach** [comment]
@daleif I guess we gladely take a pull request on that one. Otherwise it will most likely become a back burner item.

**Comment by daleif** [comment]
@FrankMittelbach I think the way Peter implemented this (the dtx mentions he took it from somewhere else) is vastly diffent from how `\verb*` is handled in the kernel nowadays. The memoir code is probably from the 200x's

**Comment by daleif** [comment]
This code seems to be enough

```
\def\verbatiminput{\begingroup
\@ifstar{\verbatim@input{\@setupverbvisiblespace\@vobeyspaces}}% <- {...} replaces \relax
{\verbatim@input{\frenchspacing\@vobeyspaces}}}
```

I'll see if I can remember how to do a PR. I'm guessing you guys handle adjustments of version numbers in the dtx
