### ISSUE TITLE
verbatim package makes de non starred version of \verb to function as it were the starred version. -- tools category

### ISSUE THREAD

**Issue by csrabak** [latex3/latex2e#1167]
## Brief outline of the bug

The verbatim package makes de non starred version of \verb to function as it were the starred version.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}

\documentclass{article}

\usepackage{verbatim}


\begin{document}

The command \texttt{\textbackslash verb} in this (2023/07/08,
 according the doc) version of \texttt{verbatim} package works as if it were \texttt{\textbackslash verb*}:

Using \texttt{\textbackslash verb}: \verb!This a short excerpt in verbatim mode non starred!.

Using \texttt{\textbackslash verb*}: \verb*!This a short excerpt in verbatim mode starred!.

If the package in the preamble is removed, the normal behaviour of the non starred and starred versions of the command is restored.
 

\end{document}
```

## Log file (required) and possibly PDF file  
[verb-test.log](https://github.com/latex3/latex2e/files/13290084/verb-test.log)
[verb-test.pdf](https://github.com/latex3/latex2e/files/13290085/verb-test.pdf)

**Comment by u-fischer** [comment]
see https://github.com/latex3/latex2e/issues/1160

**Comment by FrankMittelbach** [comment]
fix will show up in a couple of days in the distributions.
