### ISSUE TITLE
testphase package "tables" incorrectly called "tabular" in ltnews38

### ISSUE THREAD

**Issue by mbertucci47** [latex3/latex2e#1174]
## Brief outline of the bug
ltnews38 contains the lines
```tex
\DocumentMetadata
{testphase={phase-III,math,tabular}}
```
but the testphase package is called `table`, not `tabular`. The displayed code gives the warning
```
LaTeX DocumentMetadata Warning: LaTeX-lab package 'tabular' not found.
```

**Comment by FrankMittelbach** [comment]
ah, that's true. It as a last minute change to call it table because it just fitx better. but we missed out changing it in ltnews.
