### ISSUE TITLE
error if packages are loaded in a group

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#1185]
## Brief outline of the bug

Packages should not be loaded in a group as this can lead to misbeheaviour that can be hard to detect or understand. As an example hyperref fails with an internal socket error if a group has been opened by mistake: https://github.com/latex3/hyperref/issues/315.

\usepackage and \RequirePackage should check the group level and error directly.

**Comment by clason** [comment]
Sorry to be "that guy", but this broke font packages that conditionally require other packages based on package options (e.g., `notomath`). Is this known, and are there mitigation strategies?

**Comment by u-fischer** [comment]
@clason do you have an example where notomath breaks? I don't a package loaded in a group there.

**Comment by clason** [comment]
```tex
\documentclass{article}
\usepackage[sfdefault]{notomath}
\begin{document}
Test
\end{document}
```

(The `sfdefault` option is what triggers the error.)

**Comment by clason** [comment]
Seems to be this line in `notomath.sty` that is the culprit:
```tex
\ifnoto@sfdefault{\noto@MO{notosans}\else\noto@MO{noto}\fi
```

I don't quite see why, but commenting it out removes the error. (Voodoo debugging at its finest!)

**Comment by clason** [comment]
Oh, of course, that's a typo (missing brace closing the first clause). 🤦 

Thanks for rubber-ducking, and sorry for wasting your time! Looks like this PR is doing its work already ;) I'll notify the maintainer.

**Comment by u-fischer** [comment]
well that is a clear bug in the pakcage. The stray brace after `\ifnoto@sfdefault` shouldn't be there at all, and in earlier versions it would have lead to `### simple group (level 1) entered at line 54 ({)`. Notify the author.
