### ISSUE TITLE
Strange behavior of \ProcessOptions*

### ISSUE THREAD

**Issue by linasstonys** [latex3/latex2e#1186]
## Brief outline of the bug
I noticed that `\ProcessOptions*` acts not as expected in one package. 
This is due to change in [\ProcessOptions* issue](https://github.com/latex3/latex2e/issues/513)
In older TL if option is global (used in `\documentclass`)
then inside package it only evaluate that option  if it declared inside package. Now the behavior is changed.  If you declare
option in style file and do not use `\ProcessOptions` then these options will be processed in other package (in next `\ProcessOptions*` ).
Imagine I use same options for many classes and I put them in separate style file (myoptions.sty) an load it in the class.
There is only one option `\DeclareOption{showbug}{\AtEndOfClass{\IamBug}} `  and in the class file I add `\let\IamBug\empty`. So I expect that at the end of class Tex executes `\IamBug` which will be empty.
But with TL2023 I'll get  "\IamBug undefined error" because **showbug** option
will be executed not in class but at the end of loaded **simplepackage.sty**. 

HERE is the `\ProcessOptions*` responsible macro
```
\def\@xprocess@ptions{%
  \ifx\@currext\@clsextension\else
   \ifx\@classoptionslist\relax\else
    \@for\CurrentOption:=\@classoptionslist\do{%
      \ifx\CurrentOption\@empty\else
       % \@expandtwoargs\in@{,\CurrentOption,}{,\@declaredoptions,}%           TL2019 was this
        \@ifundefined{ds@\detokenize\expandafter{\CurrentOption}}{}{%           % TL2023
          \@use@ption
          \expandafter\let\csname ds@\CurrentOption\endcsname\@empty
        }%
      \fi}%
    \fi
  \fi
```

I know the example looks crazy but think about is it options processing correct now?

## Minimal example showing the bug

**myclass.tex**
```latex
\documentclass[showbug]{myclass}
\begin{document}
aa
\end{document}
```

**myclass.cls**
```
\ProvidesClass{myclass}[]
\RequirePackage{myoptions}
% there was no \ProcessOptions inside myoptions package so \ds@<option name> becomes global
%\input myoptions.sty  will work

\ProcessOptions
\RequirePackage{simplepackage}
\def\normalsize{}
\let\IamBug\empty
\endinput
```

**myoptions.sty**
```
\ProvidesPackage{myoptions}[]
\DeclareOption{showbug}{\AtEndOfClass{\IamBug}}
\endinput
```

**simplepackage.sty**
```
\ProvidesPackage{simplepackage}[]
\DeclareOption{opt2}{\dnothing}
\expandafter\show\csname simplepackage.sty-h@@k\endcsname                  % here it shows ->.
\ProcessOptions*\relax
\expandafter\show\csname simplepackage.sty-h@@k\endcsname                  % here it shows ->\IamBug \expandafter \let \csname unprocessedoptions-\@currname .\@currext \endcsname \relax .
\endinput
```

I attached all these files in a zip
[processoptions.zip](https://github.com/latex3/latex2e/files/13458904/processoptions.zip)

**Comment by davidcarlisle** [comment]
While the behaviour may have changed, I think it was always essentially undefined behaviour as `myoptions.sty` is in error as it declares options it does not process. These may or may have been picked up by a calling class but not in any expected or documented way.

The way to share such code between  classes is to make a file (say `myoptions.def`) that is `\input` then, by definition, any declared options act as if declared by the calling class or package.

I believe this works as you intended

**myclass.cls**

```
\ProvidesClass{myclass} % omit the option, don't use [] if you don't want to give a date)
\input{myoptions.def}
% there was no \ProcessOptions inside myoptions package so \ds@<option name> becomes global
%\input myoptions.sty  will work

\ProcessOptions
\RequirePackage{simplepackage}
\def\normalsize{}
\let\IamBug\empty
\endinput
```

**myoptions.def**

```
\ProvidesFile{myoptions.def}
\DeclareOption{showbug}{\AtEndOfClass{\IamBug}}
\endinput
```

as you commented in a comment `\input{myoptions.sty}` would also sort of work but then the `\ProvidesPackage` is wrong so here I renamed it to `.def` and changed `\ProvidesPackage` to `\ProvidesFile`

Note this is the legacy option handler, for any new code we would recommend using the built in key=value option handler

```
\DeclareKeys{
...
}
.
.
.
\ProcessKeyOptions
```

Which as well as supporting `\documentclass[option=something]` syntax  completely avoids the problematic "option clash" error situation as options in later calls to a package are handled far more gracefully.

see `texdoc clsguide` (`clsguide.pdf` in the base latex release)
