### ISSUE TITLE
Optimise commands produced by \NewDocumentCommand with all-m-type args

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#1189]
As discussed by the team, we have to-date avoided optimised outputs of `\NewDocumentCommand`, but as it is used more widely it would be sensible if all-`m`-type arguments result in simplified results, just `\protected\def\foo#1#2`, as there is no need for any complexity. We likely want to leave _any_ more complex cases as-now.

**Comment by muzimuzhi** [comment]
> We likely want to leave _any_ more complex cases as-now.

It would be very welcome if the case that only the first argument is optional (`o`- or `O`-type) could be optimised too.

That is, optimise cases `o m*`, `O{...} m*`, `+o, (+m)*`, and `+O{...} (+m)*` in addition.

**Comment by josephwright** [comment]
> > We likely want to leave _any_ more complex cases as-now.
> 
> It would be very welcome if the case that only the first argument is optional (`o`- or `O`-type) could be optimised too.
> 
> That is, optimise cases `o m*`, `O{...} m*`, `+o, (+m)*`, and `+O{...} (+m)*` in addition.

I'm not seeing this: you are building up complexity in the setup quite a bit - you _do_ need a separate grabber for an optional argument, so there is nothing like as much gain.
