### ISSUE TITLE
Hook in \@setref

### ISSUE THREAD

**Issue by lstonys** [latex3/latex2e#1195]
Now `\label` has a hook so could `\@setref` have a hook as well? With the ref name argument.

```
\def\@setref#1#2#3{%
  \ifx#1\relax
   \protect\G@refundefinedtrue
   \nfss@text{\reset@font\bfseries ??}%
   \@latex@warning{Reference `#3' on page \thepage \space
             undefined}%
  \else
   \begingroup
   \somehook{#3}%
   \expandafter#2#1\@empty\@empty\@empty\null
   \endgroup
  \fi}
```

**Comment by u-fischer** [comment]
What is the use case?

**Comment by lstonys** [comment]
Ok, I see that I already asked about such a hook in hyperref project https://github.com/latex3/hyperref/issues/250. I usually  redefine both \@setref macros (from kernel and from hyperref).  If you think that this hook is worthless that's fine just close this issue. It is not a big macro to copy and redefine it in the style.
