### ISSUE TITLE
Provide `\NewLengthCopy`?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#1197]
Just as `\NewCommandCopy {⟨cmd⟩} {⟨existing-cmd⟩}` and friends, it would be nice to have a `\NewLengthCopy{⟨length⟩} {⟨existing-length⟩}` command. A typical use case is to have a more straightforward way for:
```latex
\newlength\keptparindent
\keptparindent=\parindent
```
(as to be found in [this answer](https://tex.stackexchange.com/a/115090/18401)).

**Comment by FrankMittelbach** [comment]
the point with copying commands is that they have internal structure that needs to be copied as well, something that isn't true in case of registers, so in LaTeX syntax the above is
```
\newlength\keptparindent
\setlength\keptparindent{\parindent}
...
\setlength\parindent{\keptparindent}
```
An extra declaration form wouldn't gain you much and given that we do not have CamelCase commands for registers it would be odd to provide just this one. Furthermore, in many cases you would want to keep the declaration separate from storing the value at a certain point.

Thus, I don't think we want to provide this.
