### ISSUE TITLE
Should keyval need 2 brace groups to keep spaces?

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#120]
## Brief outline of the bug

I can understand that keyval drops spaces on top-level, but if the value is a brace group I think it should honor that (and not require 2 groups to keep spaces in the value intact).

see also: 
https://github.com/jbezos/enumitem/issues/13#issuecomment-459375590

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\nonstopmode

\usepackage{keyval}
\makeatletter
\define@key{test}{a}{\def\toshow{(#1)}\show\toshow}
\setkeys{test}{a={{; }}, a={; }, a={{ and }}, a={ and }}

\stop

```

## Log file (required) and possibly PDF file  

[keyval-issue.log](https://github.com/latex3/latex2e/files/2817985/keyval-issue.log)

**Comment by davidcarlisle** [comment]
The current brace stripping came about after


https://www.latex-project.org/cgi-bin/ltxbugs2html?pr=graphics%2F3446

Not to say it's right now, just keeping a link to previous discussions.

**Comment by u-fischer** [comment]
Curious, I thought 2014 the code was changed so that `key={{{value}}} ` strips only one brace level, but when I do `\setkeys{test}{a={{{x}}}}` I now get `> \toshow=macro:->({x})`. Where is the second brace? Or is my memory wrong?

**Comment by davidcarlisle** [comment]
I'll need to check the mail log but I suspect there were problems, i
see in the git log


commit 76b3bc935b02efd5d6ed66869e0cb4547269d20e
Author: David Carlisle <d.p.carlisle@gmail.com>
Date:   Thu May 8 17:28:28 2014 +0000

    revert keyval brace change

**Comment by josephwright** [comment]
We had issues as other people were relying on how `keyval` currently strips braces (_cf._ `expl3` where we are extremely careful). I'm not sure we can change anything here.

**Comment by davidcarlisle** [comment]
We actually adjusted this once for

https://www.latex-project.org/cgi-bin/ltxbugs2html?category=LaTeX&pr=graphics%2F3446

But it caused several issues with assorted packages assuming the current level of brace removal so it was backed out again.

**Comment by wspr** [comment]
From discussion above it sounds like keyval.sty needs to remain frozen in this respect. Okay to close this issue?
