### ISSUE TITLE
lthooks: bug with '|' in labels

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#1201]
## Brief outline of the bug

If we use `|` in labels, lthooks internals get fooled when rules are involved.
More precisely `C|A|B` holds for both pairs `C`, `A|B` and `C|A`, `B`.

Label names like `my_module/big&(red|blue)` should not be problematic.

I have patched lthooks to safely accept `|` in label names. The idea is to use `^^J` instead of `|` to store rules, assuming that excluding `^^J` from labels is not a real problem. So far, all checks passed. There is however a supplemental problem when rules are displayed in the terminal: the above `C|A|B` ambiguity remains. I also have a new `\ShowHookInfo` that solves this problem and is somehow better than `\ShowHook`, but this is for another PR.

## Minimal example showing the bug

```latex
\nonstopmode
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
\NewHook{X}
\AddToHook{X}[C|A]{\typeout{C|A}}
\AddToHook{X}[A|B]{\typeout{A|B}}
\AddToHook{X}[B]{\typeout{B}}
\AddToHook{X}[C]{\typeout{C}}
\AddToHook{X}[D]{\typeout{D}}
\DeclareHookRule{X}{A|B}{incompatible-error}{C}
\ShowHook{X}
\UseHook{X}
\end{document}
```
When declaring only one `incompatible-error` rule
```latex
\DeclareHookRule{X}{A|B}{incompatible-error}{C}
```
I would expect only labels `A|B` and `C` to be dropped down.
Instead `C|A` and `B` are also dropped down: the log file reads
```latex.
> Rules:
>     C|A|B with relation xE
>     C|A|B with relation xE
```
## Log file (required) and possibly PDF file  

[2.log](https://github.com/latex3/latex2e/files/13599508/2.log)

**Comment by muzimuzhi** [comment]
> There is however a supplemental problem when rules are displayed in the terminal: the above `C|A|B` ambiguity remains.

Apart from wraping hook label names in braces like how `\clist_show:N` does,
```
Rules:
    {C}|{A|B} with relation xE
    {C|A}|{B} with relation xE
```
I also wonder if `|` is avoidable in `\ShowHook` output.

Currently `|` is used as the separator for hook labels both in implementation and in `\ShowHook` output. If then the separator used in implementation is going to be changed, then there's no necessity to stick to `|` in `\ShowHook`.

Also I find the short names `xE` (`incompatible-error`) and `xW` (`incompatible-warning`) confusing. They are so short and never mentioned in `lthooks-doc.pdf`, hence quite difficult to be understood. Displaying full rule names in log?

Combine the two, I suggest (perhaps the label and/or rule names can take a thin formatting, for instance double-quoted):
```
Rules:
     C and A|B with relation incompatible-error
     C|A and B with relation incompatible-error
```

**Comment by josephwright** [comment]
Supported syntax doesn't include `|`: we will clarify this in the docs (as mentioned in another issue).
