### ISSUE TITLE
utf8 i with ogonek į should be dotted, not dotless

### ISSUE THREAD

**Issue by mvsfrasson** [latex3/latex2e#122]
## Brief outline of the bug

In short: lowercase i with ogonek accent should be dotted, not dotless.

Loading package inputenc with option utf8 triggers loading of file t1enc.dfu, where we find
  \DeclareUnicodeCharacter{012F}{\k\i}
which declares Unicode char U+012F to typeset as *dotless i* with ogonec accent.

Looking in a UTF8 database, like
  https://www.utf8-chartable.de/unicode-utf8-table.pl
we find the following declaration
  U+012F     į     c4 af     LATIN SMALL LETTER I WITH OGONEK

Although UTF8 doesn't tell how to typeset the characters, in my browser's font, it looks like with dot. On a font display like http://libertine-fonts.org/, looking the test applet, į has the dot. I think that LaTeX (with pdfTeX) is typesetting i with ogonek wrong.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}

i with ogonek as utf8 char U+012F (should be \k i): į 
  
\end{document}
```

## Log file (required) and possibly PDF file  

[lixo2.log](https://github.com/latex3/latex2e/files/2833858/lixo2.log)
[lixo2.pdf](https://github.com/latex3/latex2e/files/2833860/lixo2.pdf)

**Comment by FrankMittelbach** [comment]
thanks for the report. and obvious cut and paste error copying the definition from another one that has an accent above.  Will correct.
