### ISSUE TITLE
\IfFileLoadedTF missing

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1222]
## Minimal example showing the current behaviour
pdflatexing

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{document}

\IfFileLoadedTF{l3backend-pdftex.def}{\message{l3backend-pdftex.def has been loaded.}%
}{\message{l3backend-pdftex.def has NOT been loaded.}%
}
  
\end{document}
```

gives `! Undefined control sequence. \IfFileLoadedTF{l3backend-pdftex.def}{\message{l3backend-pdftex.def has...`, 
while `\IfPackageLoadedTF` and `\IfClassLoadedTF` are defined.

## Minimal example showing the desired new behaviour

Define `\IfFileLoadedTF`.

**Comment by muzimuzhi** [comment]
Nice complement to
- #1015

**Comment by josephwright** [comment]
Is there a concrete use case here?

**Comment by FrankMittelbach** [comment]
problem is that most files aren't detected by this approach, you have to have a file that contains a \ProvidesFile line, that is true for some .def files but not for all nor for many .cfg files etc. Which is why I don't really think this is very useful.

**Comment by FrankMittelbach** [comment]
added the commands

**Comment by FrankMittelbach** [comment]
it should, sigh :-) thanks
