### ISSUE TITLE
\DeclareDefaultHookRule does not work

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#1227]
## Brief outline of the bug
`\DeclareDefaultHookRule` has no effect on code chunk ordering

## Minimal example showing the bug

```latex
\nonstopmode
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\NewReversedHook{KOOH}
\AddToHook{KOOH}{\typeout{[TOP LEVEL]}}
\AddToHook{KOOH}[LABEL 1]{\typeout{[code 1]}}
\AddToHook{KOOH}[LABEL 2]{\typeout{[code 2]}}
\AddToHook{KOOH}[LABEL 3]{\typeout{[code 3]}}
\DeclareHookRule{KOOH}{LABEL 3}{before}{LABEL 1}
\DeclareDefaultHookRule{LABEL 3}{before}{LABEL 2}
\ShowHook{KOOH}
\UseHook{KOOH}
\begin{document}
Done
\end{document}
```

The log reads
```
-> The hook 'KOOH':
[...]
> Rules:
>     LABEL 3|LABEL 1 with relation <
>     LABEL 3|LABEL 2 with default relation <
> Execution order (after reversal and applying rules):
>     LABEL 2, LABEL 3, LABEL 1.
```
The execution order is not consistent with the default rule.

## Log file (required) and possibly PDF file  

[2.log](https://github.com/latex3/latex2e/files/13781728/2.log)

**Comment by muzimuzhi** [comment]
From comment for `\g__hooks_??_reversed_tl`, default ordering rules applied to a reversed hook behave reversely. That is, `after` becomes `before` and `before` becomes `after`. Hence in your example,
```tex
\DeclareDefaultHookRule{LABEL 3}{before}{LABEL 2}
% works for hook "KOOH" as if
\DeclareHookRule{KOOH}{LABEL 3}{before}{LABEL 2}
% is set
```

Therefore it seems this is a designed behavior, only not documented.
https://github.com/latex3/latex2e/blob/cc704066a05e5fb1563786558db0cd5f3e91e0ec/base/lthooks.dtx#L4979-L4986

**Comment by car222222** [comment]
@muzimuzhi Did you mean actually to write this?
(`before -> after`) :

`% works for hook "KOOH" as if
\DeclareHookRule{KOOH}{LABEL 3}{after}{LABEL 2}`

**Comment by car222222** [comment]
It is somewhat strange that such reversal gets applied to `\DeclareDefaultHookRule` but *not* to 
`\DeclareHookRule` (for reversed hooks). 

But it is too late to change that by now. 
Thus very clear documentation is needed, probably in several places.

**Comment by muzimuzhi** [comment]
> @muzimuzhi Did you mean actually to write this? (`before -> after`) :
> 
> `% works for hook "KOOH" as if \DeclareHookRule{KOOH}{LABEL 3}{after}{LABEL 2}`

@car222222 Yes, thanks. I've corrected in https://github.com/latex3/latex2e/issues/1227#issuecomment-1870702305.

**Comment by muzimuzhi** [comment]
> It is somewhat strange that such reversal gets applied to
> `\DeclareDefaultHookRule`
> but _not_ to
> `\DeclareHookRule`

`\DeclareDefaultHookRule{<label1>}{<relation>}{<label2>}` is essentially the same as
`\DeclareHookRule{??}{<label1>}{<relation>}{<label2>}`, so what's special is the (general) hook `??`.

https://github.com/latex3/latex2e/blob/cc704066a05e5fb1563786558db0cd5f3e91e0ec/base/lthooks.dtx#L7579-L7589

**Comment by u-fischer** [comment]
> It is somewhat strange that such reversal gets applied to
> `\DeclareDefaultHookRule`
> but _not_ to
> `\DeclareHookRule`
> (for reversed hooks).

Imho it is correct so. `\DeclareDefaultHookRule`  is applied to *all* hooks including hook-pairs, and so it is quite logical that it has to reverse the rule in reversed hooks to keep the mirror ordering. On the other side `\DeclareHookRule` is a rule for a specific hook, and imho it would be strange if you would have to say "after" to get a chunk *before* another only because the hook is a reversed hook (which you perhaps even don't know or would have to look up first.)

> Thus very clear documentation is needed, probably in several places.

Yes one should probably add a few sentences that explain that the order defined by `\DeclareDefaultHookRule` is mirrored in reversed hooks.

**Comment by FrankMittelbach** [comment]
This is precisely the rationale. Default rules are for general relationships and so if everything from package A should be before package B then it is reasonable to reverse that for reversed hooks. A specific rule is a specific hook and it is there to change the order that would otherwise  occur, ie  you look at the final result and change that.  So basically if it needs some more explanation but that's it.

**Comment by jlaurens** [comment]
Actually, using standalone forward hooks or standalone reversed hooks is absolutely the same: if code chunks must be ordered, rules help. The only interest of reversed hooks is within pairs, then you perfectly know that the second hook is reversed, but you can't reorder both hooks independently.

The example of nested environments illustrates the subtleties: consider
```
\documentclass{article}
\newenvironment{ENV}{}{}
\newenvironment{ENV1}{<1>}{</1>}
\newenvironment{ENV2}{<2>}{</2>}
\AddToHook{env/ENV/before}[1]{\begin{ENV1}}
\AddToHook{env/ENV/before}[2]{\begin{ENV2}}
\AddToHook{env/ENV/after}[1]{\end{ENV1}}
\AddToHook{env/ENV/after}[2]{\end{ENV2}}
\begin{document}
\DeclareHookRule{env/ENV/before}{2}<{1}
\DeclareHookRule{env/ENV/after}{1}<{2}
\begin{ENV}X\end{ENV}
\end{document}
```
if you do not balance the rule for the `before` hook with the mirrored rule for the `after` hook, things get broken.
A `\DeclareHookPairRule` would help in that situation.
```
\DeclareHookPairRule{env/ENV/before}{env/ENV/after}{2}<{1}
```
Moreover, any operation on the first hook that changes the order (including code chunk replacement) must be balanced by an appropriate operation on the second hook.

The really interesting information is not that a hook is "implemented as a reversed hook", but what are the balancing hook pairs.

**Comment by jlaurens** [comment]
@u-fischer 
> it would be strange if you would have to say "after" to get a chunk _before_ another only because the hook is a reversed hook

Yet this is exactly what `\ShowInfo` tells us with default rules as illustrated by the minimal example showing the bug.

**Comment by josephwright** [comment]
@FrankMittelbach One for a doc change? Assign to you?
