### ISSUE TITLE
Review non-robust commands in amsmath & kernel

### ISSUE THREAD

**Issue by wspr** [latex3/latex2e#123]
## Brief outline of the bug

There are many macros in the 2e kernel and/or amsmath that are not robust/protected but should be.
This issue report inspired by Enrico: https://github.com/wspr/unicode-math/issues/493

We should review this en masse at some stage.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\listoffigures
\begin{figure}
  \caption{Test caption $i \bmod 64$.}
\end{figure}
\end{document}
```

## Log file (required) and possibly PDF file  

While this compiles without error the .lof file produced is less useful than it could be:

```latex
\contentsline {figure}{\numberline {1}{\ignorespaces Test caption $i \nonscript \mskip -\medmuskip \mkern 5mu\mathbin {\mathgroup \symoperators mod}\penalty 900 \mkern 5mu\nonscript \mskip -\medmuskip 64$.}}{1}% 
```

**Comment by car222222** [comment]
Task: prepare a list of all those in amsmath and add it to amsmath ltodo listl.

**Comment by FrankMittelbach** [comment]
@car222222 and of course check if there are some remaining in the LaTeX kernel itself and prepare a list for that too.

**Comment by car222222** [comment]
Could do yet another trawl through the kernel but it has been done so many times that it is probably better to leave any remaining to surface somehow.

**Comment by blefloch** [comment]
Couldn't we extract automatically a list of all user commands in the
kernel (no @) and produce automatically a list of those that are not robust?

Should \includegraphics be made robust, or are we only talking here
about math commands?

**Comment by josephwright** [comment]
In a word, `\protected`. Really.

**Comment by car222222** [comment]
Very little that is a \protected def in this kernel, not even used by \DeclareRobustCommand !  Unreal !

**Comment by josephwright** [comment]
@car222222 Sure, but we are talking about stuff that would be being changed. Surely adding `\protecgted` is no more invasive than using `\DeclareRobustCommand` (and thus blowing another macro) in these cases.

**Comment by car222222** [comment]
@josephwright Yes, that is the fix.  But we need to find what still needs fixing.  I was thinking, like Bruno, that it may be possible to do automate this but I do not have any insights as to how.  If Will is correct that they are “many” then this may be relatively easy.

**Comment by FrankMittelbach** [comment]
Am 10.02.2019 um 17:09 schrieb Chris Rowley:
> @josephwright <https://github.com/josephwright> Yes, that is the fix. 
> But we need to find what still needs fixing. I was thinking, like Bruno, 
> that it may be possible to do automate this but I do not have any 
> insights as to how. If Will is correct that they are “many” then this 
> may be relatively easy.

Possibly a fairly simple way is to prepare a test file (or several ones) 
that runs a user number of  commands simply inside \typeout

If robust they should basically give reasonable output otherwise those 
would then be the ones that need tackling. And by providing that test 
file (and sticking it into the testfiles of the distribution) would then 
also be a nice way to ensure that their protection stays the way we want 
in future releases).

**Comment by FrankMittelbach** [comment]
Am 10.02.2019 um 08:14 schrieb Bruno Le Floch:
> 
> Should \includegraphics be made robust, or are we only talking here
> about math commands?

first step would be finding all non-robust commands, second step seeing 
if those that aren't can be / should be made robust and yes, I think 
\includegraphics would be a good candidate too

**Comment by blefloch** [comment]
Which packages should we be focusing on?  How to get a full list of
commands?  (One way would be to dump a mylatexformat and find where in
that the string pool sits, it's doable manually but annoying because
there is no indication of where strings end.)

**Comment by car222222** [comment]
There are certainly a lot of non-robust commands in the 2e kernel that could be made robust, but many, maybe most, are not really LaTeX user/document commands, although they can be used in documents.  Some examples: a number of lower-level commands from plain that are used as internal LaTeX commands.  Some plain commands to access symbols or structures that are not documented as LaTeX commands and are not really needed at all.

**Comment by FrankMittelbach** [comment]
@car222222  I've picked up all csnames defined by latex.ltx, fonttext.ltx, fontmath.ltx. They can now easily be tested and we can then decided once that test is in place which should or could be made robust. It is equally simple to do that for amsmath and or other package (from tools) --- not done yet. A new test file documenting the current behavior will come up shortly.

**Comment by car222222** [comment]
Excellent, many thanks.

**Comment by FrankMittelbach** [comment]
2e kernel commands are now all reasonably robust (with a small number of exceptions (noticable in the .tlg file for github-robust-0123). `amsmath` is partly done, the rest will have in the following release. Thus I keep this one open for a while.

**Comment by FrankMittelbach** [comment]
with +801 the remaining part should finally be done. There are a few odds and ends, but they have to wait for another rainy day (if ever).
