### ISSUE TITLE
upquote package has no effect on macrocode environments

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#1230]
## Brief outline of the bug

This is a follow-up to #953, which mentioned `\verb`, `verbatim`,  and `macrocode`.

In ltnews37.pdf it is explained that support for the upquote package was added to the doc package, but only `\verb` and `verbatim` are mentioned.

Indeed, recently when a fellow package author sent me a package.pdf and I saw there curly ticks, I proposed that he should add `\usepackage{upquote}`; the reply came soon (translated) *it does not change anything*.[^1]

The *anything*  is exaggerated but indeed nothing happens in macrocode.  Here is output from minimal example below:

![Capture d’écran 2023-12-29 à 23 09 42](https://github.com/latex3/latex2e/assets/2589111/a9934d78-2a44-4854-ae2d-a3741d97375f)

## Minimal example showing the bug

He was using `ltxdoc` here I use `article` class and `doc` package.

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{upquote}
\usepackage{doc}

\begin{document}
\verb|`Z=`a|

\begin{verbatim}
\lccode`Z=`a
\end{verbatim}

\MakePercentIgnore
%    \begin{macrocode}
\lccode`Z=`a
%    \end{macrocode}
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/13796352/test.log)

## Unrelated typo

Looking in `doc.dtx` to see if some comment was there related to this topic (found only  the `\changes` entry) I accidentally bumped into this which contains seemingly a typo "comands":

```latex
%\RenewDocElement[macrolike = true ,
%		 toplevel  = false,
%                idxtype   = ,
%                idxgroup  = LaTeX comands\actualchar\LaTeX{} commands ,
%                printtype =
%               ]{Macro}{macro}
```

[^1]: in my packages I have since long time often been using monospace fonts where the ticks are straight  anyhow so this problem was long forgotten to me but checking now I see I have a few dtx where code à la  upquote is done but using `\verbatim@nolig@list`.  Edit: which is certainly not the natural location to append ``\let'\textquotesingle\let`\textasciigrave`` now that I re-check the matter, it is only a user hack ir is not the good way, because some third party might expect  `\verbatim@nolig@list` to remain a sequence of `\do` instructions.

**Comment by jfbu** [comment]
In this context I am mentioning here the following fact, which does not seem to be worth a "bug report", it is more perhaps that it could be documented somewhere : in `ltxdoc` class or `article + doc`, one can use `\MacroFont`.  But there is a divergence between `verbatim` and `macrocode`.  The former obeys the current `\MacroFont` configuration, the latter uses the one which was decided in preamble of document.

```latex
\documentclass{article}
\usepackage{upquote}
\usepackage{doc}
\def\MacroFont{\normalfont\sffamily}

\begin{document}

\makeatletter\def\verbatim@font{\bfseries}% works here since LaTeX release 2023-06-01
\verb|`Z=`a|

\def\MacroFont{\normalfont\bfseries\itshape}
\begin{verbatim}
\lccode`Z=`a
\end{verbatim}

\MakePercentIgnore
%    \begin{macrocode}
\lccode`Z=`a
%    \end{macrocode}
\end{document}
```

**Comment by FrankMittelbach** [comment]
> In this context I am mentioning here the following fact, which does not seem to be worth a "bug report", it is more perhaps that it could be documented somewhere : in `ltxdoc` class or `article + doc`, one can use `\MacroFont`. But there is a divergence between `verbatim` and `macrocode`. The former obeys the current `\MacroFont` configuration, the latter uses the one which was decided in preamble of document.

It is documented that `\MacroFont` should only be changed in the preamble or in packages. Your example shows that changing it later has "some weird" effects, but  the input violate the documented interface.

Initially I thought that it should be easy to either prevent verbatim from acting on changes of `\Macrofont` or to allow `\MacroFont` changes throughout. But it turned out that the dependencies are more subtle and that it either would need som major surgery. So I guess I keep it like this with and just strengthened the documentation a bit.
