### ISSUE TITLE
\verbatiminput* from the verbatim package vs TABs

### ISSUE THREAD

**Issue by daleif** [latex3/latex2e#1245]
## Brief outline of the bug

Given that the kernel fixed `\verb*|A<tab>B|` to show the TAB as a space, it would be nice to also make `\verbatiminput*` mark TABs as spaces.

In the PDF we can see the space is marked, but the TAB is not.

## Minimal example showing the bug

First make a file with a tab between two letters, forexample

    A<tab>B<space>C

(`filecontens` converts TABs so cannot be used, and tabs are not shown one the web)

We'll assume the file is called `verb.txt` (I've also attached it below)

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{verbatim}
\begin{document}
\verbatiminput*{verb.txt}
\end{document}
```

## Log file (required) and possibly PDF file  

[verb.txt](https://github.com/latex3/latex2e/files/13960813/verb.txt)

[bug.log](https://github.com/latex3/latex2e/files/13960815/bug.log)

[bug.pdf](https://github.com/latex3/latex2e/files/13960818/bug.pdf)

**Comment by daleif** [comment]
Just playing around a bit, this might be enough

Not sure if there are sideeffects.

```
\documentclass{article}
\usepackage{verbatim}
\makeatletter
\def\verbatiminput{\begingroup
  \@ifstar{\verbatim@input{\@setupverbvisiblespace\@vobeyspaces}}% <-- changed, arg was \relax
          {\verbatim@input{\frenchspacing\@vobeyspaces}}}
\makeatother
\begin{document}
\verbatiminput*{verb.tex}
\end{document}
```

**Comment by FrankMittelbach** [comment]
we normally only close once the fix has reached the main release.
