### ISSUE TITLE
minor doc tweaks to ltfilehook

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#1266]
A few small typo-ish corrections for the ltfilehook doc. For your consideration.
[ltfilehook.txt](https://github.com/latex3/latex2e/files/14224321/ltfilehook.txt)

**Comment by FrankMittelbach** [comment]
thanks .. didn't went in cleanly because I had updated at least one of them last night :-)

**Comment by FrankMittelbach** [comment]
fixed in #1269
