### ISSUE TITLE
source2e documentation footers/ \ProvidesFile of base .dtx

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1267]
source2e documentation source2e.pdf has in its footers text, which for some files looks like this:

`File e: ltexpl.dtx Date: 2023/10/13 Version v1.3g`

because
```
\ProvidesFile{ltexpl.dtx}                                          
             [2023/10/13 v1.3g LaTeX Kernel (expl3-dependent code)]
```
For others files the footer is like this:

`File h: lthooks.dtx`

because no `\ProvidesFile` but
```
\def\lthooksversion{v1.1f}
\def\lthooksdate{2023/10/02}
```
And for still other files it is like this:

`File C: fontdef.dtx Date: ? Version ?`

because just `\ProvidesFile{fontdef.dtx}`

Having all footers use the first format (i.e. all files use `\ProvidesFile{...}[...]`) would be more consistent, but maybe there are reasons against this.

(Also: https://github.com/latex3/latex2e/tree/c1eedbcb1aaac4820a01ec972d25fc5ddc4af500/CONTRIBUTING.md has an "of of" which should be "of", but should I really file a bug report for that?)

**Comment by davidcarlisle** [comment]
I just commited (to the gh1267 branch) a fix for `fontdef.dtx` 

That still leaves the following files that are missing version data for various reasons

```
$ grep XXX source2e.log  | sort | uniq | grep -v Date
XXX: File I: {\ttfamily ltproperties.dtx} 
XXX: File U: {\ttfamily ltmarks.dtx} 
XXX: File Y: {\ttfamily ltfilehook.dtx} 
XXX: File Z: {\ttfamily ltshipout.dtx} 
XXX: File a: {\ttfamily ltdirchk.dtx} 
XXX: File d: {\ttfamily ltluatex.dtx} 
XXX: File h: {\ttfamily lthooks.dtx} 
XXX: File i: {\ttfamily ltcmdhooks.dtx} 
XXX: File j: {\ttfamily ltsockets.dtx} 
XXX: File o: {\ttfamily ltpara.dtx} 
XXX: File p: {\ttfamily ltmeta.dtx} 
```

**Comment by muzimuzhi** [comment]
> Thanks we'll look in to that, I notice C fontdef.ltx is showing a stray latexrelease docstrip guard with the file date as well.

This is exactly the problem reported in #1173. Thank you for addressing it.
