### ISSUE TITLE
Possible source2e improvements

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#1271]
This is a holding issue  preparing to make a branch and PR fixing several unrelated issues in source2e.pdf that have come up while reviewing recent PR

----

## Sort order of files in the code index

the file list uses a-z A-Z aa-zz which is not sorted correctly by makeindex, we could consider using a numeric scheme with a prefix such as 01:100 ... 55:100  (or keep the current aalph numbering scheme a100 .. bb100 but expose the numeric value to makeindex for sorting)

---

## overfull boxes in table of contents

we went over 1000 pages 

`\renewcommand{\@pnumwidth}{2em}`

would fix this

---

## overfull boxes in macrocode

we already have

```
\renewcommand*\MacroFont{\fontencoding\encodingdefault
                   \fontfamily\ttdefault
                   \fontseries\mddefault
                   \fontshape\updefault
                   \small
                   \hfuzz 6pt\relax}
```

but `%<latexrelease>` lines regularly over run this, we could use (say) 50pt here without overrunning the page margin.
Remaining lines longer than that should or could be reformatted by hand.

---

## other overfull and underfull boxes

The running text has a lot of unbreakable command names and doesn't justify easily: we should probably use `\sloppy` 

---

## l3doc warnings

There are several warnings about L3 code being used in the wrong module, mostly these need to be fixed by disabling the warning rather than changing the code.

Most are fixed by adding `[kernel]`  so

```
\LoadClass[kernel]{l3doc}
```

in `source2edoc.cls`

The remaining ones are mostly in Lua or in NFSS code

**Comment by davidcarlisle** [comment]
Most of this is done, we could close and then just open any new issues that come up

**Comment by FrankMittelbach** [comment]
Guess we could -- or you add a  "(done)" after each of them that was handled above.

**Comment by davidcarlisle** [comment]
yes but the remaining ones (unlike the badly formatted toc) all relate to warnings in the log (overfull hbox...) so we don't really need to keep a ticket open just look at the log every year or so....
