### ISSUE TITLE
longtable seems misaligned horizontally in itemize environment

### ISSUE THREAD

**Issue by nwhetsell** [latex3/latex2e#128]
## Brief outline of the bug

When using a `longtable` in an `itemize` environment, the `longtable` seems to be misaligned horizontally (too far to the left).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}

\documentclass{article}

\usepackage{longtable, blindtext}

\begin{document}
\begin{itemize}
\item \blindtext

\begin{longtable}{@{}p{\linewidth}@{}}
longtable \\\hline%\endhead
longtable \\
\end{longtable}

\item \blindtext

\begin{tabular}{@{}p{\linewidth}@{}}
tabular \\\hline
tabular \\
\end{tabular}

\end{itemize}
\end{document}
```

The `tabular` environment is there for the sake of comparison, and shows where I’d expect the `longtable` to be. In the `longtable`, `\endhead` is commented out so that the two tables are pretty much the same, but including `\endhead` produces the same behavior.

## Log file and PDF file

[longtable-in-itemize.log](https://github.com/latex3/latex2e/files/2909970/longtable-in-itemize.log)
[longtable-in-itemize.pdf](https://github.com/latex3/latex2e/files/2909971/longtable-in-itemize.pdf)

<img width="598" alt="longtable-in-itemize" src="https://user-images.githubusercontent.com/14102861/53486444-b896cd80-3a56-11e9-81e7-a37f71a1126e.png">

**Comment by davidcarlisle** [comment]
A tabular is an inline construct that is part of a surrounding paragraph so
it naturally indents to whatever paragraph settings are in force within the
lift.

longtable is a display construct that is always the full width of the page,
and by default centres the specified columns within that width.

If you want the longtable to appear indented to the list indent then


\setlength\LTleft{\leftmargin}
\begin{longtable}{@{}p{\linewidth}@{}}

Should do what you need.

**Comment by nwhetsell** [comment]
Got it, thanks!
