### ISSUE TITLE
New command: \__kernel_set_arg_to_keyvalue:Nnn

### ISSUE THREAD

**Issue by Sophanatprime** [latex3/latex2e#1288]
## Brief outline of the enhancement

There is a handy command `\__cmd_arg_to_keyvalue:nn`, which can convert a token list to a key-value. It saves the result to `\ProcessedArgument`. I'm not sure `\ProcessedArgument` can be used freely, and ` \__cmd_set_arg_to_keyvalue:nn` is an internal command. So maybe we can have a command `\__kernel_set_arg_to_keyvalue:Nnn` which saves the result to the first parameter.

With this command, we now can easily define a command `\my_if_keyvalue:nTF`, I think it is widely used.

## Minimal example showing the behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\ExplSyntaxOn
\tl_new:N \l__my_keyvalue_tl
\scan_new:N \s__my_mark
\cs_new_protected:Npn \__my_if_keyvalue:nTF #1#2#3
  {
    \__kernel_set_arg_to_keyvalue:Nnn \l__my_keyvalue_tl { \s__my_mark } {#1}
    \str_if_eq:eeTF { \s__my_mark } { \tl_head:N \l__my_keyvalue_tl }
      {#3} {#2}
  }
\ExplSyntaxOff

\begin{document}

  % Demonstration of issue here
  
\end{document}
```

**Comment by muzimuzhi** [comment]
I interpret your need as "exposing the logic of `=` argument modifier in `ltcmd` module as a public latex3 conditional function, which checks whether an `n`-type argument is in key-value format or not in the same way `=` modifier does". (The documentation of `=` modifier can be found in `texdoc usrguide` (2023-05-23), sec. 2.9 "Auto-converting to key–value format".)

I think the quickest way is implementing a modified version of `\__cmd_arg_to_keyvalue:nn` in your code.

Can you give some precise use cases which are not covered by `=` modifier?

**Comment by Sophanatprime** [comment]
The main reason is document command is rather slower than a usual macro, it executes many unnecessary codes for this demand.

```tex
\documentclass{article}

\ExplSyntaxOn
\cs_new:Npn \__kernel_set_arg_to_keyvalue:Nnn #1#2#3
  {
    \__cmd_arg_to_keyvalue:nn {#2} {#3}
    \tl_set_eq:NN #1 \ProcessedArgument
  }
\tl_new:N \l__my_keyvalue_tl
\scan_new:N \s__my_mark
\cs_new_protected:Npn \__my_if_keyvalue:nTF #1#2#3
  {
    \__kernel_set_arg_to_keyvalue:Nnn \l__my_keyvalue_tl { \s__my_mark } {#1}
    \str_if_eq:eeTF { \s__my_mark } { \tl_head:N \l__my_keyvalue_tl }
      {#3} {#2}
  }
\NewDocumentCommand \__mz_if_keyvalue:nTF { ={\s__my_mark} +m +m +m }
  {
    \str_if_eq:eeTF { \s__my_mark } { \tl_head:n {#1} }
      {#3} {#2}
  }
\ExplSyntaxOff
\usepackage{l3benchmark}
\begin{document}

\ExplSyntaxOn
\benchmark_tic:
\prg_replicate:nn { 10000 }
  { \__my_if_keyvalue:nTF {aa=b,hudiw=dwuiahud,ajwdihfuawijdaodhawdfe,aa=b } {}{} }
\benchmark_toc:

\benchmark_tic:
\prg_replicate:nn { 10000 }
  { \__mz_if_keyvalue:nTF {aa=b,hudiw=dwuiahud,ajwdihfuawijdaodhawdfe,aa=b } {}{} }
\benchmark_toc:

\benchmark_tic:
\prg_replicate:nn { 10000 }
  { \__my_if_keyvalue:nTF {aa=b,hudiw=dwuiahud,ajwdihfuawijdaodhawdfe,aa=b } {}{} }
\benchmark_toc:

\benchmark_tic:
\prg_replicate:nn { 10000 }
  { \__mz_if_keyvalue:nTF {aa=b,hudiw=dwuiahud,ajwdihfuawijdaodhawdfe,aa=b } {}{} }
\benchmark_toc:
\ExplSyntaxOff

\end{document}
```
and the result is
```txt
(l3benchmark) + TOC: 0.305 s %% plain macro
(l3benchmark) + TIC
(l3benchmark) + TOC: 0.678 s %% document command
(l3benchmark) + TIC
(l3benchmark) + TOC: 0.311 s %% plain macro
(l3benchmark) + TIC
(l3benchmark) + TOC: 0.664 s %% document command
```
in my laptop (with pdflatex).

**Comment by muzimuzhi** [comment]
BTW `\__kernel...` is still an internal name. `\cmd_...` is OK but I doubt LaTeX2e kernel will provide such one in short term.

**Comment by josephwright** [comment]
At present, the use case here does not really seem to justify adding this: yes document commands are slower than 'raw' macros, but there are reasons.
