### ISSUE TITLE
The grammar of 2 error messages are a bit off

### ISSUE THREAD

**Issue by colourful-land** [latex3/latex2e#129]
!! Please fill out all sections after reading CONTRIBUTING guidelines (and remove lines starting with !!)

## Brief outline of the bug

The grammar of 2 error messages are a bit off

## Minimal example showing the bug

The original issue is filed here:
https://github.com/jgm/pandoc/issues/5332

    $ pandoc --latex-engine=xelatex -o design.pdf design.md
    [pandoc warning] Unable to convert `3.svg' for use with pdflatex.
    ! LaTeX Error: Cannot determine size of graphic in 3.svg (no BoundingBo
    x).
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.1650 \includegraphics{3.svg}
    
    pandoc: Error producing PDF
    Makefile:2: recipe for target 'design.pdf' failed
    make: *** [design.pdf] Error 43

Two grammar issues:

1. Cannot determine size of graphic in 3.svg should be:
Cannot determine size of *the* graphic in 3.svg

2. See the LaTeX manual or LaTeX Companion for explanation. should be:
See the LaTeX manual or LaTeX Companion for *an* explanation.

One semantic issue:

`Cannot determine size of graphic in 3.svg (no BoundingBox)` can mean:

a. No bounding box is found in the SVG file where it should be.
b. No bounding box is specified (in LaTex) for the SVG file.

This can be easily amended by changing it to:

Cannot determine size of graphic,  *no BoundingBox* *in 3.svg.

By the way, I really appreciate if you also address the underlying technical problem I am having since my SVG file does have a bounding box. I asked in the group: https://groups.google.com/forum/#!topic/pandoc-discuss/_VPm7XoqMQA

**Comment by colourful-land** [comment]
The semantic issue that `Cannot determine size of graphic in 3.svg (no BoundingBox)` can mean 2 different things is worse than the grammar issue since the user can ignore grammar issue.

**Comment by davidcarlisle** [comment]
there is a cost to changing these error messages, it invalidates existing
documentation and searches, for example

https://tex.stackexchange.com/questions/17734/cannot-determine-size-of-graphic

Also some editor front ends detect certain messages and supply additional
help (although emacs auctex doesn't do that for this one)

In this case the main issue is that SVG files do not have BoundingBox
comments at all LaTeX is using the default EPS reader, as (despite the
contributing guidelines) no test file is provided, there is not a lot else
I can say.

I would disagree that

> The semantic issue that Cannot determine size of graphic in 3.svg (no
BoundingBox) can mean 2 different things

is an issue, as the two things are the same. This message is intended for
(E)PS files:

the BoundingBox information can come from (in order of search) optional
argument on \includegraphics, from a  .bb (bounding box) file or a
%%BoundingBox comment  in the PostScript. If no size is found in any of
those places you get this error and you can fix it by adding the size in
any of those three ways.

**Comment by FrankMittelbach** [comment]
Thanks for your suggestions, but as David said, changing such error message texts would come at a fairly high cost in terms of finding answers on the web etc.
