### ISSUE TITLE
\if@reversemargin wrongly documented in source code

### ISSUE THREAD

**Issue by pietvo** [latex3/latex2e#1296]
## Brief outline of the bug

In `ltoutput.dtx` line 850 it says `% \begin{macro}{\if@reversemarginpar}`.
However, this should be `% \begin{macro}{\if@reversemargin}`

It doesn't affect any code, just the documentation of the source.

So no example necessary, or even relevant.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here

\begin{document}

  % Demonstration of issue here
  
\end{document}
```

**Comment by davidcarlisle** [comment]
Thanks, fixed in develop branch, I guess that's been wrong for 30 years:-)
