### ISSUE TITLE
Ligatures=TeX with \babelfont

### ISSUE THREAD

**Issue by jbezos** [latex3/latex2e#130]
At some point (I don't know when), `fontspec` enabled `Ligatures=TeX` with `\setmainfont` and `\setsansfont`. But `\babelfont` doesn't, and very likely should, but it's based on an open model, so that it can be adapted to non-European typography, which is not always based on rm/sf/tt. So, when must `Ligatures=TeX` be enabled? It's tempting to activate it with rm/sf, or with any family except tt, but I'm not sure.

**Comment by u-fischer** [comment]
It is not only fontspec, the tlig-ligatures are already in TUlmr.fd and TUlmss.fd and so activated by the format. Imho babelfont should activate them for rm/sf, that's a better default.

**Comment by wspr** [comment]
I agree with Ulrike. (Although the fontspec change predates the TU implementation.)

I think the changes of it causing a problem are so low that even if there are some scripts that don’t use it, having it on by default shouldn’t cause any issue.

**Comment by jbezos** [comment]
Will, do you mean always, ie, every font except tt? The alternative es
never, except rm/sf.

**Comment by wspr** [comment]
Yes, the tt / monospaced font is the one exception where it’s definitely no good :) But I never took the plunge of enabling it by default with \newfontfamily…

**Comment by jbezos** [comment]
:-/ So, we go back to the beginning, because I regard `\babelfont` as a sort of extended version of `\newfontfamily` (except it can be used to set the standard families).

**Comment by wspr** [comment]
In that case no argument from me — I’d be happy if it were left as is :)

**Comment by jbezos** [comment]
After investigating a bit further, I noticed these defaults are not hardcoded, but set by `fontspec.cfg` with a `\defaultfontfeatures` . But `\babelfont` ignores the latter command altogether, which should be considered a bug. So, I've rewritten this part (which I'm currently testing).
