### ISSUE TITLE
Adding a .dir-locals.el to the project root directory

### ISSUE THREAD

**Issue by dr-scsi** [latex3/latex2e#1309]
Hi all,

given that some of the developers use Emacs, would you consider adding a `.dir-locals.el` to the project root?  A very basic setup can look like this:

```
;;; Directory Local Variables            -*- no-byte-compile: t -*-
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((sentence-end-double-space . t)
         (indent-tabs-mode . nil)
         (fill-column . 74))))

```

Different settings can be applied to `latex-mode` or `doctex-mode` or other modes if necessary.

Rationale: I have set `indent-tabs-mode` to `nil` locally and each time I edit a file for a PR, the tabs are converted and I have to be careful not to apply them untabifying big portion of the file.  Line breaks and `fill-column` is the next topic.

I hope you consider this; would make life easier for contributors (who use Emacs, of course).

**Comment by FrankMittelbach** [comment]
I use emacs but I would hate `sentence-end-double-space`. But I agree, a setup possibility in that direction is probably a good idea.

**Comment by davidcarlisle** [comment]
I use emacs all the time, but I'm not sure I'd want this. As @FrankMittelbach  just commented even for emacs users it's not always clear what the settings would be and if we allow emacs then we would probably have to allow other settings for other editors as well. It would end up (presumably) being several files in several repositories. I have one parent directory for all the latex3 github organisation repositories so if I did want such a file I could have a single one there but that is not under git so we'd probbaly end up with multiple copies under each of latex2e, latex3, hyperref...

**Comment by josephwright** [comment]
I have to say for me this feels like a 'local' setting, as it's about individuals not the repo - but I can live with it if it works for Emacs users.

**Comment by dr-scsi** [comment]
> I use emacs all the time, but I'm not sure I'd want this. As @FrankMittelbach just commented even for emacs users it's not always clear what the settings would be

@davidcarlisle - I'm not sure if I understand the above correctly, but my understanding is that the project leaders agree once on the settings and then it is dictated for all of us since the settings apply to all the files in the project.

> and if we allow emacs then we would probably have to allow other settings for other editors as well.

Probably, the question is what other editors core contributors use and how many other files you expect.  There is [EditorConfig](https://editorconfig.org) which tries to circumvent this issue, but I don't think it worth the hassle to set it up for LaTeX repos (I've never used it, so can't tell if it works).

> It would end up (presumably) being several files in several repositories.

Yes, this can happen, but my experience is that these config files don't change often, so it is sort of "fire and forget".

> I have one parent directory for all the latex3 github organisation repositories so if I did want such a file I could have a single one there but that is not under git so we'd probably end up with multiple copies under each of latex2e, latex3, hyperref...

Yes, true.  But this can also be an advantage if you want different settings for hyperref and others for latex2e etc.

**Comment by Skillmon** [comment]
I'd say if you do something like this it shouldn't be editor specific, so EditorConfig might actually be a good idea. But an Emacs specific file would then also call for files specific to all possible editors frequently used by LaTeX editors (so basically every LaTeX editor, plus the "good" general purpose text editors, including Emacs, VIM, VisualStudio, ... -- not something I'd like to clutter every LaTeX-project repository).
