### ISSUE TITLE
longtable: Misordered when combined with \paragraph and \subparagraph

### ISSUE THREAD

**Issue by adunning** [latex3/latex2e#131]
## Brief outline of the bug

When adding a `longtable` following a `\paragraph` or `\subparagraph`, the table appears before rather than after the heading.

There are solutions to this on [StackExchange](https://tex.stackexchange.com/q/192646/) and a [Pandoc issue](https://github.com/jgm/pandoc/issues/1658), but could this be addressed in the package directly? The workaround (see [the Pandoc LaTeX template](https://github.com/jgm/pandoc/blob/cdad322a98f7fd694008733ead8a189ce27edf77/data/templates/default.latex#L293)) can cause other problems, and it would be nice to be able to remove it.

## Minimal example showing the bug

<img width="383" alt="Screen Shot 2019-03-14 at 08 45 18" src="https://user-images.githubusercontent.com/1084407/54357920-816b1380-4635-11e9-9ba4-d7f19f550c32.png">

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{longtable}

\begin{document}

\subsubsection{Title 3}

\begin{longtable}[]{@{}llll@{}}
12 & 12 & 12 & 12\tabularnewline
\end{longtable}

\paragraph{Title 4}

\begin{longtable}[]{@{}llll@{}}
12 & 12 & 12 & 12\tabularnewline
\end{longtable}

\paragraph{Title 5}

\begin{longtable}[]{@{}llll@{}}
12 & 12 & 12 & 12\tabularnewline
\end{longtable}

\end{document}
```

## Log file (required) and possibly PDF file  

[longtable.log](https://github.com/latex3/latex2e/files/2966384/longtable.log)
[longtable.pdf](https://github.com/latex3/latex2e/files/2966385/longtable.pdf)

**Comment by u-fischer** [comment]
longtable could perhaps test for `\if@noskipsec` and insert an \mbox{} if it is true:

~~~~
\documentclass{article}
\usepackage{longtable}
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\par\if@noskipsec \mbox{CONTENT ONLY FOR TEST}\fi}{}{\fail}
\makeatother
\begin{document}
\begin{longtable}{l}
yyy
\end{longtable}

\paragraph{paragraph}

\begin{longtable}{l}
yyy
\end{longtable}

\paragraph{paragraph}
\begin{longtable}{l}
yyy
\end{longtable}

\paragraph{paragraph} abc

\begin{longtable}{l}
yyy
\end{longtable}

text
\begin{longtable}{l}
yyy
\end{longtable}

\section{blblb}

\begin{longtable}{l}
yyy
\end{longtable}

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/54429292-62957b80-4720-11e9-9144-752ef0a44bc1.png)

**Comment by adunning** [comment]
That suggestion works perfectly in my testing; thank you!

**Comment by car222222** [comment]
I think I would put the \par after the \mbox ?? Thus:

\if@noskipsec \mbox {}\par

**Comment by adunning** [comment]
Still an issue.

**Comment by davidcarlisle** [comment]
yes sorry I hope to get to this before texlive 2020.

**Comment by adunning** [comment]
No rush – I was only aiming to prevent the bot from closing the issue!

**Comment by davidcarlisle** [comment]
fixed as suggested by @car222222  above
