### ISSUE TITLE
Changes in horizontal spacing in some equations

### ISSUE THREAD

**Issue by jovyntls** [latex3/latex2e#1319]
## Brief outline of the bug

The spacing of characters in some equations has changed from the TeXLive 2022 distribution to TeXLive 2023 distribution.
It seems to occur for equations using `~` with an operator like `-` or `\leq`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

	\begin{equation}
	  -1,~-2
	\end{equation}
  
\end{document}
```

## Log file (required) and possibly PDF file  

[main.log](https://github.com/latex3/latex2e/files/14768813/main.log)

PDF file from TeXLive 2022:
[main2022.pdf](https://github.com/latex3/latex2e/files/14768889/main2022.pdf)

PDF file from TeXLive 2023:
[main2023.pdf](https://github.com/latex3/latex2e/files/14768892/main2023.pdf)

Using the diff-pdf tool to superimpose both PDF files shows the difference in alignment (red is 2022, blue is 2023):
[outdiff.pdf](https://github.com/latex3/latex2e/files/14768869/outdiff.pdf)
<img width="843" alt="image" src="https://github.com/latex3/latex2e/assets/61113575/acd9c946-3a56-475d-9b1a-edbfa5805155">

**Comment by muzimuzhi** [comment]
In LaTeX2e 2023-11-01 (see e98027dcfd95d74d99e0c724739b55df894311d1), to make it safe in csnames, definition of active tilde was changed from
```tex
\def~{\nobreakspace{}}
```
to
https://github.com/latex3/latex2e/blob/4472861c8f6b65bc3c1fd8eca614ec699d332932/base/ltspace.dtx#L1229-L1234

The new definition acts like `\nobreakspace` without trailing pair of braces when used in non-csnames, for example in math equations.

There's even a code comment (added by a4df9c4bd31177e10bbc3ca4516b6f32442413d2) which explains why the `{}` is now unneeded.
https://github.com/latex3/latex2e/blob/4472861c8f6b65bc3c1fd8eca614ec699d332932/base/ltspace.dtx#L1217-L1220

I think current behavior of `~` in math is more correct. Note the spacing (actually the math class of minus sign) between minus sign and number 2 was interfered by the trailing `{}` in `~` prior to LaTeX2e 2023-11-01.

Also maybe math spacing commands `\,`, `\:`, and `\;` are more recommended than `~`.

```tex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}
Before \LaTeXe{} 2023-11-01
\begingroup
\def~{\nobreakspace{}}
\begin{equation}
  -1,~ -2
\end{equation}
\endgroup

Starting from \LaTeXe{} 2023-11-01
\begin{equation}
  -1,~ -2
\end{equation}
```

![image](https://github.com/latex3/latex2e/assets/6376638/28d1533d-1b4c-4650-a386-d2e1bd17b427)

**Comment by FrankMittelbach** [comment]
I would say so, but not the other one you opened up in colortbl necause, while  releated that nevertheless might need some actions.
