### ISSUE TITLE
babel: Arabic text do not appear correctly  between two inline math formulas

### ISSUE THREAD

**Issue by seloumi** [latex3/latex2e#132]
## Brief outline of the bug

With babel `bidi=basic-r` if I insert Arabic text between two inline math formulas the result appear incorrectly (letters are not linked) 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       
\documentclass[12pt]{article}

\usepackage[nil,bidi=basic-r]{babel}
\babelprovide[import=ar-DZ, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}

$x$ نص عربي للتجريب $y$

\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/2970597/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/2970595/test.pdf)

**Comment by jbezos** [comment]
Works with `bidi=basic`, and also if the first math is ‘hidden’ inside an `\mbox`. I'll investigate next week.

**Comment by jbezos** [comment]
I've just pushed a new version which, I think, fixes it.

**Comment by seloumi** [comment]
Thanks for your reply and for your work on bidi with babel.

**Comment by seloumi** [comment]
There  is also another issue with closing parenthesis in inline math in right to left context 

```latex
\RequirePackage{latexbug}
 \documentclass[12pt]{article}

\usepackage[nil,bidi=basic-r]{babel}
\babelprovide[import=ar-DZ, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}
$f(x)$

$$f(x)$$
\end{document} 
```
[test.pdf](https://github.com/latex3/latex2e/files/2985546/test.pdf)
