### ISSUE TITLE
CamelCase or Pascal case?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#1321]
According to https://en.wikipedia.org/wiki/Camel_case:

> Camel case is the practice of writing phrases without spaces or punctuation and with capitalized words. The format indicates the first word starting with either case, then the following words having an initial uppercase letter.
>
> The more specific terms Pascal case and upper camel case refer to a joined phrase where the first letter of each word is capitalized, including the initial letter of the first word.

[Several documents](https://github.com/search?q=org%3Alatex3%20CamelCase&type=code) of `LaTeX2e` refer to “CamelCase”. But is it actually “CamelCase” (or, maybe better, “Camel case”) or, instead, “Pascal case”?

**Comment by davidcarlisle** [comment]
In practice we always use Camel Case to mean first letter Uppercase (so Pascal case) but as it is always consistent I think its fine to use Camel Case  for that. .NET languages have conventions where some constructs use lower first and some upper, so their doc does consistently call the uppercase first style Pascal case to distinguish, but I don't think it would help to use that term here.

**Comment by FrankMittelbach** [comment]
I'm against any change here. CamelCase may not be the version that is most often used but is is *one* of the ways to refer to it and in constrast to Camel case or Pascal Case it is immediately visiable what is meant and for me that counts. View people would understand Pascal case and "Camel case" is also far less clear. S no, regardless of what Wikipedia claims is the most common synonym :-)

**Comment by dbitouze** [comment]
OK. My question was also whether the first letter could be in lower case. It isn't and it won't be: OK.
