### ISSUE TITLE
\textcircled and TS1 missing circle.

### ISSUE THREAD

**Issue by lstonys** [latex3/latex2e#1337]
In the class file to get TS1 symbols I use
```
\DeclareEncodingSubset{TS1}{\rmdefault}{0}
```
it's just because class is used for many different journals with different fonts.
(related to https://github.com/latex3/latex2e/issues/1257)

TL2024 pdflatex using `\textcircled{1}` I get warning:
```
Missing character: There is no O in font charssil-tlf-ts1!
```
Ok, this symbol is not in TS1: 
```
Some glyphs are missing from sub-encoding 0:
   ==> \textcircled (79) is missing
```
but when I use `\usepackage{textcomp-2018-08-11}` instead of `DeclareEncodingSubset` then it works like in TL2019 ant circle symbol is taken from OMS encoding (cmsy family).
```
LaTeX Font Warning: Font shape `OMS/charssil-TLF/m/n' undefined
(Font)              using `OMS/cmsy/m/n' instead on input line 9.
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{CharisSIL}

\DeclareEncodingSubset{TS1}{\rmdefault}{0}
%\usepackage{textcomp-2018-08-11}

\begin{document}
text \textcircled{1}
\end{document}
```

Without `\DeclareEncodingSubset{TS1}{\rmdefault}{0}` (charssil-TLF is set to `5` in the kernel) it works fine (like in the old texlive). So conclusion is 
that setting `\DeclareEncodingSubset` to `0` forces to use everything from TS1 without any substitution and this is the only behavior comparing with the `textcomp-2018-08-11`?

**Comment by u-fischer** [comment]
Sorry I don't understand the question or issue. You are obviously lying to LaTeX by claiming that your font has full textcomp support. That is clearly wrong user input so where is the bug? You would have got a similar problem with the old textcomp if you had used the package options `full,force`.

**Comment by FrankMittelbach** [comment]
As Ulrike said, with `\DeclareEncodingSubset{TS1}{\rmdefault}{0}` you are claiming that the current font for Roman has all glyphs from TS1 which is just not true in many cases including for CharisSIL. This is basically a wrong thing to do. If there is no subencoding specification for a specifc family then LaTeX is cautious and chooses the one that normally works with any font family. But is has suitable definitions for many free families already.
In other words,  `\DeclareEncodingSubset` is meant to be used for specific families not as a generic setting like you do and if you had done this with an old textcomp package it would also show the issue (doesn't even need full or force) -- of course, you have to make the declaration after the package got loaded but then it also generates
```
Missing character: There is no O in font charssil-tlf-ts1!
```
The difference between the 2018 version and the current version in the kernel is that the original package had only a few fonts set up with subencodings and only 4 different subencodings while the current one is much more granular and has 10 subencodings or so and covers about 100 font families out of the box correctly.

So in summary you should not make such kind of a declaration in a class (with \rmdefault) but only one with explicit  families if at all, but normally it is better to make such a declaration only in font support files for a particular font or in the kernel.
