### ISSUE TITLE
\resizebox* mentioned but unexplained in grfguide?

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#1339]
In grfguide, the section "Scaling to a requested size" shows the synopsis
```
\resizebox*{h-length }{v-length }{text }
```
but I'm not seeing any explanation of what the *-form is. The examples have no *.

I believe the * form determines whether the v-length is the height or the height+depth, but the point is that it's not in the doc. Not that it's hard to find elsewhere, but ...

**Comment by davidcarlisle** [comment]
Admitedly it falls on the next page but both grfguide and graphics.dtx do say

> Normally \emph{v-length} refers to the height of the box, but in the
 star form, it refers to the `height +  depth'.

**Comment by davidcarlisle** [comment]
I could add

>  ... star form, `\resizebox*`, ....  

so if someone just searches for `resizebox*` they find it more easily?

**Comment by car222222** [comment]
In addition, @davidcarlisle, it would be much clearer if the sentence referring to the star form, with this addition, was moved to form a second paragraph.

Maybe also add an example of the star-form in use?

**Comment by kberry** [comment]
I'm sorry for my foolishness. I missed the word "star". I knew it had to be there ...

as long as we're talking about it, yes, an example or something with an actual * character could only help dunces like me :). Thanks.

**Comment by davidcarlisle** [comment]
@kberry  after last commit it looks like

![image](https://github.com/latex3/latex2e/assets/1268738/e22fbab5-a82b-43c1-9a41-6445d0526f25)

hmm missing the comma after `\resizebox*`
