### ISSUE TITLE
babel: issue with closing parenthesis in inline math in right to left context

### ISSUE THREAD

**Issue by seloumi** [latex3/latex2e#134]
## Brief outline of the bug
@jbezos  There is also another issue with the last closing parenthesis in inline math in right to left context.
The issue appear with `bidi=basic-r` and also with  `bidi=basic`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
 \documentclass[12pt]{article}

\usepackage[nil,bidi=basic-r]{babel}
\babelprovide[import=ar-DZ, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}
$f(x)$

$$f(x)$$
\end{document}
```

## Log file (required) and possibly PDF file  

[test.pdf](https://github.com/latex3/latex2e/files/2985612/test.pdf)
[test.log](https://github.com/latex3/latex2e/files/2985593/test.log)

**Comment by jbezos** [comment]
It seems I was overly optimistic about #132, mainly because I was doing a wrong assumption about the math mode. The problem also appears with `bidi=basic`. I have to reorganize some parts of the algorithm, to isolate properly the direction in math blocks.

**Comment by jbezos** [comment]
I've found a solution based on assuming everything inside math has the \mathdir direction. Bidi math is not trivial and deserves a fairly elaborate treatment. This is an area where any help will be greatly appreciated.

**Comment by seloumi** [comment]
In most of the cases math in RTL context is LTR.
