### ISSUE TITLE
Improvement to package rotating part of the graphics suit

### ISSUE THREAD

**Issue by anton-vrba** [latex3/latex2e#1347]
## Brief outline of the enhancement

In books `twoside` mode tables generated by  `sidewaystable`  read from the binding to the outer page edge.  

I have made a small change to `rotating.dtx`   introducing the option `figuresinner` and `figuresouter`.

`figuresinner:` is the default mode, tables read from the book binding to outer edge of paper

`figuresouter:`  tables read from outer edge to the book binding.

This modification is fully compatible with the current release of the package.

I attach three files:

[rotating.dtx.txt](https://github.com/latex3/latex2e/files/15286076/rotating.dtx.txt) with following modification  also commented by ## 

1. The first modification is on lines 187 to 197 introducing the two new options and the new if `\if@rot@outer`
2.  The second modification is on lines 407 to 443, which now includes testing for new options. The if structure is not indented so that it is easily identified.

The other two files [figuresinner.pdf](https://github.com/latex3/latex2e/files/15286081/figuresinner.pdf) and [figuresouter.pdf](https://github.com/latex3/latex2e/files/15286085/figuresouter.pdf) each with an even and odd page demonstrate the intended result.

Interestingly: the default mode centres the table in _textwidth_ whereas `figuresouter` centres the table in _textwidth+marginparwidth_, why that should be I have no idea but provides a desirable result as I am using marginala.

My hope is that you also view this as an improvement for a future release 
regards
Anton Vrba

**Comment by josephwright** [comment]
We are looking at the functionality of `rotating` but not extending the package: as such, this issue will not move forward.
