### ISSUE TITLE
babel: wrong direction of numbering in \thesection, \thesubsection, \thesubsubsection, ...... in RTL context

### ISSUE THREAD

**Issue by seloumi** [latex3/latex2e#135]
## Brief outline of the bug
With babel using `bidi=basic` in right to left mode numbers are writen from left to right and that's correct in main text but this is not desirable in heading numbering ( inside \thesection, \thesubsection, \thesubsubsection, ...... and also inside \thefigure, \thetable, \thetheorem, ...... ) where numbers should be RTL. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       
\documentclass[12pt]{article}

\usepackage[bidi=basic-r]{babel}
\babelprovide[import=ar-DZ, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}

\section{first section}
\subsection{first subsection} 
\subsection{second subsection} % wrong numbering

1.34 % correct numbering

\renewcommand{\thesubsection}{\hbox{\arabic{section}}.\arabic{subsection}}

\subsection{third subsection} % correct numbering

\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/2999261/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/2999264/test.pdf)

**Comment by car222222** [comment]
I am not sure you mean that the individual numbers should be RTL.  Rather that the Section digits string should be to the right of the Subsection digits string, etc.

Or not?  is the fourteenth Section written in digits as 14  or 41 ?

**Comment by seloumi** [comment]
The `bidi`  package redefine all this numbering (xelatex engine)
https://github.com/bidi-tex/bidi/blob/5a9d99e1f4e038435eb79bff436c37c01c149e21/bidi.dtx#L328

**Comment by seloumi** [comment]
Numbering inside heading should be like this
                                                                                                                           first section  1
                                                                                                               first subsection 1.1
                                                                                                         second subsection  2.1

**Comment by u-fischer** [comment]
(Assuming that I understood what you want as output) you need to declare the order with the layout option:

```
\RequirePackage{latexbug}
\documentclass[12pt]{article}

\usepackage[bidi=basic-r,layout=counters]{babel}
\babelprovide[import=ar-DZ, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}

\section{first section}
\subsection{first subsection}
\subsection{second subsection} % wrong numbering

1.34 % correct numbering

\renewcommand{\thesubsection}{\hbox{\arabic{section}}.\arabic{subsection}}

\subsection{third subsection} % correct numbering

\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/54865628-81bb8b00-4d68-11e9-85c2-4fcbdba2969b.png)

**Comment by seloumi** [comment]
The fourteenth Section written in digits is 14  but  the first subsection in the  fourteenth Section should be numbered `1.14` not `14.1`

**Comment by seloumi** [comment]
Thanks u-fischer that's what I need.
