### ISSUE TITLE
Update README.md copyright to 2024

### ISSUE THREAD

**Issue by flowrolltide** [latex3/latex2e#1358]
> Copyright (C) 2019-2023
> The LaTeX Project

Proposed change: Copyright (C) 2019-202**4**

**Comment by josephwright** [comment]
Hasn't been edited this year that I can see

**Comment by FrankMittelbach** [comment]
true but being top-level, I think it is appropriate if that in this case shows the current date as it will be perceived as the copyright notice for everything.
