### ISSUE TITLE
xfrac package broken by LaTeX 2024-06-01

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#1369]
## Brief outline of the bug

```
! Undefined control sequence.
<argument> \IfInstanceExistTF 
                              {xfrac}{mathfam\number \fam }{\UseInstance {xf...
l.6 et avec \textsf{xfrac} : $\sfrac{a}{b}
                                          $
? X
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
  \usepackage{xfrac}

\begin{document}
et avec \textsf{xfrac} : $\sfrac{a}{b}$
\end{document}
```

## Log file (required) and possibly PDF file  

[4_domaines_specialises_mathematiques_structures_fractions_composer_le_ratio_a_sur_b_avec_des_espaces_corrects-4e0f3d79.log](https://github.com/user-attachments/files/15669141/4_domaines_specialises_mathematiques_structures_fractions_composer_le_ratio_a_sur_b_avec_des_espaces_corrects-4e0f3d79.log)

**Comment by u-fischer** [comment]
The new xfrac  (2024-06-04) which resolves has been uploaded two days ago.

**Comment by jfbu** [comment]
ah ok but it was not installed at the last time I did `tlmgr update --all` which installed LaTeX 2024-06-01.

**Comment by jfbu** [comment]
`tlmgr update xfrac` did install the new one, thanks.
