### ISSUE TITLE
tabularx no longer distributes space equally among X columns

### ISSUE THREAD

**Issue by logological** [latex3/latex2e#1372]
## Brief outline of the bug

I just updated my TeX Live 2024 installation and now `tabularx` no longer distributes space equally among `X` columns.  Perhaps this is related to Issue #1368?

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{tabularx}
\begin{document}
\begin{tabularx}{\linewidth}{|X|X}
\hline
&\\
\hline
\end{tabularx}
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/user-attachments/files/15743663/test.log)
[test.pdf](https://github.com/user-attachments/files/15743664/test.pdf)

The PDF shows that the second column of the `tabularx` environment is much wider than the first, whereas I expected them to be of equal width.

**Comment by muzimuzhi** [comment]
The processing for empty cells is problematic.

```tex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{tabularx}
\begin{document}

\fmtname, \fmtversion

\begin{tabularx}{\linewidth}{|X|X|}
  \hline
  a & a \\ \hline
\end{tabularx}

\begin{tabularx}{\linewidth}{|X|X|}
  \hline
  a &   \\ \hline
\end{tabularx}

\begin{tabularx}{\linewidth}{|X|X|}
  \hline
    & a \\ \hline
\end{tabularx}

\begin{tabularx}{\linewidth}{|X|X|}
  \hline
    &   \\ \hline
\end{tabularx}
\end{document}
```
- LaTeX 2023-06-01 (compiled on overleaf.com)
  ![image](https://github.com/latex3/latex2e/assets/6376638/f41c2e04-13db-41ab-9110-03ee239a1af9)
- LaTeX 2024-06-01
  ![image](https://github.com/latex3/latex2e/assets/6376638/fd937171-840e-4ec6-831e-7592281391e2)

**Comment by muzimuzhi** [comment]
`tabularx` converts `X` columns into `p{<length>}` columns from `array` package, and yes empty cell in a `p{<length>}` column is problematic too.

```tex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{array}

\begin{document}
\newcommand{\testpcol}[2]{
  \begin{tabular}{|p{20pt}|p{20pt}|}
    \hline
    #1 & #2 \\ \hline
  \end{tabular}
  \par}

\testpcol{a}{a}
\testpcol{}{a}
\testpcol{a}{}
\testpcol{}{}
\end{document}
```
- LaTeX 2023-06-01
  ![image](https://github.com/latex3/latex2e/assets/6376638/69d7e916-05db-4608-b110-f3846171693a)
- LaTeX 2024-06-01
  ![image](https://github.com/latex3/latex2e/assets/6376638/d29b4e5a-88db-4543-824a-91d5d8c2ba5f)

**Comment by davidcarlisle** [comment]
>  empty cell in a p{<length>} column is problematic too.

a `\parbox` width is (as documented) not respected if no paragraph is triggered as the width is the width used for line breaking.  it looks like a change in the way struts are added for tables means that the empty case isn't triggering a paragraph and so the width is lost. we need to look how best to address this.

**Comment by FrankMittelbach** [comment]
It is most likely because of the fix for not adding a final strut if the material has finished in vertical mode (rather than being still in horizontal mode where the strut makes sense). Putting the strut in vertical mode meant that one ended up with an unwanted extra line containing nothing but the strut.

Of course, in a truly empty cell that gave you the line that gave the cell a width.

**Comment by FrankMittelbach** [comment]
maybe like this:
```
\makeatletter
\def\@finalstrut#1{%
  \unskip
  \ifhmode \nobreak 
%  \vrule
  \else
    \ifdim \prevdepth=-\@m\p@
    \else
      \vskip-\prevdepth
    \fi   
\vskip-\baselineskip  %new
%    \hrule
  \fi
  \vrule %new
  \@width\z@\@height\z@\@depth\dp#1}
\makeatother
```
