### ISSUE TITLE
Missing spaces in array 'Illegal pream' message

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#1378]
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{array}
\begin{document}

\begin{tabular}{X}
  1.23 \\
\end{tabular}

\end{document}
```
results in 
```
! Package array Error: Illegalpream-token(X):`c'used.

See the array package documentation for explanation.
Type  H <return>  for immediate help.
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/user-attachments/files/15833067/test.log)

**Comment by josephwright** [comment]
This is happening as the code is now in `\ExplSyntaxOn`, so we need some `~`.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  I have this ready unless you want to push as change?

**Comment by FrankMittelbach** [comment]
please go ahead, I didn't assign myself, that was Joseph :-)
