### ISSUE TITLE
babel: "Token not allowed in a PDF string" warning  with layout=counters

### ISSUE THREAD

**Issue by seloumi** [latex3/latex2e#138]
## Brief outline of the bug
If I add `layout=counters` for babel with the hyperref package  this warning appear 

> Token not allowed in a PDF string (PDFDocEncoding):
> (hyperref) removing `\textdir'  

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}      
\documentclass{article}
\usepackage[unicode]{hyperref}
\usepackage[bidi=basic-r,layout=counters]{babel}
\babelprovide[import, main]{arabic}
\babelfont{rm}{Amiri}


\begin{document}
text
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/3005453/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/3005456/test.pdf)

**Comment by u-fischer** [comment]
well the hyperref package is not part of the kernel (and latexbug tells you this). You can try to disable the warning with `\pdfstringdefDisableCommands{\def\babelsublr{}}` but it could lead to wrong direction somewhere, e.g. in the bookmarks.

**Comment by seloumi** [comment]
Is there a solution somewhere in `counters` choice  implementation 
https://github.com/latex3/latex2e/blob/6a0e4cd0e874c00125a3a119228cd7be77634544/required/babel/babel.dtx#L11311

**Comment by u-fischer** [comment]
I'm not sure if the babel code is the right place. Imho the question about counter representations in various places (bookmarks, document, destination names) need some more thoughts.

**Comment by car222222** [comment]
Agreed that there are more general problems here.  Probably not just counters but other data holders that need to be “evaluated” or “dereferenced” only at the “right time”.

**Comment by u-fischer** [comment]
@car222222  the question is not so much evaluation time but the actual content of the definition. E.g. a document would perhaps want \arabic to use hebrew numbers or to change direction (`\def\arabic#1{{\textdir TRT \@arabic\csname c@#1\endcsname}}`) but this is then rather problematic if hyperref uses the command in bookmarks or to define destination names.

**Comment by jbezos** [comment]
The warning itself is not important (it just tells us there might be something wrong). The real problem is very likely the bookmarks - how are they displayed and how should they be displayed? Do the links point to the correct destination? For example, there is an obvious problem in https://github.com/latex3/latex2e/blob/master/required/babel/samples/lua-arabic.pdf , namely, the anchor is misplaced (it's too far to the right).

**Comment by seloumi** [comment]
Bookmarks are displayed fine (aligned to the right)
```latex
\documentclass{article}
\usepackage[unicode]{hyperref}
\usepackage[nil,bidi=basic-r,layout=counters]{babel}
\babelprovide[import=ar-DZ, main]{arabic}
\babelprovide[import,language=Default]{english}
\babelfont{rm}{Amiri}


\begin{document}

\tableofcontents

\section{عنوان أول}
\subsection{عنوان فرعي أول}
\subsection{عنوان فرعي ثان}

\end{document} 
```
![Capture](https://user-images.githubusercontent.com/8249073/55026534-7afc7480-5003-11e9-9e93-17230c3898c5.PNG)

**Comment by jbezos** [comment]
If everything is OK, then very likely all we need is to disable the warning (as suggested by Ulrike). I'm not yet sure if this should be done in `babel` or elsewhere (it looks like it must be in `babel`).
