### ISSUE TITLE
rollback error

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#1386]
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\RequirePackage[2024-05-01]{latexrelease}

\documentclass{article}
\begin{document}

This is NOT an item.

\begin{itemize}
\item This is an item.
\end{itemize}

\end{document}
```

errors with 

~~~~
! LaTeX Error: Something's wrong--perhaps a missing \item.
~~~~

This rollback is not applied:
~~~
Already applied: [2021/06/01] minipage fix on input line 9924.
~~~

and so the toks register at the end of `\g__para_standard_everypar_tl` is missing.

## Log file (required) and possibly PDF file  
[test-utf8.log](https://github.com/user-attachments/files/15915278/test-utf8.log)

**Comment by muzimuzhi** [comment]
The rollback code for `\g__para_standard_everypar_tl` labeled `minipage fix` has two versions. Rolling back to 2024/05/01 applies the 2023/06/01 version, thus it's OK that the 2021/06/01 version logs "Already applied".
```
Applying: [2023/06/01] minipage fix on input line 9899.
Already applied: [2021/06/01] minipage fix on input line 9924.
```

It seems the 2023/06/01 version lacks something like
https://github.com/latex3/latex2e/blob/022e71422ed86784d086d252e0c3e47b4e51238e/base/ltpara.dtx#L851-L857

**Comment by FrankMittelbach** [comment]
what I'm not so sure about is the question of whether or not this can wait until the fall release (not being able to roll back to the 2023-11 release) or wther that should go into a  hotfix

**Comment by josephwright** [comment]
We should fix asap I guess: PL is really no major issue

**Comment by FrankMittelbach** [comment]
In that case the code should go into a hotfix and the ltnews entry only in develop with a mentioning that this was already resolved as a hotfix in PL2

**Comment by FrankMittelbach** [comment]
in PL2
