### ISSUE TITLE
Hook `enddocument/info` is written twice if rolled back

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1407]
## Brief outline of the bug

If LaTeX is rolled back to 2020-10-01 or later, `enddocument/info` hook is written twice, once by the format and once by rollback code. This causes the file list (if enabled), end document warnings (if exist), and release info written to log twice.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\RequirePackage[2023-11-01]{latexrelease}
\documentclass{article}

\ShowHook{enddocument/info}

\begin{document}
\end{document}
```
shows in the log
```
-> The hook 'enddocument/info':
> Code chunks:
>     kernel/filelist -> \@dofilelist \@dofilelist 
>     kernel/warnings -> \@enddocument@kernel@warnings \@enddocument@kernel@war
nings 
>     kernel/release -> \let \show@release@info \wlog \show@release@info { ****
*******}\the \LaTeXReleaseInfo \show@release@info { ***********}\let \show@rele
ase@info \wlog \show@release@info { ***********}\the \LaTeXReleaseInfo \show@re
lease@info { ***********}
> Document-level (top-level) code (executed last):
>     ---
> Extra code for next invocation:
>     ---
> Rules:
>     kernel/warnings|kernel/filelist with relation >
>     kernel/release|kernel/filelist with relation <
> Execution order (after applying rules):
>     kernel/release, kernel/filelist, kernel/warnings.
<recently read> }
                 
l.5 \ShowHook{enddocument/info}
```

## Log file (required) and possibly PDF file  

[enddocument-info-hook-doubly-written.log](https://github.com/user-attachments/files/16156852/enddocument-info-hook-doubly-written.log)

## Related source code

- `\IncludeInRelease{2023/11/01}`
  https://github.com/latex3/latex2e/blob/0a5276b0c3c056219b18e361952853e02ef41d20/base/ltmiscen.dtx#L279-L285
- `\IncludeInRelease{2020/10/01}`
  https://github.com/latex3/latex2e/blob/0a5276b0c3c056219b18e361952853e02ef41d20/base/ltmiscen.dtx#L392-L398

**Comment by FrankMittelbach** [comment]
I guess the solution is to clear the hook first since we do not know from which version we roll back and none of the later code should be there.

**Comment by muzimuzhi** [comment]
Or skip both the `\NewHook{<hook>}` and `\AddToHook{<hook>}{<code>}` if such `<hook>` already exists?

**Comment by FrankMittelbach** [comment]
\NewHook is needed in case of roll forward and it is properly handled/suppressed by the rollback code, so I think it is correct the way it is
