### ISSUE TITLE
eliminating ".tex" file special case in kpathsea

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#1412]
(Since no one answered my July 1 mail to latex-team, I'll try here.)

Due to LaTeX's ".tex" file, there has always been a special case in kpathsea to allow writing a file named ".tex" (no other dot files are allowed). I'd like to eliminate the special case (for TL25), since nefarious people could in theory use it and most users probably wouldn't think twice about it. It's not technically more of a security issue than being able to write anything, but still, it would be nice to get rid of it for safety and simplicity.

Right now I gather `.tex` is created in the current directory by
tools.ins: `\generate{\file{.tex}{\from{fileerr.dtx}{return}}}`. If I change kpathsea, that write will fail.

The simplest way I can think of to handle this is to have the dtx write to a temp file, say `tmpdot.tex`, and then move it to `.tex` outside of TeX, as part of making the distribution.  If there's some other way to handle it, then great.

wdyt? --thanks, karl.

**Comment by davidcarlisle** [comment]
sorry the email dropped through the cracks.

Another possibility would be not to generate `.tex` at all but simply have it included in the source distribution.

**Comment by kberry** [comment]
Another possibility would be not to generate `.tex` at all but simply
    have it included in the source distribution.

Sure, that sounds simplest of all. I just didn't know if you'd up for
having a non-dtx-generated file :).  --thanks, karl.

**Comment by FrankMittelbach** [comment]
> Sure, that sounds simplest of all. I just didn't know if you'd up for having a non-dtx-generated file :). --thanks, karl.

CTAN will tell us off for it --- a code file without source ---, but we can refer them to you then :-)

more seriously it probably needs a bit juggling with the set up, but it should be doable, and no it didn't fell through the cracks, at least not here, only I didn't want to address it before Prague, especially not as somebody wants slides in time and I had originally planned for a mindmap  talk (my bad I should have realized beforehand that this would become a requirement)

**Comment by FrankMittelbach** [comment]
I guess what needs happening is that we have to put the .tex explicitly on github and make sure that it gets copied into the ctan upload.

In addition we probably have to comment out the extration in the .ins file so that Karl's scripts don't generate an error. However, I would prefer to leave that in the .ins file if possible. Thus, @kberry do you really run the .ins files for the latex format or do you simply use the tds tree we provide?

**Comment by davidcarlisle** [comment]
@FrankMittelbach  if we leave it in it will hit any end users (not just karl) who run the docstrip on base.
It might be safer to generate something like `empty.tex` and have l3build (at least) rename it.

**Comment by FrankMittelbach** [comment]
ah true ... then perhaps the .ins file should contain a `\Msg` line telling people to rename that file at the OS level manually.
And perhaps the name should be longer, e.g., `rename-me-with-empty-base-name.tex`  after all "empty.tex" is not an unlikely real name.

**Comment by FrankMittelbach** [comment]
anyway, please sort ot out ... I'm intending to have some vacation :-)

**Comment by davidcarlisle** [comment]
@kberry  as far as I can see the restriction on writing "dot files" does not apply to a texlua script calling 

```
os.execute("mv something.tex .tex")
```

so the pull request https://github.com/latex3/latex2e/pull/1466  writes something safe from tex and then renames it in the build script (or you would have to rename during texlive integration if not using the supplied tds zip file)

does that sound reasonable?

**Comment by kberry** [comment]
Indeed, there are no restrictions on texlua (only luatex). Renaming
after creation sounds good to me.

I do use your (and all non-erroneous) tds.zip's, so it won't make a
difference to the TL-updating process.

I'll make the change in the kpse code after a latex release is made with
this change. There is no hurry at all.

Thanks much. -k
