### ISSUE TITLE
Size and hash of historic version of a package

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1413]
## Brief outline of the bug

If LaTeX rollback causes loading of historic version of a package, in `\listfiles[sizes, hashes]` output, the logged package info (date, version, etc.) is of historic version, while the size and hash are of the  latest version.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
% \RequirePackage[2023-11-01]{latexrelease}
\documentclass{article}
\usepackage{array}

\listfiles[sizes, hashes]

\begin{document}
\end{document}
```
gives
```
 *File List*
...
   array.sty    2024/06/14 v2.6d Tabular extension package (FMi)
    (size 14067, hash 1383BD6EE23AB18AE0E796155404DEB7)
...
```
and uncomment the `\RequirePackage[2023-11-01]{latexrelease}` gives
```
 *File List*
...
latexrelease.sty    2022/11/14 v1.0p LaTeX release emulation and tests (includi
ng releases up to 2024-06-01)
    (size 710925, hash 156BFC1ADA060CE40F75D50ACCE69C2D)
...
   array.sty    2023/10/16 v2.5g Tabular extension package (FMi)
    (size 14067, hash 1383BD6EE23AB18AE0E796155404DEB7)
...
```

Note that the date and version of `array.sty` changed, while the size and hash didn't. Thus the package info and size/hash don't match.

For rolled back packages maybe each of their two versions (here `array.sty` and `array-2023-11-01.sty`) need an entry in `\listfiles` output.

## Log file (required) and possibly PDF file  

[sizes-and-hashes-of-rolled-back-packages.log](https://github.com/user-attachments/files/16193771/sizes-and-hashes-of-rolled-back-packages.log)

**Comment by muzimuzhi** [comment]
> For rolled back packages maybe each of their two versions (here `array.sty` and `array-2023-11-01.sty`) need an entry in `\listfiles` output.

Refer to how `\@input@` is defined, adding `\@addtofilelist{#1}` before a historic version is loaded by `\@@input <filename>\relax` seems to fix the bug here.
https://github.com/latex3/latex2e/blob/c2f7848d5e58b40a209f5af1d920158a42906bbf/base/ltfiles.dtx#L1531-L1533

Side question: how to test against the change of `\listfiles[sizes, hashes]` output in a portable and smooth (no need to update testfile after new package release) way?

```tex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\RequirePackage[2023-11-01]{latexrelease}
\documentclass{article}

\makeatletter
\def\pkgcls@use@this@release#1#2{%
   \pkgcls@show@selection{#1}{#2}%
   \pkgcls@targetdate\z@
   \@addtofilelist{#1}% <<< added
   \@@input #1\relax
   \endinput
}
\makeatother

\usepackage{array}

\listfiles[sizes, hashes]

\begin{document}
\end{document}
```
Excerpted Log
```
   array.sty    2023/10/16 v2.5g Tabular extension package (FMi)
    (size 14067, hash 1383BD6EE23AB18AE0E796155404DEB7)
array-2023-11-01.sty
    (size 12587, hash A31DD046F448E0F10D598DB28081A110)
```

PS: The example above would complain that `array-2023-10-01.sty` is a third-party package. I've opend https://github.com/latex3/latexbug/pull/7 to fix this.

**Comment by muzimuzhi** [comment]
> Excerpted Log
> 
> ```
>    array.sty    2023/10/16 v2.5g Tabular extension package (FMi)
>     (size 14067, hash 1383BD6EE23AB18AE0E796155404DEB7)
> array-2023-11-01.sty
>     (size 12587, hash A31DD046F448E0F10D598DB28081A110)
> ```

Hmm, the date and version are still not matching.

**Comment by josephwright** [comment]
> Hmm, the date and version are still not matching.
> 
> I think that's because `<pkgname>-yyyy-mm-dd.sty` pretends it provides the original `<pkgname>.sty` rather than itself (`<pkgname>-yyyy-mm-dd.sty`).

I think that's OK - the reason for having the info here is to allow us to check that that package versions are 'as expected'.

**Comment by josephwright** [comment]
@muzimuzhi  Fancy making a PR?

**Comment by muzimuzhi** [comment]
Yes I'm preparing a PR which would give better results.
