### ISSUE TITLE
ltkeys: Omitting `=` while defining a key throws low level error

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex2e#1415]
## Brief outline of the bug

When you omit the equals sign in a key definition in `\keys_define:nn` and use one of the property names for the `ltkeys` layer you get a low level TeX error (for the corresponding `l3keys` layer names everything works as expected and you get a missing value error).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!

\DeclareKeys{foo .code}

\stop
```

Happens with every other key property, because they all use the faulty call to `\__keys_define_code:w`.

## Log file (required) and possibly PDF file  

The log is quite short so I put it here instead of attaching it.

```
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=pdflatex 2024.7.5)  13 JUL 2024 23:29
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**ltkeysbugreport.tex
(./ltkeysbugreport.tex
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-05-27>
)
Runaway argument?
.code\s__keys_stop {\use:c {\c__keys_props_root_str \l__keys_property_str \ETC.
! File ended while scanning use of \__keys_define_code:w.
<inserted text> 
                \par 
<*> ltkeysbugreport.tex
                       
? 
! Emergency stop.
<inserted text> 
                \par 
<*> ltkeysbugreport.tex
                       
End of file on the terminal!

 
Here is how much of TeX's memory you used:
 14 strings out of 473584
 376 string characters out of 5728335
 1925905 words of memory out of 5000000
 23006 multiletter control sequences out of 15000+600000
 558069 words of font info for 36 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 12i,0n,23p,77b,8s stack positions out of 10000i,1000n,20000p,200000b,200000s
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by Skillmon** [comment]
The issue actually is that it is assumed that every key property name contains a `:` by `\@@_define_code:n` which uses `\@@_define_code:w` in case there was a missing value in order to throw the error message of a required value. Since the legacy names don't include a `:` that fails, but all legacy properties (currently) require a value, so one can make a rather simple change to that test to either throw the error if there is no colon at all, or if one is found use the current logic.

**Comment by Skillmon** [comment]
Also, this is sort of fixed in current `develop`, but the fix there is wrong, imho, as instead of throwing the appropriate error that fix silently ignores the `ltkeys` names requiring a value, potentially leading to other errors down the line. If that behaviour is indeed preferred by the team, at least the documentation is wrong on that part because of the following wording:

```latex
%   otherwise execute it. There is no need to check for a |:| as if it
%   was missing the earlier tests would have failed.
```

**Comment by Skillmon** [comment]
I can provide a fix that throws the errors if that's wanted.

**Comment by muzimuzhi** [comment]
Isn't this a latex3 issue?

> Also, this is sort of fixed in current `develop`, but the fix there is wrong, imho, as instead of throwing the appropriate error that fix silently ignores the `ltkeys` names requiring a value, potentially leading to other errors down the line.

The current fix https://github.com/latex3/latex3/commit/76bdd69d710136f9b223b77c32726f9b19bac13c (contained in latex3 [2024-06-19-dev](https://github.com/latex3/latex3/releases/tag/2024-06-19-dev) and available with dev formats) is indeed buggy.

```tex
% compile with one of -dev formats
\documentclass{article}

\ExplSyntaxOn
\keys_define:nn {mymod} {foo .code}
% \keys_show:nn doesn't support empty key module, see latex3/latex3#1279
\keys_show:nn {mymod} {foo}
\ExplSyntaxOff

\begin{document}
\end{document}
```
gives
```
! LaTeX Error: Missing \begin{document}.

The key mymod/foo has the properties:
>  code  =>  \str_set:Nn .
<recently read> }
```

The fix assumes that key properties containing no colons (`:`) in their names have zero arity (take no arguments), but such LaTeX2e key properties actually have arity 1. Therefore (using dev format), `\DeclareKeys{foo .code}` would wrongly take `\str_set:Nn` as the value of `.code`, and leaving `\l__keys_module_str {<value of \l__keys_module_str before `\DeclareKeys>}` in the input stream.

**Comment by Skillmon** [comment]
This is arguably a borderline thing, as the real issue only affects the `ltkeys` properties but the problematic code is in `l3keys`. I really wasn't sure where to open the issue, but decided to go for `ltkeys`, and that would be `2e`.

**Comment by josephwright** [comment]
Right, the PR is merged and will be out in `l3kernel-dev` today - shall I close or marked fixed-in-dev?

**Comment by muzimuzhi** [comment]
Is the agreement reached that LaTeX2e key properties never raise a missing value error?

**Comment by Skillmon** [comment]
Please, no. Except for one (`.code`) this doesn't make any sense. And even in `.code` it's questionable. I'd much prefer the always-error solution, which is both easier to code and more likely to catch user error (for the sole disadvantage to require one symbol more if you indeed want to set an empty key code).

**Comment by Skillmon** [comment]
@josephwright about the question whether the consensus should be that the LaTeX2e key properties never raise a missing value error. (that's how I understood @muzimuzhi's last message)

As a result, this is also a "no" towards the question whether this should be marked as fixed or closed, as I don't deem the proposed fix valid (though that's of course my own opinion about the matter, as always team has the last word).

**Comment by muzimuzhi** [comment]
Among the 6 existing LaTeX2e key properties, semantically
- `.if`, `.ifnot`, `.store`, and `.usage` always require a value;
- `.code` may accept a missing value and treat it as an empty value, though that rarely makes sence;
- `.pass-to-packages` treats missing value as `true` value.
  Its current user doc (in `clsguide`) is not explicit about the behavior on missing value, but its implementation clearly shows that.
  https://github.com/latex3/latex2e/blob/22375e7b5e90cc9638f62806f69a11aa532430e5/base/ltkeys.dtx#L195-L203

Maybe `l3keys` can store and make use of arity, an extra piece of info for LaTeX2e key properties.

**Comment by muzimuzhi** [comment]
> Maybe `l3keys` can store and make use of arity, an extra piece of info for LaTeX2e key properties.

Sorry, not "arity", but "if-value-required" or even "default value" of a LaTeX2e key _property_.
