### ISSUE TITLE
\renewcommand without any changes causes endless compile

### ISSUE THREAD

**Issue by chojje** [latex3/latex2e#142]
## Brief outline of the bug

Using renewcommand without making any changes causes compile to go on endlessly

## Minimal example showing the bug

```latex
\documentclass{article}
\usepackage[utf8]{inputenc}

\begin{document}

\newcommand{\hello}{hello\\world}
\hello\\ % should display line break (works)
{\renewcommand\\{ } \hello} % should replace line break with space (works)
{\renewcommand\\{\\} \hello} % should display line break (causes compile to run endlessly)

\end{document}
```

Expected outcome: The file compiles, with the desired command changes

Actual outcome: Compile runs endlessly

This was tested in Overleaf

**Comment by eg9** [comment]
The expected outcome *is* an endless loop. You are telling LaTeX “when you find `\\`, replace it with `\\`. The replacement text will be then looked at, which causes the replacement of `\\` with `\\`…

This is known and documented. No bug. You wrote an endless loop.
