### ISSUE TITLE
Macros defined with \newcommand are protected when they have an optional argument, but expand fully when they have no optional argument

### ISSUE THREAD

**Issue by LupinoTech** [latex3/latex2e#1422]
I noticed that macros defined with `\newcommand` behave differently inside a `\protected@edef` when they have an optional argument when compared to macros without optional argument:
```latex
\RequirePackage{latexbug}
\documentclass{article}

\title{}
\author{}
\parindent=0pt

\begin{document}

\makeatletter
\newcommand\macroA[2][]{\relax}
\newcommand\macroB[1]{relax}

\protected@edef\storageA{\macroA{}}
\protected@edef\storageB{\macroB{}}

\expandafter\verb\expandafter|\meaning\storageA| % macro->\protect\macroA{}
\expandafter\verb\expandafter|\meaning\storageB| % macro->\relax
\end{document}
```
[test.log](https://github.com/user-attachments/files/16439870/test.log) Is this behavior intended?

**Comment by FrankMittelbach** [comment]
Yes that's the intended behavior. People always used simple newcommands with the expection that they expand which is why in most places where data is expected there is at least a one level expansion (or a `\protected@edef`) so that instead of a string you can use a macro. Commands with optional argument would always break, which is why they are made robust.

**Comment by LupinoTech** [comment]
Just for the sake of completeness for someone who stumbles over the same issue: Defining the macros with `\DeclareRobustCommand` instead of `\newcommand` makes them both robust:
```latex
\RequirePackage{latexbug}
\documentclass{article}

\title{}
\author{}
\parindent=0pt


\begin{document}
\makeatletter
\DeclareRobustCommand\macroA[2][]{\relax}
\DeclareRobustCommand\macroB[1]{relax}

\protected@edef\storageA{\macroA{}}
\protected@edef\storageB{\macroB{}}

\expandafter\verb\expandafter|\meaning\storageA| % macro->\protect\macroA{}
\expandafter\verb\expandafter|\meaning\storageB| % macro->\protect\macroB{}
\end{document}
```

**Comment by muzimuzhi** [comment]
@LupinoTech Now (starting from LaTeX2e 2020-10-01) you also have `\NewDocumentCommand` which defines engine-protected commands (using prefix `\protected`) and `\NewExpandableDocumentCommand` which defines fully-expandable commands with some restriction. See `texdoc usrguide` (2024-05-24), sec. 2.4 and 2.12 for more info.
