### ISSUE TITLE
longtable leads to  leads to nesting error for links 

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#143]
## Brief outline of the bug

longtable adds a box around the output page. This leads to a fatal boxlevel nesting error if there are links at the page break before the longtable:

~~~~
! pdfTeX error (ext4): \pdfendlink ended up in different nesting level than \pd
fstartlink.
~~~~

## Minimal example showing the bug
Removing the marked \vbox avoids the fatal error, but this doesn't mean that this is a suitable fix, it only demonstrates that the additional box is the problem!

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{longtable}
\makeatletter
% copied from longtable.sty:
\def\LT@output{%
  \ifnum\outputpenalty <-\@Mi
    \ifnum\outputpenalty > -\LT@end@pen
      \LT@err{floats and marginpars not allowed in a longtable}\@ehc
    \else
      \setbox\z@\vbox{\unvbox\@cclv}%
      \ifdim \ht\LT@lastfoot>\ht\LT@foot
        \dimen@\pagegoal
        \advance\dimen@-\ht\LT@lastfoot
        \ifdim\dimen@<\ht\z@
          \setbox\@cclv\vbox{\unvbox\z@\copy\LT@foot\vss}%
          \@makecol
          \@outputpage
          \setbox\z@\vbox{\box\LT@head}%
        \fi
      \fi
      \global\@colroom\@colht
      \global\vsize\@colht
      \vbox %<--- removing this box avoids the error
        {\unvbox\z@\box\ifvoid\LT@lastfoot\LT@foot\else\LT@lastfoot\fi}%
    \fi
  \else
    \setbox\@cclv\vbox{\unvbox\@cclv\copy\LT@foot\vss}%
    \@makecol
    \@outputpage
      \global\vsize\@colroom
    \copy\LT@head\nobreak
  \fi}
\makeatother
\begin{document}

\vspace*{41\baselineskip}
\leavevmode\pdfstartlink
  attr {/Border[0 0 1]}
  user{
       /Subtype/Link%
       /A<<%
         /Type/Action%
         /S/URI%
         /URI(https://www.latex-project.org/)%
       >>%
      } 
      
some long text that goes over lines\\
some long text that goes over lines\\
some long text that goes over lines\\
some long text that goes over lines
\pdfendlink
      
\begin{longtable}{l}
a longtable
\end{longtable}
\end{document}
```

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/3088442/test-utf8.log)

**Comment by davidcarlisle** [comment]
That vbox causes other issues as well

http://www.latex-project.org/cgi-bin/ltxbugs2html?pr=tools/3479

http://www.latex-project.org/cgi-bin/ltxbugs2html?pr=tools/2373

The longtable V5 experiments at

https://github.com/davidcarlisle/dpctex/blob/master/longtable/longtable.dtx#L2053

remove this except for V4 compatibility but the V5 code is stalled and not generally usable at present.

The reason that the box was added originally (and this is still not addressed in v5) is that after the table finishes the output routine reverts to the standard one which handles the rest of the page below the table, currently that output routine has no information that the top part of the table is the end of a longtable so it can  insert top floats into the page splitting the table with another table... However it should I think be enough to do effectively `\supressfloats[t]` in the endlongtable code and not have the box.

**Comment by car222222** [comment]
It also gives another example of a known problem with the heuristic used by pdftex internals for what to “include in a link” This “same box level” idea is not optimal, so we need to think about whether it should or can be improved on.  But for now all we can do us try to fix those parts of latex we know about.  Does luatex deal with this more flexibly (out-of-the-box)?

**Comment by u-fischer** [comment]
@car222222  The luatex primitive has the same problem: I asked about the startlink/endlink on the luatex list https://mailman.ntg.nl/pipermail/dev-luatex/2018-December/006148.html, but the answer was not promising. I don't know what context does to avoid such problems, but I suspect that they actually don't  use this functions at all but create the annotations with lua-code.

**Comment by u-fischer** [comment]
@davidcarlisle  I don't understand the remark about top floats. Even with the current code tables can move before the last part of a longtable:

~~~~
\documentclass{article}
\usepackage{longtable}
\begin{document}

\vspace*{41\baselineskip}

\begin{longtable}{l}
a longtable\\
a longtable\\
a longtable\\
a longtable\\
a longtable\\
a longtable\\
\end{longtable}%\suppressfloats[t]

\begin{table}%[t]
a table
\end{table}
\end{document}
~~~~

**Comment by davidcarlisle** [comment]
@u-fischer yes sure, I only said that's why it was added, not that it worked:-)  it does of course prevent some cases, as the LT rows can not be split but a float could still be inserted at the top above all the rows if that fits. It was all a long time ago, written for 2.09 before \suppressfloats was a documented thing.

**Comment by FrankMittelbach** [comment]
Am 17.04.19 um 11:46 schrieb David Carlisle:
> \suppressfloats was a documented thing

or even available :-)

**Comment by car222222** [comment]
@u-fischer    “I suspect that they actually don't use this functions at all but create the annotations with lua-code”

Sounds very likely, but that lua code must itself need “to decide” what to include, so it would be useful to know what heuristic it uses(and whether/how it works in the Context context.  So, Needs further investigation, as does whether “box nesting depth” can be made to work, provided pakage writers etc “follow the rules” we give.

**Comment by leomayer** [comment]
Since I'm the initiator of this bug with the friendly help of Ulrike I want to report that the proposed fix works in my situation perfectly. I tried as well `\supressfloats` without any success. Would be great if this issue could be fix finally. At least this proposed fix is better than the current situation.
V5 of longtable seems to be not really maintained. I mean 20yrs back the last changes where annoted. I guess a fix there is rarely doable - if at all. Sounds like a rotten bug which will continue its degeneration.

**Comment by davidcarlisle** [comment]
The engine level pdftex warning is now a warning not an error, and the vbox is removed in longtable 4.15 in the dev release so theer is no warning at all there.
