### ISSUE TITLE
Label redefinition - with just one label

### ISSUE THREAD

**Issue by the-snork** [latex3/latex2e#1436]
## Brief outline of the bug
When compiling given file, something is messed up with the label. For the first two runs, there is a warning about a changed reference and for the third run, a warning regarding a multiply defined label is given. The resulting label in the output is not the figure number in this case, but the section number of the section containing the list of figures.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{book}
\begin{document}

\subsection{YYY}

\begin{figure}
\centering{}\caption{\protect\label{fig:xxx}XXX}
\end{figure}

Ref~\ref{fig:xxx}. \listoffigures

\end{document}

```

## Log file (required) and possibly PDF file  

[run1.log](https://github.com/user-attachments/files/16573450/run1.log)
[run2.log](https://github.com/user-attachments/files/16573451/run2.log)
[run3.log](https://github.com/user-attachments/files/16573452/run3.log)

[Archiv.zip](https://github.com/user-attachments/files/16573453/Archiv.zip)

**Comment by FrankMittelbach** [comment]
There is no bug :-).  Remove the \protect in your source it is wrong because it ensure that the \label is written into the list of figures file rather than being removed on the way to it -- therefore multiple labels on the third run.
