### ISSUE TITLE
`letter.cls` documentation contains offensive term

### ISSUE THREAD

**Issue by leingang** [latex3/latex2e#1439]
This is a request for documentation enhancement only, and does not refer to any functionality. 

# Issue

One of the examples in the `letter.cls` documentation ([line 843 of `letter.dtx`](https://github.com/latex3/latex2e/blame/22964cc5f5669e36abef76b2604c5a9e10435883/base/letter.dtx#L843)) contains a placeholder name for an institution. The name is a play on the real-life Institute for Advanced Study. It uses an antonym for _advanced_, which was, at one time, the accepted medical term for people with intellectual disabilities. Today the term is most often considered offensive, and the word itself is frequently avoided.

# Proposed Solution

Change the placeholder name to something like _Institute for Trivial Study_, _Institute for Rudimentary Study_, _Institute for Antediluvian Study_, or any other term that maintains the original intent (to spoof on IAS) but avoids this outdated usage.

# References

* [US Social Security Administration rule on terminology](https://www.federalregister.gov/documents/2013/08/01/2013-18552/change-in-terminology-mental-retardation-to-intellectual-disability) August 1, 2013. In the public comment phase of the proposed rule change, 71 of 76 commenters enthusiastically supported replacing the term.
* [Merriam-Webster's Dictionary definition](https://www.merriam-webster.com/dictionary/retarded) N.B. the annotation _dated_, _now offensive_
* [Google ngram for the word,  1800–2019](https://books.google.com/ngrams/graph?content=retarded%2C&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3)

**Comment by GabbySeligman** [comment]
I kind of like the old term.
