### ISSUE TITLE
latex-dev:  version is required in luatexbase.provides_module

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#1443]
## Brief outline of the bug

in latex-dev  `ltluatex.lua` now formats the version field with `string_gsub`:

~~~~
.. spaced(string_gsub(info.version,"^(%d)","v%1"))
~~~~

This makes `version` a required field and lua files without a version field error:

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\begin{filecontents}[noheader,overwrite]{testlua.lua}
luatexbase.provides_module({
  name = 'test',
  date = '2024-08-16',
  description = 'test of missing version',
})

\end{filecontents}

\documentclass{article}

\directlua{require("testlua.lua")}
\begin{document}
blub
\end{document}
```
errors with 

~~~~
bibindent=\dimen140
)...ocuments/gitinstalltexmf/tex/latex-dev/base/ltluatex.lua:67: bad argument #1
 to 'string_gsub' (string expected, got nil)
stack traceback:
	[C]: in function 'string.gsub'
	...ocuments/gitinstalltexmf/tex/latex-dev/base/ltluatex.lua:67: in field 'provi
des_module'
	./testlua.lua:1: in main chunk
	[C]: in function 'require'
	[\directlua]:1: in main chunk.
l.198 \directlua{require("testlua.lua")}
~~~~

This affects for example the luatexja package where the lua-files typically do not have a version field.

**Comment by muzimuzhi** [comment]
A regression caused by 3f91918d (Mark "v" in provides_module() when logging version string, 2024-06-04) in supporting https://github.com/latex3/latex2e/issues/1364.

Does this work:
```lua
info.version ~= nil and string_gsub(info.version,"^(%d)","v%1") or ""
```

**Comment by josephwright** [comment]
I think just 
```lua
string_gsub(info.version and info.version or "","^(%d)","v%1")
```
should do it.

**Comment by muzimuzhi** [comment]
Agreed. I'm too worried about falsy values (in this case `info.version` won't be `false`), see https://github.com/latex3/l3build/issues/265.
