### ISSUE TITLE
\includegraphics does not find images from the -output-directory

### ISSUE THREAD

**Issue by MeanSquaredError** [latex3/latex2e#145]
There is a bug in the graphicx package which prevents \includegraphics from including a valid image which is located in the graphics path. The bug show up when the following conditions are met:

- We are using pdflatex on Linux.
- An directory is listed in \graphicspath, in the example below it is /root/texout/
- That directory contains a valid .pdf file, in the example below it is myimg.pdf
- The \includegraphics macro includes an image specified by its filename only (with or without an extension). In our example it is called "myimg" (without the double quotes).
- The compiled tex file is placed in a directory which is different from the directory that contains the image file and the current directory is not an ancestor directory of the directory with the image file.
  In our example the .tex file is in /root/archive/downloads/zzz/graphics_bug.tex.
- When we invoke pdflatex our current directory is the directory that contains the tex file. In our case the current directory is /root/archive/downloads/zzz/
- pdflatex is run from a current directory
- The directory that contains the .pdf file is specified as an output directory of pdflatex. In our case the pdflatex is invoked as:
  pdflatex -output-directory=/root/texout/ ./graphics_bug.tex

This is the sample file located in /root/archive/downloads/zzz/graphics_bug.tex
```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\begin{document}
\graphicspath{{/root/texout/}}
\includegraphics{myimg}
\end{document}
```

pdflatex should be able to find and include successfully the file myimg.pdf, but instead it shows the following error:
```latex
! Package pdftex.def Error: File `myimg.pdf' not found: using draft setting.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.8 \includegraphics{myimg}
```

If we run pdflatex without the -output-directory argument, then the file is compiled successfully:

```
Output written on graphics_bug.pdf (1 page, 8989 bytes).
Transcript written on graphics_bug.log.
```

This bug is caused by the fact that \includegraphics uses \IfFileExists which is able to find graphics_bug.pdf in the output directory, but the corresponding \pdffilesize and \pdfximage are not able to find it.

More specifically, when we call \includegraphics the call chain goes like this:
```latex
\includegraphics ->
\Gin@i ->
(optional) \Gin@ii ->
(optional) \Gin@iii ->
\Ginclude@graphics ->
\Gin@getbase ->
\IfFileExists ->
\openin
```
The \openin primitive uses the function texlive-20180414-source/texk/web2c/lib/openclose.c:open_input
which checks if the -output-directory is specified. If it is, then the function tries opening the input
file from that directory. If that fails, then it tries the regular kpse_find_file function.

More specifically the code looks like this:
```
    /* Look in -output-directory first, if the filename is not
       absolute.  This is because .aux and other such files will get
       written to the output directory, and we have to be able to read
       them from there.  We only look for the name as-is.  */

    The code tries to open the file in the output directory

    /* No file means do the normal search. */

    The code then does the normal search through kpse_find_file
```

This means that if an output directory has been specified as an argument to pdftex, then the \openin primitive will always check first for a relative pathname in the output directory.

In turn it means that if a file is placed in the output directory, then the LaTeX macro \IfFileExists macro will always find that file and the \@filef@und macro will be set to the name of the searched file with a trailing space. In this case \@filef@und will be just a filename without an absolute path unlike the case when the file would be found by \IfFileExists -> \@iffileonpath in one of the input paths specified in \input@path (which is equal to the graphics path in this case)

The filename from \@filef@und is used passed to pdftex.def:Gread@pdftex which uses \pdffilesize and \Gread@@pdftex -> \pdfximage to read the actual PDF file. However neither \pdffilesize nor \pdfximage check for the input file in the output directory as does \IfFileExists, so the attempt to include the graphics file fails.

This is obviously a bug, but I am not sure what is the correct fix in this case. I have implemented a workaround by replacing \IfFileExists with \@iffileonpath

```latex
\def\Gin@getbase#1{%
  \edef\Gin@tempa{%
    \def\noexpand\@tempa####1#1\space{%
      \def\noexpand\Gin@base{####1}}}%
  \@iffileonpath{\filename@area\filename@base#1}%
    {\Gin@tempa
     \expandafter\@tempa\@filef@und
     \edef\Gin@ext{#1}}{}}%
```

This works for me, but it also means that \includegraphics uses only the graphics
path and completely ignores the TEXINPUTS search path.

## Log file (required) and possibly PDF file  
[graphics_bug.log](https://github.com/latex3/latex2e/files/3140245/graphics_bug.log)

**Comment by wspr** [comment]
Thanks for the excellent bug report!

**Comment by MeanSquaredError** [comment]
You are welcome :-)

It seems that the github markup language messed up the bugreport a little bit by removing the backslashes from the \ @ macro names, but I think it is still readable.

I am still unsure of the optimal way to fix the issue.

One possible solution would be to change the graphics macro(s) so that they would only find files in the graphics path or the tex input path.

Another approach would be to update the \pdf* primitives so that they would search the output directory pretty much like \openin does.

A third solution would be just to document this behavior and call it a feature instead of bug :-)

**Comment by davidcarlisle** [comment]
I would say that this arguably a pdftex bug and should be fixed there
rather than in the macro layer.

(Personally I always advise people not to use -output-directory which
complicates the entire pipeline as you need to configure every other
program to find the files that have been moved, however in this case it is
pdftex itself that is not finding the files, I think \pdffilesize argualbly
should be using the same search logic as \openin.)

However the documented behaviour is to search TEXINPUTS so it would seem
the natural thing to do if the image file is in /root/texout is to add that
to TEXINPUTS rather than relying on specifying that as an output directory
having a side effect of adding it to the input path?

**Comment by MeanSquaredError** [comment]
In my case the graphics are kept as .odt files, then the build process creates temporary .pdf files and runs pdflatex which creates the main .pdf files. I would like to avoid building the temporary image .pdf files in the source directory because it would complicate the version control. So -output-directory is one possible solution. Adding the output directory to TEXINPUTS seems like the optimal approach indeed, but only after one knows what is causing the problem. So it would be nice to fix the discrepancy between \openin and \pdf* because it can really confuse people like it did in my case with \graphicspath and \includegraphics.

If one of the latex developers is not working on the fix, I can try creating and submitting a pull request with a proposed fix to \pdf* that would enable these functions to check the output directory regardless of the .tex search path.

**Comment by u-fischer** [comment]
On windows it works in miktex (both with `--output-directory` and `--aux-directory`) but it fails in texlive 2019. But like David I never use this options (and so was actually quite surprised that they can write to external folders - that's something I don't like at all, I created with a type by accident a folder in C:).

**Comment by davidcarlisle** [comment]
Especially given that it works in miktex, I think raising it on texlive list would be best, especially if you could suggest a patched code, thanks.

**Comment by MeanSquaredError** [comment]
This has been fixed in the development tree of Tex Live
https://tug.org/pipermail/tex-k/2019-May/003015.html

**Comment by davidcarlisle** [comment]
Thanks for sorting this out and pushing the fix to texlive
