### ISSUE TITLE
Documentation of \ShowCommand

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1458]
source2e.pdf, page 100, File 06: ltdefns.dtx Date: 2024/04/17 Version v1.5t, 1.5.2 Showing robust commands, `\ShowCommand`, second sentence: 
"the command’s is detected to has a given type of robustness"
That does not sound like proper English.
Also, when editing there anyway: In the third sentence, please use a \newline after the colon (overfull line).
And the next command `\@showcommandlisthook` is printed in the margin one line too late.
Thank you!

**Comment by muzimuzhi** [comment]
https://github.com/latex3/latex2e/blob/fc85575fbc5a668db69c98fa6568504559343941/base/ltdefns.dtx#L1773-L1777

Does this read better?
```diff
%   Most of the machinery defined for \cs{NewCommandCopy} can be used to show
%   the definition of a robust command, in a similar fashion to \texttt{texdef}.
-%   The difference is that after the command's is detected to has a given type
+%   The difference is that after the command is detected to has a given type
%   of robustness, rather than making a copy, we use a separate routine to show
%   its definition.
```

**Comment by car222222** [comment]
Better Grammar: 😀 
. . . is detected to have a given . . .

**Comment by FrankMittelbach** [comment]
> And the next command `\@showcommandlisthook` is printed in the margin one line too late.

That is something that is due to the rather fragile definitions in ltxdoc and its overwrites. Happens probably because the margin is too small in the  setup for source2e. Not something I would spend time on debugging or fixing given that the class does need a rewrite anyway (one day).

The other issues have been addressed, thanks.
