### ISSUE TITLE
array change in 2018-04-30?

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#146]
## Brief outline of the bug

The output of a MWE posted on  https://tex.stackexchange.com/questions/159257/increase-latex-table-row-height/159260#159260 is different after "array.sty" 2018-04-30 update.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{array}%[=2018-04-29]

\newcolumntype{M}[1]{>{\centering\arraybackslash}m{#1}}
\newcolumntype{N}{@{}m{0pt}@{}}


\begin{document}

\begin{table}[ht]
\begin{tabular}{|M{4cm}|M{4cm}|N}
\hline
\textbf{Text} & \textbf{Text} &\\[50pt]
\hline
text & text&\\[50pt]
\hline
\end{tabular}
\end{table}

\end{document}
```

### Before 2018-04-30 update

<img width="325" alt="array-20161006" src="https://user-images.githubusercontent.com/9957466/58747541-6fb44200-84a7-11e9-9005-5ac51efb22da.png">

### After 2018-04-30 update

<img width="339" alt="array-20180430" src="https://user-images.githubusercontent.com/9957466/58747514-12b88c00-84a7-11e9-9eac-e3951cad434e.png">

## Log file (required) and possibly PDF file  

[sx159260.log](https://github.com/latex3/latex2e/files/3243689/sx159260.log)

**Comment by davidcarlisle** [comment]
This was the intent of the change. the `\\[50mm]` is documented as applying to the row and the spacing you get now is the same if the columns  were `cm{3cm}` or `m{3cm}c`  with the old definition, if the `m` column was the last one on the row, the extra depth got added before the vertical centering so only half the depth got added, the rest being added to the height.

**Comment by aminophen** [comment]
> This was the intent of the change.

I understand. Thanks for your answer.

**Comment by aminophen** [comment]
The reason why I asked here is that \usepackage{array} → \usepackage{arydshln} behaves the same as old version of array; now I understand that the change of array is intended, I think arydshln needs updated. I'll report to the author.

**Comment by FrankMittelbach** [comment]
> The reason why I asked here is that \usepackage{array} → \usepackage{arydshln} behaves the same as old version of array; now I understand that the change of array is intended, I think arydshln needs updated. I'll report to the author.

that would be appreciated. I had it on my list to do but didn't got around so far. This is really a longstanding bug and even though there are uses like your example, that made use of the incorrect implementation (with hidden columns) it is just not right.
