### ISSUE TITLE
\thetotalpages does not match documented value

### ISSUE THREAD

**Issue by viccie30** [latex3/latex2e#1470]
## Brief outline of the bug

According to the documentation [`\thetotalpages` "expands to the number of total pages from the previous run"](https://github.com/latex3/latex2e/blob/bdb49dc7cff52d4fe224fdf41eb1e26f02fa033a/base/ltshipout.dtx#L472), but it actually [prints `\g_shipout_totalpages_int`](https://github.com/latex3/latex2e/blob/bdb49dc7cff52d4fe224fdf41eb1e26f02fa033a/base/ltshipout.dtx#L1652-L1666) which is the counter of pages in the current run so far. Either the definition should be changed to match the documentation or the other way around.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\RequirePackage{lipsum}

\documentclass{report}

\makeatletter
\def\@oddfoot{%
  \hfil \thepage \space of \thetotalpages\space (\textbackslash thetotalpages) \hfil
  \thepage \space of \PreviousTotalPages\space (\textbackslash PreviousTotalPages) \hfil}

\begin{document}
\lipsum[1-20]
\end{document}
```

## Log file (required) and possibly PDF file  

[mwe.log](https://github.com/user-attachments/files/17027800/mwe.log)

**Comment by u-fischer** [comment]
that looks like a documentation bug, `\thetotalpages` belongs to the paragraph before, to the `totalpages` counter.
