### ISSUE TITLE
\newcolumntype doesn't emit any warning for the redefinition of a primitive type of column

### ISSUE THREAD

**Issue by fpantigny** [latex3/latex2e#148]
## Brief outline of the bug
The command `\newcolumntype` of `array` should emit a warning when used with a primitive column type and it doesn't. I think it's a bug in the programmation.

## Minimal example showing the bug

```latex
\RequirePackage{array}
\documentclass{article}
\begin{document}
\newcolumntype{c}{l}
$\begin{array}{cc}
a+b+c & a \\
d & e 
\end{array}$


\end{document}
```
I think a `\noexpand` should be deleted in the line 244 of `array.sty` (latest version:  v2.4k 2018/12/30)
[MWE.log](https://github.com/latex3/latex2e/files/3360077/MWE.log)

**Comment by davidcarlisle** [comment]
oh thanks, I think the intended code was

`\if\expandafter\noexpand\next\NC@char`

(in case array was read in after ! was made active by babel etc) but it's been wrong since at least 2005 (oldest version in this git)

**Comment by davidcarlisle** [comment]
The old svn shows march 1994:
 ```
 

@@ -2094,7 +2093,7 @@
 % the list "\NC@list".
 %    \begin{macrocode}
   \@ifundefined{NC@find@\NC@char}%
-    {\@tfor\next:=<>clrmbp@!|\do{\if\next\NC@char
+    {\@tfor\next:=<>clrmbp@!|\do{\if\noexpand\next\NC@char
                     \@warning{Redefining primitive column \NC@char}\fi}%
      \NC@list\expandafter{\the\NC@list\NC@do#1}}%
     {\@warning{Column \NC@char\space is already defined}}%
@@ -2436,39 +2435,6 @@
 % \end{macro}
 % \end{macro}
```
