### ISSUE TITLE
checkencodingsubset.tex shouldn't use undefined cs \Providesfile

### ISSUE THREAD

**Issue by cfr42** [latex3/latex2e#1496]
## Brief outline of the bug

Undefined cs in `checkencodingsubset.tex`.

## Minimal example showing the bug

Project's file: `checkencodingsubset.tex`

```bash
 $ (cd /tmp/ ; latex checkencodingsubset)
```

## Output

```latex
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/checkencodingsubset.tex
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-09-10>
! Undefined control sequence.
l.45 \Providesfile
                  {checkencodingsubset.tex}
? x
No pages of output.
Transcript written on checkencodingsubset.log
```

## Log

```latex
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=latex 2024.10.17)  17 OCT 2024 20:08
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**checkencodingsubset
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/checkencodingsubset.tex
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-09-10>
! Undefined control sequence.
l.45 \Providesfile
                  {checkencodingsubset.tex}
? x

Here is how much of TeX's memory you used:
 14 strings out of 473580
 490 string characters out of 5728259
 386800 words of memory out of 5000000
 23011 multiletter control sequences out of 15000+600000
 558069 words of font info for 36 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 12i,0n,13p,94b,8s stack positions out of 10000i,1000n,20000p,200000b,200000s
No pages of output.
```

**Comment by davidcarlisle** [comment]
Oh thanks: it should be `F` not `f`

**Comment by FrankMittelbach** [comment]
means nobody ever used that before .. why did we bother? :-(

**Comment by cfr42** [comment]
> means nobody ever used that before .. why did we bother? :-(

Plenty of people only report bugs they can't easily fix themselves and this is trivial. Much easier to fix than report, especially if the guidance seems less than enthusiastic about bug reports and insists on requirements which don't apply. I understand why you have that  guidance, but it will inevitably deter some reports. After all, that's the point of having the guidance. I did report it, but I certainly thought twice first.

**Comment by cfr42** [comment]
I realise that sounds as if I'm griping about the guidance. I'm not. I just meant: I don't think you can infer zero usage from zero bug reports when it is this easy to fix.

**Comment by muzimuzhi** [comment]
> means nobody ever used that before .. why did we bother? :-(

@cfr42 I think this is just some sense of humor. 😄 Of course your report is welcome.

**Comment by FrankMittelbach** [comment]
> I realise that sounds as if I'm griping about the guidance. I'm not. I just meant: I don't think you can infer zero usage from zero bug reports when it is this easy to fix.

probably not, but in this particular case I'm not so sure. If you read ltnews then you see that there was a big plea to people making TS1 fonts to use it in order to improve the situation with that encoding. Now the real test for usage is probably if over time such .fd files will get the necessary declarations.

anyway, yes your report is of cource appreciated.
