### ISSUE TITLE
\includegraphics does not account for image Exif data

### ISSUE THREAD

**Issue by JordanSavoie** [latex3/latex2e#1497]
Some image editors will save image rotations using Exif data. Since graphics/graphicx ignore this, sometimes images need to be manually rotated with `angle=` or by resaving the image with the rotation.

```latex
\RequirePackage{latexbug}
\documentclass{minimal}

\usepackage{graphicx}

\begin{document}
	\includegraphics[width=\textwidth]{reber telescope.jpeg}
\end{document}
```

[example.log](https://github.com/user-attachments/files/17442329/example.log)
[example.pdf](https://github.com/user-attachments/files/17442333/example.pdf)
[reber telescope.jpeg](https://github.com/user-attachments/assets/f4ed82f3-de20-4f51-88bf-e464410d73c1)

**Comment by davidcarlisle** [comment]
LaTeX has no access to the binary data so this is really a feature request that needs to be made to the maintainers of the back end software.

pdftex, luatex and xdvipdfm-x (as used by xetex) do in fact all read the exif data to some extent, see this changelog entry for pdftex

```
2015-02-16  Akira Kakuto  <......>

	* writejpg.c: support JPEG Exif in addition to JFIF.
	(borrowed from dvipdfm-x).
```

However as far as I can see it is only picking up the horizontal and vertical sizes and resolutions, not the orientation.

https://github.com/TeX-Live/texlive-source/blob/trunk/texk/web2c/pdftexdir/writejpg.c#L152



If the back end image library returned the rotated image then latex would "support" this without change.

You might perhaps be best to raise this initially on the texlive list (as if any change is made probably it needs to be made separately in all relevant back ends, as some honouring the rotation and some not would be more confusing)

**Comment by FrankMittelbach** [comment]
per David's comment, can't be handled from LaTeX directly and needs resolving elsewhere, so close here.
