### ISSUE TITLE
Fix for `\KeyValue` in templates defined `\fp_(g)set:NV` to `\relax`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1523]
## Brief outline of the bug

193bfa8d4 (Expand variable contents when passing \KeyValue content (fixes #1486), 2024-10-07) added something like `\exp_not:c { #1 V }` to `\__template_assign_variable:n`, in which `#1` has the form `<type>_(g)set:N`. See line 2127 below.

https://github.com/latex3/latex2e/blob/19854823731d3c1ec932bab9223a3cb576852f19/base/lttemplates.dtx#L2120-L2138

Among the possible `<type>` values, at least for `fp`, `\fp_(g)set:NV` are (previously) undefined, but are now wrongly defined to `\relax`.

Release [release-2024-11-01](https://github.com/latex3/latex2e/releases/tag/release-2024-11-01) _is_ affected.

(First reported in https://github.com/CTeX-org/ctex-kit/issues/723, by myself.)

## Minimal example showing the bug

```latex
% needs latex-dev
\RequirePackage{latexbug}
\documentclass{article}

\NewTemplateType{foo}{0}    % current LaTeX version

\def\foocode{}
\DeclareTemplateInterface{foo}{FOO}{0}
  {
    foo.code : real ,
    code.foo : real = \KeyValue{foo.code} ,
  }
\DeclareTemplateCode{foo}{FOO}{0}
  {
    foo.code = \foocode ,
    code.foo = \foocode ,
  }
  {\AssignTemplateKeys (\fpeval\foocode)}

\DeclareInstance{foo}{i1}{FOO}{ foo.code=1 }
\DeclareInstance{foo}{i2}{FOO}{ code.foo=1 }

\begin{document}
\UseInstance{foo}{i1} % errors
\UseInstance{foo}{i2} % errors
\end{document}
```

The first error
```
! LaTeX Error: A floating point with value '1' was misused.
```

## Log file (required) and possibly PDF file  

[latex-KayValue-2.log](https://github.com/user-attachments/files/17597683/latex-KayValue-2.log)

**Comment by josephwright** [comment]
Sigh - I guess the package wasn't tested against `dev` - drat. I see you went for
```latex
\cs_gset_protected:Npn \fp_set:NV
  { \exp_args:NNV \fp_set:Nn }
```
but shouldn't 
```latex
\cs_generate_variant:Nn \fp_set:Nn { NV }
```
work equally well? I could do that in `expl3` today and we could avoid a patch release!

**Comment by muzimuzhi** [comment]
> but shouldn't
> 
> ```
> \cs_generate_variant:Nn \fp_set:Nn { NV }
> ```
> 
> work equally well?

True. At the time I was not sure about whether `\cs_generate_variant:Nn` works like `\cs_new...` or `\cs_(g)set...`.

**Comment by muzimuzhi** [comment]
The `\__template_assign_variable:` is responsible for processing 7 types: `tl`, `clist`, `fp`, `int`, `dim`, `skip`,  and `muskip`. Among them only the first two have `\<type>_(g)set:NV` defined.

**Comment by josephwright** [comment]
Hmm, lets see what everyone else thinks - a test for the existence of a `V`-type variant would add steps to every key assignment - perhaps easier to to quickly add the `V`-type variants even though they are not all needed.

**Comment by muzimuzhi** [comment]
Or, use `\exp_args:NNV \<type>_(g)set:Nn` in replace of `\<type>_(g)set:NV`.

**Comment by josephwright** [comment]
> Or, use `\exp_args:NNV \<type>_(g)set:Nn` in replace of `\<type>_(g)set:NV`.

Sure, that would work - I was thinking not only about a 'quick fix' but also that we perhaps should make sure this doesn't come up elsewhere, and adding a few variants to `expl3` addresses that

**Comment by FrankMittelbach** [comment]
> Sure, that would work - I was thinking not only about a 'quick fix' but also that we perhaps should make sure this doesn't come up elsewhere, and adding a few variants to `expl3` addresses that

I would add the V-type variants and make a note in the template code that (if ever) this part gets extended with further variable types then it is necessary to ensure that the corresponding V-type is implemented.

**Comment by josephwright** [comment]
@FrankMittelbach Cool - I'll shortcut the normal main/dev cycle for `expl3` and upload both at the same time (may be tomorrow) ...

**Comment by josephwright** [comment]
Should be fixed: if everyone is happy with that being done at the `expl3` end, I'll close (and mark hotfixed).

**Comment by muzimuzhi** [comment]
Maybe add some tests (to [`lttemplates005.lvt`](base/testfiles-lttemplates/lttemplates005.lvt))?

**Comment by josephwright** [comment]
Doing tests as suggested, there is still an issue - I will need to look again at this. Fix hopefully later today - with tests :)

**Comment by josephwright** [comment]
Sorted - I'll close
