### ISSUE TITLE
`cleveref` needs another firstaid to work with LaTeX 2024-11-01 plus `hyperref`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#1524]
## Brief outline of the bug

Loading `hyperref` and `cleveref` in LaTeX 2024-11-01, the use of `\refstepcounter{<counter>}` won't update `\cref@currentlabel` thus a corresponding `\cref{<counter>}` will typeset "??".

This may be related to the changes in `hyperref`: when used with LaTeX 2024-11-01, it doesn't redefine `\refstepcounter` anymore.

Found when running `l3build check --dev` from `ctex` directory, https://github.com/CTeX-org/ctex-kit repository.

## Minimal example showing the bug

```latex
% needs latex(-dev) 2024-11-01
% \RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{hyperref}
\usepackage{cleveref}

\begin{document}
\section{title}\label{key}

\makeatletter
\show\cref@currentlabel % still empty
\makeatother

\cref{key} % typesets "??"

\end{document}
```

In `.aux`
```tex
% with hyperref, bad
\newlabel{key}{{1}{1}{title}{section.1}{}}
\newlabel{key@cref}{{}{[1][1][]1}{}{}{}}

% without hyperref, good
\newlabel{key}{{1}{1}{}{section.1}{}}
\newlabel{key@cref}{{[section][1][]1}{[1][1][]1}{}{}{}}
```

## Log file (required) and possibly PDF file  

[cleveref-refstepcounter.log](https://github.com/user-attachments/files/17599132/cleveref-refstepcounter.log)

**Comment by u-fischer** [comment]
I works ok for me. You must ensure that the format has been built with the newest firstaid version. You can check that by looking into the hook label:

~~~
\documentclass{article}
\usepackage{hyperref}
\usepackage{cleveref}

\begin{document}
\ShowHook{label}
\section{title}\label{key}

\cref{key} % typesets "??"

\end{document}
~~~~

it should show the cleveref hook:

~~~~
-> The hook 'label' (1 argument):
> Code chunks:
>     nameref -> \def \label@name {#1}\label@hook 
>     firstaid/cleveref -> \ifx \@currentcounter \@empty \else \firstaid@cref@updatelabeldata {\@currentcounter } \fi 
> Document-level (top-level) code (executed last):
>     ---
> Extra code for next invocation:
>     ---
> Rules:
>     ---
> Execution order:
>     nameref, firstaid/cleveref.
<recently read> }
~~~~

**Comment by muzimuzhi** [comment]
> It works ok for me.

You're right. The problem disappears if I use the format built from this repo, on tag release-2024-11-01. Perhaps some changes taken place between the last pre-release and the stable release of 2024-11-01 help.

I'll close this issue once double checked using LaTeX 2024-11-01 updated from `tlmgr`.

**Comment by muzimuzhi** [comment]
> Perhaps some changes taken place between the last pre-release and the stable release of 2024-11-01 help.

It's 3d8c18544 (firstaid for gh1393 and tagging-project733 (<span>#</span>1494), 2024-10-21).

> I'll close this issue once double checked using LaTeX 2024-11-01 updated from `tlmgr`.

Confirm fixed, thank you again.

**Comment by clason** [comment]
I'm sorry for necro-posting, but I have a similar(?) problem with cleveref that still occurs on v1.1g (2024-10-16) of the firstaid package:
```latex
\documentclass{report}
\usepackage{amsthm}
\usepackage{hyperref}
\usepackage{cleveref}

\newtheorem{theorem}{Satz}[chapter]
\newtheorem{bsp}[theorem]{Beispiel}
\crefname{bsp}{Beispiel}{Beispiele}

\begin{document}
\begin{bsp}
    Mein Beispiel.
\end{bsp}

\end{document}
```

gives the error
```
 Use of \cref@override@label@type doesn't match its definition.
\refstepcounter@optarg ...cref@currentlabel \@nil
                                                  {\@tempa }}
l.11 \begin{bsp}
```

**Comment by caizixian** [comment]
@muzimuzhi I was just doing some debugging. Is it possible that this issue has a similar cause https://tex.stackexchange.com/questions/740703/clevereflisting-line-reference-shows-up-as-section-in-tex-live-2025

**Comment by u-fischer** [comment]
@caizixian according to a comment under my answer https://tex.stackexchange.com/a/738358/2388 the next listings version will fix that.
