### ISSUE TITLE
overlapping environment and macro names in source2e

### ISSUE THREAD

**Issue by mbertucci47** [latex3/latex2e#1526]
## Brief outline of the bug

Several environments that are defined as commands (`\envname...\endenvname`) have overlapping names in source2e. This happens when the dtx looks like
```tex
% \begin{environment}{list}
% \begin{macro}{\list}
%    \begin{macrocode}
\def\list#1#2{<code>}
%    \end{macrocode}
% \end{macro}
% \end{environment}
```
I see this happening in source2e for
- document
- verbatim
- equation
- eqnarray
- eqnarray*
- list
- trivlist
- array
- tabular
- picture
- filecontents

Here's what it looks like for array and tabular:

<img width="484" alt="overlap" src="https://github.com/user-attachments/assets/cd51b854-71ae-414a-bbf0-3fe39a66d33e">

## Minimal example showing the bug

Unfortunately I can't reproduce it with a simple doc example. This looks fine:
```tex
\documentclass{article}
\usepackage{doc}

\begin{document}

\begin{environment}{list}
\begin{macro}{\list}
Stuff
\end{macro}
\end{environment}

\end{document}
```
But clearly there's an issue just by inspecting source2e.

**Comment by FrankMittelbach** [comment]
It's a class issue (but I think there is already an issue for it somewhere). Problem is, this has lowest priority, because the whole class (and l3doc) would need to be redone which is a lot of work and there are really more important things to tackle.

**Comment by muzimuzhi** [comment]
> It's a class issue (but I think there is already an issue for it somewhere).

It's

- https://github.com/latex3/latex3/issues/1147

**Comment by mbertucci47** [comment]
Ah thanks @muzimuzhi. Will close here
