### ISSUE TITLE
Errors after last updates

### ISSUE THREAD

**Issue by GMS103** [latex3/latex2e#1528]
## Brief outline of the bug

After the last updates, I am getting lots of errors like the following:
```
Package hyperref Info: bookmark level for unknown The defaults to 0 on input line 2254.
```
and
```
warning  (pdf backend): ignoring duplicate destination with the name 'The.1'
```

I can look for a MWE if you think it is worthwhile.

**Comment by u-fischer** [comment]
We certainly need an MWE. And probably this should be an issue at the hyperref github (but I can transfere it if needed).

**Comment by GMS103** [comment]
Thank you very much, Ulrik.  I have opened
https://github.com/latex3/hyperref/issues/359
and
https://github.com/muzimuzhi/thmtools/issues/70

**Comment by u-fischer** [comment]
closing here as this is a thmtools/hyperref problem.
