### ISSUE TITLE
escaped dollar and braces do not seem have correct encoding with Unicode engines

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#153]
from gnats: 4500 (see discussion there)

## Brief outline of the bug
bad font encoding (OT1) used for dollar and braces under lualatex and xelatex

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Color=BB0000]{Latin Modern Roman}
\begin{document}
\$ % \OT1/LatinModernRoman(0)/m/n/10 $ ! not TU... --> not colored

\{

\}

\csname TU/LatinModernRoman(0)/m/n/10\endcsname 

\char`\$ % --> colored

\char`\{

\char`\}

\showoutput
\end{document}
\endinput

```

## Note

fix and comments are in gnats, but I think they never got appplied

**Comment by eg9** [comment]
This is the output I get with both LuaLaTeX and XeLaTeX

<img width="48" alt="Screen Shot 2019-07-08 at 19 23 36 " src="https://user-images.githubusercontent.com/302839/60829741-eaaefd80-a1b5-11e9-975a-1bd0dc1ebe15.png">

No reference to OT1 in the log file.

**Comment by FrankMittelbach** [comment]
ah well, David fix it but didn't close the pr (and he fixed it differently, which tripped me :-) ). so much the better.
