### ISSUE TITLE
Bug with the latest version of \dots when used in conjunction with colortbl.

### ISSUE THREAD

**Issue by fpantigny** [latex3/latex2e#1540]
The latest version of the command `\dots`, provided by `amsmath` seems to have a bad interaction with `colortbl`.

The following code leads to an error `! Extra \fi.`

```
\documentclass{article}
\usepackage{colortbl}
\usepackage{amsmath}

\begin{document}

\[\begin{array}{ccc}
a & \dots & c \\
\end{array}\]

\end{document}
```

[test.log](https://github.com/user-attachments/files/17630887/test.log)

**Comment by josephwright** [comment]
https://github.com/latex3/latex2e/issues/1448

**Comment by fpantigny** [comment]
OK!
