### ISSUE TITLE
extractbb now own package, not part of dvipdfmx

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#1556]
I have a note that your test setup installed the dvipdfmx package and assumed that would be enough. I'm not sure if that includes the stated dependencies, but if not, this is a heads-up that you'll need to also install the extractbb package now.

Background: As you may have seen on some list or another, Max (Chernoff) has written a new standalone implementation of extractbb, the script called by (x)dvipdfmx. It's now in TL.  It seemed sensible to make it a separate package, updated through CTAN in the usual way, instead of being part of the dvipdfmx package.

I submitted this as an "issue" just in case more back-and-forth is needed.

**Comment by josephwright** [comment]
Was an issue for the latex3 repo, which is now sorted :)
