### ISSUE TITLE
save tabular in a box

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex2e#1558]
## Brief outline of the bug

```
[...]
(/usr/local/texlive/2024/texmf-dist/tex/latex/tools/array.sty)
! Undefined control sequence.
\tbl_count_missing_cells:n #1->\tag_if_active:T 
                                                {\int_compare:nNnT \g__tbl_c...
l.9 \end{tabular}}

```

Up-to-date TL24

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass{article}
\usepackage{array}
\newsavebox\hvOBox

\savebox\hvOBox{%
\begin{tabular}{@{} *9c @{\hspace{6em}} *3c @{}}
2007& 2074& 1626& 113& 25& 8& 11&  8& 12&  71& 200& 3\\
\end{tabular}}

\begin{document}
foo
\end{document}
```

## Log file (required) and possibly PDF file  

This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=pdflatex 2024.11.10)  22 NOV 2024 10:49
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**08-09-18.ltx2
(./08-09-18.ltx2
LaTeX2e <2024-11-01>
L3 programming layer <2024-11-02>
(/usr/local/texlive/2024/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2024/07/16 v1.0p Bug-classification
)
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/article.cls
Document Class: article 2024/06/29 v1.4n Standard LaTeX document class
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2024/06/29 v1.4n Standard LaTeX file (size option)
)
\c@part=\count196
\c@section=\count197
\c@subsection=\count198
\c@subsubsection=\count199
\c@paragraph=\count266
\c@subparagraph=\count267
\c@figure=\count268
\c@table=\count269
\abovecaptionskip=\skip49
\belowcaptionskip=\skip50
\bibindent=\dimen141
)
(/usr/local/texlive/2024/texmf-dist/tex/latex/tools/array.sty
Package: array 2024/10/17 v2.6g Tabular extension package (FMi)
\col@sep=\dimen142
\ar@mcellbox=\box52
\extrarowheight=\dimen143
\NC@list=\toks17
\extratabsurround=\skip51
\backup@length=\skip52
\ar@cellbox=\box53
)
\hvOBox=\box54
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <7> on input line 9.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <5> on input line 9.

! Undefined control sequence.
\tbl_count_missing_cells:n #1->\tag_if_active:T 
                                                {\int_compare:nNnT \g__tbl_c...
l.9 \end{tabular}}
                  
? 
(/usr/local/texlive/2024/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
File: l3backend-pdftex.def 2024-05-08 L3 backend support: PDF output (pdfTeX)
\l__color_backend_stack_int=\count270
\l__pdf_internal_box=\box55
)
(./08-09-18.aux)
\openout1 = `08-09-18.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 11.
LaTeX Font Info:    ... okay on input line 11.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 11.
LaTeX Font Info:    ... okay on input line 11.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 11.
LaTeX Font Info:    ... okay on input line 11.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 11.
LaTeX Font Info:    ... okay on input line 11.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 11.
LaTeX Font Info:    ... okay on input line 11.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 11.
LaTeX Font Info:    ... okay on input line 11.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 11.
LaTeX Font Info:    ... okay on input line 11.

[1

{/usr/local/texlive/2024/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./08-09-18.aux)
 ***********
LaTeX2e <2024-11-01>
L3 programming layer <2024-11-02>
 ***********
 ) 
Here is how much of TeX's memory you used:
 1889 strings out of 473362
 44751 string characters out of 5720989
 417399 words of memory out of 5000000
 25070 multiletter control sequences out of 15000+600000
 558069 words of font info for 36 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 35i,6n,50p,166b,1352s stack positions out of 10000i,1000n,20000p,200000b,200000s
</usr/local/texlive/2024/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>

Output written on 08-09-18.pdf (1 page, 9483 bytes).
PDF statistics:
 13 PDF objects out of 1000 (max. 8388607)
 7 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by davidcarlisle** [comment]
Thanks, it's not so much that it's in a savebox, as that it is before `\begin{document}`  typesetting before begin document is always rather fragile as much of the font and math code is not finalised at that point, however given this case works without `array` and worked with previous releases, we can probably avoid the error here.

**Comment by FrankMittelbach** [comment]
should be fixed in PL1 (fairly soon), but in general it is safer for many reasons to delay typesetting to the document start, e.g., with `\AtBeginDocument{\savebox ...}`

**Comment by FrankMittelbach** [comment]
on its way to ctan
