### ISSUE TITLE
Referencing tagged equation by `cleveref` no longer works due to `firstaid` patch

### ISSUE THREAD

**Issue by zyoshoka** [latex3/latex2e#1560]
## Brief outline of the bug
After updating `firstaid` to 1.1g, referencing tagged equation by `cleveref` does not work correctly.

## Minimal example showing the bug

```latex
% \RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{amsmath,cleveref}
\begin{document}
\cref{eq:a}
\begin{equation}\tag{$*$}\label{eq:a}
  a
\end{equation}
\end{document}
```

### Expected
It should print like `eq. (*)` on the first line.

### Actual
It prints `eq. (0)` on the first line.

**Comment by u-fischer** [comment]
In your example you should use the unnumbered `equation*` if you use a `\tag`. `equation` gives wrong links with hyperref. E.g in the following example the reference jumps to the first equation and not as wanted to the second: 

~~~~
\documentclass{article}
\usepackage{amsmath}
\usepackage{hyperref}
\begin{document}
\ref{eq:b}
\begin{equation}\tag*{$*$}\label{eq:a}
  a
\end{equation}

\newpage 
\begin{equation}\label{eq:b}
  b
\end{equation}
\end{document}
~~~~

With the starred version both the links and also cleveref works fine:

~~~~
\documentclass{article}
\usepackage{amsmath}
\usepackage{hyperref}
\usepackage{cleveref}
\begin{document}
\cref{eq:a}, \cref{eq:b}
\begin{equation*}\tag*{$*$}\label{eq:a}
  a
\end{equation*}

\newpage 
\begin{equation}\label{eq:b}
  b
\end{equation}

\end{document}
~~~~

![image](https://github.com/user-attachments/assets/d740af8b-fe6a-446e-8a98-a43c625e4578)

**Comment by zyoshoka** [comment]
Your example works correctly, but is not a complete workaround since referencing tagged `equation*` inside referenceable environments doesn't work. For example, the following example gives `1. item 1` instead of `1. eq. (*)`:
```tex
\documentclass{article}
\usepackage{amsmath,cleveref}
\begin{document}
\begin{enumerate}
  \item \cref{eq:a}
  \begin{equation*}\tag{$*$}\label{eq:a}
    a
  \end{equation*}
\end{enumerate}
\end{document}
```

**Comment by jfbu** [comment]
@u-fischer sorry to drop-in, but I got a revelation when reading and then testing your advice about not using `\tag` within `equation` but only `equation*`.  The `amsmath` documentation says

> You can also override a number with a tag of your own using \tag{⟨label⟩}, where ⟨label⟩ means arbitrary text such as $*$ or ii used to “number” the equation. [...]. If you are using hyperref,

As I read this decades ago (in `amsldoc.pdf`) and it still says "override a number", and as the paragraph mentions `hyperref` without discussing the issue, I may have been doing bad practice for ages without realizing it.  I confirmed I used `\tag` in `equation` as recent as one week ago, but in a document not using `hyperref`.  With `hyperref` I see that pdftex raises warnings, but such warning not originating in LaTeX are not reported by my editor (Emacs AUCTeX).  It could be that I never realized that hyperlinks were wrong in some documents.

Could an update to `amsmath` documentation explain the good practice?

**Comment by u-fischer** [comment]
@zyoshoka ok I think testing for `\iftag@` in the hook should work, at least I get for all the variants here the same output as in tl2022:

~~~~
\documentclass{article}
\usepackage{amsmath}
\usepackage{hyperref}
\usepackage{cleveref}
\makeatletter
\RemoveFromHook{label}[firstaid/cleveref]
\ExplSyntaxOn
 \newif\iftag@ \tag@false %if amsmath is not loaded
 \AddToHook{label}[firstaid/cleveref]
         {%
          \ifx
           \@currentcounter\@empty
          \else
          \iftag@\else
           \firstaid@cref@updatelabeldata{\@currentcounter}%
          \fi 
          \fi}
\ExplSyntaxOff          
\makeatother
\begin{document}
\cref{sec},\\
\cref{a1},\\
\cref{a2},\\
\cref{b},\\
\cref{c},\\
\cref{d},\\
\cref{e},\\
\cref{f},\\
\cref{g},\\
\cref{h}
\section{section}\label{sec}
\begin{align}
a& b\tag{align}\label{a1}\\
a& b \label{a2}
\end{align}
\begin{equation}
a= b\label{b}
\end{equation}
\begin{equation*}
a= b\label{c}
\end{equation*}

\begin{equation}
a= b\tag{tageq}\label{d}
\end{equation}

\begin{equation*}
a= b\tag{tageq*}\label{e}
\end{equation*}

\[
a= b\label{f}
\]

\[
a= b\tag{tagX}\label{g}
\]

\begin{enumerate}
  \item item
   \begin{equation*}
    a= b \tag{inenum}\label{h}
  \end{equation*}
\end{enumerate}
\end{document}
~~~~

**Comment by FrankMittelbach** [comment]
on its way to CTAN and from there in 1-2 days to the distributions
