### ISSUE TITLE
amsmath and cleveref incompatibility: equation labels offset from right when both used after latest texlive update

### ISSUE THREAD

**Issue by LSinev** [latex3/latex2e#1563]
## Brief outline of the bug

Extra space added to the right of parentheses of equation numbers. Nothing happens if `\usepackage{cleveref}` is commented out (not a solution as provided example is MWE) or with numbers from `equation` environment.
I suppose something changed in `\label` lately but not everything was patched accordingly.

## Minimal example showing the bug

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{cleveref}
%\usepackage[showframe]{geometry}
\listfiles

\begin{document}

We want to label each line separately. The inserted text and formulas
have to be aligned like in this example:
\begin{subequations}
\label{eq:optim}
\begin{align}
    \underset{X}{\text{minimize}}
        & \quad \mathrm{trace}(X)   \label{eq:co_st} \\
    \text{subject to} 
        & \quad X_{ij} = M_{ij}\,, \; (i,j) \in \Omega\,, \label{eq:const-1} \\
        & \quad X \succeq 0 \,. \label{eq:co-nst_2}
\end{align}
\end{subequations}

Equation \ref{eq:co_st} is the cost and Equations \ref{eq:const-1} and \ref{eq:co-nst_2}
are the constraints of optimisation problem \ref{eq:optim}.

\end{document}
```
## TexLive2024 with latest updates (except amsmath for comparison) results:
[test_labels.pdf](https://github.com/user-attachments/files/17894774/test_labels.pdf)
[test_labels.log](https://github.com/user-attachments/files/17894775/test_labels.log)
![Screenshot 2024-11-24 23-35-47](https://github.com/user-attachments/assets/e76af988-80f3-47a4-a1bc-0be4599d6043)

## TexLive2024 from overleaf (almost the same package versions) results:
[cleveref_test.log](https://github.com/user-attachments/files/17894793/cleveref_test.log)
[cleveref_test.pdf](https://github.com/user-attachments/files/17894794/cleveref_test.pdf)
![Screenshot 2024-11-24 23-38-00](https://github.com/user-attachments/assets/d436b974-13f0-4a25-841e-f310312d15a0)

**Comment by u-fischer** [comment]
There is a spurious space in the cleveref firstaid. These will be fixed in a few days.  As a workaround until the release you can use the fix in https://github.com/latex3/latex2e/issues/1560#issuecomment-2496081058 (the important part is the `%` after `\firstaid@cref@updatelabeldata{\@currentcounter}`).

**Comment by FrankMittelbach** [comment]
on its way to CTAN and from there in 1-2 days to the distributions
