### ISSUE TITLE
Some characters are mirrored when using Hebrew or Arabic script in XeLaTeX

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex2e#157]
## Brief outline of the bug

When using Hebrew or Arabic script, and compiled with Xe(La)TeX, the direction of some characters may be mirrored.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}

% Using Hebrew letters such as `א` gives the similar result

ع(

ع(abcd]

ع

(

\font\FreeSerif="[FreeSerif.otf]/OT:script=latn;"\FreeSerif

ع(

ع(abcd]

ع

(
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/61265811-98c53380-a7c4-11e9-8c3c-eae154dee44e.png)

If use the default font (e.g. lmr), the `(`, `]` after the Arabic letter `ع` are mirrored. However, if load another font with `script=latn` option, then only those characters in the same line are mirrored.

This issue is from CTeX-org/forum#48.

## Log file (required) and possibly PDF file  

[test.zip](https://github.com/latex3/latex2e/files/3395228/test.zip)

**Comment by u-fischer** [comment]
This is clearly no a latex problem: you get the same output in plain. The mirroring is done by the harfbuzz library, it applies bidi-mirroring. If there is bug it is either in the fonts or in the harfbuzz library. 

For information about bidi-mirroring see e.g. http://www.unicode.org/L2/L2017/17438-bidi-math-fdbk.html (it is about math but contains various links to the topic).

**Comment by stone-zeng** [comment]
I have tested with plain TeX, but the result is different:

```tex
% xetex test.tex
א(

א(abcd]

א

(

(

\font\FreeSerif="[FreeSerif.otf]/OT:script=latn;"\FreeSerif

א(

א(abcd]

א

(

(
\bye
```

![image](https://user-images.githubusercontent.com/18233088/61275445-94a70f00-a7e0-11e9-98df-6dc607a7368f.png)

**Comment by u-fischer** [comment]
You need to activate the right font in plain. Without it you are using cmr in the first part. 

~~~~
 \font\test="[lmroman10-regular.otf]/OT:scrip=latn;"\test
~~~~

**Comment by khaledhosny** [comment]
That is a XeTeX “feature”, it detects tat the text is right to left (it does not fully apply the BiDi algorithm, though, as this operates on word level not paragraph level) and tell HarfBuzz to shape the text in the RTL direction which in turn activates BiDi mirroring.
