### ISSUE TITLE
lscapeenhanced

### ISSUE THREAD

**Issue by Rimole** [latex3/latex2e#1578]
There is: https://github.com/latex3/latex2e/issues/166
And there is: https://www.ctan.org/pkg/lscapeenhanced

lscapeenhanced seems to fix the bug without breaking anything. (Does it?)

Would it be possible to merge lscapeenhanced into lscape?

**Comment by u-fischer** [comment]
> lscapeenhanced seems to fix the bug without breaking anything

Didn't you read the documentation? lscapeenhanced doesn't "fix" #166.  `\textheight` is still (as with lscape) unchanged. But it additionally also leaves `\textheight` unchanged. Personally I doubt that users really want that:

~~~~
\documentclass{article}
\usepackage{lscapeenhanced}
\begin{document}
\SetKeys[lscapeenhanced]{lscape=false}
\begin{landscape}
\noindent\rule{\linewidth}{\textheight}
\end{landscape}

\begin{landscape}
\noindent\rule{\textwidth}{\textheight}
\end{landscape}

\SetKeys[lscapeenhanced]{lscape=true}
\begin{landscape}
\noindent\rule{\textwidth}{\textheight}
\end{landscape}

\begin{landscape}
\noindent\rule{\linewidth}{\textheight}
\end{landscape}

\end{document}
~~~~

The first two pages are the original, the following four pages with the lscapeenhanced patch:

![image](https://github.com/user-attachments/assets/1fb221bd-7f91-46d6-847d-abd662a737be)
