### ISSUE TITLE
Local options cannot be checked using the \ProcessKeyOptions command

### ISSUE THREAD

**Issue by texno3** [latex3/latex2e#1589]
## Brief outline of the bug
Local options cannot be checked using the `\ProcessKeyOptions` command, In the previous LaTeX  `\aaa` should have been `bbb`, but now it is `aaa`, indicating that option `opt` is not recognized by the macro package `mypkg`.

## Minimal example showing the bug

```latex
\begin{filecontents}{mybook.cls}
\NeedsTeXFormat{LaTeX2e}
\ProvidesExplClass{mybook}{2024/12/21}{}{}
\DeclareKeys{opt.code = \def\aaa{aaa}}
\ProcessKeyOptions
\LoadClass{book}
\end{filecontents}

\begin{filecontents}{mypkg.sty}
\NeedsTeXFormat{LaTeX2e}
\ProvidesExplPackage{mypkg}{2024/12/21}{}{}
\DeclareKeys{opt.code = \def\aaa{bbb}}
\ProcessKeyOptions
\end{filecontents}

\documentclass[opt]{mybook}
\usepackage{mypkg}
 
\begin{document}
\aaa
\end{document}
```

**Comment by muzimuzhi** [comment]
You need to use
```tex
\DeclareKeys{
  opt .code = \def\aaa{aaa},
  opt .pass-to-packages = true
}
```
The `.pass-to-packages` is added in the LaTeX2e 2024-11-01 release, and yes the default behavior has been changed to `.pass-to-packages = false` since then.

`texdoc clsguide` (2024-09-15), sec. 4.4 Creating and using keyval options and `texdoc ltnews40`, sec. "Avoiding key–value option clashes between classes
and packages" contain doc and motivation for this change.

**Comment by texno3** [comment]
Okay, thank you. I've noticed

> This is the new expected behavior since LaTeX2e 2024-11-01.
> 
> To pass class options to packages, you need to use
> 
> ```
> \DeclareKeys{
>   opt .code = \def\aaa{aaa},
>   opt .pass-to-packages = true
> }
> ```
> 
> The `.pass-to-packages` key property is added in the LaTeX2e 2024-11-01 release, and yes the default behavior has been changed since then.
> 
> `texdoc clsguide` (2024-09-15), sec. 4.4 Creating and using keyval options and `texdoc ltnews40`, sec. "Avoiding key–value option clashes between classes and packages" contain doc and motivation for this change.

Okay, thank you. I've noticed.

**Comment by FrankMittelbach** [comment]
As @muzimuzhi said, this was a deliberate change to avoid interaction problems that could otherwise occur.
