### ISSUE TITLE
Re-integrate doc and base distribution into one for CTAN

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#163]
The artifical split of `doc` and `base` which was done in the past to keep uploads smaller, doesn't really serve any purpose any more (as we essentially always upload both at the same time).

We should therefore integrate `doc`back into `base`to make life easier for everybody.

**Comment by josephwright** [comment]
OK, @FrankMittelbach  would prefer the doc part stay separate within `base`. I'm working on it!
