### ISSUE TITLE
Provide dummy defs for \conditionally@traceon/off in the kernel

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#164]
At the moment these are defined only by trace.sty. Better have an empty definition already in the kernel so that packages can use them without having to worry whether or not the trace package is loaded. (Currently an issue for xparse)

**Comment by josephwright** [comment]
Better in `l3kernel`? Something like `\trace_conditional_begin:`? For the present this can be set equal to the LaTeX2e one if available?

**Comment by FrankMittelbach** [comment]
I'm ok with the l3kernel offering an l3 interface to the concept, but I  I think the function should be provided in in 2e kernel with its 2e name so that trace.sty can interact with other 2e package that may want to reduce the trace footprint.

**Comment by josephwright** [comment]
Couldn't we just add all of `trace` to the kernel?

**Comment by FrankMittelbach** [comment]
@josephwright we could but then that could would be always executing and it is done in places that are fairly often called, which is why I'm not sure we should. I tend to think that just adding the dummy ones is better.

**Comment by josephwright** [comment]
@FrankMittelbach I don't follow: without `\traceon` aren't the conditional macros no-ops? I just meant that is there a need to not pre-load `trace` in its entirety, so one can `\traceon`  without `\usepackage{trace}`?

**Comment by wspr** [comment]
I think Frank’s point is that trace.sty is like the expl3 debug code — even if the tracing is off it requires no-ops to be included in macro definitions that operate at a very low level (recall that NFSS is quite optimised).

**Comment by FrankMittelbach** [comment]
@josephwright if the code from trace is in the kernel, then yes, the conditionals are noops but they are nevertheless executed  so you have possibly several thousands of macros executed as "do nothing" but  still expanded. But it might be preferable over having certain commands change their definition depending on whether or not the package is loaded. I guess I'm still somewhat tied into believing execution cycles needed to be saved when possible, but in this case it is probably a bad idea and better to fold the whole of trace.sty into the kernel directly.

**Comment by FrankMittelbach** [comment]
Basically any font change would trigger the no-ops but that probably amounts to less than 100 per page typically so it is indeed not really worth preserving these days.

**Comment by FrankMittelbach** [comment]
I decided to go for providing just the two function needed in external packages for now. At a later stage we might consider moving the whole of `trace` as well. Once this is live it can be used in `xparse` and the like.
