### ISSUE TITLE
bug in lscape

### ISSUE THREAD

**Issue by GMS103** [latex3/latex2e#166]
## Brief outline of the bug
In the macro \landscape, \textwidth is not modified (it stays as it is), unlike \textheight:

% First set up the page size for landscape.
%    \begin{macrocode}
\def\landscape{%
  \clearpage
  \begingroup
  \vsize=\textwidth
  \hsize=\textheight
  \linewidth=\hsize
  \columnwidth=\hsize
  \@colroom=\vsize
  \textheight=\vsize
  \@colht=\vsize
%    \end{macrocode}
%    Rotate the page body (text and float pages).
%    \begin{macrocode}
  \def\@makecol{\LS@makecol\LS@rot}%
  \def\@makefcolumn##1{\LS@makefcolumn{##1}\LS@rot}}
%    \end{macrocode}

**Comment by davidcarlisle** [comment]
This is by design as the page head and foot remain in portrait orientation and many packages, notably fancyhdr use `\textwidth` as part of the page head layout.

**Comment by GMS103** [comment]
All right.
I was trying to use
`\begin{adjustbox}{max width=\textwidth}`
and I did not understand why it does not work and why `\textwidth` = `\textheight`…
(I changed it to `\begin{adjustbox}{max width=\hsize}`.)
Thank you for your quick answer.

**Comment by davidcarlisle** [comment]
somone commented recently that the package could (and probably should) have kept `\textwidth`  with portrait values within the output routine while setting the page head and foot but set it for the landscape setting within the page body, but I think it's some decades too late to change that now.

**Comment by GMS103** [comment]
Perhaps a new package **lscape2** taking that into account?
It would be most welcome, I think.

**Comment by wspr** [comment]
Does \linewidth work for your needs instead of \textwidth? \linewidth is usually the better length to use for such things as it works correctly in two-column mode, inside minipages, etc. But I can’t guarantee here, I haven’t checked sorry!

**Comment by davidcarlisle** [comment]
yes \linewidth \columnwidth \hsize all reflect landscape I just kept
\textwidth for the page head/foot settings

**Comment by GMS103** [comment]
Thanks.
