### ISSUE TITLE
nested minipage highjacks the footnote

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#168]
Reference: https://tex.stackexchange.com/q/504688/2388 (here with todonotes)

A nested minipage grabs footnotes from the outer minipage:

```latex
\RequirePackage{latexbug}
\documentclass[12pt]{article}
\begin{document}
\section{nested}
\begin{minipage}{6cm}
some text\footnote{footnote A}

\hspace*{3cm}%
\begin{minipage}{3cm}
 nested
\end{minipage}

some text \footnote{footnote B}
\end{minipage}
\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/63249801-7b273600-c26a-11e9-9756-b6633c2ddd6a.png)

## Log file (required) and possibly PDF file  
[test-utf8.log](https://github.com/latex3/latex2e/files/3514823/test-utf8.log)

This can be surprising for the user if the inner minipage is actually hidden, e.g. in a tikzpicture:

```latex
\documentclass[12pt]{article}
\usepackage{tikz}

\begin{document}
\begin{minipage}{6cm}
some text\footnote{footnote A}

\hspace*{3cm} \begin{tikzpicture}
 \node[draw=red,text width=3cm,align=left]
 {nested};
 \end{tikzpicture}

some text \footnote{footnote B}
\end{minipage}
\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/63250002-e83acb80-c26a-11e9-940e-2b7cce2788f4.png)

**Comment by PhelypeOleinik** [comment]
Not only the footnote goes to the wrong place, but also the inner minipage inherits the width of the outer one, resulting in an overfull box.

Adding `\setbox\@mpfootins\box\voidb@x` to the initialisation of the minipage to ensure that the insertion box starts empty (thus, only footnotes added to the _current_ minipage are seen) seems to solve the problem:

```latex
\makeatletter
\def\@iiiminipage#1#2[#3]#4{%
  \leavevmode
  \@pboxswfalse
  \setlength\@tempdima{#4}%
  \def\@mpargs{{#1}{#2}[#3]{#4}}%
  \setbox\@tempboxa\vbox\bgroup
    \color@begingroup
      \hsize\@tempdima
      \textwidth\hsize \columnwidth\hsize
      \@parboxrestore
      \def\@mpfn{mpfootnote}\def\thempfn{\thempfootnote}\c@mpfootnote\z@
      \let\@footnotetext\@mpfootnotetext
      \let\@listdepth\@mplistdepth \@mplistdepth\z@
      \setbox\@mpfootins\box\voidb@x% <=================================
      \@minipagerestore
      \@setminipage}
\makeatother

\RequirePackage{latexbug}
\documentclass[12pt]{article}
\begin{document}
\section{nested}
\begin{minipage}{6cm}
some text\footnote{footnote A}

\hspace*{3cm}%
\begin{minipage}{3cm}
 nested
\end{minipage}

some text \footnote{footnote B}
\end{minipage}
\end{document}
```

![image](https://i.stack.imgur.com/928tc.png)

**Comment by u-fischer** [comment]
@PhelypeOleinik your code solves my example, but if the inner minipage has also a footnote one looses the first:

~~~
% patch as a above ....
\documentclass[12pt]{article}
\begin{document}
\section{nested}
\begin{minipage}{6cm}
some text\footnote{footnote A}

\hspace*{3cm}%
\begin{minipage}{3cm}
 nested\footnote{footnote C}
\end{minipage}

some text \footnote{footnote B}
\end{minipage}
\end{document}
~~~

![image](https://user-images.githubusercontent.com/4047173/63267395-36af9080-c292-11e9-9a6c-282d4eae7ee6.png)

**Comment by PhelypeOleinik** [comment]
@u-fischer Oh :/

The code for `\@mpfootnotetext` globally sets `\@mpfootins`, so my local `\setbox\@mpfootins\box\voidb@x` won't work. I suspect that the reason for that assignment to be global is that both footnotes A and C are labeled "_a_", then things get confusing.

Changing `\global\setbox\@mpfootins` to `\setbox\@mpfootins` in the definition of `\@mpfootnotetext`, plus the patch above seem to solve the second problem as well. However, having the global assignment will probably require something more elaborate to detect the nested minipages...

**Comment by car222222** [comment]
Maybe nested minipages were never supported (at least not with footnotes everywhere!) so this is simply a documentation problem?

But a package extending coverage to  “recursive minipages” may be a good idea.  Good for making pages that contain reduced copies of themselves, I guess.

**Comment by blefloch** [comment]
Maybe replace

    \setbox\@mpfootins\box\voidb@x

in Phelype's code by

    \setbox\mybox\box\@mpfootins

(with a better name for the box than \mybox, of course) and in the
\end{minipage} code do

    \global\setbox\@mpfootins\box\mybox

**Comment by FrankMittelbach** [comment]
This is a documented restriction: LaTeX Book page 106, so it works as designed. That does not mean that we can't change it. However, I'm not sure that it is correct that a tikz picture is internally using  a minipage instead of a parbox ... is that supposed to support inner footnotes?

**Comment by car222222** [comment]
I should have RTFM :-).

**Comment by u-fischer** [comment]
@FrankMittelbach I don't know why tikz or todonotes (which triggered the issue) use minipage. It could be footnotes, but perhaps simply as environments are easier to handle in begin/end code. I never saw a question about the side-effect before and even if one know in theory that a single mp-footnote counter and insert means that nesting could be problematic it is easy to forget that in practice.

**Comment by car222222** [comment]
So it would be a good idea to at least issue a warning when a nested minipages us spotted.  Not that anyone will notice a warning, of course.

**Comment by FrankMittelbach** [comment]
the above commit is a red herring it should have referenced #186

**Comment by FrankMittelbach** [comment]
I have now added a check and a warning if minipages are nested.
