### ISSUE TITLE
babel: Definition of hyphenrules

### ISSUE THREAD

**Issue by moewew** [latex3/latex2e#17]
## Brief outline of the bug

Since `babel` 3.15 2017/10/30 (specifically https://github.com/latex3/latex2e/commit/8b0b10baea14df33e76db82b89ebdb11f8cfc145#diff-77fe35201eeb1884d615a3b11ff1afe8R9133) `hyphenrules` can't be used any more with `polyglossia`. The use of internal macros such as `\bbl@ifunset` and `\bbl@exp` instead of the slightly longer generic `\expandafter` definitions seem to be problematic here. Naturally one could consider this a bug in `polyglossia`, but since there have been no changes to `polyglossia` in over a year I hope that the report is not considered invalid here.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{polyglossia}
\begin{document}
\begin{hyphenrules}{dutch}
Lorem
\end{hyphenrules}
\end{document}
```

## Log file (required) and possibly PDF file  
The log file is at https://gist.github.com/moewew/0a4b0ba2d87395c81a6e9a99b5eef1b1 

The relevant bits are
```
! Undefined control sequence.
<argument> ...nguageshorthands {none}\bbl@ifunset 
                                                  {\bbl@tempf hyphenmins}{\s...
l.5 \begin{hyphenrules}{dutch}
                              
? 
! Undefined control sequence.
<argument> ...nmins \tw@ \thr@@ \relax }{\bbl@exp 
                                                  {\\\set@hyphenmins \@nameu...
l.5 \begin{hyphenrules}{dutch}
                              
? 
```

## Relevant links
https://tex.stackexchange.com/q/400986/
https://tex.stackexchange.com/questions/396569/biblatex-langid-with-autolang-hyphen-makes-csquotes-use-localized-quotation-mark/396614#comment987134_396614
https://github.com/plk/biblatex/issues/698

**Comment by jbezos** [comment]
Actually, switch.def shouldn't use any macro not defined there (the conflicting macros are defined in babel.sty and babel.def), so in some sense it's a bug in babel. I'll rewrite it for 3.18.

**Comment by jbezos** [comment]
Fixed on GitHub.

**Comment by FrankMittelbach** [comment]
@jbezos I suggest that we always add a category and once identified either "bug" or "enhancement" or "invalid" or whatever for housekeeping purposes.

**Comment by moewew** [comment]
Thank you very much.
