### ISSUE TITLE
A longtable does not issue `\@nobreakfalse` resulting in inconsistent spacing

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#173]
## Brief outline of the bug

As `longtable` does not modify the `\if@nobreak` flag, the spacing after it and before next section title varies according to whether some contents before it provoked or not `\@nobreakfalse`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}

\documentclass{article}

\usepackage{longtable}

\def\TESTTABLE{%
\begin{longtable}[c]{|l|l|l|}
\caption{Long table before header\strut}

\endfirsthead

\endhead

\endfoot

\endlastfoot

a
&
b
&
c
\\
\hline
1
&
2
&
3
\\
\hline
\end{longtable}
}


\def\SOMERULE{\smash{\rule{2pt}{40pt}}}
\begin{document}

\section{FOO1}

\TESTTABLE

\section{FOO2 is closer to \SOMERULE longtable than FOO3 will be}

AAA

\TESTTABLE

\section{FOO3 more distant \SOMERULE from long table than FOO2}

AAA

\end{document}
```

## Log file (required) and possibly PDF file  

[buglongtable.log](https://github.com/latex3/latex2e/files/3538277/buglongtable.log)
[buglongtable.pdf](https://github.com/latex3/latex2e/files/3538279/buglongtable.pdf)

**Comment by jfbu** [comment]
This means mismatch between doing a longtable or doing  a tabular in paragraph mode (with `\centering`). The different vertical spacing in output between the two cases is unexpected. (specific problem arose in context using `titlesec` but mwe here is core LaTeX only)

**Comment by jfbu** [comment]
A variant of this issue applies in case of positive `\parindent` (which is default in LaTeX, but was not in original context where the issue arose, due to usage of `parskip` package). The two situations:

1. title then tabular then text paragraph,

2. title then longtable then text paragraph,

give diverging results. Former case has indentation, latter case has no paragraph indentation.

**Comment by davidcarlisle** [comment]
This didn't get in this time bumped the milestone to the next release.
