### ISSUE TITLE
Invalid UTF-8 byte sequence ?

### ISSUE THREAD

**Issue by petiard** [latex3/latex2e#177]
Hello

pdflatex-dev complains:
! Package inputenc Error: Invalid UTF-8 byte sequence
but the same file compiles without problem with pdflatex
So I think the problem is not in [french]{babel} and not in inputenc.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass[oneside,a4paper,french]{article}
\usepackage{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}

On n'écrit pas 1\up{ère} ni 1\up{ères}

\end{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/3612431/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/3612432/test.pdf)

**Comment by josephwright** [comment]
Can be cut down a little more:
```latex
\documentclass{article}

\usepackage[french]{babel}

\begin{document}

\MakeLowercase{ère}

\end{document}
```

**Comment by josephwright** [comment]
Even more
```latex
\documentclass{article}
\begin{document}
\MakeLowercase{ère}
\end{document}
```

**Comment by FrankMittelbach** [comment]
As we just have pushed out pre-release-3 it will take (probably until the official release date that this gets fixed, to not make too much extra work for the CTAN folks), but for now the following code should work for you --- sorry for the inconvenience and thanks for testing ... much appreciated.
```
\makeatletter
\DeclareRobustCommand{\MakeUppercase}[1]{{%
      \def\i{I}\def\j{J}%
      \def\reserved@a##1##2{\let##1##2\reserved@a}%
      \expandafter\reserved@a\@uclclist\reserved@b{\reserved@b\@gobble}%
%    \end{macrocode}
%    Tell UTF-8 processing to process chars even though we are in an \cs{protected@edef}.
% \changes{v2.1h}{2019/09/14}{Expand UTF8 chrs when case changing (github/177)}
%    \begin{macrocode}
      \let\UTF@two@octets@noexpand\@empty
      \let\UTF@three@octets@noexpand\@empty
      \let\UTF@four@octets@noexpand\@empty
      \protected@edef\reserved@a{\uppercase{#1}}%
      \reserved@a
   }}
\DeclareRobustCommand{\MakeLowercase}[1]{{%
      \def\reserved@a##1##2{\let##2##1\reserved@a}%
      \expandafter\reserved@a\@uclclist\reserved@b{\reserved@b\@gobble}%
      \let\UTF@two@octets@noexpand\@empty
      \let\UTF@three@octets@noexpand\@empty
      \let\UTF@four@octets@noexpand\@empty
      \protected@edef\reserved@a{\lowercase{#1}}%
      \reserved@a
   }}
```

**Comment by davidcarlisle** [comment]
@petiard  I just pushed an updated textcase package to ctan to address this issue (as it affects that package too) so once that is distributed an alternative to adding the local redefinition will be to add

`\usepackage[overload]{textcase}`

to the document, which will then redefine `\MakeUppercase` to be the newly fixed `\MakeTextUppercase`  and your original test file runs without error.
