### ISSUE TITLE
Possible extra \expandafter in the \IncludeInRelease{0000/00/00}{\refstepcounter}

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#179]
Here is from develop branch (I suppose this is the one uploaded to CTAN as latex-dev ?)

https://github.com/latex3/latex2e/blob/a7963325cd2fabc0c88ee018450e839409b56881/base/ltxref.dtx#L383-L393

The `\csname p@#1\expandafter\endcsname\csname the#1\endcsname` should not have `\expandafter` as far as I understand the `\IncludeInRelease{0000/00/00}` syntax which I presume means it provides the legacy coding.

From `texdoc -l source2e` on an updated TL2019 I see there was no `\expandafter` in the past (which matches the new code comments of course).

**Comment by FrankMittelbach** [comment]
yep, cut-and-paste error, thanks
