### ISSUE TITLE
Typesetting `ltnews30.tex`

### ISSUE THREAD

**Issue by lemzwerg** [latex3/latex2e#182]
[7c57754e76cbf5a9493e61c8a327b9cc4dcd4606 from `develop` branch]

I've just tried to compile `ltnews30.tex` with
```
TEXINPUTS=..: xelatex ltnews30.tex
```
However, this fails because `\href` is not defined.

What about adding, say,
```latex
\usepackage[colorlinks]{hyperref}
```
to the file to allow easy stand-alone processing?

**Comment by FrankMittelbach** [comment]
not sure why you can't compile it standalone I can. Hyperref is loaded by ltnews.cls, so not sure where your problem is. Anyway, there isn't really a need to do so as we supply the pdf as well as the source, so `texdoc ltnews30` gives you the documentation

**Comment by lemzwerg** [comment]
Stand-alone compilation fails with `xelatex` only; the line
```latex
\IfFileExists{hyperref.sty}{%
```
in `ltnews.cls` is never executed.

Compilation with both `pdflatex` and `lualatex` work.  It was just an accident that I tried `xelatex` first...

**Comment by u-fischer** [comment]
well the class and the tex file is not meant for xelatex. The document starts with `\usepackage[T1]{fontenc}` which a clear indication for "compile with pdflatex".

**Comment by lemzwerg** [comment]
ok
