### ISSUE TITLE
longtable height miscalculated after itemize list

### ISSUE THREAD

**Issue by idleroux** [latex3/latex2e#183]
## Brief outline of the bug

A longtable that begins on the same page as an itemized list and continues onto the following page can overflow the textblock, such that the table footer (for the first page) collides with the page footer.

The size of the potential overflow appears to scale with the length of the preceding itemized list.

## Minimal example showing the bug

```
\RequirePackage{latexbug}

\documentclass{article}
\usepackage{longtable}

\begin{document}

\begin{itemize}
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
	\item foo
\end{itemize}
\vspace{1cm} %Fine adjustment of spacing to get table footer on top of page number.

\newcommand*\stuff{
Lorem ipsum dolor sit amet, con-
sectetuer adipiscing elit. Ut purus
elit, vestibulum ut, placerat ac, adip-
iscing vitae, felis. Curabitur dictum
gravida mauris. Nam arcu libero, non-
ummy eget, consectetuer id, vulputate
a, magna. Donec vehicula augue eu
neque.}

\begin{longtable}{p{0.5\linewidth}}
		\hline Heading \\* \hline
	\endfirsthead
		\ldots continued from previous page \\*
		\hline
	\endhead
		\hline
		continues on following page\ldots\\
	\endfoot
		\hline
	\endlastfoot

	\begin{minipage}[t]{\linewidth} \stuff \end{minipage} \\
	 \begin{minipage}[t]{\linewidth} \stuff \end{minipage} \\
	\begin{minipage}[t]{\linewidth} \stuff \end{minipage} \\
	\begin{minipage}[t]{\linewidth} \stuff \end{minipage} \\
	\begin{minipage}[t]{\linewidth} \stuff \end{minipage} \\
	\begin{minipage}[t]{\linewidth} \stuff \end{minipage} \\
\end{longtable}

\end{document}
```

Note that, in this example, the first part of the longtable extends below the page number on p. 1.

## Log file (required) and possibly PDF file  

[demo.log](https://github.com/latex3/latex2e/files/3623406/demo.log)
[demo.pdf](https://github.com/latex3/latex2e/files/3623409/demo.pdf)

**Comment by u-fischer** [comment]
I think this and also https://www.latex-project.org/cgi-bin/ltxbugs2html?pr=latex/3685 can be reduced to the problem that there is sometimes a wrong pagebreak if the preceding material contains lots of shrinkable space:

~~~~
\documentclass[a4paper]{article}
\usepackage{longtable}
\begin{document}
\tracingpages=1
\def\item{x \par \vskip 11pt  minus 5pt} %fails
%\def\item{x \par \vskip 11pt  minus 4pt} %works 
   \item \item \item \item \item
   \item \item \item \item \item
   \item \item \item \item \item
   \item \item \item \item \item
   \item \item \item \item \item
   \item \item \item \item \item
   \item \item \item

\begin{longtable}{lll}
   a & b & c \\
\end{longtable}

\end{document}
~~~~

**Comment by davidcarlisle** [comment]
shrink glue also here

http://www.latex-project.org/cgi-bin/ltxbugs2html?pr=tools/2601

reminder to myself to check the example there if adjusting for page shrink

**Comment by u-fischer** [comment]
@davidcarlisle  I think issue #215 is also due to shrink glue. It behaves if one set `\LTpre=12pt` but fails with `\LTpre=12pt minus 4pt`.

**Comment by davidcarlisle** [comment]
@u-fischer  I think actually that's a separate issue. There are two problems with shrink glue, one is that it isn't correctly accounted for so the first page of the table can over-shoot (that is the issue at the top of this post) then slightly different it isn't accounted for when longtable decides to force a beak and start on a new page so you can get spurious  page breaks as in your example.

If you try the following redefinition after loading longtable (this one or 4.13) it seems to fix most of the examples posted in linked isses.


```
\def\LT@start{%
  \let\LT@start\endgraf
  \endgraf\penalty\z@\vskip\LTpre\endgraf
% new test from Lars Hellström force TeX to consider a page break here
% https://www.latex-project.org/cgi-bin/ltxbugs2html?pr=tools/3396
   \ifdim \pagetotal<\pagegoal \else
      \dimen@=\pageshrink
      \advance \dimen@ 1sp
      \kern\dimen@\penalty 9999\endgraf \kern-\dimen@
   \fi
  \dimen@\pagetotal
  \advance\dimen@ \ht\ifvoid\LT@firsthead\LT@head\else\LT@firsthead\fi
  \advance\dimen@ \dp\ifvoid\LT@firsthead\LT@head\else\LT@firsthead\fi
  \advance\dimen@ \ht\LT@foot
  \dimen@ii\vfuzz
  \vfuzz\maxdimen
    \setbox\tw@\copy\z@
    \setbox\tw@\vsplit\tw@ to \ht\@arstrutbox
    \setbox\tw@\vbox{\unvbox\tw@}%
  \vfuzz\dimen@ii
  \advance\dimen@ \ht
        \ifdim\ht\@arstrutbox>\ht\tw@\@arstrutbox\else\tw@\fi
  \advance\dimen@\dp
        \ifdim\dp\@arstrutbox>\dp\tw@\@arstrutbox\else\tw@\fi
  \advance\dimen@ -\pagegoal
% new test from me zero out pageshrink as page-so-far is boxed
\ifdim\pageshrink>\z@\pageshrink\z@\fi
  \ifdim \dimen@>\z@\vfil\break\fi
      \global\@colroom\@colht
  \ifvoid\LT@foot\else
    \global\advance\vsize-\ht\LT@foot
    \global\advance\@colroom-\ht\LT@foot
    \dimen@\pagegoal\advance\dimen@-\ht\LT@foot\pagegoal\dimen@
    \maxdepth\z@
  \fi
  \ifvoid\LT@firsthead\copy\LT@head\else\box\LT@firsthead\fi\nobreak
  \output{\LT@output}}
```

**Comment by idleroux** [comment]
My apologies for the delay in responding.  Including your redefinition of \LT@start in the tex file after \usepackage{longtable} doesn't seem to have any effect, but editing (a copy of) longtable.sty to use the new definition does fix the bug for me.  I look forward to the next release.  Thanks for investigating and correcting this!
