### ISSUE TITLE
fontmath.ltx of 2019-10-01 does \let\|=\Vert but the latter is now robust, this means \| is not strictly LaTeX2e robust

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#184]
`\|` will become `\Vert` (+space in name) when being handled in a moving argument (now that the latter is robust macro). Somehow, this looks (perhaps, I don't have strong opinion at all, just mentioning) unsatisfactory, because it means `\|` is not robust in the strict LaTeX2e sense.

Raising this because I have similar issues in a package of mine and would like to know official canon.

**Comment by FrankMittelbach** [comment]
well, I guess we have to think how that should be handled. It is similar to, say, `ä`, `\"a` and `\"{a}` all resolving to the same cannonical LICR and you could think of `\|`being a shorthand for the cannonical form `\Vert`. But I'm not saying that this is the final answer.

**Comment by davidcarlisle** [comment]
at the time using `\let` saved us a byte or two but I think now it might be better to just declare `\|` directly with`\DeclareMathDelimiter` .

In particular, previously the `\let` meant there was no dependency on the symbols, you could redefine `\Vert` without changing `\|` but now the  indirection introduces a dependency

**Comment by FrankMittelbach** [comment]
@davidcarlisle good point, so perhaps we should distangle that. But it is actually not just \Vert. Also a number of other commands made robust years ago have alias versions via let for example \ne is let to \neq (which is robust)

**Comment by FrankMittelbach** [comment]
somehow that was already fixed with the actually release of 2019-10 but not marked resolved
