### ISSUE TITLE
Provide better error message for "Missing \begin{document}"

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex2e#185]
The LaTeX error `Missing \begin{document}` is very confusing, especially for new users. Normally, people will not forget `\begin{document}` and this error is due to that something is typesetted in the preamble by mistake.

So could please consider to modify this error message? Something like "Attempt to typeset before `\begin{document}`" is much more user-friendly.

The code:

https://github.com/latex3/latex2e/blob/06814a346ab13447ba52c5f51414e9705202b648/base/lterror.dtx#L579-L587

Some links:

- https://texfaq.org/FAQ-missbegdoc
- https://www.overleaf.com/learn/latex/Errors/LaTeX%20Error:%20Missing%20%5Cbegin%20document

**Comment by PhelypeOleinik** [comment]
You're right, but I think the message is too ubiquitous to be changed.
People would be confused if it changed to something else...

What I do find annoying about that error message and could perhaps be
improved is that when the guilty code is hidden inside a macro there's
no immediate way to tell _what_ triggered the error.

I have already used something like this to help me find what is
triggering the `\@nodocument` error:
```latex
\makeatletter
\gdef\@nodocument#1{%
  \@latex@error{Missing \protect\begin{document}}{%
    I found a `#1' before the \protect\begin{document}.%
    \MessageBreak\@ehd}}
```

Then if you have something like this (pretent `\somecode` is something
more complicated):
```latex
\def\somecode{x}
\somecode
```
the error help would say:
```none
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.23 \somecode

? h
I found a `x' before the \begin{document}.
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.
?
```

which at least tells you what token triggered the error...

**Comment by blefloch** [comment]
I'm in favor of this change, provided we wrap #1 in \detokenize in the
error message.

**Comment by stone-zeng** [comment]
@PhelypeOleinik I think very few people will type an `h` to get a more detailed info. Usually the editor/IDE will simply compile the TeX file until finish.

**Comment by PhelypeOleinik** [comment]
@stone-zeng I agree, very few people (even know that they can) type `h`
to get more help. My suggestion was actually more aimed at users who
are debugging code (mostly developers?) and the change might help in
that case.

I agree with you that the wording of `\@nodocument` could be improved
to something more meaningful (indeed, I've never seen anyone actually
forget to insert a `\begin{document}`).

However I think that changing a well-known error message at this point
in time will only bring more confusion to people who are accostumed to
the `Missing \begin{document}`. Unfortunately for newcomers I think
this is a "standard bug" which should remain as it is.

That's _my_ opinion, of course :-)

**Comment by blefloch** [comment]
Could both positions be combined by making \@nodocument take an argument
and replacing the "Missing \begin{document}" message by a longer one
such as "Missing \protect\begin{document} before `\detokenize{#1}'"?

**Comment by dbitouze** [comment]
> "Missing \protect\begin{document} before `\detokenize{#1}'"?

I would phrase it the other way round: "'\detokenize{#1}' before \protect\begin{document}" because, most of the time, `\begin{document}` is not strictly speaking "missing" but wrongly located (or, better, '\detokenize{#1}' is wrongly located with respect to `\begin{document}`).

**Comment by blefloch** [comment]
On 9/27/19 9:34 AM, Denis Bitouzé wrote:
>     "Missing \protect\begin{document} before `\detokenize{#1
>     <https://github.com/latex3/latex2e/issues/1>}'"?
> 
> I would phrase it the other way round: "'\detokenize{#1
> <https://github.com/latex3/latex2e/issues/1>}' before
> \protect\begin{document}" because, most of the time, |\begin{document}|
> is not strictly speaking "missing" but wrongly located (or, better,
> '\detokenize{#1 <https://github.com/latex3/latex2e/issues/1>}' is
> wrongly located with respect to |\begin{document}|).

I agree but one requirement was to not change the message too much.  The
message should stay recognizable (to search engines at least).

**Comment by u-fischer** [comment]
I would suggest

~~~~
 \@latex@error{Missing \protect\begin{document}.\MessageBreak 
               Attempt to typeset `\detokenize{#1}' in the preamble}
~~~~

Then the first line stays (with the exception of the additional period) as it is known.

~~~~
! LaTeX Error: Missing \begin{document}.
               Attempt to typeset `x' in the preamble.
~~~~

**Comment by dbitouze** [comment]
@u-fischer If I'm right, TeX editors such as TeXstudio display only the first line of the error messages and hence what follows `\MessageBreak` wouldn't appear. What about the message you suggest but without `\MessageBreak`?

**Comment by u-fischer** [comment]
@dbitouze Without the message break you can get quite bad line breaks in the terminal and the log-file.

**Comment by car222222** [comment]
Would this work on one line? —
Missing \protect\begin{document}? - or `\detokenize{#1}' in preamble}

**Comment by davidcarlisle** [comment]
I'm not _completely_ against changing the messages but there is a big cost to doing so, books and IDEs are set up to describe the existing texts and changing the texts means they all need to update.

For example if I put some text in the preamble, emacs shows:

```
ERROR: LaTeX Error: Missing \begin{document}.

--- TeX said ---

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2 j
     jj
--- HELP ---
LaTeX produced printed output before encountering a \begin{document}
command. Either you forgot the \begin{document} command or there is
something wrong in the preamble. The problem may be a stray character
or an error in a declaration---for example, omitting the braces around
an argument or forgetting the \ in a command name.
```

It can only offer the extended help text if the error message text from the system exactly matches one of the texts that it "knows". I am sure other IDE have similar features.

**Comment by blefloch** [comment]
With the document
```
\makeatletter
\gdef\@nodocument#1{%
  \@latex@error{Missing \protect\begin{document} before "\detokenize{#1}"}\@ehd#1}
jj
```
emacs (auctex, really) produces the same help message even though the error is changed to
```
ERROR: LaTeX Error: Missing \begin{document} before "j".
```

**Comment by davidcarlisle** [comment]
@blefloch  :-) yes I suspected that there would be some flexibility in auctex's matching, but the general principle remains that these error messages are part of the documented interface.  Auctex got lucky here but I don't know what other IDE do.

**Comment by josephwright** [comment]
I think most IDEs don't offer extra help on errors, to be honest: look at all of those that manage to hide the `Undefined control sequence` so people are totally confused. Emacs is likely an outlier. What I would suggest is we ask Overleaf about their parser: that's a place that is used by a _lot_ of novices and makes it non-trivial to see the `.log`.

**Comment by eg9** [comment]
Consider
```latex
\makeatletter
\gdef\@nodocument#1{%
  \@latex@error{Missing \protect\begin{document} before "\detokenize{#1}"}\@ehd#1}
\makeatother

\documentclass{article}

\def\foo{gnu}

\foo
```

The error message would be
```latex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./nodoc.tex
LaTeX2e <2019-10-01> patch level 3
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/10/25 v1.4k Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/size10.clo))

! LaTeX Error: Missing \begin{document} before "g".

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.10 \foo
```
Not really an advancement, in my opinion.

**Comment by josephwright** [comment]
The balance here is not really worth it: the number of 'good' messages we gain compared to the number of places we break existing parsing, etc.
