### ISSUE TITLE
pkgloader maintenance by the team?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#187]
The [`pkgloader` package](https://www.ctan.org/pkg/pkgloader) "seeks to address the frustration caused by package conflicts" and it is very useful. Unfortunately, its author is ["too busy to actively maintain this package"](https://github.com/mhelvens/latex-pkgloader/issues/12#issuecomment-366548321).

Would it possible for the LaTeX2e/LaTeX3 team to maintain this package (as it does e.g. for `varioref`)?

**Comment by car222222** [comment]
Improvements in this area (package loading oder) are currently being considered by The Team and so we shall certainly look at this package, and its issues, before deciding what to do.

Meanwhile it seems to be unusable with the current version of expl3.

**Comment by dbitouze** [comment]
> Improvements in this area (package loading oder) are currently being considered by The Team

Very good news!

> and so we shall certainly look at this package, and its issues, before deciding what to do.

Naturally.

> Meanwhile it seems to be unusable with the current version of expl3.

Yes, that's what motivated this issue :)

**Comment by FrankMittelbach** [comment]
> Yes, that's what motivated this issue :)

please refrain from that :-) We are taking on way too many packges these days and it is really impossible to take on more with a handful of people and it distracts from doing more fundamental work. So the answer to such request is going to be 99.9% no.

Going to close that issue here.

**Comment by dbitouze** [comment]
>We are taking on way too many packges these days

I understand and I sympathize very much with the team!

>it distracts from doing more fundamental work

I understand but, IMHO, the package loading order is somewhat fundamental as it bites many novice users and average users and, sometimes, experienced users.

>So the answer to such request is going to be 99.9% no

Doesn't this conflicts with what @car222222  said: "Improvements in this area (package loading oder) are currently being considered by The Team"

**Comment by FrankMittelbach** [comment]
No it does not conflict with that. There is a big differance between taking on a legacy package written by somebody else where peple expect it to work the way it worked in the past and fundamental work to get LaTeX to a better state solving the same problem (or a similar problem) but without all the historical baggage. For example: tabu has a number of nice ideas but it is impossible for us to maintain it it just adds to the mess, so eventually there will be a new package for tables taking ideas from various other packages including tabu, but not keeping that alive (at least not by us). Same here. We are looking at this area but we are not going to maintain an existing package.

**Comment by josephwright** [comment]
Notably, the right solution to package load order issues is new features and interfaces in the kernel or appropriate packages. Trying to post-hoc patch the load order is much less desirable.

**Comment by dbitouze** [comment]
>or appropriate packages

Do you mean packages such as `pkgloader`?

>Trying to post-hoc patch the load order is much less desirable.

I don't understand what you mean here.

**Comment by blefloch** [comment]
I've very briefly looked at the pkgloader documentation and the
interface seems pretty reasonable, except for the TeX-like keyword
approach to declaring relations between packages.

The best place to have rules or conflict resolution code would be
directly inside packages, but it is useful to have an additional
database of rules for the many packages that will not be updated to use
any new mechanism provided directly by LaTeX.
