### ISSUE TITLE
Testing the distribution fails

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#19]
## Brief outline of the bug

When checking the distribution starting on the top level it is impossible to test only etex

## Minimal example showing the bug

```
$ texlua build.lua check -e etex

! Error: Engine "etex" not set up for testing!

  Valid values are:
  - pdftex
  - xetex
  - luatex

$ texlua build.lua check -e pdftex
Running script build.lua with target "check" for module base

! Error: Engine "pdftex" not set up for testing!

  Valid values are:
  - etex
  - xetex
  - luatex
```

**Comment by josephwright** [comment]
This is 'works for me' when run in `base`, thought the top-level is a bit more tricky.

**Comment by FrankMittelbach** [comment]
sorry, yes it works in base, I meant to write top-level and had changed that above

**Comment by josephwright** [comment]
@FrankMittelbach  Ah right, the trickier aspect.  You can already 'force' things with `texlua build.lua check -e etex -f`: is that enough or do we want something 'smoother'?

**Comment by FrankMittelbach** [comment]
If I can remember that :-) that enough for now, but it is a little weird to getthe two contradicting error messages
