### ISSUE TITLE
multicol incorrectly using \maxdepth=0pt when splitting boxes

### ISSUE THREAD

**Issue by polysyllabic** [latex3/latex2e#190]
## Outline of the bug
I believe [this stackexchange question](https://tex.stackexchange.com/questions/509198/inconsistent-spacing-after-multicols-inside-figure) is the result of an edge case triggering a subtle bug.

The sequence of events is as follows:
1. A multicol environment is inserted into a bottom figure.
2.  `\@addtobot` globally sets` \maxdepth` to 0pt.
3. A second multicol environment is inserted into another bottom figure before the first one is output.

In this case, the `\balance@columns` routine will use `\maxdepth=0pt` when trying to split the vertical boxes. If the actual depth of the last line in the columns is >0, this makes the initial height of the first column too short after reboxing, and in attempting to try to rebalance the columns, an amount equivalent to that missing depth eventually gets added to the total column height.

The result is two multicolumn boxes of different heights even when they contain identical text.

I believe this issue can be fixed by replacing references to `\maxdepth` with `\@maxdepth`.

## Minimal example showing the bug
Note that latexbug complains about the use of lipsum. Shouldn't it be ignoring that package?

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[balancingshow]{multicol}
\usepackage{lipsum}

\newcommand\blockitem[1]{\par#1\strut}

\newsavebox{\demobox}

\newenvironment{blocklist}{%
  \begin{lrbox}{\demobox}
    \begin{minipage}[b]{\textwidth}
      \begin{multicols}{3}}{%
      \end{multicols}
    \end{minipage}
  \end{lrbox}%
  \begin{figure*}[!b]
    \fbox{\usebox{\demobox}}
    \par Box Height=\the\ht\demobox
  \end{figure*}
  }

\begin{document}

\begin{multicols}{3}
  \lipsum[1-4]
  \begin{blocklist}
    \blockitem{Alfa} \blockitem{Bravo} \blockitem{Charlie} \blockitem{Delta} \blockitem{Echo} \blockitem{Foxtrot} \blockitem{Golf} \blockitem{Hotel} \blockitem{India}
  \end{blocklist}
  \lipsum[1-4]
  \begin{blocklist}
    \blockitem{Alfa} \blockitem{Bravo} \blockitem{Charlie} \blockitem{Delta} \blockitem{Echo} \blockitem{Foxtrot} \blockitem{Golf} \blockitem{Hotel} \blockitem{India}
  \end{blocklist}
  \lipsum[1-8]
  \begin{blocklist}
    \blockitem{Alfa} \blockitem{Bravo} \blockitem{Charlie} \blockitem{Delta} \blockitem{Echo} \blockitem{Foxtrot} \blockitem{Golf} \blockitem{Hotel} \blockitem{India}
\end{blocklist}
  \lipsum[1-8]
\end{multicols}
\end{document}
```

## Log file (required) and possibly PDF file  
[mc-spacing-test.log](https://github.com/latex3/latex2e/files/3684016/mc-spacing-test.log)
[mc-spacing-test.pdf](https://github.com/latex3/latex2e/files/3684024/mc-spacing-test.pdf)

**Comment by FrankMittelbach** [comment]
fixed in development for spring release

**Comment by FrankMittelbach** [comment]
Decision to keep issues open until fixed in stable release
