### ISSUE TITLE
problems with \includegraphics after `graphics` bundle release 2019-10-01 

### ISSUE THREAD

**Issue by open711** [latex3/latex2e#191]
## Brief outline of the bug
I just installed an update of the graphics bundle via MiKTeX (available since Fr Okt 4 22:11:27 2019).
After the update my document won't compile anymore. The error message arelinked to \includeprahics.
I am not sure if it the graphics package is the source of the problem. Packages that have been also updated today:

- l3kernel
- miktex-misc
- tools
- xcharter

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{graphicx}

\begin{document}
 text
\begin{figure}[tbp]
\centering
\includegraphics[width=0.7\textwidth]{test.pdf}
\caption{test}
\label{fig:test}
\end{figure}
  
\end{document}
```

## Log file (required) and possibly PDF file  
I couldn't upload the log file, so I copy and pasted it.
<details open=""><summary><strong>Log-file</strong></summary>
This is LuaTeX, Version 1.10.0 (MiKTeX 2.9.7200 64-bit)  (format=lualatex 2019.10.5)  5 OCT 2019 16:03
 restricted system commands enabled.
**minimal_example_graphics.tex
(./minimal_example_graphics.tex
LaTeX2e <2018-12-01>
Lua module: luaotfload-main 2019-09-13 3.00 luaotfload entry point
Lua module: luaotfload-init 2019-09-13 3.00 luaotfload submodule / initializatio
n
Lua module: lualibs 2019-08-11 2.67 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2019-08-11 2.67 ConTeXt Lua libraries -- extended c
ollection.
Lua module: luaotfload-log 2019-09-13 3.00 luaotfload submodule / logging
Lua module: luaotfload-parsers 2019-09-13 3.00 luaotfload submodule / filelist
Lua module: luaotfload-configuration 2019-09-13 3.00 luaotfload submodule / conf
ig file reader
luaotfload | conf : Root cache directory is C:/Users/usr/AppData/Local/MiKTeX
/2.9/luatex-cache/generic/names.
luaotfload | init : Loading fontloader “fontloader-2019-08-11.lua” from kpse
-resolved path “C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/luatex/l
uaotfload/fontloader-2019-08-11.lua”.
Lua-only attribute luaotfload@state = 2
Lua-only attribute luaotfload@noligature = 3
Lua-only attribute luaotfload@syllabe = 4
luaotfload | init : Context OpenType loader version “3.109”
Inserting `luaotfload.node_processor' at position 1 in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' at position 1 in `hpack_filter'.
Lua module: luaotfload-loaders 2019-09-13 3.00 luaotfload submodule / callback h
andling
Inserting `luaotfload.define_font' at position 1 in `define_font'.
Lua module: luaotfload-database 2019-09-13 3.00 luaotfload submodule / database
Lua module: luaotfload-unicode 2019-09-13 3.00 luaotfload submodule / Unicode he
lpers
Lua module: luaotfload-colors 2019-09-13 3.00 luaotfload submodule / color
Lua-only attribute luaotfload_color_attribute = 5
Lua module: luaotfload-resolvers 2019-09-13 3.00 luaotfload submodule / resolver
s
luaotfload | conf : Root cache directory is C:/Users/usr/AppData/Local/MiKTeX
/2.9/luatex-cache/generic/names.
Lua module: luaotfload-features 2019-09-13 3.00 luaotfload submodule / features
Lua module: luaotfload-letterspace 2019-09-13 3.00 luaotfload submodule / color
Lua module: luaotfload-embolden 2019-09-13 3.00 luaotfload submodule / color
Lua module: luaotfload-notdef 2019-09-13 3.00 luaotfload submodule / color
Lua module: luaotfload-auxiliary 2019-09-13 3.00 luaotfload submodule / auxiliar
y functions
Inserting `luaotfload.aux.set_sscale_dimens' at position 1 in `luaotfload.patch_
font'.
Inserting `luaotfload.aux.patch_cambria_domh' at position 2 in `luaotfload.patch
_font'.
Inserting `luaotfload.aux.fixup_fontdata' at position 1 in `luaotfload.patch_fon
t_unsafe'.
Inserting `luaotfload.aux.set_capheight' at position 3 in `luaotfload.patch_font
'.
Inserting `luaotfload.aux.set_xheight' at position 4 in `luaotfload.patch_font'.
Lua module: luaotfload-multiscript 2019-09-13 3.00 luaotfload submodule / multis
cript
Inserting `luaotfload.rewrite_fontname' at position 5 in `luaotfload.patch_font'
.
luaotfload | main : initialization completed in 1.516 seconds

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/latexbug/latexbug
.sty"
Package: latexbug 2019/09/13 v1.0f Bug-classification
)
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/article.cls"
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/base/size10.clo"
File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
luaotfload | db : Font names database loaded from C:/Users/usr/AppData/Local/
MiKTeX/2.9/luatex-cache/generic/names/luaotfload-names.luc)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/graphics/graphicx
.sty"
Package: graphicx 2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/graphics/keyval.s
ty"
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
)
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/graphics/graphics
.sty"
Package: graphics 2019/07/20 v1.3b Standard LaTeX Graphics (DPC,SPQR)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/graphics/trig.sty
"
Package: trig 2016/01/03 v1.10 sin cos tan (DPC)
)
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/graphics-cfg/grap
hics.cfg"
File: graphics.cfg 2016/06/04 v1.11 sample graphics configuration
)
Package graphics Info: Driver file: luatex.def on input line 105.

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/graphics-def/luat
ex.def"
File: luatex.def 2018/01/08 v1.0l Graphics/color driver for luatex
))
\Gin@req@height=\dimen103
\Gin@req@width=\dimen104
)
No file minimal_example_graphics.aux.

\openout1 = minimal_example_graphics.aux
LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/context/base/mkii/supp-
pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
\scratchcounter=\count88
\scratchdimen=\dimen105
\scratchbox=\box27
\nofMPsegments=\count89
\nofMParguments=\count90
\everyMPshowfont=\toks15
\MPscratchCnt=\count91
\MPscratchDim=\dimen106
\MPnumerator=\count92
\makeMPintoPDFobject=\count93
\everyMPtoPDFconversion=\toks16
)
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/oberdiek/epstopdf
-base.sty"
Package: epstopdf-base 2016/05/15 v2.6 Base part for package epstopdf

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/infwar
err.sty"
Package: infwarerr 2016/05/16 v1.4 Providing info/warning/error messages (HO)
)
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/oberdiek/grfext.s
ty"
Package: grfext 2016/05/16 v1.2 Manage graphics extensions (HO)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/kvdefi
nekeys.sty"
Package: kvdefinekeys 2016/05/16 v1.4 Define keys (HO)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/ltxcmd
s.sty"
Package: ltxcmds 2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
)))
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/latex/oberdiek/kvoption
s.sty"
Package: kvoptions 2016/05/16 v3.12 Key value format for package options (HO)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/kvsetk
eys.sty"
Package: kvsetkeys 2016/05/16 v1.17 Key value parser (HO)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/etexcm
ds.sty"
Package: etexcmds 2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/ifluat
ex.sty"
Package: ifluatex 2016/05/16 v1.4 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX detected.
))))
("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/pdftex
cmds.sty"
Package: pdftexcmds 2019/07/25 v0.30 Utility functions of pdfTeX for LuaTeX (HO)

("C:/Users/usr/AppData/Local/Programs/MiKTeX 2.9/tex/generic/oberdiek/ifpdf.
sty"
Package: ifpdf 2018/09/07 v3.3 Provides the ifpdf switch
)
Package pdftexcmds Info: \pdf@primitive is available.
Package pdftexcmds Info: \pdf@ifprimitive is available.
Package pdftexcmds Info: \pdfdraftmode found.
\pdftexcmds@toks=\toks17
)
Package epstopdf-base Info: Redefining graphics rule for `.eps' on input line 43
8.
Package grfext Info: Graphics extension search list:
(grfext)             [.pdf,.png,.jpg,.mps,.jpeg,.jbig2,.jb2,.PDF,.PNG,.JPG,.JPEG
,.JBIG2,.JB2,.eps]
(grfext)             \AppendGraphicsExtensions on input line 456.
)
! Undefined control sequence.
\Ginclude@graphics ...\Ginput@path \set@curr@file 
                                                  {#1}\edef \uq@curr@file {\...
l.8 \includegraphics[width=0.7\textwidth]{test.pdf}
                                                 
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
\Ginclude@graphics ...e \expandafter {\@curr@file 
                                                  }}\expandafter \filename@p...
l.8 \includegraphics[width=0.7\textwidth]{test.pdf}
                                                 
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
<recently read> \unquote@name 
              
l.8 \includegraphics[width=0.7\textwidth]{test.pdf}
                                                 
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
<recently read> \quote@name 
            
l.8 \includegraphics[width=0.7\textwidth]{test.pdf}
                                                 
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
<recently read> \quote@name 
            
l.8 \includegraphics[width=0.7\textwidth]{test.pdf}
                                                 
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Undefined control sequence.
<recently read> \unquote@name 
              
l.8 \includegraphics[width=0.7\textwidth]{test.pdf}
                                                 
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

)
Runaway argument?
{{}{}.pdf }\edef \Gin@ext {\Gin@temp }\fi \def \Gin@temp {.png}\ifx \Gin@temp \
ETC.
! File ended while scanning use of \@tempa.
<inserted text> 
\par 
<*> minimal_example_graphics.tex
                             
I suspect you have forgotten a `}', causing me
to read past where you wanted me to stop.
I'll try to recover; but if the error is serious,
you'd better type `E' or `X' now and fix your file.

! Emergency stop.
<*> minimal_example_graphics.tex
                             
*** (job aborted, no legal \end found)

Here is how much of LuaTeX's memory you used:
 2009 strings out of 494291
 100000,106986 words of node,token memory allocated 625 words of node memory still in use:
   4 hlist, 2 rule, 2 local_par, 2 dir, 3 glue, 3 kern, 17 glyph, 6 attribute, 5
7 glue_spec, 6 attribute_list, 3 temp, 5 if_stack, 1 write nodes
   avail lists: 2:1,3:1,4:1,5:1
 6209 multiletter control sequences out of 65536+200000
 15 fonts using 723495 bytes
 41i,2n,25p,275b,487s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!
</details>

**Comment by davidcarlisle** [comment]
This appears to be a miktex packaging issue

https://github.com/MiKTeX/miktex-packaging/issues/131

latex base, tools, graphics were all updated together, but unfortunately the base code has not been distributed with miktex. I assume that it will be fixed there soon.
