### ISSUE TITLE
\extracolsep{\fill} broken?

### ISSUE THREAD

**Issue by bgvoisin** [latex3/latex2e#192]
## Brief outline of the bug

@{\extracolsep{\fill}} as column specifier seems to produce the same output as @{}. This seems a fairly recent bug. I don't know whether that's related to the fix for issue #102.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

\begin{tabular}{lr}
AA & BB \\
x  & y \\
\end{tabular}

\begin{tabular*}{10cm}{l@{\extracolsep{\fill}}r}
AA & BB \\
x  & y  \\
\end{tabular*}

\end{document}
```

## Log file (required) and possibly PDF file  

[test-potentialbug.log](https://github.com/latex3/latex2e/files/3698373/test-potentialbug.log)
[test-potentialbug.pdf](https://github.com/latex3/latex2e/files/3698374/test-potentialbug.pdf)

**Comment by FrankMittelbach** [comment]
A bug indeed, but nothing to do with #102. It is due to making `\extracolsep` robust.
For now please add
```
\renewcommand\extracolsep[1]{\tabskip #1\relax}
```
to the document preamble.

**Comment by FrankMittelbach** [comment]
should get deployed during the next days
