### ISSUE TITLE
Documentation of filecontents environment: package vs environment

### ISSUE THREAD

**Issue by moewew** [latex3/latex2e#193]
The documentation of the `filecontents` *environment* currently has the line

https://github.com/latex3/latex2e/blob/61d717124a56a854cb96c62e5692fe7edd53b92e/base/ltclass.dtx#L158

mentioning a *package*. Since I was coming from using the `filecontents` package and was trying to figure out why I wasn't getting the overwriting behaviour any more, this confused me for quite a while. I assume this is simply a typo and it should have been

```latex
% The environment can also be called with an optional argument which is
```

**Comment by FrankMittelbach** [comment]
thanks gain
