### ISSUE TITLE
[shellesc] Add runsystem(...) to log file when using lualatex

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#195]
## Brief outline of the feature request
When using `lualatex` in combination with package `shellesc` it would be great to have some information about executed system commands like `pdflatex` does with `runsystem` in the log file. Currently, nothing is displayed which makes debugging more complicated with packages relying on `\ShellEscape` (e.g. `svg` or `pstricks-pdf`).

## Minimal example showing feature request
```latex
\documentclass{article}
\usepackage{shellesc}
\usepackage{pdftexcmds}
\begin{document}
\makeatletter
\ifluatex
  \wlog{+++++ requested feature +++++}
  \ifcase\pdf@shellescape
    \wlog{runsystem(echo "foo")...disabled.}
  \or
    \wlog{runsystem(echo "foo")...executed.}
  \else
    \wlog{runsystem(echo "foo")...disabled (restricted).}
  \fi
\fi
\makeatother
\ShellEscape{echo "foo"}
\meaning\ShellEscape
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/3717618/test.log)

**Comment by davidcarlisle** [comment]
This seems a perfectly reasonable suggestion, thanks.

**Comment by FrankMittelbach** [comment]
... and a  backslash to `\LaTeX` while your at it :-)

**Comment by davidcarlisle** [comment]
I am having difficulty implementing this presently, as currently the package just does

`os.execute("echo foo")`

and the details of whether this runs or not is in the luatex internals.  clearly if the shell escape status is 0 or 1 then it is easy to say whether it runs or not, but in the default case then (if luatex doesn't log this automatically) the Lua code would have to look up `echo` in the restricted command list to see if it can run, to log the correct action.

The luatex manual hints that this information could be in `texconfig.shell_escape_commands` but currently I am not seeing anything useful in the `texconfig` table.  Investigating.....

**Comment by davidcarlisle** [comment]
ah.. The information can be reached via the kpse library:

```
\directlua{
print(kpse.var_value('shell_escape_commands'))
}
```

**Comment by mrpiggi** [comment]
Package `pdftexcmds` does

```
\protected\edef\pdf@shellescape{%
  \numexpr\directlua{tex.sprint(%
       \number\catcodetable@string,status.shell_escape)}\relax}
```

**Comment by davidcarlisle** [comment]
@minoki  that only tells you if `--shell-escape`  has been used (this package does equivalent) but it doesn't tell you in the default case that say `echo` will not execute but `bibtex`  will, the code suggested above will do that but actually Marcel has suggested a better test, I will commit a version to the sources shortly

**Comment by davidcarlisle** [comment]
with the version in the last checkin then the logging is

```
runsystem(echo "foo")...(Command execution disabled via shell_escape='p')
runsystem(eckho "foo")...(Command execution disabled via shell_escape='p')
runsystem(bibtex "zzz")...failed 
```

note it distinguished the case of echo (not allowed) with bibtex zzz (allowed but returns error)

if you use `--no-shell-escape` the logging is
```

runsystem(echo "foo")...(All command execution disabled.)
runsystem(eckho "foo")...(All command execution disabled.)
runsystem(bibtex "zzz")...(All command execution disabled.)
```

**Comment by mrpiggi** [comment]
Thanks a lot. So now, the LuaLaTeX even reports, if the execution of a shell command was successful or not, in contrast to pdfLaTeX, where the execution itself is only reported. That's great.

**Comment by davidcarlisle** [comment]
This went out with LaTeX2e 2019-10-01 patch level 2 but there was a typo which meant it set the catcode of `"` to be a math subscript for the rest of the document

https://github.com/wspr/fontspec/issues/389

So the working version, v1.0c is in the latex-tools release 2019-11-08 which went to CTAN today.

Thanks for the suggestion, closing...
