### ISSUE TITLE
Latest LaTeX version and package pst-pdf (preview)

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex2e#196]
```
%\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
%\RequirePackage[2018/12/01]{latexrelease}
\documentclass{article}
\usepackage{pst-pdf}
\begin{document}
\includegraphics{example-image}

\begin{pspicture}[showgrid](5,5)
\end{pspicture}
\end{document}
```

running `latex <file>` creates _two_ pages in the `dvi`. From the log file:

> [...]
> Preview: Fontsize 10pt
> <example-image.eps>
> Preview: Tightpage -32891 -32891 32891 32891
> [1] [2] )
> (see the transcript file for additional information)
> Output written on zzz7.dvi (2 pages, 2108 bytes).
> Transcript written on zzz7.log.

Using an older LaTeX release (uncomment the line) it creates the expected dvi file with _one_ page

> [...]
> Preview: Fontsize 10pt
> Preview: Tightpage -32891 -32891 32891 32891
> [1] )
> (see the transcript file for additional information)
> Output written on zzz7.dvi (1 page, 1936 bytes).
> Transcript written on zzz7.log.
> 

The package `pst-pdf` and `preview` had no changes since 2018. 
Up-to-date TL 2019

**Comment by davidcarlisle** [comment]
Thanks for the test file. I'll see what I can do (you get 2 pages using a 2017 format with the 2019 graphics.sty which narrows down the changed behaviour to a few lines, but tracing what pst-pdf needs to do to work correctly with the new file handling (which allows non-ascii characters in filenames, which requires some additional quoting) may take a bit of thought (a lot of graphics commands are being patched here:-)

**Comment by u-fischer** [comment]
@davidcarlisle it seems to be a catcode issue. A test fails as the extension has catcode 12 now. When I add a \detokenize it works again:

```
\documentclass{article}
\usepackage{pst-pdf}
\makeatletter
\renewcommand*\ppf@is@pdfTeX@graphic[5]{%
  \@ppf@pdftex@graphicfalse%
  \begingroup
    \edef\pdfTeXext{\detokenize\expandafter{#2}}%<----added
    \def\Gin@setfile##1##2##3{%
      \edef\@tempb{##2}%
      \@for\@tempa:=\pdfTeXext\do{%
        \ifx\@tempa\@tempb\global\@ppf@pdftex@graphictrue\fi}}%
    \edef\Gin@extensions{#2,#3}%
    \pr@outerfalse\ppf@Ginclude@graphics{#1}%
  \endgroup
  \if@ppf@pdftex@graphic#4\else#5\fi
}

\begin{document}
\includegraphics{example-image}
\begin{pspicture}[showgrid](5,5)
\end{pspicture}
\end{document}
```

**Comment by davidcarlisle** [comment]
@u-fischer  yes definitely catcodes I was just looking around the `\pp@` code to see where to normalize them, thanks for the pointer

**Comment by u-fischer** [comment]
@davidcarlisle perhaps a better place to normalize it would be to do it for \@tempa and @tempb just before the `\ifx\@tempa\@tempb` then it would work also with older setups.

**Comment by davidcarlisle** [comment]
@u-fischer  here?
```

\documentclass{article}
\usepackage{pst-pdf}
\makeatletter
\renewcommand*\ppf@is@pdfTeX@graphic[5]{%
  \@ppf@pdftex@graphicfalse%
  \begingroup
    \edef\pdfTeXext{\detokenize\expandafter{#2}}%<----added
    \def\Gin@setfile##1##2##3{%
      \edef\@tempb{\detokenize\expandafter{##2}}%
      \@for\@tempa:=\pdfTeXext\do{%
        \ifx\@tempa\@tempb\global\@ppf@pdftex@graphictrue\fi}}%
    \edef\Gin@extensions{#2,#3}%
    \pr@outerfalse\ppf@Ginclude@graphics{#1}%
  \endgroup
  \if@ppf@pdftex@graphic#4\else#5\fi
}

\begin{document}
\includegraphics{example-image}
\begin{pspicture}[showgrid](5,5)
\end{pspicture}
\end{document}
```

**Comment by u-fischer** [comment]
I meant here

~~~
      \@for\@tempa:=\pdfTeXext\do{%
        \edef\@tempa{\detokenize\expandafter{\@tempa}}%<---
        \edef\@tempb{\detokenize\expandafter{\@tempb}}%<---
        \ifx\@tempa\@tempb\global\@ppf@pdftex@graphictrue\fi}}%
~~~

**Comment by davidcarlisle** [comment]
yes but then you do ` \edef\@tempb{\detokenize\expandafter{\@tempb}}%<---` which is same thing each time round the loop so I think you can the tempb one  that just once before the loop.

**Comment by u-fischer** [comment]
Yes, you are right, sitting in the sun and hadn't seen that you had detokenized the \@tempb ;-) already. Your code looks good too.

**Comment by davidcarlisle** [comment]
@hvoss49  does the code in my comment above work with any real  pstricks tests you have to hand? Given that it is rewriting `\Gin@setfile` here I suspect I can't address this from the graphics package code and the pst-pdf code will need to adapt, which is unfortunate but probably unavoidable if we are to get non ascii filename support working consistently,

**Comment by hvoss49** [comment]
Thanks David, it works fine in bigger documents, too. We will 
make the changes in pst-pdf.

Herbert

**Comment by mrpiggi** [comment]
I was just wondering, if a macro like this would make sense within the kernel
```tex
\newcommand\kernel@ifstr[2]{%
  \begingroup
    \protected@edef\reserved@a{\detokenize\expandafter{#1}}
    \protected@edef\reserved@b{\detokenize\expandafter{#2}}
    \ifx\reserved@a\reserved@b
      \aftergroup\@firstoftwo
    \else
      \aftergroup\@secondoftwo
    \fi
  \endgroup
}
```
