### ISSUE TITLE
amsmath: document newly added \overunderset

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#197]
Although `\overunderset` is added in amsmath v2.17c 2019/04/01 (see #125), it is not documented in user manual `amsldoc.(tex|pdf)` yet. The corresponding section is

https://github.com/latex3/latex2e/blob/c21736631d69629f216177af63f95bc1c7eff220/required/amsmath/amsldoc.tex#L1368-L1379

**Comment by davidcarlisle** [comment]
Thanks for the reminder, we will add  for next release,

David

**Comment by muzimuzhi** [comment]
Thanks. You can close the issue if needed.

**Comment by davidcarlisle** [comment]
fixed in master branch, closing
