### ISSUE TITLE
Standard article class with rollback error

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#201]
## Brief outline of the bug

Rolling back to 2014/12/31, \documentclass{article} throws an error:

```
! Undefined control sequence.
l.55 \MakeRobust
                \normalsize
?
```

## Minimal example showing the bug

``` tex
\RequirePackage{latexbug}
\RequirePackage[2014/12/31]{latexrelease}
\documentclass{article}
\begin{document}
a
\end{document}
```

## Log file (required) and possibly PDF file  

- [roll.log](https://github.com/latex3/latex2e/files/3771956/roll.log)

**Comment by PhelypeOleinik** [comment]
`\MakeRobust` was introduced in [2015/01/08](https://github.com/latex3/latex2e/blob/c5a4a4cded7ec6b27a2be7227e0887ce73d20137/base/ltdefns.dtx#L1170). Loading `latexrelease` with a date prior to `2015/01/01` undefines `\MakeRobust`:
```latex
\IncludeInRelease{0000/00/00}{\MakeRobust}{\MakeRobust}%
\let\MakeRobust\@undefined
\EndIncludeInRelease
```
Adding one day to your document makes it work:
```latex
\RequirePackage{latexbug}
\RequirePackage[2015/01/01]{latexrelease}
\documentclass{article}
\begin{document}
a
\end{document}
```

Do you _need_ 2014/12/31?

**Comment by aminophen** [comment]
*I* don't need 2014/12/31, but requesting for completeness; someone would expect supporting older date because LaTeX2e dated 2015/01/01 introduced many incompatible changes.

**Comment by aminophen** [comment]
The classes.pdf says

> We use \MakeRobust instead of \DeclareRobustCommand above to avoid a log entry for the redefinition.

The extra log entry is ignorable compared to the error, IMHO supporting the older date is relatively easy.

**Comment by FrankMittelbach** [comment]
Well, yes, maybe :-) but I don't think we want to clutter each and every log file with info about all those redefinitions either, so I'll have to see what to do here.

**Comment by aminophen** [comment]
If you prefer \NeedsTeXFormat{LaTeX2e}[2015/01/01], that'll be fine with *me*.

**Comment by PhelypeOleinik** [comment]
@aminophen Ah, sorry, I see the problem now. You're right. I overlooked the fact that the code should work with either date.

**Comment by FrankMittelbach** [comment]
> If you prefer \NeedsTeXFormat{LaTeX2e}[2015/01/01], that'll be fine with _me_.

that would prevent any rollback prior 2015(like now). No I think I just don't do anything if \MakeRobust is unavailable.

**Comment by aminophen** [comment]
> I think I just don't do anything if \MakeRobust is unavailable.

Oh, I see; that's far better, thanks

**Comment by FrankMittelbach** [comment]
done for next PL
