### ISSUE TITLE
Unbalanced conditionals in .toc after 2018/12/01

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex2e#202]
## Brief outline of the bug

From here: https://tex.stackexchange.com/q/513617

After the `2018/12/01` release, with the fix for #73 one cannot write unbalanced conditionals to the `.toc` file anymore.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
% \RequirePackage[2018/11/30]{latexrelease}
\documentclass{article}
\begin{document}
\addtocontents{toc}{\protect\iffalse}
\addtocontents{toc}{something}
\addtocontents{toc}{\protect\fi}
\tableofcontents
\section{test}
\end{document}
```

## Log file:

[test.log](https://github.com/latex3/latex2e/files/3772256/test.log)

## Suggested fix:

Moving the assignment of `\@temptokena` outside of the `\ifx...\fi` in `\add@percent@to@temptokena` seems to solve the problem:
```latex
\long\def\add@percent@to@temptokena
    #1\protected@file@percent#2\add@percent@to@temptokena
    {\ifx!#2!\expandafter\dont@add@percent@to@temptokena\else
             \expandafter\do@add@percent@to@temptokena\fi{#1}}
\long\def\dont@add@percent@to@temptokena#1{%
  \@temptokena\expandafter{#1}}
\begingroup
\catcode`\%=12
\catcode`\^^A=9
\long\gdef\do@add@percent@to@temptokena#1{%
  \@temptokena\expandafter{#1%^^A
  }}
\endgroup
```

**Comment by FrankMittelbach** [comment]
not sure I would cound unbalanced lowlevel condistionals as supported syntax in that place :-) but  ...

**Comment by daleif** [comment]
Here is a use case, https://tex.stackexchange.com/q/512742/3929, but Ulrikes suggestion in https://tex.stackexchange.com/a/513634/3929 seems to work just fine.

Is see no better way to solve the OPs requirement of having two tocs and two toc in toc entries that are conditionally shown. Most robust method in that case seems to patch \tableofcontents and add conditionals around the \addcontentsline

**Comment by FrankMittelbach** [comment]
@daleif oh I dn't doubtthat there are use cases for unsupported syntax :-) ... anyway, it will get resolved @PhelypeOleinik 's suggested fix should work just fine.

**Comment by FrankMittelbach** [comment]
done for next PL

**Comment by Ulrich-Diez** [comment]
[Here are some suggestions how I would probably handle this issue.](https://tex.stackexchange.com/a/513685/118714)

**Comment by jfbu** [comment]
@daleif sorry to hijack this issue but I don't visit tex.sx but do visit here from time to time. I see a user "murray" asked the question you link to. If you have a way to ping him, yes of course this is easily done with `etoc` package. Queries addressed directly to `etoc` author are always welcome. Isn't it always better to go to source than to use some Q&A site?

**Comment by schlcht** [comment]
With the new implementation, you can get some disconcerting log output. This for example:

```
%\RequirePackage{latexbug}
%\RequirePackage[2018/11/30]{latexrelease}
\documentclass{article}
\usepackage{hyperref}
\usepackage{hypdestopt}
\begin{document}
\tableofcontents
\def\x{\hyperpage{1}A }
\def\y{\x\x\x\x\x\x\x\x\x\x\x}
\def\z{\y\y\y\y\y\y\y\y\y\y\y}
\section{A}
\z\z\z\z\z\z\z
\section{B}
\z\z\z\z\z\z\z
\end{document}
```

will yield:

```
...
Overfull \hbox (1575.5484pt too wide) in paragraph at lines 870--15
[]\OT1/cmr/m/n/10 %                                                            
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
                                                                               
%
...
```

(ie. two percent characters, and loads of spaces in between)

If you remove the `hypdestopt` package, all is fine, but so it is when using the old latex release, so I'm not sure who's to blame here.

**Comment by blefloch** [comment]
Thanks @schlcht, this is a bug.  When the following definition is made, percent has catcode other, so the first `%` ends up in the definition of `\do@add@percent@to@temptokena`.  The fix will be to replace `%` by `^^A` I suppose.  I'm a bit confused at present on top of which branch I should fix that, so I'll let one of the others do the fix please.  I'm also confused why the percent characters don't end up visibly typeset; it might be because the problem shows up while processing the aux file at `\end{document}`.
```
\long\gdef\do@add@percent@to@temptokena#1{%
  \@temptokena\expandafter{#1%^^A
  }}
```

**Comment by davidcarlisle** [comment]
Apart from `%` not being a comment, ^^A is added as a comment but it's catcode 9sothe current definition adds a space at the end, I think it should be

```
\begingroup
\catcode`\%=12
\catcode`\^^A=14
\long\gdef\do@add@percent@to@temptokena#1{\@temptokena\expandafter{#1%^^A
  }}
\endgroup
```

**Comment by davidcarlisle** [comment]
This has just been sent to ctan as 2010-10-01 Patch Level 3, @schlcht thanks again for reporting this.
