### ISSUE TITLE
Interference between doc package and \verbvisiblespace in (xe|lua)tex

### ISSUE THREAD

**Issue by pablgonz** [latex3/latex2e#205]
## Brief outline of the bug
When you load the `doc` package and compile using `xelatex` or `lualatex` the `visible spaces` in `verbatim` disappear. If you redefine `\verbvisiblespace` the problem persists. Use `TeXLive 2019` (updated to date) under `fedora 30`. Just to complement it, in the documentation of `fontspec` page 7 you can see that the character of `visible space` does not appear.

I assume the `doc` package lacks updates to use `\verbvisiblespace`, the documentation date on my system is `2018/09/25` and `\verbvisiblespace` was implemented in (https://github.com/latex3/latex2e/issues/70) on 12 Oct 2018.
```
$ pdffonts luadefault.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
UAOKEN+LMMono10-Regular              CID Type 0C       Identity-H       yes yes yes      4  0
DGBCZV+CMTT10                        Type 1            Builtin          yes yes no       5  0
TGBOVF+LMRoman10-Regular             CID Type 0C       Identity-H       yes yes yes      6  0
```
```
$ pdffonts luawithdoc.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
JAPUPS+LMMono10-Regular              CID Type 0C       Identity-H       yes yes yes      4  0
TGBOVF+LMRoman10-Regular             CID Type 0C       Identity-H       yes yes yes      5  0
DGBCZV+CMTT10                        Type 1            Builtin          yes yes no       6  0
ZQJNWC+LMMono9-Regular               CID Type 0C       Identity-H       yes yes yes      7  0
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass{article}
%\usepackage{doc}
%\DeclareRobustCommand\verbvisiblespace{{\fontfamily{lmtt}\selectfont\char"2423}}
\pagestyle{empty}
\begin{document}
\verb*|x   x| and \verb*|   | 
Some\verbvisiblespace text\textvisiblespace and 
\begin{verbatim*}
  x  x
\end{verbatim*}
\end{document}
```
Output of the document without the `doc` package:
![luadefault-crop-1](https://user-images.githubusercontent.com/2289461/67789450-61fceb80-fa4a-11e9-939f-bb54b8de7eda.png)
Output of the document with the `doc` package:
![luawithdoc-crop-1](https://user-images.githubusercontent.com/2289461/67789644-b011ef00-fa4a-11e9-91a4-a32ea49aa485.png)

## Log file (required) and possibly PDF file  

[luadefault.log](https://github.com/latex3/latex2e/files/3784795/luadefault.log)
[luadefault.pdf](https://github.com/latex3/latex2e/files/3784796/luadefault.pdf)
[luawithdoc.log](https://github.com/latex3/latex2e/files/3784797/luawithdoc.log)
[luawithdoc.pdf](https://github.com/latex3/latex2e/files/3784798/luawithdoc.pdf)

**Comment by FrankMittelbach** [comment]
will show up with the next PL
