### ISSUE TITLE
Make xr package work with beamer's \againframe

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#206]
Suppose I'd like to extract from a main (long) `beamer` file some of the frames it contains. It would be nice if the `xr` package could work with `\againframe`, as in the following example (where the compilation of `extracted-frames.tex` fails):

```latex
\begin{filecontents*}[overwrite]{extracted-frames}
\documentclass{beamer}
\usepackage{xr}
\externaldocument{main}
\begin{document}
\againframe{bar}
\end{document}
\end{filecontents*}

\documentclass{beamer}
\begin{document}
\begin{frame}[label=foo]
  \frametitle{Foo}
  Foo
\end{frame}
\begin{frame}[label=bar]
  \frametitle{Bar}
  Bar
\end{frame}
\end{document}
```

BTW, there is a typo in the documentation of `xr`:

>For fcompatibility with `xcite`

**Comment by davidcarlisle** [comment]
Thanks for the type reference but I suspect that you need to put in a feature request to beamer rather than here, 

I don't know how the beamer feature works (@josephwright  ?) but I suspect that it would need to read a lot of beamer-specific code such as the  `.snm`  file

```
\beamer@slide {foo<1>}{1}
\beamer@slide {foo}{1}
\beamer@slide {bar<1>}{2}
\beamer@slide {bar}{2}
```

and beamer specific `aux` lines

```
\newlabel{foo<1>}{{1}{1}{}{Doc-Start}{}}
\@writefile{snm}{\beamer@slide {foo<1>}{1}}
\newlabel{foo}{{1}{1}{}{Doc-Start}{}}
\@writefile{snm}{\beamer@slide {foo}{1}}
```

If you had added `\RequirePackage{latexbug}` to the test file as requested  then latex would have warned you that this was the wrong repository:


```
! Package latexbug Error: Third-party file(s)
(latexbug)                
(latexbug)                This test file uses third-party file(s)
(latexbug)                
(latexbug)                ==============
(latexbug)                beamer.cls  ->  Joseph Wright 
(latexbug)                    https://github.com/josephwright/beamer/issues
(latexbug)                ==============
(latexbug)                
(latexbug)                So you should contact the authors
(latexbug)                of these files, not the LaTeX Team!
(latexbug)                (Or remove the packages that load
(latexbug)                them, if they are not necessary to
(latexbug)                exhibit the problem).
```

**Comment by samcarter** [comment]
@dbitouze

as a workaround, you could use the `catchfilebetweentags` package to import individual frames from other documents

**Comment by josephwright** [comment]
Please report against https://github.com/josephwright/beamer/ (transfer is not possible here as the repo owner is different).

**Comment by dbitouze** [comment]
>If you had added \RequirePackage{latexbug} to the test file as requested then latex would have warned you that this was the wrong repository:

Sorry for that: I knew `beamer` isn't supported by LaTeX2e team but I hoped `xr`, supported by the team, could be extended to support `beamer` :)

**Comment by dbitouze** [comment]
@josephwright  Done.

**Comment by dbitouze** [comment]
@samcarter 
>you could use the `catchfilebetweentags` package to import individual frames from other documents

Unfortunately, the frames I plan to import may contain listings from the `listings` package and `catchfilebetweentags` cannot deal with verbatim material.

**Comment by FrankMittelbach** [comment]
@dbitouze that was just for the record (like the reports all labeled for sorting), as @josephwright has seen it and so not need to report again :-)
