### ISSUE TITLE
 category:amsmath Improve error message when using amsmath after breqn

### ISSUE THREAD

**Issue by Volker-Weissmann** [latex3/latex2e#209]
As documented  [here](http://mirror.physik-pool.tu-berlin.de/pub/CTAN/macros/latex/contrib/breqn/breqn.pdf), if you want to use breqn and amsmath, you have to use \usepackage{amsmath} BEFORE \usepackage{breqn} or it won't work. There is nothing wrong with this constraint, but I think the error message should be clearer: If you attempt to compile
```
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{breqn}
\usepackage{amsmath}
\begin{document}\end{document}
```
you get the error message
```
! LaTeX Error: Command \dfrac already defined.
               Or name \end... illegal, see p.192 of the manual.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
l.224 \newcommand{\dfrac}{\genfrac{}{}{}0}
```
It would be a nice improvement if \usepackage{amsmath} would check if breqn was already imported and output a "You cannot import amsmath after breqn" - Error-message.

**Comment by davidcarlisle** [comment]
I'll see if the situation can be improved, I'm moderately against one package having a fixed check assuming the capabilities of another package as these sorts if checks tend to become wrong as packages change over time. 

One way of avoiding the error would be if breqn did \RequirePackage{amsmath}
so it  was always loaded and the error couldn't happen, but that may have too many compatibility issues (@wspr ?)

**Comment by Volker-Weissmann** [comment]
You are kind of right. The most elegant way would be to make sure, that 
```
\usepackage{breqn}
\usepackage{amsmath}
```
compiles without error.

**Comment by wspr** [comment]
I would support auto-loading of amsmath. They are complements and generally one needs both — breqn can’t do everything.

**Comment by FrankMittelbach** [comment]
@wspr you are maintaining breqn these days don't you? If so I would suggest to close here and you do just that (or at least we open an issue on breqn for this. Unfortunately, issue transfer doesn't work across.

**Comment by FrankMittelbach** [comment]
open issue with breqn so close here
