### ISSUE TITLE
graphics: images disappear when keys natwidth and natheight are used  

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#21]
Currently with pdflatex and lualatex using (wrongly) the natwidth and natheight keys leads silently to blank spaces and the images are not in the pdf.  Imho it would be better if the keys are either ignored, do something sensible, or give an error. 

~~~~
\documentclass{article}
\usepackage{graphicx}

\begin{document}
\includegraphics[width=10cm,natwidth=10cm,natheight=10cm]{example-image.eps}
\includegraphics[width=10cm,natwidth=10cm,natheight=10cm]{example-image.jpg}
\includegraphics[width=10cm,natwidth=10cm,natheight=10cm]{example-image.png}
\includegraphics[width=10cm,natwidth=10cm,natheight=10cm]{example-image.pdf}
\end{document}
~~~~

**Comment by FrankMittelbach** [comment]
As this is bad behavior on wrong input I don't think it qualifies as a bug but certainly the behavior could be improved in that case (ignoring the image without warning is certainly not the most intutive kind of handling :-) )

**Comment by u-fischer** [comment]
@FrankMittelbach  @davidcarlisle  as natwidth/natheight is the same as bburx/bbury and these keys are set in pdftex.def/luatex.def to give an error, I added natwidth/natheight to the error message and mapped them to `\KV@Gin@bbllx` like bburx etc.  Would that be okay? And if yes, should I upload this directly to master, or as a new branch first? (btw: this would also affect issue https://github.com/latex3/graphics-def/issues/4).

**Comment by davidcarlisle** [comment]
@u-fischer  seems reasonable, we usually edit straight to master.

**Comment by davidcarlisle** [comment]
this was never released

**Comment by u-fischer** [comment]
This has been released now, but the version of pdftex.def and luatex.def looks wrong, it still shows begin of 2018: [2018/01/08 v1.0l Graphics/color driver for luatex] ??

**Comment by FrankMittelbach** [comment]
What is with this one @davidcarlisle ? that is from 2018 but you had it reopened.

**Comment by davidcarlisle** [comment]
This can be closed the public version already gives an error message

````
! Package pdftex.def Error: Options `bblly', `bblly', `bburx', `bbury',
(pdftex.def)                `natheight' and `natwidth' are not
(pdftex.def)                supported by pdftex driver:
(pdftex.def)                use `viewport' instead.
```

we omitted to change the filedate at that time but the version in the sources master branch has 2020/08/09 date (for the graphics viewport code change) this needs to be released before the next pre release of latex-dev
