### ISSUE TITLE
graphicx package features: why not provided by LaTeX itself?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#211]
Recently, I provided a LaTeX training to a person (from a pure literary education) who was very surprised that including a graphic with LaTeX needs a dedicated package. And that remark frequently happens with newbies who follow a LaTeX course.

After so many years of so good job and, AFAIK, with no serious competitors on the market, wouldn't be time for LaTeX to directly provide all the features of the `graphicx` package?

**Comment by davidcarlisle** [comment]
perhaps, but why just \includegraphics? latex doesn't provide \section either (you need to load some file that defines it) or all the hyperlinking features of hyperref.  So yes, if it wasn't being designed to fit in a 640K emtex msdos implementation a lot more would be in the format.

Probably at some point the format can be extended to preload a lot more, but it needs to be part of an  overall grand plan, we can't really just gradually preload existing packages one at a time.

**Comment by u-fischer** [comment]
The specific problem with graphicx (and color and hyperref) is that it needs to load code for the backend, and the backend is in some cases not known when the format is created, so not all code can be loaded in the format.

**Comment by dbitouze** [comment]
>perhaps, but why just \includegraphics?

Very good question! I didn't want to be too demanding :)

> latex doesn't provide \section either (you need to load some file that defines it)

Ah?! Wasn't aware of this. At least it is transparent for the end user.

> or all the hyperlinking features of hyperref.

Excellent suggestion! :)

>  So yes, if it wasn't being designed to fit in a 640K emtex msdos implementation a lot more would be in the format.

Damn dinosaurs!

> Probably at some point the format can be extended to preload a lot more, but it needs to be part of an overall grand plan, we can't really just gradually preload existing packages one at a time.

I see. Has the overall grand plan already been discussed?

**Comment by dbitouze** [comment]
>The specific problem with graphicx (and color and hyperref) is that it needs to load code for the backend, and the backend is in some cases not known when the format is created, so not all code can be loaded in the format.

Is it necessary for this code to be in the format by itself?

**Comment by davidcarlisle** [comment]
> Ah?! Wasn't aware of this. At least it is transparent for the end user.

the user doesn't notice `\includegraphics` isn't defined if they use `\usepackage{some package that defines it}`  and they won't notice that \section isn't defined if they use `\documentclass{some class that defines it}` 

most but not all classes define \section, but (try minimal for example)  but that is just by loose convention of package authors to start a class by copying or including article, not anything implemented or enforced by the system.

**Comment by u-fischer** [comment]
> Is it necessary for this code to be in the format by itself?

No, but when should it be loaded and how can latex know which backend code it should use? 
How can one avoid that conflicting backend settings lead to problems?

Documents currently use either `\documentclass[dvisvgm]` or `\usepackage[dvisvgm]{graphicx}` or `\PassOptionToPackage` or perhaps define some command like the pgfsys driver to declare the backend, and  all this must be coordinated somehow.

**Comment by dbitouze** [comment]
>the user doesn't notice \includegraphics isn't defined if they use \usepackage{some package that defines it} and they won't notice that \section isn't defined if they use \documentclass{some class that defines it}

Okay but using LaTeX requires `\documentclass{some class}` and, as you said, most classes define `\section`, hence most of time the `\section` command is available with no extra work for the end user. By contrast, using `\includegraphics` increases his mental load since he has to not forget to load a dedicated package or he would be bothered by a compilation error he will have to analyze.

**Comment by davidcarlisle** [comment]
I'm  going to close this, as I say there are plans to have wider plans and specifically for graphics, as Ulrike says there would have to be some syntax to allow back end specification separate from loading if graphics was pre-loaded.  Some things would be easier if we were not starting from where we are, but on the other hand starting completely afresh and keeping existing users is not easy either so these things are always a balance.

So I guess you don't really like the fact that the answer to the question in the title is "because emtex had not enough memory available to hold the graphics and amsmath packages at the same time"  but it is what it is, for the present. For the future things will probably be different but we can't say exactly how yet.
