### ISSUE TITLE
verbatim and verbatim* reversed for ltxdoc (probably doc related) 

### ISSUE THREAD

**Issue by randrej** [latex3/latex2e#213]
## Brief outline of the bug
The `verbatim` and `verbatim*` environments for `ltxdoc` class seem to be swapped: `verbatim` outputs visible spaces, while `verbatim` doesn't. 
Since `verbatim` is redefined within the `doc` package (which is included within `ltxdoc`), the problem is probably there.
When using, say, article, this issue doesn't happen (demonstrated below).

This was tested under lualatex. It's even worse in pdflatex, where both the starred and non-starred `verbatim` commands output visible spaces.

### The bug manifests when using `\documentclass{ltxdoc}`

```latex
\RequirePackage{latexbug}
\documentclass{ltxdoc}
\setlength\parindent{0pt}

\begin{document}
\section*{ltxdoc}

Regular verbatim:
\begin{verbatim}
    multiple words
\end{verbatim}

Starred verbatim:
\begin{verbatim*}
    multiple words
\end{verbatim*}
\end{document}
```
### The bug doesn't manifest when using `\documentclass{article}`
```latex
\RequirePackage{latexbug}
\documentclass{article}
\setlength\parindent{0pt}

\begin{document}
\section*{article}

Regular verbatim:
\begin{verbatim}
    multiple words
\end{verbatim}

Starred verbatim:
\begin{verbatim*}
    multiple words
\end{verbatim*}
\end{document}

```

### Log file for the buggy (`ltxdoc`) version
[ltxdoc_verb_bug.pdf](https://github.com/latex3/latex2e/files/3828796/ltxdoc_verb_bug.pdf)
[ltxdoc_verb_bug.log](https://github.com/latex3/latex2e/files/3828797/ltxdoc_verb_bug.log)

### Log file for the non-buggy (`article`) version
[article_verb_nobug.pdf](https://github.com/latex3/latex2e/files/3828798/article_verb_nobug.pdf)
[article_verb_nobug.log](https://github.com/latex3/latex2e/files/3828799/article_verb_nobug.log)

**Comment by u-fischer** [comment]
with pdflatex I get visible space in both places, that they are missing in lualatex is probably related to issue #212.

**Comment by FrankMittelbach** [comment]
@u-fischer no to a mixup of mine in #205 that nobody noticed and the test files said ok because the font restrictions we have in the test suite :-(

**Comment by randrej** [comment]
Your fix from last night (4b41051) seems to work it for me (with `lualatex`). Shall I close this?

**Comment by FrankMittelbach** [comment]
I don't think it is already available in all distributions. I close it then

**Comment by FrankMittelbach** [comment]
should be fixed and distributed by now
