### ISSUE TITLE
keeping latex-dev up to date

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#214]
I suggest always releasing latex-dev when you release latex.

Otherwise, workflows which have been adjusted to use latex-dev per your wishes (like TUGboat :) will be using old code sometimes, like now. Unless I manually switch back and forth between latex and latex-dev according to whichever is newer, which seems like what latex-dev was intended to eliminate.

wdyt? tx.

**Comment by josephwright** [comment]
Yeah, we know ... the problem is the load on CTAN, primarily ...

**Comment by kberry** [comment]
The load on CTAN does not seem more important to me than the load on
users from the version skew. They could further automate their
processing.

Alternatively, if you're knowingly not going to keep latex-dev up to
date, then at least announce it, and all us users (or you) could write a
script "newest-latex" which checks whether latex or latex-dev is the
current one and invokes accordingly. (Yuck.)

**Comment by FrankMittelbach** [comment]
It wasn't planned this way, basically we are all still learning how to handle this best, but during the next days we will push a first set of -dev files. Next main release, we should really push -dev as an identical copy, ie, you run  `pdflatex-dev`  but you will see just the new release then as if you have run `pdflatex`. Then internally we can prepare for a first real `-dev` release.

**Comment by josephwright** [comment]
There's also a version number question: it the 'matching' version 'pre-release 0'?

**Comment by FrankMittelbach** [comment]
no there there isn't, but there isn't any problem in my opinion if initially `pdflatex-dev` simply says

 LaTeX Release 2020-02-01

without mentioning any pre-release.

Then when we know that we want to release a next version, say in July and we have pre-release 1 ready that then changes to

LaTeX 2020-07-01 prerelease 1

looks like a workable approach to me.

**Comment by josephwright** [comment]
@FrankMittelbach  I'll need to subtly adjust the scripting, but that should be OK. When we do then next release, we'll have the deployment set up so actually building will be trivial. I guess we just need to convince CTAN that it will work nicely :)

**Comment by FrankMittelbach** [comment]
The decision on this should be documented as part of the wiki page on (pre)release version numbering.

**Comment by josephwright** [comment]
I've added details to the wiki (https://github.com/latex3/latex2e/wiki/Releases:-version-strings,-tagging-and-building).

**Comment by FrankMittelbach** [comment]
overall looks great, but I have some difficulties understanding the "Building a release". When I want to make a prerelease is that atomaticaly providing all required bundles automatically? what if we only want to push a new kernel-dev or only a new tools-dev to CTAN?

**Comment by josephwright** [comment]
I'll add more details

**Comment by josephwright** [comment]
I've added more detail: as we use one repo, tagging builds everything so there are always five zip files.

**Comment by FrankMittelbach** [comment]
ok thanks.
