### ISSUE TITLE
Longtable Overfull \vbox page not breaking

### ISSUE THREAD

**Issue by jsmallpbs** [latex3/latex2e#215]
## Brief outline of the bug
Depending on the amount of stuff before a longtable (same page), all the table's rows will be on the same page and give an Overfull error, rather than automatically doing a page break and putting 1 or 2 rows onto the next page.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass[12pt,letterpaper,notitlepage]{article}

  % Any preamble code goes here
\usepackage{array}
\usepackage{longtable}

\begin{document}

  % Demonstration of issue here
  \rule{2pt}{457pt}%Takes up enough space for this problem to come up

  \begin{longtable}{| m{5cm} |}
    \hline\endfirsthead
    \hline\endhead
    \hline\endfoot
    \hline\endlastfoot

    step 1\\
    step 2\\
    step 3\\
    step 4\\
    step 5\\
    final step\\
  \end{longtable}
\end{document}
```

## Log file (required) and possibly PDF file  
  
[MWE.log](https://github.com/latex3/latex2e/files/3853567/MWE.log)
[MWE.pdf](https://github.com/latex3/latex2e/files/3853568/MWE.pdf)

!! Use drag-and-drop  (remember: .log file is required) !!

**Comment by davidcarlisle** [comment]
This appears fixed in 4.14 in develop branch (and 4.15 in feature branch)
