### ISSUE TITLE
Allow spaces in filenames in \include and \includeonly

### ISSUE THREAD

**Issue by blefloch** [latex3/latex2e#217]
## Brief outline of the bug

Currently, `\include` passes the file name to `\@include`, which grabs a space-delimited file name.  This prevents file names from containing spaces.  I guess the fix might just be to change

    \set@curr@file {#1 }
    \expandafter \@include \@curr@file

to (space before `%` on purpose)

    \set@curr@file {#1}%
    \expandafter \@include \expandafter {\@curr@file } %

Of course then we also need to fix `\includeonly` not to use `\zap@space`, but there it's less clear what the most backward-compatible fix is.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{filecontents}{file.tex}
\typeout{file.tex}
\end{filecontents}
\begin{document}
\include{file name}
\end{document}
```

incorrectly loads `file.tex` and typesets `name`.

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/3854667/test.log)

**Comment by davidcarlisle** [comment]
when I looked at this a few weeks ago I came up with the following (copied here from internal mail to keep things together) I used an `\expandafter..\space` here but your `{...} %` space possibly better.
It would be nice to drop the space delimited macro here but there seem to be several ctan packages using it, so changing that might raise too many issues.

this doesn't do `\includeonly`  yet either.

```
\makeatletter

\def\include#1{\relax
  \ifnum\@auxout=\@partaux
    \@latex@error{\string\include\space cannot be nested}\@eha
  \else
  \set@curr@file{#1}%
  \expandafter\@include\expandafter\@curr@file\space% compatibility with space delimited include
  \fi}

\def\@include#1 {%
  \clearpage
  \if@filesw
    \immediate\write\@mainaux{\string\@input{#1.aux}}%
  \fi
  \@tempswatrue
  \if@partsw
    \@tempswafalse
    \edef\reserved@b{#1}%
    \@for\reserved@a:=\@partlist\do
      {\ifx\reserved@a\reserved@b\@tempswatrue\fi}%
  \fi
  \if@tempswa
    \let\@auxout\@partaux
    \if@filesw
      \immediate\openout\@partaux"#1.aux" %
      \immediate\write\@partaux{\relax}%
    \fi
    \@input@{#1.tex}%
    \clearpage
    \@writeckpt{#1}%
    \if@filesw
      \immediate\closeout\@partaux
    \fi
  \else
    \deadcycles\z@
    \@nameuse{cp@#1}%
  \fi
  \let\@auxout\@mainaux}

\documentclass{article}

\begin{document}

\include{space here/abc}

\end{document}

```

**Comment by PhelypeOleinik** [comment]
Now that LaTeX supports spaces in file names, what's missing to add this to the kernel?

**Comment by FrankMittelbach** [comment]
test time and finishing it. So not for this release, not going to do anthoer -dev version so close to next month. But feel free to start a branch gh217 and start preparing for it.
