### ISSUE TITLE
Possible oddity with \@iffileonpath and \input@path 

### ISSUE THREAD

**Issue by blefloch** [latex3/latex2e#219]
## Brief outline of the bug

In `\@iffileonpath` it's strange to use `\quote@name` when checking file existence but then use quotes when defining `\@filef@und`.  The result is different if the `\input@path` contains quotes.  I'm not sure this is a bug: my test file is not great because I don't understand whether anything should set `\input@path` normally.

## Minimal example showing the bug

The directory `some directory/` must exist for the example to work.

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{filecontents}{some directory/a.tex}
  \typeout{*** a.tex ***}
\end{filecontents}
\makeatletter
\def\input@path{{"some directory"/}}
\makeatother
\begin{document}
\typeout{*** input ***}
\input{a}
\typeout{*** InputIfFileExists ***}
\InputIfFileExists{a}{}{}
\end{document}
```
Both `\input` and `\InputIfFileExists` end up doing `\@@input""some directory"/a"`, which complains that the file `some.tex` does not exist.  To get the log file I typed `.tex` in response to both prompts, so that TeX would not complain repeatedly.

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/3854725/test.log)

**Comment by davidcarlisle** [comment]
in develop  branch it is fixed to

` \edef\@filef@und{\expandafter\quote@name\expandafter{\reserved@b#1} }%`

**Comment by blefloch** [comment]
Ah, sorry, I forgot you mentioned that.  When do we close issues?  When fixed in develop?  When distributed?

**Comment by davidcarlisle** [comment]
On Sat, 16 Nov 2019 at 21:39, Bruno Le Floch <notifications@github.com>
wrote:

> Ah, sorry, I forgot you mentioned that. When do we close issues? When
> fixed in develop? When distributed?
>

when it's gone to ctan, I think, but whether latex-dev release counts I'm
not sure, it might still be useful to keep things open if they relate to
the current stable release,  if we flag the issue that it is fixed in
development but keep it open then it's less likely people re-report it,
perhaps?

**Comment by blefloch** [comment]
Assuming you meant adding a label to issues once they're fixed in dev, I've created a new label for that.

**Comment by car222222** [comment]
@blefloch Thanks for the new label.  But yes, we maybe need some agreement on how to use labels, projects, milestones etc.
