### ISSUE TITLE
Unknown option error for defined option

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#22]
## Brief outline of the bug

When a package is loaded with a number of options, say X,Y,Z and if that package then loaded other packages there is a situation that results an error reporting that a used option (e.g., X) is claimed to be unknown.

The issue happens is by some roundabout way one of the other packages makes sure that the original has been loaded, e.g. `test2` checks that `test1` was loaded below. 

Right now that happened to me in `doc` when I load `hypdoc` in a certain situation (which itself ensures that `doc` was loaded.

By the way, the kernel uses both global and local defs for  the `\...-h@@k` macros which isn't quite right either.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\begin{filecontents}{test1.sty}
\DeclareOption{X}{\typeout{Package test1 with option X}}

\ProcessOptions*

\RequirePackage{test2}
\end{filecontents}

\begin{filecontents}{test2.sty}
\RequirePackage{test1}  % make sure test1 is loaded (no options)

\typeout{Do something}
\end{filecontents}

\documentclass{article}

\usepackage[X]{test1}

\stop

```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/1790410/test.log)

**Comment by aminophen** [comment]
I think I reported this on 2016-09-19 on LaTeX-team mailing list privately;

----
> From: Hironobu Yamashita `<h.y.acetaminophen at gmail.com>`
> Title: Strange interference of "Unknown option" error
> Date: 2016-09-16 14:05:10 JST
> To: LaTeX Team `<latex-team at latex-project.org>`

My proposal at that time is available [here](https://gist.github.com/aminophen/18f4018a9b4a9e6429e325f98197587c).

**Comment by eg9** [comment]
My opinion is that `\RequirePackage{foo}` should do nothing at all if `foo` has already been loaded (with or without options), but raise an error in case one does `\RequirePackage[<options>]{foo}` and `foo` has been loaded with contradicting options.

This is not completely foolproof, because the package `baz` doing `\RequirePackage{foo}` _might_ want `foo` with no options and we could do something in order to enforce this, something like `\RequirePackage[]{foo}` that explicitly tells LaTeX that `baz` wants `foo` with no option.

On the other hand, reporting an existent option as non-existent is surely a bug that should be fixed.

**Comment by FrankMittelbach** [comment]
> My proposal at that time is available [here](https://gist.github.com/aminophen/18f4018a9b4a9e6429e325f98197587c).

@aminophen I have finally added an implementation, somewhat different than your proposal but hopefully covering the same grounds.

**Comment by aminophen** [comment]
Thanks, but the following MWE that was fine will give an error.

``` tex
\begin{filecontents}{test0.sty}
\DeclareOption{FOO}{\PassOptionsToPackage{FOO}{test1}}
\ProcessOptions\relax
\AtEndOfPackage{\RequirePackage{test1}}
\end{filecontents}

\begin{filecontents}{test1.sty}
\DeclareOption{FOO}{\typeout{*** FOO OPTION ***}}
\ProcessOptions\relax
\end{filecontents}

\documentclass{article}
\usepackage[FOO]{test0}

\stop
```

```
! LaTeX Error: Unknown option `FOO' for package `test1'.
```

**Comment by FrankMittelbach** [comment]
@aminophen you are of course right and I just exchanged one error for annother. So I now followed your suggestion to keep the data on a per package basis as I should have in the first place. But took me a long time to understand why that approach broke the rollback :-( initially. Hope it is now correct.
