### ISSUE TITLE
Spaces in filenames in ltclass

### ISSUE THREAD

**Issue by blefloch** [latex3/latex2e#220]
## Brief outline of the bug

In `base/ltclass.dtx`, `\filec@ntents` could simply do `\edef\q@curr@file{"\@curr@file"}`
without using the slower `\quote@name` since `\set@curr@file` already removes all quotes.  On the other hand, `\immediate\openout\reserved@c#1\relax` in one of the conditional branches of `\filec@ntents` should presumably use `\q@curr@file` like the other branch.

Unfortunately I don't quite understand the various nestings of conditionals in `\filec@ntents` so I don't have a test file, sorry.

**Comment by FrankMittelbach** [comment]
Can you have a look at some point @davidcarlisle ?

**Comment by JohannesBraams** [comment]
Created a testfile and applied change
