### ISSUE TITLE
Allow spaces in filenames in docstrip.tex

### ISSUE THREAD

**Issue by blefloch** [latex3/latex2e#221]
## Brief outline of the bug

In some cases, `docstrip.tex` does not support spaces in generated file names.

## Minimal example showing the bug

```latex
%<*driver>
\RequirePackage{latexbug}
\documentclass{article}
\input docstrip.tex
\askforoverwritefalse
\generate{ \file{lorem ipsum.tex} { \from{\jobname.tex} {lips} } }
\stop
%</driver>
%<lips>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
```
This generates `lorem.tex` (rather than `lorem ipsum.tex`), with the docstrip preamble and postamble stating ```This is file \`lorem ipsum.tex'```, and the rest of the file name (namely `ipsum.tex`) is typeset, with the usual error about a missing begin document.  Strangely, adding `\begin{document}` before `\generate{...}` makes `docstrip` generate the correct file.

This problem might be due to `\@pathname` not being properly quoted.

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/3854775/test.log)

**Comment by JohannesBraams** [comment]
I've been looking at the code, the names of output files are turned into control sequences that point to an output stream. So in the example given we end up with " \openout \lorem ipsum.tex" and eventually with "\openout0 = `./lorem.tex'" ...
