### ISSUE TITLE
unambiguous file start/end in log [wishlist]

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#226]
This is probably crazy, but I wondered about having LaTeX's \input, or really \@@input, I guess, output lines in the log about starting and ending a file, so there is a feasible way to associate the line numbers TeX outputs for overfull box messages, etc., with filenames. That is, I just can't consider counting proper parentheses as "feasible" :).

I mean, something like this:
^^JStart reading file: {./foobar}^^J
^^JEnd reading file: {./foobar}^^J
(\Maybe with some better identification prefix, but you get the idea.)

Or maybe it would be better done at the engine level. Clearly that would be more basic, but also more "intrusive" in some way.

But either way, do you think it's at all reasonable? Do you think the extra log lines could cause problems, or just be useless? I know nothing that tries to be portable through old TeX versions could rely on them, but they could be used if present, especially in ancillary scripts where perfect robustness isn't an issue.

I wanted this when faced with a zillion underfull/overfull hbox messages and a complicated document with dozens of source files. Painful to figure out the right file that needs to be fixed.

I seem to recall peb telling me there was no good way to include filenames in the *erfull box lines (or other errors that don't follow the filename:lineno: marking with -file-line-error), or to have a primitive to report the current input file, and I just haven't pursued it. Sigh.

Thanks for any feedback/ideas ...

**Comment by FrankMittelbach** [comment]
One has to realize I guess that this may change the behavior of  in certain situations and there would be a write on both ends. Not that I suggest it is a good idea to habe X at the end of a file interact with something following or S before a file interact with the content but the write would certainly stop that, e.g. \ignorespaces for X would never go beyond the file.  Just a passing thought though.

So in some sense this would be much better placed inside the engine level implementation of the primitive (cf @PhelypeOleinik ) but that would then need to go in all engines so, probably not really a workable idea.

**Comment by PhelypeOleinik** [comment]
It's a pretty easy change at the engine level, and changing directly to `tex.ch` makes it
affect all engines, so the implementation is not the problem.

Though this would wreak havoc in tests against the `.log` file...

**Comment by u-fischer** [comment]
Well I think making log-files here more readable would be very nice. It is quite often really a pain to identify the current file. 

With luatex it can be quite easily done by changing the two relevant callbacks. So one could experiment here a bit without the need to adapt the engine directly.

**Comment by FrankMittelbach** [comment]
> Though this would wreak havoc in tests against the `.log` file...

only if unconditionally be done, ie not if there is an option or switch to decide classic or modern log. furthermore  even if that would be only a onetime pain for a few people and if your test suite is in a good state, ie no errors you just change to the new version and regenerate all tests and are done. Of course checking 600+ test diffs manually takes a few hours if that is necessary but that happened to me before and even that is doable albeit somewhat painful

**Comment by FrankMittelbach** [comment]
In other words @kberry , if you are open to an engine approach (and your initial issue text indicates that) then I would suggest to consider that direction as it seems to be to me the less intrusive approach especially if there is a config possibility to switch it on or off. The importance is that it then doesn't have any effects on the processing level whatsoever.

that is to say, except for application that parse the log (like the test suite) which is why I think some switch is not a bad idea. And again, here the engine approach is superior because it is then configurable from the outside, while a LaTeX solution even if it works would be part of the document source to which an external reader of the log usually has no control over.

**Comment by kberry** [comment]
I like doing it at the engine level. I guess we could have \(pdf)logfilenamemarkers or some such horrible name to turn it on/off. On by default. do you think? Or off? I guess off would be safer for the first year, anyway.

I'll discuss details further with Phelype offline. Thanks.

**Comment by FrankMittelbach** [comment]
Has any such discussion taken place @kberry @PhelypeOleinik ?

**Comment by wspr** [comment]
Am I missing something as to why this couldn’t be provided with new hooks around the places where \@@input is being used? I guess there is an issue of expansion in the general case?

**Comment by PhelypeOleinik** [comment]
@FrankMittelbach yes, we discussed this and I have some draft (not quite working) implementation, but hadn't had the time to finish it yet (and my computer's in a box right now :-).
