### ISSUE TITLE
Wrong behavior of `\dimexpr` and `\glueexpr` 

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#227]
## Brief outline of the bug
Using `\dimexpr` as well as `\glueexpr` does not always lead to the expected result. I actually thought, wrapping `\dimexpr...\relax` around a statement containing glue will gobble that but in fact it does not. Or is this a misunderstanding on my part?

Currently, it is kind of tricky to deal with length expressions assigning it to a `\skip` or `\dimen` register as you have to enclose it _every time_ in the appropriate `\glueexpr` and or `\dimexpr` to get the desired result.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{calc}
\begin{document}
\makeatletter
\setlength\@tempskipa{5pt plus 2pt minus 1pt}
result: \the\@tempskipa\quad(fine)

\setlength\@tempdima{5pt plus 2pt minus 1pt}
result: \the\@tempdima\quad(without package calc, glue is outputted!)

\bigskip

\setlength\@tempskipa{\dimexpr 5pt plus 2pt minus 1pt\relax}
result: \the\@tempskipa\quad(should be 5pt)

\setlength\@tempdima{\dimexpr 5pt plus 2pt minus 1pt\relax}
result: \the\@tempdima\quad(without package calc, glue is outputted!)

\bigskip

\setlength\@tempskipa{\glueexpr 5pt plus 2pt minus 1pt\relax}
result: \the\@tempskipa\quad(fine)

\setlength\@tempdima{\glueexpr 5pt plus 2pt minus 1pt\relax}
result: \the\@tempdima\quad(fine)

\bigskip

\setlength\@tempskipa{\glueexpr\dimexpr 5pt plus 2pt minus 1pt\relax\relax}
result: \the\@tempskipa\quad(should be 5pt)

\setlength\@tempdima{\glueexpr\dimexpr 5pt plus 2pt minus 1pt\relax\relax}
result: \the\@tempdima\quad(fine)

\bigskip

\setlength\@tempskipa{\dimexpr\glueexpr 5pt plus 2pt minus 1pt\relax\relax}
result: \the\@tempskipa\quad(fine)

\setlength\@tempdima{\dimexpr\glueexpr 5pt plus 2pt minus 1pt\relax\relax}
result: \the\@tempdima\quad(fine)
  
\end{document}
```

## Log file (required) and possibly PDF file  

[test.pdf](https://github.com/latex3/latex2e/files/3891397/test.pdf)
[test.log](https://github.com/latex3/latex2e/files/3891398/test.log)

**Comment by davidcarlisle** [comment]
Note that the LaTeX project isn't responsible for the behaviour of the primitives such as `\glueexpr` although partly this is concerns `\setlength`.

Both `\setlength` and `\dimexpr` follow the classic tex tradition of only reading as far as necessary  a `\dimexpr` does not allow plus or minus components so at the primitive level

`\@tempskipa=\dimexpr 5pt plus 2pt minus 1pt\relax`

the dimexpr stops at the p so assigns 5pt and then typesets `plus 2pt minus 1pt`

essentially all your cases are similar to this.

At the TeX primitive level that is just how it is. Arguably `\setlength` could trap if there are remaining tokens left after the assignment, but currently it doesn't, and there mat be compatibility issues with changing it.

**Comment by u-fischer** [comment]
> Both `\setlength` and `\dimexpr` follow the classic tex tradition of only reading as far as necessary a `\dimexpr` does not allow plus or minus components so at the primitive level
> 
> `\@tempskipa=\dimexpr 5pt plus 2pt minus 1pt\relax`

\dimexpr doesn't cut the stretch and glue part:

~~~~
\@tempskipa=\dimexpr 5pt plus 2pt minus 1pt\relax
\showthe\@tempskipa
~~~~

gives

~~~~
> 5.0pt plus 2.0pt minus 1.0pt.
l.251 \showthe\@tempskipa
~~~~

The glue and stretch is only removed if you assign to a dimen.

**Comment by mrpiggi** [comment]
> The glue and stretch is only removed if you assign to a dimen.

Only, if package `calc` is loaded.

Maybe, it would be sufficient, to have the two new macros `\setlengthguarded` and `\addtolengthguarded` tow overcome this issue and to preveent compatibility issues.

**Comment by davidcarlisle** [comment]
I edited my original answer which mixed two cases. `\dimexpr` does stop at the `p`  it is tehn picked up again at the skip assignment

`\@tempskipa=\dimexpr 5pt plus 2pt minus 1pt\relax`

is

`\@tempskipa=\dimexpr 5pt\relax plus 2pt minus 1pt\relax`

so the `\dimexpr` is just 5pt but the skip register assignment included the plus and minus components.

I don't think there is a latex issue here. The behaviour or `calc` package is a little different but that predates eTeX and has a different syntax for infix expressions so some differences are inevitable.

**Comment by FrankMittelbach** [comment]
> Maybe, it would be sufficient, to have the two new macros `\setlengthguarded` and `\addtolengthguarded` or something like this to overcome this issue and prevent compatibility issues.

Guard against what? User error?

I'm not a fan of adding ad-hoc extra commands that aren't really fitting into the overall design and I would say this is the case here. If you stick to the LaTeX level then `\newlength` will always allocate a skip for you. Neither `\glueexpr` nor `\dimexpr` are LaTeX user-level commands and if used by a package author, then it doesn't seem unreasonable to assume that he or she is not using them in the wrong place. The problem in your sample comes from assuming that `\dimexpr` drops the glue part while in reality it simply never reads it, i.e., the syntax is not that it reads until it reaches a `\relax`the syntax is that it reads until it is no longer part of a dimen and drops a `\relax`if that was signaling the end of the dimen.

**Comment by u-fischer** [comment]
> I edited my original answer which mixed two cases. `\dimexpr` does stop at the `p` it is then picked up again at the skip assignment

Oh, you are right. There is a difference between `\@tempdima = \dimexpr 5pt + 4pt  plus 2pt minus 1pt  \relax` and `\@tempdima = \dimexpr 5pt plus 2pt minus 1pt  +4pt \relax` . It happens so rarely that one has such an explizit skip somewhere that I never thought about it.

**Comment by mrpiggi** [comment]
@FrankMittelbach My initial thought was to expose a length to an user interface. As this length must not hold any glue, I thought to implement it as a `\dimen`. Setting this length on user-level, only `\setlength` is usable. And if some user just tries to set some glue, although it isn't supported, this ends up in the output wherever `\setlength` was used.
```tex
\newdimen\userlength
\setlength\userlength{5pt plus 3pt minus 2pt}
```
So I do have to use `\newlength\userlength` and wrap `\dimexpr\userlength\relax` everywhere in the source. I can deal with it, although it is not that comfortable.

**Comment by davidcarlisle** [comment]
@mrpiggi  better to make the user length a skip, then if you use that somewhere that has to be a dimen the components just get dropped `\wd0=\userlength`  or whatever. If there are some places where you need to drop the length by hand you could assign it to a dimen first or use the classic tex expression `1\userlength` or as you say, the etex `\dimexpr\userlength\relax`  these all seem quite reasonable options.

**Comment by FrankMittelbach** [comment]
Am 26.11.19 um 13:04 schrieb Falk Hanisch:
> @FrankMittelbach <https://github.com/FrankMittelbach> My initial thought 
> was to expose a length to an user interface. As this length must not 
> hold any glue, I thought to implement it as a |\dimen|. Setting this 
> length on user-level, only |\setlength| is usable. And if some user just 
> tries to set some glue, although it isn't supported, this ends up in the 
> output wherever |\setlength| was used.
sure but this only properly resolved by changing \setlength to trap it 
and as David said, there are a number of good reasons why that is not 
really advisable. And this is why LaTeX for all user lengths make it 
skips so the glue is always accepted (but it doesn't do it properly for 
some of its internal dimen that can also be set via \setlength)

> So I do have to use |\newlength\userlength| and wrap 
> |\dimexpr\userlength\relax| everywhere in the source. I can deal with 
> it, although it is not that comfortable.

again \dimexpr is *not* removing the glue, what you need to do is

\internaldimen=\userlength

or simpler

\userlength=1\userlength

once after \userlength has received its value.

**Comment by davidcarlisle** [comment]
@FrankMittelbach 

> `again \dimexpr is *not* removing the glue, what you need to do is`

actually it does there as the skip register is absorbed into the dimexp so coerced to a skip, unlike the case with literal `plus and minus` which stops the scan. (but using a prefix 1 is easier:-)

**Comment by mrpiggi** [comment]
@davidcarlisle was faster, but it does if applied to a skip

> again \dimexpr is *not* removing the glue

```tex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}

\newlength\userlength
\setlength\userlength{5pt plus 3pt minus 2pt}
\the\userlength

\the\dimexpr\userlength\relax

\newlength\userlengthB
\setlength\userlengthB{\dimexpr5pt plus 3pt minus 2pt\relax}
\the\userlengthB

\setlength\userlengthB{\dimexpr\userlength\relax}
\the\userlengthB

\end{document}
```

**Comment by FrankMittelbach** [comment]
> and wrap |\dimexpr\userlength\relax| everywhere in the source.

sorry, correction, the above works too, as the glue is hidden inside the 
register and therefore read an then dropped

**Comment by davidcarlisle** [comment]
so in summary I think we close this as working as designed.

**Comment by FrankMittelbach** [comment]
Am 26.11.19 um 13:24 schrieb David Carlisle:
> actually it does there as the skip register is absorbed into the dimexp 
> so coerced to a skip, unlike the case with literal |plus and minus| 
> which stops the scan. (but using a prefix 1 is easier:-)

as you see I noticed after I send it off ... :-)

**Comment by blefloch** [comment]
This (and a comment of Frank) raises an interesting issue that

\documentclass{article}
\begin{document}
\setlength{\jot}{3pt plus 2pt}
\end{document}

typsets "plus 2pt".  (I just searched \newdimen in latex.ltx to find an
example; there are others.)

**Comment by davidcarlisle** [comment]
@blefloch  it does but it's consistent with `\setlength{\jot}{3pt wibble}` typesetting `wibble` . A  naive latex user is not supposed to know about the `plus` syntax and someone who does know about it is supposed to know where it can be used. There are lots of places where error checking in latex could be different, and would have been different if we hadn't have run out of token memory in emtex, but I don't think this is the most serious of them.

**Comment by blefloch** [comment]
Ok, I admit I don't know what naive users know.

**Comment by FrankMittelbach** [comment]
@blefloch it falls under the category, "yes LaTeX doesn't have protection against all kind of user input errors" in my opinion, just like `\footnote{\section*{...}}`. 

In the case of `\setlength` making that test its input will most certainly break a lot which is worse then keeping a behavior that has well worked for 30+ years.

**Comment by davidcarlisle** [comment]
Closing as this is the tex primitive behaviour.
