### ISSUE TITLE
longtable: tail can not be made dependant on rows

### ISSUE THREAD

**Issue by jotbeel** [latex3/latex2e#232]
## Brief outline of the bug
A longtable row changes a counter, the following tail does not see the change.
Note that e.g., the supertabular package behaves as expected.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here
\usepackage{longtable}
\begin{document}

  % Demonstration of issue here
\newcounter{total}

\begin{longtable}[l]{r}
	Total: \thetotal
	\endfoot

	1\addtocounter{total}{1}\\

\end{longtable} 
\end{document}
[MWE.log](https://github.com/latex3/latex2e/files/3908865/MWE.log)
[MWE.pdf](https://github.com/latex3/latex2e/files/3908866/MWE.pdf)

```

## Log file (required) and possibly PDF file  

!! Use drag-and-drop  (remember: .log file is required) !!

**Comment by davidcarlisle** [comment]
This is as designed (even if it is perhaps not the best feature of the package) the head ad foot are set in boxes, so constant throughout a table. Changing that in a reliable way would require essentially rewriting the package so while that may happen it isn't a quick fix, sorry.

https://tex.stackexchange.com/questions/151380/how-to-print-subtotals-in-each-page-of-a-long-table/157193#157193

has some related code that could possibly be used, or the `supertab` and related packages support changing the head and foot by default (but lack some other features of `longtable`)

**Comment by jotbeel** [comment]
David,

thank you very much for replying so quickly, very much appreciated! Pity
though that longtable being such a useful tool does not have that feature.
supertabular has shortcomings which render it unusable for my task.
More thanks for pointing me to the ...subtotals... code - was searching
tex.stackexchanges without luck :-(  That's the way I'll go.

Finally: I am a newcomer to LaTeX bug reporting, so please advise if I
should do anything to close the case.

pon., 2 gru 2019 o 00:41 David Carlisle <notifications@github.com>
napisał(a):

**Comment by jotbeel** [comment]
I hope the rewrite will happen :-)

**Comment by car222222** [comment]
How long can you hold your breath :-) ??

**Comment by jotbeel** [comment]
As needed, but not longer ;-) I gather that you are not above taking this up... 

Should I/whoever reopen as a feature request? Seems essential, especially that longtable is LaTeX's core package..

**Comment by davidcarlisle** [comment]
@jotbeel  It's logged an a possible V5 extension  already

http://htmlpreview.github.io/?https://raw.githubusercontent.com/davidcarlisle/dpctex/master/longtable/ltbugs.html

(see "variable header material")

But the list of things to do is rather long.....

**Comment by car222222** [comment]
>: longtable is LaTeX's core package..

We shall log that opinion of its importance!
