### ISSUE TITLE
Name of the amsmath's user-level documentation

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#233]
CTAN recommends that the packages and their user-level documentations share the same name. Currently, the `amsmath`'s:
- user-level documentation is named `amsldoc`,
- code documentation is named `amsmath`.

It would be nice for its user-level documentation to be named `amsmath`.

**Comment by FrankMittelbach** [comment]
Thanks for the suggestion. 

While I agree with the general concept and am quite interested in standardization, I think it would be a bad idea to do this at this stage for something as major as `amsmath`. Its documentation is referred to in probably thousands of documents,  help manuals, etc. and changing its name without a good reason (like the production of a major release) is only going to generate confusion, broken links and at best a quite substantial amount of work for many people. So I don't think we are going to make any such change at this point in time.

**Comment by dbitouze** [comment]
@FrankMittelbach Wouldn't it be possible to rename the code documentation to `amsmath-doc` and, as an exception, make `amsmath.pdf` and `amsldoc.pdf` be the same document (kind of symlinks)?

**Comment by FrankMittelbach** [comment]
a lot is possible, sure but symlinks etc, have their own problems across platforms. Anyway from a user perspective best practice for documentation is anyway `texdoc <package name>` and that gives you the document if you go `texdoc amsmath`.

**Comment by davidcarlisle** [comment]
There is a second user documentation for `amsmath`  The short math Guide

`texdoc shortmathguide`

https://ctan.org/pkg/short-math-guide?lang=en

This was originally written by Michael Downes, but updated by Barbara Beeton and adopted by the AMS after his death.

This just came up in one of Barbara's answers on tex.sx, and she has just obtained agreement from the AMS that we could incorporate this into the amsmath distribution, which I think would be a good thing to make sure the documentation keeps in sync with any package updates.

**Comment by FrankMittelbach** [comment]
then I guess we should add this to the sources so that it is available starting next release from here. Needs coordination with David Jones though I guess that they take it off their distribution.

**Comment by FrankMittelbach** [comment]
@davidcarlisle since you know what Barbara has arranged in detail, can you take that one on and integrate it into the distribution including that it isn't distributed from two ends?

as to changing the names or adding symlinks adding the pdfs al times under difsferent names, I think neither approach is good and will add more confusion than help (symlinks would be kind of  ok, but that is something that couldn't be done from our end and getting it done in *all* TeX distributions for different platform ...) 

So I think the best answer is use `texdoc` to query for documentation

**Comment by davidcarlisle** [comment]
Decided to leave short-math-guide at AMS for now, may request moving later if we have any need for updates.

**Comment by dbitouze** [comment]
> Decided to leave short-math-guide at AMS for now, may request moving later if we have any need for updates.

Too bad! Will you remember to move later? :wink:
