### ISSUE TITLE
luatex can't input files without extensions

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#236]
## Brief outline of the bug

with lualatex(-dev) files without extension can not be input when \openin is involved (the primitive `\@@input` works).

See also https://tex.stackexchange.com/a/511688/2388

I tested also with the newest experimental luahbtex engine. 

## Minimal example showing the bug

```latex
\begin{filecontents}{noextension.} %works on windows, no idea about other OS
blub
\end{filecontents}
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
\makeatletter
\@@input noextension\relax
\input{noextension}
\end{document}

```
gives the error 

      ! LaTeX Error: File `noextension.tex' not found.

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/3933106/test-utf8.log)

**Comment by josephwright** [comment]
Er, isn't this 'report-elsewhere'?

**Comment by FrankMittelbach** [comment]
Maybe, but it affects the interface we provide, so we might want to track it? Maybe only documenting that it doesn't work if it is a luatex design question.

**Comment by zauguin** [comment]
> Er, isn't this 'report-elsewhere'?

Actually this is 'fixed-elsewhere' by now. It works with LuaTeX experimental. We could document that this only works starting with LuaTeX 1.12 (TeXLive 2020), but given that there will be a TeXLive update soon we can probably just close it.

**Comment by u-fischer** [comment]
I haven't yet got an experimental luatex binary with the fix to test. But the main question is if we need a work around for older luatex or not.

**Comment by FrankMittelbach** [comment]
I would say no. It is a bug (so the workaround for older luatex's is to use a file with extension :-) ) if it is fixed that soon I would just leave it as that.

**Comment by u-fischer** [comment]
I just tested with the newest experimental 1.12. version (id 7283) and it works fine. So I think we can close it, it will be solved in texlive 2020.
