### ISSUE TITLE
hhline: support "blanks in argument

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#242]
## Brief outline of the bug

Specifying rule segments in hhline needs different number of characters depending on the type of rule segment. This makes it rather difficult to define them correctly, so allowing blanks between them would be a great help.

The first tabular works (no blanks), the second where you can actually see what is used where dies with
```
Runaway argument?
! Forbidden control sequence found while scanning use of \next.
```
It seems to hit `\endtemplate`. Removing the last space before the `}` avoids the error but the output is rubbish (probably because of the other blanks)

If it weren't for the error above I would have labeled it "enhancement" but so I think it qualifies as bug :-)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!

\documentclass{article}
\pagestyle{empty}
\usepackage{hhline}  \setlength\arrayrulewidth{.8pt}
\renewcommand\arraystretch{1.5}

\begin{document}
                                 % cols:    1 2     3 4      5
\begin{tabular}{||cc||c|c||c}   \hhline{|t:==:t:== :t|}
 a & b & c & d               \\ \hhline{|:==:|~|~||}
 1 & 2 & 3 & 4               \\ \hhline{#==#~|=:b|-}
 i & j & k & l
   & \multicolumn{1}{c|}{?}  \\ \hhline{||--||---}
 w & x & y & z               \\ \hhline{|b:==:b:==:b|}
\end{tabular}

\iftrue

                                 % cols:    1 2     3 4      5
\begin{tabular}{||cc||c|c||c}   \hhline{|t: = = :t: = =  :t|  }
 a & b & c & d               \\ \hhline{|:  = = :|  ~|~  | |  }
 1 & 2 & 3 & 4               \\ \hhline{ #  = =  #  ~|=  :b| -}
 i & j & k & l
   & \multicolumn{1}{c|}{?}  \\ \hhline{||  - - ||  - -      -}
 w & x & y & z               \\ \hhline{|b: = = :b: = =  :b|  }
\end{tabular}

\fi

\end{document}
```

## Log file (required) and possibly PDF file  

[1-7-3.log](https://github.com/latex3/latex2e/files/4006476/1-7-3.log)

**Comment by FrankMittelbach** [comment]
Actually, the output of the top right corner also looks a bit suspicous.

**Comment by davidcarlisle** [comment]
Not sure what you mean by the corner? I get

![image](https://user-images.githubusercontent.com/1268738/71550316-60f22700-29c5-11ea-9a4f-c5d78959602c.png)

after adding a line (`% NEW`) to ignore space tokens
```

\documentclass{article}
\pagestyle{empty}
\usepackage{hhline}  \setlength\arrayrulewidth{.8pt}
\renewcommand\arraystretch{1.5}
\makeatletter

\def\HH@loop{%
  \ifx\@tempb`\def\next##1{\the\toks@\cr}\else\let\next\HH@let
  \ifx\@tempb|\if@tempswa\HH@add{\hskip\doublerulesep}\fi\@tempswatrue
          \HH@add{\@tempc\vline\@tempc}\else
  \ifx\@tempb:\if@tempswa\HH@add{\hskip\doublerulesep}\fi\@tempswatrue
      \HH@add{\@tempc\HH@box\arrayrulewidth\arrayrulewidth\@tempc}\else
  \ifx\@tempb##\if@tempswa\HH@add{\hskip\doublerulesep}\fi\@tempswatrue
         \HH@add{\@tempc\vline\@tempc\copy\@ne\@tempc\vline\@tempc}\else
  \ifx\@tempb~\@tempswafalse
           \if@firstamp\@firstampfalse\else\HH@add{&\omit}\fi
              \HH@add{\hfil}\else
  \ifx\@tempb-\@tempswafalse
           \if@firstamp\@firstampfalse\else\HH@add{&\omit}\fi
              \HH@add{\leaders\hrule\@height\arrayrulewidth\hfil}\else
  \ifx\@tempb=\@tempswafalse
       \if@firstamp\@firstampfalse\else\HH@add{&\omit}\fi
       \HH@add
          {\rlap{\copy\@ne}\leaders\copy\@ne\hfil\llap{\copy\@ne}}\else
  \ifx\@tempb t\HH@add{\rlap{\HH@box\doublerulesep\z@}}\else
  \ifx\@tempb b\HH@add{\rlap{\HH@box\z@\doublerulesep}}\else
  \ifx\@tempb\@sptoken\let\next\HH@spacelet\else   % NEW
  \PackageWarning{hhline}%
      {\meaning\@tempb\space ignored in \noexpand\hhline argument%
       \MessageBreak}%
  \fi\fi\fi\fi\fi\fi\fi\fi\fi\fi
  \next}

\lowercase{\def\HH@spacelet} {\futurelet\@tempb \HH@loop}  % NEW
\makeatother


\begin{document}


% cols:    1 2     3 4      5
\begin{tabular}{||cc||c|c||c}   \hhline{|t:==:t:== :t|}
 a & b & c & d               \\ \hhline{|:==:|~|~||}
 1 & 2 & 3 & 4               \\ \hhline{#==#~|=:b|-}
 i & j & k & l
   & \multicolumn{1}{c|}{?}  \\ \hhline{||--||---}
 w & x & y & z               \\ \hhline{|b:==:b:==:b|}
\end{tabular}

\iftrue

                                 % cols:    1 2     3 4      5
\begin{tabular}{||cc||c|c||c}   \hhline{|t: = = :t: = =  :t|  }
 a & b & c & d               \\ \hhline{|:  = = :|  ~|~  | |  }
 1 & 2 & 3 & 4               \\ \hhline{ #  = =  #  ~|=  :b| -}
 i & j & k & l
   & \multicolumn{1}{c|}{?}  \\ \hhline{||  - - ||  - -      -}
 w & x & y & z               \\ \hhline{|b: = = :b: = =  :b|  }
\end{tabular}

\fi

\end{document}
```

**Comment by u-fischer** [comment]
The corner here looks wrong:

![image](https://user-images.githubusercontent.com/4047173/71550342-7fa8eb80-29ce-11ea-866f-ea6021a94743.png)

**Comment by davidcarlisle** [comment]
@Ulrike Fischer <fischer@troubleshooting-tex.de>  oh the ? bit not the top
row of the table. I only looked were I was told:-)

for the bottom right of the ? you  need

` & \multicolumn{1}{c|}{?}  \\ \hhline{||  - - ||  - -      -|}`

with a final `|`  for the top right you need

` & \multicolumn{1}{c|}{?}  \\ \hhline{||  - - ||  - -      -:}`

excerpt with just the bottom half of a `:`  sort of like `b` but not
currently available 9`b` is too wide)...

or @Frank Mittelbach <frank.mittelbach@latex-project.org>  could use the
`array` package which gets rid of the negative spacing around vertical
rules.

**Comment by FrankMittelbach** [comment]
@davidcarlisle I assume that "enhancement" will come? At least I added it to the Feb release cycle

**Comment by FrankMittelbach** [comment]
hmm, my top right corner looks different  not the one next to the ? (when I run it as a TLC3 example) have to check why then.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  space skipping I could add now (or at least tomorrow when I'm awake) not sure if I should add top and bottom rule fragments though, would need to think of two more characters.

TLC3 will be using array won't it? the rule spacing is different there

Whatever changes I do here I need to port to colortbl (which replicates almost all the package)

**Comment by u-fischer** [comment]
@FrankMittelbach  the top right in your first example looks wrong as you had a space there too (and you got a warning from hhline). With David's new code it is fine too.

**Comment by FrankMittelbach** [comment]
Am 29.12.19 um 01:08 schrieb Ulrike Fischer:
> @FrankMittelbach <https://github.com/FrankMittelbach> the top right in 
> your first example looks wrong as you had a space there too (and you got 
> a warning from hhline). With David's new code it is fine too.

ah, that explains it, so yes please add the two lines to ignore spaces 
David, once you are awake (and port it to colortbl as I think spaces 
should be support in such arguments)

**Comment by FrankMittelbach** [comment]
guess that should be documented in ltnews31 - I  made a dummy entry
