### ISSUE TITLE
change \baselineskip in \textsuperscript

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#249]
## Brief outline of the bug

\textsuperscript sets \baselineskip to 0pt:

~~~~
\def\@textsuperscript#1{%
 {\m@th\ensuremath{^{\mbox{\fontsize\sf@size\z@#1}}}}}
~~~~

hyperref uses in some cases the current baselineskip and so you get a
too small link area on the latex+dvips route in superscripts:
https://github.com/latex3/hyperref/issues/115

Instead of `\z@` `\sf@size` or perhaps even `\sf@size` * 1.2 should be used.

**Comment by FrankMittelbach** [comment]
`\sf@size` and friends are macros and one can't write `1.2\sf@size` so my proposal is to either use `\sf@size` or `\f@size` for the baselineskip. I tend to think the former is best.

**Comment by wspr** [comment]
I had a small concern this might lead to funny interactions with superscript placement, but I think that would only happen if there were subscripts as well, which can’t happen for \textsuperscript. So I think I agree changing the baselineskip is safe, and \sf@size makes sense.

**Comment by u-fischer** [comment]
You could use \dimexpr to handle the 1.2\sf@size, but the smaller value (last) looks imho quite good:

![image](https://user-images.githubusercontent.com/4047173/78872650-e6b45280-7a49-11ea-8f15-1b7f9ce015b8.png)

**Comment by FrankMittelbach** [comment]
yeah I could, but it is complicating things and I have to account for it being with or without a dimension etc. Furthermore you don't what the box become too high to not open up the line so I think just using `\sf@size` is best.

**Comment by FrankMittelbach** [comment]
Am 09.04.20 um 09:52 schrieb Will Robertson:
> I had a small concern this might lead to funny interactions with 
> superscript placement, but I think that would only happen if there were 
> subscripts as well, which can’t happen for \textsuperscript. So I think 
> I agree changing the baselineskip is safe, and \sf@size makes sense.

as you say it can't really happen, but anyway as long as we use \sf@size 
for the baselineskip the box wouldn't get (much) higher than its content 
anyway and not at all if large characters such a parentheses are part of 
the text

**Comment by u-fischer** [comment]
The baselineskip doesn't change the height, you can put 50pt there. (At least in all normal cases, if there is a tabular in the argument, and a \selectfont then it would be picked up, but in this cases a sensible baselineskip shouldn't harm).

**Comment by FrankMittelbach** [comment]
Ok so hyperref hides the height, but it uses it so if we smaller enlargements, e.g. 9pt baseline you bump with the box into preceding text using your example in the original issue, e.g.

<img width="532" alt="Screenshot 2020-04-09 at 11 40 26" src="https://user-images.githubusercontent.com/1062981/78881373-02722580-7a57-11ea-9a99-bf1569129579.png">

so I think staying with `\sf@size`is correct.

**Comment by u-fischer** [comment]
No hyperref doesn't hide the height. The height of an \mbox doesn't change if you only change the baselineskip. 

~~~~
\documentclass{article}
\begin{document}

\fbox{\mbox{\fontsize{10pt}{50pt}\selectfont T}}

\fbox{\mbox{\fontsize{10pt}{50pt} \strut T}}

\fbox{\mbox{\fontsize{10pt}{50pt}\selectfont \strut T}}

\end{document}
~~~

> so I think staying with \sf@size is correct.

Yes I agree that this is a good value.

**Comment by FrankMittelbach** [comment]
What I meant is that hyperref makes a box with borders but in a way that its height/placement (of the borders ) is hidden. If it would have been a normal \fbox like thing it would have pushed things apart. So hyperref does hide the fact that it places something 50pts above the baseline, does it not?  Not that it matters what we call the behavior ... seems we have caught a virus here :-)

**Comment by u-fischer** [comment]
> What I meant is that hyperref makes a box with borders but in a way that its height/placement (of the borders ) is hidden.

Ah. No, there is nothing "hidden". hyperref simply writes out the baselineskip in a \special, so that dvips/ghostscript can use it to calculate the height of the link box:

~~~~
\def\hyper@linkend{%
  \literalps@out{\strip@pt@and@otherjunk\baselineskip\space H.L}%
~~~~

**Comment by car222222** [comment]
Mane Frank means that it is "hidden" from TeX’s layout machines.

**Comment by FrankMittelbach** [comment]
hiding it by writing directly into the PS layer then, but I agree hyperref does y openly most likely :-)
