### ISSUE TITLE
Error: \bigl + delimiter inside \protected@edef

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#251]
## Brief outline of the bug

LaTeX2e 2019-10-01 breaks using `\bigl` and co with delimiters inside `\protected@edef`.  Now it causes an error

```
! Missing delimiter (. inserted).
```

## Minimal example showing the bug

The following code worked fine on "real" format as of 2018-12-01, but no longer works on format as of 2019-10-01 or later.  Please also note that the `\RequirePackage[2018-12-01]{latexrelease}` cannot solve the problem.

```latex
\RequirePackage{latexbug}
% LaTeX2e 2018-12-01: OK
% LaTeX2e 2019-10-01: NG
\documentclass{article}
\begin{document}

\makeatletter
\def\X{\bigl\{ a \bigr\}}
\protected@edef\Y{\X}
\makeatother

$\X$ % => no error
$\Y$ % => ! Missing delimiter (. inserted).

\end{document}
```

## Log file (required) and possibly PDF file  

- [20200119-delim.log](https://github.com/latex3/latex2e/files/4086056/20200119-delim.log)

## Suggestion

The error appeared when `\bigl` and co. were made robust, but I think this error can be avoided by defining the delimiters as engine-protected, say

```
\protected\long\def\{{\ifmmode \lbrace \else \textbraceleft \fi}
```

instead of

```
\DeclareRobustCommand\{{\ifmmode \lbrace \else \textbraceleft \fi}
```

**Comment by FrankMittelbach** [comment]
thanks for reporting, guess you are right and the best is to use engine protection.

**Comment by FrankMittelbach** [comment]
hmm, that easy fixed turned out to require 2 dozen files to change (the other delimiters had the same issue and the change showed that there was a hidden issue in amsmath)
