### ISSUE TITLE
Normalize interfaces for tuenc.def

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#253]
## Brief outline of the bug

The interfaces  (defined and used) used in tuenc.def have been developed over time and are rather inconsistent. Some declarations require an encoding name (always TU or rather `\UnicodeEncodingName`) while others like `\DeclareUnicodeComposite` don't. This kind of inconsistency should be cleaned up.

Given that there is only a single encoding for Unicode we should always drop the encoding argument.

This is a cleanup exercise on the way to better align with fontspec etc.

**Comment by FrankMittelbach** [comment]
To make that interface more consistent I'm contemplating to add
```
\DeclareUnicodeSymbol#1#2   ->  \DeclareTextSymbol  {#1}\UnicodeEncodingName{#2}
\DeclareUnicodeCommand#1#2  ->  \DeclareTextcommand {#1}\UnicodeEncodingName{#2}
```
then the encoding is always implicit.

**Comment by davidcarlisle** [comment]
Possibly just a documentation issue as in practice you don't want multiple TU-variant encodings but "only a single encoding for Unicode" sits a little uneasily with fontspec's facilities (in chapter V of its doc) for declaring variant encodings with for example different accent handling.

**Comment by FrankMittelbach** [comment]
Still to do is to provide `\DeclareUnicodeSymbol` and `\DeclareUnicodeCommand`for consistency.

**Comment by FrankMittelbach** [comment]
> Possibly just a documentation issue as in practice you don't want multiple TU-variant encodings but "only a single encoding for Unicode" sits a little uneasily with fontspec's facilities (in chapter V of its doc) for declaring variant encodings with for example different accent handling.

sorry @davidcarlisle , where exactly is that statement? Can't find it.

**Comment by u-fischer** [comment]
@FrankMittelbach in section "2 Adjusting a pre-existing encoding", this basically defines a new encoding.
