### ISSUE TITLE
TS1 encoding within kernel

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#255]
## Brief outline of the bug
When calling `pdflatex-dev` some text commands like `\textperthousand` newly defined by the kernel (`lttextcomp.dtx`) are overwritten, when `t1enc.def` is loaded.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\begin{document}
  \meaning\textperthousand
  
  \expandafter\meaning\csname ?\string\textperthousand\endcsname
  
  \expandafter\meaning\csname T1\string\textperthousand\endcsname
  
  \expandafter\meaning\csname TS1\string\textperthousand\endcsname

\end{document}
```

## Log file (required) and possibly PDF file  
[ts1test.log](https://github.com/latex3/latex2e/files/4108905/ts1test.log)

**Comment by FrankMittelbach** [comment]
hmm, yes. The use of \UndeclareTextCommand is rather stupid here. I should have explicitly removed the commands from the rencodings (had intended to do that but forgotten about it  by the time I integrated the code).  Also the case for a few other symbols. Thanks for spotting.
