### ISSUE TITLE
[documentation] ltfssaxes.dtx

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#259]
Header of ltfssaxes.dtx is wrong, it says `%%% From File: ltfssbas.dtx`.

https://github.com/latex3/latex2e/blob/63ef4aef8c9e073d887c663c0a8e8fc349ba3e85/base/ltfssaxes.dtx#L30

Also, source2e.tex is wrong: it reads `ltfssbas.dtx` twice.

https://github.com/latex3/latex2e/blob/63ef4aef8c9e073d887c663c0a8e8fc349ba3e85/base/doc/source2e.tex#L269

**Comment by FrankMittelbach** [comment]
thanks, I'll take care of it
