### ISSUE TITLE
textcomp.sty: \NeedsTeXFormat{LaTeX2e}[2020/02/02]

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#260]
https://github.com/latex3/latex2e/blob/d24e2339f78b70ac39ded28f689c51618d1e1b93/base/lttextcomp.dtx#L1400

It would be nice if `\NeedsTeXFormat{LaTeX2e}[2020/02/02]`is added somewhere in the almost-empty textcomp.sty; there are some cases that users fail to update the format file and use this new one...

**Comment by FrankMittelbach** [comment]
If you obtain a new LaTeX with TL or MikTeX distributions format generation is automatic. Are you telling me that for Japanse users that is not necessarily the case?

We can certainly do that but it will not show up immediately (but probably only with the next release --- I hope for a change that we don't have to do a patch release and this doesn't seem to warrant one, or does it?)

**Comment by aminophen** [comment]
Not only for Japanese, but users of BasicTeX on macOS will be affected.  Until recently (middle of October 2019) BasicTeX did not trigger format regeneration.

Ref. https://tug.org/pipermail/tex-live/2019-October/044121.html

**Comment by FrankMittelbach** [comment]
since we wil have a patch release anyway, I include this one.
