### ISSUE TITLE
\DeclareFontSeriesDefault{bf}{b} causes error

### ISSUE THREAD

**Issue by hair-splitter** [latex3/latex2e#264]
## Brief outline of the bug
\DeclareFontSeriesDefault{bf}{b} causes an error.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\DeclareFontSeriesDefault{bf}{b}
\begin{document}
\textbf{Text}  
\end{document}
```

## Log file (required) and possibly PDF file  
[document.log](https://github.com/latex3/latex2e/files/4158085/document.log)

**Comment by eg9** [comment]
A typo in `latex.ltx`.

Line 4589 has
```latex
  \ifx\@resereda\@empty
```
which should obviously be
```latex
  \ifx\@reserveda\@empty
```

**Comment by FrankMittelbach** [comment]
unbelievable but true :-( there are so many tests around that code, still ...

**Comment by aminophen** [comment]
ltfssini.dtx still has \@reservedb and \@reservedc ... (there is no actual problem, though ...)

**Comment by FrankMittelbach** [comment]
thanks. fixed in upcoming hotfix
