### ISSUE TITLE
Recent change of \usefont causes problem in package xeCJK

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#265]
## Brief outline of the bug

In https://github.com/latex3/latex2e/commit/69f67052aa0bcb8178c17bec81e96881e8057288#diff-ba08b740b88cf76da18c9c76eb8b8b15, `\usefont` was redefined to use `\edef\f@family{#2}` directly instead of `\fontfamily{#2}`.

This change invalidated the effect of patching `\fontfamily`, done by LaTeX package xeCJK, inside `\usefont`.
```tex
% in xeCJK.sty
\RenewDocumentCommand \fontfamily { m }
  {
    \tl_set:Nx \f@family {#1}
    \xeCJK@fontfamily {#1}
  }
```
And that invalidation may cause problems of "font not found" in very strict conditions. See https://github.com/CTeX-org/ctex-kit/issues/482 (in Chinese) and the following example.

Are there any reasons that latex2e really need use `\edef\f@family{}` instead of `\fontfamily` inside `\usefont`? The reason for substituting `\fontseries` and `\fontshape` are already documented as
https://github.com/latex3/latex2e/blob/57ae2b5217c1ed4da3d783854a69b6d960483f55/base/ltfssbas.dtx#L823-L830
but `\fontfamily` is not mentioned.

## Minimal example showing the bug

```latex
% compile with xelatex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[LoadFandol=false]{xeCJK}

%% case 1, cause "font not found"
% expected: "[FandolSong-Regular.otf]/OT:language=dflt;"
% current: "FandolSong-Regular.otf/OT:language=dflt;"
%\setCJKmainfont[Extension=.otf]{FandolSong-Regular}

%% case 2, cause "font not found"
% expected: "FandolSong/OT:language=dflt;"
% current: "FandolSong.otf/OT:language=dflt;"
\setCJKmainfont{FandolSong}

\setmainfont[Scale=MatchLowercase]{texgyretermes-regular.otf}

\begin{document}
abc
\end{document}
```

## Log file (required) and possibly PDF file

[usefont-invalidate-xecjk.log](https://github.com/latex3/latex2e/files/4161025/usefont-invalidate-xecjk.log)

**Comment by FrankMittelbach** [comment]
Can you explain a little bit what  `\xeCJK@fontfamily {#1}` is trying to do given some family name in `#1`? finding a matching CJK font for it? I.e., the same what the Japanese classes did by patching \rmfamily \sffamily ...?

As of using \edef in \usefont: \usefont is intended to select one specific font given attribute and not do any preprocessing on its attributes. At the moment \fontfamily doesn't do that (except that your patch does it in some sense) so right now it could have stayed \fontfamily, but that would be very inconsistent and not future proof.

Anyway, I need to better understand the problem, right now. I can't make your example file work in any way. It doesn't work in my 2018 environment and it doesn't work if I add the old definition of \usefont, I alays end up with

kpathsea: Running mktextfm FandolSong/OT

evne though the oft is on my system

**Comment by u-fischer** [comment]
@FrankMittelbach  the error message is the actual problem.  But like you I think that relying on a side effect in \usefont to setup the fonts looks a bit odd. Imho patching e.g. \normalfont etc would make more sense:

~~~~
\documentclass{article}
\usepackage{fontspec}
\usepackage[LoadFandol=false]{xeCJK}
\makeatletter
\DeclareRobustCommand\normalfont
                 {\usefont\encodingdefault
                          \familydefault
                          \seriesdefault
                          \shapedefault
                  \relax
                  \xeCJK@fontfamily{\familydefault}}
\makeatother
%\setCJKmainfont[Extension=.otf]{FandolSong-Regular}

\setCJKmainfont{FandolSong}

\setmainfont[Scale=MatchLowercase]{texgyretermes-regular.otf}



\begin{document}

abc

\end{document}
~~~~

**Comment by FrankMittelbach** [comment]
@u-fischer I would still like to understand a) why on my system it tries to metafont FangolSong
and b) if not \@rmfamilyhook \@sffamilyhook would be the right place

**Comment by muzimuzhi** [comment]
@FrankMittelbach 

> a) why on my system it tries to metafont FangolSong

This is caused by a wrong use of `\font` (with the syntax extended by xetex). In the following simplified example
```tex
\documentclass{article}
\usepackage{xeCJK}
\setCJKmainfont[Extension=.otf]{FandolSong-Regular}
\setmainfont[Scale=MatchLowercase]{texgyretermes-regular.otf}

\begin{document}
abc
\end{document}
```
parsing kv `Scale=MatchLowercase` results in calling something like
```tex
\font \l__fontspec_test_font ="FandolSong.otf/OT" at 10pt
```
but the right syntax for specifying a font by file name should be
```tex
\font \l__fontspec_test_font ="[FandolSong.otf]/OT" at 10pt
```
This wrong use of `\font` results in `kpathsea: Running mktextfm FandolSong-Regular.otf/OT`.

This explains why `kpathsea: Running mktextfm FandolSong-Regular.otf/OT` will present. Currently I only know limited info about this problem:
 - Reason for why `\font` is used with wrong syntex: some fontspec internals (`\__fontspec_fontname_wrap:n` and `\l__fontspec_extension_tl` at least) are not properly initialed or set. And I currently don't know why they are wrongly set.
 - Reason for why I opened this issue: the problem appears after upgrading to latex2e 2020-02-02, so I suspect some latex2e changes caused that and find the redefinition of `\usefont` counts. Currently I do not clearly know the relation between change of `\usefont` and wrong use of `\font` yet.

> Can you explain a little bit what \xeCJK@fontfamily {#1} is trying to do given some family name in #1? finding a matching CJK font for it? I.e., the same what the Japanese classes did by patching \rmfamily \sffamily ...?

> b) if not @rmfamilyhook @sffamilyhook would be the right place

I don't know enough to answer this question. So sorry. Hope I can provide more useful info in one week.

**Comment by FrankMittelbach** [comment]
well, I guess the \usefont change is not your problem (and the patch of \fontfamily is not necessarily a good idea (or could perhaps be done differently but for that I would need to understand what that code is really trying to achive (conceptually)). The missing brackets look to me more like a fontspec issue so perhaps @wspr  can help.

**Comment by muzimuzhi** [comment]
@FrankMittelbach 
> Can you explain a little bit what `\xeCJK@fontfamily {#1}` is trying to do given some family name in `#1`? finding a matching CJK font for it? I.e., the same what the Japanese classes did by patching \rmfamily \sffamily ...?

Some info about `\xeCJK@family`:

xeCJK uses a latex3 property list (`\g__xeCJK_family_name_prop`) to store the mapping `<family type> -> <CJK font family>`, for example `rm -> FandolSong`. When its argument is a family type (one of `\defaultfamily`, `rm`, `sf`, and `tt`), `\xeCJK@fontfamily {#1}` sets corresponding default CJK font family commands, say `\CJK[default|rm|sf|tt]faimly`, to the value of key `#1` stored in the property list.

And I know nothing about Japanese classes (did you mean classes like `jarticle`?).

**Comment by davidcarlisle** [comment]
@muzimuzhi  there is some discussion of the hooks used by the Japanese classes here

https://github.com/texjporg/platex/issues/88#issuecomment-573300944

(some of that issue is in Japanese which I don't read but google translate makes quite a reasonable english version)

**Comment by FrankMittelbach** [comment]
that'll help. So you really try to find a matching font for the current meta family, ie matching some Latin rm with a reasonable CJK font and similar for sf and tt. I thought that might be the case.

For that particular scenario we now have \@rmfamilyhook \@sffamilyhook and \@ttfamilyhook that are called whenever LaTeX switches to one of those families and this is where the jclass do rougly what you try to do as well (setting up matching japanese fonts)

**Comment by wspr** [comment]
@muzimuzhi — thanks of trying to trace this error. When you say:

> parsing kv Scale=MatchLowercase results in calling something like
>     \font \l__fontspec_test_font ="FandolSong.otf/OT" at 10pt

I tried to use my debug version of fontspec to trace this and I couldn't figure out why this could be happening. It appears to me (but I could be wrong!) that this error is being caused somewhere in the execution of `\setCJKmainfont{FandolSong}` but NOT in an equivalent `\setmainfont{FandolSong}`.

Is it possible this issue is arising entirely from within the CJK package? I'm happy to try and provide additional hooks in fontspec if this will help.

**Comment by muzimuzhi** [comment]
@FrankMittelbach 
Thanks and I will have a try.

@wspr 
A detailed analysis (in Chinese) can be seen https://github.com/CTeX-org/ctex-kit/issues/482#issuecomment-582654889. I can provide an English version if the machine translation is difficult to understand.  In short,
 - The problem is originally caused by`\setCJKmainfont`, but the error (wrong usage of `\font` hence calling metafont) is triggered by the following `\setmainfont`.
 - `\setCJKmainfont` uses `\normalfont` at the end.
 - Before the redefinition of `\usefont`, `\normalfont` uses `\fontfamily`, hence `\xeCJK@fontfamily` indirectly. Therefore, `\setCJKmainfont{FandolSong}` calls `\xeCJK@fontfamily` which sets property list `\g__xeCJK_family_name_prop` to `{rm}  =>  {FandolSong-Regular(0)}`.
 - After the redefinition of `\usefont`, `\setCJKmainfont{FandolSong}` won't use `\xeCJK@fontfamily`, which leaves `\g__xeCJK_family_name_prop` empty. Then `\fontfamily` (and hence `\xeCJK@fontfamily`) is first called in the following `\setmainfont`, when parsing `Scale=MatchLowercase`.
 - Since the property list is empty, `\xeCJK@fontfamily` uses `\fontspec_gset_family:Nnn` to get the family name, but this relies `\__fontspec_fontname_wrap:n` and `\l__fontspec_extension_tl`. Since at that time `\xeCJK@fontfamily` is called in the middle of expansion of `\setmainfont`, the meaning of `\__fontspec_fontname_wrap:n` and `\l__fontspec_extension_tl` are bound to the font set by `\setmainfont` (in the previous example, it is `texgyretermes`). This causes a wrong usage of `\font`.

**Comment by muzimuzhi** [comment]
In https://github.com/CTeX-org/ctex-kit/issues/482#issuecomment-583349583, @qinglee pointed that
 - The problem may be caused by that fontspec did not initialize `\l__fontspec_external_bool` to false in `\__fontspec_init:`. @wspr 
 - And, currently using `\@[rm|sf|tt]familyhook` as well as patching `\normalfont` would solve the problem in xecjk. Furthermore, providing a new `\@defaultfamilyhook` in latex2 would help xecjk avoid patching the `\normalfont`. @FrankMittelbach @u-fischer

**Comment by FrankMittelbach** [comment]
> * And, currently using `\@[rm|sf|tt]familyhook` as well as patching `\normalfont` would solve the problem in xecjk. Furthermore, providing a new `\@defaultfamilyhook` in latex2 would help xecjk avoid patching the `\normalfont`. @FrankMittelbach @u-fischer

`\normalfont` would only need patching if the document font is neither one of rm/sf/tt which in nearly all cases would be. But I agree you could set things up differently and precisely for that reason I already thoughts that `\@defaultfamilyhook` is the missing link that I overlooked. Guess the next release will provide this to make patching `\normalfont` unnecessary.

https://github.com/latex3/latex2e/issues/269

**Comment by FrankMittelbach** [comment]
upcoming hotfix be6da633d641197af6d92d110494887408ea59e2 will provide `\@defaultfamilyhook` executed in `\normalfont`.  This should take care of the issue and patching of `\fontfamily` should no longer be necessary.

**Comment by muzimuzhi** [comment]
Thanks. And @qinglee has provided https://github.com/CTeX-org/ctex-kit/commit/8f6a8b09d6e5c8848264b8d6a909a45c222353ce to close CTeX-org/ctex-kit#482, in which both with or without `\@defaultfamilyhook` cases are taken care of.

**Comment by FrankMittelbach** [comment]
that's pretty fast :-).   I'll expect the hotfix for LaTeX to appear in a few days.
