### ISSUE TITLE
Update of README.md and other files (.txt)

### ISSUE THREAD

**Issue by pablgonz** [latex3/latex2e#268]
Hello, just for curiosity I have placed to review the files distributed officially (available in ctan) for `latex(-dev)`. Here I leave a note of some considerations.

## Brief outline of the bug
1. The file `README.md` refers to `unpacked.txt`, `patches.txt` and `autoload.txt` which are not distributed.
2. The file `manifest.txt` refers to `patches.txt` which is not distributed and needs to add `ltnews...` (it is only up to number 26). The files `ltluatex.dtx` and `changes.old.txt` are not mentioned.
3. The `bugs.txt` file should be updated to the new reporting system (https://github.com/latex3/latex2e/blob/master/CONTRIBUTING.md).
4. The `usrguide.tex` file needs to update the section related to `filecontents`.

I think that's it.

**Comment by FrankMittelbach** [comment]
Thanks, there is more I'm sure. Some are leftovers from long removed approaches (like autoload for small machines) that simply make no sense anymore.  But it is good to have them on record for fixing.
