### ISSUE TITLE
There should be a \@defaultfamilyhook

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#269]
To better support CJK font handling underthe extended NFSS `\@rmfamilyhook`, `\@sffamilyhook`, and `\@ttfamilyhook` got added. Given that in theory the document family may different from `\rmfamily` `\sffamily` or `\ttfamily` there should be a further hook `\defaultfamilyhook` to be executed inside `\normalfont`.

**Comment by FrankMittelbach** [comment]
Went out with LaTeX 2020-02-02 PL 2

**Comment by muzimuzhi** [comment]
Thanks.
