### ISSUE TITLE
xspace : filtration on \ifvmode / \ifmmode

### ISSUE THREAD

**Issue by FOCCOF** [latex3/latex2e#27]
Hello,

I wonder about the opportunity to test at the beginning of the
command \xspace (provided by xspace.sty) to test if TeX is in
vertical mode :

Clearly when \ifvmode is true, there is never the need to insert a
{blank space}.

Moreover, \xspace could be deactivated when \ifmmode is true either
(what is the purpose to add a \space in a mathematical formula ?)

Best regards. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here

\begin{document}

See what happens in the .log

{\loggingall

\xspace


}

  
\end{document}
```

## Log file (required) and possibly PDF file  

!! Use drag-and-drop !!

**Comment by FrankMittelbach** [comment]
please follow the issue template and provide workable test files that you have actually run  next time :-) and the other components we ask for. In the long run this is helping everybody, thanks

**Comment by davidcarlisle** [comment]
Possibly, but I wonder about the use case here, \xspace is really for very
limited use in simple text documents for in text abbreviations, while the
macro could, as you say, detect math and vertical modes, I'm more inclined
to say it is an error of the programmer if they use \xspace in a position
that could be vertical mode. Adding a space does no harm anyway does it in
vmode?

**Comment by eg9** [comment]
The example code misses `\usepackage{xspace}`. Anyhow, `\xspace` should never be used in a document by itself, only as the last token in the definition of a parameterless macro.

Adding a space in vertical or math mode does nothing, so there's no point in checking for them.

**Comment by FrankMittelbach** [comment]
This really does fall under "works as designed", as explained it is inteded for a clearly defined use case and `\xspace` appearing in `vmode` or `mmode` is in fact an error on the programmers side using it (but at the same time adding a space in that mode doesn't do any harm either.

**Comment by FOCCOF** [comment]
But definitely, \xspace  does not ONLY insert a space : it first looks for the next tokens. So there is no point to check next tokens if TeX is in vmode or mmode.

Nevertheless, I'll come later with an example, if this behaviour might be harmful somewhere, due to the looking forward of \xspace...

**Comment by FrankMittelbach** [comment]
The question is always how much you guard against incorrect usage. If you put a \chapter command into a \footnote it will blow up, but no we don't think it is worth testing  if chapter is called inside a \insert.

Same here: \xspace is supposed to be used only after some text, so it is always by nature of supported use in hmode, so why should it test for that on any occasion if it shouldn't be ever in that situation (and if it is it is even fairly harmless)?
You really seem to have some use in mind for which it is not intended.

**Comment by FOCCOF** [comment]
Yes Frank, I know that. But things are not always so simple : suppose a command that typeset something in a \hbox, at the end there is \xspace. 

But after the \hbox, TeX may be in vertical mode (as it was before the \hbox).

I'm not sure it's better for the user to check: \ifhmode \expandafter \xspace \fi   than to the xspace command to perform the check.

Best regards.

**Comment by FOCCOF** [comment]
Alternatively, a test with \ifhmode can be considered as an optimisation, since nothing happens unless \ifhmode.

**Comment by davidcarlisle** [comment]
Sorry I can't think of any reasonable example where a user facing command using xspace would have a bare \hbox. Document level boxes should always start with \leavevmode.
Thank you for the suggestion but I do not propose to make any changes here.
