### ISSUE TITLE
\capitalgrave doesn't give accent in tabbing when used with lualatex

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#271]
## Minimal example showing the bug

```latex
\RequirePackage{latexbug}  
\documentclass{article}
\begin{document}
\begin{tabbing}
 \capitalacute a \capitalgrave a  \capitalmacron a 
\end{tabbing}  
\end{document}
```

this gives accents with pdflatex 
![image](https://user-images.githubusercontent.com/4047173/74110885-6d56cb80-4b90-11ea-9afc-304ed45cd3e4.png)

but tabbing commands with lualatex:

![image](https://user-images.githubusercontent.com/4047173/74110897-88294000-4b90-11ea-815a-a9e5a77ab891.png)

## Log file (required) and possibly PDF file  

[test-utf8.log](https://github.com/latex3/latex2e/files/4177950/test-utf8.log)

**Comment by FrankMittelbach** [comment]
yeah, guess

```
\makeatletter
  \def\capitalacute{\@tabacckludge'}
  \def\capitalgrave{\@tabacckludge`}
  \def\capitalmacron{\@tabacckludge=}
\makeatother
```
is needed as the default definition

**Comment by FrankMittelbach** [comment]
Went out with LaTeX 2020-02-02 PL 2
