### ISSUE TITLE
fontenc: provide record of loading requests (including the supplied optional arguments)

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#273]
## Brief outline of the bug

As the font encodings `T1` and `OT1` are no longer reloaded by `fontenc` it is difficult for babel to correctly deduce value that should be used for `\latinencoding`, see https://github.com/latex3/babel/issues/47 for examples.

It is therefore necessary to provide a mechanism that records with which optional arguments  the fontenc package is requested.

**Comment by jbezos** [comment]
Now it works again. I think it can be closed.

**Comment by FrankMittelbach** [comment]
Went out with LaTeX 2020-02-02 PL 2
