### ISSUE TITLE
Missing \ignorespaces in definition of \linethickness

### ISSUE THREAD

**Issue by rolfn** [latex3/latex2e#274]
## Brief outline of the bug

Using `\linethickness` in conjunction with the drawing macro `\polygone` (part of package »pict2e«) gives bad results if trailing spaces  are not suppressed. 

## Minimal example showing the bug

This example shows the bug (wrong addional space). See also the bug report for »pict2e« (https://github.com/rolfn/pict2e/issues/3#). `\iffalse --> \iftrue` shows a possible solution.

```latex
\RequirePackage{latexbug}
\documentclass{minimal}
\usepackage{color,pict2e}
\makeatletter
\iffalse
\DeclareRobustCommand\linethickness[1]
   {\@wholewidth #1\relax \@halfwidth .5\@wholewidth\ignorespaces}
\fi
\begin{document}
\unitlength=1cm
\begin{picture}(2,1)(-0.5,-0.1)
\color{yellow}\polygon*(0,0)(1,0)(1,1)
\linethickness{4bp} % <-- bad effect! 
\color{red}\polygon(0,0)(1,0)(1,1)
\end{picture}
\bigskip

\begin{picture}(2,1)(-0.5,-0.1)
\color{yellow}\polygon*(0,0)(1,0)(1,1)
\linethickness{4bp}%
\color{red}\polygon(0,0)(1,0)(1,1)
\end{picture}
\end{document}
```

## Log file (required) and possibly PDF file  

[bug.log](https://github.com/latex3/latex2e/files/4190690/bug.log)

**Comment by tloimer** [comment]
Here is a latex-only example, probably showing the same issue:
```tex
\documentclass{minimal}
\usepackage{latexbug}
\begin{document}
Common usage of picture command, \textbackslash linethickness with
or without space does not matter.\\
Without space: \begin{picture}(144,10)\put(0,5){\line(1,0){72}}
\linethickness{2pt}\put(72,5){\line(1,0){72}}\end{picture}\\
With space: \phantom{out}\begin{picture}(144,10)\put(0,5){\line(1,0){72}}
\linethickness{2pt} \put(72,5){\line(1,0){72}}\end{picture}

But naughty input makes a difference.\\
Without space:
\begin{picture}(144,10)
\put(0,5){\line(1,0){72}\linethickness{2pt}\line(1,0){72}}%
\end{picture}\\
With space: \phantom{out}%
\begin{picture}(144,10)
\put(0,5){\line(1,0){72}\linethickness{2pt} \line(1,0){72}}%
\end{picture}
\end{document}
```
[lines.log](https://github.com/latex3/latex2e/files/4191278/lines.log)

**Comment by FrankMittelbach** [comment]
In that example  the problem appears in invalid picture code only. According to Lamport's Manual: the only commands allowed in picture mode are `\put`, `\multiput` `\qbezier`and specific declarations like `\linethickness`.  So something like `\line` should not appear outside `\put`(which takes care of the spacing). 

The problem in the original example is that the color node prevents `\polygon` to remove a possibly added space, i.e., if you change the order
```
\color{red}
\linethickness{4bp} % <-- bad effect! 
```
the problem is gone too.
However,  I don't see any harm in not adding a space in first place instead of hoping it gets removed, so we will add the `\ignorespaces`.

**Comment by tloimer** [comment]
Well, for the sake of precision, it is not that \line would appear outside of \put. Rather, \linethickness  (and a second \line) is written into \put. I do not know, whether that is allowed.

**Comment by FrankMittelbach** [comment]
>  Rather, \linethickness (and a second \line) is written into \put. I do not know, whether that is allowed.

arguably not :-) but I agree it is something people do and it does "usually" work, so by fixing it that syntax is also (at least implicitly) supported. Thanks for the test file, I used that as the basis for a regression test.

**Comment by FrankMittelbach** [comment]
@rolfn we like to keep issue open in this repository until they are available in the master release (not just in -dev)
