### ISSUE TITLE
alltt breaks line spacing in preceding paragraph

### ISSUE THREAD

**Issue by mgttlinger** [latex3/latex2e#276]
## Brief outline of the bug

An `alltt` environment with changed font size changes the line spacing of the preceding paragraph if it is not separated by an empty line.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{alltt}
\usepackage{lipsum}

\begin{document}
\lipsum[20]
\begin{small}
\begin{alltt}
\lipsum[20]
\end{alltt}
\end{small}

\lipsum[20]

\clearpage
\lipsum[20]

\begin{small}
\begin{alltt}
\lipsum[20]
\end{alltt}
\end{small}

\lipsum[20]
\end{document}
```

## Log file (required) and possibly PDF file  
[bug.log](https://github.com/latex3/latex2e/files/4204675/bug.log)

The two pages showcase the wrong and the expected output.
[bug.pdf](https://github.com/latex3/latex2e/files/4204684/bug.pdf)

**Comment by eg9** [comment]
It's not `alltt`. Your `\begin{small}` declaration causes the `\par` command at the start of `alltt` to be issued when `\small` is in force, which affects the line space of the paragraph that's being typeset, that is, the _preceding_ text.

**Comment by mgttlinger** [comment]
Oh, I see. Nonetheless, this is unexpected behaviour. I would assume that the `small` environment only affects what is inside the environment and not escape this scoping.

**Comment by eg9** [comment]
There is no _documented_ `small` environment.

You can define a new environment:
```latex
\documentclass{article}

\usepackage{alltt}
\newenvironment{xalltt}[1][\normalsize]{\alltt#1}{\endalltt}
\usepackage{lipsum}

\begin{document}

\lipsum[20]
\begin{xalltt}[\small]
\lipsum[20]
\end{xalltt}
\lipsum[20]

\end{document}
```

**Comment by FrankMittelbach** [comment]
> Oh, I see. Nonetheless, this is unexpected behaviour. I would assume that the `small` environment only affects what is inside the environment and not escape this scoping.

As Enrico said, there is no defined "small" environment. Technically, if you have a command `\foo` then 
```
\begin{foo}  ... \end{foo}
```
does not produce an error but is nothing more than
```
{\foo ...}
```
Thus if you have
```
some text1 \begin{small} text2 \par ...\end{small}
```
then the `\par` is the point when the baselineskip and other paragraph values for the whole paragraph (`some text1 text2`) are determined. TeX only looks at the values at the end of the paragraph. Might be unexpected but that is how the engine works.

**Comment by mgttlinger** [comment]
Okay, thanks for the detailed explanation and sorry for the unnecessary issue.
