### ISSUE TITLE
Breakage of \textbf{\sffamily...} (seems to happen when font family differs from {rm,tt,...}default)

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#277]
```latex
% Samedi 15 février 2020 à 11:51:39
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[T1]{fontenc}
% next line is not needed to display problem
% it is only there to illustrate correct behaviour of description label
\renewcommand\familydefault{\sfdefault}
\begin{document}\thispagestyle{empty}
% Next line is the trigger of the problem
\fontfamily{ptm}\selectfont
\begin{description}
\item[hello] \textbf{\sffamily hello} {\bfseries\sffamily hello}
  {\fontseries{bx}\sffamily hello}
\end{description}
\showoutput
\end{document}
```

![Capture d’écran 2020-02-15 à 11 57 15](https://user-images.githubusercontent.com/2589111/74586683-5843c780-4fea-11ea-967e-56551c6f7f10.png)

With TL2018, all words are bold (sans-serif).

Took me some effort to get to a minimal example. The real one is this: 
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{newtxtt}
\begin{document}\thispagestyle{empty}
\ttzfamily
\textbf{\sffamily hello} {\bfseries\sffamily hello}
  {\fontseries{bx}\sffamily hello}
\showoutput
\end{document}
```
which produces
![Capture d’écran 2020-02-15 à 11 59 47](https://user-images.githubusercontent.com/2589111/74586709-b1abf680-4fea-11ea-9d87-09edfdbb2bef.png)

But to comply with `latexbug` I formulated as above (one can not `\fontfamily{newtxtt}\selectfont` directly due to the way `t1newtxtt.fd` is set-up, it would trigger a missing `\fi` error).

Turned out the problem appears to be that `\ttzfamily` activates a font family (`newtxttz`)  which is not the `\ttdefault` (or any other default). (I examined cursorily a trace but did not dig deeper).

In my example at top of this report the business with `\familydefault` is only to show that description labels correctly load `\T1/cmss/bx/n/10` (and also because it was part of my original set-up). The triggering line is the one setting the font family to `ptm`.

[bugnfss.log](https://github.com/latex3/latex2e/files/4208372/bugnfss.log)

**Comment by FrankMittelbach** [comment]
Thanks for the report (and also for producing a latexbug compatible version.

Actually the two are somewhat different because newtxtt invents an additional "meta" family and while there is planned support for that, right now the code in NFSS is restricted to the three meta families rm/sf/tt.

Nonetheless, in the existing code there is a bug/limitation that shouldn't be there. Pity though you didn't find this a few days earlier :-( so that a fix could have gone into PL2

> But to comply with `latexbug` I formulated as above (one can not `\fontfamily{newtxtt}\selectfont` directly due to the way `t1newtxtt.fd` is set-up, it would trigger a missing `\fi` error).

sounds to me like a bug  if the fd file behaves like that and I think should be reported to Michael.
I guess this code is the culprit:

```
\let\newtxtt@@upq\@empty
\expandafter\ifx\csname txtt@upqfalse\endcsname\relax    
\else   
    \iftxtt@upq\def\newtxtt@@upq{q}\fi
\fi
```
The typical case of testing for a conditional but then using it even if it doesn't exist :-)


> Turned out the problem appears to be that `\ttzfamily` activates a font family (`newtxttz`) which is not the `\ttdefault` (or any other default). (I examined cursorily a trace but did not dig deeper).

yes, right now if you use an arbitrary font family then `\sffamily` and friends will not adjust the `\bfdefault`to their need but stick with whaever is current which in this case is "b"

Here is a possible fix that you may want to try, but I'm not going to implement that immediately.

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{newtxtt}


\makeatletter

\let\series@change@debug\@empty

\def\prepare@family@series@update#1#2{%
%FMi   
   \series@change@debug{Prepearing for switching to #1 (#2)\on@line}%
%FMi --end   
   \expand@font@defaults
   \let\target@series@value\@empty
   \def\target@meta@family@value{#1}%
%FMi -- new
   \expandafter\edef\csname ??def@ult\endcsname{\f@family}%
%FMi --end   
   \let\@elt\update@series@target@value
     \@meta@family@list
%FMi -- new   
     \@elt{??}%
%FMi --end   
   \let\@elt\relax
   \fontfamily#2%
   \ifx\target@series@value\@empty
%FMi   
     \series@change@debug{Target series still empty ...}%
%FMi --end   
   \else
%FMi   
     \ifx \f@series\target@series@value
       \series@change@debug{Target series unchanged: \f@series \space = \target@series@value}%
     \else
%FMi --end   
       \maybe@load@fontshape
%FMi   
       \series@change@debug{Target series: \f@series \space -> \target@series@value}%
%FMi --end   
       \let\f@series\target@series@value
     \fi
   \fi
}
\def\update@series@target@value#1{%
  \def\reserved@a{#1}%
  \ifx\target@meta@family@value\reserved@a   % rm -> rm do nothing
  \else
%FMi   
   \series@change@debug{Trying to match #1: \csname#1def@ult\endcsname \space = \f@family\space ?}%
%FMi --end   
    \expandafter\ifx\csname#1def@ult\endcsname\f@family
      \let\@elt\@gobble
      \expandafter\let\expandafter\reserved@b
                      \csname mdseries@\target@meta@family@value\endcsname
      \expandafter\let\expandafter\reserved@c
                      \csname bfseries@\target@meta@family@value\endcsname
      \expandafter\ifx\csname mdseries@#1\endcsname\f@series
                                      \let\target@series@value\reserved@b
      \else\expandafter\ifx\csname bfseries@#1\endcsname\f@series
                                      \let\target@series@value\reserved@c
      \else\ifx\f@series\mddef@ult    \let\target@series@value\reserved@b
      \else\ifx\f@series\bfdef@ult    \let\target@series@value\reserved@c
      \fi\fi\fi\fi
    \fi
  \fi
}

%% for tracing ...

\let\series@change@debug\typeout

\makeatother


\begin{document}\thispagestyle{empty}

\ttzfamily


TT \textbf{TT BF \sffamily hello} 

{\bfseries\sffamily hello}

{\fontseries{bx}\sffamily hello}

\textsf{\bfseries BF
  \typeout{*** ttz family doesn't check, but works because it has a bx substitution default}%
  \ttzfamily TT ??
}
\textsf{          BF \ttzfamily TT }

\textttz{TT \textbf{TT BF  \textsf{ SF}}}

\showoutput
\end{document}
```

**Comment by u-fischer** [comment]
@FrankMittelbach  my first reaction was that (like in the fontspec case) the best would be if T1cmss (and other fonts) would provide a declaration for the b-series.  This solves the problem as long as b=bx. But if the fonts differ then there is again a problem if the series is changed before the family. Can one avoid that \sffamily adjusts the series in such cases:

~~~~
\documentclass{article}
\usepackage[T1]{fontenc}
\sffamily
\DeclareFontShape{T1}{cmss}{b}{n}%
       {<->sub*cmss/bx/it}{} %something different to b
\begin{document}

\normalfont 
  {\fontseriesforce{bx}\selectfont\sffamily hallo}
  {\fontseriesforce{b}\selectfont\sffamily hallo} %how to get b??

  {\sffamily\fontseriesforce{bx}\selectfont hallo}
  {\sffamily\fontseriesforce{b}\selectfont hallo}

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/74591914-9823a280-501c-11ea-9f73-faacd2b83143.png)

**Comment by FrankMittelbach** [comment]
The issue is really that `\bfseries` and `\mdseries`play a dual rule. On one hand they are "virtual" with the meaning of "switch to the standard bold face in the current family" but technically they are really going low-level and do some `\fontseries{bx}` or  `\fontseries{b}`  and are then no longer distinguishable from calling the lower level commands directly.

As a result there is really not a 100% satifying solution here and using faked b -> bx mappings is only a solution when there isn't any real "bx" which in case of, say CM or LM fonts there is (for Roman at least).

But perhaps a slight alteration to my previous attempt might do:
```

\makeatletter

\let\series@change@debug\@empty


\newif\if@forced@series

\DeclareRobustCommand\fontseriesforce[1]{\@forced@seriestrue\edef\f@series{#1}}
\DeclareRobustCommand\fontseries[1]{\@forced@seriesfalse\merge@font@series{#1}}

\def\prepare@family@series@update#1#2{%
%FMi
\if@forced@series
   \series@change@debug{No series preparation (forced \f@series)\on@line}%
   \fontfamily#2%
\else
   \series@change@debug{Prepearing for switching to #1 (#2)\on@line}%
%FMi --end   
   \expand@font@defaults
   \let\target@series@value\@empty
   \def\target@meta@family@value{#1}%
%FMi -- new
   \expandafter\edef\csname ??def@ult\endcsname{\f@family}%
%FMi --end   
   \let\@elt\update@series@target@value
     \@meta@family@list
%FMi -- new   
     \@elt{??}%
%FMi --end   
   \let\@elt\relax
   \fontfamily#2%
   \ifx\target@series@value\@empty
%FMi   
     \series@change@debug{Target series still empty ...}%
%FMi --end   
   \else
%FMi   
     \ifx \f@series\target@series@value
       \series@change@debug{Target series unchanged: \f@series \space = \target@series@value}%
     \else
%FMi --end   
       \maybe@load@fontshape
%FMi   
       \series@change@debug{Target series: \f@series \space -> \target@series@value}%
%FMi --end   
       \let\f@series\target@series@value
     \fi
   \fi
\fi
}

\def\update@series@target@value#1{%
  \def\reserved@a{#1}%
  \ifx\target@meta@family@value\reserved@a   % rm -> rm do nothing
  \else
%FMi   
   \series@change@debug{Trying to match #1: \csname#1def@ult\endcsname \space = \f@family\space ?}%
%FMi --end   
    \expandafter\ifx\csname#1def@ult\endcsname\f@family
      \let\@elt\@gobble
      \expandafter\let\expandafter\reserved@b
                      \csname mdseries@\target@meta@family@value\endcsname
      \expandafter\let\expandafter\reserved@c
                      \csname bfseries@\target@meta@family@value\endcsname
      \expandafter\ifx\csname mdseries@#1\endcsname\f@series
%FMi   
   \series@change@debug{\string\mdseries@#1 (\csname mdseries@#1\endcsname) identified}%
%FMi --end   
                                      \let\target@series@value\reserved@b
      \else\expandafter\ifx\csname bfseries@#1\endcsname\f@series
%FMi   
   \series@change@debug{\string\bfseries@#1 (\csname bfseries@#1\endcsname) identified}%
%FMi --end   
                                      \let\target@series@value\reserved@c
      \else\ifx\f@series\mddef@ult    \let\target@series@value\reserved@b
%FMi   
   \series@change@debug{\string\mddef@ult (\mddef@ult) identified}%
%FMi --end   
      \else\ifx\f@series\bfdef@ult    \let\target@series@value\reserved@c
%FMi   
   \series@change@debug{\string\bfdef@ult (\bfdef@ult) identified}%
%FMi --end   
      \fi\fi\fi\fi
    \fi
  \fi
}

%% for tracing ...

\let\series@change@debug\typeout

\makeatother

\showoutput


\documentclass{article}
\usepackage[T1]{fontenc}
\sffamily
\DeclareFontShape{T1}{cmss}{b}{n}{<->sub*cmtt/bx/n}{}


\begin{document}

\normalfont 
{\fontseriesforce{bx}\selectfont\sffamily hallo} 
{\fontseriesforce{b}\selectfont\sffamily hallo} 

{\sffamily\fontseriesforce{bx}\selectfont hallo}
{\sffamily\fontseriesforce{b}\selectfont hallo} 

\end{document}
```

**Comment by jfbu** [comment]
> sounds to me like a bug if the fd file behaves like that and I think should be reported to Michael.
> I guess this code is the culprit:
> 
> ```
> \let\newtxtt@@upq\@empty
> \expandafter\ifx\csname txtt@upqfalse\endcsname\relax    
> \else   
>     \iftxtt@upq\def\newtxtt@@upq{q}\fi
> \fi
> ```

Yes. I have right now written to Michael to propose to use
```
\let\newtxtt@@upq\@empty
\expandafter\ifx\csname txtt@upqfalse\endcsname\relax
\csname iftrue\endcsname
\else
    \iftxtt@upq\def\newtxtt@@upq{q}\fi
\fi
```
which fixes this. (there are many ways). Also for `t1newtxttz.fd` same thing.

**Comment by jfbu** [comment]
> But perhaps a slight alteration to my previous attempt might do:

Only to mention I tried your code and the behaviour of `\textbf{\sffamily foo}` is back to my naive expectations also in my original context.  (My original context has many lines in the preamble dating back to 2014 of the `\DeclareFontFamily{T1}{newtxttb}...` type with the comment `I need also the font with a slashed zero, for verbatim code.` but I am now in elderly maintenance mode for this and I am glad that they seem to interact well with as fancy things as `\fontseriesforce` of which I had never heard of before... even though a priori the two things are completely disjoint, nevertheless that no problem seems to arise is good). I can not comment more as I would need to assimilate current nfss goals and principles first.

**Comment by FrankMittelbach** [comment]
went out as part of PL3
