### ISSUE TITLE
Both \Umathcode and \Umathchar are used to determine the unicode-capability

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#279]
The ltnews31 says that, 
 - engines which are fully Unicode-capable must provide three primitives: `\Uchar`, `\Ucharcat`, and `\Umathcode`
 - it has become standard practice to check for Unicode-aware engines by using the existence of the `\Umathcode` primitive.

But in latex2e kernel, both `\Umathcode` and `\Umathchar` are used to determine the unicode-capability, and `\Umathchar` is even not one of the three required primitives.

Is this on purpose?

**Comment by wspr** [comment]
Sorry for the confusion. I think \Umathcode was (kind of) shorthand for “all of the \UmathXX” primitives. Does this make a practical difference or are you just trying to clarify the language? Nonetheless the use of \Umathchar as a check should be swapped simply for consistency...

**Comment by muzimuzhi** [comment]
I am only curious about the tiny differences between ltnews and source code, and no practical differences are met.

**Comment by muzimuzhi** [comment]
@zauguin Thanks.
