### ISSUE TITLE
TOC entry is NOT GENERATED if unnumbered chapter title contains Romanian diacritics

### ISSUE THREAD

**Issue by rsandu2007** [latex3/latex2e#28]
Hello all,

## Brief outline of the bug

In the following simple test file, the table of content entry corresponding to **the unnumbered chapter is not generated (does not show up in PDF output)** if Romanian diacritics are used in the chapter title.

Please note that the following characters with diacritics are an integral part of the Romanian language and may be entered directly from the keyboard when using Romanian layout (officially standardised since 2004):

- capital S with comma-below (Ș - Unicode 0218)
- small s with comma-below (ș - Unicode 0218)
- capital T with comma-below (Ț - Unicode 021A)
- small t with comma-below (ț - Unicode 021B)

Also, please note that corresponding characters with cedilla-below (Unicode 015E, 015F, 0162, 0163) are NOT correct for the Romanian language (they are still used sometimes for backward compatibility, but discouraged).

## How to reproduce the bug

- copy-paste the provided test file in a LaTeX editor (I used stock TexStudio in Fedora 27, with Romanian support, fonts, etc.)
- save and build the file to PDF
- note that Romanian diacritics **are** rendered correctly in the title and author's name
- note that the corresponding table of content entry for the unnumbered chapter does not show up in TOC (is not displayed in the resulting PDF file)
- change "chapter*{diacriticstext}" (unnumbered chapter) to "chapter{diacriticstext}" (numbered chapter), keeping "diacriticstext" the same
- rebuild the PDF file
- note that the corresponding TOC entry is now rendered correctly
- put back "chapter*{sometext}", now replacing "sometext" with text without diacrtitics
- rebuild the PDF file again
- note that the corresponding TOC entry is now rendered correctly

## Minimal example showing the bug

```latex
\documentclass[10pt,a4paper,twoside]{book}
\usepackage[romanian]{babel}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
 	
\title{Acesta este un titlu care „conține” ș-uri și ț-uri}
\author{Șerban Ioniță}
\date{}

\begin{document}
	 \maketitle
	 \tableofcontents
	 \chapter*{Introducțiune despre ș-uri ăâȚȘ}
\end{document}
```

## Log file (required) and possibly PDF file  

[test-correct.pdf](https://github.com/latex3/latex2e/files/1873438/test-correct.pdf)
[test-incorect.pdf](https://github.com/latex3/latex2e/files/1873439/test-incorect.pdf)

Thanks a lot,
Răzvan

**Comment by eg9** [comment]
Unnumbered chapters don't generate entries in the table of contents in the `book` class.
