### ISSUE TITLE
amslatex: Problems with [] in aligned

### ISSUE THREAD

**Issue by Volker-Weissmann** [latex3/latex2e#281]
Compiling of the following code:
```
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{equation}
\begin{aligned}
[abc]test
\end{aligned}
\end{equation}
\end{document}
```
should result in a pdf with the line "[abc]test". But it results in a pdf with the line "test":
[main.pdf](https://github.com/latex3/latex2e/files/4220184/main.pdf)
[main.log](https://github.com/latex3/latex2e/files/4220187/main.log)

pdflatex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.85.0

**Comment by davidcarlisle** [comment]
This is something of a FAQ the `[...]` is being taken as an (invalid) alignment option. You can guard by prefixing with `\relax`.

It is possible that the behaviour could be changed, and there is an open issue for this

https://github.com/latex3/latex2e/issues/5

so I will close here.
