### ISSUE TITLE
Font warnings after LaTeX2e update to 2020-02-02

### ISSUE THREAD

**Issue by callegar** [latex3/latex2e#282]
## Brief outline of the bug

After the recent update to LaTeX2e 2020-02-02, I am starting to see many font warnings on some documents. These did not occur with LaTeX2e 2019-10-01 patch level 3.

I realize that this is a font related issue and that the contributing guide advises about them. However, this issue seems to be directly related to some LaTeX2e change, and I would like to find out whether this is a regression or an intended behavior. In the latter case, having insight on the LaTeX2e kernel change that causes the warnings can be helpful to update whatever needs to be updated to gain compatibility with the latest LaTeX2e kernel.  The minimal example uses `fontspec` and the issue has also been crossposted to the `fontspec` issue tracker at https://github.com/wspr/fontspec/issues/409.

The warnings look like
```
LaTeX Font Warning: Font shape `TU/STEP(0)/bx/n' undefined
(Font)              using `TU/STEP(0)/b/n' instead on input line 61
```
and the same warning is repeated multiple times.

The warning seems to be triggered by the instancing of all the font series to modify the inter word spacing as `IEEEtran.cls` does. The minimal example below replicates that logic. Knowing whether this logic needs to be updated for the most recent LaTeX2e format is important because LaTeX is often used for publications that need to be consistent with IEEE standards. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\makeatletter
\newdimen\@IEEEtrantmpdimenA
\newdimen\@IEEEtrantmpdimenB
\newdimen\@IEEEtrantmpdimenC

\def\@IEEEinterspaceratioM{0.35}
\def\@IEEEinterspaceMINratioM{0.23}
\def\@IEEEinterspaceMAXratioM{0.50}

\def\@IEEEinterspaceratioB{0.375}
\def\@IEEEinterspaceMINratioB{0.23}
\def\@IEEEinterspaceMAXratioB{0.55}

\def\@@@IEEEsetfontdimens#1#2#3{{%
    \setlength{\@IEEEtrantmpdimenB}{\f@size pt}
    % grab the font size in pt, could use 1em instead.
    \setlength{\@IEEEtrantmpdimenA}{#1\@IEEEtrantmpdimenB}%
    \fontdimen2\font=\@IEEEtrantmpdimenA\relax
    \addtolength{\@IEEEtrantmpdimenA}{-#2\@IEEEtrantmpdimenB}%
    \fontdimen3\font=-\@IEEEtrantmpdimenA\relax
    \setlength{\@IEEEtrantmpdimenA}{#1\@IEEEtrantmpdimenB}%
    \addtolength{\@IEEEtrantmpdimenA}{-#3\@IEEEtrantmpdimenB}%
    \fontdimen4\font=\@IEEEtrantmpdimenA\relax}}

% revise the interword spacing for each font weight
\def\@@IEEEsetfontdimens{{%
    \mdseries
    \@@@IEEEsetfontdimens{\@IEEEinterspaceratioM}{\@IEEEinterspaceMAXratioM}{\@IEEEinterspaceMINratioM}%
    \bfseries
    \@@@IEEEsetfontdimens{\@IEEEinterspaceratioB}{\@IEEEinterspaceMAXratioB}{\@IEEEinterspaceMINratioB}%
  }}

% revise the interword spacing for each font shape \slshape is not often
% used for IEEE work and is not altered here. The \scshape caps are
% already a tad too large in the free LaTeX fonts (as compared to what the
% IEEE uses) so we won't alter these either.
\def\@IEEEsetfontdimens{{%
    \normalfont
    \@@IEEEsetfontdimens
    \normalfont\itshape
    \@@IEEEsetfontdimens
  }}

\def\IEEEtunefonts{{\selectfont\rmfamily
    \tiny\@IEEEsetfontdimens
    \scriptsize\@IEEEsetfontdimens
    \footnotesize\@IEEEsetfontdimens
    \small\@IEEEsetfontdimens
    \normalsize\@IEEEsetfontdimens
    \large\@IEEEsetfontdimens
    \LARGE\@IEEEsetfontdimens
    \huge\@IEEEsetfontdimens
    \Huge\@IEEEsetfontdimens}}

\makeatother
\usepackage{fontspec}
\setmainfont{STEP}
\IEEEtunefonts
\begin{document}
hello \emph{hello}
\end{document}
```

## Log file (required) and possibly PDF file  
[testme.log](https://github.com/latex3/latex2e/files/4230424/testme.log)

**Comment by callegar** [comment]
A much more minimal test case:

```latex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{STEP}
{\bfseries}
\begin{document}
hello \emph{hello} \textbf{hello}
\end{document}
```

**Comment by FrankMittelbach** [comment]
The `\setmainfont{STEP}` changes the roman font to STEP (which has a "b" bold) but it doesn't currently alter the default used by `\bfseries`when typesetting in `\rmfamily` which is still set up to work with LMR (which uses "bx").  At `\begin{document}` NFSS checks the setup figures out that `\rmfamily` is no longer LMR or any other of the few "bx" fonts and changes the default accordingly. But during the preamble the setup is inconsistent.
`\setmainfont`would need to issue
```
\DeclareFontSeriesDefault[rm]{bf}{b}
```
when setting up the font to avoid that (which it will in its next release).

So I'll close the issue here as it is also logged with @wspr and need to be fixed in fontspec.
