### ISSUE TITLE
changes to classes.dtx are missing in letter.dtx

### ISSUE THREAD

**Issue by JohannesBraams** [latex3/latex2e#283]
## Brief outline of the enhancement

Recently some changes were made in classes.dtc. While getting the NTG classes in sync with the standard LaTeX classes I noticed that similar changes haven't been applied to letter.dtx

The obvious example it \itemlabel\font, there are more. I can provide a more extensive list or even a diff

**Comment by FrankMittelbach** [comment]
A short list  would be useful (or even making the changes) if there are other things they may have been older because I can't remember any recent changes other than the itemlabel font (but that may be my bad memory.

**Comment by JohannesBraams** [comment]
There were other things I had to do to brief.dtx. but they were Indeed
older . I have s modifuedletter.dtx available,  will check again tomorrow
morning after a good night's sleep ;)
