### ISSUE TITLE
Graphics inclusion fails (for some drivers) in `\endlinechar-1` context

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#286]
## Minimal example showing the bug

```latex
% compile with latex (+dvips+ps2pdf)
% similar example can be done with platex (+dvipdfmx) with a png image
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{graphicx}
\begin{document}
{\endlinechar-1
\includegraphics{example-image.eps}}
\end{document}
```

The graphics inclusion code wants to do `\catcode\endlinechar 5` and this breaks if `\endlinechar` has been set to `-1`.

```console
! Bad character code (-1).
\Gread@generic@aux ...`\	10 \catcode \endlinechar 
                                                  5 \@makeother \:\@makeothe...
l.8 \includegraphics{example-image.eps}
                                       }
? X
```

In real life, the issue arose with `platex + dvipdfmx` (and `dvipdfmx` class option) and inclusion of a `png` file. The reason for the `\endlinechar -1` is that this was embedded into some `\scantokens` and we wanted to avoid the space token this process induces. More precisely for some reason (having to do with using `\href` in some context with active characters needing deactivation) the `\includegraphics` was incorporated into the `\everyeof` toks (to freeze its catcodes and not have them submitted to `\scantokens`).

For this real life context, fix can be obtained by starting the `\everyeof{}` contents by `\endlinechar13 `.

## Log file (required) and possibly PDF file  

[endlinechar.log](https://github.com/latex3/latex2e/files/4240685/endlinechar.log)

**Comment by davidcarlisle** [comment]
Thanks for the report, the issue is due to this change I guess

```
% \changes{v0.5e}{1994/1l/02}
%     {Fix the catcodes of \cs{endlinechar} and ctrl-D}
```

I think best thing to do would be to make sure it's locally set to 13 in the "read"  macros `\Gread@generic@aux` in graphics.sty and `\Gread@@pdf` in dvipdfmx.def, luatex.def etc.

**Comment by jfbu** [comment]
> % \changes{v0.5e}{1994/1l/02}

I am a slow tester, but give me a few decades and I can sometimes find things.

**Comment by FrankMittelbach** [comment]
Am 23.02.20 um 13:13 schrieb Jean-François B.:
>     % \changes{v0.5e}{1994/1l/02}
> 
> I am a slow tester, but give me a few decades and I can sometimes find 
> things.
> 

you mean that it took 26 years to find that the changes lines has an "l" 
instead of a 1? :-)

**Comment by jfbu** [comment]
@FrankMittelbach sadly only in 1994 could I have spotted that, nowadays that would require me to set my screen fonts to size `\Huge`.

**Comment by davidcarlisle** [comment]
Despite my comment above, I think now dvipdfmx `\Gread@pdf` all use the core `\Gread@generic@aux` so it is enough to add

```
  \endlinechar13 %NEW
```

just before the catcode setting, so equivalent to the following (using `[dvipdfmx]` but also variants  with `dvips`  with latex, and with xetex).


```

\documentclass{article}
\usepackage[dvipdfmx]{graphicx}
\makeatletter
\def\Gread@generic@aux#1#2{%
  \begingroup
  \@tempcnta\z@
  \loop\ifnum\@tempcnta<\@xxxii
     \catcode\@tempcnta14 %
     \advance\@tempcnta\@ne
  \repeat
  \catcode`\^^?14 %
  \let\do\@makeother
  \dospecials
  \catcode`\ 10 %
  \catcode`\^^I10 %
  \endlinechar13 %NEW
  \catcode\endlinechar5 %
  \@makeother\:%
  \@makeother\-%
  \immediate\openin\@inputcheck\quote@name{#1} %
  #2{#1}%
  \ifGin@bbox
    \expandafter\xdef\csname #1 bbox\Gread@attr@hash\endcsname{\@gtempa}%
  \else
    \@latex@error
      {Cannot determine size of graphic in #1 (no BoundingBox)}%
      \@ehc
    \gdef\@gtempa{0 0 72 72 }%
  \fi
  \endgroup
}
\makeatother

\begin{document}
{\endlinechar-1
\includegraphics{example-image.eps}}
\end{document}
```

**Comment by FrankMittelbach** [comment]
Plan to write a short entry for doc/ltnews32 ?

**Comment by davidcarlisle** [comment]
yes (need to write something about the viewport addition as well)
