### ISSUE TITLE
Problems with [ after \\ in aligned

### ISSUE THREAD

**Issue by Volker-Weissmann** [latex3/latex2e#288]
The following code does not compile. [Logfile](https://github.com/latex3/latex2e/files/4241466/bug.log)
```
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{equation}
\begin{aligned}
abc\\[def]
\end{aligned}
\end{equation}
\end{document}
```

The following code also does not compile.  [Logfile](https://github.com/latex3/latex2e/files/4241469/bug.log)

```
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{equation}
\begin{aligned}
abc\\[def
\end{aligned}
\end{equation}
\end{document}
```
Interestingly, both examples compile if you put a newline after \\\\.
It would be great if you could either make this compile or improve the error message. Currently, the first fails with the message
```
./bug.tex:7: Missing number, treated as zero.
<to be read again> 
                   d
l.7 abc\\[def]
```
and the second one fails with the message
```
Runaway argument?
def \end {aligned} \end {equation} \end {document} 
! File ended while scanning use of \math@cr@@.
<inserted text> 
                \par 
<*> bug.tex
```

This bug is seams similar to issue #5 , but it is not identical.

**Comment by u-fischer** [comment]
It is standard in LaTeX that `\\` takes an optional argument which must be a dimension. 

In the amsmath environments you can add a space or a newline before the bracket. Then the content will be part of the document, see amsldoc.pdf, 3.9 Vertical spacing and page breaks in multiline displays.

**Comment by FrankMittelbach** [comment]
As Ulrike said this is documented behavior and while the low-level error is not nice, it is very difficult to change without breaking a lot of documents. #5 in contrast is a bug because tings get silently swallowed.
