### ISSUE TITLE
Some .fd files incorrectly specify "mc" as series which should have been "c"

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#289]
## Brief outline of the bug

Try this simple document
```
\documentclass{article}
\usepackage[T1]{fontenc}
\begin{document}

\fontfamily{phv}\fontseries{mc}\selectfont
\expandafter\string\the\font

\end{document}
```

With the current kernel,  this generates
```
LaTeX Font Warning: Font shape `T1/phv/c/n' undefined
(Font)              using `T1/phv/m/n' instead on input line 5.
```
and the font name happens to be
```
\T1/phv/m/n/10
```

However, with TL 2018, the series is honored and the
document prints
```
\T1/phv/mc/n/10
```
Technically this was always wrong in the `.fd`which should always have specified the series as `c` not `mc` and with the updated LaTeX this now matters.

## Fix

One possibility is to correct all `.fd` files that specify `mc` as series names in  `\DeclareFontShape` and replace that with the correct value `c`. The alternative is to augment  the declaration to drop an extra `m` in cases where it shouldn't be there, i.e., make
```
\DeclareFontShape{T1}{phv}{mc}{n}{...}
```
behave like
```
\DeclareFontShape{T1}{phv}{c}{n}{...}
```
This is most likely the approach that we will take.

**Comment by FrankMittelbach** [comment]
gone to CTAN

**Comment by schlcht** [comment]
I may be a bit late to the game, but I just wanted to register my scepticism about these new warnings concerning the "incorrect series value \`mc'". 

Firstly, I find it a bit harsh to rate "mc" as "incorrect". After much searching, I did now see that the special case of medium condensed is indeed mentioned in `fntguide.pdf`, but on the other hand, for example the Font installation guide only says that weight and width shall be "concatenated" (without mentioning "c" as a special case), and also even `fontinst`'s`\latinfamily` will create "mc" series by default. (So I'm not the only one who wasn't aware that this would be incorrect.)

Secondly, IMHO, "mc" is much clearer than "c", and this not only if you have a font with many variants: "lc, mc, sbc, bc" makes more sense to me than "lc, c, sbc, bc"

And finally, why would you issue warning if, as @u-fischer rightly says [here](https://github.com/latex3/latex2e/issues/308#issuecomment-598918099), it is harmless?
