### ISSUE TITLE
filecontents doc niglets/update

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#298]
In ltclass.dtx, nopremable (typo) on line 164 should apparently actually be "noheader".

Not important, but two lines down from that, the "actually" is unnecessary.

Then, in usrguide, the filecontents description has apparently not been updated. No mention of the new options, still said to be required before \documentclass, etc.

**Comment by FrankMittelbach** [comment]
thanks, first part is actually already reported and addressed by #296. The missing documentation I thought was also in an issue, but doesn't to be, so I keep this one option for usrguide.tex update.
