### ISSUE TITLE
File ".tex" is not installed

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#30]
Starting from [texlive r47330](https://www.tug.org/svn/texlive?view=revision&revision=47330), the file ".tex" (generated from fileerr.dtx) is missing.

When I locally execute `texlua build.lua install` it is actually missing; is this intended?

**Comment by josephwright** [comment]
Nothing has changed in the `.ins`: I guess there is a file-copy issue. Will try to sort today!

**Comment by josephwright** [comment]
I'm going to re-upload to fix this by using an older `l3build`, then fix the issue in the current release of `l3build` separately (fixing the `tools` release is more urgent).

**Comment by FrankMittelbach** [comment]
yeah, sounds like a plan. in that case the upload would also contain the small docu corrections that I made in tools after the last update

**Comment by josephwright** [comment]
@FrankMittelbach Ah, of course. I've uploaded the fixed version, and am working on the issue at the `l3build` end: first step is to track down the change. (I suspect the tree support ...)

**Comment by FrankMittelbach** [comment]
mising file uploaded to ctan. problem in l3build tracked under different issue
