### ISSUE TITLE
record the name of the counter in \refstepcounter

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#300]
## Brief outline of the enhancement

The zref package has a module which allows to record the name of the counter from the last `\refstepcounter` in a label. This can be useful to write e.g. commands like `autoref` which automatically add words like "Figure" or "Table" before a reference. 

For this feature zref patches at begin document `\refstepcounter`. But the patch clashes with patches from hyperref  and the reference is wrong for e.g. equations. See https://github.com/ho-tex/zref/issues/5. 

I suggest that the kernel stores the counter name directly. Then zref could simply use this and the patch would be unneeded. The following example changes `\refstepcounter` and implements a zref-property which uses the new interface and works as expected. 

## Minimal example showing the suggested patch and the output

```latex
\makeatletter
\def\refstepcounter#1{%
    \stepcounter{#1}%
    \def\@currentcounter{#1}% <--NEW
    \protected@edef\@currentlabel
       {\csname p@#1\expandafter\endcsname\csname the#1\endcsname}%
}
\makeatletter

\documentclass{book}
\usepackage{zref-user,zref-counter}
\makeatletter
\zref@newprop{newcounter}{\@currentcounter}
\zref@addprop\ZREF@mainlist{newcounter}
\makeatother
\usepackage{hyperref}
\begin{document}

\refstepcounter{section}
\begin{equation}
  1=1\zlabel{eq}    
\end{equation}        

\zref[newcounter]{eq},  %OK
\zref[counter]{eq}         %WRONG, shows section instead of equation
\end{document}

```

![image](https://user-images.githubusercontent.com/4047173/75981768-7fa0fc80-5ee5-11ea-984f-3887c84ec144.png)

**Comment by davidcarlisle** [comment]
seems reasonable but would need `\edef`  for `\refstepcounter\@listctr` it may help to rationalise some of the overloaded definitions for this (zref, hyperref, cleveref, varioref and probably more all redefine refstepcounter at some point)

**Comment by FrankMittelbach** [comment]
Name should probably `\@currcounter` in line with other 2e `\@curr...`

**Comment by u-fischer** [comment]
I used \@currentcounter as there was also \@currentlabel. But \@currcounter or \@curr@counter is fine too.
