### ISSUE TITLE
amsmath: dropping bracket group without warning

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#305]
## Brief outline of the bug

Some amsmath environments have a trailing optional argument, e.g. `gathered`. As normal with LaTeX this  argument can be on a new line. While problematical because it can be misinterpreted when the formular starts with a real bracket,this is not really a bug (mathtools has an option disallow spaces to make this less problematical).

However what is really problematical is that such a bracked group is only tested for the values `t` and `b`and everything else is assumed to be `c` and dropped which may result loosing text without warning as in the example. The latter is a bug.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{amsmath}
\showoutput
\begin{document}
\[
\begin{gathered}
[p] = 100 \\
[v] = 200
\end{gathered}
\]
\end{document}
```

**Comment by davidcarlisle** [comment]
@FrankMittelbach  isn't this the same as https://github.com/latex3/latex2e/issues/5

**Comment by FrankMittelbach** [comment]
guess so. didn't check that we had on old one of that open :-(. Ok might as well use that one then and close here.

**Comment by josephwright** [comment]
`xparse`?

**Comment by FrankMittelbach** [comment]
> `xparse`?

no. no functional change here for amsmath. It is as it is, newlines are allowed and most certainly used in myn documents.

**Comment by blefloch** [comment]
`\str_case:nnTF`
