### ISSUE TITLE
Helvet triggers font warnings with recent LaTeX2e

### ISSUE THREAD

**Issue by callegar** [latex3/latex2e#308]
## Brief outline of the bug

Loading helvet triggers font warnings when reading `texmf-dist/tex/latex/psnfss/t1phv.fd`

```
LaTeX Warning: Font shape declaration has incorrect series value `mc'.
               It should not contain an `m'! Please correct it.
               Found on input line 20.
```
A similar warning is repeated multiple times for different lines in `t1phv.fd`.

Either recent versions of LaTeX2e were unwillingly made incompatible with `helvet` or `helvet` in the psnfss bundle (which is declared as a required piece of LaTeX) needs updating.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{helvet}
\begin{document}
{\sffamily Test}
\end{document}
```

## Log file (required) and possibly PDF file  
[testme.log](https://github.com/latex3/latex2e/files/4331688/testme.log)

**Comment by u-fischer** [comment]
This is known, see https://github.com/latex3/latex2e/issues/299. But it wasn't yet possible to contact  the maintainer of helvet:. The warnings are harmless, so you can ignore them for now.

**Comment by callegar** [comment]
Thanks for pointing out, in my search I initially missed it. And good to know that the warnings are totally harmless.

**Comment by FrankMittelbach** [comment]
.fd files have now been updated on CTAN but it will take until TL2020 that they automatically make it to the user desktops
