### ISSUE TITLE
A macro name conflict between array and makecell package

### ISSUE THREAD

**Issue by qinglee** [latex3/latex2e#31]
## Brief outline of the bug

The macro `\mcell@box` is defined by array (2017/11/07 v2.4f) and makecell (2009/08/03 V0.1e).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\RequirePackage{makecell}
\stop
```

## Log file (required) and possibly PDF file  

[z.log](https://github.com/latex3/latex2e/files/1886259/z.log)

**Comment by FrankMittelbach** [comment]
fixed in source (renamed some internals) and uploaded to ctan -- thanks
