### ISSUE TITLE
Figure number is not generated correctly 

### ISSUE THREAD

**Issue by ykzhou** [latex3/latex2e#312]
## Brief outline of the bug
In the tex source, I used   \ref{sincos}  to refer to a figure with \label{sincos}, 
but the produced PDF shows the \ref{} to point to another figure (generated using a different label)

I tracked down this bug and noticed that if I commented out the \item (see the attached source file), then this bug no longer shows up.

I tested two different versions of latex (pdflatex), the same bug shows up.  So I would like this issue being resolved.  

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!

\documentclass[11pt]{article}
%\usepackage[margin=0.7in]{geometry}
\usepackage{enumerate}

\begin{document}

\title{pdfTeX bug in figure reference numbers?}
\date{}
\maketitle

\begin{enumerate}[Pr.1.~]
\item  %remove this \item then the bug does not show up
  
This item can be empty or non-empty, as long as it is here, the bug always shows up.

\item
  This should refer to Figure 1  (Figure \ref{sincos}.)
  But this mistakenly pointed to Figure \ref{sincos_mod}, why such a bug?
\begin{figure}[htp]
\begin{center}
\caption{label\{sincos\}}
\end{center}
\label{sincos}
\end{figure}


\item
[fig_ref_bug.log](https://github.com/latex3/latex2e/files/4384470/fig_ref_bug.log)
[fig_ref_bug.log](https://github.com/latex3/latex2e/files/4384471/fig_ref_bug.log)
[fig_ref_bug.pdf](https://github.com/latex3/latex2e/files/4384474/fig_ref_bug.pdf)



This should refer to Figure \ref{sincos_mod},  not Figure \ref{sincos}.

\begin{figure}[htp]
\begin{center}
\end{center}
\caption{label\{sincos\_mod\}}
\label{sincos_mod}
\end{figure}  

\end{enumerate}%{itemize}

\end{document}

The following version of pdfTex on ubuntu 16.0  shows the bug:

pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.6.17; using libpng 1.6.17
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.41.0


Another version of pdfTex on CentOS Linux release 7.5 shows the same bug:

pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with xpdf version 3.04

```

**Comment by davidcarlisle** [comment]
sorry this is user error not a bug, the `\label` needs to be in the same scope as the `\caption` but you have it after `\end{center}`

**Comment by ykzhou** [comment]
Hello, thanks for your prompt reply last time.  Sorry about the long delay in posting a follow up Thank You note.

What you said makes perfect sense.  On a minor side, especially from a casual user's point of view, the label here is used to refer to the Figure, not the caption.  It is not uncommon to assume that if the label is inside \begin{figure} \end{figure}, it should point to the same Figure. (By all means, the caption is only part of the figure, letting it to fully control the numbering of a figure is a bit overtaxing to a user's attention.)

**Comment by FrankMittelbach** [comment]
@ykzhou yes it is the cause of misunderstandings, but as far as `\label` is concerned there is not much that can be done about it it. It has local scope.  The original design of floats (dating back to the '80) also allows several `\caption`s within one figure in which case the interpretation "this label refers to the whole figure" is somewhat meaningless as well.
(it is not what I would design in 2022 if starting from scratch, but  what we have ...)
