### ISSUE TITLE
Indentation and formating the code in report.cls 

### ISSUE THREAD

**Issue by tmelorc** [latex3/latex2e#314]
I'm not sure if here is right place to do this, also not sure if this is too relevant, but I observed some wrong indentation in the code of `report.cls`. Sorry if I'm wrong.

Maybe the solution could be:

```
l175: remove indentation
l207: indent to match with l176
l209-259: indent the whole block inside the \else part
```
Here is the file I checked.
[https://github.com/latex3/latex3/blob/master/texmf/tex/latex/base/report.cls](url)

Regards.

**Comment by FrankMittelbach** [comment]
@tmelorc but since you took the trouble to report I'll moved it

**Comment by tmelorc** [comment]
Dear @FrankMittelbach, many thanks for attention. I agree that there are many many more import things to be done in the list of changes. Since I found those (not problems) indentations I decided to report here, maybe some day it could be changed. Unfortunately I can not help with more substantial changes. Anyway, thanks one more time. Regards.

**Comment by FrankMittelbach** [comment]
main point I was trying to make is that it is best to always report against the source files not the generated files (as they have the comments stripped off) as it is just extra work for us to then search for the issue in the real source. So try reporting such things against the .dtx not .sty/cls etc. Such  generated files always say where they are coming from near the top.

**Comment by tmelorc** [comment]
@FrankMittelbach I guess I got the point now. I never read or studied dtx files. I will see. Thanks.
