### ISSUE TITLE
\normalfont doesn't to set the correct medium font series

### ISSUE THREAD

**Issue by vjalby** [latex3/latex2e#315]
## Brief outline of the bug

When using a custom mdseries with rm font  (e.g., Minion 3 medium instead of regular), the command \normalfont (f.i., in article.cls for page number) does not set the correct (font) mdseries but the default one. The example below uses 'b' as 'md' series, just to show the problem. A quick fix is to set \let\@defaultfamilyhook\mdseries 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\DeclareFontSeriesDefault[rm]{md}{b}

\begin{document}
roman text in font-serie-default-medium (=bold)

\normalfont
roman text in global-medium (=rm)

\mdseries 
roman text in font-serie-default-medium (=bold)

\end{document}
```

## Log file (required) and possibly PDF file  
[normalfont.log](https://github.com/latex3/latex2e/files/4465996/normalfont.log)

**Comment by FrankMittelbach** [comment]
Thanks for the problem report. I guess your  assumption is that `\normalfont` is a synonym for the roman font so if you change that, `\normalfont` changes with it. However, that is not how it is implemented or defined. It is defined as the "default document font"  is given by the values  for `\familydefault`, `\seriesdefault` and `\shapedefault`.

It would, for example be allowed to have these defaults point to the "sf" family or even to a family that is neither the one set up for "rm", "sf", or "tt". In  any such case the document should start out with the above 3 defaults for family/series/shape and return to them in various places when \normalfont is called.  

And just like a document doesn't need to start out with the "rm" family there is no reason why it need to start out in the "md" series or "n" shape. Therefore forcing a call to `\mdseries` into `\normalfont` would fix your example but wouldn't be correct in general.

I can see that there a bit of surprise in the fact that you change the setup for the family that is used as a document font and that change is not automatically carried through and instead you have to also alter `\seriesdefault`. 

So while I don't think this is  a bug I guess there is perhaps some room for improvement and I'll think about whether that could be changed in a way that it is comprehensible while still allowing for the defaults to be altered directly in the other scenarios.

**Comment by FrankMittelbach** [comment]
I decided on implementing a logic that the family used for the document font (\normalfont) is influencing the default for \seriesdefault automatically with the following restrictions:
 - changes after \begin{document} do not change the setup for \normalfont 
 - if \seriesdefault has been directly changed in the preamble then it is not altered

**Comment by vjalby** [comment]
It's the behavior I was expected when I made this report. Thanks you!
