### ISSUE TITLE
8r.enc in psnfss.enc stale by one comment

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#316]
Not that it matters, but the 8r.enc in psnfss (does it really need to be there?) is stale by one comment that I fixed (in fontname) in 2006:

```
--- macros/latex/required/psnfss/8r.enc
+++ Master/texmf-dist/fonts/enc/dvips/base/8r.enc

 %   version   = "2.0",
-%   date      = "30 October 2002",
+%   date      = "27nov06",
 %   filename  = "8r.enc",
@@ -116,3 +116,3 @@
  /logicalnot /hyphen /registered /macron
-% 0xD0
+% 0xB0
  /degree /plusminus /twosuperior /threesuperior
```

**Comment by u-fischer** [comment]
Well I don't know if 8r.enc should be there. Is it the "official" source for 8r.enc or is there another one? Or is there a better suited package to hold the file?

(I adapted the comment and the date in my local version, so if I ever reupload psnfss it will be corrected, but I don't think that it is worth a ctan upload on its own.

**Comment by kberry** [comment]
As far as I know the official source for 8r.enc is my fontname package. Thus the version I put in TL comes from there.

Certainly agree that there's no need to re-upload just for this (or the other typos).

**Comment by FrankMittelbach** [comment]
Guess all of this should be reported to Walter (not that I expect any other change to that package any time soon)
