### ISSUE TITLE
psnfss doc typo, psfonts.pdf, dist

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#317]
In the second changes.txt item for the new psnfss,
`fd-files pf pcz` should be `fd-files of pzc`.

Perhaps it would still be worth building and distributing psfonts.pdf, in addition to psnfss2e.pdf. Since this is such a core package.

At any rate, FYI, I've just imported the new release to TL (r54694). Hope it works out. I trust there were no changes to the tfm/vf files, even though their mtimes changed. (I ignored them in those sub .zip files after checking a few.) --thanks, karl.

**Comment by u-fischer** [comment]
I corrected the typo in my local version, but we didn't really take over maintenance of psnfss. I only uploaded the needed changes for the new latex once in agreement with the maintainer so bug reports should better be sent to him. 
I didn't touch the tfm/vf files, but I had to unpack and repack the zip files and used git, so this could affect the dates.
