### ISSUE TITLE
With longtable, a * in the first column does not appear unless it is written {*}

### ISSUE THREAD

**Issue by keithbriggs** [latex3/latex2e#318]
## Brief outline of the bug

With longtable, a * in the first column does not appear unless it is written {*}

## Minimal example showing the bug

```latex
\documentclass[10pt,a4paper]{book}
\usepackage[T1]{fontenc}
\usepackage{longtable}
\usepackage[lmargin=25mm,rmargin=25mm,bmargin=30mm]{geometry}
\RequirePackage{latexbug}
\begin{document}

With longtable, a \texttt{*} in the first column does not appear unless it is written \texttt{\{*\}}! (Except in the first row.)

Good:
\setlength{\tabcolsep}{0pt}
\begin{longtable}[l]{rp{150mm}}%\RaggedRight
{*}& \textit{\=Aca}: Akenham\tabularnewline
{*}& \textit{{\AE}lffl{\=\ae}d}: Alpheton\tabularnewline
   & \textit{{\AE}lfwynn}: Aveley Hall (in Assington)\tabularnewline
   & \textit{{\AE}{\th}elhild}: \textit{Ailildescroft} (in Peasenhall)\tabularnewline
{*}& \textit{Aldhere}: Aldringham\tabularnewline
& \textit{Aldwulf}: \textit{Aldulveston} (in Culpho)\tabularnewline
\end{longtable}

Bad:
\setlength{\tabcolsep}{0pt}
\begin{longtable}[l]{rp{150mm}}%\RaggedRight
*& \textit{\=Aca}: Akenham\tabularnewline
*& \textit{{\AE}lffl{\=\ae}d}: Alpheton\tabularnewline
 & \textit{{\AE}lfwynn}: Aveley Hall (in Assington)\tabularnewline
 & \textit{{\AE}{\th}elhild}: \textit{Ailildescroft} (in Peasenhall)\tabularnewline
*& \textit{Aldhere}: Aldringham\tabularnewline
 & \textit{Aldwulf}: \textit{Aldulveston} (in Culpho)\tabularnewline
\end{longtable}

\end{document}
[try_longtable.log](https://github.com/latex3/latex2e/files/4469092/try_longtable.log)
[try_longtable.pdf](https://github.com/latex3/latex2e/files/4469093/try_longtable.pdf)

```

**Comment by davidcarlisle** [comment]
This (unfortunately) is a standard feature of commands with `*` forms, `\\*` (and `\tabularnewline*`) are versions of the end of row command that prevent page breaking but there can be white space between the command and the `*` .

`amsmath` uses a modified version of `\@ifnextchar` in some contexts that does not allow a newline between the command and the `*`  or `[` for an optional argument, but the general issue applies to all latex commands with a `*` form or optional argument.

**Comment by keithbriggs** [comment]
Ok, thanks very much for the explanation.   That is a pretty bad misfeature.  I need to check now whether any more of my *s are going missing!

**Comment by FrankMittelbach** [comment]
The problem is that the amsmath approach only works for something like `\\`but not for any command whose name consists of letters such as `\tabularnewline`. On a very low level in the engine TeX drops all blank spaces (including newlines) after scanning such a command name so to TeX 
```
\tabularnewline*  \taularnewline *
\tabularnewline
   *
```
are all one and the same. The only possible fix for that is making a newline character active so that it behaves like a command nd thus stops the dropping of spaces. That coud perhaps been done 35 years ago when LaTeX was originally invented.  These days trying to do that would break millions of documents in one way or the other.

**Comment by blefloch** [comment]
Crazy idea: check \inputlineno before and after doing \@ifnextchar.

**Comment by FrankMittelbach** [comment]
Woah. Not so crazy at all. For \@ifnectchar we are anyway non-expandable.

**Comment by blefloch** [comment]
\long\def\@firstofthree#1#2#3{#1}
\def\@ifstar{\expandafter\@ifstar@\expandafter{\the\inputlineno}}
\long\def\@ifstar@#1#2#3{%
  \@ifnextchar *%
    {\ifnum#1=\inputlineno
       \expandafter\@firstofthree
     \else
       \expandafter\@secondoftwo
     \fi
     {#2}{#3}}%
    {#3}%
}

**Comment by FrankMittelbach** [comment]
yes I know it could be done expandably :-) but there is no reason for doing so given that \@ifstar is not expandable. But if we go in that direction an expandable version might be needed for xparse.

**Comment by blefloch** [comment]
Caveat: You probably know it, but of course using \inputlineno to detect
new lines will not work if things have already been taken as the
argument of some other command, e.g., in an align environment.

**Comment by FrankMittelbach** [comment]
Yes, that is a caveat for sure and it applies to most amsmath environments. However, there the main command with issues is `\\`and that already disallows any spaces to avoid the problem in the first place.
