### ISSUE TITLE
Contradicting claims in array.dtx, and lttab.dtx inconsistencies

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/latex2e#319]
## Brief outline of the bug

`array.dtx` (2019/08/31 v2.4l) claims that

> *Subsection&nbsp;2.1: Handling of rules*
> There are two possible approaches to the handling of horizontal and vertical rules in tables:
>
> 1. rules can be placed into the available space without enlarging the table, or
> 2. [&hellip;]
>
> [&hellip;] while the default implementation in the LaTeX kernel implements the first concept. [&hellip;]
>
> - With standard LaTeX adding rules to a table will not affect the width or height of the table (unless double rules are used) [&hellip;]

This claim is true for (1)&nbsp;vertical rule produced by column specifier&nbsp;`|` and (2)&nbsp;horizontal rule produced by `\cline{i-j}`. **However, this claim is false for horizontal rule produced by `\hline`**.

---

The LaTeX2e kernel (`lttab.dtx` 2019/10/07 v1.1q) implements
https://github.com/latex3/latex2e/blob/59b3e833a5507d01c78171c9e42570485aea2b4d/base/lttab.dtx#L1478-L1480
**So `\hline` does occupy a vertical space of `\arrayrulewidth`**. The kernel should have said
```latex
\def\hline{%
  \noalign{\ifnum0=`}\fi
  \vskip -.5\arrayrulewidth
  \hrule \@height \arrayrulewidth
  \vskip -.5\arrayrulewidth
  \futurelet\reserved@a\@xhline}
```
So `\hline` would behavior like `|` in a more symmetrical way (`\hskip-.5\arrayrulewidth \vrule\@width\arrayrulewidth \hskip-.5\arrayrulewidth`).

But I guess any changes to the kernel are too late now. So one can only correct the documentation of `array`.

---

One final note: **`\cline` does not occupy extra space, but its back spacing is not symmetrical**! The kernel defines `\cline` as `... \leaders\hrule\@height\arrayrulewidth\hfill \cr \noalign{\vskip-\arrayrulewidth}`, but kernel should have said `\noalign{\vskip-.5\arrayrulewidth} ... \leaders\hrule\@height\arrayrulewidth\hfill \cr \noalign{\vskip-.5\arrayrulewidth}`. Again, too late to change though.

**Comment by FrankMittelbach** [comment]
As you say this is nothing that could be changed in the kernel at this point, but it should get correctedin the documentation at least.
