### ISSUE TITLE
non-ascii file name regression

### ISSUE THREAD

**Issue by edocevoli** [latex3/latex2e#32]
## Brief outline of the bug

One of my test cases breaks with the the current 2018-04-01 release.

What I have done:

1. update only the LaTeX base package (MiKTeX: `ltxbase`)
2. open a command-prompt window and then:

````
chcp 65001    
pdflatex tèst.tex
````

This gives:

````
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6655 NEXT 64-bit)
entering extended mode
! I can't find file `./t'.
<to be read again> 
                   \global 
<*> ./tè
         st.tex
Please type another input file name: 
! Emergency stop.
<to be read again> 
                   \global 
<*> ./tè
         st.tex
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.
````

Maybe this is a MiKTeX-specific Windows bug. I will do further tests on macOS and Linux.

## Minimal example showing the bug

```latex
\documentclass{article}
\begin{document}
Hallo Welt
\end{document}
```

## Log file (required) and possibly PDF file  

[texput.log](https://github.com/latex3/latex2e/files/1887203/texput.log)

**Comment by josephwright** [comment]
@aminophen  Not quite that simple ... but I have to say I'm surprised that the binaries treat the file _name_ argument at the TeX level (it's not `\input tést`, after all).

**Comment by josephwright** [comment]
Something like `pdflatex \input\detokenize{tést}\relax` works, but that's not ideal.

**Comment by aminophen** [comment]
> the binaries treat the file name argument at the TeX level

Any arguments to *tex is treated as TeX code;-) When the first token is a character, *tex treats it as if \input is prefixed; when the first token is a control sequence, \input is not prefixed.

**Comment by josephwright** [comment]
@aminophen I have to say I've always imagined the logic differently :) 'If the first char is the escape char, treat as TeX code, otherwise read as a filename'

**Comment by davidcarlisle** [comment]
one thing I had experimented with is starting with

\long\def\UTFviii@two@octets#1#2{%
\string#1\string#2}

and switching to the main definition "later" but the timing gets tricky and
making the implicit input on the commandline work like an explicit \input
also isn't as easy as one would hope.

**Comment by davidcarlisle** [comment]
@aminophen  yes I'm actually currently running some tests with ltfinal changed as

```
%    \begin{macrocode}
\edef\inputencodingname{utf8}%
\input{utf8.def}
\let\UTFviii@two@octets@@\UTFviii@two@octets
\long\def\UTFviii@two@octets#1#2{\string#1\string#2}
\everyjob\expandafter{\the\everyjob
\let\UTFviii@two@octets\UTFviii@two@octets@@
}
\let\@inpenc@test\@undefined
\let\saved@space@catcode\@undefined
%    \end{macrocode}

```

would need  the longer cases as well, not just the two byte of course.  delaying the catcode activation until everyjob would work on the commandline but if we can make it work without that it may give a path to accepting utf8 filenames more generally in the document 9which did not work in previous releases after inputenc was loaded)

**Comment by aminophen** [comment]
https://github.com/latex3/latex2e/commit/724013b6c9fe3f3ac51ac3ac962da80254d3a746 works as expected for pdfLaTeX; I commited a support for that change in pLaTeX https://github.com/texjporg/platex/commit/8b6c518ac49d44fddf5435827b8f4fe744ef2f0b and it’s ok on both pLaTeX and upLaTeX. I’ll upload the new version of pLaTeX, when LaTeX is ready.
