### ISSUE TITLE
Rotation with 'origin=c' picks wrong origin

### ISSUE THREAD

**Issue by dpthurst** [latex3/latex2e#321]
## Brief outline of the bug
In some circumstance, specifying 'origin=c' to \rotatebox appears to pick a center of rotation that is outside the box being rotated.

In the example below, note that the frame does not tightly fit around the rotated picture when [origin=c] is specified. If the origin is left unspecified, the rotation works fine.

I have not pinned down exactly when the bug happens. I also tried it with the most recent copy of the graphics bundle.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{graphicx}

\begin{document}
\framebox{\rule{50mm}{75mm}}

\framebox{\rotatebox[origin=c]{80}{\rule{50mm}{75mm}}}

\framebox{\rotatebox{80}{\rule{50mm}{75mm}}}
\end{document}
```

## Log file (required) and possibly PDF file  
[latex-bug.log](https://github.com/latex3/latex2e/files/4470833/latex-bug.log)
[latex-bug.pdf](https://github.com/latex3/latex2e/files/4470836/latex-bug.pdf)

**Comment by davidcarlisle** [comment]
This is actually as designed (I think). Rotation is slightly tricky as the reference point of a box has to be at the left edge, and to keep th einterface simple the resulting box is responsible for positioning the rotated object so can't simply bind tightly to it. So `\rotatebox` rotates in place  and then if necessary translates the reference point of the resulting box to its left edge,

Here as the box is tall, if you rotate it about the centre then the centre stays at the same height above the baseline so there is white space below the visible box and the baseline. this positioning though is arranged by returning a box of the height shown by your \framebox. If it returned a box that was tightly bound to the rotated rectangle the rotated box would "drop" on to the baseline.

arguably the resulting box could have a negative depth here  but `\framebox` would not show that, as you will see in this example even with no rotation involved

```
\documentclass{article}
\usepackage{graphicx}

\begin{document}

x\framebox{\rule{20mm}{75mm}}x
x\framebox{\rule[50mm]{20mm}{75mm}}x
x\framebox{\rule[50mm]{20mm}{25mm}}x
x\framebox{\rule[-50mm]{20mm}{25mm}}x


\end{document}
```

**Comment by blefloch** [comment]
David, I think that it's true that framebox does not see when a box has
negative depth, but your example with rules doesn't show that.  Indeed,
LaTeX's \rule seems to produce zero-depth boxes, e.g.

\hbox{%
  \rule{20pt}{75pt}%
  \rule[50pt]{20pt}{75pt}%
  \tracingall\showlists
}

shows

\hbox(75.0+0.0)x20.0
.\rule(75.0+0.0)x20.0
\hbox(125.0+0.0)x20.0
.\rule(125.0+-50.0)x20.0

which clearly says that the rule has negative depth but it is enclosed
in a zero-depth hbox.  Maybe that's a misfeature in LaTeX's \rule, by
the way.

**Comment by davidcarlisle** [comment]
@blefloch  oh you are right, basically due to the nature of teh `\vrule` primitive as you get the same from this plain tex

```
\hbox{\vrule width 10pt height 150pt depth -50pt}\tracingall\showlists}
\bye
```

the rule has negative depth but the resulting hbox has depth 0.

**Comment by dpthurst** [comment]
Ah! David, I agree that this is what's happening. Then I think there's a
documentation issue: grfguide is not quite explicit what "rotating
around" means.

In practice, what I wanted to do was include a figure with
includegraphics, rotated 270 degrees, but sitting in the usual place
with standard depth. This seems awkward with the available arguments
to \includegraphics:

\includegraphics[angle=270]{fig}

leaves the figure dangling below the baseline, while

\includegraphics[origin=c,angle=270]{fig}

leaves the figure at an odd height. So this behaviour for \rotatebox
gives unfortunate behaviour for \includegraphics.

In any case, the bug should be closed.

--Dylan Thurston

**Comment by davidcarlisle** [comment]
@dpthurst   I guess this is the result you want, even if the markup's a bit more verbose than would be desirable

```
\documentclass{article}

\usepackage{graphicx}

\begin{document}

aaa\raisebox{\depth}{\includegraphics[angle=270]{example-image}}

\end{document}
```

**Comment by FrankMittelbach** [comment]
I take the liberty ...
