### ISSUE TITLE
Bug report: docs are missing stuff

### ISSUE THREAD

**Issue by ORESoftware** [latex3/latex2e#324]
I am trying to figure out how to install this on Linux (you know, the thing we use).

I saw this:
https://www.latex-project.org/get/#a-note-on-git-pull-requests

I saw this:
https://www.tug.org/texlive/

I saw this:
https://www.tug.org/texlive/quickinstall.html

the last link is most promising..but after looking at it for 15 seconds I realized I was stuck.

Can we not clone this repo, and then just `make && make install`? If so, why doesn't the readme.md file say that?

I just want to install and use this :/

**Comment by davidcarlisle** [comment]
You need to have obtained a tex distribution from elsewhere we give pointers on how to obtain this for the more popular operating systems at

https://www.latex-project.org/get/

The git source of latex is really only of interest if you want to work on latex development it is not intended as a source for end user installations.

> Can we not clone this repo, and then just make && make install? 

No latex is written in tex and is cross platform, many platforms do not have make, and if you obtain tex then you will get latex at the same time, so you should not need to install the latex sources from here.

**Comment by ORESoftware** [comment]
ty, i don't fully understand, but processing it

**Comment by FrankMittelbach** [comment]
As an analogy, think of this of this repository  as something containing just the C-source code of some program (say emacs) nothing else. With that you can't do anything if you don't have an operating system and an environment containing make, a C compiler etc. If you do then you can take the repository and compile it.  LaTeX = C program,  make/C-compiler, etc = TeX distribution such as TeXLive (l3build = make, by the way in the analogy)

Such a "TeX Live distribution" is like your Linux  and it comes with  a ready prepared LaTeX for use (= emacs binary) so you normally don't need the sources here and it has a package manager that runs the equiv of make etc to compile the LateX sources found in this repository for you in the background if they are updated and packaged.

These here are the unpackaged sources and only of interested to a few people directly working in development.

**Comment by blefloch** [comment]
> These here are the unpackaged sources and only of interested to a few
> people directly working in development.

Probably worth saying explicitly on that page of the website.
