### ISSUE TITLE
color should store color values of named colors in a backend independent way

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#325]
## Brief outline of the enhancement

the three main color packages, `color` (C), `xcolor`  (X) and `l3color` (L) store color values of names colors in internal commands. All in a different way:

~~~~
### rgb

pdftex/luatex
\\color@blueC=1 1 0 rg 1 1 0 RG
\\color@blueX=\xcolor@ {}{1 1 0 rg 1 1 0 RG}{rgb}{1,1,0}
\l__color_named_blueL_tl=rgb 1.0 1.0 0.0

xdvipdfmx/dvips
\\color@blueC=rgb 1 1 0
\\color@blueX=\xcolor@ {}{rgb 1 1 0}{rgb}{1,1,0}.
\l__color_named_blueL_tl=rgb 1.0 1.0 0.0


### cmyk

pdftex/luatex
\\color@blueC=1 1 0 0 k 1 1 0 0 K
\\color@blueX=\xcolor@ {}{1 1 0 0 k 1 1 0 0 K}{cmyk}{1,1,0,0}
\l__color_named_blueL_tl=cmyk 1.0 1.0 0.0 0.0

xdvipdfmx/dvips
\\color@blueC=cmyk 1 1 0 0
\\color@blueX=\xcolor@ {}{cmyk 1 1 0 0}{cmyk}{1,1,0,0}
\l__color_named_blueL_tl=cmyk 1.0 1.0 0.0 0.0
~~~~

The main problem here is the output of the color package: as it is backend dependant it is rather awkward to extract the values to add the color values e.g. to a link border. And so hyperref for example doesn't allow named colors with `color`, but requests `xcolor`. 

It would be easier if there were for every color an additional command e.g. a `\\colorvaluesof@blueC ` command which would follow either the xcolor or the l3color syntax (prefered ...).

**Comment by josephwright** [comment]
Rather than handle in `color`, the latest plan is to hook into `l3color`, rounding out features in the latter to support exporting color in different formats. This should be covered by #342, plus of course moving `l3color` to `l3kernel`.

**Comment by josephwright** [comment]
We are not going to change `color.sty` here, so closing.
