### ISSUE TITLE
\verb uses spaces as delimiters

### ISSUE THREAD

**Issue by djasnd** [latex3/latex2e#327]
## Brief outline of the bug
This has been around a long time, so you probably don't want to change it, but it is too surprising to go unreported. A space between a \verb command and the intended delimiter character is taken to be the delimiter.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\begin{document}
\verb |~|
\end{document}
```

## Log file (required) and possibly PDF file  

[verb-space-bug.log](https://github.com/latex3/latex2e/files/4515508/verb-space-bug.log)

**Comment by eg9** [comment]
Thinking a bit deeper, the behavior makes sense: the space stops the scanning for a control sequence name, but it's not yet tokenized. After absorbing `\verb`, TeX knows it has no arguments, so it expands it and at this point the category code of the space changes. Entering the “skipping spaces” state does nothing and the first token found is a category code 12 space.

It's just surprising and the manual should be explicit in saying that a space after `\verb` is not allowed (or that it is, but…).

**Comment by FrankMittelbach** [comment]
Either that or we actually look for it. It is a little weird the `\verb |x| foo` actually works and drops both spaces so you get `|x|foo`in the output. In other words space as a delimiter does work but it is pretty weird and hard to get a real space after such a verb.

**Comment by FrankMittelbach** [comment]
What I mean: you can get a space there by putting 2 spaces (one as the delimiter and one being a real space) but this is "hard/weird" so I doubt that anybody ever used space as a delimiter for real.

**Comment by wspr** [comment]
OTOH is there a plausible scenario in which a user might have intentionally written something weird like

    foo \verb !bar !

and expected it to typeset ‘foo \texttt{!bar}!’ ? I hope not but now that I know about it I guess I *might* actually be tempted to delimit control words with spaces like this:

    \verb|\foo| vs \verb \foo  hello

I think I’ve just convinced myself that we can’t change the behaviour now.

**Comment by FrankMittelbach** [comment]
> OTOH is there a plausible scenario in which a user might have intentionally written something weird like foo \verb !bar ! and expected it to typeset ‘foo \texttt{!bar}!’ ? 

I would reject that as a strong misuse and obfuscation :-) So I would not be toooo bothered if we break that.
Much more likely in my option is `\verb* !bar !` with the hope of getting `bar<visible space>`
but instead getting "bar !" silently and not noticing.

>I hope not but now that I know about it I guess I *might* actually be tempted to delimit control words with spaces like this: \verb|\foo| vs \verb \foo hello I think I’ve just convinced myself that we can’t change the behaviour now.

would you? in that case you would get `\foohello`unless you put two spaces in after \foo, so again I doubt that has been used. So all in all I don't think there is a serious obstacle fixing it, e.g.
```
\makeatletter
\let\@@sverb\@sverb
\def\@sverb#1{\if\noexpand#1 \expandafter\@sverb\else\@@sverb{#1}\fi}
\makeatother
```
or similar

**Comment by wspr** [comment]
I did type the two spaces :) But no, I’m happy to follow your lead here. If you seriously think no-one has used this feature enough to keep the behaviour I do agree it would make sense to change the behaviour.

**Comment by FrankMittelbach** [comment]
given millions of users out there, who knows, but it could be reasonably called a bug and all possible scenarios are so strange. We could of course
 - generate a warning or even
 - generate an error
but in my opinion is overdoing misfeature-compatibility.

**Comment by wspr** [comment]
I agree, I think once a decision for change is made it should be embraced and the code not encumbered forever with warnings of edge cases and so on. If the change is included in the rollback code that’s enough to sort out historical documents that abuse the mis-feature.

**Comment by Richardk2n** [comment]
As a PhD-Student who has to deal with the latex files of our chair not compiling anymore after an update that brought us this change, I can tell you the assumption, that nobody uses this feature is very wrong. For us, it is indeed the default way, as a space character is very easy to type compared to anything else. Furthermore, reading the documentation from TeX user group `The single-character delimiter char surrounds literal-text—it must be the same character before and after. No spaces come between \verb or \verb* and char, or between char and literal-text, or between literal-text and the second occurrence of char` shows that the original report above uses the command wrong. This phrasing, highlighting that there may not be a space before char, that is only necessary if space is an allowed delimiter, can be found in latex documentation going back to at least 1995. The space was likely always an allowed delimiter on purpose and I cannot understand how that can be considered a bug. I cannot fathom how one can remove a feature, that is documented, hurts nobody, works as intended and is older than me with so little thought.

**Comment by josephwright** [comment]
@Richardk2n  Lamport's books says 

> ... you can use any character that does not appear in the argument except a space, a letter, or a `*`.

thus using a space as a delimiter was a bug.

**Comment by u-fischer** [comment]
@Richardk2n sorry but `No spaces come between \verb or \verb* and char` clearly indicates that *space*  and *char*  are viewed as different things.  

The LaTeX manual from Leslie Lamport explicitly states (emphazing by me):

> ... Instead of +  or 2, you can use any character that does not appear in the argument except **a space**, a letter, or a *

And in lshort.pdf you can find

> Use any character except letters, * or space.

**Comment by car222222** [comment]
Probably these days "character" should be clarified to say more precisely "printable ASCII character".

**Comment by u-fischer** [comment]
> Probably these days "character" should be clarified to say more precisely "printable ASCII character".

well with an unicode engine this here works fine (and as space is allowed between the command and the delimiter, the restriction "no letters" is actually gone).

~~~~
\documentclass{article}

\begin{document}
\verb ü\sectionü

\verb🦆\section🦆
\end{document}
~~~~

**Comment by car222222** [comment]
So should it now say "any character (even unprintable ones) except 'ascii-space' and 'ascii-*' " ?

**Comment by davidcarlisle** [comment]
> So should it now say "any character (even unprintable ones) except 'ascii-space' and 'ascii-*' " ?

any character _token_  

with xe/lua latex, 

`\verb ü\sectionü` works, `\verb ü\sectionü` also works for some definition of work, but may not produce what you expect (unless you expect what it produces)

**Comment by car222222** [comment]
But most users have no idea if they are using xe/lua/hi/low/... tex.

**Comment by car222222** [comment]
Let alone the duff fence between a character and a token.
