### ISSUE TITLE
filecontents in index of ltclass

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#329]
Claudio Beccari reports:

The index of ltclass.pdf lists several class environments, but
filecontents is missing.

Since there is no ltclass.pdf distributed any more, I can't readily check, sorry ...

**Comment by davidcarlisle** [comment]
ltclass.dtx is a component of source2e.tex and I don't think we ever distributed the pdfs of those separately.

However you are correct there is something wrong with the docstrip guards: looking at page  569 of source2e.pdf  comments and changes entries that  should be typeset are appearing in the code block.

we'll sort it out....

**Comment by mrpiggi** [comment]
There's also a change note within the code block in `fontdef.dtx`
https://github.com/latex3/latex2e/blob/5ed6ceb27ae589066fcb671a678aed6bba9a4e07/base/fontdef.dtx#L569

**Comment by kberry** [comment]
ltclass.pdf was distributed in TL'18 and TL'19. And it seems like quite a useful document, IMHO.

**Comment by davidcarlisle** [comment]
On Fri, 24 Apr 2020 at 22:15, kberry <notifications@github.com> wrote:

> ltclass.pdf was distributed in TL'18 and TL'19. And it seems like quite a
> useful document, IMHO.
>

So it was, sorry (at least it was in tl2018) I have tl2016-tl2020 here and
it's only in tl2018, although I may not have the final updated version of
all the releases so I will not argue with you about tl2019:-)

That's very weird, I suspect by mistake, although another team members may
recall.

ltclass.dtx doesn't contain self standing code it is just one part of
source2e split into chunks mostly relating to ease of email communication
in the 1990s so while each of the parts can be processed independently and
some (like that one) have an almost self standing introduction, it doesn't
really make sense as a self standing document. especially if we don't
distribute the other sections of source2e as separate documents.

David

**Comment by FrankMittelbach** [comment]
> ltclass.pdf was distributed in TL'18 and TL'19. And it seems like quite a useful document, IMHO.

It was clearly distributed by mistake as an individual file (it is and was as David said distributed as part of source2e.pdf where it really belongs). I think I remember that at one time l3build was not cleaning out the source directory  from stray files when generating the ctan distribution so if somebody had generated a pdf from some .dtx for testing or even wrote some test.tex -> test.pdf it ended up in the ctan zip file. I guess that is how it ended up there. But that is speculation.

We could, of course, easily  distribute all the individual pdfs for each .dtx in addition to source2e.pdf that contains them all, but other than a lot of duplication there doesn't seem to be much gain as code is somewhat randomly distributed across them and source2e with its full index is a much better resource than any of the singe ones.
