### ISSUE TITLE
Space before date optional argument to \ProvidesPackage causes error

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#33]
## Brief outline of the bug

As reported on the TeX Live list, with the 2018-04-01 release of the kernel there is a low-level error when a `.sty` file (or similar) has a space between the `[` and date in the optional argument to `\ProvidesPackage`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\begin{filecontents}{test.sty}
\ProvidesPackage{test}%
  [ 2018/04/08 v0.0 Test Package. ]
\end{filecontents}
\documentclass{article}
\usepackage{test}
\begin{document}
Hello, World!
\end{document}
\begin{document}
```

## Log file (required) and possibly PDF file  
[ex2.log](https://github.com/latex3/latex2e/files/1887207/ex2.log)

**Comment by eg9** [comment]
> On 8 Apr 2018, at 11:21 , Joseph Wright <notifications@github.com> wrote:
> 
> Suggested code change:
> 
> \makeatletter
> \def\@ifl@t@r#1#2{%
> 
>   
> \ifnum\expandafter\@parse@version\expandafter#1//00\@nil<%
> 
>         
> \expandafter\@parse@version\expandafter#2//00\@nil
> 
>     
> \expandafter\@secondoftwo
> 
>   
> \else
> 
>     
> \expandafter\@firstoftwo
> 
>   
> \fi
> }
> 
> \def\@parse@version#1{\@parse@version@0#1\@nil
> }
> 
> \def\@parse@version@#1/#2/#3#4#5\@nil{%
> \@parse@version@dash#1-#2-#3#4\@nil
> 
> }
> 
> \makeatother

Agreed, this can catch weird errors when [ in \ProvidesPackage is at the end of a line by itself, for instance.

Ciao
Enrico

**Comment by josephwright** [comment]
I'd change this but `latexrelease` makes life tricky: one for @davidcarlisle  I think ;)

**Comment by davidcarlisle** [comment]
@josephwright  a simper change with less impact of latexrelease.sty would be
```

\def\@ifl@t@r#1#2{%
  \ifnum\expandafter\@parse@version@#1//00\@nil<%
        \expandafter\@parse@version@#2//00\@nil
    \expandafter\@secondoftwo
  \else
    \expandafter\@firstoftwo
  \fi}
\def\@parse@version@#1{\@parse@version0#1}
```

**Comment by josephwright** [comment]
@davidcarlisle  Sure: I was just looking for a 'quick fix'.
