### ISSUE TITLE
lppl.tex / lppl.pdf no longer distributed

### ISSUE THREAD

**Issue by schlcht** [latex3/latex2e#330]
I've already reported this on the [TL list](https://tug.org/pipermail/tex-live/2020-April/045474.html), and Karl advised me to suggest it here.

The LPPL is no longer included in tex or pdf format in TL anymore. Is this intentional? `lppl.pdf` used to reside in the `doc` tree, `lppl.tex` in the `tex` tree (until 2019, when it was moved to `doc`, too). 
This made sense to me, as you would want to have the _L_PPL nicely typeset by LaTeX, too, wouldn't you, while `lppl.tex` being available in `tex/` allowed including it in manuals, which, according to [latex-project.org](https://www.latex-project.org/lppl/), "authors of LPPL software are encouraged" to do.

Sorry if I should have missed any previous discussion about this.

**Comment by FrankMittelbach** [comment]
I think this is a mistake in our generation scripts for the distribution. At least I don't think we decided to deliberately drop it even though we aren't any more really promoting to put a longish unreadbale license text into a manual (at least I don't). But having it available if people want to is something we should do.

**Comment by josephwright** [comment]
Hopefully this is a one-line fix: I'll do a build to check
