### ISSUE TITLE
\capitalring, etc with xelatex, lualatex unicode

### ISSUE THREAD

**Issue by bdtc** [latex3/latex2e#332]
When using xelatex or lualatex, \capitalring and similar macros fail if using hyperref, but succeed if hyperref is not loaded.

`
% Works with pdflatex, with or without hyperref.

% Works with xelatex or lualatex without hyperref.

% Fails with xelatex or lualatex with hyperref.

\documentclass{article}

% \usepackage{hyperref}

\begin{document}

\capitalcedilla A

\capitalogonek A

\capitalgrave A

\capitalacute A

\capitalcircumflex A

\capitaltilde A

\capitaldieresis A

\capitalhungarumlaut A

\capitalring A

\capitalcaron A

\capitalbreve A

\capitalmacron A

\capitaldotaccent A

\end{document}
`

**Comment by u-fischer** [comment]
> Would it be a good idea to remove PU and use TU throughout?

No. You only need to look into puenc.def. puenc translates the commands into the octal representation needed by pdf strings, not it something useful for typesetting
For example:

~~~~
\DeclareTextCommand{\textasciiacute}{PU}{\80\264}% U+00B4
~~~~

**Comment by car222222** [comment]
I see, so PU is something totally different, nothing at all related to Unicode characters in fonts.  
Even more reason to remove it and use a better method of translating LICRs into other formats such as octal representations.

**Comment by u-fischer** [comment]
> I see, so PU is something totally different, nothing at all related to Unicode characters in fonts.
> Even more reason to remove it and use a better method of translating LICRs into other formats such as octal representations.

T1- or OMS-encoding aren't related to unicode characters either. So perhaps we should remove them too? Beside this: the numbers are related to a font. At the end they produce a bookmark which is shown on my screen with the help of a font. They are as real and font related as is a `&#x20AC;` in a html file or some glyph slot number in a .dvi or  a pdf stream.

**Comment by FrankMittelbach** [comment]
Fixed. It will show up with the next release in fall. But the capital accents will only work in unicode engines if the accent is suported by the current font, e.g., in LM `\capitalcedilla C`  will come out right, but `\capitalcedilla A` in your example will complain about a missing combining accent as  that doesn't exist in the font and a precomposed character doesn't exist either.

This is where the engines behave differently.
