### ISSUE TITLE
integrate l3docstrip module support in docstrip

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#337]
## Brief outline of the enhancement

l3docstrip and docstrip are nearly identical. The only difference is that l3docstrip can deal with the "module" convention, i.e.
```
%<@@=module>
```

While this is only useful in expl3 code it is nevertheless pointless have two extraction programs when one can do. So the proposal is to integrate that support into `docstrip.tex` and promote to use that always (with l3docstrip kept available as a trial shell calling dostrip).

**Comment by JohannesBraams** [comment]
There are two parts to this:
1 first integrate the <@@=...> functionality into docstrip.dtx; test and verify it
2 strip l3docstrip to just load the new docstrip.tex

**Comment by FrankMittelbach** [comment]
- 2a test if format is 2020/10/01 or later
 - 2b if not, keep what is currently added in l3docstrip
