### ISSUE TITLE
filecontents: more meaningful warning in case of existing file?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#338]
## Brief outline of the enhancement
Currently, when the `filecontents` environment is used with an already existing file, LaTeX displays the following message:
```
LaTeX Warning: File `...' already exists on the system.
               Not generating it from this source.
```
Now, if the user wants to overwrite the file, he will have to look for the relevant documentation which is currently not easy to find.

It would be nice for the above warning to be more meaningful, with something like:
```
LaTeX Warning: File `...' already exists on the system.
               Not generating it from this source. If you want it to be overwritten,
               pass the `overwrite' option to the `filecontents' environment.
```
## Minimal example showing the current behaviour

Compile the following file twice.

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{filecontents}{\jobname.txt}
Foo
\end{filecontents}
\begin{document}
Bar
\end{document}
```

**Comment by mrpiggi** [comment]
Would it be possible to add an option to overwrite only files, which were previously created by the `filecontents` environment?

**Comment by wspr** [comment]
How would filecontents know whether it created a previous version of a file with the same name?

**Comment by FrankMittelbach** [comment]
I guess technically it would be possible (given that TeX is turing complete :-) ) one could for example record those in the aux file but in all honesty I think it is over the top to make such attempts and complicate the code and processing. Is there really much gain?

**Comment by wspr** [comment]
Well, to answer my own question, by default there is usually a comment in the first line of the file that says “created with filecontents”, although you can turn that off.

It’s not out of the question that as long as the “magic comment” is being written that you could optionally read in a pre-existing file and check for the magic comment...

**Comment by FrankMittelbach** [comment]
Am 25.05.20 um 14:57 schrieb Will Robertson:
> Well, to answer my own question, by default there is usually a comment 
> in the first line of the file that says “created with filecontents”, 
> although you can turn that off.

exactly which is why you can't use that (the * form deliberately doesn't 
add anything to the file, so no way to "mark" it). An .aux file record 
would perhaps be feasible, but as I said I don't think the gain really 
fits the complications. By default you don't overwrite and if you do you 
need to deliberately decide (using overwrite and maybe nosearch) and 
imho that is enough.

**Comment by FrankMittelbach** [comment]
@dbitouze coming back to the original issue... It is documented at length in usrguide (except that this isn't yet online but will be in the fall release and soon in the -dev release). 

I'm a bit reluctant to start lengthening warning and error messages as that isn't the LaTeX way in other places either  and it is costly even thoughwe have more space. Furthermore, it is difficult to be accurate in a one para message (like why not explain "nosearch" too etc). So I'm leaning towards keeping it the way it isgiven that the documentation in usrguide will appear soon.

**Comment by mrpiggi** [comment]
I actually had the "magic comment" in mind but did not consider, that it is also possible to generate files without the preamble. 

In principle, I would find it convenient to be able to use the environment to overwrite files that were previously created with it without receiving a warning. But this is not important or urgent at all.

**Comment by FrankMittelbach** [comment]
> In principle, I would find it convenient to be able to use the environment to overwrite files that were previously created with it without receiving a warning. But this is not important or urgent at all.

what's wrong with `overwrite` or `overwrite,nosearch` then? The danger that you have such a file in your current directory that was generated differently? if so a magic string check wouldn't help as it would be likely that the other instance was also via filecontents and if not automatic overwrites should only happen if you explicitly ask for it (ensuring yourself that it is safe)

**Comment by mrpiggi** [comment]
I only had the case in mind that the environment can also be used by classes or packages and could accidentally overwrite user files. But the problem affects pretty much all output streams.
