### ISSUE TITLE
[Document] A Strayed Parenthesis

### ISSUE THREAD

**Issue by cmplstofB** [latex3/latex2e#343]
Hello.
I found a small typo in `ltclass.dtx`’s document.
There is a strayed parenthesis at line 1820 of it:

https://github.com/latex3/latex2e/blob/59b3e833a5507d01c78171c9e42570485aea2b4d/base/ltclass.dtx#L1820

I don’t belong to LaTeX Team, so I open an issue here, sorry for bothering you with a small issue.

**Comment by FrankMittelbach** [comment]
thanks, but that is already corrected in the development version. The master branch always shows what is  on ctan and will not change before the fall release.

**Comment by cmplstofB** [comment]
I, see. Thank you.
