### ISSUE TITLE
empty closing \part cannot be labelled 

### ISSUE THREAD

**Issue by dymky** [latex3/latex2e#346]
## Brief outline of the bug

During writing it can happen that the source ends with an empty labelled \part-definition. Then it appears in the table of contents, but (preceding) references behave as if the label is not defined.

It can be confusing and wastes time.

Adding even "~" to the last part solves the problem.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!


\documentclass{book}

\begin{document}

\ref{efg}

\part{abc}\label{efg}

\end{document}

```

## Log file (required) and possibly PDF file  

[aaa.log](https://github.com/latex3/latex2e/files/4823239/aaa.log)

**Comment by u-fischer** [comment]
Adding `~` will create an additional page. The correct way to add the label is to put it into the argument. Then the reference will also point to the right page. 

~~~~
\documentclass{book}

\begin{document}

\ref{efg}

\part{abc\label{efg}}

\end{document}
~~~~

**Comment by dymky** [comment]
I see thank you!
Does this mean I've been labelling things wrongly all the time? :)

Let me just mention that \section{} behaves differently: putting it in the place of "\part" in my original example makes everything behave as expected.

I let the developers decide whether this is something that needs to be fixed; as for me, the answer by _u-fischer_ is fully satisfactory.

**Comment by u-fischer** [comment]
section doesn't write its title on a page of its own and doesn't issue a \clearpage. So the label has a chance to stay near it.

**Comment by dymky** [comment]
Fine, then let me close the issue.

Thank you very much, and sorry for the false report!

**Comment by FrankMittelbach** [comment]
It is not quite a false report. The LaTeX manual by Lamport suggests that you put the \label inside the heading argument to attach it firmly to the heading (or caption) but like you many people including me prefer putting it after the heading because that is more readable in the source. With most headings this works well, but \part is special as it gets on a page by its own, so putting it after \part and then doing \pageref would get you the wrong page reference (but the right part number) and if nothing follows the label gets dropped.

Still, there is an issue that a totally empty page at the very end only containing a \label gets dropped because \label is actually executed in \shipout and there is no further page to ship out. That is perhaps  somewhat unfortunate but nothing that can be easily fixed (and one can argue it is incorrect input).

**Comment by u-fischer** [comment]
@FrankMittelbach  the LaTeX manual (1994, for 2e) actually only says in 4.2 Cross-References

> A \label can appear in the argument of a sectioning or \caption command but in no other moving argument

And all examples put the \label behind the sectioning or \caption command.

**Comment by FrankMittelbach** [comment]
Then it is even vaguer than I remembered, but anyway, to be correct it has to be inside for \part if you want a pge reference while for other headings it is usually fine to be placed after. But there is really no way to detect that there are dangling \write commands after the last page.

**Comment by dymky** [comment]
I see. I am using my own macros for starting a part/chapter/section/…, so a global correction of this label placement issue was rather straightforward. I just never knew that it had to be put inside.

**Comment by mrpiggi** [comment]
Ideally, the mechanism would recognize whether the last label set refers to a section or caption. And if  `\label` was not used within the corresponding argument like `\caption{...\label{...}}`, a warning could then be issued.  But this is certainly not easy to implement.

**Comment by FrankMittelbach** [comment]
> Ideally, the mechanism would recognize whether the last label set refers to a section or caption. And if `\label` was not used within the corresponding argument like `\caption{...\label{...}}`, a warning could then be issued. But this is certainly not easy to implement.

fear not. It is perfectly permissable to go
```
\part{Foo}
In\label{sec:foo} we  .... \newpage  ... On page \pageref{sec:foo} ...
```
and then the label after the the heading is valid. And it would be even valid if directly after the heading. Besides, it is a very very common and natural place to put it and I wouldn't want millions of documents suddenly produce unnecessary warnings env if the detection would be possible.

**Comment by mrpiggi** [comment]
You're right, it would obviously have to be checked whether there is only white space between the sectioning command and the label. And of course, this should be an opt-in feature. Never mind, I was just curious...
