### ISSUE TITLE
No trace of LaTeX format version apart date of dump in log

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#35]
## Brief outline of the bug

When I compile minimal document and check the log I can not tell which version of LaTeX format is in use. I am mentioning this in relation to recent April 2018 release.

```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex 2018.4.9)  10 APR 2018 15:54
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**\input temp.tex
(./temp.tex (/usr/local/texlive/2018/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2017/10/12 v1.0d Bug-classification
) (/usr/local/texlive/2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
...
```

I get information about packages such as latexbug which I added as per instructions, and article class. The ``preloaded format=pdflatex 2018.4.9`` only tells me the format was built yesterday.

I (=lambda user of LaTeX posting a question on tex.sx and asked to provided the log) have no way of knowing that I am using the April 2018 version of LaTeX, in particular regarding its incorporation of UTF8 as default.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass{article}

% nothing here

\begin{document}

  % nothing here either here
  
\end{document}
```

## Log file (required) and possibly PDF file  

[temp.log](https://github.com/latex3/latex2e/files/1894915/temp.log)

**Comment by josephwright** [comment]
We've changed nothing here in that regard, and for me the usual line gets printed
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/W32TeX) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2018-04-01> patch level 2
```
Which OS are you using?

**Comment by jfbu** [comment]
I am on MacOS 10.9.5. The binaries are built on my locale using  an rsync'ed TeXLive source. I will check with binaries from darwin-legacy.

**Comment by davidcarlisle** [comment]
If you use

pdflatex test

then it is logged but if you use

pdflatex \input test

then the banner comes to the terminal but not the log, I see the same in
(for example ) texlive 2016

David

**Comment by jfbu** [comment]
indeed, this is compiled from Emacs/AUCTeX buffer which does `\input`

**Comment by jfbu** [comment]
yes, as David says, from command line it is ok

```
s$ pdflatex temp.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./temp.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 26 language(s) loaded.
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/inputenc.sty) (./temp.aux)
[1{/usr/local/texlive/2018/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./temp.aux) )</usr/local/texlive/2018/texmf-dist/fonts/type1/public/amsfonts/c
m/cmr10.pfb>
Output written on temp.pdf (1 page, 9975 bytes).
Transcript written on temp.log.
```

with darwinlegacy this time binaries and rebuilt formats (not that it should change anything as far as I know)

**Comment by davidcarlisle** [comment]
I think this is just a feature of tex that if you use commands on the
commandline then the `\everyjob` banner is executed before tex has frozen
\jobname so the typeout just goes to the terminal as the log is not open.

**Comment by jfbu** [comment]
Sorry for noise, indeed it was already like this in TL2017. When compiling from command line, I got then the

```
LaTeX2e <2017-04-15>
```

line both on Terminal and in log

But from Emacs/AUCTeX buffer the LaTeX2e stamp is only in process output, it is not in log file.

Never had noticed that...

**Comment by davidcarlisle** [comment]
Feature of the tex engine if making messages before \jobname is fixed, This has always been this way.
