### ISSUE TITLE
Undefined control sequence in log file: indentation vs visibility

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#351]
Long macros names may not be entirely visible in log files. This is a long-standing fact but its frequency is likely to increase with `expl3`: its `_` separator encouraging more meaningful macros names but, as a consequence, also quite long macros names. I stumbled upon it just now:
```
! Undefined control sequence.
\key code > studentreport/institute/unknown ...:N 
                                                  \g__studentreport_institut...
l.129 }
```
Maybe indentation (alignment with the previous line) is not as crucial as visibility of the undefined control sequence.

**Comment by PhelypeOleinik** [comment]
The `! Undefined control sequence` error is produced by TeX, and the alignment is part of TeX's error context routine.  I'm afraid there's not much that can be done about that.

Note that LuaTeX's error reporting is slightly different and might provide a bit more context.

**Comment by dbitouze** [comment]
>The` ! Undefined control sequence` error is produced by TeX, and the alignment is part of TeX's error context routine. I'm afraid there's not much that can be done about that.

Too bad...

> Note that LuaTeX's error reporting is slightly different and might provide a bit more context.

I didn't notice any difference.

**Comment by PhelypeOleinik** [comment]
> I didn't notice any difference.

It depends on the situation.  It often does: we have a lot of LuaTeX specific test logs because of small differences in error reporting.

**Comment by blefloch** [comment]
While Phelype is right about the general fact that this error is beyond our
reach, I'm surprised by this specific error: "\key code ..." functions are
produced by l3keys internals, and it is surprising to get an undefined control
sequence error rather than an unknown key error or some such.

Could you provide some more context as to how this error arises?  l3keys could
perhaps catch it and give a more meaningful error.

**Comment by PhelypeOleinik** [comment]
@blefloch I believe the code Denis had is something like:
```latex
\ExplSyntaxOn
\keys_define:nn { studentreport }
  {
    , institute .choice:
    , institute/unknown .code:n =
        { \some_undefined_macro:N \g__studentreport_institute_tl }
  }
\keys_set:nn { studentreport } {
  institute = some~institute 
}
```
which errors in the same way with `\some_undefined_macro:N` being undefined, but only the final `:N` is printed:
```none
! Undefined control sequence.
\key code > studentreport/institute/unknown ...:N 
                                                  \g__studentreport_institut...
l.11 }
      
?
```
And there's not much `l3keys` can do about that here.

On the other hand, we could implement something like what you've done for grabbing a delimited argument with `xparse`: define a temporary `\key institute/unknown` macro, which would be a copy of `\key code > studentreport/institute/unknown`, then the error message would be (very) slightly better...

**Comment by davidcarlisle** [comment]
It's true that l3keys can't do much here but the cut off is a user-settable value on the commandline or texmf.cnf


```
$ error_line=100 half_error_line=80 pdflatex undef2
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./undef2.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-18>
! Undefined control sequence.
\key code > studentreport/institute/unknown #1->\some_undefined_macro:N 
                                                                        \g__stu
dentreport_institu...
l.10 }
      
? 
```

**Comment by dbitouze** [comment]
@blefloch @PhelypeOleinik essentially got the point: I mixed up `etoolbox`'s `\booltrue` and `expl3`'s `\bool_gset_true:N` in a vain `\bool_true:N`:

```latex
  institute / unknown .code:n ={%
    \tl_gset:Nn \g_@@_institute_name_tl {#1}
    \bool_true:N \g_@@_institute_name_displayed_bool
  },%
```
As you noticed, the thrown error:
```
! Undefined control sequence.
\key code > studentreport/institute/unknown ...:N 
                                                  \g__studentreport_institut...
```
didn't help me much to localize the culprit line since I didn't see either `\bool_true:N` or the end of the macro name `\g__studentreport_institute_name_displayed_bool`  (and I have other macros the names of which starting identically, e.g. `\g__studentreport_institute_name_tl`).

**Comment by blefloch** [comment]
A variant of Phelype's suggestion is to have \cs_set_eq:Nc \__keys_tmp:w { keys
~ code ~ > ... } \__keys_tmp:w so that the control sequence name is much
shorter.  I don't know in which cases this kind of technique should be applied.

**Comment by PhelypeOleinik** [comment]
> A variant of Phelype's suggestion is to have \cs_set_eq:Nc \__keys_tmp:w { keys ~ code ~ > ... } \__keys_tmp:w so that the control sequence name is much shorter. I don't know in which cases this kind of technique should be applied.

Yeah, my suggestion of `\key <key name>` was more aimed at the error message showing in which key the error happened, if that makes any sense

**Comment by blefloch** [comment]
Actually I'm starting to think that the error message was not so bad because it
did contain in full the key name "studentreport/institute/unknown" (and even
much longer key names would appear in full), which seems enough to locate the
error.  Any renaming of \key code > studentreport/institute/unknown (other than
just removing "code > ", which we could do), would lose this information,
without guaranteeing that one would see the other relevant control sequences
better if the key were much longer.  I have no strong opinion there.

**Comment by dbitouze** [comment]
@blefloch > [the error message] did contain in full the key name "studentreport/institute/unknown" (and even
much longer key names would appear in full), which seems enough to locate the error.

True. Nevertheless, and maybe because I'm not experienced enough, it was not helpful for me since:

1. in the source file, `studentreport/institute/unknown` doesn't appear like this but is split (and contains spaces):
```latex
\keys_define:nn { studentreport }
{
  institute .choice:,
    institute / unknown .code:n ={%
    \tl_gset:Nn \g_@@_institute_name_tl {#1}
    \bool_gset_true:N \g_@@_institute_name_displayed_bool
  },
  [...]
```
2. as you see, even if the key name is located, multiple control sequences may be involved.

**Comment by blefloch** [comment]
I _think_ I fixed the issue with my latest commit
8de1d9f190ac06b58ea6227002257f450bd469b1 in the LaTeX3 repository
https://github.com/latex3/latex3 but perhaps someone else can make sure I didn't
mess up: I don't know the key code well.
