### ISSUE TITLE
[Localization] Add `japanese` Option to varioref.sty

### ISSUE THREAD

**Issue by cmplstofB** [latex3/latex2e#352]
## Brief outline of the enhancement
Hello.
Could you add a new language option `japanese` to varioref.sty?
the following code will make it works.
Because of grammatical reason, \vrefrange command has \reftextlabelrange and \vpagerefrange in a reversed order.

```latex
\DeclareOption{japanese}
  {\vref@addto\extrasjapanese{%
    \def\reftextfaceafter {\reftextvario{見開き}{次}頁}%
    \def\reftextfacebefore{\reftextvario{見開き}{前}頁}%
    \def\reftextafter     {\reftextvario{直後の}{次}頁}%
    \def\reftextbefore    {\reftextvario{直前の}{前}頁}%
    \def\reftextcurrent   {\reftextvario{この}{現}頁}%
    \def\reftextfaraway#1{\pageref{#1}頁}%
    \def\reftextpagerange#1#2{\pageref{#1}頁から\pageref{#2}頁}%
    \def\reftextlabelrange#1#2{\ref{#1}から\ref{#2}}%
  }%
  \AtEndOfPackage{%
  \renewcommand\vrefrange[3][\reftextcurrent]{%
  \vpagerefrange[{#1}]{#2}{#3}の\reftextlabelrange{#2}{#3}%
  }}}
```

**Comment by FrankMittelbach** [comment]
don't really think it can be done this way. If I'm not mistaken that this would disallow using more than one language as the different order in \vrefrange would be permanent. So have to think about this a bit, but yes glad to add a Japanese language option.

**Comment by FrankMittelbach** [comment]
@aminophen can I trouble you to have a look over the the fix for #352 and see if this correctly works including when mixing Japanese with, say English, thanks.  If you prefer I can add it into the dev format first, then you see it there via the CTAN route.

**Comment by aminophen** [comment]
@FrankMittelbach Thanks; I will ask some more users in Japan if they have any comments on the current implementation and/or translations.

**Comment by FrankMittelbach** [comment]
good, thanks. It is now on its way to CTAN in the dev release so in a day or two it should be usable via uplatex-dev

**Comment by FrankMittelbach** [comment]
It should be now available if the dev format is used, e.g., `pdflatex-dev file`

**Comment by cmplstofB** [comment]
@FrankMittelbach Hello. I'm sorry for the late response.

The [current implementation](https://github.com/latex3/latex2e/blob/952651adb565f283ad3ec5641e477eb3cad0899d/required/tools/varioref.dtx) does not seem to be able to handle the language-specific `\vrefrangeformat` format.

[In this part](https://github.com/latex3/latex2e/blob/a91ede24c84df04fcfb986fbc928ac28bb6dfe37/required/tools/varioref.dtx#L1271-L1272), `\vrefrangeformat` is defined as follows
https://github.com/latex3/latex2e/blob/a91ede24c84df04fcfb986fbc928ac28bb6dfe37/required/tools/varioref.dtx#L1271-L1272
for the “japanese” option, but the [typeset result](https://github.com/latex3/latex2e/blob/develop/required/tools/testfiles-TU/github-0352.lvt) is the same as the `\vrefrangedefaultformat` format.

This is what `\vrefrangeformat` is expected to output when we specify the “japanese” option (last two lines of test file compilation results):

![a](https://user-images.githubusercontent.com/20594300/88276266-b4d5ac00-cd19-11ea-9398-bfa80c4c893a.png)

But the actual output looks like this:

![b](https://user-images.githubusercontent.com/20594300/88276306-c8811280-cd19-11ea-80c5-da596a961391.png)

**Comment by FrankMittelbach** [comment]
can you please add the source (and log), thanks.

**Comment by FrankMittelbach** [comment]
forget it .. just saw the link in your post

**Comment by cmplstofB** [comment]
Apart from my previous comment, there are additional reports.

I will engage in these tasks once the above problem is resolved.

As a result of [discussions among users in Japan](https://texuser.slack.com/archives/C4ZQMCYNL/p1595334969458600),
* One translated term is needed to be changed. (“頁” → “ページ”)
* As with the `\vrefrange` command, some of the commands which declared in fixed word order (eg `\fullref`, `\vref@star`, `\Vref@star`, etc.) also needed to be modified for grammatical reasons.

**Comment by FrankMittelbach** [comment]
> The [current implementation](https://github.com/latex3/latex2e/blob/952651adb565f283ad3ec5641e477eb3cad0899d/required/tools/varioref.dtx) does not seem to be able to handle the language-specific `\vrefrangeformat` format.

yes it does not. my mistake. I execute the option first and then set the default ... stupid me. If you move processoptions to the very end of the file it should work.

**Comment by FrankMittelbach** [comment]
> I will engage in these tasks once the above problem is resolved.
> 
> As a result of [discussions among users in Japan](https://texuser.slack.com/archives/C4ZQMCYNL/p1595334969458600),
> 
>     * One translated term is needed to be changed. (“頁” → “ページ”)
> 
>     * As with the `\vrefrange` command, some of the commands which declared in fixed word order (eg `\fullref`, `\vref@star`, `\Vref@star`, etc.) also needed to be modified for grammatical reasons.

ok. I will not generate a new version (see comment above how to fix it locally) but wait for an explicit set of new defaults
and some default definitions for the star stuff (integrating them is then somehting I can do).

**Comment by cmplstofB** [comment]
@FrankMittelbach Thank you for your patience.
Due to the volume of changes, I've decided to make a pull request, even though I'm not part of the LaTeX team.
I'm sorry if my actions have confused you....

**Comment by FrankMittelbach** [comment]
I didn't apply the patch directly because we normally don't immediately pull into develop and there are a lot of other things that need to be taken care of (from test files to change logs to documentation), but I  used your supplied file as a basis, which was helpful. Thanks.
