### ISSUE TITLE
[Localization] Add `japanese` Option to layout Package

### ISSUE THREAD

**Issue by cmplstofB** [latex3/latex2e#353]
## Brief outline of the enhancement
Hello.
Could you add a new language option `japanese` to [layout Package](https://github.com/latex3/latex2e/blob/ffd1ecd60056fa3287532abb86bc6b73bbc47852/required/tools/layout.dtx)?
The following code will make it works.

```latex
\DeclareOption{japanese}{%
  \def\Headertext{天}
  \def\Bodytext{基本版面}
  \def\Footertext{地}
  \def\MarginNotestext{傍\\注}
  \def\oneinchtext{1インチ}
  \def\notshown{非表示}
  }
```

cf: W3C. _“Requirements for Japanese Text Layout”_, Appendix G [Terminology](https://www.w3.org/TR/jlreq/#terminology)

**Comment by FrankMittelbach** [comment]
It should be now available if the dev format is used, e.g., `pdflatex-dev file`

**Comment by FrankMittelbach** [comment]
this is not yet done my earlier message was for the wrong issue

**Comment by JohannesBraams** [comment]
@aminophen  can I trouble you to have a look over the the fix for #353 and see if this correctly works including when mixing Japanese with, say English, thanks. This is not yet in the dev release, I would likt to have it checked first if possible

**Comment by FrankMittelbach** [comment]
As there wasn't any further feedback I'm going to merge this into develop (in the hope it is correct) if not it can be updated later.

**Comment by cmplstofB** [comment]
Thank you!
