### ISSUE TITLE
Improve error recovery for \begin again (was made long by mistake)

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#354]
## Brief outline of the bug

somehwere between a bug and an enhancement. In the past error recovery for `\begin` was better

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!

\documentclass{article}

\begin{document}


\begin{quote)
qqq
\end{quote}

aaa

aaa
\end{document}
```

now generates

     ! File ended while scanning use of \begin .

in 2018 it only ate a paragraph

    ! Paragraph ended before \begin was complete.

**Comment by u-fischer** [comment]
Phelype wrote that there is * missing: \DeclareRobustCommand\begin[1]{%

**Comment by PhelypeOleinik** [comment]
Although the most common case is `\begin` (probably), other macros were mistakenly made `\long` with that change.  Looping through all macros listed with `\kernel@make@fragile` (for `latexrelease`), then `grep`ping for `\DeclareRobustCommand<macro>` and filtering out the ones that don't take arguments returns:
```bash
phelype@phelype ~/d/latex2e$ for i in $(grep -Phor '(?<=kernel@make@fragile)\\\w+'); do grep -Pr "\\\\DeclareRobustCommand\\$i\b\["; done
base/ltpictur.dtx:\DeclareRobustCommand\linethickness[1]
base/ltmiscen.dtx:\DeclareRobustCommand\begin[1]{%
base/ltpage.dtx:\DeclareRobustCommand\markboth[2]{%
base/ltpage.dtx:\DeclareRobustCommand\markright[1]{%
base/ltsect.dtx:\DeclareRobustCommand\title[1]{\gdef\@title{#1}}
base/ltsect.dtx:\DeclareRobustCommand\author[1]{\gdef\@author{#1}}
base/ltsect.dtx:\DeclareRobustCommand\date[1]{\gdef\@date{#1}}
base/ltsect.dtx:\DeclareRobustCommand\thanks[1]{\footnotemark
base/ltmath.dtx:\DeclareRobustCommand\cases[1]{\left\{\,\vcenter{\normalbaselines\m@th
base/ltmath.dtx:\DeclareRobustCommand\matrix[1]{\null\,\vcenter{\normalbaselines\m@th
base/ltmath.dtx:\DeclareRobustCommand\pmatrix[1]{\left(\matrix{#1}\right)}
base/ltoutenc.dtx:\DeclareRobustCommand\UseTextAccent[3]{%
base/ltoutenc.dtx:\DeclareRobustCommand\UseTextSymbol[2]{%
phelype@phelype ~/d/latex2e$
```
which should (some of them, at least) be made short again. I'm not sure if all of them to keep the old behaviour, of if some could use a `\par` inside them...

**Comment by FrankMittelbach** [comment]
In case of `\begin` it was clearly a mistake as the syntax expects an environment name and finding a `\par`means something was wrong and it is better to find out about it soon and not at the end of the document. However, in cases where the argument is text, e.g., `\thanks`, `\title`, etc. I personally think it is better to allow paragraphs even if forgetting the closing brace means everything to the end of the document is swallowed up. I would therefore suggest to correct only the obvious mistakes above.

**Comment by car222222** [comment]
Cases where the argument is text are clearly distinct from begin/end.

But they come in many different flavours, mostly depending precisely on what precisely is meant by 'text'.

It is not clear a priori that all these flavours should allow text that is 'conceptually/logically multi-paragraph'.  

But that is a question/decision at a different level from whether they should be at the low-level ' made \long'. Am I correct that this level is all,we are discussing here?

**Comment by FrankMittelbach** [comment]
> It is not clear a priori that all these flavours should allow text that is 'conceptually/logically multi-paragraph'.

Agreed, it depends

> But that is a question/decision at a different level from whether they should be at the low-level ' made \long'. Am I correct that this level is all,we are discussing here?

no we are discussing UI commands here if you look at the list by Phelype.  All of them have been short in the past and got long by the recent change for robustness. From that list I think for \title and \thanks it is reasonable to support \par in the argument for others such as \date I think we should return to the behavior that they had in the past (which is what I have done in the branch for this issue.

**Comment by car222222** [comment]
Thanks for the clarification.  But are we discussing only 'preamble', 'meta-data like' commands?  Rather than \subsection{...} or \index{...} . . . or . . .

**Comment by car222222** [comment]
Not sure I understand why Phelype's list is so short and so varied.

What is the current (long-)status of all the other hundreds of text-arg commands?

**Comment by PhelypeOleinik** [comment]
> Not sure I understand why Phelype's list is so short and so varied.

It's the output of a `grep` command: it only shows the first line of each definition (across many files).

> What is the current (long-)status of all the other hundreds of text-arg commands?

The list only shows commands made long by the robustness update, so stuff that changed in behaviour recently.  Other commands may still need changing, yes, but so they did for years.

**Comment by PhelypeOleinik** [comment]
> However, in cases where the argument is text, e.g., `\thanks`, `\title`, etc. I personally think it is better to allow paragraphs even if forgetting the closing brace means everything to the end of the document is swallowed up. I would therefore suggest to correct only the obvious mistakes above.

Yes, indeed (although in a title a `\\` might be a better option than `\par`).  I think that from the list, the ones that should be made short again:

 - `base/ltpictur.dtx:\linethickness` because it expects a length;
 - `base/ltmiscen.dtx:\begin` should be changed in this file as well (or not?);
 - `base/ltsect.dtx:\date` dates shouldn't contain `\par`... But then nothing _too_ bad happens if they do. I'm not sure.
 - `base/ltmath.dtx:\cases` a `\par` will break the math environment anyway, but with a less clear error
 - `base/ltmath.dtx:\matrix` same
 - `base/ltmath.dtx:\pmatrix` and same
 - `base/ltoutenc.dtx:\UseTextAccent` unless adding an accent to a paragraph break is now a thing ;-)
 - `base/ltoutenc.dtx:\UseTextSymbol` arguments are `<encoding>` and `<command>` both of which can't take a `\par` without breaking badly down the road

The others (`\markboth`, `\markright`, `\title`, and `\thanks`) can take some form of free-text from the user, so `\par` might be used eventually (even if due to a missing `}` :-)

**Comment by FrankMittelbach** [comment]
Your analysis looks accurate to me @PhelypeOleinik. I have pondered about that that could be kept long but thought in the end that except for \title and \thanks (where people quite often like to have a \par but can't except by using \endgraf) we should return to the behavior that was there in the past. 

@car222222 this issue is not about a general cleanup on what or what not should be \long in the UI but just ensuring that the mistaken change made during the robustness update (and some simply break if \par is used) gets reverted. A general look at \long/non-\long should be done in a separate issue, but in my opinion this is not pressing and so should not be undertaken now (not with "robustness not finished", for example).

**Comment by car222222** [comment]
Not directly relevant to whether they should be but I agree with Phelype that within meta-data-like things (\thanks, \title) it is better to encourage the use of some separator other than \par.

**Comment by car222222** [comment]
For the math structure cases, such as 'cases' and 'matrix' it is quite reasonable to want to add some text within a minipar (within a \text) and hence an explicit \par could reasonably get into these.

**Comment by car222222** [comment]
That last may all be rubbish in case they are always environments in LaTeX.

**Comment by FrankMittelbach** [comment]
matrix an pmatrix are really discurraged plain tex versions. So keeping them the way they where for 30+ years seems to me the right balance.
