### ISSUE TITLE
\input{} tries to load `csnameendcsname.tex`

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex2e#356]
## Brief outline of the bug

With the spaces-in-file-names update from last year, `\input{}` now tries to load `csnameendcsname(.tex)` rather than `.tex`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\input{}
\stop
```

## Cause

`\set@curr@file` does `\escapechar=-1` then `\expandafter\string\csname#1\endcsname`, and when `#1` is empty, the empty csname is created, and `\string` leaves `csnameendcsname`, then `\IfFileExists@` tries to look for that file.  This also means that apart from the weird name in the error message, if a file `csnameendcsname.tex` _does_ exist (unlikely, yes), then it is input.

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/4888401/test.log)

**Comment by FrankMittelbach** [comment]
will probably resolve itself by @PhelypeOleinik's code changes so assigned him too

**Comment by FrankMittelbach** [comment]
fixedwith thenew implementation
