### ISSUE TITLE
a.pdf in grfguide is not valid

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex2e#357]
## Brief outline of the bug

When using XeLaTeX or LuaLaTeX to compile the document `grfguide.tex`, the image `a.pdf` will lead to an error. See the following example.

## Minimal example showing the bug

```latex
\begin{filecontents*}{a.pdf}
%PDF-1.4
%%%%%
1 0  obj
<<
/Pages 2 0 R
/Type /Catalog
>>
 endobj
2 0  obj
<<
/Kids [3 0 R]
/Type /Pages
/Count 1
>>
 endobj
3 0  obj
<<
/Rotate 0
/Parent 2 0 R
/MediaBox [0 0 72 72]
 /Resources
<<
/ExtGState 4 0 R
/Font 5 0 R
/ProcSet [/PDF /Text]
>>
/pdftk_PageNum 1
/Type /Page
/Contents 6 0 R
>>
 endobj
4 0  obj
<<
/R7 7 0 R
>>
 endobj
5 0  obj
<<
/R8 8 0 R
>>
 endobj
6 0  obj
<<
/Length 135
>>
stream
q 0.1 0 0 0.1 0 0 cm
/R7 gs
10 w
0 G
0 0 m
720 720 l
0 720 l
720 0 l
S
0 g
q
10 0 0 10 0 0 cm BT
/R8 72 Tf
1 0 0 1 0 0 Tm
(A)Tj
ET
Q
Q

 endstream
 endobj
7 0  obj
<<
/Type /ExtGState
/OPM 1
>>
 endobj
8 0  obj
<<
/BaseFont /Times-Roman
/LastChar 65
/Subtype /Type1
/FontDescriptor 9 0 R
/Widths [722]
/Type /Font
/Encoding /WinAnsiEncoding
/FirstChar 65
>>
 endobj
9 0  obj
<<
/FontName /Times-Roman
/StemV 105
/CharSet (/A)
/Ascent 674
/Flags 65568
/Descent 0
/ItalicAngle 0
/MissingWidth 250
/FontBBox [0 0 706 674]
/Type /FontDescriptor
/CapHeight 674
>>
 endobj
10 0  obj
<<
/Producer (GPL Ghostscript 9.06)
/ModDate (D:20140426202438+01'00')
/CreationDate (D:20140426202438+01'00')
>>
endobj xref
0 11
0000000000 65535  f
0000000015 00000  n
0000000066 00000  n
0000000125 00000  n
0000000308 00000  n
0000000341 00000  n
0000000374 00000  n
0000000563 00000  n
0000000610 00000  n
0000000774 00000  n
0000000975 00000  n
trailer

<<
/Info 10 0 R
/Root 1 0 R
/Size 11
/ID [<4ca1370d594acd28b9d948a5e8b925c3> <4ca1370d594acd28b9d948a5e8b925c3>]
>>
startxref
1106
%%EOF
\end{filecontents*}

\RequirePackage{latexbug}
\documentclass{minimal}
\usepackage{graphics}
\begin{document}
\includegraphics{a.pdf}
\end{document}
```

## Log file (required) and possibly PDF file  

I use `pdflatex`, `xelatex`+`xdvipdfmx`, `lualatex` to compile this mwe.

[mwe.zip](https://github.com/latex3/latex2e/files/4957967/mwe.zip)

**Comment by davidcarlisle** [comment]
That's odd, why is dvipdfmx seeing a link object at all? I tried opening a.pdf with acrobat pro 99, a bit old, but what I have)  and it didn't give any warnings as far as I can see. @u-fischer  any ideas?

**Comment by u-fischer** [comment]
@davidcarlisle imho the `pdf_link_obj():` means the linked lists of objects starting from the xref table. If one makes xdvipdfmx more verbose, it also mentions `xdvipdfmx:warning: Didn't find "endobj".`. The pdf syntax checker agrees with xelatex and lualatex and says too that the pdf structure is corrupt. Only pdflatex seems to be able to handle it. 

Using pdftk repairs the pdf, but the syntax checker still reports an error:
 
         Indirect object "endobj" keyword not followed by an EOL marker

Does it still make sense to try to add the pdf verbatim in a file contents environment?

**Comment by davidcarlisle** [comment]
@u-fischer  probably not, I could check in the eps and pdf directly I suppose, making a new pdf from the eps, although I thought the current one was just an uncompressed version of the eps2pdf translation, but perhaps it got corrupted along the way...

**Comment by car222222** [comment]
@u-fischer 
Does pdftk give this error for every endobj in the file?

**Comment by car222222** [comment]
I can also find one, this line:

   endobj xref

**Comment by u-fischer** [comment]
pdftk doesn't give any error. The errors are from xdvipdfmx and pdfpilot. And yes, the fact that the endobj are indented and not on a line on their own is a probable source of the problem. The reference doesn't say explicitly imho that this is required (it says it only for endstream), but it is better to do it anyway, some validators complain.  But I didn't really try to find out what is really wrong. I don't think that it is worth the time,  we should simply replace it by a correct pdf.

**Comment by car222222** [comment]
"The reference doesn't say explicitly imho that this is required (it says it only for endstream)" 
Interesting: I had not looked up again the detail about where the EOL is required, only recalling that sometimes it is.

**Comment by FrankMittelbach** [comment]
>  But I didn't really try to find out what is really wrong. I don't think that it is worth the time, we should simply replace it by a correct pdf.

can you make one for David that passes pdfpilot and can be placed into `filecontents*` I think there is some advantage in having it as part of the source rather than as a separate file

**Comment by u-fischer** [comment]
I can try to make an uncompressed version, but I don't know if I can really check with filecontents, as I have no idea what my system will do with line endings and whitespaces -- as you know my commits change them sometimes ;-)

**Comment by davidcarlisle** [comment]
I think the problematic objects are mostly due to the non embedded font for
the Times Roman A, I made a new pdf with epstopdf  from a.ps but with an
embedded font (subset) it's quite a bit bigger, it may be best if we are
including the pdf to re-do the EPS to only have lines and not a character,
the pdf is then a lot simpler to manage. I'll do some experiments later.

**Comment by car222222** [comment]
Or one with nothing at all that gets rendered in its contents stream?
Depends a lot on why it is there, of course.

**Comment by davidcarlisle** [comment]
> 
> 
> Or one with nothing at all that gets rendered in its contents stream?
> Depends a lot on why it is there, of course.

er it's there to show examples of scaling and rotation in grfguide, so an example that doesn't render anything might be problematic...


I suggest we do this, replace a.ps by a.eps (called xa.eps here) so it triggers the automatic call to epstopdf when needed
This automatic conversion wasn't automatic when gfrguide was originally written....



```
\begin{filecontents*}{xa.eps}
%!PS-Adobe-2.0 EPSF-2.0
%%BoundingBox: 0 0 72 72
0 0 moveto
72 72 rlineto
72 neg 0 rlineto
72 72 neg rlineto
stroke
newpath
0 0 moveto
20 40 lineto
40 0 lineto
10 20 moveto
30 20 lineto
stroke
%%EOF
\end{filecontents*}
\documentclass{minimal}
\usepackage{graphics}
\begin{document}
\includegraphics{xa.eps}
\end{document}
```

**Comment by car222222** [comment]
I said it depends:-).
