### ISSUE TITLE
bibliography abbreviation does not preserve special character

### ISSUE THREAD

**Issue by JosueBock** [latex3/latex2e#359]
## Brief outline of the bug

If the initials of the first name of an author is a special character, it is not preserved in the final bibliography

(this is my first time reporting a bug here. I tried to check that it is suited to report it here, please apologise if not)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\usepackage{natbib}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}
\bibliographystyle{abbrvnat}

See the error in \cite{tjiputra_ocean_2020} : \O{}yvind Seland has not been abbreviated correctly: it appears as O. Seland instead of \O. Seland.

Other test in \cite{other_2020} (special character now duplicated in the family name): it is kept throughout the bibliography formatting process.

\bibliography{bug}

\end{document}



```

## Log file (required) and possibly PDF file  

[bug1.log](https://github.com/latex3/latex2e/files/5001942/bug1.log)
[bug1.pdf](https://github.com/latex3/latex2e/files/5001943/bug1.pdf)

**Comment by u-fischer** [comment]
As the log file says you are using a third party package here.

~~~~
! Package latexbug Error: Third-party file(s)
(latexbug)                
(latexbug)                This test file uses third-party file(s)
(latexbug)                
~~~~

So you are at the wrong place. Also you didn't add the bib-file so your example can not be tested.  

But beside this: input your author like this:

     author={{\relax \O}yvind Seland},

Or switch to biblatex + biber which can handle the full unicode range without problems.

**Comment by JosueBock** [comment]
Sorry, I did not notice the message in log file.
Thank you for your help and advice.

**Comment by FrankMittelbach** [comment]
@JosueBock just curious, what setup do you use? Because it should stop the run with an error message
```
See the latexbug package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.8 \begin{document}
                    
? 
```
so if that doesn't happen I'm interested in what kind of environment you executed it.

(and as an aside, it is not that we want to get rid of many issues, it is just we can't really help in most of such cases even if we had the bandwidth --- there are 5000+ packages but third party developers out there and we are a handful of people who maintain the core but not the rest of LaTeX).

**Comment by JosueBock** [comment]
@FrankMittelbach I am using Kile, the only error that I got refered to the wrong character, not to the third party package.

I fully understand that you only deal with the core of LaTeX, sorry for my mistake not noticing the log message about the natbib.sty package

**Comment by moewew** [comment]
You don't even need the `\relax`, you just need to remember to enclose macro-escapes for non-US-ASCII chars in an additional pair of curly braces (this holds only for `.bib` files, this is not the case in normal text in your `.tex` file).

[`btxdoc`](http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf) explains this with `ö` (§2.1, item 4, pp. 3-4). The correct way to input the name *Kurt Gödel* would be
```latex
author = {G{\"o}del, Kurt},
```
or
```latex
author = {G{\"{o}}del, Kurt},
```
with the macro-escape `\"o` or `\"{o}` for `ö` wrapped in an additional pair of curly braces.

See also §2.1, item 4 (p. 2) in [`btxFAQ`](http://mirrors.ctan.org/biblio/bibtex/contrib/doc/btxFAQ.pdf).

For Ø that means that the correct way to give the character's macro-escape in the `.bib` file is `{\O}` and not just `\O`.


Indeed, with all macro-escapes fixed
```latex
\documentclass{article}

\usepackage{natbib}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{filecontents}{\jobname.bib}
@article{tjiputra_ocean_2020,
  author  = {Tjiputra, Jerry F. and Schwinger, J{\"{o}}rg
             and Bentsen, Mats and Mor{\'{e}}e, Anne L. and Gao, Shuang
             and Bethke, Ingo and Heinze, Christoph and Goris, Nadine
             and Gupta, Alok and He, Yan-Chun and Olivi{\'{e}}, Dirk
             and Seland, {\O}yvind and Schulz, Michael},
  title   = {Ocean biogeochemistry in the {Norwegian} {Earth} {System} {Model} version 2 ({NorESM2})},
  volume  = {13},
  issn    = {1991-9603},
  doi     = {10.5194/gmd-13-2393-2020},
  number  = {5},
  journal = {Geoscientific Model Development},
  month   = may,
  year    = {2020},
  pages   = {2393-2431},
}
@article{other_2020,
  author  = {Ztesta, Ytestb and {\O}testX, {\O}testW},
  title   = {Ocean biogeochemistry in the {Norwegian} {Earth} {System} {Model} version 2 ({NorESM2})},
  volume  = {13},
  issn    = {1991-9603},
  doi     = {10.5194/gmd-13-2393-2020},
  number  = {5},
  journal = {Geoscientific Model Development},
  month   = may,
  year    = {2020},
  pages   = {2393-2431},
}
\end{filecontents}

\begin{document}
\bibliographystyle{abbrvnat}

See the error in \citet{tjiputra_ocean_2020} : \O{}yvind Seland has not been abbreviated correctly: it appears as O. Seland instead of \O. Seland.

Other test in \citet{other_2020} (special character now duplicated in the family name): it is kept throughout the bibliography formatting process.

\bibliography{\jobname}
\end{document}
```
compiles to the expected output

![Ø. Seland](https://user-images.githubusercontent.com/6755835/88973644-b245fa00-d2b7-11ea-97a7-9549e58dc9e9.png)

----

As Ulrike says, if you use `biblatex` and Biber you can (and ideally should) use the Unicode characters directly.

```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[backend=biber, maxbibnames=999, giveninits=true]{biblatex}

\begin{filecontents}{\jobname.bib}
@article{tjiputra_ocean_2020,
  author  = {Tjiputra, Jerry F. and Schwinger, Jörg
             and Bentsen, Mats and Morée, Anne L. and Gao, Shuang
             and Bethke, Ingo and Heinze, Christoph and Goris, Nadine
             and Gupta, Alok and He, Yan-Chun and Olivié, Dirk
             and Seland, Øyvind and Schulz, Michael},
  title   = {Ocean Biogeochemistry in the {Norwegian} {Earth} {System} {Model} Version 2 ({NorESM2})},
  volume  = {13},
  issn    = {1991-9603},
  doi     = {10.5194/gmd-13-2393-2020},
  number  = {5},
  journal = {Geoscientific Model Development},
  month   = may,
  year    = {2020},
  pages   = {2393-2431},
}
@article{other_2020,
  author  = {Ztesta, Ytestb and ØtestX, ØtestW},
  title   = {Ocean Biogeochemistry in the {Norwegian} {Earth} {System} {Model} Version 2 ({NorESM2})},
  volume  = {13},
  issn    = {1991-9603},
  doi     = {10.5194/gmd-13-2393-2020},
  number  = {5},
  journal = {Geoscientific Model Development},
  month   = may,
  year    = {2020},
  pages   = {2393-2431},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
See the error in \autocite{tjiputra_ocean_2020} : \O{}yvind Seland has not been abbreviated correctly: it appears as O. Seland instead of \O. Seland.

Other test in \autocite{other_2020} (special character now duplicated in the family name): it is kept throughout the bibliography formatting process.

\printbibliography
\end{document}
```

The fact that your `.bib` file contains `urldate = {2020-07-30},` makes it look quite `biblatex`-y already. I know of no `biblatex` style that supports a `urldate` field with `YYYY-MM-DD` format.

**Comment by JosueBock** [comment]
Dear @moewew ,
Thank you for your answer and all these tips about the correct way to handle the bibliography reference.
Regarding the biblatex + biber suggestion: I indeed had a look to this after the first reply from Ulrike, and clearly plan to move to this method for future work.
Best wishes
