### ISSUE TITLE
can not find .bib file on MacTeX using relative path

### ISSUE THREAD

**Issue by piggy00wiggy** [latex3/latex2e#36]
## Brief outline of the bug

can not find .bib file using relative path like \bibliography{../Library} 
(please create a library in parent folder by yourself because .bib file cannot be uploaded as attachment, and modify bibtex key accordingly)

this issue happens on my macOS while works well on windows 10

my platform: 
macOS 10.13.4 with MacTeX (texlive 2017 distribution)
windows 10 with texlive 2017

## Minimal example showing the bug

```latex
%!TEX program = xelatex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
test cite \cite{key1}
\bibliographystyle{IEEEtran}
\bibliography{../Library1.bib}
\end{document}
```

## Log file (required) and possibly PDF file  
[manuscript.pdf](https://github.com/latex3/latex2e/files/1914705/manuscript.pdf)
[manuscript.log](https://github.com/latex3/latex2e/files/1914706/manuscript.log)

!! Use drag-and-drop  (remember: .log file is required) !!

**Comment by FrankMittelbach** [comment]
all that `\bibliography {../foo}` does is writing the line
```
\bibdata{../foo}
```
into the .aux file. This file is then processed by BibTeX. I have just checked and it works perfectly on my mac. Could it be that you have some special security setting enabled? (one can configure texlive to never write (or even read) anything starting with a dot).

In any case this is not a LaTeX problem but a problem with the way your BibTeX program opens files (and we do not manage any TeX related binaries).

**Comment by piggy00wiggy** [comment]
sorry for the invalid report. 
with the help of your information, my problem is resolved .
Thank you @FrankMittelbach

**Comment by FrankMittelbach** [comment]
no problem - happy LaTeXing
