### ISSUE TITLE
Nested hooks with new hook management

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#360]
## Brief outline of the bug
Nesting definitions for the same hook with `\AddToHook` are only executed on top-level, whereas nesting `\AtBeginDocument` works. Is it be purpose 

Nested definitions with '\AddToHook' for the same hook are only executed at  top-level, whereas nesting '\AtBeginDocument' works. Is this intentional or a bug? I noticed this because nesting of _etoolbox'_ `\AtEndPreamble` does not work with the current dev version.

## Minimal example showing the bug

```latex
\listfiles
\RequirePackage{latexbug}
\documentclass{article}
%\DebugHookOn
\AddToHook{begindocument}{%
  \typeout{+++++ check}%
  \AddToHook{begindocument}{\typeout{+++++ check nested}}
}
\AddToHook{env/document/begin}{%
  \typeout{***** check}%
  \AddToHook{env/document/begin}{\typeout{***** check nested}}
}

\begin{document}
test
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/5007012/test.log)

**Comment by PhelypeOleinik** [comment]
The difference of `begindocument` and `env/document/begin` is that the former is a “one-time hook”, which means that after being used, any later `\AddToHook{begindocument}{<code>}` will execute `<code>` immediately (including inside the hook itself).  `env/document/begin` is a generic environment hook, so it can't be a one-time hook.  This means that a `\AddToHook{env/document/begin}{<code>}` inside that hook will only add to the next execution of that code.  So yes, all working as designed here.

However `etoolbox`'s `\AtEndPreamble` was formerly implemented as a one-time hook, so `env/document/begin` should perhaps be implemented as a one-time hook as well. Should be easy to fix, as we already have an exception there.

**Comment by FrankMittelbach** [comment]
now fixed in etoolbox
