### ISSUE TITLE
Conflict between latexrelease and l3cctab

### ISSUE THREAD

**Issue by qinglee** [latex3/latex2e#363]
## Brief outline of the bug

There will raise a `LaTeX3 Error` when use `latexrelease` and `l3cctab` in lualatex.

```
! LaTeX3 Error: Invalid \catcode table.

For immediate help type H <return>.
 ...                                              
                                                  
l.5 \cctab_begin:N \c_code_cctab
                              
? 
```

## Minimal example showing the bug

```latex
% !TeX program = lualatex
\RequirePackage{latexbug}
\RequirePackage[2020-02-01]{latexrelease}

\ExplSyntaxOn
\cctab_begin:N \c_code_cctab
\cctab_end:
\ExplSyntaxOff

\stop
```

##  Cause

`\e@alloc@ccodetable@count` is reset to `0` in latexrelease. Maybe it caused some inconsistency.

## Log file (required) and possibly PDF file  

[1.log](https://github.com/latex3/latex2e/files/5012170/1.log)

**Comment by josephwright** [comment]
I think I've sorted this: I wonder if there is urgency to a fix in the release or if we can wait for the next scheduled update.

**Comment by FrankMittelbach** [comment]
It only affects cases where you use latexlease and then only if with luatex? In that case I think it is okay if we wait with it until the 3rd -dev release.

**Comment by josephwright** [comment]
The bug is LuaTeX-specific and only occurs if you load `latexrelease`.

**Comment by FrankMittelbach** [comment]
Then I said we wait. If it enough to have an updated latexrelease.sty around?  If so perhaps you can just for now add that one to the issue here as a workaround
