### ISSUE TITLE
longtable footnotes not \long

### ISSUE THREAD

**Issue by djasnd** [latex3/latex2e#364]
## Brief outline of the bug

line 2145 of longtable.dtx 

\def\LT@p@ftntext#1{%

should be

\long\def\LT@p@ftntext#1{%

That would be consistent with other footnote text macros in LaTeX. Currently, \par is prohibited 
## Minimal example showing the bug

none

**Comment by davidcarlisle** [comment]
fixed in branch at  dafe02c3
