### ISSUE TITLE
Overrideable obeylines and obeyspaces

### ISSUE THREAD

**Issue by hmenke** [latex3/latex2e#367]
## Brief outline of the enhancement

Currently `\obeylines` defaults to `\par` and `\obeyspaces` defaults to `\space`.  In ConTeXt, this is slightly different where `\obeylines` defaults to `\obeyedline` and `\obeyspaces` defaults to `\obeyedspace`.  These “obeyed” macros can be overridden at any time which has some interesting use-cases.

One possiblity is to add some more stretch to interword spaces for verbatim material to facilitate better line breaks (see MWE below).  Another use-case was demonstrated on TeX.SX (https://tex.stackexchange.com/questions/551035) where `\obeyedline` was used to look ahead for `\end` and not insert a `\par` in that case.

I think this change is rather minimally invasive, since by default `\obeyedspace` can still expand to `\space` and `\obeyedline` can still expand to `\par` in this implementation:
```latex
\def\obeyedline{\par}
\def\@obeyedline{\obeyedline}
{\catcode`\^^M=\active % these lines must end with %
  \gdef\obeylines{\catcode`\^^M\active \let^^M\@obeyedline}%
  \global\let^^M\@obeyedline} % this is in case ^^M appears in a \write
\def\obeyedspace{\space}
\def\@obeyedspace{\obeyedspace}
\def\obeyspaces{\catcode`\ \active}
{\obeyspaces\global\let =\@obeyedspace}
```
The two-step implementation `\@obeyed...` -> `\obeyed...` is needed such that users can change `\obeyed...` even after `\obey...` has already been issued.  However, the active character now require two steps of expansion.  If that is not desired, maybe an implementation like this could be feasible:
```latex
\let\obeyedline\par
\def\@obeyedline{\obeyedline}
{\catcode`\^^M=\active % these lines must end with %
  \gdef\obeylines{\catcode`\^^M\active \let^^M\obeyedline}%
  \global\let^^M\@obeyedline} % this is in case ^^M appears in a \write
\let\obeyedspace\space
\def\@obeyedspace{\obeyedspace}
\def\obeyspaces{\catcode`\ \active}
{\obeyspaces\global\let =\@obeyedspace}
```
This only requires one step of expansion.
## Minimal example

```latex
\RequirePackage{latexbug}
\documentclass{article}

\makeatletter

\def\obeyedline{\par}
\def\@obeyedline{\obeyedline}
{\catcode`\^^M=\active % these lines must end with %
  \gdef\obeylines{\catcode`\^^M\active \let^^M\@obeyedline}%
  \global\let^^M\@obeyedline} % this is in case ^^M appears in a \write
\def\obeyedspace{\space}
\def\@obeyedspace{\obeyedspace}
\def\obeyspaces{\catcode`\ \active}
{\obeyspaces\global\let =\@obeyedspace}

\makeatother

\begin{document}

\bgroup
\ttfamily
\def\obeyedspace{\hskip\fontdimen2\font plus 1em\relax}%
\obeyspaces%
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur massa turpis,
semper quis fringilla ut, viverra nec risus. Pellentesque habitant morbi
tristique senectus et netus et malesuada fames ac turpis egestas. Donec nunc
lorem, sollicitudin vel sodales eget, vehicula nec mi. Proin ullamcorper rutrum
nibh, at porttitor nunc euismod et. Donec faucibus nisi faucibus ipsum porttitor
pharetra. Sed elementum, lectus nec congue imperdiet, ipsum leo viverra nisi, sit
amet commodo odio odio id nisl. Fusce sagittis lobortis nisi sed consectetur. Nam
egestas, sem ut fermentum convallis, ipsum tellus venenatis augue, eget
condimentum risus quam id erat. Sed metus dui, sollicitudin pharetra pellentesque
sed, placerat eget augue. Mauris sodales pretium tortor vitae rutrum. Proin quam
sem, lobortis tincidunt pretium vitae, feugiat eu lacus.

\textcopyright egreg design services
\egroup

\end{document}
```

![test](https://user-images.githubusercontent.com/1903556/89767179-7c253780-db4d-11ea-83c8-f881113e0a4b.png)

**Comment by FrankMittelbach** [comment]
@hmenke I can see  the advantage of havin this indirection, but I'm not convinced that
```
  \global\let^^M\@obeyedline} % this is in case ^^M appears in a \write
```
should be done; a `^^M` that happens in a write, essentially happens out of context and so I think it might be better in that case to have a single well-defined definition that *is* `\par`. For the same reason I don't think that an active space (which too can show up in writes) should become globally an essentially random macro but should be `\space` in that case.

**Comment by hmenke** [comment]
That sounds good to me. Should I prepare a PR?

**Comment by FrankMittelbach** [comment]
if you want to get down't into the depth of rollback setup :-) and test file preparations ... it would certainly be appreciated if there is some help but I'm not sure it is really feasible

**Comment by FrankMittelbach** [comment]
Looking at the code in the kernel, the suggested change breaks this comment
```
% In |\obeylines|, we say |\let^^M=\par| instead of |\def^^M{\par}|
% since this allows, for example, |\let\par=\cr \obeylines \halign{...|
```
While this is a "plain TeX" comment, it is not impossible that there is code out there that makes use of the way Don proposed to use the commands, so a change needs to be a little more elaborate (and can't be made just in ltplain.dtx).

**Comment by hmenke** [comment]
I think it would still work but it constrains the scope of the feature a little bit. In particular the two stage process via `\@obeyedline` has to go, but then this should still work:
```latex
\let\obeyedline\cr
{\catcode`\^^M=\active % these lines must end with %
  \gdef\obeylines{\catcode`\^^M\active \let^^M\obeyedline}%
  \global\let^^M\par} % this is in case ^^M appears in a \write
```
The downside is that in this case redefining `\obeyedline` after already having issued `\obeylines` has no effect.

**Comment by FrankMittelbach** [comment]
Don't think that works at all -- it now issues `\cr`by default, and as far as I can't see wouldn't support the reason why you wanted the feature in the first place.

My comment was not because I don't think it is not doable, but because it gets more elaborate if that is taken into account, e.g., it has to be `\let\obeyedline\par` but with `\par` having the meaning of `\para_end:`which is not yet available in ltplain.dtx.

**Comment by FrankMittelbach** [comment]
> The downside is that in this case redefining \obeyedline after already having issued \obeylines has no effect.

for that you can repeat the `\obeylines` after the redefinition (while in the scope of a running `\obeylines`. Not beautiful but, ok I would say.

**Comment by FrankMittelbach** [comment]
This break demo.tex from the metre package, what was the other document again @zauguin ?

**Comment by zauguin** [comment]
> This break demo.tex from the metre package, what was the other document again @zauguin ?

`etexcomp.tex` of "components-of-TeX"

**Comment by FrankMittelbach** [comment]
@hmenke Henri, if you a cycle or two and want to do us a favor, you could go after the two owners that use `\let\par\cr` in their documentation and make sure they are aware and update  as necessary.
