### ISSUE TITLE
Code for `\counterwithin` is missing the dot

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#38]
The code for `\counterwithin` as in recent LaTeX release

```latex
\def\counterwithin{\@ifstar\counterwithin@s\counterwithin@x}
\def\counterwithin@s#1#2{%
  \@ifbothcounters{#1}{#2}{\@addtoreset{#1}{#2}}}
\def\counterwithin@x#1#2{%
  \@ifbothcounters{#1}{#2}%
      {\@addtoreset{#1}{#2}%
       \expandafter
       \gdef\csname the#1\expandafter\endcsname\expandafter
            {\csname the#2\expandafter\endcsname\expandafter
             \@arabic\csname c@#1\endcsname}}}
```

is missing the dot which is promised in the documentation:

edit: I forgot to say this originates in a [tex.sx question](https://tex.stackexchange.com/questions/427451/dot-between-chapter-number-and-figure-number-disapear-after-update)
```
\counterwithin{counter}{within-counter}: Resets counter whenever
within-counter s stepped. Also redefines \thecounter command to produce
\thewithin-counter.\arabic{hounter}. 
```

**Comment by FrankMittelbach** [comment]
fixed by 4738b15f9476f7abb9c25c3bc9a67faa19c71dba interestingly enough the text showed the mistake, only we overlooked that it come out wrong :-(
