### ISSUE TITLE
Another stuttering?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#380]
Another stuttering? :smile: 

https://github.com/latex3/latex2e/blob/3aca7b6a6120ae22874565ce284ddc0348ef87c9/base/ltfilehook.dtx#L110

**Comment by FrankMittelbach** [comment]
thanks, yes I guess so. 

But if possible I would prefer to see this as a simple comment to the  3aca7b6. It reaches us too there and it doesn't clutter the issue list (given that people actually look through that for finding issues it would be nice if we can keep it fairly clean.

**Comment by dbitouze** [comment]
> But if possible I would prefer to see this as a simple comment to the [3aca7b6](https://github.com/latex3/latex2e/commit/3aca7b6a6120ae22874565ce284ddc0348ef87c9)

Sorry for that.  I hesitated to comment on a non culprit commit. Initially, I planned to make a pull request, so cloned the `latex3/latex2e` repository but then I couldn't find the `ltfilehook.dtx` file! :confused:

**Comment by FrankMittelbach** [comment]
Am 27.08.20 um 19:17 schrieb Denis Bitouzé:
>     <https://github.com/latex3/latex2e/commit/3aca7b6a6120ae22874565ce284ddc0348ef87c9>
> 
> Sorry for that. I hesitated to comment on a non culprit commit. 
> Initially, I planned to make a pull request, so cloned the 
> |latex3/latex2e| repository but then I couldn't find the 
> |ltfilehook.dtx| file! 😕

Denis, it is in the develop branch only, becuase in 2020/02 (master) is 
wasn't yet born.

No harm done in fact I took the opportunity to find a little more 
stuttering :-) I just wanted to mention that -- for 2e at least -- we 
prefer only real bugs to end up  in the issue list
