### ISSUE TITLE
polyglossia, filehook, and unknown \InputIfFileExists

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#382]
Trying to load polyglossia with {lua,xe}latex-dev fails with
! Package filehook Error: Detected unknown definition of \InputIfFileExists.

I rebuilt the .fmts so they are up to date. No problem with non-dev. Hence I thought I'd report it here, instead of to polyglossia ...

```
\documentclass{article}
\usepackage{polyglossia}
\begin{document}
\end{document}
```

**Comment by FrankMittelbach** [comment]
This is due to polyglossia loding filehook which is not yet adjusted to the new definition \InputIfFileExists. Martin is aware of the issue with filehook and is in the proces of producing a new version that uses LaTeX's hook management instead of altering the LaTeX commands.

**Comment by dbitouze** [comment]
Does it mean that, in order to test against `latex-dev` our packages/classes that load `filehook`, we have to wait this package is fixed?

**Comment by u-fischer** [comment]
@dbitouze if you load filehook-ltx early enough it should work in most cases.

**Comment by dbitouze** [comment]
Unfortunately, it isn't enough if `filehook` is indirectly loaded, e.g. by `currfile`:

```latex
\documentclass{article}
\usepackage{filehook-ltx}
\usepackage{currfile}
\begin{document}
Test
\end{document}
```

BTW, the [Martin's `bitbucket` repositories ](https://bitbucket.org/martin_scharrer/currfile/) don't exist anymore.

**Comment by u-fischer** [comment]
currfile is broken as it uses internal commands of filehook, and so the replacement doesn't work. 

The new repos are here https://sourceforge.net/u/mscharrer/profile/

(sadly all the old issues are gone, but I did add issues both about filehook and about currfile about two months ago.)

**Comment by dbitouze** [comment]
> (sadly all the old issues are gone, but I did add issues both about filehook and about currfile about two months ago.)

Indeed, the several issues I opened on several of his packages are gone :(

**Comment by FrankMittelbach** [comment]
@dbitouze perhaps it helps if you open new  issues in the new location. As I said we have contacted Martin and he is aware of the problem for some time, but he may not realize that there are other packages relying on his code. And the nominal release date is approaching now (and we can only hold that back a little bit).

**Comment by dbitouze** [comment]
> perhaps it helps if you open new issues in the new location.

Indeed, sorry. 

> And the nominal release date is approaching now (and we can only hold that back a little bit).

That's the reason I gave a try to my classes and was facing this issue. Martin's attention [is drawn](https://sourceforge.net/p/currfile/tickets/1/).

**Comment by FrankMittelbach** [comment]
this should be resolved by now
