### ISSUE TITLE
Overfull \hbox when using new shipout code

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#387]
## Brief outline of the bug

With the latest 'develop' branch (I'm using 6410c48)

```
Overfull \hbox (614.295pt too wide) has occurred while \output is active
```

which was not there in current stable.

## Minimal example showing the bug

Intentionally removed `\RequirePackage{latexbug}` because it reports atbegshi.sty is third-party.

```latex
\documentclass[dvipdfmx]{book}
\usepackage{atbegshi}
\usepackage{graphicx}
\begin{document}

\AtBeginShipout{%
  \AtBeginShipoutUpperLeft{%
    \parbox[t][\paperheight][b]{\paperwidth}{%
      \includegraphics[width=210mm,height=297mm]{example-image-a.png}
    }%
  }%
}

Here!
\end{document}

```

## Log file (required) and possibly PDF file  

* Stable format: [abgs-overfull-o.log](https://github.com/latex3/latex2e/files/5196400/abgs-overfull-o.log)
* Develop format: [abgs-overfull.log](https://github.com/latex3/latex2e/files/5196401/abgs-overfull.log)

**Comment by u-fischer** [comment]
yes looks wrong. The definition was changed in  75108758a9a to avoid to create a box of its own, but now it misses the needed \put command. Something like this should work:

~~~
\def\AtBeginShipoutUpperLeft#1{%
              \@expl@@@shipout@add@background@picture@@n{\put(0,0){#1}}}

\def\AtBeginShipoutUpperLeftForeground#1{%
              \@expl@@@shipout@add@foreground@picture@@n{\put(0,0){#1}}}

~~~~

**Comment by FrankMittelbach** [comment]
An additional \put would fix it but I would say what is missing is \hss in the definition of the overlay command:
```
\ExplSyntaxOn
\cs_set:Npn \__shipout_picture_overlay:n #1 {
    \__shipout_init_page_origins:
    \kern -\c__shipout_horigin_tl \scan_stop:
    \vbox_to_zero:n {
      \kern -\c__shipout_vorigin_tl \scan_stop:
      \unitlength 1pt \scan_stop:
      \hbox_set_to_wd:Nnn \l__shipout_tmp_box \c_zero_dim { \ignorespaces #1 \tex_hss:D }
      \box_set_ht:Nn \l__shipout_tmp_box \c_zero_dim
      \box_set_dp:Nn \l__shipout_tmp_box \c_zero_dim
      \box_use:N \l__shipout_tmp_box
      \tex_vss:D
    }
}
\ExplSyntaxOff
```

**Comment by u-fischer** [comment]
@FrankMittelbach  You are right, I misread the original atbegshi code. It actually doesn't put the argument in a \put command, only in a picture command. But this also means that putting material directly in the argument isn't correct, one should use it with \put (as it shown in the documentation, (and is done by eso-pic):

~~~~
\AtBeginShipout{%
 \AtBeginShipoutUpperLeft{%
 \put(0.5\paperwidth,-0.5\paperheight){\circle{10}}%
 }%
~~~~

(but the \hss is sensible nevertheless).

**Comment by FrankMittelbach** [comment]
Well, I'm not sure how atbegshi actually documented the usage, but putting stray horizontal material into a pictre env does work (in a certain way) so the \hss is missing to mimic the old behavior. Anyway, we document the hooks as use \put to place your material so I think we are good if that gets added.

**Comment by car222222** [comment]
This should probably go to an issue or an L3PL todo list.

Is the primitive \tex_hss:D currently the only way to do this?
Should a wrapper for it be added to some existing module?

And do we need a module,'l3glue'?,with package/design/CamelCase simple descriptive names for many such things (mostly not primitives).

**Comment by josephwright** [comment]
@car222222 See `xbox` in `l3trial` for some ideas I had.
