### ISSUE TITLE
Support \pkg{calc} in various kernel commands and \cs{textbackslash}

### ISSUE THREAD

**Issue by dr-scsi** [latex3/latex2e#390]
## Brief outline of the bug

Dear all,

current [ltnews32.tex](https://github.com/latex3/latex2e/blob/58ea958e3ddd0c89a9c62e98e39f86bd3b38730a/base/doc/ltnews32.tex#L297) states:

```latex
\subsection{Support \pkg{calc} in various kernel commands}

The \cs{hspace}, \cs{vspace}, \cs{addvspace}, \cs{textbackslash} and
other commands simply passed their argument to a \TeX{} primitive to
produce the necessary space.
```

Is `textbackslash` really part of this change?

**Comment by FrankMittelbach** [comment]
no that was supposed to say `\cs{\textbackslash}`  - thanks
