### ISSUE TITLE
\bigskip, \medskip, and \smallskip

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex2e#398]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\renewcommand\bigskip[1][1]{\vspace{#1\bigskipamount}}
% instead of \def\bigskip{\vspace\bigskipamount}

\begin{document}

foo

\bigskip
bar

\bigskip[2]
baz
  
\end{document}
```

It would be nice, if we can have an optional argument for the three macros, whcih is easier to write than
`\vspace{2\bigskipamount}`. Same for the other two length macros

**Comment by FrankMittelbach** [comment]
The problem with this is that it is a trailing optional argument, so
```
\bigskip
  [put figure here]
\bigskip
```
would suggenly blow up and that isn't a totally obscure scenario.

**Comment by car222222** [comment]
Also, the meaning of the integer parameter is not very intuitive. 

A better solution would be a user-shorthand macro/command with a mandatory argument, something like `\varbigskip {<scale>}`.

**Comment by davidcarlisle** [comment]
Note also the definition would need to be more complicated than the suggested

```
\renewcommand\bigskip[1][1]{\vspace{#1\bigskipamount}}
```
as that loses the stretch and shrink components and would make `\bigskip` a fixed length

**Comment by car222222** [comment]
Sure, that is a silly nuisance factor!  
You will need a little arithmetic to 'preserve the glue'!
