### ISSUE TITLE
Is it possible to detect free spaces in a document to place images?

### ISSUE THREAD

**Issue by Brunn3r** [latex3/latex2e#40]
Hi,

We generate PDFs with dynamic content. Moreover we would like to place some additional images or advertisements at blank spots in the document.

For example we have a page with a title and a description on the first page. 40% of the page is blank, so we would like to place an image there to fill the page.

Is there a way to get this behavior?

Thanks in advance

**Comment by davidcarlisle** [comment]
Thank you for your enquiry but the issue tracker is for bug reports and feature requests, we can not offer latex help through this channel, you could ask a question on stackexchange
https://tex.stackexchange.com/

You could modify the output routine to detect underfull pages, but whether your title page is underfull or not depends on whether the white space has been naturally added to that length or stretched to fill the page, and several other details specific to the document and can't really be tracked in this issue tracker for the latex base code.

David
