### ISSUE TITLE
BibTeX unusable for \include on LaTeX2e 2020-10-01

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#400]
## Brief outline of the bug

Using LaTeX2e 2020-10-01, BibTeX cannot be used for \include file, since the `\@input` file name of .aux is enclosed in quote.

```
This is BibTeX, Version 0.99d (TeX Live 2021/dev)
The top-level auxiliary file: bibinc.aux
"bibinc1.aux" has a wrong extension---line 2 of file bibinc.aux
 : \@input{"bibinc1.aux"
 :                      }
I'm skipping whatever remains of this command
The style file: plain.bst
I found no \citation commands---while reading file bibinc.aux
Database file #1: bibinc0.bib
(There were 2 error messages)
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
%\RequirePackage[2020/02/02]{latexrelease}

\begin{filecontents}[overwrite]{\jobname0.bib}
@book{knuth,
  author = {Knuth, Donald E.},
  title = {The TeXbook},
  publisher = {Addison-Wesley},
  year = 1984
}
\end{filecontents}

\begin{filecontents}[overwrite]{\jobname1.tex}
Cite 1: \cite{knuth}.
\end{filecontents}

\documentclass{book}
\begin{document}

\include{\jobname1}

\bibliographystyle{plain}
\bibliography{\jobname0}

\end{document}
```

## Log file (required) and possibly PDF file  

* Current LaTeX2e 2020-10-01: [20201001.zip](https://github.com/latex3/latex2e/files/5321947/20201001.zip)
* Using `\RequirePackage[2020/02/02]{latexrelease}`: [20200202.zip](https://github.com/latex3/latex2e/files/5321946/20200202.zip)

BTW, `latexbug` complains about third-party file `expl3.ltx` which is obviously not, when `\RequirePackage[2020/02/02]{latexrelease}` is used.

**Comment by eg9** [comment]
I guess this is the result of the attempt to quote all file names, in order to cope with spaces and other special characters. Unfortunately, `bibtex` doesn't know about quoted file names.

**Comment by u-fischer** [comment]
as a work-around you can remove the quotes, they look quite unneeded. But the file name should not contain spaces if bibtex is involved as it can't handle this. 

~~~~
\usepackage{etoolbox}
\makeatletter
\patchcmd\@include{\@input{"#1.aux"}}{\@input{#1.aux}}{}{\fail}
\makeatother
~~~~

**Comment by FrankMittelbach** [comment]
A fix was added to firstaid which is on its way to CTAN. In a few days this will be replaced by a PL1 for the kernel

**Comment by FrankMittelbach** [comment]
that wasn't to be closed before PL1 or at least the firstaid is out ... not sure how that came about

**Comment by mrpiggi** [comment]
> not sure how that came about

Because you pushed to the default branch master and used 'magic' commit message containing `...fix #400...`

**Comment by FrankMittelbach** [comment]
Has this to do with the fact that it was to master which I normally don't do?

**Comment by mrpiggi** [comment]
exactly. as soon as you are using a keyword like 

+ close(s|d)?
+ fix(es|ed)?
+ resolve(s|d)?

directly followed by `#<nr>` within a commit message, the issue will be closed either immediately on default branch---which is mostly master--- or automatically when the commit is pushed to master in future.
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by franpog859** [comment]
Hey, guys! The error appears in my project. I'm new to the LaTeX world so I don't really know how to deal with it. May I ask you for guidance on how to fix it without any workarounds? Is the fix already released so I can update something and it'll work again?

**Comment by PhelypeOleinik** [comment]
@franpog859 Yes, the fix is already in the kernel, so an update should suffice (`tlmgr update --all` if you use TeXLive, or update `latex-base` (or `base`, I'm not sure) if you use MiKTeX).

When you run LaTeX you should see, at the top of the `.log`:
```latex
LaTeX2e <2020-10-01> patch level 1
```
as opposed to the version with this bug:
```latex
LaTeX2e <2020-10-01>
```

**Comment by franpog859** [comment]
Beautiful, @PhelypeOleinik ! I ran `sudo tlmgr update --self` and `sudo tlmgr update --all` and it works superbly. Thank you!
