### ISSUE TITLE
Number of arguments for \AddToHook rollback

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#401]
## Brief outline of the bug

Using latexrelease, the optional argument of \AddToHook cannot be gobbled.

```
! LaTeX Error: Missing \begin{document}.
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\RequirePackage[0000/00/00]{latexrelease}

% suppose some package detect LaTeX2e 2020-10-01
% and add some

\ifdefined\AddToHook
  \AddToHook{begindocument}[mypackage]{\relax}
\fi

\show\AddToHook %==> \AddToHook=\long macro:#1#2->.
```

## Log file (required) and possibly PDF file  

* [hook.log](https://github.com/latex3/latex2e/files/5322696/hook.log)

lthook.dtx says

> Rolling back here doesn’t undefine the interface commands
> as they may be used in packages without rollback functionality.

but it's a pity that some packages intended for rollback do not work.

**Comment by aminophen** [comment]
BTW: could you tell us how to support rollback properly?

Suppose you want to execute "some JP code" at \sffamily as follows:

* for LaTeX2e 2020-10-01: use `\AddToHook{sffamily}{some JP code}`
* for LaTeX2e 2020-02-02: use `\g@addtomacro{\@sffamilyhook}{some JP code}`
* for ancient LaTeX2e: redefine \sffamily manually to add "some JP dode"

I tried to do it as follows, but it does not work properly for rollback, since `\AddToHook` is defined but no-op.

``` tex
\ifdefined\AddToHook
  % 2020-10-01
\else\ifdefined\@sffamilyhook
  % 2020-02-02
\else
  % ancient
\fi\fi
```

The package "etoolbox" also has a similar test

``` tex
\ifdef\AddToHook
  {%
    \newrobustcmd*{\AtEndPreamble}{\AddToHook{begindocument/before}}%
    \let\AfterPreamble\AtBeginDocument
    \newrobustcmd*{\AfterEndPreamble}{\AddToHook{begindocument/end}}%
    \newrobustcmd*{\AfterEndDocument}{\AddToHook{enddocument/end}}%
    \endinput
  }
  {}
```

buy it would not work for similar reason.

**Comment by FrankMittelbach** [comment]
I mixed up the the definitions for `\AddToHook` and `\AddToHookNext` in the rollback code :-(
The fix will show up in PL1 in a few days, but let's first see if there are other issues discovered.

As to doing rollback in packages/classes, a test for `\AddToHook` is obviously wrong, instead do
```
\providecommand\IfFormatAtLeastTF{\@ifl@t@r\fmtversion}
\IfFormatAtLeastTF{2020-10-01}
   { code for 2020-10-01 }
   {\IfFormatAtLeastTF{2020-02-02}
      { code for 2020-02-02 }
      { code for older kernels }
```
The etoolbox package was updated before the hook stuff was finalized, so the test there need to be changed by @josephwright at some point too.

**Comment by aminophen** [comment]
@FrankMittelbach Thanks.

\IfFormatAtLeastTF{2020-10-01} would work, but \IfFormatAtLeastTF{2020-02-02} would not be correct because `\@sffamilyhook` and co. were added in 2020-02-02 PL2.  I rather prefer functionality-based conditionals, and it could be achieved if latexrelease.sty simply undefined those.  You already know that silently gobbling hooks would not work as the author expects either, so what is the importance of simply avoiding errors?

**Comment by FrankMittelbach** [comment]
> You already know that silently gobbling hooks would not work as the author expects either, so what is the importance of simply avoiding errors?

it is a judgement call (and perhaps a bad judgement). But if, for example, a package adds some ordering rules then it would most likely continue to work in a rollback situation even if it doesn't provide rollback itself. And the same can be true (but may not be) it if something like \AddToHook is used. Of course, the correct thing is that a package does provide rollback but ...

**Comment by aminophen** [comment]
OK, I will use \IfFormatAtLeastTF.

**Comment by josephwright** [comment]
@FrankMittelbach  I've adjusted `etoolbox`
