### ISSUE TITLE
TU encoding is missing some declarations

### ISSUE THREAD

**Issue by eg9** [latex3/latex2e#404]
## Outline of the enhancement

Among the “hyphens and dashes” group in Unicode, U+2011 to U+2015, TU only defines `\textendash` and `\textemdash`, respectively U+2013 and U+2014.

Adding support for U+2011 NON-BREAKING HYPHEN, U+2012 FIGURE DASH and U+2015 HORIZONTAL BAR seems necessary.

In `xunicode.sty`, U+2012 is called `\textthreequartersemdash`, but it seems a badly chosen name, as well as `\texttwelveudash` for U+2015.

These names should probably be kept for backwards compatibility, but declared deprecated.

U+2011 `\textnbhyphen` (or a longer name)
U+2012 `\textfiguredash` (with `\textthreequartersemdash` as alias)
U+2013 `\textendash` (already defined)
U+2014 `\textemdash` (already defined)
U+2015 `\texthorizontalbar` (with `\texttwelveudash` as alias)

Reference: https://tex.stackexchange.com/q/565751/4427

Since these are additions, they should not break existing documents, so long as they don't have defined the commands themselves, which is why I propose also the aliases.

**Comment by FrankMittelbach** [comment]
Am 07.10.20 um 12:54 schrieb Enrico Gregorio:
> In |xunicode.sty|, U+2012 is called |\textthreequartersemdash|, but it 
> seems a badly chosen name, as well as |\texttwelveudash| for U+2015.
> 
> These names should probably be kept for backwards compatibility, but 
> declared deprecated.
> 

is there really a need for the strange xunicode names?  Do you think 
people take xunicode out of existing old documents and then fall over? 
because for new documents it might be better if they (can) use only the 
official Unicode names in my opinion.

**Comment by FrankMittelbach** [comment]
Should `\textfiguredash` and `\texthorizontalbar` retrofitted into T1 and OT1 encodings as well (as  `--` and `------`)?
And what about `\textnonbreakinghyphen` ?  as something horrible as `\leavevmode\nobreak-`?

**Comment by FrankMittelbach** [comment]
Problem: neither 2012 nor 2015 is available in the LM fonts as far as I can see which is the default font for LaTeX in Unicode engines and as the example shows with Garamond also not in other fonts. So would it make sense to provide it as
```
\DeclareTextCommand{\textfiguredash}     \UnicodeEncodingName
     {\iffontchar\font "2012 \char "2012 \else \char "2013 \fi}
\DeclareTextCommand{\texthorizontalbar}     \UnicodeEncodingName
     {\iffontchar\font "2015 \char "2015 \else \char "2014 \char "2014 \fi}
```
i.e. with some approximation?

**Comment by car222222** [comment]
I need to find some pictures to decide what is the best approximation.  Or I can look up to check westbound Unicode states about how long each of these should be.

Very lazy font designer not to add all possible lengths:-).

**Comment by blefloch** [comment]
Should there be some additional ActualText magic to allow correct copying of
these from the pdf even in the fallback case?

**Comment by FrankMittelbach** [comment]
> Should there be some additional ActualText magic to allow correct copying of these from the pdf even in the fallback case?

maybe one day when we get to providing such stuff generally. I do't think this is a good idea to provide adhoc ActualText just here (we don't do this for anything else and  OT1, T1 do that for many characters (and even TU in some places))

**Comment by FrankMittelbach** [comment]
> I need to find some pictures to decide what is the best approximation. Or I can look up to check westbound Unicode states about how long each of these should be.

I believe the approximation to use en-dash for figure dash and twice em-dash for the horizontal bar is reasonable (from what I  have seen in fonts that actually have them. By the end of the day you can't get anything perfect anyway as you don't  know what the designer would choose had he/she provided the glyph. So it is also a question of being reasonable in complexity as well as being fairly reasonable in outcome --- certainly anything is better than a full failure.

> Very lazy font designer not to add all possible lengths:-).

there is that.

**Comment by car222222** [comment]
There seems to be little agreement about the length of 'horizontal bar' in the Unicode literature.  It is variously described as being: between the en- and em-dashes; same as em-dash; up to twice em-dash.

Maybe it should not be considered a text/punctuation character at all!

**Comment by FrankMittelbach** [comment]
> There seems to be little agreement about the length of 'horizontal bar' > in the Unicode literature. It is variously described as being: 
between > the en- and em-dashes; same as em-dash; up to twice em-dash.
if it is actually more often between en and em-dash (as wikipedia 
claims) then perhaps the best approximation to use an em-dash if 
unavailable (not 2)

> Maybe it should not be considered a text/punctuation character at all!

by whom? by unicode? it seems to be there accepted as a quotation intro dash

**Comment by car222222** [comment]
Yes, I found that suggestion about the 'quoted speech' usage.  But that usage seems to be associated with a length longer than em-dash, I have seen this usage in actual books.  For this a different (extra) name would be good: \textquotedash (cf. \textfiguredash).

On figure dash, I shall quote in full:
"Similar to an en dash, but with exactly the width of a digit in the chosen typeface. The vertical position may also be centered on the zero digit, and thus higher than the en dash and em dash, which are appropriate for use with lowercase text in a vertical position similar to the hyphen. The figure dash may therefore be preferred to the en dash for indicating a closed range of values."

Thus, it seems that designers clearly should be concerned with figure dash and, even if their aesthetic determines that it should be identical to en-dash in their font, the glyph should still be accessible via both code points.

**Comment by zauguin** [comment]
> Yes, I found that suggestion about the 'quoted speech' usage. But that usage seems to be associated with a length longer than em-dash, I have seen this usage in actual books. For this a different (extra) name would be good: \textquotedash (cf. \textfiguredash).

I wouldn't use an extra name here. The use of "horizontal bar" for this is officially recognized by the Unicode standard, to the degree that "quoted dash" is an official alias for "HORIZONTAL BAR". Also there don't seem to be any real other usecases for the horizontal bar. So we would only introduce confusion if we split them and deviate from Unicode in tiny ways here. Also using another glyph for the quotation dash would go against the wishes of any font designer who relied on official Unicode rules when designing their glyphs. So if someone wants longer dashes here, they should use a font which provides the right length. 

Since the name "HORIZONTAL BAR" seems quite imprecise, I would be neutral towards renaming it to \textquotationdash. While I would consider that name more readable, it is less discoverable for people used to working with Unicode. (Which are probably most people who care about such differences these days)

**Comment by car222222** [comment]
I was not suggesting to split 'horizontal bar' and 'quote dash', or renaming it (to something like \textquote(s)dash); only maybe providing some such as additional name (one that reflects its major intended use).  Sorry for any misunderstanding.
