### ISSUE TITLE
ltfssini: Typo and redundant code

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/latex2e#405]
There is a missing `t` in `default`:
https://github.com/latex3/latex2e/blob/aa9592e6e1b4e17f721365ccc5b5767b884e5cec/base/ltfssini.dtx#L1079

However, the exact same line (without typo) appears way down in the same document again:
https://github.com/latex3/latex2e/blob/aa9592e6e1b4e17f721365ccc5b5767b884e5cec/base/ltfssini.dtx#L1794

**Comment**: One of these two lines should perhaps be removed (after the typo has been corrected, of course).

**Comment by FrankMittelbach** [comment]
thanks
