### ISSUE TITLE
Error message in \renewcommand

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#41]
## Brief outline of the bug

Is there any plan for fixing [the "bug" in error message](https://tex.stackexchange.com/questions/134859/problem-redefinning-command/134871#134871)?

`! LaTeX Error: \1undefined.`

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\renewcommand{\1}{A}
```

## Log file (required) and possibly PDF file  

[sx134859.log](https://github.com/latex3/latex2e/files/1957623/sx134859.log)

**Comment by FrankMittelbach** [comment]
I can't see a reason why not, but as this is nothing essential we will do them as part of one of the next patches or the next release.
