### ISSUE TITLE
\vb@xt@

### ISSUE THREAD

**Issue by rolfn** [latex3/latex2e#412]
## Brief outline of the enhancement

LaTeX2e already defined the auxiliary macro `\hb@xt@`. Sometimes it would be desirable to be able to use `\vb@xt@` as well:
```
\def\vb@xt@{\vbox to}
```
Thank you for the years of work on LaTeX.

**Comment by FrankMittelbach** [comment]
Rolf, such kind of macros with several `@`signs in the name have never been really meant as macros for general use and their introduction was mainly for fighting the severe memory limits LaTeX had back then. They do not make code easier to understand or faster. So these days we rather work on moving aways from them and will therefore not introduce additional `@` monsters if we can avoid it. So I doubt you will get many thumbs up :-)

**Comment by rolfn** [comment]
OK. I understand.
