### ISSUE TITLE
Angle symbols which can be copy and pasted from PDF

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#420]
It would more pleasant when one copy-paste e.g. `\seq_map_indexed_inline:Nn ⟨seq var⟩ {⟨inline function⟩}` to get:

- `\seq_map_indexed_inline:Nn ⟨seq var⟩ {⟨inline function⟩}`
- instead of `\seq_map_indexed_inline:Nn hseq var i {hinline function i}`.

Hence, what about one of the solutions provided for [this question](https://tex.stackexchange.com/q/18146/18401) for the various `latex3` documentations that involve `\meta`?

**Comment by FrankMittelbach** [comment]
That should be fixed by #465, correct @zauguin ? Iassume yes and adjusted the state :-)
