### ISSUE TITLE
LaTeX2e 2020-10-01: when loaded by relative path, pkg options are ignored

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#422]
## Brief outline of the bug

For example, when package `mypkg.sty` located in `./style/mypkg.sty` is loaded by `\usepackage[key1]{style/mypkg}`,
 - until LaTeX2e 2020-02-02, package option `key1` is processed, but
 - from LaTeX2e 2020-10-01, package option `key1` is never processed.

I know that loading a package by using relative path is a bad practice, but some thesis templates (for example, [mohuangrui/ucasthesis](https://github.com/mohuangrui/ucasthesis)) use this trick to make the use of template portable.

## Minimal example showing the bug

Directory structure:
```tex
.
├── sty-option-test.tex
└── style
    └── mypkg.sty
```

```latex
% \RequirePackage{latexbug} % third-party file "mypkg.sty" required
\documentclass{article}
\usepackage[key1]{style/mypkg}

\begin{document}
content
\end{document}
```

```latex
% this is file "mypkg.sty" located in sub-dir "./style"
\ProvidesPackage{mypkg}

\DeclareOption{key1}{\PackageError{mypkg}{error text}{}}
\ProcessOptions\relax
```

## Log file (required) and possibly PDF file  

The following log files are produced with applying
```latex
\tracingall
\usepackage[key1]{style/mypkg}
\fail
```
[sty-option-test-20201001.log](https://github.com/latex3/latex2e/files/5469266/sty-option-test-20201001.log), with LaTeX2e <2020-10-01> patch level 2
[sty-option-test-20200202.log](https://github.com/latex3/latex2e/files/5469267/sty-option-test-20200202.log), with LaTeX2e <2020-02-02> patch level 5, the one currently provided by overleaf

**Comment by muzimuzhi** [comment]
Perhaps the template author(s) should use something like
```tex
\makeatletter
\def\input@path{{./style}}
\makeatother

\usepackage[key1]{mypkg}
```

**Comment by PhelypeOleinik** [comment]
Thanks!  I have to check carefully, but I'm almost certain this is caused by the same as #421 (thus the same temporary patch should work), and apparently came to life when I fixed #414.

**Comment by muzimuzhi** [comment]
> Perhaps the template author(s) should use something like
> 
> ```
> \makeatletter
> \def\input@path{{./style}}
> \makeatother
> 
> \usepackage[key1]{mypkg}
> ```

Or, if the new features of LaTeX2e 2020 fall are not used, roll back to LaTeX2e 2020-02-02
```tex
\RequirePackage[2020/02/02]{latexrelease}
\documentclass{article}
\usepackage[key1]{style/mypkg}
```

**Comment by PhelypeOleinik** [comment]
Keeping this open until the patch release.

**Comment by FrankMittelbach** [comment]
Part of PL3

**Comment by xexeo** [comment]
This seems to affect \@ifclassloaded and \@ifpackageloaded too. They will not recognize a class or package as loaded if they are in another directory. They, however, recognize the path/name combination.

**Comment by FrankMittelbach** [comment]
@xexeo if you think there is still an issue please make a compilable short example o what you think is the problematical behavior.

**Comment by xexeo** [comment]
Just made a minimal example and have different results according to the LaTeX version being used, newer versions working well.

Directory Structure
````
.\document.tex
.\styles\pack.sty
.\styles\minimal.cls 
```

minimal.cls was copied from minimal package on CTAN

document.tex is

```
\documentclass{styles/minimal}
\usepackage{styles/pack}
\makeatletter
\@ifpackageloaded{pack}
{\def\packpresent{YES}}
{\def\packpresent{NO}}
\@ifclassloaded{minimal}
{\def\minimalpresent{YES}}
{\def\minimalpresent{NO}}
\makeatother
\begin{document}
    
    \LaTeX{} version: \LaTeXe~\fmtversion
    
    Pack is loaded \packpresent%
    
    Minimal is loaded \minimalpresent%
\end{document}
```
While pack.sty is
```
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{pack}[2021/06/09 1.0 pack]
\def\packdef{this is a test}
\endinput
```

I just noticed that I found the problem in Overleaf, which is running LaTeX 2E 2020-02-02. This code does not work there, showing NO for both answers.

However, it works in LaTeX 2E 2020-10-01 and 2021-06-01 (pdfLaTeX, LuaLaTeX, XeTeX and LaTeX) - Current and Previous MikTeX distribution

 I don´t know how to check the HotFix is working, but I hope that this can be used as a test.

Thanks for your work,

**Comment by PhelypeOleinik** [comment]
That sounds correct, the hotfix in question was applied to LaTeX 2020-10-01, so it's present from that point onwards.  Overleaf updated their TeX Live 2020 before that release, so in their version this still shows the old behaviour.  In Overleaf you'd have to write `\@ifpackageloaded{styles/pack}` or add `styles` to `\input@path`

**Comment by FrankMittelbach** [comment]
Don't want to make a promise ,but what might work (or not) is to pick up a latexrelease.sty from a current version and stick it onto overleaf to make a rollforward.  The focus of latexrelease to to roll back and roll foward is a sideeffect we try to support but it isn't the *focus* (and notoriously difficult to work well). If if it doesn't  it is not going to be fixed.

**Comment by PhelypeOleinik** [comment]
@xexeo Indeed, grabbing a recent `latexrelease.sty` (for example [from here](https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/base/latexrelease.sty?view=co)), and adding `\RequirePackage[latest]{latexrelease}` or `\RequirePackage[2020-06-01]{latexrelease}` at the very top of the document works fine.
