### ISSUE TITLE
rollback with amsmath

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#423]
## Brief outline of the bug

I'm not sure how to use rollback with \usepackage{amsmath}:

* With `\RequirePackage[2018/12/01]{latexrelease}`, it raises an error:

```
! LaTeX Error: Command \negmedspace already defined.
               Or name \end... illegal, see p.192 of the manual.
```

* With `\RequirePackage[2018/11/30]{latexrelease}`, another error is raised:

```
! LaTeX Error: Suspicious rollback date given.
```

## Minimal example showing the bug

``` latex
\RequirePackage{latexbug}
\RequirePackage[2018/12/01]{latexrelease}
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\stop
```

## Log file (required) and possibly PDF file  

* [20181201-ams.log](https://github.com/latex3/latex2e/files/5509784/20181201-ams.log)
* [20181130-ams.log](https://github.com/latex3/latex2e/files/5509782/20181130-ams.log)

**Comment by FrankMittelbach** [comment]
looks like a bug in the rollback code. amsmath load its version from 2018-12-01 in which `\negmedspace`is defined with `\newcommand`, but the main rollback doesn't undefine the command :-(

As a workaround
```
\RequirePackage[2018/12/01]{latexrelease}
\let\negmedspace\undefined
\let\negthickspace\undefined
```
avoids that error, but of course it should be fixed.

Concerning the suspicous rollback date, the extended help there says
```
The package 'amsmath' claims that it came into existence on 2018-12-01 which
is after your requested rollback date --- so something is wrong here.
Continue and we use the earliest known release.
```
However if would be more accurate to state something like
```
The package 'amsmath'  has no rollback data before 2018-12-01 which
is after your requested rollback date --- so something may be wrong here.
Continue and we use the earliest known release.
```
I guess we should alter that one too.

**Comment by FrankMittelbach** [comment]
a fix should appear in the next patch release

**Comment by FrankMittelbach** [comment]
Part of PL3

**Comment by davidcarlisle** [comment]
> I still have this problem.

This was fixed in texlive 2021, are you running an old release? (There is not much we can do for old releases other than suggest that you upgrade)
