### ISSUE TITLE
Recent LaTeX core update breaks ltxkeys package: Extra \endgroup

### ISSUE THREAD

**Issue by juliangilbey** [latex3/latex2e#425]
## Brief outline of the bug

Attempting to load the `ltxkeys` package now breaks; it worked fine with LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-09-24>, but breaks with LaTeX2e <2020-10-01> patch level 2
L3 programming layer <2020-10-27> xparse <2020-03-03>.  I don't know whether this is a bug in the kernel or that the `ltxkeys` package needs to be updated for the new hook system.

I have done a little bit of exploration of this, but have not got very far.  I thought it might be to do with latex2e-first-aid-for-external-files.ltx introducing an extra `\endgroup` but that's not the case: introducing a `\message{\meaning\document}` before the `\begin{document}` line shows similar results in both cases:

Older LaTeX (works):
```
macro:->\endgroup \let \BeforeStartOfDocument \@firstofone \cpt@beforestartdoc 
\let \BeforeStartOfDocument \@notprerr \gundefcs \cpt@beforestartdoc \gdef \cpt
@docstarted {}\begingroup \endgroup \@expl@sys@load@backend@@ \begingroup \endg
roup \ifx \@unusedoptionlist \@empty \else \@latex@warning@no@line {Unused glob
al option(s):
[rest trimmed]
```

Newer LaTeX (doesn't work):
```
macro:->\endgroup \let \BeforeStartOfDocument \@firstofone \cpt@beforestartdoc 
\let \BeforeStartOfDocument \@notprerr \gundefcs \cpt@beforestartdoc \gdef \cpt
@docstarted {}\begingroup \UseOneTimeHook {begindocument/before}\@kernel@after@
begindocument@before \@expl@sys@load@backend@@ \ifx \@unusedoptionlist \@empty 
\else \@latex@warning@no@line {Unused global option(s):
[rest trimmed]
```

So something is breaking the deep magic of balancing the `\begingroup` and `\endgroup`; perhaps it's that ltxkeys relies on low-level LaTeX kernel behaviour that has just changed?

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{ltxkeys}
\begin{document}
\end{document}
```

## Log file (required) and possibly PDF file  

```latex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex 2020.11.4)  15 NOV 2020 21:56
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**test
(./test.tex
LaTeX2e <2020-10-01> patch level 2
L3 programming layer <2020-10-27> xparse <2020-03-03>
(/usr/local/texlive/2020/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2020/09/25 v1.0h Bug-classification
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2020/04/10 v1.4m Standard LaTeX file (size option)
)
\c@part=\count175
\c@section=\count176
\c@subsection=\count177
\c@subsubsection=\count178
\c@paragraph=\count179
\c@subparagraph=\count180
\c@figure=\count181
\c@table=\count182
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
)
(/usr/local/texlive/2020/texmf-dist/tex/latex/ltxkeys/ltxkeys.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/catoptions/catoptions.sty
\m@one=\count183
\z@pt=\dimen139
Package: catoptions 2014/08/29 v0.2.7h Securing catcodes and parsing options (A
M)
\cpt@csvdepth=\count184
\cpt@optdepth=\count185
\cpt@cnta=\count186
\indrisdepth=\count187
\cpt@foreachdepth=\count188
\cpt@exprcnt=\count189
)
Package: ltxkeys 2012/11/17 v0.0.3c A robust key-value parser (AM) (Ahmed Musa)

\ltxkeys@csvdepth=\count190
\ltxkeys@keydepth=\count191
)
! Extra \endgroup.
\document ->\endgroup 
                      \let \BeforeStartOfDocument \@firstofone \cpt@beforest...
l.4 \begin{document}
                    
? x
 
Here is how much of TeX's memory you used:
 2694 strings out of 479485
 43454 string characters out of 5871978
 346634 words of memory out of 5000000
 19784 multiletter control sequences out of 15000+600000
 535088 words of font info for 29 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 67i,0n,79p,141b,498s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.
PDF statistics:
 0 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

```

**Comment by PhelypeOleinik** [comment]
This is `catoptions`'s fault:  it does some deep changed to the LaTeX kernel which are incompatible with the latest version.  The author has been notified quite some time ago, but no update so far.

If you use `ltxkeys` in your own code, I suggest you adapt to a different key-value package (lots of options [here](https://tex.stackexchange.com/q/26771/134574); the choice might depend on your application).

If `ltxkeys` is loaded by another package you use, then you can try one of the workarounds in #411, but they are not really guaranteed to work.

What is your use-case for `ltxkeys`?

**Comment by juliangilbey** [comment]
Thanks @PhelypeOleinik!

I had written a class file for typesetting a certain structured document, and used `ltxkeys` to begin a new environment which starts with a table of data given in the keys. But I guess I'll have to move to something else now.  I'll inform the author of `ltxkeys`.

Best wishes,

   Julian

**Comment by PhelypeOleinik** [comment]
Well, the author of `ltxkeys` is the author of `catoptions`, so he's already informed.  But I guess some pressure might lead to an update.

A widely used key-val package is `kvoptions` (used, for example, by `hyperref`).  Another good option, usually used by packages written in `expl3` (but can also be used otherwise) is `l3keys2e`.

If you're interested in performance, take a look at the documentation of [`expkv`](http://mirrors.ctan.org/macros/generic/expkv/expkv.pdf): it brings some benchmarking of key-value packages.  `expkv` itself has an auxiliary `expkv-opt` package for managing package and class options.
