### ISSUE TITLE
Optional argument of \\ not consumed in \begin{letter} of letter class (possible regression)

### ISSUE THREAD

**Issue by callegar** [latex3/latex2e#427]
## Brief outline of the bug

The `\\` command is expected to take an optional parameter specifying a lenght, so that a vertical space as large as the given length is introduced together with the line break.

However, in the argument of the `\begin{letter}` environment of the `letter` class the `\\` does not work properly, being unable to consume its optional parameter *on first use*. 

As a consequence, if in the `\begin{letter}` environment the first `\\` uses the optional length, the optional argument gets *printed* rather than interpreted as an option. This happens both in the standard letter class and in the KOMA script `scrlttr2` letter class.

The issue may have to do with recent changes to `\\` applied in 2020. 

## Minimal example showing the bug

Please, consider the following test case 

```latex
\RequirePackage{latexbug}
\documentclass{letter}

\begin{document}
\begin{letter}{First line\\[1ex]
    Second line\\
    Third line\\
    Fourth line\\[1ex]
    Fifth line\\
    Sixth line\\
    Seventh line}

  \opening{Dear Sirs,}
  Blah Blah Blah\dots
  \closing{Best regards}
\end{letter}
\end{document}
```

Here, a minimal letter should be produced where the addressee specified as the argument of the `letter` environment should contain seven lines with a wider line break in between the first and the second line and in between the fourth and the fifth line.

However, when the example is compiled using a recent latex format, the first line break introduced by `\\[1ex]` does not work properly. The `[1ex]` is not interpreted as an optional parameter and not consumed by `\\` remaining in the input stream. Consequently, the printed letter ends up containing the text `[1ex]` at the beginning of the second addressee line.

After the first use of `\\`, the command starts working properly. In fact, the `\\[1ex]` after the fourth line is interpreted correctly, leaving a larger space in between the fourth and the fifth addressee lines.

## Log file and PDF file  

[testcase.log](https://github.com/latex3/latex2e/files/5571947/testcase.log)
[testcase.pdf](https://github.com/latex3/latex2e/files/5571948/testcase.pdf)

**Comment by u-fischer** [comment]
This is not new behaviour, at least for letter.cls. I get the same with a texlive 2017 and texlive 2014 (tested on overleaf).  The code splits up the \fromname at the first `\\ ` and this leaves the optional argument in the stream.

**Comment by davidcarlisle** [comment]
as Ulrike says this is not a recent change I think it has been there forever.

I think addition of one `\expandafter` is all that is needed

```
\documentclass{letter}

\makeatletter
\renewcommand*\opening[1]{\ifx\@empty\fromaddress
  \thispagestyle{firstpage}%
    {\raggedleft\@date\par}%
  \else  % home address
    \thispagestyle{empty}%
    {\raggedleft\begin{tabular}{l@{}}\ignorespaces
      \fromaddress \\*[2\parskip]%
      \@date \end{tabular}\par}%
  \fi
  \vspace{2\parskip}%
  {\raggedright \toname \expandafter\\\toaddress \par}%
                        %%%%%%%%%%%%%
  \vspace{2\parskip}%
  #1\par\nobreak}
\makeatother

\begin{document}
\begin{letter}{First line\\[1ex]
    Second line\\
    Third line\\
    Fourth line\\[1ex]
    Fifth line\\
    Sixth line\\
    Seventh line}

  \opening{Dear Sirs,}
  Blah Blah Blah\dots
  \closing{Best regards}
\end{letter}
\end{document}
```

**Comment by blefloch** [comment]
Workaround: expand the `\toaddress` (which starts with `[1ex]`) before using it.  I haven't checked if there are other places where it should be changed.  Conceptually, the correct fix would be to also parse an optional argument (and star) when splitting into `\toname` and `\toaddress`, and keep the separator in some other variable, say, `\toseparator`.
```
\documentclass{letter}
\usepackage{etoolbox}
\patchcmd{\endletter}{\\\toaddress}{\expandafter\\\toaddress}{}{}
\patchcmd{\opening}{\\ \toaddress}{\expandafter\\\toaddress}{}{}
\begin{document}
\begin{letter}{First line\\[1ex]
    Second line\\
    Third line\\
    Fourth line\\[1ex]
    Fifth line\\
    Sixth line\\
    Seventh line}

  \opening{Dear Sirs,}
  Blah Blah Blah\dots
  \closing{Best regards}
\end{letter}
\end{document}
```

**Comment by davidcarlisle** [comment]
@blefloch  yes, the endletter patch isn't actually needed as that's in a `\write` so it all gets expanded anyway. I wondered about moving the parsing earlier but `\toaddress`  isn't used elsewhere so it's not too bad if it has the optional argument at the start, and given that  this code has been there for decades and probably copied in to multiple local letter-like classes minimising the changes used in the fix is probably good.  the main disadvantage is that in the somewhat unlikely case that there is just one line but terminated with `\\[2pt]` then this test `  \ifx\toaddress\@empty` will take the non-empty address branch, but nothing too bad happens (and better than typesetting the argument as text, as happens now).

**Comment by FrankMittelbach** [comment]
As mentioned, this isn't anything new and I'm pretty sure it dates back to LaTeX 2.09 i.e. to 1986. The `\\` was only ever implemented as a seprator not as something the allows for formatting information. I think we can safely apply the  solution suggested by @blefloch, but given that in 35 years nobody else ever has stumbled upon it and bothered to report it, I think going beyond and changing the splitting method is not worth it (and may cause more than gain as it may break other classes that are based upon letter.cls).

**Comment by davidcarlisle** [comment]
just looking at classes that accept the syntax of this example, at least these classes in texlive need a similar patch

akletter.cls
bletter.cls
letter.cls
chletter.cls
extletter.cls
frletter.cls
hletter.cls
scrlttr2.cls
lettre.cls
beletter.cls
brief.cls

**Comment by JohannesBraams** [comment]
I'm responsible for brief.cls, So, once decided on a patch I'll tackle 
that one.
I must say I never had someone send me a similar complaint yet.

Come to think of it, are there other places where the use of " \\" is 
intended as a separator, not as a line ending with an optional argument 
(\author has \and for that purpose, but...)

Johannes

**Comment by FrankMittelbach** [comment]
As I said, my guess that this a really something that was never attempted by users before, otherwise there would have been questions on SX or elsewhere. No harm in fixing it for letter.cls but as far as the other classes are concerned, I don't think we have the bandwidth to chase them.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  yes I wasn't planning to do anything about the others, but just putting the list there for the record as people may land here or developers of the letter variants can copy the patch (brief for example:-) . Weird that it has never come up before, as this has been this way forever...

**Comment by callegar** [comment]
I'm amazed I've run into something that has never caused any issue in so long! Sorry for assuming that it could have come from recent changes (which was just hasty on my side as I saw that `//` had received some attention in 2020).

In fact, I didn't even realize that the format was internally splitting the name and address based on the first `\\`.

I guess this means that in principle, having an addressee name that should span 2 lines one should use something different from `\\` for the first linebreak.

**Comment by callegar** [comment]
@FrankMittelbach 

> The \\ was only ever implemented as a seprator not as something the allows for formatting information 

Curious about history (since I only began using LaTeX with 2e circa 1993). Does this mean that the usage of `\\` in general text as a shorthand for `\newline` happened in the move from 2.09 to 2e?  Are there other cases in addition to `\begin{letter}` where `\\` is used as a separator to split different parts of a textual argument with no or at best a loose structure (as opposed to tabulars, mathematical arrays, etc. where there is an inherent semantic associated to the linebreaks so the `\\` clealy matches *structure* rather than *formatting*).

Asking because I am expecting the usage of `\\` in `\begin{letter}` to have aged rather badly given that almost everyone now use `\\` with the idea of introducing a linebreak rather than a separator. Are there users actual cases where `\toname` and `\toaddress` are used independently? Even if my issue has been a unicum in 35 years, I guess that the current separation logic will probably get those wrong in multiple occasions, given the way in which `\\` is used nowadays. For instance, in some languages, formal letters may require some *honorific forms* in front of the addressee like “Spettabile” which are certainly not part of the the *name* and that may need to go on a separate line if they make a too long text with the name itself.  Incidentally, this is the reason why I have stumbled into my issue.

In fact, given how we tend to do things today, it would be nice to have a keyval syntax in `\begin{letter}`. Something like:
`\begin{letter}{toprefix=Spett. ditta, toname=Mr Pinco, toaddress=xxx yyy}`. A matter of redefining `\@processto` I guess, maybe I'll try playing with that.

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach
> 
> > The \ was only ever implemented as a seprator not as something the allows for formatting information
> 
> Curious about history (since I only began using LaTeX with 2e circa 1993). Does this mean that the usage of `\\` in general text as a shorthand for `\newline` happened in the move from 2.09 to 2e?

No I meant in the letter style of 2.09 the `\\` was already implemented as it now (in the rest of 2.09 it had a star form and an optional argument but in the address field it was just `\\` (but documented as giving a new line in Lamports book -- just checked an old copy).

> Are there other cases in addition to `\begin{letter}` where `\\` is used as a separator to split different parts of a textual argument 

I guess `\shortstack` was (or maybe even is) like that

> In fact, given how we tend to do things today, it would be nice to have a keyval syntax in `\begin{letter}`. Something like:
> `\begin{letter}{toprefix=Spett. ditta, toname=Anonima Rubinetterie Lombardovenete s.r.l., toaddress=xxx\\yyy\\zzz}`. A matter of redefining `\@processto` I guess, maybe I'll try playing with that.

The letter style (or class with 2e) was always only meant as an example not really as a finished product ... already Lamport in 1986 talks about that the style may have more features "on your installation, like adding a company or university logo ..." 
and it nevery got much attention because a real letter class would be fairly individually designed.

Anyway, yes, if one would start from scratch a letter class would probably look quite different today and offer much more customizations and perhaps a key value interface.

**Comment by callegar** [comment]
As an aside, the new LaTeX hooks are great for accurately placing logos and other items constituting typical imprints of company stationery.

**Comment by FrankMittelbach** [comment]
> As an aside, the new LaTeX hooks are great for accurately placing logos and other items constituting typical imprints of company stationery.

good :-) but I hope and think they are also quite useful otherwise (and will be even more so if we get more of them over time.

**Comment by mrpiggi** [comment]
Info: This issue was [discussed for KOMA-Script](https://sourceforge.net/p/koma-script/tickets/2/) and a fix for `scrltt2/scrletter` was rejected. So at least this line can be removed. https://github.com/latex3/latex2e/blob/33b33f0f2713718a52f4689bcf586ca542ec6145/base/letter.dtx#L1037
