### ISSUE TITLE
typos in dtx

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#428]
I don't know why, but I ran a spell checker on the (% lines) of the (current dev) .dtx files. I will attach a list of typos, since it's a lot to copy/paste. I assume the buglets will be clear, but if any questions, let me know.
[dtxspell.txt](https://github.com/latex3/latex2e/files/5576611/dtxspell.txt)

**Comment by FrankMittelbach** [comment]
at least some are quite consistent :-)

**Comment by kberry** [comment]
Another one, line 588 of ltfntcmd.dtx:

%    Frank thinks that the next bit it is inefficient if done after

The "it" should be deleted.
