### ISSUE TITLE
latexrelease: Cannot emulate newer kernel

### ISSUE THREAD

**Issue by user227621** [latex3/latex2e#434]
## Brief outline of the bug

I am trying to emulate LaTeX 2020-10-01 on a system still using LaTeX 2020-02-02 PL 5. I have downloaded the latest version of `latexrelease.sty` from [GitHub](https://github.com/latex3/latex2e/releases). However, the following MWE fails.

(First reported on [StackExchange](https://tex.stackexchange.com/questions/572199))

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\RequirePackage[2020/10/01]{latexrelease}
\documentclass{article}

\begin{document}

Test.

\end{document}
```

## Log file (required) and possibly PDF file  

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.7) (preloaded format=pdflatex 2020.11.5)  24 NOV 2020 17:17
entering extended mode
**D:/XXX/Dokumente/z-latexrelease-bug/bug.tex
(D:/XXX/Dokumente/z-latexrelease-bug/bug.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-09-03>
("C:\Users\XXX\MiKTeX 2.9\tex/latex/latexbug\latexbug.sty"
Package: latexbug 2020/09/25 v1.0h Bug-classification
)
(latexrelease.sty
LaTeX Info: Redefining \IfTargetDateBefore on input line 275.
Package: latexrelease 2018/05/08 v1.0k LaTeX release emulation and tests (inclu
ding releases up to 2020-10-01)
Applying: [2019/10/01] Final dot for extension on input line 423.
Already applied: [0000/00/00] Final dot for extension on input line 440.
Applying: [2020/10/01] Pre-load expl3 on input line 451.
Skipping: expl3 code already part of the format on input line 455.
Already applied: [2020/02/02] Pre-load expl3 on input line 497.
Applying: [2020/10/01] expl3 macros added for the 2020-10-01 release on input l
ine 518.
Already applied: [0000/00/00] expl3 macros added for the 2020-10-01 release on 
input line 528.
Applying: [2020/10/01] Allow "par" in \typeout  on input line 539.
Already applied: [0000/00/00] Allow "par" in \typeout  on input line 546.
Applying: [2020/10/01] \MakeRobust  on input line 551.
Already applied: [2019/10/01] \MakeRobust  on input line 590.
Already applied: [2015/01/01] \MakeRobust  on input line 617.
Already applied: [0000/00/00] \MakeRobust  on input line 644.
Applying: [2020/10/01] Undo robustness on input line 649.
Already applied: [0000/00/00] Undo robustness on input line 665.
Applying: [2020-10-01] Add \robust@command@act  on input line 678.
Already applied: [0000-00-00] Add \robust@command@act  on input line 714.
Applying: [2020-10-01] Add \NewCommandCopy , \RenewCommandCopy , and \DeclareCo
mmandCopy  on input line 724.
Already applied: [0000-00-00] Undefine \NewCommandCopy , \RenewCommandCopy , an
d \DeclareCommandCopy  on input line 750.
Applying: [2020-10-01] Add \ShowCommand  on input line 759.
Already applied: [0000-00-00] Undefine \ShowCommand  on input line 769.
Applying: [2020-10-01] Add \@if@DeclareRobustCommand , \@if@newcommand , \@copy
@DeclareRobustCommand , \@copy@newcommand , \@show@DeclareRobustCommand , \@sho
w@newcommand  on input line 776.
Already applied: [0000-00-00] Undefine \@if@DeclareRobustCommand , \@if@newcomm
and , \@copy@DeclareRobustCommand , \@copy@newcommand , \@show@DeclareRobustCom
mand , \@show@newcommand  on input line 870.
Applying: [2018-04-01] Leave commands undefined in \@ifundefined  on input line
 882.
Already applied: [0000-00-00] Leave commands undefined in \@ifundefined  on inp
ut line 910.
Applying: [2020/10/01] Add \string@makeletter  on input line 919.
Already applied: [0000/00/00] Undefine \string@makeletter  on input line 935.
Applying: [2020/10/01] Use primitive \- in Lua\LaTeX  on input line 940.
LaTeX Info: Redefining \- on input line 942.
Already applied: [2017/04/15] Use \hyphenchar in \- on input line 955.
Already applied: [0000/00/00] Use \hyphenchar in \- on input line 966.
Applying: [2019/10/01] Make various commands robust on input line 971.
LaTeX Info: The control sequence `\allowbreak' is already robust on input line 
972.
LaTeX Info: The control sequence `\bigbreak' is already robust on input line 97
3.
LaTeX Info: The control sequence `\break' is already robust on input line 974.
LaTeX Info: The control sequence `\dotfill' is already robust on input line 975
.
LaTeX Info: The control sequence `\frenchspacing' is already robust on input li
ne 976.
LaTeX Info: The control sequence `\goodbreak' is already robust on input line 9
77.
LaTeX Info: The control sequence `\hrulefill' is already robust on input line 9
78.
LaTeX Info: The control sequence `\medbreak' is already robust on input line 97
9.
LaTeX Info: The control sequence `\nobreak' is already robust on input line 980
.
LaTeX Info: The control sequence `\nonfrenchspacing' is already robust on input
 line 981.
LaTeX Info: The control sequence `\obeylines' is already robust on input line 9
82.
LaTeX Info: The control sequence `\obeyspaces' is already robust on input line 
983.
LaTeX Info: The control sequence `\slash' is already robust on input line 984.
LaTeX Info: The control sequence `\smallbreak' is already robust on input line 
985.
LaTeX Info: The control sequence `\strut' is already robust on input line 986.
LaTeX Info: The control sequence `\underbar' is already robust on input line 98
7.
Already applied: [0000/00/00] Make various commands robust on input line 990.
Applying: [2020/10/01] The hook management on input line 1017.
\l__hook_labels_int=\count168

! Undefined control sequence.
l.1911 \NewDocumentCommand
                           \NewHook             { m }{ \hook_new:n {#1} }
? 
! Emergency stop.
l.1911 \NewDocumentCommand
                           \NewHook             { m }{ \hook_new:n {#1} }
End of file on the terminal!

 
Here is how much of TeX's memory you used:
 773 strings out of 481199
 16396 string characters out of 2913467
 249315 words of memory out of 3000000
 16466 multiletter control sequences out of 15000+200000
 535088 words of font info for 29 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 20i,0n,25p,202b,498s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!

```

**Comment by FrankMittelbach** [comment]
Ahh a roll forward issue. We try to emulate and test for this in our test suite but is is naturaly incomplete with automated test because there no really old format available within the test suite.

Try adding `\RequirePackage{xparse}` before `\RequirePackage[2020-10-01]{latexrelease}`.

**Comment by user227621** [comment]
@FrankMittelbach

When trying

```
\RequirePackage{xparse}
\RequirePackage[2020/10/01]{latexrelease}
\documentclass{article}

\begin{document}

Test.

\end{document}
```

I get

```
! Undefined control sequence.
<argument> \@kernel@after@enddocument 
                                      
l.4671 }
        
? 
```

**Comment by PhelypeOleinik** [comment]
@FrankMittelbach There are a couple other definitions that can probably be fixed with the right `latexrelease` tags (for example the `kernel` hook OP just posted). The main problem is because in (what I used to test) TL 2019 it is missing `\file_parse_full_name_apply:nN`, defined in `expl3` a couple of months ago.

Not sure how we should go about `expl3` in rolling forward.  We may copy some definitions around, but in the end we will be restrained by the engine version.  For example, rolling forward from 2018 to 2020 is basically undoable (within `latexrelease` only) because of `\expanded`...

**Comment by FrankMittelbach** [comment]
ok, good try, but not good enough then. As @davidcarlisle rolling forward is tricky and maybe it will turn out that the situation here is just too complicated to make it work in a reasonable way, due to the fact that all of the new kernel hook management will be missing which we can't easily stick into latexrelease for forward rolling.

**Comment by FrankMittelbach** [comment]
> Not sure how we should go about `expl3` in rolling forward. We may copy some definitions around, but in the end we will be restrained by the engine version. For example, rolling forward from 2018 to 2020 is basically undoable (within `latexrelease` only) because of `\expanded`...

maybe the answer has to be that roll forward across certain versions something we can't really support so instead of trying we may have to compare current fmtversion and target version and for certain combinations simply stage that roll forward is impossible (like with the case you outlined). Not sure though that 20-02-02 to 20-10-01 is unfixable.

**Comment by PhelypeOleinik** [comment]
> Not sure though that 20-02-02 to 20-10-01 is unfixable.

Yes, the 2018 to 2020 example is one extreme that really is not possible, but OP's case is likely doable.  Probably the easiest way is by copying `\file_parse_full_name_apply:nN` (expandable) from a current `expl3` into `latexrelease`, then fix the remaining missing `latexrelease` tags.

**Comment by FrankMittelbach** [comment]
Am 24.11.20 um 18:10 schrieb Phelype Oleinik:
> Yes, the 2018 to 2020 example is one extreme that really is not 
> possible, but OP's case is likely doable. Probably the easiest way is by 
> copying |\file_parse_full_name_apply:nN| (expandable) from a current 
> |expl3| into |latexrelease|, then fix the remaining missing 
> |latexrelease| tags.
> 

there is another problem it seems. The order of file loading in the 
format has changed (for a number of reasons) but not in latexrelease and 
so you find that \@kernel@after@enddocument  gets defined but only 
*after* it has been usedwhich explains the error when adding xparse.

  Of course the order of loading latexrelease can be adjusted too and 
most certainly has to, but it might be a limiting factor in both 
rollback and roll forward, because there may be similar dependencies in 
earlier chunks that assume the old order (not likely but not impossible).

**Comment by FrankMittelbach** [comment]
I put it on hotfix for now, but after analysis we might decide we do it only for the next release (or not at all).

**Comment by PhelypeOleinik** [comment]
Keeping this open until the patch release.

**Comment by FrankMittelbach** [comment]
Part of PL3
