### ISSUE TITLE
References in `latexchanges.pdf` are not hyper links

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#44]
## Brief outline of the bug
(Not a bug per se.) Would be nice if the references (especially to the GitHub issues) in the `latexchanges.pdf` file of changes to the LaTeX 2ε format could be hyper links, e.g. in section "Changes introduced in 2018-04-01 patch 3":

>Additional adjustments for GitHub issues 34 and 38, [...]

**Comment by davidcarlisle** [comment]
yes good idea, I'll try to sort something out for next time.

**Comment by davidcarlisle** [comment]
github issues, stackexchange answers and (more recent) gnats issues are hyperlinked in the version in patch level 5, on CTAN yesterday. (Hyperlinking is not on by default but is if hyperref has been loaded by the class cfg file, which is the case for the public ctan builds.)
