### ISSUE TITLE
list of the defined macros in the logfile with the debug option.

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex2e#442]
## Brief outline of the bug

With the debug option,  definitions with \cs_set are not listed in the logfile.
Is this the intended behaviour??

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}  
\documentclass{article}
\usepackage[enable-debug]{expl3}

\ExplSyntaxOn
\debug_on:n {all}
\begin{document}
\cs_new:Nn \my_baz: { baz~ }
\cs_set:Nn \my_FOO: { \my_baz: }% not listed in the log
\cs_new:Nn \my_foo: { \my_baz: }
\cs_new:Nn \my_bar: { bar~ }
\end{document}
```

## Log file (required) and possibly PDF file  

[...]
Defining \my_baz: on line 8
Defining \my_foo: on line 10
Defining \my_bar: on line 11
[...]

## the complete log.  Up-to-date TL2020

[03-05-1.log](https://github.com/latex3/latex2e/files/5610598/03-05-1.log)

**Comment by FrankMittelbach** [comment]
I would say yes. This not for tracing the usage but the declaration and `\..._set_...` is not declaring something but changing it. I'm not quite sure that the option name is perfect, it is really just logging the  declarations. With `check-declarations` you can find missing declarations.

**Comment by blefloch** [comment]
Side question: should

    \ExplSyntaxOn
    \begin{document}

reset catcodes before loading the aux file for instance?  Or is this use
unsupported in principle?  (Of course in such a simple file it doesn't matter.)

**Comment by FrankMittelbach** [comment]
@blefloch we had a chat about this in the team meeting today and the conclusion was that it is unsupported and you are responsible to set or reset catcodes. Currently `\begin{document}` doesn't do any catcode scheme management and to reset just those of expl3 seems wrong. And a general mechanism is problematical as it needs to work hand in hand with all such language files etc, that do sometimes alter catcodes and expect them to survive. Maybe one day but not a pressing topic.

@hvoss49  Herbert, as to your question, we think it works as designed. Only declarations are tracked but not usage.
