### ISSUE TITLE
Bug in colaction in multicol

### ISSUE THREAD

**Issue by colasbd** [latex3/latex2e#45]
## Brief outline of the bug

In the attached document, it seems to me that `multicol` call the wrong argument. 
**We are at column `2` but `multicol` calls the action for the first column.** 
The file is `exercices_espaces_euclidiens.tex`

The example is definitively not a MWE and I am sorry about it.
I hope you will still be able to understand what is going on, and maybe help me.

The file where I use `colaction` is `macrosColas_Exercices_18_19.sty`. Here is the code:

The call where `colaction` is not having the expected result is
`\docolaction{\conditionalspace{1}}{}{\conditionalspace{2}}`

```tex
% 4bis. Conditional rule
%https://tex.stackexchange.com/a/405256/8323

% we don't put rule after first sections
% (cf. \varIsNewSectionExercise)
\numdef{\columnnumber}{0}
\newcommand{\conditionalrule}[1]{
    \ifnumequal{#1}{\columnnumber}
    	% then
		{%
			\ifnum\varIsNewSectionExercise=1%
				% then
			\else
				% else
				\vspace*{2mm plus 2mm minus 1mm}
				\hrule
				\vspace*{4mm plus 2mm minus 1mm}
			\fi}
		% else
		{%
			% we nullify the above space
			\vspace{-\abovedisplayskip}
			\vspace{-\parskip}
		}
    \global\numdef{\columnnumber}{#1}
    }


% 4 bis bis. Conditional space
\numdef{\columnnumberbis}{0}
\newcommand{\conditionalspace}[1]{
    \ifnumequal{#1}{\columnnumberbis}
    	% then
		{\bfseries}
		% else
		{%
			% we nullify the above space for the second column
			\ifnumequal{#1}{2}
				% then
				{%
					\vspace{-\abovedisplayskip}
					\vspace{-\parskip}\itshape
				}
				% else
				{}
		}
    \global\numdef{\columnnumberbis}{#1}
    }




% 4ter. Print the info about IDs, etc.
\def\printInfoAboutIDs{%
    \ifthenelse{\equal{\shouldPrintIDs}{Y}}
    	{%
    		{\color{gray}
    		\hfill {\small\ttfamily\completeIdExo} \par \hfill{\small\bfseries \varNumberIDExo}%
    		\ifthenelse{\equal{\withCorrige}{Y}}
        		{\par{\color{black}\LARGE \hfill$\bullet$}}
        		{}
    		\par
    	}%
        {}
    \gdef\withCorrige{N}%
    }	
}



% 5. Main environment
\newcounter{cptrforexos}

\newenvironment{exo}[1][]{%
\addtocounter{cptrforexos}{1}
%
\initCountersExoSymbols
\computeCountersExoSymbols{#1}
%
%\vspace{-\abovedisplayskip}
%\vspace{-\parskip}
\docolaction{\conditionalspace{1}}{}{\conditionalspace{2}}
\begin{minipageparskip}
%
\nilParskip
%
\docolaction{\conditionalrule{1}}{}{\conditionalrule{2}}
\gdef\varIsNewSectionExercise{0}
%% Id of the exos and infos
\computeCompleteIdExo
\printInfoAboutIDs
%
\par
\textbf{Exercice \documentIndex.\thecptrforexos\,\printExoSymbols \varForConcours}
\vspace{0.5mm plus 0.5mm minus 0.25mm}
%
\varForTitreExo
%
\par
%
\normalParskip
\vspace*{-\parskip}
}
{%
\end{minipageparskip}
%
\gdef\varForConcours{}
\gdef\varForTitreExo{}
%
}
```

[exercices.zip](https://github.com/latex3/latex2e/files/1976899/exercices.zip)

**Comment by FrankMittelbach** [comment]
As you say this is by no means a MWE (nor has it been reduced to cover only packages supported by us), so please cut it down to a reasonable example if you want us to have a look. We don't have the manpower to do that for you - thanks.

**Comment by colasbd** [comment]
Thanks for your reply @FrankMittelbach.
I thought you could have been interested by this example (even if not a MWE). I'll try to make it shorter.

**Comment by FrankMittelbach** [comment]
well, interested perhaps but if I spend several ours on each and every user problem, I have an time issue as you can imagine. So please obey our request for a MWE that doesn't use third party packages next time.

anyway, I think I found your problem (even though I must admit that I haven't fully checked  the purpose of the construction using \columnumber etc). The problem seems to be that between the first \docolaction and the second (or rather before the "minipageparskip" environment) there is a potential column break and if that is taken then your code logic seems to fail --- as I said I haven't tried to understand that part of your code.

So by adding

```
\docolaction{\conditionalspace{1}}{}{\conditionalspace{2}}%
\nobreak   % <- added
\begin{minipageparskip}
```
it seems that your problems vanish. If not please take the time to prepare a proper MWE.

**Comment by colasbd** [comment]
Thanks very much, I will check and tell you.

**Comment by colasbd** [comment]
@FrankMittelbach I think you rock 👍
