### ISSUE TITLE
xparse in l3kernel?

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#450]
I don't know if it's desirable, but maybe xparse should be in l3kernel instead of l3packages? It is apparently no longer possible to build the .fmt without xparse. Or maybe some other change is preferable. Or maybe it should all be left as-is (it doesn't especially matter to me, but was noticed by downstream). Cutting from pdflatex.log:
....
(/usr/local/texlive/dev/texmf-dist/tex/latex/l3packages/xparse/xparse.ltx
(/usr/local/texlive/dev/texmf-dist/tex/latex/l3packages/xparse/xparse-generic.t
ex
...

**Comment by josephwright** [comment]
Take a look a the `cmd` branch in the `latex2e` repo: the plan is to move the code entirely.

**Comment by FrankMittelbach** [comment]
But now the move/shift is simple (well comparably) whereas it would have been difficult to do --- with a lot of dependencies and requirements on parallel installs on the distributions in the 2020-10 release. So yes it is coming (with the next release).
