### ISSUE TITLE
The firstaid fix for pgfmorepages is not correct.

### ISSUE THREAD

**Issue by loopspace** [latex3/latex2e#455]
In `latex2e-first-aid-for-external-files.ltx` there is a fix for how the `pgfmorepages` package hooks into the shipout routine.  This is a direct copy of the fix for the `pgfpages` package, but the two packages hook into the shipout routine slightly differently: `pgfpages` applies its hook at the end of the package but `pgfmorepages` applies its hook via an `AtBeginDocument` call.

To that end, the fix for `pgfmorepages` should patch the `pgfmorepages` hook rather than try to override its effect.  The following is what I think it ought to be:

```
\AddToHook{file/after/pgfmorepages.sty}[firstaid]{%
  \cs_set_nopar:Npn \pgfhookintoshipout {
    \cs_set_eq:NN \pgfpages@originalshipout \tex_shipout:D
    \cs_set_eq:NN \tex_shipout:D \pgfpages@interceptshipout
  }
}
```

Some MWEs.

Currently not working:

```
\documentclass{article}

\usepackage{pgfmorepages}
\usepackage{lipsum}

\begin{document}

\lipsum[1-4]{}

\end{document}
```

Currently working:

```
\documentclass{article}

\ExplSyntaxOn
\makeatletter
\RemoveFromHook{file/after/pgfmorepages.sty}[firstaid]
\AddToHook{file/after/pgfmorepages.sty}[firstaid]{%
  \cs_set_nopar:Npn \pgfhookintoshipout {
    \cs_set_eq:NN \pgfpages@originalshipout \tex_shipout:D
    \cs_set_eq:NN \tex_shipout:D \pgfpages@interceptshipout
  }
}
\makeatother
\ExplSyntaxOff

\usepackage{pgfmorepages}
\usepackage{lipsum}

\begin{document}

\lipsum[1-4]{}

\end{document}
```

**Comment by FrankMittelbach** [comment]
now on ctan

**Comment by loopspace** [comment]
Thank you!
