### ISSUE TITLE
Redundant \let\normalshape\@undefined in ltfssaxes.dtx

### ISSUE THREAD

**Issue by user227621** [latex3/latex2e#458]
`\let\normalshape\@undefined` appears twice in `ltfssaxes.dtx` (lines 1282 and 1289 in the master branch version of this file). It should be enough to undefine the command once.

**Comment by FrankMittelbach** [comment]
Actually it is more than unnecessary, it is a (minor) bug because it needs moving to a point after the definition of \normalshape. Otherwise the rollback will not undefine it.

**Comment by user227621** [comment]
> Actually it is more than unnecessary, it is a (minor) bug because it needs moving to a point after the definition of \normalshape. Otherwise the rollback will not undefine it.

@FrankMittelbach Apparently the rollback code in `ltfssaxes.dtx` has been rearranged after the 2020-10-01 PL 2 release. In the PL 2 release the code is arranged correctly (The only problem there is the redundant `\let\normalshape\@undefined`).
