### ISSUE TITLE
\ProcessOptions fails if class is loaded from a local folder

### ISSUE THREAD

**Issue by kia999** [latex3/latex2e#459]
## Brief outline of the bug

I see closed issue https://github.com/latex3/latex2e/issues/422 but I still have similar problem with custom class loaded from a subfolder. MWE below demonstrates that `\ProcessOptions` in fails if cls file is located in a subfolder. In this MWE, the role of custom class is played by the standard book.cls renamed to myBook.cls and copied to Common subfolder.

By the way, adding \RequirePackage{latexbug} caused error message althoug MWE is correct.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
%%
%% myBook.cls is an identical copy of book.cls
%%
% This succeed to process options
%\documentclass[12pt,openany,twoside]{myBook}
% This fails to process options
\documentclass[12pt,openany,twoside]{Common/myBook}

\begin{document}
We have:
\makeatletter
	\verb|bk1\@ptsize|=bk1\@ptsize\
\makeatother
but it should be \verb|bk1\@ptsize|=bk12.
\end{document}
[test-cls-location.log](https://github.com/latex3/latex2e/files/5708500/test-cls-location.log)
[test-cls-location.pdf](https://github.com/latex3/latex2e/files/5708503/test-cls-location.pdf)
```

**Comment by PhelypeOleinik** [comment]
The issue has been fixed in the repository (see PR #438) but we didn't make a release to CTAN yet.  A release should happen soon.

I will keep this issue open until the release
