### ISSUE TITLE
Inconsistent local/global assignment of hooks

### ISSUE THREAD

**Issue by cgnieder** [latex3/latex2e#463]
## Brief outline of the bug

Debugging expl3 code shows errors in the hook code (using LaTeX 2020-10-01 PL3).
This is not a problem in itself (I guess) but is at least annoying when debugging own code.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\ExplSyntaxOn
\sys_load_debug:
\debug_on:n {all}
\ExplSyntaxOff
\begin{document}
\end{document}
```
This example shows several errors of the form
```
./test.tex:7: LaTeX3 Error: Inconsistent local/global assignment

For immediate help type H <return>.
 ...                                              
                                                  
l.7 \begin{document}
                    

This is a coding error.

Global assignment to a constant variable '\__hook begindocument'.
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/5760224/test.log)

**Comment by FrankMittelbach** [comment]
bugger :-(

**Comment by FrankMittelbach** [comment]
part of PL4
