### ISSUE TITLE
Changing \CurrentFile inside a file changes the file/after/<name> hook

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex2e#464]
## Brief outline of the bug

Initially reported by @moewew at https://tex.stackexchange.com/q/577191, if the string `\CurrentFile` is changed within a file, the `file/after/<name>` hook is changed.  This happens with `LaTeX2e <2020-10-01> patch level 3`, but it didn't happen with `patch level 2`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\begin{filecontents}{testA.tex}
\egroup\bgroup
\end{filecontents}

\documentclass{article}
\AddToHook{file/after}{\typeout{After "\CurrentFile"}}
\begin{document}
\bgroup
\input{testA}
\egroup
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/5761079/test.log)

**Comment by FrankMittelbach** [comment]
part of PL4
