### ISSUE TITLE
usrguide3 should make use of a PostScript font

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#470]
## Brief outline of the enhancement
The `usrguide3.pdf` should be created with a PostScript font (e.g. Latin Modern): currently, it doesn't look very clean when read on the screen.

**Comment by FrankMittelbach** [comment]
it is not just that file seems that a bunch of other generated documentaton files contain a mix of type1 and type 3 fonts. Not sure why we get type3 stuff now  --- it wasn't the case in the past (looks like cm-super type ones are now replaced by type3 fonts).

If I regenerate the documentation it comes out correctly, so looks like a  issue in @josephwright's setup local perhaps.

**Comment by josephwright** [comment]
@FrankMittelbach Did you generate using `l3build` or just by running with your system format? I suspect it might be due to the isolated system set-up we use.

**Comment by FrankMittelbach** [comment]
I ran l3build doc usrguide3.  The documentation is not sandboxed as far as I know because we didn't want to put all the fonts into the sandbox. So it should get what is on your system and in my case it loads
```
(see the transcript file for additional information){/usr/local/texlive/2020/te
xmf-dist/fonts/enc/dvips/cm-super/cm-super-t1.enc}{/usr/local/texlive/2020/texm
f-dist/fonts/enc/dvips/cm-super/cm-super-ts1.enc}</usr/local/texlive/2020/texmf
-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/local/texlive/2020/texmf-
dist/fonts/type1/public/amsfonts/cm/cmr10.pfb></usr/local/texlive/2020/texmf-di
st/fonts/type1/public/amsfonts/cm/cmsy10.pfb></usr/local/texlive/2020/texmf-dis
t/fonts/type1/public/amsfonts/cm/cmsy9.pfb></usr/local/texlive/2020/texmf-dist/
fonts/type1/public/cm-super/sfbx1000.pfb></usr/local/texlive/2020/texmf-dist/fo
nts/type1/public/cm-super/sfbx1200.pfb></usr/local/texlive/2020/texmf-dist/font
s...
```

**Comment by zauguin** [comment]
> it is not just that file seems that a bunch of other generated documentaton files contain a mix of type1 and type 3 fonts. Not sure why we get type3 stuff now --- it wasn't the case in the past (looks like cm-super type ones are now replaced by type3 fonts).

Maybe it's because we build the releases on Travis now? It looks like `support/texlive.sh` doesn't install `cm-super`.

**Comment by FrankMittelbach** [comment]
> Maybe it's because we build the releases on Travis now? It looks like `support/texlive.sh` doesn't install `cm-super`.

Ah I guess that explains it then. If the documentation is generated there then obviously we need to add cm-super there.

**Comment by josephwright** [comment]
Should I adjust?

**Comment by FrankMittelbach** [comment]
if we generate the documentation in this way, then yes I think we have to (but not worth a patch level)

**Comment by josephwright** [comment]
The file was build on the CI, so the checkin should fix everything!
