### ISSUE TITLE
Regression: \input is now wrapped

### ISSUE THREAD

**Issue by hmenke** [latex3/latex2e#473]
## Brief outline of the bug

Forwarding the bug that was reported by @ahaselbacher against PGF: https://github.com/pgf-tikz/pgf/issues/982

The `\input` command has changed in such a way that macros that look ahead to scan for arguments at the end of a file trigger either an error or, as in the case of the present MWE, unexpected output.

I don't have an old version of the kernel at hand to test this but it was reported working with older releases. Also the primitive `\@@input` does not show the incorrect behaviour.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\begin{filecontents*}{collectarg.tex}
\collectarg
\end{filecontents*}
\documentclass{article}
\makeatletter
% just need something that skips spaces
\def\collectarg{\@ifnextchar\relax{\@collectarg}{\@collectarg}}
\def\@collectarg#1{#1 world!}
\begin{document}
\input{collectarg.tex}{hello}
\end{document}
```

![test](https://user-images.githubusercontent.com/1903556/104717960-70582580-572a-11eb-837b-b4e285d257ab.png)

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/5820089/test.log)

**Comment by josephwright** [comment]
The demo fails on older LaTeX if one for example loads `filehook`: I think this is borderline for supported behaviour.

**Comment by FrankMittelbach** [comment]
I agree with Joseph here. This may have worked in the past on and off, but it is not supported and never was.  `filehook` has been loaded in the past by several other package so it worked on and off and etex's `\everyeof` would have killed it too and it would have never worked with `\include`, ... Now that basically the equiv of filehook is always loaded you have always the state that it doesn't work, so yes, maybe a regression from an unknown state to a never supported state but nothing that can be made possible and at the same time support adding code before and after files.

**Comment by josephwright** [comment]
As discussed, this is basically unsupported behaviour, as one cannot provide file hooks without appending to `\input`, and that already happened with the `filehook` pacakge. It was never documented that one could have a 'dangling' command in `\input`.
