### ISSUE TITLE
Package everysel broken with current dev-release

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#474]
## Brief outline of the bug
With `LaTeX2e <2021-05-01> pre-release-1 (develop 2021-1-16 branch)` package `everysel` got broken because of the new font selection mode. Could you maybe consider to provide a first-aid-fix for this issue?

## Minimal example showing the bug

```latex
%\RequirePackage{latexbug}
\listfiles
\documentclass{minimal}
\usepackage{everysel}
\begin{document}
normal text but: \textbf{not bold}!
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/5823720/test.log)

### Edit
Initially I thought, package `ragged2e` got broken but `everysel` is used internally. Nevertheless, both packages are maintained by Martin Schröder who seems to be inactive.

**Comment by FrankMittelbach** [comment]
yes that will need some firstaid or better a new maintainer

**Comment by FrankMittelbach** [comment]
actually it is already available only not yet distributed to CTAN.

**Comment by TeXhackse** [comment]
@u-fischer  contacted me about that. Martin had asked me to take care of his packages.

Fixed it similar to the issue we had with everyshi and prelim2e. Going to update ragged2e to no longer depend on it as soon as I finde time to d so. But the workaround should work up to then.

CTAN Upload was done today. I hope all of you are fine with this.

**Comment by FrankMittelbach** [comment]
@mrpiggi  so I suggest you close it Falk the moment it has hit CTAN and you have verified it works

**Comment by FrankMittelbach** [comment]
or rather leave it open as a reminder for me to take the now unnecessary firstaid out (before it get distributed) and I close it.

**Comment by mrpiggi** [comment]
At the moment
```
\disable@package@load{everysel}{%
  \newcommand*\EverySelectfont[1]{\AddToHook{selectfont}{##1}}%
}
\RequirePackage{ragged2e}
```
works fine with the current dev-release. But as the hook `selectfont` does not exist in the current kernel, it might make sense to update package `ragged2e` only after the next release and provide the firstaid-fix until it is done?

**Comment by FrankMittelbach** [comment]
@mrpiggi I have not check how @TeXhackse has updated everysel but I would have expected she does it with a suitable guard to that the  change only kicks in when the format is 2021/05/01 (otherwise things would break is somebody does a rollback, say). I therefore don't expect the need for firstaid any more.

**Comment by mrpiggi** [comment]
I just looked into the update and everything looks great. The actual implementation is:
```tex
\providecommand\IfFormatAtLeastTF{\@ifl@t@r\fmtversion}
\IfFormatAtLeastTF{2021/01/05}{}{\input{everysel-2011-10-28.sty}}
\IfFormatAtLeastTF{2021/01/05}{}{\endinput}
\newcommand*{\EverySelectfont}[1]{\AddToHook{selectfont}{#1}}
\newcommand*{\AtNextSelectfont}[1]{\AddToHookNext{selectfont}{#1}}
```
So everything should work as expected. Many thanks to @TeXhackse 

I'll leave this issue open as requested.

**Comment by mrpiggi** [comment]
I just wanted to mention, that there are some classes and packages, that rely on `\@EverySelectfont@Init` which is not defined anymore. This concerns (searching TeX Live tree) at least:
* ctex @CTeX-org
* pxeverysel @aminophen 
* LuaTEX-ja @h-kitagawa
* KOMA-Script @komascript

**Comment by FrankMittelbach** [comment]
@mrpiggi a quick look seems to indicate this is largely "used" to check for the hook being there or not being there ... not it is always available. So yes, there are probably adjustments needed (one of the cases, whenever you try to comine and simplify you hit against somebody trying to use or combine things already and their tests/use then no longer works). So yes, there are probably some changes needed for those classes/packages even though everysel is now suitable for old and new LaTeX.

**Comment by TeXhackse** [comment]
@mrpiggi Well, the intention of the update was to preserve compatibility. I'll have a look and think about changing everysel so it can be used in the way they did.

**Comment by FrankMittelbach** [comment]
@TeXhackse 

> I would also add a warning, that this package became obsolete. Maybe this gets users to switch to the lthooks a bit faster. 

 A warning generated by the package  about its state might be  be a good idea I think.

> The only one creaking ist pxeverysel, but this seems to be a patch which only was necessary due to the original implementation.

creaking?  :-) I'm sure Hironobu is happy to adjust, he is very responsive

> Or does anyone of you have any better suggestions?

no, but on the whole it would help if over time people switch to kernel methods as that makes everbody's life easier in the long run. So if you could help with that  by talking to one or the other package owner this would be great (even if their package continue working through your efforts).

**Comment by mrpiggi** [comment]
@TeXhackse The suggested add-on looks good to me. FYI: Besides `pxeverysel` package `lltjfont` would also create an error as it executes `\@EverySelectfont@Init` without checking for its existence.

Regarding the addition of a warning, maybe it would make sense to raise a warning only if `\@EverySelectfont@Init` was changed:
```tex
\newcommand*\@EverySelectfont@Legacy{\let\@EverySelectfont@Init\undefined}
\newcommand*{\@EverySelectfont@Init}{\@EverySelectfont@Legacy}
\AddToHook{begindocument}{%
  \expandafter\ifx\@EverySelectfont@Init\@EverySelectfont@Legacy\else%
    \PackageWarningNoLine{everysel}{...}%
  \fi%
}
```
so that package authors using `\@EverySelectfont@Init` as a hook would have to adapt in the first place. After a certain time, this could then be replaced by a general warning (and maybe dropping `\@EverySelectfont@Init` at all). This would make the transition phase a little smoother.

**Comment by aminophen** [comment]
Hi; I'm already aware of this change of everysel (see https://github.com/latex3/latex2e/issues/444#issuecomment-737200841); I'm the one who reported that everysel needs updated to work with new kernel. To match the change, I'm planning to update pLaTeX first (https://github.com/texjporg/platex/issues/96) then pxeverysel. The code in LuaTeX-ja is based on pLaTeX, and the developer (Kitagawa-san) is also watching pLaTeX so it should be fine soon.

**Comment by aminophen** [comment]
I mean, raising a warning to notice is not necessary as we are already aware ;-)

**Comment by h-kitagawa** [comment]
> FYI: Besides `pxeverysel` package `lltjfont` would also create an error as it executes `\@EverySelectfont@Init` recklessly without checking for its existence.

Thanks for the information. I updated LuaTeX-ja's code for using 'selectfont' hook instead of the everysel package ([commit](https://osdn.net/projects/luatex-ja/scm/git/luatexja/commits/29b7fb601adedbd524fd68727919329981d7910a)).

**Comment by TeXhackse** [comment]
@FrankMittelbach 

> creaking?  :-) I'm sure Hironobu is happy to adjust, he is very responsive

 Crappy auto correction. :/




I will add the warning and prepare the update tomorrow. Thanks for your support.

**Comment by FrankMittelbach** [comment]
> Crappy auto correction. :/

yeah, these days when I don't add the typos myself they are helpfully 
added by Apple MS and Co :-)

**Comment by TeXhackse** [comment]
@mrpiggi thanks for the suggestion, I uploaded a new version yesterday including that.

When I am back online (probably next week, hoping for good weather) I will be able to upload the new ragged2e and currently I am planning to switch to a general warning in about 4 weeks.

**Comment by mrpiggi** [comment]
@TeXhackse In my opinion, switching to a general warning does not make sense until 4 weeks after the next release (2021/01/05), as the hook `selectfont` will not be officially available until then.

**Comment by FrankMittelbach** [comment]
@mrpiggi I'm sure that warning will be in the part that kicks in when the new format is detected not otherwise when running with an older format

**Comment by TeXhackse** [comment]
jup, the fallback variant will not be affected of course.

**Comment by mrpiggi** [comment]
Well, my initial intention was to use `\@EverySelectfont@Legacy` to distinguish whether `\@EverySelectfont@Init` is used only to check if it exists (harmless) or abused as a hook.
```latex
\AddToHook{begindocument}{%
  \expandafter\ifx\@EverySelectfont@Init\@EverySelectfont@Legacy%
    \PackageInfo{everysel}{%
      This package is not required anymore as the\MessageBreak%
      LaTeX kernel provides this functionality with\MessageBreak%
      `\string\AddToHook[Next]{selectfont}{...}'\MessageBreak%
      See lthooks-doc for further information%
    }%  
  \else%
    \PackageWarningNoLine{everysel}{%
      Hooking into `\string\@EverySelectfont@Init' is prohibit,\MessageBreak%
      as this macro will be removed in a future release\MessageBreak%
      and errors most certainly will occur. You should\MessageBreak%
      urgently switch to hook `selectfont' provided by the\MessageBreak%
      LaTeX kernel (see lthooks-doc)%
    }%
  \fi%
  \@EverySelectfont@Init%
}
```
Since package `everysel` is more likely loaded by other packages rather than directly by end users, I didn't want to bother them unnecessarily with warnings. So maybe using `\PackageInfo` in the first place is sufficient and optionally switch to a warning later. 

@FrankMittelbach Is there actually a way to get a listing of the dependencies of all packages so that it can be quickly seen which package was requested and/or loaded by which?

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Is there actually a way to get a listing of the dependencies of all packages so that it can be quickly seen which package was requested and/or loaded by which?

I'm not aware of any. It might be already quite helpful if someone would implement a (lua?) script that scan's the TL tree and finds all cases of `\RequirePackage`, `\LoadClass`, `\input`, `\@input` and the like and build some automatic depdency tree but there are so many other depdencies that one can't easily detect (like packages making chars active and breaking code of other packages) or packages  having different code branches depdening on what is loaded or ...  so all in all it would be some daunting exercise I guess.

Anyway, as far as this issue here is concerned I think it is resolved and so I'll close it.
