### ISSUE TITLE
Copy-paste the result of \TeX and \LaTeX should be "TeX" and "LaTeX"

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#475]
## Brief outline of the enhancement
Copy-paste the result of \TeX and \LaTeX should be "TeX" and "LaTeX", not "TEX" and "L A TEX"

## Minimal example showing the current behaviour

Compile with `pdflatex` or `lualatex` the following file
```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\pagestyle{empty}
\begin{document}
\TeX{}

\LaTeX{}
\end{document}
```
open the resulting PDF file, copy the whole content. The resulting paste is:

>TEX
L A TEX

while one could expect:
>TeX
LaTeX

**Comment by u-fischer** [comment]
That requires an /ActualText Entry in the pdf, something that is currently (until more pdf related support is in the LaTeX format) only possible with an external package like accsupp.

**Comment by FrankMittelbach** [comment]
As Ulrike said we are painfully aware of this (especially as we tend to write a lot of documents containing the logos :-) but as long as there is no direct support from within core LaTeX there is not much we can do about. But this is part of the bigger project of making LaTeX support tagging and make it produce accessible PDFs https://www.latex-project.org/publications/indexbytopic/pdf/. 

So I'm closing this here for now.
