### ISSUE TITLE
Error with latex-dev 2021/05/01 and latexrelease 2020/10/01

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#479]
## Brief outline of the bug
Using the current `latex-dev` with rollback to `2020/10/01` throws:
`LaTeX3 Error: Control sequence \g__hook_debug_bool already defined.`

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\RequirePackage[2020/10/01]{latexrelease}
\documentclass{minimal}
\begin{document}
Test
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/5849203/test.log)

**Comment by PhelypeOleinik** [comment]
Rolling back to 2020-10-01, the release when `lthooks` was introduced, tries to load `lthooks` all over again, which errors with all `\<something>_new:N` commands from `expl3`...

**Comment by PhelypeOleinik** [comment]
@mrpiggi Lots of fun, this one. Hopefully it's a bit future-proof now :)
