### ISSUE TITLE
non termination with  \protect commands in \input

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#481]
## Brief outline of the bug

`\input{sqrt{2}}`  is non terminating and `\input{\frac{1}{2}}` works but inputs `protect{begingroup1endgroupover2}.tex` which might not be the expected file.

We could add `\let\protect\string` to `\set@curr@file` which makes both these safer
it would in theory prevent some safe expansions that currently happen but it is hard to think of many real cases where expanding a protected command leads to a natural file name so I suspect this would be  safe, the file below inputs (or gives missing file errors for)
`sqrt {2}.tex`, `frac {1}{2}.tex`, `zzzzzz.tex`

## Minimal example showing the bug

If you remove the suggested fix the file below loops and does not terminate.

```latex
\documentclass{article}

\begin{document}
\makeatletter
\def\set@curr@file#1{%
  \begingroup
    %%%%%%%%%%%%%%%%%%%
    \let\protect\string
    %%%%%%%%%%%%%%%%%%%
    \escapechar\m@ne
    \xdef\@curr@file{%
      \expandafter\expandafter\expandafter\unquote@name
      \expandafter\expandafter\expandafter{%
      \expandafter\string
        \csname\@firstofone#1\@empty\endcsname}}%
  \endgroup
}

\input{\sqrt{2}}

\input{\frac{1}{2}}

\protected\def\blub{zzzzzz}
\input{\blub}
\end{document}
```

## Log file (required) and possibly PDF file  
[str2.log](https://github.com/latex3/latex2e/files/5861268/str2.log)

**Comment by josephwright** [comment]
One word: `\protected`

**Comment by car222222** [comment]
See also my email re the same.

**Comment by davidcarlisle** [comment]
On Sun, 24 Jan 2021 at 08:22, Joseph Wright <notifications@github.com>
wrote:

> One word: \protected
>

apart from the fact that there is rather a lot of legacy already using
\protect, not sure that would do the right thing here in all cases,
\protected commands expand in a csname (as shown by the \protected\def
\blub definition in the test file here)

**Comment by car222222** [comment]
The subtext being perhaps: is \protected the problem?  
Or is it a Good Thing™?

**Comment by davidcarlisle** [comment]
It should be noted that the `\set@curr@file` that needs `\let\protect`\string` is the new one in ltfilehooks, the old definition used on comment 1 is from ltfiles and now only used during format building.
