### ISSUE TITLE
Rollback prior to 2019/10/01 retains robust definition of \begin and \end

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#494]
## Brief outline of the bug
With making commands `\begin` and `\end` robust, both `\csname begin \endcsname` and `\csname end \endcsname` are defined as well. Rolling back prior to 2019/10/01 does not undefine the latter definitions, so testing for existence is positive although these are not executed. I initially reported this at josephwright/etoolbox/issues/32 but as this not only concerns `etoolbox` but also packages `breqn` and `extract` I wanted to suggest that `latexrelease` should do something like
```tex
\expandafter\let\csname begin \endcsname\@undefined
\expandafter\let\csname end \endcsname\@undefined
```
prior to 2019/10/01

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\listfiles
\RequirePackage[2019/10/00]{latexrelease}
\documentclass{minimal}
\show\begin
\expandafter\show\csname begin \endcsname
\show\end
\expandafter\show\csname end \endcsname
\begin{document}
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/5944622/test.log)

**Comment by FrankMittelbach** [comment]
@mrpiggi can you give a good reason why these totally internal names need to be undone? I can see that for a *perfect* rollback that is true, but there are literally hundreds of those and adding them all over the place would be rather a major undertaking with (as I can see) much or any gain.

**Comment by davidcarlisle** [comment]
@FrankMittelbach   etoolbox currently does `\ifcsname begin \endcsname`  to decide whether to hook `\begin` directly or the internal definition if it is there, so takes the wrong branch on rollback

**Comment by mrpiggi** [comment]
As mentioned, at least packages `etoolbox` and `breqn` are testing for the existence of `\csname begin \endcsname` and `\csname end \endcsname` instead of using `\IfFormatAtLeastTF`. As @u-fischer and @josephwright are maintaining these packages, it's up to you who is to blame for ;)

As far as I could see by searching the texmf-tree with this regex
```
(\\csname (begin|end)( |\\space)\\endcsname)|(\{(begin|end)( |\\space)\})|(\\DeclareRobustCommand\*?\{?\\(begin|end)\}?)[\[\{]
```
only package `subfiles` is affected additionally. Therefore I already created a PR https://github.com/gsalzer/subfiles/pull/25

**Comment by u-fischer** [comment]
I don't maintain breqn, I only made one fix to keep it working after a latex change and I won't spent time to adjust it to the rollback. 

But you evaded the question: what is your use case here? Do you simply play around to find problems in rollback? Or is this used somewhere in earnest?

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach etoolbox currently does `\ifcsname begin \endcsname` to decide whether to hook `\begin` directly or the internal definition if it is there, so takes the wrong branch on rollback

not that good to rely on implementation details :-)
I don't mind undoing the two commands but not going across all files and figuring out what else is there internally, just binds too much resources. And as well all know (or don't) a single such change with all its additional work needed takes easily several hours each.

**Comment by mrpiggi** [comment]
@u-fischer 
The use case was concerned with `etoolbox` as the rollback I mentioned did not work. That's why I initially posted the issue there. Afterwards I just searched the texmf-tree for potential concerned packages and reported here in order to let the decision to the LaTeX team how to deal with it. If it would be fixed with `latexrelease`, the packages could left in the current state but if the LaTeX team would refuse this change, the packages would need adoption. So for `breqn` here is your use case:

```latex
\RequirePackage[2019/10/00]{latexrelease}
\documentclass{minimal}
\usepackage{breqn}
\begin{document}
\begin{dmath}
f(x)=\frac{1}{x} \condition{for $x\neq 0$}
\end{dmath}
\end{document}
```

**Comment by PhelypeOleinik** [comment]
I'd suggest doing the same for `\InputIfFileExists` because `memoir`, `filehook`, and `scrlfile` looks for that

**Comment by FrankMittelbach** [comment]
> I'd suggest doing the same for `\InputIfFileExists` because `memoir`, `filehook`, and `scrlfile` looks for that

doing the same what? they are looking for a robust internal of that command? Great :-)


By the wayI just did it for begin/end and that breaks the test suite (but only because of the the newly introduced hyperref bug I guess, so hopefully that resolves by magic in a day or two).

**Comment by mrpiggi** [comment]
> doing the same what? they are looking for a robust internal of that command? Great :-)

AFAICS this was done in order to apply patches to `\InputIfFileExists` before the introduction of the hook management. And as hooks weren't available with `latexrelease` prior to 2020/10/01, all tests and patches for hooking into `\InputIfFileExists` are done like they've been done with older kernels. And well, the named packages adapted to the changes coming with 2019/10/01 and implemented their patches to the robust variant of `\InputIfFileExists`, so assuming the kernel state of 2019/01/01 and testing the existence with `\ifcsname InputIfFileExists \endcsname` seems legit to me.

**Comment by FrankMittelbach** [comment]
sorry ... was a joke ... (aka smiley). Yes I understand how it comes about and we don't have a good interface for checking (except via format date which would have less potential problems). There are now fixes in for both, but they don't compile right now (because of the error in hyperref that I'm waiting to get resolved in a day or two).

**Comment by mrpiggi** [comment]
I took the smiley as sarcasm. Sorry for that 0:-)

**Comment by FrankMittelbach** [comment]
take it as "raised his hands in despair" :-) I should have thought about that this is a likely test people do.
