### ISSUE TITLE
Providing a release candidate

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#495]
First of all, I would like to thank the whole LaTeX team for providing `latex-dev` as a way for third-party developers to test their own packages against updates to the kernel. This is great and will (hopefully) ensure the stability of third-party packages in the future.

Nevertheless, I would like to suggest to create an RC branch (2021-05-01-RC) for future releases at a certain point in time (maybe 4 weeks before the actual release?) and to make it available via `latex-dev` in order to really be able to react to all adjustments to the kernel. This branch should then contain no further changes but only necessary bug fixes—which can easily be back-merged to `develop`—and serve as the basis for the upcoming release.

For 2019-10-01 and 2020-02-02, everything from the then-current `develop` branch was used for the release, leading to the situation where potentially critical updates were published that could not be tested beforehand. This procedure undermines the actually excellent intention of `latex-dev`.

Kind regards
Falk

**Comment by FrankMittelbach** [comment]
I'm not sure I understand your point. That is what we call LaTeX-dev, the release candiate for the upcoming release.
There was a final version each time that was published as latex-dev about 4 weeks before the releases you mentioned and that version (plus fixes found during testing by others in the last 4 weeks )went into the final release. This last -dev release  was announced as the final RC each time, e.g.,

https://www.latex-project.org/news/2020/09/01/latex-dev-2020-10-1c/

So what potentially critical updates are you referring to? Granted those fixes where not available in latex-dev going through ctan but that is a problem you will always have.

**Comment by mrpiggi** [comment]
I recently remembered the chaos with 2019-10-01 when the file name handling was improved. But at that time I wasn't aware of latex-dev either. Anyway, I had a look at the last releases and actually didn't find anything critical:

    git difftool --dir-diff release-2020-10-01 dev-2020-10-01-8 -- *.{cfg,cnf,def,dtx,ltx,txt}
    git difftool --dir-diff release-2020-02-02 dev-2020-02-01-2 -- *.{cfg,cnf,def,dtx,ltx,txt}
    git difftool --dir-diff release-2019-10-01 dev-2019-10-01-2 -- *.{cfg,cnf,def,dtx,ltx,txt}

Only `lthooks` could maybe have been problematic, but the changes were available in the pre-release `dev-2020-10-01-9` at least two weeks before.

    git difftool release-2020-10-01 dev-2020-10-01-8 -- base/lthooks.dtx
    git difftool release-2020-10-01 dev-2020-10-01-9 -- base/lthooks.dtx

My concern is that, from an official release candidate onwards, how do you ensure that no unnecessary or unwanted changes are made to the kernel that are not intended to be included in the next major release? As soon as someone adds something to `develop` at this point, it will end up in the major release, even if it is not dedicated to it.

That's why it might make sense to use a `release` branch and only include necessary bug fixes there. Then `develop` could be used for further development without any problems and without affecting the next major release. This procedure is often referred to as `git-flow`, here an ASCII diagram for illustration:

                        *                                                                  *   
                        *                                                                  *   
    master            --*------------------------------------------------------------------+-- 
                        *                                                                 /*   
                        *                                                                / *   
                        *                                                               /  *   
    release             *         +--+----+----+-------+-----+-------+------------+----+   *   
                        *        /    \         \                   /            /      \  *   
                        *       /      \         \                 /            /       |  *   
    release-fix1        *      /        +---------\-----+---+-----+            /        |  *   
                        *     /                    \               \          /         |  *   
                        *    /                      \               \        /          |  *   
    release-fix2        *   /                        +-----+----+----\------+           |  *   
                        *  /                                          \      \          |  *   
                        * /                                            \      \          \ *   
                        */                                              \      \          \*   
    develop           --+---------+--------------+-------------------+---+------+----+-----+-- 
                        *          \                                /               /      *   
                        *           \                              /               /       *   
    new-feature         *            +--------+-----+-----+-------/               /        *   
                        *                                  \                     /         *   
                        *                                   \                   /          *   
    ontop-feature       *                                    +-----------------+           *   
                        *                                                                  *   
                        *                                                                  *   
                        *                                                                  *   
                   rc-xxxx-xx-xx                                                 release-xxxx-xx-xx

This is only meant as a suggestion, Maybe you already know `git-flow` (at least you work diligently with branches) and have decided against it or consciously chosen your current approach. I'm pretty sure the release process is complicated enough as it is. I just wanted to mention it. Maybe I should add a better graphic after all ;)

https://nvie.com/posts/a-successful-git-branching-model/

![](https://nvie.com/img/git-model@2x.png)

**Comment by josephwright** [comment]
> My concern is that, from an official release candidate onwards, how do you ensure that no unnecessary or unwanted changes are made to the kernel that are not intended to be included in the next major release? As soon as someone adds something to `develop` at this point, it will end up in the major release, even if it is not dedicated to it.

Because we don't add them to `develop` :) There are only a few people, around 5 or 6, who actually commit to the repo at all. So we always talk though any major additions before they go in.

**Comment by FrankMittelbach** [comment]
Falk

 > I recently remembered the chaos with 2019-10-01 when the file name 
handling was improved.

issues happen, despite testing or in that case not testing enough 
externally.

 > Only |lthooks| could maybe have been problematic, but the changes 
were available in the pre-release |dev-2020-10-01-9| at least two weeks 
before.

it was available at the time of the TUG conference (only then the code 
was still in a different file and not linked in as lthooks.dtx) so it 
was available for testing for much longer (only internal shuffling 
happened nearer to the end but again not 2 but nearly 4 weeks because we 
delayed the release from its nominal day as well.

 > My concern is that, from an official release candidate onwards, how 
do you ensure that no unnecessary or unwanted changes are made to the 
kernel that are not intended to be included in the next major release?

develop is our release candidate branch, we do not develop inside that 
branch we develop in subbranches of it and they only get merged into 
develop if we want the code to appear in the next release.

 > As soon as someone adds something to |develop| at this point, it will 
end up in the major release, even if it is not dedicated to it.

there is no "someone" that is doing that (or allowed to do it). We don't 
allow random pulls or work from the outside so rest assured there is no 
stuff appearing there unintentional and ending up in the next release.
 >
 > That's why it might make sense to use a |release| branch and only 
include necessary bug fixes there.

which we have (currently called master, soon probably main) it only gets 
hotfixes.

and yes, thanks we know of git-flow and similar schemes and we have 
deliberately chosen a variant that best suits our needs. That is a bit 
lighter than running with explicit 3 levels plus feature branches but it 
is pointless to make it more complicated that it should be for what yu need.

**Comment by mrpiggi** [comment]
Thanks for your answer and explanation to me.
