### ISSUE TITLE
Missing } inserted.

### ISSUE THREAD

**Issue by paulgeisler72** [latex3/latex2e#498]
## Brief outline of the bug
Error occurs on any table found in a *.tex file on the last line of the table "\end{longtabu}".

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here

\begin{document}

 I could not find a way to reproduce the problem in a single file. So I have attached the project zip file. I did pdflatex refman.tex
The first bug is in line 44 of _s_a_s.tex

Error msg is "Missing } inserted"

[refman.log](https://github.com/latex3/latex2e/files/5968173/refman.log)
[latex.zip](https://github.com/latex3/latex2e/files/5968181/latex.zip)

## Log file (required) and possibly PDF file  

<!--- Use drag-and-drop  (remember: .log file is required!) -->

**Comment by davidcarlisle** [comment]
I am sorry but this is a bug reporting system for the core latex distribution, not a help service for documents using dozens of contributed packages. Especially as you say it is using `tabu` which is  not supported by anyone after having been abandoned by its original author. Please make a test file using `\RequirePackage{latexbug} ` that does not report use of contributed packages.

**Comment by paulgeisler72** [comment]
Ok thanks that's useful information. Now I need to figure out why doxygen is creating a tex file that is using the longtabu package.

**Comment by davidcarlisle** [comment]
doxygen uses a patched longtabu setup that more or less works for the restricted tables that it writes but as should have been made clear  in https://github.com/latex3/latex2e/blob/master/CONTRIBUTING.md files using third party packages can not be supported here, this repository is for the core latex format sources, not a general CTAN support.
