### ISSUE TITLE
Commit messages of the type "Fix #NNN" make commit history little legible

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#499]
## Brief outline of the <strike>bug</strike> slight discomfort

From time to time I ``git pull`` to update my local clone and follow developments. Then I will  ``git log`` on develop typically or ideally ``git log --oneline``, hoping to get a quick summary. And I end up my updating visit via checking up latest ltnews for traces of the most important evolutions.

But some commit messages such as 3c50d3dfc7583bb01b4d0cd327c1d5ded062d9c6 or 99f135ec5f6a814b4959857143f7889435f8a67c or 2147f1c2e7ad7349e2e61d074c62f7f577043c93 (nobody targeted especially ;-) ) are rather terse ``Fix for #NNN``. I end up having to fire up my web browser and enter into a clickodrom which is at times a bit slow with all the github.com added javascript etc... (also I don't like the idea GItHub tracking my every moves around here; for a brief short time still, but who knows how long it will last, at least when I navigate on my hard disk through my clones I am not tracked by Big Brother -- it is here, you know, and more than ever these days --- so I always hesitate whether to log in or not to github; I had to today to open this ticket).

It would be neat if a few words could sum up (even very tersely) the issue. Of course ``#NNN`` is useful too, as it is hyperlinked when one navigates on github.com.

Also in long term, if the latex2e repo is moved to some other web interface, will such cross-links actually still work in future?

**Comment by josephwright** [comment]
We don't have any formal standard for commit messages - normally one would read `changes.txt` to see the detail for LaTeX2e stuff. In terms of portability, there is an API to export bugs, so they could be moved to say GitLab and keep their number. But in a sense that's no different from the move from Gnats: the two sets of bugs are just listed separately. So it's quite possible that if we moved somewhere else, we'd just start numbering again from 1.

**Comment by jfbu** [comment]
When the fix is accompanied by  a changes entry, could this entry (which often is a few words only) be integrated into commit message?

**Comment by FrankMittelbach** [comment]
Often that is the case.  But while anything is possible, everything that is done also costs time and effort. In the cases you list it would have been easy and I quite readily confess I never thought it worth documenting in the checkin log a space correction or adding a \par command in a place where TeX currently calls the paragraph builder automatically  or an improvement of a rollback situation beyond a proper changes.txt and a bunch of \changes{...} entries.

In other cases the changes go very much across and end up in more than a single changest.txt entry and then copying all into the git log takes effort will likely be incomplete and would make at least my GUI view of the the repository quite cluttered. On the other hand looking at changes.txt for the data related to NNN would not be hard and brings things nicely into perspective.

Our main change reference is changes.txt and that is fairly accurately managed (and doesn't have the danger of being related to a tool that might change). Nor does it need for you to log into some big brother monitored system.
So perhaps your starting point could be to look at that file?

The repository on the other hand is mainly a tool for us. Making it available to others doesn't mean that its checkin history is the best place to look for seeing or appreciating changes.  That may be a pity for some and I will try to keep that in mind, but the day has only 24 hours of which I easily spend already an average of 10 on keeping LaTeX alive and kicking and so pardon  me for terseness  in some places.

**Comment by jfbu** [comment]
> So perhaps your starting point could be to look at that file?

yes, definitely. Taking into account
```
latex2e$ find . -name "changes.txt"
./base/changes.txt
./required/amsmath/changes.txt
./required/cyrillic/changes.txt
./required/firstaid/changes.txt
./required/graphics/changes.txt
./required/tools/changes.txt
```
And these are definitly useful.

Anyway, I can certainly do things such as ``git diff 99f135ec~..99f135ec`` whenever I see something such as ``99f135ec fixfor #494`` in the ``git log --oneline`` output. No big deal!

**Comment by FrankMittelbach** [comment]
yes, old school emacs:-) ...  one changes.txt per directory (and despite the disclaimer in some of them all fairly accurate).

**Comment by jfbu** [comment]
besides it is true that first line of commit message should not exceed something like 78 or 80 chars I forgot guideline, and next line should be blank. So yes, copying pasting from changes may require additional work. When ithappens in my own private repos that I make a mistake to paste some too  long stuff as commit message first line I am always annoyed afterwards when it ruins git log --oneline, so most of the time I amend. In case it is impossible to explain things concisely I simply insert some continuation points and continue after a blank line in commit message.

For github interface the Fix #NNN can be anywhere I think, and github will close the ticket, but I gather this is not to your taste (hence I guess the "fixfor").

(I hope you forgive me citing my own habits; it is great that latex2e has a public repo when one can follow in details without being actually involved in the day-to-day work. Many thanks for that)

**Comment by jfbu** [comment]
> 78 or 80 chars I forgot guideline

72 at my locale

**Comment by FrankMittelbach** [comment]
> (hence I guess the "fixfor").

nope ... my need for new fingers and also my need for a new macbook one day, the keyboard is no longer as good as it was.
#NNN does not close unless you are pushing to the main branch (which we aren't)

**Comment by josephwright** [comment]
> > (hence I guess the "fixfor").
> 
> nope ... my need for new fingers and also my need for a new macbook one day, the keyboard is no longer as good as it was.
> #NNN does not close unless you are pushing to the main branch (which we aren't)

New MacBook Pro keyboard is good, or get a Logitech Master Keys, or both ;) (Work paid for the latter for me)

**Comment by PhelypeOleinik** [comment]
> For github interface the Fix #NNN can be anywhere I think, and github will close the ticket, but I gather this is not to your taste (hence I guess the "fixfor").

As Frank said, `fixfor` was a typo, buy yes, anywhere in the commit title or description works, but `fix for` (rather, `for`) is not a valid keyword for auto-closing: https://stackoverflow.com/a/60027286/6015190

**Comment by FrankMittelbach** [comment]
I guess we can close this, right? Request noted (see recent checkins :-)) and alternatives discussed.
