### ISSUE TITLE
\big does not force horizontal mode

### ISSUE THREAD

**Issue by blefloch** [latex3/latex2e#50]
## Brief outline of the bug

Using `\big` at the beginning of a paragraph has the same problem as `\hbox`: the parenthesis ends up along in a line.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}
\begin{document}
We claim that $16^{3^2} = (8^4)^3$.

\big(Recall that $x^{y^z}=x^{(y^z)}$.\big)
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/1997898/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/1997899/test.pdf)

**Comment by blefloch** [comment]
This problem does not need amsmath.

**Comment by davidcarlisle** [comment]
comments and possible code changes for this issue are combined with those for issue #49

**Comment by eg9** [comment]
Neither does `\smash`, for instance, nor `\,` and `\enspace`. Only `\,` is mentioned in the LaTeX manual, which doesn't tell about `\big` in text mode.

**Comment by kberry** [comment]
also \thinspace and \negthinspace (ltspace.dtx)

**Comment by FrankMittelbach** [comment]
My guess is that for all the spaces the 2.09 rule "save tokens" was applied as starting a paragraph with a space is rather uncommon and back then each token did count. As this is no longer true these days one should add `\leavevmode` to all of them in my opinion to support even the rare cases as right now they are simply unusable at  that point.
