### ISSUE TITLE
Provide a way to use old definition of `\@fnsymbol`?

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#502]
## Brief outline of the enhancement

Since 2015/01/01, `\thanks` in `\maketitle` will try to use `\textasteriskcentered`. However not all commonly used fonts have it in the TS1 encoding. Stix2 does not.

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{stix2}

% Missing character: There is no * in font ts1-stix2text!
% same with TL2019
% lié à un changement en 2015 dans \@fnsymbol
% 2015/01/01 Release
% commit c08f8c6c de latex2e
\title{\string\textasteriskcentered\space gives empty in output: \textasteriskcentered}
\author{JFBU\thanks{mumble}}
\date{February 15, 2021}
\begin{document}
\maketitle

where are you \textasteriskcentered?

\end{document}
```

[bugtextasteriskcentered.log](https://github.com/latex3/latex2e/files/5980911/bugtextasteriskcentered.log)

Relates: c08f8c6c

**Comment by FrankMittelbach** [comment]
sigh, incomplete TS1 implementation are a nightmare ... :-(
```
Here: \textlegacyasteriskcentered

\renewcommand\textasteriskcentered{\textlegacyasteriskcentered}

where are you \textasteriskcentered?

or using \verb=\UseLegacyTextSymbols=
in the preamble
```

If somebody can figure out in which TS1 subencoding the stix2 font belongs We can make that work (hopefully out of the box) but that stix2 doesn't have the asterisk is really a font bug imho

**Comment by FrankMittelbach** [comment]
Actually `\textlegacy...`are described in ltnews31.

**Comment by jfbu** [comment]
> Actually `\textlegacy...`are described in ltnews31.

`\UseLegacyTextSymbols` does provide a workaround (it also does other things that resetting the footnote symbols, dealing with `\oldstylenums`).

I had promised myself to read in detail the ltnews31 entry... However I find no mention of `\textlegacy...` themselves.

**Comment by FrankMittelbach** [comment]
The kernel actually assumes that textasteriskcentered is available in all font that have a TS1 encoding. So it isn't really possible to put stix2 into some subencoding (there isn't one not containing that glyph).

I can't really believe that this happens in (many) other fonts because if so I would have expected that this problem would have shown up earlier.

Anyway, I think I will change the TS1 definition for it to become
```
\DeclareTextCommand \textasteriskcentered{TS1}{%
  \iffontchar\font 42 \char42 \else \textlegacyasteriskcentered \fi}
```
given that the asterisk is a core footnote symbol I think it should get lost so the math symbol is better than nothing.
Nevertheless stix2 should provide it I would say.

And yes you are right, we only described \UseLegacyTextSymbols ... so it isn't that clear from there,

**Comment by jfbu** [comment]
I get this
```
LaTeX Font Warning: Font shape `OMS/stix2/m/n' undefined
(Font)              using `OMS/cmsy/m/n' instead
(Font)              for symbol `textlegacyasteriskcentered' on input line 18.
```

I wonder if an approach such as ``\raisebox{-.3\height}{*}`` would not provide a poor man centered asterisk better fitting with the ambient font.

Much better however if stix2 had a more complete TS1 font table.

**Comment by FrankMittelbach** [comment]
well the substitution is what you get (and I think got in the past) so not really surprising you get a warning; other fonts may have OMS encoded fonts going with it.

Using a poor man's version would be possible too but it gets a little ugly too (because the symbols aren't the same size typically, so something like
```
\makeatletter
\DeclareTextCommand \textasteriskcentered{TS1}{%
  \iffontchar\font 42 \char42 \else 
   \begingroup\fontencoding{T1}%
       \fontsize
       {\the\dimexpr1.15\dimexpr\f@size pt\relax}%
       {\f@baselineskip}%
      \selectfont
      \raisebox{-0.6ex}[\dimexpr\height-0.6ex][0pt]{*}%
    \endgroup
   \fi}
\makeatother

\begin{document}

where are you * \textasteriskcentered?\textlegacyasteriskcentered\  
            \textbf{* \textasteriskcentered?\textlegacyasteriskcentered}
```

**Comment by jfbu** [comment]
Yes, I agree the poor man way is a lot of trouble with somewhat arbitrary choices, where the root problem is a font problem of less than ideal support of TS1.

There are other problems with stix2: https://github.com/stipub/stix_type1/issues/3

Also, the non-compression of fonts by pdflatex route shows clearly its effet. The MWE at the link above gives via pdflatex a file reported to have 324851 bytes (!) at my locale; with xelatex 4202 bytes, with latex+dvips+ps2pdf 6404 bytes, and wityh latex+dvipdfmx 4199 bytes.

For such font reasons generally speaking my preferred route to PDF has been latex+dvipdfmx whenever possible for a long time. However, as latex defaults to dvips driver when dvi output is on, one has the trouble to have to add dvipdfmx explicitly as class option. Making a multiple route source is complicated from the fact that \PassOptionsToClass will not make dvipdfmx known to hyperref (and geometry). On the + side, there is now no anymore trouble with dvipdfm having to be passed to geometry and some other stuff with hyperref.
