### ISSUE TITLE
LaTeX2e no longer keys packages by pathnames

### ISSUE THREAD

**Issue by Witiko** [latex3/latex2e#510]
## Brief outline of the bug

Prior to 75108758a9a1336676d99a97ea2ac5406be8dec8, LaTeX2e would key packages by the entire pathname (`\@ifl@aded\@currext{#1}%`). This made it possible to namespace packages by directory names as in the following example:

``` latex
\usepackage{directory1/package}
\usepackage{directory2/package}
```

Since 75108758a9a1336676d99a97ea2ac5406be8dec8, LaTeX2e keys packages only by their filename (`\@ifl@aded\@currext\@currname`), which makes the second `\usepackage` in the example above a noop. From packages that I personally maintain, this change breaks [fithesis][] and [markdown][].

 [fithesis]: https://ctan.org/pkg/fithesis
 [markdown]: https://ctan.org/pkg/markdown

## Minimal example showing the bug

Before typesetting, create directories `hello` and `world` in the current working directory.

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{filecontents}{hello/package.sty}
\def\hello{Hello }
\end{filecontents}
\begin{filecontents}{world/package.sty}
\def\world{world!}
\end{filecontents}
\usepackage{hello/package}
\usepackage{world/package}
\begin{document}
\hello\world  % Fails, because \world is undefined.
\end{document}
```

## Log file (required) and possibly PDF file  
[example.log](https://github.com/latex3/latex2e/files/6014789/example.log)
[example.pdf](https://github.com/latex3/latex2e/files/6014790/example.pdf)

**Comment by PhelypeOleinik** [comment]
I'm sorry, this was an intended change (but introduced with PR #438, not the one you linked), so we will probably not fix this.

The rationale between this change is that before it, you could do exactly that:
```latex
\usepackage{hello/package}
\usepackage{world/package}
```
but paths shouldn't matter when loading packages and both `hello/package` and `world/package` are `package.sty` which (hopefully) contains the same code (things get yet more confusing if you include `\input@path` to the mix).  For your own local packages that might not be always true, as is your case, but suppose another other package, for example, `array.sty`:  if I have a copy of `array.sty` under `hello/array.sty` then do
```
\usepackage{array}
\usepackage{hello/array}
```
that would break.  Also there is the problem that
```
\usepackage{hello/package}
\usepackage{./hello/package}
```
load the same file, but they would look like different packages for LaTeX.  So we decided to make both `hello/package` and `world/package` be internally identified by the file's base name, `package.sty`, thus don't load twice in that case.

I do wonder: why do you need the same name for packages in different directories?

**Comment by Witiko** [comment]
> I'm sorry, this was an intended change (but introduced with PR #438, not the one you linked), so we will probably not fix this.

You can bisect the change from `\@ifl@aded\@currext{#1}%` to `\@ifl@aded\@currext\@currname` to https://github.com/latex3/latex2e/commit/75108758a9a1336676d99a97ea2ac5406be8dec8.

> [...] but suppose another other package, for example, `array.sty`: if I have a copy of `array.sty` under `hello/array.sty` then do
> 
> ```
> \usepackage{array}
> \usepackage{hello/array}
> ```
> 
> that would break.

I don't see how this is a problem. If the package contains `\ProvidesPackage{hello/array}`, then it should either not be loaded as `\usepackage{hello/array}`, or LaTeX2e should use the value in `\ProvidesPackage` as the identifier.

> I do wonder: why do you need the same name for packages in different directories?

The fithesis package is highly modular and consists of many smaller LaTeX packages. The flat filesystem makes things difficult to name and maintain, so being able to namespace packages makes things easier. The markdown package supports user themes, where we want to be able to differentiate `user1/themeX` and `user2/themeX`.

**Comment by u-fischer** [comment]
> I don't see how this is a problem. If the package contains `\ProvidesPackage{hello/array}` ...

That would be much too late to decide if some of the package/file hooks should be executed or not. `\ProvidesPackage`  doesn't need to be the first thing in a file (and it doesn't need to be there at all, or can be `\ProvidesExplPackage`) and LaTeX can't scan a whole file only to detect the "real" package name. 

> The markdown package supports user themes, where we want to be able to differentiate user1/themeX and user2/themeX.

I would use something based on `\input` for such a setup, not on `\usepackage`.

**Comment by Witiko** [comment]
> > I don't see how this is a problem. If the package contains `\ProvidesPackage{hello/array}` ...
> 
> That would be much too late to decide if some of the package/file hooks should be executed or not. `\ProvidesPackage` doesn't need to be the first thing in a file (and it doesn't need to be there at all, or can be `\ProvidesExplPackage`) and LaTeX can't scan a whole file only to detect the "real" package name.

Technically, LaTeX could scan the whole file to detect the real package name, using the full pathname if it is not provided.

> > The markdown package supports user themes, where we want to be able to differentiate user1/themeX and user2/themeX.
> 
> I would use something based on `\input` for such a setup, not on `\usepackage`.

That's a valid suggestion, but then we lose the whole standard option-passing-to-packages mechanism. I realize that keying packages by full pathnames was never promised by LaTeX2e, but it is a departure from the previous behavior and a breaking change. I would expect less of these from a format that announces itself as stable.

**Comment by FrankMittelbach** [comment]
Vít

> Technically, LaTeX could scan the whole file to detect the real package 
> name, using the full pathname if it is not provided.

technically it probably could, yes, with a huge processing penalty for a 
case that has not be ever advertised as a supported solution and 
possibly side effects from scanning. I grant you that you have build a 
processing model around that unsupported method and so yes, it now 
breaks for you which i a pity but there are conceptually better 
solution and we think there are good reasons to not support it going 
forward.
> 
>         The markdown package supports user themes, where we want to be
>         able to differentiate user1/themeX and user2/themeX.
> 
>     I would use something based on |\input| for such a setup, not on
>     |\usepackage|.
> 
> That's a valid suggestion, but then we lose the whole standard 
> option-passing-to-packages mechanism.

if you prefer that then you could keep private name spaces by altering 
package name

> I realize that keying packages by full pathnames was never promised by 
> LaTeX2e, but it is a departure from the previous behavior and a breaking 
> change. I would expect less of these from a format that announces itself 
> as stable.

Stable doesn't mean stagnant and no change or improvement ever. Offering 
file hooks, for example, is a big improvement (it offers for example 
adjustments made based on whether or not some other package is loaded 
instead (as in the past) program with horrible if X loaded do Y and then 
tell people you package need to come after X (or push such re-coding to 
begin document and hope for the best).

Anyway, LaTeX will improve and ergo change in places (and in the future 
probably even more so), and yes that will make some workflows that 
happened to work for one ore the other reason invalid. We try to 
minimize impacts but it will not be possible to avoid that in all cases 
or produce elaborate coding around to maintain such workflows.

**Comment by Witiko** [comment]
Dear Frank,

thank you for the response and the suggestions. I admit that I fail to see how cramming structured information to a flat filename is a conceptually better solution to using directories, but the decision ultimately lies with the LaTeX team.

**Comment by PhelypeOleinik** [comment]
@Witiko Not necessarily better, but it's a compromise between implementation complexity and usability.

The restriction on paths for packages has two main reasons:
 - first, you can type a file like `path/to/file.sty` or like `./path/to//file.sty` or `.//path/to//../../path///to/../to/file.sty` and all point to the same location on your filesystem.  Making LaTeX differentiate between any of the above and, say, `./path/file.sty` would be a quite large programming exercise.  Definitely not impossible, but not trivial either.
 - second, and most important, any package that gets distributed with TeX Live or whatnot lives somewhere on a texmf tree and the file is found by name by `kpse`, which will completely(ish) ignore paths, so it will return the first `file.sty` it finds.  This means that if you have two package files that share the same name, one will hide the other. (I think CTAN also won't allow you to have duplicate names, but I'm not completely sure about that.)

So overall keeping the paths in LaTeX's internal data structures would be a good deal of extra processing to sanitise paths to support something that doesn't actually work due to how packages are organised in a TeX distribution.  Of course this unfortunately breaks local arrangements like yours, but it should be possible to port your setup from using `\usepackage` to something that uses `\input` and allows passing options using some keyval package.

**Comment by FrankMittelbach** [comment]
> I admit that I fail to see how cramming structured information to a flat filename is a conceptually better solution to using directories, but the decision ultimately lies with the LaTeX team.

that was't really what I meant. What we restrict as far as packages or classes are concerned is loading more than once a package or class with the same name. Also we do not differenciate the file hooks based on explicit packages. So

      \AddToHook{package/after/foo}{....}

applies to `\usepackage{foo}`  or `\usepackage{./foo}`  or even `\usepackage{dir1/foo}` and after any of them them got executed `foo` is consided being loaded and so will not be loaded again.

So  my suggestion was more that if you want to keep directories and have explicit loading paths (which means local to your main file) you nevertheless call the package differently, eg  xx/xx-foo.sty and yy/yy-foo.sty. That doubles the "xx" unnecessarily, you may say, but it means other aspects of LaTeX are free of needing to know where from you call the package and whether that is vial automaticly finding it  or not.

**Comment by Witiko** [comment]
> * second, and most important, any package that gets distributed with TeX Live or whatnot lives somewhere on a texmf tree and the file is found by name by `kpse`, which will completely(ish) ignore paths, so it will return the first `file.sty` it finds.  This means that if you have two package files that share the same name, one will hide the other.

@PhelypeOleinik KPathSea will index all occurences of `file.sty`. You can request any of them by pathname suffix:

```
$ kpsewhich -a fithesis-base.sty
/home/witiko/texmf/tex/latex/fithesis/style/fithesis-base.sty
/home/witiko/texmf/tex/latex/fithesis/style/mu/fithesis-base.sty
$ kpsewhich -a fithesis/style/fithesis-base.sty
/home/witiko/texmf/tex/latex/fithesis/style/fithesis-base.sty
$ kpsewhich -a fithesis/style/mu/fithesis-base.sty
/home/witiko/texmf/tex/latex/fithesis/style/mu/fithesis-base.sty
```

> (I think CTAN also won't allow you to have duplicate names, but I'm not completely sure about that.)

The duplicates from the above examples are currently present on CTAN. Granted, this may not fly for new submissions, since it makes `\usepackage{fithesis-base}` non-deterministic.

> […] Of course this unfortunately breaks local arrangements like yours, but it should be possible to port your setup from using `\usepackage` to something that uses `\input` and allows passing options using some keyval package.

That's what is likely going to happen, but reinventing the wheels benefits noone. The file hooks discussed by @FrankMittelbach, for example, won't work, and neither will other mechanisms such as rollbacks.

> So my suggestion was more that if you want to keep directories and have explicit loading paths (which means local to your main file) you nevertheless call the package differently, eg xx/xx-foo.sty and yy/yy-foo.sty. That doubles the "xx" unnecessarily, you may say, but it means other aspects of LaTeX are free of needing to know where from you call the package and whether that is vial automaticly finding it or not.

@FrankMittelbach This helps with maintenance, but introduces its own problems: Most filesystems limit file lengths and you must explicitly select a separator character (`-` in your example), which may not occur in either `yy` or `foo`. Neither is unsurmountable, but it shows the limits of the flat filesystem paradigm of TeX, which `\usepackage{directory/package}` provided an escape from.

**Comment by u-fischer** [comment]
> Technically, LaTeX could scan the whole file to detect the real package name, 

As you wrote yourself "the scanning would be without expansion and therefore imperfect.". 

As \ProvidesPackage can be easily hidden, obfuscated or be missing at all or contain the wrong name it is technically impossible for LaTeX to detect if `xx/foo`  means only `foo` from an unusual place, or a special `foo`. There are to many edge cases and it would  lead to a maintenance nightmare. The decision that the package name is *only* the package name was made after a number of examples and issues which showed us how problematic it is to take pathes into account. 

> but it shows the limits of the flat filesystem paradigm, which \usepackage{directory/package} provided an escape from.

If you want a special handling of paths, then write a dedicated `\usepackagewithpath` command which doesn't conflict with a command used by every LaTeX user in a large variety of environments and documents. Check packages like import or subfiles which provide commands which take directories into account.

**Comment by Witiko** [comment]
> Check packages like import or subfiles which provide commands which take directories into account.

Thank you for the helpful suggestions.
