### ISSUE TITLE
footnotetext and footnotemark are unreliable

### ISSUE THREAD

**Issue by bastien-roucaries** [latex3/latex2e#512]
Hi,

Better will be to use `\footmark{ref}` and `\foottext{label}{text`}. 

Bastien

**Comment by josephwright** [comment]
@FrankMittelbach Covered by the new `\footref`?

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Covered by the new `\footref`?

probably. I'm missing some context here. `\footref` is like `\footmark`but takes a label string as its argument  so if that refers to a label inside a `\footnote` then you get roughly this but in 2e syntax.   xfootnote is some experimental  xtemplate stuff for footnotes which never got  really followed up.
