### ISSUE TITLE
\ProcessOptions of LaTeX 2021/05/01 allows braces but \ProcessOptions* does not

### ISSUE THREAD

**Issue by komascript** [latex3/latex2e#513]
## Brief outline of the bug

From LaTeX 2021/05/01 the modified code of `\ProcessOptions` does allow `{…}` in the option list, but this fails, if a package uses the star variant `\ProcessOptions*` and braces are used inside the global option list of `\documentclass`.

## Minimal example showing the bug

```latex
\begin{filecontents}{testStar.sty}
\ProvidesFile{testStar}[2021/03/02]
\ProcessOptions*
\relax
\end{filecontents}
%\RequirePackage{latexbug}% Not used, because demontration package is needed!
\documentclass[foo={bar,BAR}]{article}
\usepackage{testStar}
\begin{document}

\end{document}
```

## Log file (required) and possibly PDF file  

```
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex-dev 2021.3.2)  2 MAR 2021 16:03
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**test.tex
(./test.tex
LaTeX2e <2021-05-01> pre-release-2 (develop 2021-3-2 branch)
L3 programming layer <2021-02-18>

LaTeX Warning: Writing file `./testStar.sty'.

\openout15 = `testStar.sty'.


(/usr/local/texlive/2021/texmf-dist/tex/latex-dev/base/article.cls
Document Class: article 2021/02/12 v1.4n Standard LaTeX document class
(/usr/local/texlive/2021/texmf-dist/tex/latex-dev/base/size10.clo
File: size10.clo 2021/02/12 v1.4n Standard LaTeX file (size option)
)
\c@part=\count179
\c@section=\count180
\c@subsection=\count181
\c@subsubsection=\count182
\c@paragraph=\count183
\c@subparagraph=\count184
\c@figure=\count185
\c@table=\count186
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
) (./testStar.sty
File: testStar 2021/03/02

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.6 \ProcessOptions*
                    
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

) (/usr/local/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
File: l3backend-pdftex.def 2021-02-18 L3 backend support: PDF output (pdfTeX)
\l__color_backend_stack_int=\count187
\l__pdf_internal_box=\box50
) (./test.aux)
\openout1 = `test.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 9.
LaTeX Font Info:    ... okay on input line 9.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 9.
LaTeX Font Info:    ... okay on input line 9.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 9.
LaTeX Font Info:    ... okay on input line 9.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 9.
LaTeX Font Info:    ... okay on input line 9.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 9.
LaTeX Font Info:    ... okay on input line 9.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 9.
LaTeX Font Info:    ... okay on input line 9.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 9.
LaTeX Font Info:    ... okay on input line 9.
[1

{/usr/local/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./test
.aux) ) 
Here is how much of TeX's memory you used:
 393 strings out of 478903
 7007 string characters out of 5857137
 291333 words of memory out of 5000000
 18059 multiletter control sequences out of 15000+600000
 403430 words of font info for 27 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 44i,5n,50p,144b,316s stack positions out of 5000i,500n,10000p,200000b,80000s
</usr/local/texlive/2021/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10
.pfb>
Output written on test.pdf (1 page, 9635 bytes).
PDF statistics:
 13 PDF objects out of 1000 (max. 8388607)
 7 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
```

## Note

If you change the `\ProcessOptions*` into `\ProcessOptions` no error occurs.

The problem is caused by:

```latex
\@expandtwoargs\in@{,\CurrentOption,}{,\@declaredoptions,}
```

in the definition of `\@xprocess@ptions`, because the definition of `\in@` does not allow braces.

I know, currently this is not a bug. However, if in future key-value options with values in braces should be possible, this could become a problem.

**Comment by davidcarlisle** [comment]
Thanks for the report

> because the definition of \in@ does not allow braces.

Yes sorry, avoiding \in@ and \zap@space in all cases while keeping maximum compatibility continues to prove difficult.
Clearly missed one case here, we will get back to you with a proposal.

**Comment by davidcarlisle** [comment]
I'd need to run the test suite and think about it a bit more but I think the consistent thing to do is add \@remove@eq@value in one more place to be consistent with its addition in \@use@option

```
\makeatletter
\def\@xprocess@ptions{%
  \ifx\@currext\@clsextension\else
    \@for\CurrentOption:=\@classoptionslist\do{%
      \ifx\CurrentOption\@empty\else
        \@expandtwoargs\in@{,\expandafter\@remove@eq@value\CurrentOption=\@nil,}{,\@declaredoptions,}%
        \ifin@
          \@use@ption
          \expandafter\let\csname ds@\CurrentOption\endcsname\@empty
        \fi
      \fi}%
  \fi
  \@process@pti@ns}
\makeatletter

\documentclass[foo={bar,BAR}]{article}
%\documentclass[foo]{article}

\usepackage{testStar}

\begin{document}

\end{document}
```

If the testStar package is set up using the classical option processing it can't have braces in its declared options (having a list of delared options including values would be odd anyway) so I think it's only necessary to make \CurrentOption safe here.

This does have a theoretical effect on an existing option usisng = in its name such as a=b which (with no braces) would not actually error previously but considering `a=b` as an option name not an option a with value b hopefully doesn't occur in real cases. 

As I say this needs more testing and is just an initial proposal but @komascript  I'd be interested to know if this addresses the use case that triggered this for you

**Comment by komascript** [comment]
> This does have a theoretical effect on an existing option usisng = in its name such as a=b which (with no braces) would not actually error previously but considering `a=b` as an option name not an option a with value b hopefully doesn't occur in real cases.

Unfortunately it does. E.g. `biblatex` has `\DeclareOption{bibliography=totoc}{…}` in `blx-compat.def`.

> As I say this needs more testing and is just an initial proposal but @komascript I'd be interested to know if this addresses the use case that triggered this for you

I've just tested, if KOMA-Script's `\FamilyKeyOptions` interferes with the changed option handling of LaTeX 2021/05/01. I found, that braces in option lists fail again, if `scrbase` is loaded. `\FamilyKeyOptions` is an extended key-value version of `\ProcessOptions*`. So after I've made a first slow, but brace-robust version of `\FamilyKeyOptions`, I've tested, whether `\ProcessOptions*` has the same issue. Currently I'm using a poor man's loop:

```latex
\in@false
\@for \reserved@a:=\@declaredoptions\do{%
   \ifx\CurrentOption\reserved@a\in@true\fi
}%
```

but I'm thinking about using a `clist` mapper instead. → https://sourceforge.net/p/koma-script/tickets/1/

**Comment by davidcarlisle** [comment]
> Unfortunately it does.

Someone always does something.  Thanks for the test

**Comment by davidcarlisle** [comment]
```
$ grep -rl '\\DeclareOption{[^{}]*[=][^{}]*}' 
abntex2/abntex2.cls
abntex2/abntex2cite.sty
biblatex/blx-compat.def
biblatex-chicago/biblatex-chicago.sty
colorspace/colorspace.sty
complexity/complexity.sty
computational-complexity/cc.cls
enumitem/enumitem.sty
gincltex/gincltex.sty
graphicxpsd/graphicxpsd.sty
latex-uni8/uni8.sty
lettre/lettre.cls
pgf/basiclayer/pgf.sty
pgf-umlsd/pgf-umlsd.sty
srdp-mathematik/srdp-mathematik.sty
trivfloat/trivfloat.sty
```

so clearly we need to not break that usage...

**Comment by komascript** [comment]
Maybe it is naive, but way not:

```latex
\def\@xprocess@ptions{%
  \ifx\@currext\@clsextension\else
    \@for\CurrentOption:=\@classoptionslist\do{%
      \ifx\CurrentOption\@empty\else
        \@ifundefined{ds@\CurrentOption}{}{%
          \@use@ption
          \expandafter\let\csname ds@\CurrentOption\endcsname\@empty
        }%
      \fi}%
  \fi
  \@process@pti@ns}
```

AFAIK at the same time, when LaTeX adds an option to `\@declaredoption`, it also defines the `\ds@…` of that option. And the `\ds@…` are set to `\relax` at the very end of `\ProcessOptions`/`\ProcessOptions*` in `\@process@pti@ns`. And `\@process@pti@ns` also uses the `\@ifundefined{ds@\CurrentOption}` test.

So shouldn't `\@ifundefined{ds@\CurrentOption}` be a valid and fast test here too?

**Comment by FrankMittelbach** [comment]
fix merged to develop
