### ISSUE TITLE
some utf8 chars are not accepted in package id lines

### ISSUE THREAD

**Issue by norbusan** [latex3/latex2e#52]
## Minimal example showing the bug

file xstyle.sty
```latex
\NeedsTeXFormat{LaTeX2e}%
\ProvidesPackage{xstyle}[2018/03/10 1.1 Teckids Teχ/LᴬTᴇX style, second epoch]%
```

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}%
\usepackage{xstyle}%
\begin{document}
foo
\end{document}
```

## Log file (required) and possibly PDF file  

[xdoc.log](https://github.com/latex3/latex2e/files/2082911/xdoc.log)

## Comments

Checked with TL up to date as of today (20180608). The [original Debian bug report ](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900980) mentions that it was working "before" so it must have been some recent LaTeX update.

**Comment by davidcarlisle** [comment]
Hi Norbert,  This has actually never really worked: it is the same issue as

\documentclass{article}
\usepackage[utf8]{inputenc}
\begin{document}
\typeout{Teχ/LᴬTᴇX}
\end{document}

So previously the package would have worked or not worked depending on whether it was loaded before or after inputenc.

What has changed is that it's now harder to avoid the problem by loading the package earlier.

It's been a long standing aim to make \typeout (and  \ProvidesPackage etc) more robust in the face of active characters but there are several possible approaches and all have potential impact on existing ctan packages.

However we should probably look at this again for next time to see if there are some reasonably compatible changes that can be made here.

Meanwhile the package can protect itself from inputenc utf-8 handling (in new or old versions of latex) by

```
\ProvidesPackage{xstyle}[2018/03/10 1.1 \detokenize{Teckids Teχ/LᴬTᴇX style, second epoch}]%
```

**Comment by mirabilos** [comment]
> What has changed is that it's now harder to avoid the problem by loading the package earlier.

Oh, that could be…

Our actual use case is that we have a `.cls` file that is rather minimal (loads `fancyhdr`, `scrartcl` and our own `.sty` file, then defines a few macros), and the “house” `.sty` file loads all other “commonly used” packages, beginning with `accsup` and `[utf8]{inputenc}`, so both `\ProvidesPackage` from the `.cls` and the `.sty` files were previously processed *before* `inputenc` was loaded.

For the actual files, see `teckids2*` [here](https://edugit.org/Teckids/teckids-tex/tree/master).

**Comment by davidcarlisle** [comment]
@mirabilos  I see you have changed to use an ASCII ProvidesPackage.

To be honest I think that is the most portable fix, even now (in 2018) you can not be sure that the user has a terminal using UTF-8 in which the Unicode message would be understandable.  However if you want to revert to the previous message, then using `\detokenize` as in my initial reply to Norbert should work (ping here if not!)

**Comment by FrankMittelbach** [comment]
@davidcarlisle, @mirabilos well, it may not have been stated explicitly (though it might somewhere) but when written the spec was that \ProvidesPackage has a 7-bit argument (just like it isn't explicitly written (very often) that label and ref args are supposed to be 7-bit.

That fact that 8-bit or utf8 happened to work (sometimes) in those places doesn't really change that this is a very fragile area and anything other than 7bit is kind of outside the spec. So staying with 7bit is probably the best course even though, as David said, we are looking at making \typeout and friends properly support utf8 eventually.

**Comment by mirabilos** [comment]
Hmm, okay.

My assumption was more on the path that “in 2018, everything ought to be 8-bit clean/transparent” and (more a support scope than an assumption) “if the user doesn’t use UTF-8 they’re SOL anyway” since if a system is 8-bit transparent you can use any encoding (using ASCII as base) with it as passthrough. 

Turns out that the first assumption was incorrect. Huh.

**Comment by FrankMittelbach** [comment]
@mirabilos we are on the way in that direction but in many places this is still a compromise if you are on an 8-bit engine, eg without a unicode engine csnames are somewhat restricted and there is no way around that and emulating utf8 with active chars already goes a very long way but in some places the history (and the resulting restrictions show through).

That problem would be totally gone if you use luatex or xetex, but as of now they do have their own issues and limitations and while that is the case and pdftex is the dominant engine we wil be somewhat between all chairs and encounter one or the other limitation/restriction along the way. The 2018 move to supporting utf8 as "text input encoding" by default was a big step in the right direction but that wasn't (yet) a move that made uft8 transparent in all aspects of processing, eg  \übermorgen will not be today (nor tomorrow) a csname (at least not for all unicode chars out there.

**Comment by mirabilos** [comment]
Hm yes, I implemented other pdftex-specific things, and all our integrations (various Makefiles, *shudder* Maven plugins, etc.) are all also pdflatex-only.

I guess for maximum compatibility we’ll just stick with ASCII in those places, then.

**Comment by FrankMittelbach** [comment]
Not sure if I overlook anything but wouldn't this here do it? (maybe even just chaging \wlog):

```
\def\save@wlog#1{\begingroup \set@display@protect \immediate \write \m@ne {#1}\endgroup }

\def\@pr@videpackage[#1]{%
  \expandafter\protected@xdef\csname ver@\@currname.\@currext\endcsname{#1}%  <-- protected...
  \ifx\@currext\@clsextension
    \typeout{Document Class: \@gtempa\space#1}%
  \else
    \save@wlog{Package: \@gtempa\space#1}%   <--- protected
  \fi}
```

**Comment by davidcarlisle** [comment]
@FrankMittelbach  looks Ok to me, apart from the name .`\safe@wlog` possibly or `\protected@wlog` would match \protected@write` ?

**Comment by FrankMittelbach** [comment]
yeah `\protected@wlog` looks fine to me
