### ISSUE TITLE
Recognize .<number> file names as metapost graphics files

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex2e#521]
## Brief outline of the enhancement

Karl suggests making pdfTeX recognize file names `.[1-9]`, or more generally `.<number>` as Metapost output graphics, and use the `mps` rule, rather than requiring a generic rule.  This could be applied to all backends, so I'm adding the issue here rather than in `graphics-def` for now.

## Minimal example showing the current behaviour

Currently one needs to declare a generic rule `\DeclareGraphicsRule{*}{mps}{*}{}` for metapost files:

```latex
\RequirePackage{latexbug}
\begin{filecontents}[overwrite]{graph-test.1}
%!PS
%%BoundingBox: -1 -1 29 29 
%%Page: 1 1
newpath
0 0 moveto
29 0 lineto
29 29 lineto
0 29 lineto
closepath stroke
showpage
%%EOF
\end{filecontents}
\documentclass{article}
\usepackage{graphicx}
\DeclareGraphicsRule{*}{mps}{*}{}
\begin{document}
\includegraphics{graph-test.1}
\end{document}
```

## Minimal example showing the desired new behaviour

The change would be equivalent to
```latex
\makeatletter
\def\x#1{\@namedef{Gin@rule@.#1}##1{{mps}{.#1}{##1}}}
\x1\x2\x3\x4\x5\x6\x7\x8\x9
\makeatother
```
for `.[1-9]` or a bit cleverer to accept a number as extension.

```latex
\RequirePackage{latexbug}
\begin{filecontents}[overwrite]{graph-test.1}
%!PS
%%BoundingBox: -1 -1 29 29 
%%Page: 1 1
newpath
0 0 moveto
29 0 lineto
29 29 lineto
0 29 lineto
closepath stroke
showpage
%%EOF
\end{filecontents}
\documentclass{article}
\usepackage{graphicx}
\makeatletter
\def\x#1{\@namedef{Gin@rule@.#1}##1{{mps}{.#1}{##1}}}
\x1\x2\x3\x4\x5\x6\x7\x8\x9
\makeatother
\begin{document}
\includegraphics{graph-test.1}
\end{document}
```

**Comment by davidcarlisle** [comment]
We discussed this, but decided against, you could only support a fixed list of numbers (say 0-9) without complicating the file parsing code for all documents by allowing any extension following a pattern, and metapost has for some time allowed the output extension to be specified to be a more conventional fixed extension reflecting the file type.
