### ISSUE TITLE
Add support for \tracingstacklevels and \tracinglostchars=3 in tracing tools

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex2e#524]
## Brief outline of the enhancement

In 2020 `\tracingstacklevels=<depth>` was added to most TeX engines to trace the macro call stack up to `<depth>` levels, and `\tracinglostchars=3` to make missing characters an error rather than a sneaky one-line warning in the `.log`.  Both could be added to the definition of `\tracingall/none` and in the kernel, and `\traceon/off` in `trace.sty`.

## Minimal example showing the desired new behaviour

This document:

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{document}
{%

\tracingonline=1

\def\a{\b{}}
\def\b{\c{}}
\def\c{\d{}}
\def\d{hi}

\tracingmacros=1
\tracingstacklevels=\maxdimen
\a

\tracinglostchars=3
\nullfont a

}
\end{document}
```

with the new tracing tools would give:
```none
~.\a ->\b {}

~..\b ->\c {}

~...\c ->\d {}

~....\d ->hi
```
for the macro calls, and the error:
```none
! Missing character: There is no a ("61) in font nullfont.
<recently read> a
                 
l.18 \nullfont a
                
?
```

for the missing character.

**Comment by car222222** [comment]
All good stuff!
