### ISSUE TITLE
Unused option list practically broken for any third-party package in LaTeX2e <2021-05-01> pre-release-2

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex2e#527]
## Brief outline of the bug

The plans on changing the option handling are a step in the right direction, imho, but the way the unused option list is handled currently (omitting `=<value>`) breaks almost *every* third party option handling package that tries to deal correctly with it. The breakage doesn't mean they don't work anymore, but only that none of them can now remove the option from the unused option list (so nothing too severe).

## Suggested "fix"

Change the implementation of `\@removeelement` as most packages use it to deal with the `\@unusedoptionlist` (exceptions of the tested packages here are `l3keys2e` which uses `\clist_remove_all:Nn` and `expkv-opt`). The proposed change would be:

1. check if the last argument is `\@unusedoptionlist`. If false, continue with the old implementation, is true continue here:
2. remove `=<value>` from the first argument
3. continue with the old implementation and the altered argument

This way all the packages using `\@removeelement` (including some packages that don't use the well-known key=val packages, but define their own internal option handling) would work correctly (and the side effects should be only a slightly reduced performance for the other usages of `\@removeelement`).

## Minimal example showing the bug

In the following example the `global` option will not be removed from the unused option list (even though it had been picked up by several packages which would all remove it with the current LaTeX2e release).

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass[global=5, noval]{article}

\begin{filecontents}{optionlist-test.sty}
\ProvidesPackage{optionlist-test}

\RequirePackage{pgfopts}
\pgfkeys
  {
     optionlist-test/.cd
    ,global/.code={\typeout{(pgfopts) global used, value was `#1'}}
    ,local/.code={\typeout{(pgfopts) local used, value was `#1'}}
    ,noval/.code={\typeout{(pgfopts) noval used}}
  }

\RequirePackage{expkv-opt,expkv-def}
\ekvdefinekeys{optionlist-test}
  {
     code global = \typeout{(expkv) global used, value was `#1'}
    ,code local  = \typeout{(expkv) local used, value was `#1'}
    ,noval noval = \typeout{(expkv) noval used}
  }

\RequirePackage{l3keys2e}
\ExplSyntaxOn
\keys_define:nn { optionlist-test }
  {
     global .code:n = \typeout{(l3keys2e)~ global~ used,~ value~ was~ `#1'}
    ,local .code:n = \typeout{(l3keys2e)~ local~ used,~ value~ was~ `#1'}
    ,noval .code:n = \typeout{(l3keys2e)~ noval~ used}
  }
\ExplSyntaxOff

\RequirePackage{kvoptions}
\SetupKeyvalOptions
  {%
    family=optionlist-test,
    prefix=tyt@
  }
\DeclareStringOption{global}\let\tyt@global\@undefined
\DeclareStringOption{local}\let\tyt@local\@undefined
\DeclareStringOption{noval}[]\let\tyt@noval\@undefined

\RequirePackage{options}
\options
  {
     /optionlist-test/.new family
    ,/optionlist-test/global/.new cmd = \typeout{(options) global used, value was `#1'}
    ,/optionlist-test/local/.new cmd = \typeout{(options) global used, value was `#1'}
    ,/optionlist-test/noval/.new cmd* = \typeout{(options) noval used}
  }

%% call the option handlers
\ProcessPgfOptions{/optionlist-test}
\ekvoProcessGlobalOptions{optionlist-test}
\ekvoProcessLocalOptions{optionlist-test}
\ProcessKeysOptions{optionlist-test}
\ProcessKeyvalOptions{optionlist-test}
\options@ProcessOptions{optionlist-test}
\ifdefined\tyt@global
  \typeout{(kvoptions) global used, value was `\tyt@global'}
\fi
\ifdefined\tyt@local
  \typeout{(kvoptions) local used, value was `\tyt@local'}
\fi
\ifdefined\tyt@noval
  \typeout{(kvoptions) noval used}
\fi
\end{filecontents}

\usepackage[local={6}]{latexdef-optionlist-test}

\begin{document}
\end{document}
```

## Log file (required) and possibly PDF file  

[optionlist-test.log](https://github.com/latex3/latex2e/files/6098032/optionlist-test.log)

**Comment by davidcarlisle** [comment]
I assume you meant optionlist-test not latexdef-optionlist-test in the `\usepackage`

Granted keyval option list processors may need to adjust but I would assume they would adjust anyway to use the new raw lists,

when you say

> none of them can now remove the option from the unused option list

You mean that they may not do the right thing currently (needing to strip the value) not that there is information loss and they can not do this don't you? (or I missed something?)  

I'm a bit afraid of introducing special case behaviour to `\@removeelement` which we'd have to keep forever, to avoid having to suggest changes in the (more or less known)  list of packages that define extended option handlers, especially as they may end up using completely different code, based on the raw lists.

That's not to say we shouldn't do this,  just giving some initial thoughts. Any change here is a delicate balancing act and it's not impossible the balance needs adjusting here, comments from others welcome....

**Comment by Skillmon** [comment]
> You mean that they may not do the right thing currently (needing to strip the value) not that there is information loss and they can not do this don't you? (or I missed something?)

Yes, that's what I meant. And you have a point in that the (actively maintained) key=value processors will most likely be adapted to use the new possibilities anyway.

The thing with `\@removeelement` is that this change would also impact/fix packages that don't use the well known list of key=value packages, as they implement an internal version of option handling (like, e.g., `microtype` does, just to name a single example). Of course one has to balance this, as it is used elsewhere, too, but the proposed change should be rather safe (I doubt that any package relies on `\@removeelement` not doing any tests, and I doubt that any package would need the old behaviour when dealing with `\@unusedoptionlist`).

I have yet to take a thorough look at the different usages of `\@removeelement` in the currently distributed packages.

**Comment by davidcarlisle** [comment]
After some discussion we decided to leave this as it is in the upcoming releases.  The intent of introducing the new "raw" lists was to minimise changes in the current standard option processing.  While it is true that in some cases you may get an unused option warning with keyval arguments the expectation is that this temporary as any packages allowing such keyval options should update to use the new lists in any case and can adjust the warning.
