### ISSUE TITLE
Contribution to layout.sty with Romanian language

### ISSUE THREAD

**Issue by JohannesBraams** [latex3/latex2e#529]
!! Please fill out all sections after reading CONTRIBUTING guidelines (and remove lines starting with !!)

## Brief outline of the bug
The package layout doesn't support the Romanian language

Patrick Danilevici wrote: 
Hi,
I would like to contribute to package "layout" by adding Romanian language.

here is the code:

\DeclareOption{romanian}{%
  \def\Headertext{Antet}
  \def\Bodytext{Corp}
  \def\Footertext{Subsol}
  \def\MarginNotestext{Note\\ Marginale}
  \def\oneinchtext{un inch}
  \def\notshown{neafișat} %  <-- i don't know if this must be escaped so I typed in UTF8
  }

If you consider, please add this to next release.

Best regards,

Patrick Danilevici

**Comment by mafsi** [comment]
Thanks for taking my email intro consideration!
