### ISSUE TITLE
IfFileExists doesn't support unbalanced conditionals

### ISSUE THREAD

**Issue by blefloch** [latex3/latex2e#530]
## Brief outline of the bug

When the argument of `\IfFileExists` includes an unbalanced primitive TeX conditional, things break, because `\IfFileExists@` uses its arguments within some TeX conditionals:
```
\ifx\input@path\@undefined
  \def\reserved@a{#3}%
\else
  \def\reserved@a{\@iffileonpath{#1}{#2}{#3}}%
\fi
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\batchmode
\IfFileExists{ifpdf.sty}{\usepackage{ifpdf}\ifpdf\fi}{}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/6121662/test.log)

**Comment by blefloch** [comment]
This bug seems to exist since 2008.  I haven't checked code for other related commands like `\InputIfFileExists`.

**Comment by FrankMittelbach** [comment]
As far as I can see all it needs is adjusting
```
\makeatletter
\long\def \IfFileExists@#1{%
  \openin\@inputcheck"#1" %
  \ifeof\@inputcheck
    \ifx\input@path\@undefined
      \let\reserved@a\@secondoftwo
    \else
      \def\reserved@a{\@iffileonpath{#1}}%
    \fi
  \else
    \closein\@inputcheck
    \edef\@filef@und{"#1" }%
    \let\reserved@a\@firstoftwo
  \fi
  \reserved@a}
\makeatother
```
to not  use `#2` and `#3` at this stage.

**Comment by blefloch** [comment]
Strictly speaking there is a related issue in \include, in case #1 contains
unbalanced conditionals.  I think that's the only similar conditional-nesting
problem in ltfiles (in all other cases where #1 etc are used within a
conditional, these arguments are already-expanded file names.

**Comment by FrankMittelbach** [comment]
@blefloch I think it is hard to see a use case where an unbalanced conditional in `#1` would be menaingful -- this is supposed to resolve to a file name (more or less) after all not to random code, or am I missing something?

**Comment by FrankMittelbach** [comment]
But I was wrong the above definition I suggested changes the semantics, before one had to write
```
\IfFileExists{trace.sty}{\def\foo##1{\typeout{##1}}}{}
```
and with the change it would be
```
\IfFileExists{trace.sty}{\def\foo#1{\typeout{#1}}}{}
```

**Comment by FrankMittelbach** [comment]
that macros is used in 598 packages, who knows how many of them deploy `##1` ... so unless we really go for a long checking session this seems to be a non-starter.

**Comment by blefloch** [comment]
It's probably trivial to do the following, no?

\def\tmp{{#2}{#3}}
\ifx ......
   ***@***.******@***.***\tmp}%
\else
   ***@***.******@***.***\tmp}%
\fi

**Comment by blefloch** [comment]
Ah, I guess this is not perfect emulation since one could have a situation where
#2 or #3 contains un-doubled # by mistake, and this would only blow up in the
branch where #2 or #3 is taken (or the ***@***.*** branch).  This should work
(untested).

\long\def \IfFileExists@#1#2#3{%
  ***@***.***"#1" %
  ***@***.***
    ***@***.******@***.***
      ***@***.******@***.***
    \else
      ***@***.******@***.***{#1}}%
    \fi
  \else
    ***@***.***
    ***@***.***@und{"#1" }%
    ***@***.******@***.***
  \fi
  ***@***.***
    ***@***.***{#2}{#3}}%
  ***@***.***}

**Comment by FrankMittelbach** [comment]
@blefloch reminds me of some puzzle questions due to the missing markup :-)

But besides that, there correct way is probably not to require doubling the `##` since elsewhere don't require that either (but that is a breaking change) so is it really better to complicate the processing instead of documenting the limitation (as long as we aren't changing/fixing the `##` behavior?

**Comment by blefloch** [comment]
Ok, haha, this is crazy, I didn't know github would do that to my code!  I've now edited.

**Comment by FrankMittelbach** [comment]
Am 12.03.21 um 11:30 schrieb Bruno Le Floch:
> The processing I'm giving in my previous post is 1-2 more lines and it 
> fixes a
> package whose maintainer is (maybe) AWOL so I don't see why we wouldn't 
> do it.

well, it would help if you mark up the fix so that it doesn't come out 
as a long list of ****@***@**** :-)

**Comment by FrankMittelbach** [comment]
> Ok, haha, this is crazy, I didn't know github would do that to my code! I've now edited.

I think it reads the `@` as the start of a name and then goes crasy if it doesn't make sense :-)

**Comment by FrankMittelbach** [comment]
@blefloch use three ``` on a line of their own before and after or indent the code by (I think 4) spaces

**Comment by blefloch** [comment]
I know, @FrankMittelbach, but Markdown is disabled for messages that came from an email.  Regarding the `@` mangling, I think github was doing two things: thinking that `input@path` and similar are email addresses that should be hidden, and thinking that `@filef` is a reference to a github user (hence the weird capitalization, I checked that the guy exists).  Anyways, here is the unmangled code.


```
\long\def \IfFileExists@#1#2#3{%
  \openin\@inputcheck"#1" %
  \ifeof\@inputcheck
    \ifx\input@path\@undefined
      \let\reserved@a\@secondoftwo
    \else
      \def\reserved@a{\@iffileonpath{#1}}%
    \fi
  \else
    \closein\@inputcheck
    \edef\@filef@und{"#1" }%
    \let\reserved@a\@firstoftwo
  \fi
  \expandafter\def\expandafter\reserved@a
    \expandafter{\reserved@a{#2}{#3}}%
  \reserved@a}
```

**Comment by FrankMittelbach** [comment]
fixed it now using your suggestion
