### ISSUE TITLE
Option in doc package to write the change date in .gls file

### ISSUE THREAD

**Issue by maieul** [latex3/latex2e#531]
## Brief outline of the enhancement

Add and option into `doc` package in order to output the change date to the .glo file. 
When you have a lot of change in a package, it would be usefule to see quickly the change date.

See https://chat.stackexchange.com/transcript/message/57321268#57321268

## Minimal example showing the current behaviour

Any classical pacckage using ltxdoc, like array.dtx

## Minimal example showing the desired new behaviour

```latex
\RecordChangeWithDate%Or maybe new option to the packa,e
```

**Comment by FrankMittelbach** [comment]
This will be provided as option `reportchangedates` in release 2022/06/01 (and earlier in -dev format).

**Comment by FrankMittelbach** [comment]
Doc now has:

reportchangedates    Boolean (default false). If set, then change entries list the date after the version number in the change log.

I've just forgotten to close this pr.
