### ISSUE TITLE
middle vertical alignment m{} in tabular does not work when mixed with p{}-alignment in another column

### ISSUE THREAD

**Issue by zahlenzauber** [latex3/latex2e#533]
## Brief outline of the bug
When I use the m-vertical alignment only, the columns are vertically aligned as expected. If there is one p-alignment the cell content of all columns is not aligned in the middle anymore.
Is this reproducible?

## Minimal example showing the bug

```latex
\documentclass[
]{book}



\usepackage{array}

\begin{document}

This works as it should: Column 1 with middle vertical alignment.

\begin{tabular}{m{2cm} m{2cm}}
short text & longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext \\
\end{tabular}



\vskip 2em
Here the vertical alignment for column 1 is broken, although only column 2 has been changed.
\vskip 2em

\begin{tabular}{m{2cm} p{2cm}}
short text & longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext \\
\end{tabular}


\end{document}

```

## Log file (required) and possibly PDF file  

[__arrayTabularMWE.pdf](https://github.com/latex3/latex2e/files/6156331/__arrayTabularMWE.pdf)
[pdflatex.log](https://github.com/latex3/latex2e/files/6156360/pdflatex.log)

**Comment by u-fischer** [comment]
The alignment is correct. `m` columns are centered around the baseline of the row. If there is only one line in the m-column this is one the baseline. Try this

~~~~
\documentclass[]{book}

\usepackage{array}
\usepackage{tikz}
\begin{document}


\begin{tabular}{l m{2cm} p{2cm}}
\tikz[overlay]\draw[red](0,0)--++(6cm,0cm);%
baseline of the row & short text\newline short text & longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext, longtext \\
\end{tabular}


\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/111470446-27235280-8728-11eb-93fb-e2a5d9f6e9d3.png)

**Comment by hvoss49** [comment]
> Am 17.03.2021 um 13:33 schrieb zahlenzauber ***@***.***>:
> 
> \begin{tabular}{m{2cm} p{2cm}}

Compare it with 

\begin{tabular}{p{2cm} m{2cm}}

Herbert

**Comment by zahlenzauber** [comment]
Thank you for the explanation and the hint. Obviously, I have a misconception of how it should work. I should read a little more about it. Please excuse me for taking up your time before doing so.
Best whishes 
Thomas
