### ISSUE TITLE
Avoid using exclusionary language in the syntax and documentation such as  ``\newcommand`` and ``command``

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#537]
Recently the ``master`` branch was renamed to ``main`` branch.

Sadly, LaTeX2e uses exclusionary language such as its concept of a "command".

I propose a transition be organized to more inclusive LaTeX2e.

**Comment by davidcarlisle** [comment]
I assume this is not a serious propsal to change the syntax of the language. There is also no possible objection to the use of the english word "command".

**Comment by jfbu** [comment]
> I assume this is not a serious proposal to change the syntax of the language. There is also no possible objection to the use of the English word "command".
> 
> 

I am very serious. As I don't like being commanded, I do see a quite clear objection to the usage of this term which is related to a master-servant relation.

**Comment by FrankMittelbach** [comment]
> I am very serious. As I don't like being commanded, I do see a quite clear objection to the usage of this term which is related to a master-servant relation.

but it is not you that is commanded it is the engine. Anyway sometimes things (or even people) need to be commanded. My guess is you would also object to the engine not producing a chapter when you write \chapter because it is Tuesday or because the engine doesn't feel like obeying you.
