### ISSUE TITLE
Stream allocation needs to 'allow' for being loaded early

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#538]
In `expl3` we use a pool of read/write streams. That works fine when loaded after the kernel has initialised, but with the move to pre-loading `expl3`, we are ending up changing the read/write numbers used by the format. This is likely sub-optimal. We just have to work out exactly how we want to change the setup of `\g_@@_streams_prop` for both `ior` and `iow`. 

(Comes up via https://tex.stackexchange.com/questions/588811/verbatim-overlays-of-powerdot-do-not-comply-with-
texlive-2020-latex-whereas-eve, although that is not directly our fault)

**Comment by FrankMittelbach** [comment]
It is not really a bug but the underlying allocation number has been 0 for such a long time that we will make sure it stays there --- though some some of the usage, eg in powerdot ,should change nevertheless.

**Comment by u-fischer** [comment]
It looks as if powerdot has been already adapted: https://www.freelists.org/post/powerdot/Bug-report,50
