### ISSUE TITLE
\\ variants in tables are not robust

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#548]
## Brief outline of the bug

We announced that we make most document level commands robust one way or the other. This is the case for `\\` most of the time but not in some cases where it is redefined (for example in tabulars).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{document}
\makeatletter
\protected@edef\@tempa{\begin{tabular}{c}a\\b\end{tabular}}\show\@tempa
\begin{tabular}{c}
\protected@edef\@tempa{\begin{tabular}{c}a\\b\end{tabular}}\show\@tempa
\end{tabular} 
\end{document}
```

## Log file (required) and possibly PDF file  

This gives
```
> \@tempa=macro:
->\protect \begin  {tabular}{c}a\\b\protect \end  {tabular}.
l.4 ...n{tabular}{c}a\\b\end{tabular}}\show\@tempa
                                                  
? 
./Untitled-2.tex:6: Argument of \@firstoftwo has an extra }.
<inserted text> 
                \par 
l.6 \protected@edef\@tempa{\begin{tabular}{c}a\\
                                                b\end{tabular}}\show\@tempa
```

**Comment by FrankMittelbach** [comment]
no way to test while travis is broken but locally this looks ok. All done except longtable and getting the praise by finishing the ltnews entry .. for one or both I assign you @davidcarlisle  :-)

**Comment by car222222** [comment]
Not sure what you mean by "all done" here?  
Where are the fixes?  
Did you fix only tabularcr or "all the non-normal uses of \\"?

**Comment by FrankMittelbach** [comment]
pull request #551: yes all different uses not just @tabularcr
