### ISSUE TITLE
Using  `bm` and `hyperref` together leads to `TeX capacity exceeded, sorry [input stack size=500]`.

### ISSUE THREAD

**Issue by Romeoly** [latex3/latex2e#55]
## Brief outline of the bug
`\usepackage`ing `bm` and `hyperref` leads to `TeX capacity exceeded, sorry [input stack size=500]`.

If I remove either `bm` or `hyperref`, the problem won't appear. Following the instructions of `bm`, I post an issue here. I don't if it is better to report this problem to  Heiko Oberdiek the autor of `hyperref`. 

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{amsmath}
\usepackage[colorlinks]{hyperref}
\usepackage{bm}
\begin{document}
\section{First derivative of $\boldsymbol{\beta}_{ij}$}
\end{document}
```

## Log file (required) and possibly PDF file  

[min.log](https://github.com/latex3/latex2e/files/2153627/min.log)

**Comment by sony976837769** [comment]
[[反璞歸真為真如 砱崆御枵麮驉無 陰陽日月為乾坤 天地遨遊趣楈錓]]
反璞歸真 黃 保欽親筆瀛題

**Comment by eg9** [comment]
I wouldn't say this is a LaTeX bug: math in titles is often problematic when PDF bookmarks are involved and `hyperref` itself has techniques for this. In your case you can choose between
```latex
\section{First derivative of \texorpdfstring{$\bm{\beta}_{ij}$}{b\_ij}}
```
or doing
```latex
\makeatletter
\pdfstringdefDisableCommands{\let\bm\@firstofone}
\makeatother
```
in the preamble with
```latex
\section{First derivative of $\bm{\beta}_{ij}$}
```
The latter method will still issue warnings.

**Comment by Romeoly** [comment]
@eg9 Thank you so much for you help. Your comment is very helpful. I agree with you that this is not a bug. In anyway if it is a bug, it is a bug of the `hyperref` package.  I couldn't find an approach to report this problem to the `hyperref` team, so I posted it here. 

Thank you again for your reading.

**Comment by FrankMittelbach** [comment]
Am 02.07.2018 um 13:47 schrieb Romeoly:
> In anyway if it is a bug, it is a bug of the |hyperref| package. I 
> couldn't find an approach to report this problem to the |hyperref| team, 
> so I posted it here.

This is why we ask everybody to include

\RequirePackage{latexbug}

in the bug report (which you did). What you missed however, is that this 
stopped with the following error message (look at the log you included):

```
! Package latexbug Error: Third-party file(s)
(latexbug)
(latexbug)                This test file uses third-party file(s)
(latexbug)
(latexbug)                ==============
(latexbug)                hyperref.sty  ->  Heiko Oberdiek
(latexbug)                    https://github.com/ho-tex/hyperref/issues
(latexbug)                ==============
(latexbug)
(latexbug)                So you should contact the authors
(latexbug)                of these files, not the LaTeX Team!
(latexbug)                (Or remove the packages that load
(latexbug)                them, if they are not necessary to
(latexbug)                exhibit the problem).
(latexbug)
(latexbug)                If you think the bug is in core LaTeX
(latexbug)                (as maintained by the LaTeX Team) but
(latexbug)                these files are needed to demonstrate
(latexbug)                the problem, please continue and mention
(latexbug)                this explicitly in your bug report.

See the latexbug package documentation for explanation.
Type  H <return>  for immediate help.
  ...
```

and that does in fact tells you where to report a bug in hyperref and 
that one should remove third-party packages before reporting a bug here

cheers - frank

**Comment by Romeoly** [comment]
@FrankMittelbach Thank you so much for your instruction. I've learnt a lot today.
