### ISSUE TITLE
Accented ae ligature with LuaLaTeX

### ISSUE THREAD

**Issue by wehro** [latex3/latex2e#552]
## Brief outline of the bug
`\'æ` and `\'\ae` look different from `ǽ` with LuaLaTeX (the acute accent is slightly moved to the right), but they should look the same (as they do with XeLaTeX).
![accents](https://user-images.githubusercontent.com/33468411/115574810-3fa40100-a2c2-11eb-8b1b-2ddc19d2794d.png)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
\'æ

\'\ae

ǽ
\end{document}
```

## Log file (required) and possibly PDF file  

[Kurztest.log](https://github.com/latex3/latex2e/files/6351807/Kurztest.log)

**Comment by FrankMittelbach** [comment]
can you take a look @zauguin ?

**Comment by zauguin** [comment]
This is a combination of Latin Modern not handling combining characters nicely and LaTeX not knowing about the precomposed character. We could fix for now by adding
```
\DeclareUnicodeComposite{\'}{\ae}{"01FD}
\DeclareUnicodeComposite{\'}{æ}{"01FD}
```
(and the uppercase variants) but in the longer term we should probably look for a more general solution. Either by doing some semi-normalization in luaotfload, by consistently declaring all Unicode precomposed characters (or at least the one present in Latin Modern) or some other approach.

I noticed that we need both lines to support both `\'\ae` and `\'æ` and I am wondering if we could avoid that which is already leading to issues (The existing `\=\ae` is only declared for `\ae`, not for `æ`. So `\=æ` doesn't work). @davidcarlisle Would it be possible to adapt the mechanism such that we don't have to duplicate lines like these?

**Comment by FrankMittelbach** [comment]
There is also the problem that the accent commands do not work in pdfTeX unless you put braces around the unicode character, e.g.,  `\'æ` dies there but `\'{æ}`. While that is not really surprising, it is surprising for the general public.

**Comment by jbezos** [comment]
With `uninormalize` it works.

**Comment by davidcarlisle** [comment]
> 
> 
> There is also the problem that the accent commands do not work in pdfTeX unless you put braces around the unicode character, e.g., `\'æ` dies there but `\'{æ}`. While that is not really surprising, it is surprising for the general public.

that one we could probably fix in general along the lines of:

     if argument is \UTFviii@three@octets  grab the next three bytes and do the right thing....

**Comment by FrankMittelbach** [comment]
> that one we could probably fix in general along the lines of:
> 
> ```
>  if argument is \UTFviii@three@octets  grab the next three bytes and do the right thing....
> ```

possibly, that was my thinking too, but it will be a bit painful :-) but probably worth doing, should get its own issue though.

**Comment by zauguin** [comment]
With 1766cb2767422bdc8c3952fadafecc8702a08ec2 the primary issue is fixed in develop.

**Comment by FrankMittelbach** [comment]
ok, the remaining stuff is then for fall release
