### ISSUE TITLE
longtable should write to \ext@table instead of "lot"

### ISSUE THREAD

**Issue by komascript** [latex3/latex2e#561]
## Brief outline of the enhancement

Package `longtable` always writes to `lot`-file independent of what has been setup as `\ext@table`. It would be useful if `longtable` would use `\ext@table` like the standard classes (and most alternative classes) that use the kernel `float` environment.

The main reason for this feature request is, that usage of `\ext@table` would allow very easy switch to another auxiliary file, i.e., in the appendix. With current implementation either `longtable` or `\addcontentsline` (or `\addtocontents`) has to be patched, but patching internals should be avoided.

## Minimal example showing the current behaviour

Note, the following code is a simplification of what I often have shown users, that need such different list of tables/figures in the appendix.

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{longtable}

\begin{document}
\listoftables

\begin{table}
  \caption{Float table in the main part}
\end{table}

\begin{longtable}{l}
  \caption{Long table in the main part}\\
\end{longtable}
 
\appendix
\makeatletter
\def\ext@table{alot}
\section*{Tables in the Appendix}
\@starttoc{alot}
\makeatother

\begin{table}
  \caption{Float table in the appendix}
\end{table}

\begin{longtable}{l}
  \caption{Long table in the appendix}\\
\end{longtable}

\end{document}
```

In this example the entry `Long table in the appendix` should be in the `Tables in the Appendix` but is in the main `List of Tables`

## Minimal example showing the desired new behaviour

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{longtable}

\makeatletter
\def\LT@c@ption#1[#2]#3{%
  \LT@makecaption#1\fnum@table{#3}%
  \def\@tempa{#2}%
  \ifx\@tempa\@empty\else
     {\let\\\space
     \addcontentsline{\ext@table}{table}{\protect\numberline{\thetable}{#2}}}% CHANGED
  \fi}
\makeatother

\begin{document}
\listoftables

\begin{table}
  \caption{Float table in the main part}
\end{table}

\begin{longtable}{l}
  \caption{Long table in the main part}\\
\end{longtable}
 
\appendix
\makeatletter
\def\ext@table{alot}
\section*{Tables in the Appendix}
\@starttoc{alot}
\makeatother

\begin{table}
  \caption{Float table in the appendix}
\end{table}

\begin{longtable}{l}
  \caption{Long table in the appendix}\\
\end{longtable}
  
\end{document}
```

`\ext@table` is part of the `float` interface. So it is only internal for users but not package authors and changing one `lot` into `\ext@table` in `longtable.sty` would allow to avoid patches of real internals.

**Comment by FrankMittelbach** [comment]
Makes sense to me; pity it came just a few days after we shipped final -dev, but this is probably harmless enough that we could sneak this into the main release without -dev testing. @davidcarlisle ?

**Comment by davidcarlisle** [comment]
@FrankMittelbach  yes I will add this.

longtable v5 trials actually go further and allowed `table` to be changed so you could use `longtable` infrastructure for tabular-arranged figures or algorithms or whatever. But there were some issues there so not pulling that in to 4.x (I think) I'd say using  `\ext@table`  not `lot` seems like a bug fix not a feature request, so I'd say it should go in now.
