### ISSUE TITLE
Unexpected extra row when including part of a table with \input command

### ISSUE THREAD

**Issue by taroxd** [latex3/latex2e#567]
## Brief outline of the bug

When using \input to include part of a table, one more row than expected is produced in the table. The output is correct for texlive 2020, but wrong since texlive 2021.

## Minimal example showing the bug

a.tex (the main file):
```latex
%%% a.tex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}

%%% The expected behaviour
\begin{tabular}{c|c}
\hline
bug & bug \\ \hline
bug & bug \\ \hline
\end{tabular}

%%% buggy behaviour
\begin{tabular}{c|c}
\hline
\input{b.tex}
\end{tabular}

\end{document}
```

b.tex (the included file)
```latex
bug & bug \\ \hline
bug & bug \\ \hline
```
## Log file (required) and possibly PDF file  
[a.pdf](https://github.com/latex3/latex2e/files/6526083/a.pdf)
[a.log](https://github.com/latex3/latex2e/files/6526084/a.log)

**Comment by PhelypeOleinik** [comment]
This is related issue #514 (basically the same problem and solution). We are still figuring out the best way to solve this issue.  Meanwhile you can:

 - use the primitive syntax `\input "b.tex"`,
 - replace `\input` by `\expandableinput` defined with:
    ```latex
    \ExplSyntaxOn
    \cs_new:Npn \expandableinput #1
      { \use:c { @@input } { \file_full_name:n {#1} } }
    \ExplSyntaxOff
    ```
 - or if you don't want manual intervention in your tables, then you can use:
    ```latex
    \ExplSyntaxOn
    \cs_new:Npn \expandableinput #1
      { \use:c { @@input } { \file_full_name:n {#1} } }
    \ExplSyntaxOff
    \let\LTXinput\input
    \AddToHook{env/tabular/before}{\let\input\expandableinput}
    \AddToHook{env/tabular/after}{\let\input\LTXinput}
    ```
    which should make `\input` behave like `\expandableinput` inside a `tabular` environment (you might need to replicate the final two lines for other environments like `tabularx`, for example).

**Comment by Skillmon** [comment]
The primitive syntax doesn't always work correctly in tables though, depending on what the sub-file contains, because the test for that isn't expandable itself, so if the input table body starts with `\hline`, `\multicolumn` or similar commands this will fail. So I'd go for the `\expandableinput` mechanism. The following adds to it an error detection for files not found, and some basic support for the primitive `"` syntax.

```tex
\ExplSyntaxOn
\cs_new:Npn \__expandableinput_input:n #1
  {
    \exp_args:Ne \__expandableinput_input:nn
      { \file_full_name:n {#1} }
      {#1}
  }
\cs_new:Npx \__expandableinput_input:nn #1#2
  {
    \exp_not:N \tl_if_empty:nTF {#1}
      { \exp_not:N \msg_expandable_error:nnn { einput } { not-found } {#2} }
      { \exp_not:c { @@input } {#1} }
  }
\msg_new:nnn { einput } { not-found } { File~ #1~ not~ found. }
\cs_new:Npn \__expandableinput_input:w #1 " { \__expandableinput_input:n {#1} }
\cs_new:Npn \expandableinput #1
  {
    \str_if_eq:nnTF {#1} {"}
      \__expandableinput_input:w
      { \__expandableinput_input:n {#1} }
  }
\ExplSyntaxOff
```

**Comment by PhelypeOleinik** [comment]
@Skillmon Yes, sorry, I should've mentioned that `\input <file>` will work but only in a handful of cases.  Thanks for the enhanced version!

@taroxd You can use Skillmon's code above plus the three lines:
```latex
\let\LTXinput\input
\AddToHook{env/tabular/before}{\let\input\expandableinput}
\AddToHook{env/tabular/after}{\let\input\LTXinput}
```
to have a semi-automatic solution for now.

**Comment by FrankMittelbach** [comment]
I'll close as a duplcate of #514
