### ISSUE TITLE
\NewDocumentEnvironment overwrites existing commands

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#570]
## Brief outline of the bug

In contrast to `\newenvironment` the declaration `\NewDocumentEnvironment` is not checking for existing `\end...` commands ...

(aside: the error message should be consolidated between the two type of declarations)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\show\endgraf

\NewDocumentEnvironment{graf}{}{}{Wrong}

\show\endgraf
```

## Log file (required) and possibly PDF file  

```
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-05-11>
> \endgraf=\par.
l.2 \show\endgraf
                 
? 
> \endgraf=macro:
->\environment graf end aux .
l.6 \show\endgraf
                 
? 
```

**Comment by u-fischer** [comment]
Additionally: `\NewDocumentCommand` doesn't check either for `\end`:

~~~~
\documentclass{article}

\begin{document}
\newcommand\endyyy{}{abc} %error
\NewDocumentCommand\endzzz{}{abc}

\end{document}
~~~~

**Comment by josephwright** [comment]
I think one should remember here that `xparse` was written when the plan was to have a new format, and so linking environments to document command names is done after defining 'proper' implementation names (which contain spaces so are hard to get at). Of course, things have changed. I see @u-fischer has mentioned `\endfoo`, which I _really_ feel we should leave alone: if I want to implement `\endo` (used for chemistry), for example, as a user I don't feel I should have to use `\def`. On environments, I guess we could check both `\foo` and `\endfoo` for `\NewDocumentEnvironment`/`\RenewDocumentEnvironment` and require both to be 'correct'. The only wrinkle is that as LaTeX allows `\begin{foo}` one formally doesn't need `\endfoo` to be defined for something to be a valid environment.

**Comment by FrankMittelbach** [comment]
I also think that `\newcommand` does some overspecification here. There is no need to disallow defining `\endfoo` if defining an environment checks that both `\foo` and `\endfoo` are free. I would rather think `\newcommand` should not do this instead of disallowing it also with `\NewDocumentCommand`.

**Comment by u-fischer** [comment]
> I would rather think `\newcommand` should not do this instead of disallowing it also with `\NewDocumentCommand`.

Would be fine with me, I think it is odd if both have different behaviour and the test for \endfoo is certainly better in the environment commands.

**Comment by blefloch** [comment]
Related to this issue, but slightly to the side: I think there was at some point the hope of decoupling environments from commands so that `\foo` and `\begin{foo}` could have independent meanings.

It might be possible to work something out by having `\begin{foo}` and `\end{foo}` run `\environment foo` and `\environment foo end aux` (xparse names if I read the code right) if they are defined, and otherwise run `\foo` and `\endfoo` as a fall-back.  This would make `\foo` and `\endfoo` available as commands.  I haven't thought through all the consequences.

**Comment by josephwright** [comment]
@blefloch Pretty good idea: would mean you can say 'environment `foo` *can only be used* via the official interface', but leave existing docs, etc., working with `\begin{centering}` or whatever.

**Comment by u-fischer** [comment]
What about code that have to uses internally  things like  `\align ... endalign` and `\tabularx ... \endtabularx`?

**Comment by FrankMittelbach** [comment]
@josephwright @blefloch I think this is a long term idea at best. There is too much code out there that would break, starting from  a few packages that do try to actually implement that already to the issue mentioned by @u-fischer that it is currently a documented interface to use environment code without `\begin`and `\end`.

**Comment by josephwright** [comment]
@u-fischer With @blefloch's proposal, they still work, it's things defined using `ltcmd` that don't. I really hope there are not loads of *new* packages using the internal `\foo` ... `\endfoo` (and I'm not sure it works properly for anything defined using `ltcmd`).

**Comment by josephwright** [comment]
@FrankMittelbach  Bruno's plan won't leave anything defined in 'classical' terms working, no? So it's only people who are already using new-ish code, and where we might well expect to be able to update (or if necessary first-aid).

**Comment by FrankMittelbach** [comment]
What I'm saying is that `\foo ... \endfoo` is documented all over the place as a workable solution.

If `\NewDocumentEnvironment` would stop defining those commands you end up with two classes of envs: one for which this method works and one for which it doesn't, and which is which is not clearl from the outside.

Furthermore it would mean that we can't move envrionments in the kernel and in packages to use `\NewDocumentEnvironment` because that would mean they would suddenly change semantics. And the latter is a must, ie to get rid of low-level argument parsing as done by minipage lists etc etc

**Comment by josephwright** [comment]
Possibly a 'softer' approach: do as @blefloch suggests and have `\begin` check first for `\environment foo`, and use that if available. That would allow something like
```
\NewDocumentEnvironment{foo}{}{}{}
\RenewDocumentCommand\foo{}{}
```
such that `\begin{foo}...\end{foo}` is independent of `\foo` *but* this is an explicit opt-in.

**Comment by blefloch** [comment]
There still needs to be a way to cover Ulrike's use case: the problem with using \begin{inner}...\end{inner} inside the definition of an "outside" environment is that error recovery is wrong:
```
\newenvironment{inner}{}{}
\newenvironment{outside}{\begin{inner}}{\end{inner}}
\begin{outside}\end{inner}
% Wrongly works, but with an extra group not being closed
\begin{outside}\end{list}
% ! LaTeX Error: \begin{inner} on input line 4 ended by \end{list}.
```
I think in the past I suggested `\begin*{inner}` and `\end*{inner}` for variants to be used inside another environment's definition.  These variants would record somehow that closing with `\end{inner}` is wrong but `\end{outside}` is right.  E.g. add a new `\@currenvir@doc` variable that keeps track of the currenvir as seen by the document author.  The other advantage is that `\begin*{inner}...\end*{inner}` could still make a group, which is necessary for some environments to work correctly.

Probably the whole discussion should be moved to some other issue, sorry.

**Comment by josephwright** [comment]
Agreed to follow 2e behaviour here.

**Comment by FrankMittelbach** [comment]
only one: I think it is ok without `\IncludeInRelease` but there should be a short ltnews34 entry as well perhaps.

**Comment by josephwright** [comment]
@FrankMittelbach News entry added
