### ISSUE TITLE
With Lua-dev no toc!

### ISSUE THREAD

**Issue by Keks-Dose** [latex3/latex2e#572]
## Brief outline of the bug

Sorry, I'm under time pressure, I can't provide an MWE. 

texlive, up-to-date. Article has about 25 pages. Issue: with lualatex-dev no table of contents is produced, except for the heading. All works well when compiling with LuaLaTex, meaning, not the -dev variant. Happens independently from the OS as well under Win 8.1 as under openSuse Tumbleweed. 

I changed the file name in the logfile lines below. 

## Log file (required) and possibly PDF file  

Running `LaTeX' on `210526-Pfpf-V5' with ``lualatex-dev  -file-line-error   --synctex=1 -interaction=nonstopmode "210526-Pfpf-V5.tex"''
This is LuaHBTeX, Version 1.13.2 (TeX Live 2021/W32TeX) 
 restricted system commands enabled.
(./210526-Pfpf-V5.tex
LaTeX2e <2021-06-01> pre-release-3 (develop 2021-5-27 branch)
 L3 programming layer <2021-05-25>
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrartcl.cls
Document Class: scrartcl 2021/03/17 v3.33 KOMA-Script document class (article)

**Comment by u-fischer** [comment]
oh come on, give us a chance. If table of contents were generally broken we would have noticed. Either show a complete example or sent me something directly.

**Comment by Keks-Dose** [comment]
> 
> 
> oh come on, give us a chance. If table of contents were generally broken we would have noticed. Either show a complete example or sent me something directly.

Yes, sorry, will do, but may take until weekend.

**Comment by Keks-Dose** [comment]
## MWE
\documentclass[pagesize, ngerman, fontsize=12pt, parskip=half, juratotoc=true,]{scrartcl}
\usepackage{fontspec}
\setmainfont{Linux Libertine O}
\setsansfont{Linux Biolinum O}
\usepackage{babel, scrjura, xspace, fewerfloatpages, geometry}
\geometry{bottom=4cm, right=4.5cm, top=3cm, left=4cm}

\title{dingens}
\begin{document}
\maketitle{}

\tableofcontents{}

\begin{contract}
\Clause{title=erstens}
\label{CLA:title=erstens}

Text und nochwas whatever.

\Clause{title=segundo}

Yes.

and no.

\end{contract}


\end{document}

% Local Variables:
% TeX-engine: Lua-dev
% End:

## Log

Running `LaTeX' on `210527-Lua-dev-bug' with ``lualatex-dev  -file-line-error   --synctex=1 -interaction=nonstopmode "210527-Lua-dev-bug.tex"''
This is LuaHBTeX, Version 1.13.2 (TeX Live 2021/W32TeX) 
 restricted system commands enabled.
(./210527-Lua-dev-bug.tex
LaTeX2e <2021-06-01> pre-release-3 (develop 2021-5-27 branch)
 L3 programming layer <2021-05-25>
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrartcl.cls
Document Class: scrartcl 2021/03/17 v3.33 KOMA-Script document class (article)
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrkbase.sty
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrbase.sty
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrlfile.sty
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrlogo.sty)))
(c:/texlive/2021/texmf-dist/tex/latex-dev/graphics/keyval.sty)))
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/tocbasic.sty)
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrsize12pt.clo)
(c:/texlive/2021/texmf-dist/tex/latex/koma-script/typearea.sty))
(c:/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.sty
(c:/texlive/2021/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(c:/texlive/2021/texmf-dist/tex/latex/l3kernel/expl3.sty
(c:/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-luatex.def)))
(c:/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
(c:/texlive/2021/texmf-dist/tex/latex-dev/base/fontenc.sty)
(c:/texlive/2021/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(c:/texlive/2021/texmf-dist/tex/generic/babel/babel.sty
(c:/texlive/2021/texmf-dist/tex/generic/babel/babel.def
(c:/texlive/2021/texmf-dist/tex/generic/babel/luababel.def)
(c:/texlive/2021/texmf-dist/tex/generic/babel/luababel.def))
(c:/texlive/2021/texmf-dist/tex/generic/babel-german/ngerman.ldf
(c:/texlive/2021/texmf-dist/tex/generic/babel-german/ngermanb.ldf
(c:/texlive/2021/texmf-dist/tex/generic/hyph-utf8/loadhyph/loadhyph-de-1996.texUTF-8 German hyphenation patterns (reformed orthography)
(c:/texlive/2021/texmf-dist/tex/generic/hyph-utf8/patterns/tex/hyph-de-1996.tex

German Hyphenation Patterns (Reformed Orthography, 2006) `dehyphn-x' 2021-02-26 (WL)))))) (c:/texlive/2021/texmf-dist/tex/latex/koma-script/scrjura.sty)
(c:/texlive/2021/texmf-dist/tex/latex-dev/tools/xspace.sty)
(c:/texlive/2021/texmf-dist/tex/latex/fewerfloatpages/fewerfloatpages.sty)
(c:/texlive/2021/texmf-dist/tex/latex/geometry/geometry.sty
(c:/texlive/2021/texmf-dist/tex/generic/iftex/ifvtex.sty
(c:/texlive/2021/texmf-dist/tex/generic/iftex/iftex.sty)))
(./210527-Lua-dev-bug.aux)
(c:/texlive/2021/texmf-dist/tex/latex-dev/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: luatex

LaTeX Warning: No \author given.

(./210527-Lua-dev-bug.toc)
Stored max is 1
Stored max is 2
Stored max is 2
[1{c:/texlive/2021/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./210527-Lua-dev-bug.aux))
 469 words of node memory still in use:
   4 hlist, 1 vlist, 1 rule, 5 glue, 3 kern, 1 glyph, 7 attribute, 53 glue_spec, 5 attribute_list, 1 write nodes
   avail lists: 1:1,2:229,3:74,4:2,5:38,6:18,7:420,8:1,9:66,10:1,11:22
<c:/Windows/Fonts/LinLibertine_Re-2.6.9.otf><c:/texlive/2021/texmf-dist/fonts/opentype/public/libertine/LinBiolinum_RB.otf>
Output written on 210527-Lua-dev-bug.pdf (1 page, 10374 bytes).

SyncTeX written on 210527-Lua-dev-bug.synctex.gz.
Transcript written on 210527-Lua-dev-bug.log.

TeX Output finished at Thu May 27 19:52:26

**Comment by Keks-Dose** [comment]
> 
> 
> oh come on, give us a chance. If table of contents were generally broken we would have noticed. Either show a complete example or sent me something directly.

Done, but not absolutely minimal.

**Comment by u-fischer** [comment]
Remove the spaces in the document option

    \documentclass[pagesize,ngerman,fontsize=12pt,parskip=half,juratotoc=true,]{scrartcl}

and report it to KOMA.

Btw: scrjura patches \document, that should perhaps be changed too

~~~~
\DeclareOption{contract}{%
  \g@addto@macro\document\contract%
}
~~~~

**Comment by Keks-Dose** [comment]
> 
> 
> Remove the spaces in the document option
> 
> ```
> \documentclass[pagesize,ngerman,fontsize=12pt,parskip=half,juratotoc=true,]{scrartcl}
> ```
> 
> and report it to KOMA.
> 
> Btw: scrjura patches \document, that should perhaps be changed too
> 
> ```
> \DeclareOption{contract}{%
>   \g@addto@macro\document\contract%
> }
> ```

Will do that. Thank you!

**Comment by u-fischer** [comment]
Hm, I'm not sure if the spaces are the problem, babel seem to interfere. Loading babel after scrjura could help too.

**Comment by u-fischer** [comment]
Well it is in part a babel problem as it define `\ds@<option>`. 

But it leads now to an error as KOMA has changed the option handling, and the defined command changes the option handling:

~~~~
\documentclass[juratotoc=true]{scrartcl}
\makeatletter\@namedef{ds@juratotoc=true}{}\makeatother
\usepackage{scrjura}
\show\cpartocdepth %2 in latex, 1073741823. in latex-dev
~~~~

**Comment by komascript** [comment]
If `\ds@<option>` is defined, `scrbase` interprets it a a classic option, defined using `\DeclareOption` instead of a key-value option. This is, because classic options are prioritised.

BTW: LaTeX kernel also uses

```latex
\@ifundefined{ds@\CurrentOption}%
```

to decide whether or not an option is defined and has been used inside the package.

IMO `babel` should not define `\ds@option` permanently. If it defines `\ds@option` it should make sure, that it is undefined (or at least `\relax`) after end of loading `babel`.

**Comment by u-fischer** [comment]
> IMO babel should not define \ds@option permanently. 

Yes, this already came up. I actually commented here in march again: https://github.com/latex3/babel/issues/110

I think a proper babel issue should be opened here.

**Comment by jbezos** [comment]
Fixed in [962154](https://github.com/latex3/babel/commit/f962154a8f88e44211fb2a3f57019958d97fe8e4). The toc is being created again.
