### ISSUE TITLE
Error with \RequirePackageWithOptions with rollback

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#577]
## Brief outline of the bug

With \RequirePackageWithOptions, rollback from 2021/06/01 to 2020/10/01 causes an error:

```
Runaway argument?
\@empty \@expl@pop@filename@@ \@reset@ptions \relax \stop 
! File ended while scanning use of \@p@pfilepath@aux.
<inserted text> 
                \par 
```

This is found when I am developing `platexrelease` package: current public `platexrelease` package stops with another error due to our mistake, but even after [removing that error](https://github.com/texjporg/platex/commit/c0098ad4b3e2a49551340a93cc57b41ca5e9d445) it stops with the above "runaway" error. (Note that `platexrelease` loads `latexrelease` with `\RequirePackageWithOptions`)

``` tex
\RequirePackage[2020/10/01]{platexrelease}
\stop
```

## Minimal example showing the bug

Using pdflatex:

```latex
\RequirePackage{latexbug}

\begin{filecontents*}[overwrite]{\jobname.sty}
\RequirePackageWithOptions{latexrelease}
\end{filecontents*}

\documentclass{book}
\usepackage[2020/10/01]{\jobname}
\stop
```

## Log file (required) and possibly PDF file  

* [20210603-ltxrel-runaway.log](https://github.com/latex3/latex2e/files/6592766/20210603-ltxrel-runaway.log)

**Comment by PhelypeOleinik** [comment]
Hm... I was pretty sure I took the case of `platexrelease` into account (loading `latexrelease` from within another package), but alas... This is some stack that went empty due to rollback then exiting two files. Thanks for the report!

**Comment by PhelypeOleinik** [comment]
Should be fixed with the next patch release. Meanwhile, if you need, you can save the stack manually by using the package hooks around `latexrelease`:

```latex
\begin{filecontents*}[overwrite]{\jobname.sty}
\RequirePackageWithOptions{latexrelease}
\end{filecontents*}

\makeatletter
\AddToHook{package/before/latexrelease}{\let\saved@pathstack\@kernel@currpathstack}
\AddToHook{package/after/latexrelease}{\let\@kernel@currpathstack\saved@pathstack}
\makeatother

\RequirePackage[2020-10-01]{\jobname}

\stop
```

**Comment by FrankMittelbach** [comment]
@aminophen Hironobu would the workaround be good for now? Because if that is the only issue that comes up I would rather not put out a hotfix for it.

**Comment by aminophen** [comment]
@FrankMittelbach OK for now; I will install it into our next platex as a workaround until it is fixed. Thanks @PhelypeOleinik

**Comment by FrankMittelbach** [comment]
@aminophen ok good, thanks. So we'll wait if anything else shows up.

**Comment by FrankMittelbach** [comment]
close only when on CTAN

**Comment by PhelypeOleinik** [comment]
Closing: on [CTAN since 2021-06-16](https://ctan.org/ctan-ann/id/mailman.775.1623855706.2581.ctan-ann@ctan.org)
