### ISSUE TITLE
\sffamily after \fontseriesforce + \selectfont

### ISSUE THREAD

**Issue by aminophen** [latex3/latex2e#579]
## Brief outline of the bug

The behavior of `\sffamily` changed after `\fontseriesforce{something}\selectfont`, between 2020-10-01 and 2021-06-01. Maybe related to #444 but I don't know whether this is an intended change.

## Minimal example showing the bug

``` latex
%#!pdflatex
\RequirePackage{latexbug}
%\RequirePackage[2020/10/01]{latexrelease}
\documentclass{article}
\makeatletter
\DeclareFontFamily{OT1}{hoge}{}
\DeclareFontShape {OT1}{hoge}{m} {n}{<-> s*cmff10}{}
\DeclareFontShape {OT1}{hoge}{ub}{n}{<-> s*cmsl10}{}
\DeclareFontFamily{OT1}{fuga}{}
\DeclareFontShape {OT1}{fuga}{m} {n}{<-> s*cmfi10}{}
\DeclareFontShape {OT1}{fuga}{sb}{n}{<-> s*cmbxsl10}{}

\def\rmdefault{hoge}\def\sfdefault{fuga}
\def\bfseries@rm{ub}\def\bfseries@sf{sb}
\def\test#1{%
  \par\begingroup#1%
    \xdef\status@af{\f@family/\f@series/\f@shape}%
  123\space\endgroup%
  (\texttt{\status@af})
}
\begin{document}

\test{}
% => hoge/m/n

\test{\fontseries{ub}\selectfont\sffamily}
% => fuga/sb/n

\test{\fontseriesforce{ub}\selectfont\sffamily}
% => changed!
%  * 2020-10-01: fuga/ub/n (fallback -> fuga/m/n)
%  * 2021-06-01: fuga/sb/n

\end{document}
```

## Log file (required) and possibly PDF file  

* TL2020 frozen (LaTeX2e 2020-10-01 patch level 4): [series-tl2020.log](https://github.com/latex3/latex2e/files/6599085/series-tl2020.log)
* Latest (LaTeX2e 2021-06-01): [series-20210601.log](https://github.com/latex3/latex2e/files/6599086/series-20210601.log)

**Comment by user227621** [comment]
I think that this happens because the "force state" is now reset after every `\selectfont`. [See here:](https://github.com/latex3/latex2e/issues/444#issuecomment-826995742)

> the force should always be reset by \selectfont not by the next \fontseries

This change was made because not resetting the "forced state" could lead to strange effects: [See Issue 3 in this comment.](https://github.com/latex3/latex2e/issues/444#issuecomment-756004419)

**Comment by aminophen** [comment]
@user227621 Thanks for the explanation; now I understand your point well.

**Comment by FrankMittelbach** [comment]
Yes this is the intended behavior and before it was wrong as the scope of the "force" was not well defined. Now it applies to the next `\selectfont`as it should.
