### ISSUE TITLE
Calc : \global assignment of lenght does not work anymore. 

### ISSUE THREAD

**Issue by maieul** [latex3/latex2e#58]
## Brief outline of the bug
Normaly, a `\global` before a `\setlength` make a global assignment.
With the calc package, it does not work anymore,

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{calc}
\begin{document}
\newlength{\toto}
\begingroup
\global\setlength{\toto}{2pt}
\endgroup
\the\toto
\end{document}



```

## Log file (required) and possibly PDF file  
[toto.log](https://github.com/latex3/latex2e/files/2195922/toto.log)
[toto.pdf](https://github.com/latex3/latex2e/files/2195923/toto.pdf)

**Comment by davidcarlisle** [comment]
sorry this is not a bug `\global` is never supported with `\setlength` although without `calc` it sort of half works by accident. With `calc` it does not work at all,
