### ISSUE TITLE
\PassOptionToClass does not expand the option argument into the raw option list

### ISSUE THREAD

**Issue by komascript** [latex3/latex2e#580]
## Brief outline of the bug

I've a [bug report](https://sourceforge.net/p/koma-script/tickets/10/) about an infinite loop in the KOMA-Script issue tracker. The reason for the issue is, that `\PassOptionToClass` uses different expansion levels for the classic option list and the raw option list.

## Minimal example showing the bug

```latex
\begin{filecontents*}[force]{testclass.cls}
\ProvidesClass{testclass}[2021/06/05 v0.0 test class]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{testclassi}}
\ProcessOptions\relax
\LoadClass{testclassi}
\endinput
\end{filecontents*}
\begin{filecontents*}[force]{testclassi.cls}
\ProvidesClass{testclassi}[2021/06/05 v0.0 internal test class]
\expandafter\show\csname @raw@opt@testclassi.cls\endcsname
\expandafter\show\csname opt@testclassi.cls\endcsname
\ProcessOptions\relax
\LoadClass{minimal}
\endinput
\end{filecontents*}
%------------------------------------------------------------
\documentclass[draft]{testclass}
\begin{document}
\end{document}
```

results in

```
> \@raw@opt@testclassi.cls=macro:
->\CurrentOption ,.
<recently read> \@raw@opt@testclassi.cls 
                                         
l.2 ...ow\csname @raw@opt@testclassi.cls\endcsname
                                                  
> \opt@testclassi.cls=macro:
->draft,.
<recently read> \opt@testclassi.cls 
                                    
l.3 ...er\show\csname opt@testclassi.cls\endcsname
```

So the raw option list and the classic options list differ here in expansion of `\CurrentOption`. The classic options list contains the expanded `\CurrentOption` → `draft`, but the raw option list contains `\CurrentOption` itself.

I don't know whether this is a bug in LaTeX or a mistake in the shown code and the class author should do the one-level expansion of `\CurrentOption` (using e.g. `\DeclareOption*{\expandafter\PassOptionsToClass\expandafter{\CurrentOption}{testclassi}}`).

**Comment by Skillmon** [comment]
I encountered the same bug a few days ago, and decided for myself that I should've expanded `\CurrentOption` for `\PassOptionsToClass`. The behaviour of not expanding `\CurrentOption` automagically in the raw option list is, imho, the correct behaviour, after all the raw option list is exactly that, raw, unprocessed options.

**Comment by davidcarlisle** [comment]
hmm, I don't think we want to always expand as that can end up with the same problem as the original lists with premature expansions, or key values. But `\PassOptionsToClass{\CurrentOption}` has been an advertised usage since the begining and `\expandafter\PassOptionsToClass\expandafter{\CurrentOption}` doesn't exactly look to be a usability improvement. I wonder if we should special case `\CurrentOption` here and expand it once.

**Comment by davidcarlisle** [comment]
something like this, but I'm not sure this is the right approach

```
\makeatletter
\def\@currentoption{\CurrentOption}%
\def\@pass@ptions#1#2#3{%
  \@expl@@@filehook@set@curr@file@@nNN
    {\@expl@@@filehook@resolve@file@subst@@w #3.#1\@nil}%
      \reserved@a\reserved@b
  \@expl@@@filehook@clear@replacement@flag@@
  \expandafter\xdef\csname opt@\reserved@a\endcsname{%
    \@ifundefined{opt@\reserved@a}\@empty
      {\csname opt@\reserved@a\endcsname,}%
    \zap@space#2 \@empty}%
  \def\reserved@c{#2}\ifx\reserved@c\@currentoption
    \let\@expafter\expandafter
   \else
    \let\@expafter\@empty
   \fi
  \expandafter\let
    \csname opt@#3.#1\expandafter\endcsname
    \csname opt@\reserved@a\endcsname
    \@ifundefined{@raw@opt@#3.#1}%
      {\expandafter\gdef\csname @raw@opt@#3.#1\expandafter\endcsname\@expafter{#2}}%
      {\expandafter\g@addto@macro\csname @raw@opt@#3.#1\expandafter\endcsname\expandafter{\@expafter,#2}}%
}
\makeatother
\begin{filecontents*}[force]{testclass.cls}
\ProvidesClass{testclass}[2021/06/05 v0.0 test class]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{testclassi}}
\ProcessOptions\relax
\LoadClass{testclassi}
\endinput
\end{filecontents*}
\begin{filecontents*}[force]{testclassi.cls}
\ProvidesClass{testclassi}[2021/06/05 v0.0 internal test class]
\expandafter\show\csname @raw@opt@testclassi.cls\endcsname
\expandafter\show\csname opt@testclassi.cls\endcsname
\ProcessOptions\relax
\LoadClass{minimal}
\endinput
\end{filecontents*}
%------------------------------------------------------------
\documentclass[draft]{testclass}
\begin{document}
\end{document}
```

**Comment by FrankMittelbach** [comment]
> hmm, I don't think we want to always expand as that can end up with the same problem as the original lists with premature expansions, or key values.

you're sure? I think it would be defensible to argue that the option list argument is expanded once (via `\expandafter`) for all commands in order to allow constructs like `\usepackage[\myoptions]{foo}` to have a chance to work properly. `\CurrentOption` seems to me to be just a special case of that.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  that might be better (and is certainly simpler)  Icertainly wasn't happy about adding special casing.

Actually though I was thinking of not expanding things like `size=\small`  or some such but perhaps I was over thinking this: if we just expand the list once only the first token is affected and that can't be  a key value anyway.

so that would be

```
\makeatletter
\def\@pass@ptions#1#2#3{%
  \@expl@@@filehook@set@curr@file@@nNN
    {\@expl@@@filehook@resolve@file@subst@@w #3.#1\@nil}%
      \reserved@a\reserved@b
  \@expl@@@filehook@clear@replacement@flag@@
  \expandafter\xdef\csname opt@\reserved@a\endcsname{%
    \@ifundefined{opt@\reserved@a}\@empty
      {\csname opt@\reserved@a\endcsname,}%
    \zap@space#2 \@empty}%
  \expandafter\let
    \csname opt@#3.#1\expandafter\endcsname
    \csname opt@\reserved@a\endcsname
    \@ifundefined{@raw@opt@#3.#1}%
      {\expandafter\gdef\csname @raw@opt@#3.#1\expandafter\endcsname\expandafter{#2}}%
      {\expandafter\g@addto@macro\csname @raw@opt@#3.#1\expandafter\endcsname\expandafter{\expandafter,#2}}%
}
\makeatother
\begin{filecontents*}[force]{testclass.cls}
\ProvidesClass{testclass}[2021/06/05 v0.0 test class]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{testclassi}}
\ProcessOptions\relax
\LoadClass{testclassi}
\endinput
\end{filecontents*}
\begin{filecontents*}[force]{testclassi.cls}
\ProvidesClass{testclassi}[2021/06/05 v0.0 internal test class]
\expandafter\show\csname @raw@opt@testclassi.cls\endcsname
\expandafter\show\csname opt@testclassi.cls\endcsname
\ProcessOptions\relax
\LoadClass{minimal}
\endinput
\end{filecontents*}
%------------------------------------------------------------
\documentclass[draft]{testclass}
\begin{document}
\end{document}
```

**Comment by FrankMittelbach** [comment]
Am 05.06.21 um 23:53 schrieb David Carlisle:
> Actually though I was thinking of not expanding things like 
> |size=\small| or some such but perhaps I was over thinking this: if we 
> just expand the list once only the first token is affected and that 
> can't be a key value anyway.

exactly, the first token is a key (that either doesn't expand) or it is 
a macro standing in for a key or a key/value list. Which is why I think 
expansion once is fine and sensible.

**Comment by davidcarlisle** [comment]
In addition to the above

https://tex.stackexchange.com/questions/600152/twocolumn-mod-option-in-a-class-doesnt-work-any-more

shows that \LoadClassWithOptions needs to short-circuit passing on the raw option list as well as the original.

```
\def\@loadwithoptions#1#2#3{%
  \expandafter\let\csname opt@#3.#1\expandafter\endcsname
       \csname opt@\@currname.\@currext\endcsname
%%% NEW
  \expandafter\let\csname @raw@opt@#3.#1\expandafter\endcsname 
       \csname @raw@opt@\@currname.\@currext\endcsname
%%% END NEW
   #2{#3}}
```

**Comment by FrankMittelbach** [comment]
This will become part of patch-level 1

**Comment by PhelypeOleinik** [comment]
Closing: on [CTAN since 2021-06-16](https://ctan.org/ctan-ann/id/mailman.775.1623855706.2581.ctan-ann@ctan.org)
