### ISSUE TITLE
Unhelpful error message LaTeX Error: \begin{foo} on input line 9 ended by \end{foo}

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#587]
## Brief outline of the bug

This is certainly a decades old feature that most every LaTeX user at least package author has encountered. Still, raising this ticket. Indeed, recently `\begin` and `\end` saw significant hook related refactoring so perhaps this could be improved as well.

```
LaTeX Error: \begin{foo} on input line 9 ended by \end{foo}.
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\newenvironment{foo}{\small}{}
\newenvironment{nokidding?}[1]{\def\myenvname{#1}\begin{#1}}{\end{\myenvname}}

\begin{document}

\begin{nokidding?}{foo}
  coucouc
\end{nokidding?}

\end{document}

```

## Log file (required) and possibly PDF file  

[latexend.log](https://github.com/latex3/latex2e/files/6662572/latexend.log)

The error goes away from adding some `\expandafter` which is not LaTeX user friendly but the main problem is the error message.

**Comment by FrankMittelbach** [comment]
That's not an error to me, at best something that can be classified as an enhancement.  And I'm not even sure it is a good enhancement because basically you do have two different specification in the begin and end which I think is not really good practice.
```
\newenvironment{nokidding?}[1]{\def\myenvname{#1}\begin{\myenvname}}{\end{\myenvname}}
```
would work and so would 
```
\NewDocumentEnvironment{nokidding?}{m}{\begin{#1}}{\end{#1}}
```
Throwing in a bunch of `\expandafter`s wouldn't really help because there are arbitrary many levels of indirection possible. What would work is to define `\@currenvir` and the test in `\@checkend` use `\edef` to evaluate, but I'm not sure that is a good idea .

**Comment by jfbu** [comment]
> \newenvironment{nokidding?}[1]{\def\myenvname{#1}\begin{\myenvname}}{\end{\myenvname}}

Indeed, I missed that, thanks. It is surprising at user level that this works but using `#1` does not!

**Comment by jfbu** [comment]
> We could, of course simply alter the error message:

The modified error message would have the merit to make it clear that `\begin` and `\end` must use the same unexpanded argument hence indirectly would make this a semi-documented feature. Looks to me as the most conservative way to address this.

**Comment by blefloch** [comment]
Ideally, whatever we do to find which hooks to run, we should do the same to detect this error.

**Comment by FrankMittelbach** [comment]
> Ideally, whatever we do to find which hooks to run, we should do the same to detect this error.

Not quite sure what you mean here @blefloch. Are there cases where the hook mgt picks up the wrong name but you don't get also the error above (whether or not it gets improved)? If so I would agree but if not I think one test that gives you the error is enough even if before or after you also end up executing the wrong hook.
