### ISSUE TITLE
\@eha advice to user includes extra spaces and it is not clear if they have to be taken into account (especially the first one)

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#588]
## Brief outline of the bug

Apologies in advance.

```
! LaTeX Error: \begin{foo} on input line 5 ended by \end{bla}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 A\begin{foo}\end{bla}
                         B
? H
Your command was ignored.
Type  I <command> <return>  to replace it with another command,
or  <return>  to continue without it.
? I X 
```

In interactive mode some errors such as here a mis-match for current environment will, if user types `H`, display the `I <command> <return>` as above, which includes two space tokens. As user I did `I<space>X<space><return>` and the first space makes it to the output if in horizontal mode (the ones at end of `I<tokens>` are removed by TeX early).

I am not paid by the number of tickets I raise... it is only out of being conscencious while I am at it. 

I do understand this is not earth-shaking importance, and is actually of nil relevance because LaTeX users who use interactive mode understand what the message means and no change is needed.

And perhaps it is obvious that `I <command> <return>` actually means `I<command><return>` or that other predefined messages use the same space separated style.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\newenvironment{foo}{}{}
\begin{document}

\ttfamily
A\begin{foo}\end{bla}B
\end{document}
```

## Log file (required) and possibly PDF file  

[testerr.log](https://github.com/latex3/latex2e/files/6663298/testerr.log)

**Comment by blefloch** [comment]
Probably some editors filter this message so it might be best to leave the spacing etc alone.

**Comment by FrankMittelbach** [comment]
I think this classifies under works as designed; this message dates back to 1984 and LaTeX 2.08 (not .09) if I remember correctly so I think the public managed well enough with it and from an visual point of view I personally would expect and prefer the spaces and would expect  `I <space> <cmd> <return>` if a space is really needed there. So I'm gonna close this.
