### ISSUE TITLE
babel: \bbl@stripslash undefined after \input bplain

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#59]
## Brief outline of the bug
\bbl@stripslash undefined when reading ngerman.sty after bplain.tex.

## Minimal example showing the bug
\input bplain
\input ngerman.sty
\end

Result:
! Undefined control sequence.
\declare@robustcommand ...\csname \bbl@stripslash
                                                  #1 \endcsname }\expandafte...
l.255 \DeclareRobustCommand{\glqq}
(followed by many more errors).

Indeed, \bbl@stripslash is not defined in this path. Maybe bplain.tex can just \input babel.def, where \bbl@stripslash is defined? I don't know, but it evidently needs to get defined somehow.

If I copy in the definition from babel.def before the \input ngerman:

\catcode`@=11 \def\bbl@stripslash{\expandafter\@gobble\string}\catcode`@=12

it goes through without error.

This was originally reported for eplain[.fmt] (https://tug.org/pipermail/tex-live/2018-July/042079.html), but per above, I don't believe it's related to eplain; it's just that eplain.ini does \input bplain.

[try.log.txt](https://github.com/latex3/latex2e/files/2258132/try.log.txt)

**Comment by jbezos** [comment]
Thanks. I've just pushed a fix.

**Comment by josephwright** [comment]
Fixed by https://github.com/latex3/latex2e/commit/e00a3d12894406eebde8487b4d13c41b7d1ce333
