### ISSUE TITLE
Afterpage throws an error with \csname if...\endcsname construction

### ISSUE THREAD

**Issue by Vidabe** [latex3/latex2e#590]
## Brief outline of the bug
Using a command created by `\newif` with `\csname/\endcsname` or `\use:c` in `\afterpage` throws some errors.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\usepackage{afterpage}
\newif\ifnew

\begin{document}

\afterpage{
  \csname ifnew\endcsname
     T
   \else 
     F
   \fi
}
  
\end{document}
```

## Log file (required) and possibly PDF file  

[lbug.log](https://github.com/latex3/latex2e/files/6677995/lbug.log)

**Comment by eg9** [comment]
I'm not sure this can be considered a bug: there are conditionals while LaTeX is supplied the argument of `\afterpage` and you're hiding `\ifnew` inside `\csname...\endcsname`, so the following `\else` and `\fi` are improperly matched.

With `expl3` you can use `\legacy_if:nTF { new } { T } { F }` which is free from the issue.

**Comment by davidcarlisle** [comment]
As @eg9 says this is arguably to be expected since you are passing in an unmatched `\fi`.  The consistent thing would be to hide the else and fi behind csname if you hide the `\ifnew` however afterpage could move `#1` out of its internal if tests so for example this probably works as you expected.

```
\documentclass{article}

\usepackage{afterpage}

\makeatletter
\long\def\afterpage#1{%
  \ifx\AP@\relax
    \gdef\AP@{}%
    \global\output{%
      \the\AP@output
      \ifnum\outputpenalty>-\@Mi
        \global\output\expandafter{\the\AP@output}%
        \aftergroup\AP@@
      \fi}%
  \fi
  \expandafter\gdef\expandafter\AP@\expandafter{\AP@{#1\par}}%
  }

\makeatother
\newif\ifnew

\begin{document}

\afterpage{
  \csname ifnew\endcsname
     T
   \else 
     F
   \fi
}
  
\end{document}
```

**Comment by FrankMittelbach** [comment]
As Enrico said this is not a bug but wrong coding. You can't hide parts of a low-level conditional, it will break in many places not just here. Instead you need to hide all of it. Most likely \csname else\endcsname and the same for \fi would work but it would be even worth coding. Constructing the \if... with \csname is basically always wrong.

**Comment by PhelypeOleinik** [comment]
@Vidabe Note that you can't really hide `\else` and `\fi` in a `\csname` otherwise TeX would fail to skip conditional branches once your conditional is reached (`\csname else\endcsname` would fail if `\ifnew` is false, and `\csname fi\endcsname` would fail if true).  I suggest `\legacy_if:nTF` too. Another (rather ugly) option would be:
```latex
\afterpage{
  \@gobble\iftrue
  \csname ifnew\endcsname
     T
   \else 
     F
   \fi
}
```
The `\iftrue` is seen when TeX is skipping conditionals, but removed by `\@gobble` when TeX is expanding tokens.

**Comment by FrankMittelbach** [comment]
True, was rubbish, I should stick to vacation. You are of course right one needs to hide the whole construction in a macro probably even a robust one depending on where else it is used.

**Comment by PhelypeOleinik** [comment]
`! Incomplete \vacation; all text was ignored after line 1.` :)

**Comment by Vidabe** [comment]
Ah, I see. I have to admit, it took me a while to understand the problem. `legacy_if:nTF` works like a charm.
