### ISSUE TITLE
Missing characters for Romanization of Cyrillic

### ISSUE THREAD

**Issue by eg9** [latex3/latex2e#593]
## Brief outline of the bug

Some additional translation of Unicode code points are necessary, especially for Romanization of Cyrillic

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}

ISO 9: g̀ǵëêžẑïǰl̂n̂ḱćŭčd̂šŝʺěèûâʼǎf̀ỳ

Other: ġďīīľńćǵăģ

\end{document}
```

## Log file (required) and possibly PDF file  

[romanization.log](https://github.com/latex3/latex2e/files/6687752/romanization.log)

## How to translate

Not all are precomposed. Compilation chokes at

```
g̀ (not precomposed) -> \`g
ẑ (U+1E91)          -> \^z
l̂ (not precomposed) -> \^l
n̂ (not precomposed) -> \^n
ḱ (U+1E31)          -> \’k
d̂ (not precomposed) -> \^d
ʺ (U+02BA)          -> ??
ʼ (U+02BC)          -> ‘ (modifier letter apostrophe)
f̀ (not precomposed) -> \`f
ỳ (U+1EF3)          -> \`y
ḟ (U+1E1F)          -> \.f
ẏ (U+1E8F)          -> \.y
```

**Comment by davidcarlisle** [comment]
I think we should add precomposed ones to the default list. There isn't a lot we can do with Unicode trailing combining accents in pdftex so probably they need to be left out.

**Comment by davidcarlisle** [comment]
Taking the precomposed characters from the above, and adding uppercase comes to

```
Ḟ (U+1E1E)          -> \.F
ḟ (U+1E1F)          -> \.f
Ḱ (U+1E30)          -> \’K
ḱ (U+1E31)          -> \’k
Ẏ (U+1E8E)          -> \.Y
ẏ (U+1E8F)          -> \.y
Ẑ (U+1E90)          -> \^Z
ẑ (U+1E91)          -> \^z
Ỳ (U+1EF2)          -> \`Y
ỳ (U+1EF3)          -> \`y
```

**Comment by davidcarlisle** [comment]
#595 was merged previously but status here was not updated to match, this is now fixed in dev
