### ISSUE TITLE
RemoveFromHook does not work properly at top-level

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#597]
## Brief outline of the bug

`\RemoveFromHook` works as documented for any label but the `top-level` reserved one.

## Minimal example showing the bug

```latex
\documentclass{minimal}
\NewHook{A}
\RemoveFromHook{A}[top-level]
\AddToHook{A}[top-level]{1}
\AddToHook{A}[top-level]{2}
\begin{document}
\UseHook{A}
\end{document}
```
The output unexpectedly reads '12' instead of '2'.

## Log file (required) and possibly PDF file  

[sansnom-17.log](https://github.com/latex3/latex2e/files/6711380/sansnom-17.log)

**Comment by jlaurens** [comment]
Is there a place were the signification of tags is explained, at least because If `mistaken/user error` means that I made an error I would be very glad to know where.

**Comment by davidcarlisle** [comment]
It isn't clear why you expect to only get 2 as you add 1 and 2 at the same point?

Did you intend

```
\documentclass{minimal}
\NewHook{A}
\AddToHook{A}[top-level]{1}
\RemoveFromHook{A}[top-level]
\AddToHook{A}[top-level]{2}
\begin{document}
\UseHook{A}
\end{document}
```

which does produce 2?

**Comment by FrankMittelbach** [comment]
> Is there a place were the signification of tags is explained, at least because If `mistaken/user error` means that I made an error I would be very glad to know where.

The hook system is explained in `texdoc lthooks-doc`.  It may not explain enough how to *use* them but it certainly explains syntax and behavior of each command and imho also various aspects of usage and interaction.
 For example the description of `\AddToHook` states:
```
If there already exists code under the ⟨ label ⟩ then the new ⟨ code ⟩ is appended to the existing one (even if this is a reversed hook). If you want to replace existing code under the ⟨ label ⟩ , first apply \RemoveFromHook.
```
There are plans to write an article on usage with examples, but that hasn't happened yet.

**Comment by jlaurens** [comment]
As stated in the title, the problem is not AddToHook, it is RemoveFromHook.

The documentation reads "If the code for that ⟨label⟩ wasn’t yet added to the ⟨hook⟩, an order is set so that when some code attempts to add that label, the removal order takes action and the code is not added."

As briefly outlined above, this is true for every <label> except for 'top-level'.
The minimal example demonstrates at least that it is false for 'top-level'.

**Comment by FrankMittelbach** [comment]
Documentation has been updated and logic for `\RemoveFromHook` has be simplified. It now doesn't attempt to remove upcoming additions but only work on already existing chunks. Documentation of the special role that the label top-level plays has also been documented more clearly. This has been carried out in other prs.
