### ISSUE TITLE
implement \ResetHook

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#598]
## Brief outline of the enhancement

`\ResetHook{<hook>}[<label>]` would mean if there is a `<label>` code chunk then remove it.

Next is not efficient
```
\AddToHook{<hook>}[<label>]{}
\RemoveFromHook{<hook>}[<label>]
```
Actually, the `\AddToHook` is necessary just in case no code was ever added which is certainly known at run time only.

## Expected [Added afterwards]
```
\ResetHook{A}[X]
\AddToHook{A}[X]{whatever}
\ShowHook{A}
```
should give
```
> Code chunks:
>     X -> whatever
```
Actually, the result of
```
\RemoveFromHook{A}[X]
\AddToHook{A}[X]{whatever}
\ShowHook{A}
```
is unpredictable unless we know every detail of what is performed before.

**Comment by FrankMittelbach** [comment]
Why do you think this is necessary? `\RemoveFromHook` does exactly what you want, in fact the hook doesn't even have to exist:
```
\RemoveFromHook{A}[X]

\NewHook{B}
\RemoveFromHook{B}[X]

\ShowHook{A}
\ShowHook{B}
```
gives you
```
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-06-18>

-> The hook 'A':
> The hook is not declared.
> The hook is empty.
<recently read> }
                 
l.6 \ShowHook{A}
                
? 

-> The hook 'B':
> The hook is empty.
<recently read> }
                 
l.7 \ShowHook{B}
                
? 
```

**Comment by jlaurens** [comment]
While `\ShowHook` does not show the whole hook state, it cannot be used for hook equality.

Actually `\RemoveFromHook{<hook>}[<label>]` is more or less
```
if there is a <label> code chunk then
  remove it
else
  gobble the next added <label> code chunk
fi
```
`\ResetHook{<hook>}[<label>]` would be something like
```
if there is a <label> code chunk then
  remove it
fi
remove all the pending 'gobble next <label> code chunk' instructions
```

**Comment by FrankMittelbach** [comment]
You deduce that from what?  `\RemoveFromHook` removes code chunks added by `\AddToHook` whether or not it is declared. What it doesn't do is to removed code added with `\AddToHookNext`. That doesn't have a "label" and clears itself after use automatically, i.e. it is a different type of operation. Again that is documented:
```
Adds ⟨ code ⟩ to the next invocation of the ⟨ hook ⟩ . The code is executed after the normal hook code has finished and it is executed only once, i.e. it is deleted after it was used.

Using the declaration is a global operation, i.e., the code is not lost, even if the declaration is used inside a group and the next invocation happens after the group. If the declaration is used several times before the hook is executed then all code is executed in the order in which it was declared.1
1 There is no mechanism to reorder such code chunks (or delete them).
```

There are no plans to allow removal of "next-use-code" because that is a runtime operation and there are no reasons for removing code. In contrast, `\AddToHook` is an overall configuration for the hook and there may be cases where one needs to undo or replace code after a certain number of usages or prevent the code chunk added by some other package to be applied though the latter is usually better done through a hook rule.

**Comment by u-fischer** [comment]
> There are no plans to allow removal of "next-use-code" because that is a runtime operation and there are no reasons for removing code.

I do have an open issue/feature request for a `\ClearHookNext`  here https://github.com/latex3/latex2e/issues/565 ;-)

**Comment by FrankMittelbach** [comment]
ouch, okay stand corrected. So we had use cases even though it is a runtime operation that needed looking at and may result in offering clearance of "next-use-code".

**Comment by jlaurens** [comment]
The documentation for `\RemoveFromHook` reads

"Removes any code labeled by ⟨label⟩ from the ⟨hook⟩. [...]
If the code for that ⟨label⟩ wasn’t yet added to the ⟨hook⟩, an order is set so that when some code attempts to add that label, the removal order takes action and the code is not added."

The documentation for `\ResetHook` would read something like

"Removes any code labeled by ⟨label⟩ from the ⟨hook⟩. [...]
Removes any pending order previously set by `\RemoveFromHook` with `<label>`, if any.
If `<label>` is '*', then all code chunks and pending orders previously set by `\RemoveFromHook` are removed, as well as the next invocation code chunk"

BTW, this reset operation is useful in conjunction with "\renewenvironment" for example.

**Comment by Skillmon** [comment]
@FrankMittelbach he is right, `\RemoveFromHook` behaves in a strange way, see the following example:

```tex
\documentclass{minimal}
\NewHook{A}
\RemoveFromHook{A}[foo]
\AddToHook{A}[foo]{1}
\AddToHook{A}[foo]{2}
\begin{document}
\UseHook{A}
\end{document}
```

(taken from https://github.com/latex3/latex2e/issues/597 and changed the label)

That prints `2` in the PDF but not `1`, so `\RemoveFromHook` removes the next `\AddToHook` if the used label doesn't yet exist (except if the used label is `top-level`, see https://github.com/latex3/latex2e/issues/597).

**Comment by PhelypeOleinik** [comment]
@Skillmon That is the expected behaviour, as documented:

> If the code for that ⟨label⟩ wasn’t yet added to the ⟨hook⟩, an order is set so that
when some code attempts to add that label, the removal order takes action and the code
is not added.

This slightly weird behaviour of `\RemoveFromHook` is intentional:  the idea is that package loading order should not matter.

Suppose this example: `amsmath` does
```latex
\AddToHook{begindocument}[amsmath]{%
  \mathchardef\std@minus\mathcode`\-\relax
  \mathchardef\std@equal\mathcode`\=\relax}
```
and `unicode-math` does
```latex
\RemoveFromHook{begindocument}[amsmath]
```
If `\RemoveFromHook` required a specific order, then we would be back with things like `unicode-math` must be loaded after `amsmath`.  The idea with the “marked removal” thing is to abstract a bit from the package loading order when hooks are involved.

**Comment by jlaurens** [comment]
@PhelypeOleinik 
Very instructive example.
In that case, it seems to me that a `voids` rule must be used instead because your code breaks as soon as
`amsmath` decides to
```
\AddToHook{begindocument}[amsmath]{%
  \mathchardef\std@equal\mathcode`\-\relax}
\AddToHook{begindocument}[amsmath]{%
  \mathchardef\std@equal\mathcode`\=\relax}
```
In short, this weird design of `\RemoveFromHook` assumes that only one `\AddToHook` is used, which goes against code separation and moreover is undocumented.

A possible approach would be to deactivate the `amsmath` for the concerned hook, but that is another improvement request.

Anyways, it would be great to focus on the original problem.

**Comment by Skillmon** [comment]
@PhelypeOleinik I know that this is documented, it just seemed like @FrankMittelbach didn't have it in mind in his answers in this thread and in https://github.com/latex3/latex2e/issues/597, that's all.

**Comment by PhelypeOleinik** [comment]
After some pondering, we've decided that the current behaviour of `\RemoveFromHook` is not ideal.  It was a nice idea, but it doesn't actually work as it should, so I'll simplify `\RemoveFromHook` to just remove if the code is there, and for other cases, where package loading order shouldn't matter, the `voids` rule should be used instead.  I've opened issue #625 to track this.
