### ISSUE TITLE
babel: Please provide a hook into \hyphenrules

### ISSUE THREAD

**Issue by lemzwerg** [latex3/latex2e#6]
[The described use-case is for xelatex, but the issue itself is generic.]

* biblatex can do automatic language switching for multilingual entries.  The least invasive option is `autolang=hyphen`, making biblatex use babel's `hyphenrules` environment; the language information for babel is taken from the `langid` field in the bibliography entries.

* If you are going to use the xeCJK package for CJK support but using a non-CJK language as the main language, it is necessary to deactivate CJK handling (`\xeCJKsetup{xeCJKactive=false}`).  Otherwise, characters like '`–`' (U+2013, `\textendash`) are treated similar to CJK characters, which implies suppression of whitespace right after the character.  [Note that using a CJK script without xeCJK works only for very short strings.]

* The reverse conclusion of the last item is that you have to activate CJK support if you switch to a CJK language (using `\makexeCJKactive`).  And here is the problem: babel doesn't provide a hook into the `hyphenrules` environment to do that.  I had to redefine the environment, which is ugly.

I thus vote for adding a hook into `hyphenrules` so that issues similar to the just outlined one can be solved elegantly.  Maybe I'm missing something – I would be glad if there already existed a solution to do what I want!

```latex
\RequirePackage{latexbug}

\documentclass{article}

\usepackage[japanese, english]{babel}
\usepackage{xeCJK}
% `autolang=hyphen' makes biblatex use the hyphenrules
% environment for language support.
\usepackage[autolang=hyphen]{biblatex}

% This font is in TeXLive.
\setCJKmainfont{ipam.ttf}

\begin{filecontents}{bb.bib} 
@BOOK{english,
  author = {England, Mister},
  title = {England forever},
  langid = {english}
}
@BOOK{japanese,
  author = {Niho, Sensei},
  title = {日本},
  langid = {japanese}
}
\end{filecontents} 

\addbibresource{bb.bib}

% Deactivate xeCJK by default so that characters like `–' (U+2013) are
% not treated as CJK (this is, suppressing spaces after the
% character).
\xeCJKsetup{xeCJKactive=false}

% If you comment in the redefinition of \hyphenrules, Japanese characters
% are properly printed in the bibliography.
%\let\myhyphenrules \hyphenrules
%\def\hyphenrules#1{%
%  \myhyphenrules{#1}%
%  \edef\myjapanese{japanese}%
%  \edef\myoption{#1}%
%  \ifx\myoption \myjapanese
%    \expandafter\makexeCJKactive
%  \fi}


\begin{document}
England\cite{english}
Japan\cite{japanese}

\printbibliography
\end{document}
```

**Comment by jbezos** [comment]
Hooks are mainly for injecting code at some “internal” points which are not easily accesible with a redefinition. I'll study your proposal, but a package like etoolbox should be enough and therefore I don't think a hook is really necessary.

**Comment by lemzwerg** [comment]
Yes, you are probably right.  I think it is a biblatex issue that I have an option `autolang=hyphen` to switch hyphenation patterns (and nothing else), an option `autolang=other` to use Babel's `otherlanguage` environment to switch languages and localized biblatex strings (for example, English 'visited:' gets changed to German 'besucht am:'), but nothing inbetween, namely switching languages without switching localized biblatex strings...
