### ISSUE TITLE
_LaTeX:  A Document Preparation System_, second edition, §C.10.1:  “The tabbing Environment”

### ISSUE THREAD

**Issue by powerpcg5** [latex3/latex2e#602]
This is a bug report for _LaTeX:  A Document Preparation System_, second edition, 17th printing (November 2003).  Was advised by the author to submit this report concerning the book itself here.  This does not appear to have been previously reported in the [second-edition book errata dated 13 October 2018](https://www.latex-project.org/help/books/manual.err).

On page 201, under §C.10.1:  “The tabbing Environment”:  "Initially, the value of next_tab_stop is 1, the value of left_margin_tab is 0"
and then:
"The value of next_tab_stop is incremented by the \\> and \\= commands, and it is reset to the value of left_margin_tab by the \\\\ and \\kill commands."

Then on page 202:

"\\\\	Starts a new line and sets the value of next_tab_stop equal to the value of left_margin_tab."

"\\kill	Throws away the current line, keeping the effects of any tab-stop-setting commands, starts a new line, and sets the value of next_tab_stop to the value of left_margin_tab."

For both \\\\ and \\kill, shouldn't both of them, after starting a new line, set the value of next_tab_stop equal to the value of left_margin_tab + 1 (rather than to the value of just left_margin_tab)?
_I. e._, initially left_margin_tab = 0 and next_tab_stop = 1 (= left_margin_tab + 1); shouldn't/wouldn't the same relationship (next_tab_stop := left_margin_tab + 1) be restored after \\\\ and \\kill?

Suggested fixes:

1.  (Pages 201–202:)  "The value of next_tab_stop is incremented by the \\> and \\= commands, and it is reset to the value of left_margin_tab by the \\\\ and \\kill commands." → Replace “left_margin_tab” with “left_margin_tab + 1”

2.  (Page 202:)  "\\\\	Starts a new line and sets the value of next_tab_stop equal to the value of left_margin_tab." → Replace “left_margin_tab” with “left_margin_tab + 1”

3.  (Page 202:)  "\\kill	Throws away the current line, keeping the effects of any tab-stop-setting commands, starts a new line, and sets the value of next_tab_stop to the value of left_margin_tab." → Replace “left_margin_tab” with “left_margin_tab + 1”

**Comment by FrankMittelbach** [comment]
I'm sorry, but despite of what Leslie may have said to you, we only distribute the errata for his book, we don't and can't make decisions on what errata is accepted for it or not. It did however told Leslie that I think you are right and he should accept your errata.
