### ISSUE TITLE
longtable is unnecessarily pushed to the next page

### ISSUE THREAD

**Issue by finefoot** [latex3/latex2e#604]
The second longtable is unnecessarily pushed to the next page:

![mh2wz](https://user-images.githubusercontent.com/33361833/123623814-2e212d00-d80e-11eb-800f-87f0d61458f5.jpeg)

I have tried to make it into a minimal example as much as possible:

```latex
\RequirePackage{latexbug}
\documentclass[]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{fancyvrb}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
\usepackage{longtable,booktabs,array}

\begin{document}

Some line of text

\begin{longtable}[]{@{}l@{}}
\toprule
header \\
\midrule
\endhead
value \\
\bottomrule
\end{longtable}

\vspace*{97mm}

\begin{Highlighting}[]
1
2
3
4
5
6
7
\end{Highlighting}

\begin{Highlighting}[]
1
2
3
4
5
6
7
8
\end{Highlighting}

Another line of text

\begin{longtable}[]{@{}l@{}}
\toprule
header \\
\midrule
\endhead
value \\
\bottomrule
\end{longtable}

\end{document}
```

Logfile: [example.log](https://github.com/latex3/latex2e/files/6725522/example.log)

Post on StackExchange for reference: https://tex.stackexchange.com/questions/598686/longtable-is-unnecessarily-pushed-to-the-next-page

**Comment by u-fischer** [comment]
Your latex is too old `LaTeX2e <2020-02-02> patch level 5`.  With `LaTeX2e <2021-06-01> patch level 1` I get only two pages.

**Comment by finefoot** [comment]
I'm sorry. I'm sure that I tested it with the most recent release when I made that post on StackExchange. Apparently that was `LaTeX2e <2020-10-01> patch level 4` and I can still reproduce the issue with that release.

However, you're right, with today's most recent release, which is `LaTeX2e <2021-06-01> patch level 1`, the issue is gone. :+1:
