### ISSUE TITLE
Provide \IfPackageLoadedTF and similar

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#621]
## Brief outline of the enhancement

A while back commands such as `\IfPackageAtLeastTF` etc were made available and not just the already existing commands with `@` in their name, but a few were left out then.

## Minimal example showing the current behaviour

Offer

- `\IfPackageLoadedTF`
- `\IfClassLoadedTF`
- `\IfPackageLoadedWithOptionsTF`
- `\IfClassLoadedWithOptionsTF`

and also allow them in code executed outside of the preamble.

**Comment by blefloch** [comment]
>   * |\IfPackageLoadedTF|
>   * |\IfClassLoadedTF|
>   * |\IfPackageLoadedWithTF|
>   * |\IfClassLoadedWithTF|

Should the "With" ones be "WithOptions"?  We have \LoadClass and
LoadClassWithOptions.

**Comment by FrankMittelbach** [comment]
Yes it should.
