### ISSUE TITLE
\contentsline should pick up 4 not 3 arguments

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#633]
## Brief outline of the enhancement

A while back `\contentsline` entries written to the toc file were written with 4 arguments, the fourth one by default empty but containing a "destination" label if hyperref  is used. However, the kernel definition of `\contentsline` still picks up only 3 arguments.

As long as the fourth is empty this doesn't matter but if you had used hyperref and then removed it from the preamble the no longer needed destinations would end up being typset with all kind of  issues.

`\contentsline` should therefore be changed to always pick up the fourth argument and store it in a variable so that hyperref can use that without the need to alter the definition.

**Comment by JohannesBraams** [comment]
I need to add this change to hte NTG document classes as well as they use a replacement for \contentsline...

**Comment by FrankMittelbach** [comment]
you don't need you, it should continue to work if you overwrite it again. However if hyperref starts using `\@contentsline@destination` directly then not.

But I don't see that `\contentsline` is touched by the ntg classes, where please?

**Comment by JohannesBraams** [comment]
You're right, the changes in layout are done at a different level, my memory served me wrong.
