### ISSUE TITLE
Make `~` active in docstrip's initex mode

### ISSUE THREAD

**Issue by vlasakm** [latex3/latex2e#636]
## Brief outline of the enhancement

I am using `docstrip.dtx` to process a few `.ins` files with `initex`. However, recently one of those `.ins` files started to expect that ``\catcode`\~=13``. I usually make these adjustments before processing the `.ins` files, like  this:

```
luatex -ini '\let\obeyspaces=\relax \input lipsum.ins'
```

This is not possible with for the `~` catcode, because that is how `docstrip` detects, that it is not run under `initex`:

```
\ifnum13=\catcode`\~{\egroup\else
  \catcode`\Z=9
  ...
\fi
```

Would it be possible to set the `\catcode` of `~` to 13 in this "plain TeX compatibility" piece of code?

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

I am perfectly fine with patching around for my dubious use case. I understand that this subtle change is not desirable after such a long time.

## Minimal example showing the current behaviour

```
$ luatex -ini '\let\obeyspaces\relax \input lipsum.ins'
...
! Missing control sequence inserted.
```

Because of `\def~{ }%`

## Minimal example showing the desired new behaviour

With:
```diff
--- a/docstrip.dtx
+++ b/docstrip.dtx
@@ -1018,6 +1018,7 @@
 Z  \catcode`\{=1  \catcode`\}=2
 Z  \catcode`\#=6  \catcode`\^=7
 Z  \catcode`\@=11 \catcode`\^^L=13
+Z  \catcode`\~=13
 Z  \let\bgroup={  \let\egroup=}
 Z
 Z  \dimendef\z@=10 \z@=0pt \chardef\@ne=1 \countdef\m@ne=22 \m@ne=-1
```

```
$ luatex -ini '\let\obeyspaces\relax \input lipsum.ins'
(no error)
```

Context: https://github.com/vlasakm/mmtex/pull/3

**Comment by PhelypeOleinik** [comment]
> However, recently one of those `.ins` files started to expect that `` \catcode`\~=13 ``.

Part of the blame is mine ;-)

I could change `lipsum.ins` to ensure `~` is active for whatever it needs:  at the `lipsum` side this is a harmless change.  Less so for `docstrip`.

Makes me wonder though: why use initex for unpacking?

**Comment by vlasakm** [comment]
> I could change `lipsum.ins` to ensure `~` is active for whatever it needs: at the `lipsum` side this is a harmless change. Less so for `docstrip`.

That was going to be my second suggestion, if you were so kind to do so. Third option being patching around it myself (I wouldn't want anyone actively maintaining my use case).

I just though that it was inconsistent for docstrip to check for a setting to detect iniTeX, but the setting is not actually needed (and hence not set). That is why this was my first try at remedying the issue at hand.
 
> Makes me wonder though: why use initex for unpacking?

I [bootstrap](https://github.com/vlasakm/mmtex/blob/db7c5ffd03a51730f3dc47ee19965d133e89a6b4/mmtex/build) a small TeX distribution (LuaTeX + OpTeX + a few packages) from a few [sources](https://github.com/vlasakm/mmtex/blob/db7c5ffd03a51730f3dc47ee19965d133e89a6b4/mmtex/sources). Essentially I do:

```
# use docstrip.dtx as docstrip.tex and l3docstrip.tex
ln -sf docstrip.dtx docstrip.tex
ln -sf docstrip.dtx l3docstrip.tex

# generate lipsum.ltd.tex
luatex -ini '\let\obeyspaces=\relax \input lipsum.ins'

# generate luamplib.{sty.lua}
luatex -ini '\catcode`\{=1 \catcode`\}=2 \let\obeyspaces\relax \input luamplib.dtx'

# generate some lualibs files
luatex -ini '\catcode`\{=1 \catcode`\}=2 \let\obeyspaces\relax \input lualibs.dtx'
```

Processing the few `.ins` files with plain would require me to generate the plain format itself (which requires fonts). Docstrip with `initex` was good enough for now.

By the way, while bothering you, I believe you can use `docstrip.tex` instead of `l3docstrip.tex` :).

**Comment by PhelypeOleinik** [comment]
> Processing the few `.ins` files with plain would require me to generate the plain format itself (which requires fonts).

Ah, minimal setups :-)

I'd say providing plain is a must for any TeX distribution (kind of “the basics”), but that's digressing.  I'll change the `.ins` file for `lipsum`.

**Comment by vlasakm** [comment]
Thank you very much, @PhelypeOleinik. That solves my issue quite well.

I still think the proposed change would make sense. But not sure if there is a point in pursuing this since it would be one of only backwards incompatible changes in `docstrip` in a long time AFAICT. (But then again, who uses `docstrip` with `initex` to process something other than `docstrip` itself :)

Leaving the decision on closing the issue on you guys.

PS: @PhelypeOleinik I used to package (TeX Live's) plain LuaTeX as well, but later decided against it. Many things I wasn't really fond of are deeply rooted in -- fonts, eTeX's `\language`s. But that is a discussion for anonther place :)

**Comment by FrankMittelbach** [comment]
> I still think the proposed change would make sense. But not sure if there is a point in pursuing this since it would be one of only backwards incompatible changes in `docstrip` in a long time AFAICT. (But then again, who uses `docstrip` with `initex` to process something other than `docstrip` itself :)

I'm against making changes to docstrip for that. It is soooo core to basically everything (other than ConTeXt) so that it is bound to generate issues and history says it will. Don't think that is worth it.  So it should be fixed in lipsum.
