### ISSUE TITLE
Babel tries to set the script to Japanese, but fontspec expects Kana.

### ISSUE THREAD

**Issue by Davislor** [latex3/latex2e#64]
## Brief outline of the bug

When including `\usepackage[japanese]{babel}` on XeLaTeX or LuaLaTeX, and setting the font with `\babelfont`, the package attempts to set the `fontspec` feature `Script=Japanese`.  However, the correct key in `fontspec` is `Script=Kana`.

It is possible to ignore the error (if using a font whose default presentation of unified CJK is Japanese).

Defining the language with `\babelprovide[import=ja, script=Kana]{japanese}` instead works.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass[varwidth, preview]{standalone}
\usepackage{fontspec}
\usepackage[japanese, english]{babel}

% The Script= setting is broken for Japanese as of August 2018.
% Workaround:
%\babelprovide[import=ja, script=Kana]{japanese}

\defaultfontfeatures{Scale=MatchUppercase, Ligatures=TeX}

\babelfont{rm}[
  Scale = 1.0,
  Ligatures={Common, TeX}]{Source Serif Pro}
\babelfont{sf}[Ligatures={Common, TeX}]{Source Sans Pro}
\babelfont{tt}{Source Code Pro}

% Font available at: https://github.com/adobe-fonts/source-han-code-jp
\babelfont[japanese]{rm}[
  Ligatures = {Discretionary, TeX},
  UprightFont = *-Regular ,
  BoldFont = *-Bold ,
  ItalicFont = *-RegularIt ,
  BoldItalicFont = *-BoldIt ,
  Extension = .otf ]{SourceHanCodeJP}

\begin{document}
Text in \foreignlanguage{japanese}{日本語}.
\end{document}
```

## Log file (required) and possibly PDF file  

[sx-sourcejp.log](https://github.com/latex3/latex2e/files/2276136/sx-sourcejp.log)

[sx-sourcejp.pdf](https://github.com/latex3/latex2e/files/2276139/sx-sourcejp.pdf)

**Comment by jbezos** [comment]
There is another approach: `\newfontscript{Japanese}{kana}`. It can be done by `babel` itself, because the `ini` file already contains this info.  And I'd like to stick to the basic script names as provided by the Unicode CLDR, too.  But I have to think a bit about it.

**Comment by wspr** [comment]
If fontspec has a poor name I'd be happy to change. (Looking anew at <https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags> it gives `kana` two names ‘hiragana’ and ‘katakana’; I suspect I simplified that to ‘Kana’ to avoid the complexity of having the two.) 

But I don't think ‘Japanese’ would be the best name here — that would be the name of the language being typeset, not the script in use. (Analogous, say, to how the English language is written in the Latin script.)

**Comment by jbezos** [comment]
I wouldn't say it's a poor name. There are just different criteria, and the Unicode CLDR provide Jpan (code) and Japanese (English name). I guess Japanese is kanji + kana, and not just kana (like Okinawan, which apparently doesn't use kanji, or only limitedly). And after all Greek is written in the Greek script, and same for Arabic, Thai, etc. :-)

**Comment by sony976837769** [comment]
[[反璞歸真為真如 砱崆御枵麮驉無 陰陽日月為乾坤 天地遨遊趣楈錓]]
反璞歸真 黃 保欽親筆瀛題

**Comment by car222222** [comment]
Why are comments being deleted?

**Comment by car222222** [comment]
“Unicode CLDR provide Jpan (code) and Japanese (English name).”  But for what is this provided.  Exactly what “script”is this?  Japanese typically uses three distinct scripts, so there should be no single script called “Japanese”.  You cannot make a script by taking a disjoint union of others!

**Comment by blefloch** [comment]
@car222222 that was a comment written in Kanji.  Google Translate-ing it gives nonsense.

**Comment by car222222** [comment]
Agreed that “kana” was not a good choice, meaningless.  Note also that in this area, Unicode names were mostly dictated by the huge Korean presence so do not reflect well other large language/cultural groupings imn that region.  In particular, the use of “kanji” is not (culturally) correct.

**Comment by car222222** [comment]
Wh not ask some Japanese what makes sense here?

**Comment by wspr** [comment]
Ahem: https://en.wikipedia.org/wiki/Kana

This isn't about Unicode when it comes to saying `script=kana`. If you want a switch that activates both `script=kana,language=JAN` that is logical and ‘Japanese’ would be a good name. But I still don't believe that `script=japanese` is meaningful.

**Comment by wspr** [comment]
(Sorry for the stream of consciousness on these comments.)

The following Adobe tutorial shows a Japanese font being constructed with both `hani` and `kana` scripts: <https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5901.Kazuraki_Tutorial.pdf>

I haven't been able to find anything more concrete than that on when a Japanese user would choose between them. I guess that when writing vertical text in fixed-width columns, it would be logical to select `hani` and when writing horizontal text with proportional spacing to select `kana`.

So given that there may be cases in which the distinction is important (e.g., a font only implements one, or there are differences between them) I think fontspec's current naming to match with the OpenType script tags is still the best approach.

**Comment by e-kwsm** [comment]
Japanese is written in kanji (CJK ideographic or hani) and kana, and agree with

> Japanese typically uses three distinct scripts, so there should be no single script called “Japanese”.

---

> I guess that when writing vertical text in fixed-width columns, it would be logical to select `hani` and when writing horizontal text with proportional spacing to select `kana`.

No, `hani` is kanji.

**Comment by jbezos** [comment]
See  see http://www.unicode.org/iso15924/faq.html#14 (and also http://scriptsource.org/cms/scripts/page.php?item_id=script_detail&key=Jpan ). So, my guess was correct, because Japanese is used as an alias for Han + Hiragana + Katakana. Maybe conceptually it's wrong, but from a practical point of view it makes sense.

**Comment by FrankMittelbach** [comment]
With Japanse you can write text completely using just Hiragana (as often done with entry-level childrens books) you can in theory write it completely just using Katakana (though that isn't done to my knowledge) or you can mix and match and write some parts in Hiragana, some in Katakana (like foreign words etc) and some using Kanji. In some sense it seems a bit like the situation with the scripts for English where "italic" is really a different script (typically justed just for emphasis (though not always), but for ease of usage we don't refer to it as a separate script but  claim that a text is written in Latin script even if it is in fact written in several Latin based scripts (with the change in scripts indicated though other means).

So I guess what you call the combination of several scripts partly depend on what you want to do downstream with it and what kind of support you have to switch internally from one of the "inner" scripts to another. So my feeling is that calling Hani+Kana a "Japanese script" is not a bad thing as such assuming you have internally then ways to decide whether you want to typeset"dog" as 犬 or いぬ or イヌ

**Comment by wspr** [comment]
I still think we are confusing the difference between OpenType "scripts" and Unicode "scripts". Javier suggested earlier:

    \newfontscript{Japanese}{kana}

I was trying to explain why this isn’t the default naming in fontspec. Here, the first argument `Japanese` is the fontspec name for the script, and `kana` is the OpenType tag for the script.

The OpenType standard ([link to list of tags](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)) describes TWO scripts for Japanese: `kana` and `hani`. (`hani` is of course also used in other languages besides Japanese.) Currently fontspec defines:

    \newfontscript{Kana}{kana}
    \newfontscript{CJK}{hani}

You can only declare a single script for a font, so when typesetting Japanese text in some contexts it might be correct to write `Script=Kana` and in other contexts it might be correct to write `Script=CJK` (the fontspec name for `hani`).

But this might be correct — I would be happy to add `Script=Japanese` if anyone can provide evidence of some kind that the way that Japanese OpenType fonts are set up means that in practice one would never write `Script=CJK` in a Japanese document.

However, I just took a look inside Adobe’s Source Han Sans CJK font (https://github.com/adobe-fonts/source-han-sans/releases), and for Japanese it contains the following:

script = ’hani’
language = ’JAN ’
features = ’aalt’ ’calt’ ’ccmp’ ’dlig’ ’fwid’ ’hist’ ’hwid’ ’jp78’ ’jp83’ ’jp90’ ’liga’ ’locl’ ’nlck’ ’pwid’ ’vert’ ’vrt2’ ’halt’ ’kern’ ’palt’ ’vhal’ ’vkrn’ ’vpal’

script = ’kana’
language = ’JAN ’
features = ’aalt’ ’calt’ ’ccmp’ ’dlig’ ’fwid’ ’hist’ ’hwid’ ’jp78’ ’jp83’ ’jp90’ ’liga’ ’locl’ ’nlck’ ’pwid’ ’vert’ ’vrt2’ ’halt’ ’kern’ ’palt’ ’vhal’ ’vkrn’ ’vpal’

So the actual list of features for each script are the same. However, inside the [features file for one of these fonts](https://github.com/adobe-fonts/source-han-sans/blob/master/Normal/features.JP) I can see ONE difference between `hani` and `kana`:

```
feature locl {
  # LATN SCRIPT
  script latn;
  language dflt;
  lookup latin_special;

  language JAN exclude_dflt; # ADDED
  lookup cnhkjptw_special;   # ADDED

  # KANA SCRIPT
  script kana;
  language JAN;
  lookup cnhkjptw_special;
} locl;
```

So I'm still not convinced about what the correct thing to do here is.

**Comment by e-kwsm** [comment]
Actually the word "日本語" in the [example](/latex3/latex2e/issues/64#issue-349324373) is composed of kanji scripts only, so `Script=Kana` is strange for me.

Similarly, korean (s/japanese/korean/ example) does not work and a workaround is `\babelprovide[import=ko, script=Hangul]{korean}`.

`Script=Japanese/Korean` is not correct but more intuitive than something like `Script=HaniOrKana/HaniOrHangul`, I think.

**Comment by jbezos** [comment]
The key point is ‘the difference between OpenType "scripts" and Unicode "scripts"’. As I said, simply there are several criteria. Babel is about localization and fontspec is about fonts, and with babel in fact the `Script` and the `Language` names are usually irrelevant for the user, because babel sets them for you and they remain hidden. I think there is no need to add  `Japanese` to fontspec, and mapping from the locale name to the font name/code is a task for babel.

**Comment by e-kwsm** [comment]
Usually a Japanese font provides hani, hiragana and katakana (and latin) scripts, and we don't have to care script of a character.

If a user have to specify OpenType script tag—either hani or kana—explicitly, a sentence looks like
`{\addfontfeature{Script=Kana} これは}{\addfontfeature{Script=CJK} 日本語}\addfontfeature{Script=Kana} の}{\addfontfeature{Script=CJK} 文章}{\addfontfeature{Script=Kana} です}
`
