### ISSUE TITLE
Incorrect error message for text accent in math mode

### ISSUE THREAD

**Issue by dahosek** [latex3/latex2e#643]
## Brief outline of the bug

If a user uses a text accent in math mode, LaTeX responds with 

```
LaTeX Warning: Command \' invalid in math mode on input line 22.

! Please use \mathaccent for accents in math mode.
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\begin{document}

\[
  \'{a}
\]

\end{document}
```
[x2.log](https://github.com/latex3/latex2e/files/6963711/x2.log)

**Comment by dahosek** [comment]
The reuse of `\DeclareTextCommand` seems to be the culprit here. The warning is generated at that point and then the error comes from TeX's internals. We'd need to catch the error before things got that far.

**Comment by davidcarlisle** [comment]
it could potentially be changed but I think the current behaviour is by design.

You get the latex-generated warning that mentions the document level accent syntax that caused the issue then it drops through to the tex primitive behaviour so you get an error message and a more or less reasonable fallback behaviour if you scroll past the error.

You could instead generate accent specific errors saying `\'` used in math mode, use `\acute`  but that would be a lot more code (certainly more than would have been available originally just for an error message)

**Comment by FrankMittelbach** [comment]
> it could potentially be changed but I think the current behaviour is by design.

it was/is certainly by design, but I wonder it it always had the strange spacefactor error following. Anyway, if we change something we could change it to an error not warning because you get an earror a little later anyway.

**Comment by dahosek** [comment]
My thought is, that if there's going to be a change, it would be to change the call to `\@inmathwarn` to `\@inmatherr`. This, however, would require some minor surgery though.

(I'm spending a lot of time doing things wrong in LaTeX for documentation purposes these days so I'll likely turn up some more things like this. It's perfectly fine to mark this as “won't fix.”).

**Comment by davidcarlisle** [comment]
@blefloch  commented that with lualatex you get the LaTeX warning but no error and neither the accent nor the base letter are typeset. That isn't good at all, looking....

**Comment by FrankMittelbach** [comment]
> seems to be a "recent" addition

for some definiton of "recent", kind of 2+2=5 for some large value of 2 :-)

**Comment by FrankMittelbach** [comment]
> I am tempted to just make a small change to skip the space factor setting in math mode so as now you get a warning then a primitive "use \mathaccent" error but don't then get the spacefactor error.

sounds good to me

> In the composite accent case where you get no error as \accent isn't called (typically in luatex but also possible with pdftex) you just get the warning then you either get a character or more likely you get
> 
> ```
> Missing character: There is no á (U+00E1) in font cmmi10!
> ```
> 
> which is currently rather quiet in the log file but in recent engines can be an error if we set \tracinglostchars to 3

I think this is ok/enough. a) we already now default `\tracinglostchar` to 2 so it shows on the terminal as well and  b) I think ultimately we need to lobby for  `\tracinglostchar=3` (just wrote an article for TUB on the subject), perhaps we should make that the default for unicode engines anyway (compatibility or not). After all getting tofu with Unicode engines is unfortunately rather likely and for example, most Unicode math fonts are missing symbols  even from the core set (like `\biguplus` in one case)  or - more often - some of those from amssymb.
