### ISSUE TITLE
Replace \guillemot... by \guillemet...

### ISSUE THREAD

**Issue by MdAyquassar** [latex3/latex2e#65]
### The guillemots are birds and the guillemets are characters

In the old times, there were some historical reasons for saying `\guillemotleft` and `\guillemotright`. Kudos go to the excellent comments of `brannerchinese` and `egreg` in [the corresponding SE question](https://tex.stackexchange.com/questions/34406/observation-not-a-question-the-commands-guillemotleft-and-guillemotright-ap), `David Carlisle`, `Ulrike Fischer`, and `barbara beeton` in [today's chat](https://chat.stackexchange.com/rooms/41/tex-latex-and-friends). Nowadays, the space for the synonyms is not as scarce as it was in the 1990's, so, you could replace the wrong spelling in the user interface in three time-separated steps by

1. Introducing new synonyms `\guillemetleft` and `\guillemetright`
2. Declaring old \guillemot... for deprecated
3. Removing old \guillemot... for new documents (e.g., when you get rid of `\usepackage[T1]{fontenc}` and/or `\documentclass` in favor of something new).

Of course, some folks do not use `\guillemotleft`, `\guillemotright` widely anyway, favoring «». Still, the ASCII versions make sense in case you cannot or don't wish to enter/view non-ASCII symbols for some reason (e.g., when using non-UTF8 LaTeX packages, text processing tools, or viewers.) Certainly, it is sometimes possible to hide these symbols inside `\newcommand\q[1]{\guillemotleft #1\guillemotright}` or `\enquote`, but not always, e.g., when your quote begins in one cell of a tabular and ends in another cell, or when you use the symbols non-pairwise (i.e., not for quoting). On top of that, one would finally get rid of one source of tedious comments like mine here; I apologize a lot for that.

**Comment by eg9** [comment]
I think that the synonyms should be added, but I believe that the old names should remain for back compatibility.

**Comment by MdAyquassar** [comment]
That's why I suggested "for new documents" in item 3.

**Comment by MdAyquassar** [comment]
@eg9 I thought that in the future we could find ourselves in the need of writing something like \docclass (e.g.) instead of \documentclass, which would distinguish a "new document".

**Comment by FrankMittelbach** [comment]
Fixed with 412f52a66379e54fcecae66caac7fa73ea624111

**Comment by MdAyquassar** [comment]
@FrankMittelbach Wow, that was fast!!! Thank you!!!

**Comment by PeterMuellerr** [comment]
@FrankMittelbach How about saying `\guillemetleft` and `\guillemetright` also in the .dfu files? In my copies of utf8enc.dfu, t2cenc.dfu, ot2enc.dfu, lcyenc.dfu, t2aenc.dfu, ly1enc.dfu, t1enc.dfu, t2benc.dfu, and x2enc.dfu, I still have only the versions with "o".

**Comment by FrankMittelbach** [comment]
should be address in the upcoming release

**Comment by schlcht** [comment]
Hm, what about font encoding files that our outside your purview? For example this now fails: 

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[LY1]{fontenc}
%\DeclareTextSymbol{\guillemetright}{LY1}    {187}
%\DeclareTextSymbol{\guillemetleft}{LY1}     {171}
\begin{document}
utf:«»

licr:\guillemotleft \guillemotright
\end{document}
```

Same for LGR, Cyrillic encodings ...

**Comment by PeterMuellerr** [comment]
@schlcht I might sound deliberatly bold, but isn't this failure actually good? Previously (taking, e.g., the current Debian-stable distribution), 
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[LY1]{fontenc}
\begin{document}
utf:«»

licr:\guillemetleft \guillemetright
\end{document}

```
failed. If you ask me, which version _should_ fail if there's a choice, I'd say the one with the wrong spelling (as far as French is concerned). This encourages improvement. IMHO, a textual search-and-replace of `\guillemotright` with `\guillemetright` and of `\guillemotleft` with `\guillemetleft` is a no brainer. Perhaps even `find . -type f -not -path '*/\.*' -name "*.tex" -exec sed -i 's/\guillemotright/\guillemetright/g' {} +` followed by `find . -type f -not -path '*/\.*' -name "*.tex" -exec sed -i 's/\guillemotleft/\guillemetleft/g' {} +` could do this recursively.

**Comment by FrankMittelbach** [comment]
That failure wasn't intended and no I don't think it is is good because the failure is in some enc file and not in the user document. We could of course ask the enc file maintainers to update (and that would make  some sense) but it would not catch all enc files easily and only causes unnecessary grief. On the other hand it is correct if LaTeX uses the right name as far as possible.

So perhaps the following additional default gives the best of both worlds:
```
% fall back to incorrect (old) name if the correct one not available in the font encoding and hope for the best
\DeclareTextCommandDefault{\guillemetleft}{\guillemotleft}
\DeclareTextCommandDefault{\guillemetright}{\guillemotright}
```
The  downside of that is that then in OT1 you get a warning for the old symbol name rather than the correct one, so there should probably be also
```
\DeclareTextCommand{\guillemetleft}{OT1}{\TextSymbolUnavailable\guillemetleft}
\DeclareTextCommand{\guillemetright}{OT1}{\TextSymbolUnavailable\guillemetright}
```
so that the above default doesn't apply.

**Comment by davidcarlisle** [comment]
@schlcht 


https://github.com/davidcarlisle/ly1/commit/8d56b3cc2fc7fd17abdeb8adcb2208a13f4e0e0b

Would fix this I think

`ly1nc.def` (still) has my name on it, so I did that first, but I will reach out and arrange updates to the other encoding files this weekend.
