### ISSUE TITLE
Missing \begin{document} error with \NewDocumentEnvironment

### ISSUE THREAD

**Issue by adunning** [latex3/latex2e#650]
## Brief outline of the bug

Two incomplete `\NewDocumentEnvironment`s next to one another will trigger the error `Missing \begin{document}.` This will not occur either with the correct number of braces or if a line break is placed between the lines.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass{article}

% produces an error
\NewDocumentEnvironment{test1}{}{}
\NewDocumentEnvironment{test2}{}{}

% works as expected
% \NewDocumentEnvironment{test1}{}{}{}
% \NewDocumentEnvironment{test2}{}{}{}

% a line break also prevents the error
% \NewDocumentEnvironment{test1}{}{}
%
% \NewDocumentEnvironment{test2}{}{}

\begin{document}
  
  test

\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/7028262/test.log)

**Comment by FrankMittelbach** [comment]
There is no error here. A blank line is, as far as TeX is concerned equal to a `\par`. Furthermore, in most places the engine accepts either a single token or a brace group and you can't really check for this from LaTeX as it is engine behavior. So
```
% produces an error
\NewDocumentEnvironment{test1}{}{}
\NewDocumentEnvironment{test2}{}{}
```
is equiv to
```
\NewDocumentEnvironment{test1}{}{}{\NewDocumentEnvironment}
% and the remainder is triggering the error:
{test2}{}{}
```
while
```
\NewDocumentEnvironment{test1}{}{}

\NewDocumentEnvironment{test2}{}{}

```
is equiv to
```
\NewDocumentEnvironment{test1}{}{}{\par}
\NewDocumentEnvironment{test2}{}{}{\par}
```
so no error shows up, but you have a crippled definition. This can't be caught on the LaTeX level unless you abandon everything that TeX automatically does for you and do everything manually instead, i.e. read character by character and not let TeX do the parsing, but that would mean even with today's computers you would wait probably minutes for a page to compile and not a few milliseconds.

**Comment by adunning** [comment]
Thanks for the clarification. I suppose there is no way to give an error indicating that `\NewDocumentEnvironment` is incomplete rather than `\begin{document}`?

**Comment by FrankMittelbach** [comment]
It boils down to `\def\foo#1{}` accepting both `\foo{a}`as well as `\foo a` with the same result. One can prevent that by not letting TeX parse the argument, but looking for an explict open brace and only then grabbing it. That's possible but results in a noticable slowdown and it is also not really what one wants in many places, e.g., most people use `\newcommand\foo[1]{...}` not `\newcommand{\foo}[1]{...}` because it is more readable, which is precisely the same mechanism.
