### ISSUE TITLE
\color not \escapechar safe

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#659]
## Brief outline of the bug

At certain times during process LaTeX disables the escapechar, e.g. while processing fonts. If during that time `\color` is called, the processing fails and a named color is not recognized because color doesn't temporarily restore the escape char as other commands do.

This can, for example, happen if the OR is called at the wrong time. One could (and probably should) restore the escape char there, but nontheless I think the color commands should itself take care of this. Might also need handling in l3color.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\usepackage{color}

\begin{document}

\color{blue} blue

\escapechar=-1

\color{blue} blue

\end{document}
```

## Log file (required) and possibly PDF file  

```
LaTeX Error: Undefined color `blue'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.13 \color{blue}
                  blue
? 
```

**Comment by u-fischer** [comment]
l3color seems not to be affected. After `\let\color\color_select:n` (and grouping the setting naturally) it works fine.

**Comment by davidcarlisle** [comment]
for `color` the `\string` isn't really needed as it's just applied to`color`  (as long as we can assume normal escapechar while color definitions are made)

so perhaps

```
$ diff color.sty~ color.sty
96,102c96,103
< \def\@declaredcolor#1{%
<   \@ifundefined{\string\color @#1}%
<     {\c@lor@error{`#1'}}%
<     {\expandafter\let\expandafter\current@color
<      \csname\string\color @#1\endcsname
<      \set@color}%
<   \ignorespaces}
---
> {\catcode`|=0 \catcode`\\=12 %
> |gdef|@declaredcolor#1{%
>   |@ifundefined{\color@#1}%
>     {|c@lor@error{`#1'}}%
>     {|expandafter|let|expandafter|current@color
>      |csname \color@#1|endcsname
>      |set@color}%
>   |ignorespaces}}
```

For `xcolor` needs a bit more as with or without that change you get 

```
l.2 g
     def @abspage@last{1}
```

while readung the aux file back

**Comment by PhelypeOleinik** [comment]
Defining
```latex
\cs_new:Npn \XC@string { \c_backslash_str \cs_to_str:N }
```
then replacing pretty much every occurrence of `\string` by `\XC@string` seems to work on `xcolor`.

**Comment by davidcarlisle** [comment]
@PhelypeOleinik  yes or use the existing `\@backslashchar` as its 2e-style is what I was goung to suggest. (Perhaps use that as well for `color`  rather than a catcode 12 `\ `  suggested above as it saves having to make a local catcode 0 character even though it costs an expansion on each use)
