### ISSUE TITLE
babel: \begin{otherlanguage*} behaves differently to \foreignlanguage in lists with bidi

### ISSUE THREAD

**Issue by dcpurton** [latex3/latex2e#67]
## Brief outline of the bug

The `babel` documentation states that `\begin{otherlanguage*}` is the same as `\foreignlanguage` but as an environment (§ 1.8). However, when the package option `bidi=basic` or `bidi=basic-r` is set, the behaviour is different in a list environment.

## Minimal example showing the bug

This MWE requires `fontspec` and a font with Hebrew characters (Free Serif in this example) in order to demonstrate the problem.

The `layout=lists` option does not make a difference, but the `babel` manual specifies that it is required for multilingual documents with `lualatex`.

Compile with `lualatex`.

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[nil,bidi=basic,layout=lists]{babel}
\babelprovide[import=he]{hebrew}
\babelprovide[import=en,main]{english}
\babelfont{rm}{Free Serif}
\begin{document}
\begin{enumerate}
  \item \foreignlanguage{hebrew}{שלום.}
  \item \begin{otherlanguage*}{hebrew}שלום.\end{otherlanguage*}
  \item Hello.
\end{enumerate}
\selectlanguage{hebrew}
\begin{enumerate}
  \item \foreignlanguage{english}{Hello.}
  \item \begin{otherlanguage*}{english}Hello.\end{otherlanguage*}
  \item שלום.
\end{enumerate}
\end{document}
```

## Log file (required) and possibly PDF file  

[bidi_lists_otherlanguagestar.log](https://github.com/latex3/latex2e/files/2281029/bidi_lists_otherlanguagestar.log)

[bidi_lists_otherlanguagestar.pdf](https://github.com/latex3/latex2e/files/2281030/bidi_lists_otherlanguagestar.pdf)

**Comment by jbezos** [comment]
It used to behave as described, but unfortunately `\foreignlanguage` didn't enter in h mode and therefore the direction was set at the wrong place. So, when I introduced the `bidi` option I had to make it a ”text macro” (v 3.11), with a `\leavemode` implicit, which won't make sense in `otherlanguage*`.

For backwards compatibility it's done only with the option `bidi`. It's documented later, but I forgot to modify this section. I'll point this out in the next release (next week, I hope). Those things will be sorted out with the introduction of a new user interface (see the wiki page for further info: https://github.com/latex3/latex2e/wiki/Babel:-current-work ).

Just add `\leavevmode`. BTW, you may want to move the dot outside the macro/environment.
