### ISSUE TITLE
\AddToHook error with latex-dev 2021/11/15 pre-release-2 and latexrelease 2021/06/01

### ISSUE THREAD

**Issue by h20y6m** [latex3/latex2e#675]
## Brief outline of the bug

With latex-dev 2021/11/15 pre-release-2 and latexrelease 2021/06/01,
using `\AddToHook` with a generic hook gives an error.

```
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.4 \AddToHook{env/quote/before}{}

?
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\RequirePackage[2021/06/01]{latexrelease}
\documentclass{article}
\AddToHook{env/quote/before}{}
\begin{document}
\end{document}
```

## Log file (required) and possibly PDF file  

[rollback-error.log](https://github.com/latex3/latex2e/files/7229042/rollback-error.log)

**Comment by FrankMittelbach** [comment]
looks like a bug in the rollback code for sure, thanks.
