### ISSUE TITLE
ltnews: markup package names more consistently

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#679]
## Brief outline of the bug

The easy part: Some package names in sectioning titles of ltnews28 & 29 are not marked-up with `\pkg{...}`:
```bash
$ git checkout develop
$ grep -rni 'Changes to packages in the' base/doc | head -6
base/doc/ltnews28.tex:294:\section{Changes to packages in the tools category}
base/doc/ltnews28.tex:320:\section{Changes to packages in the amsmath category}
base/doc/ltnews29.tex:382:\section{Changes to packages in the \pkg{tools} category}
base/doc/ltnews29.tex:454:\section{Changes to packages in the amsmath category}
base/doc/ltnews34.tex:620:\section{Changes to packages in the \pkg{graphics} category}
base/doc/ltnews34.tex:632:\section{Changes to packages in the \pkg{tools} category}
```

The more complex part: Taking `amsmath` as an example, it is marked-up in various ways:
```
\package{amsmath}
\pkg{amsmath}
\textsf{amsmath}
\texttt{amsmath}
amsmath % without any markup
```

**Comment by FrankMittelbach** [comment]
@muzimuzhi if you care to take the time to prepare a pull request I'm happy to take it. Those files have been written at different times by different people and often but not always a skeleton was copied from an earlier version (which explains why the amsmath section looks like it does, say).

**Comment by car222222** [comment]
@muzimuzhi Agreed, but any changes needed in ltnews34 (the latest) should please be reported separately since we are still working on the final version.

**Comment by FrankMittelbach** [comment]
went over ltnewsXX and normalized somewhat but may have missed one or the other place. @muzimuzhi if you want to suggest further updates please make a pull request, that would help. I kept a bunch of `\textsf`deliberately when they indicate bundles rather than packages.
