### ISSUE TITLE
latexrelease.sty fails to roll forward

### ISSUE THREAD

**Issue by jweening** [latex3/latex2e#68]
## Brief outline of the bug
Using latexrelease.sty to roll forward from an old LaTeX kernel sometimes fails.  The following example rolls forward correctly when run with latexrelease.sty version 2018-04-01 and the 2017-04-15 kernel (TeX Live 2017).  But when run with latexrelease.sty version 2018-04-01 and the 2016-03-31 kernel (TeX Live 2016), it fails with the error:

```
! Undefined control sequence.
\@outputpage ...nguage \document@default@language
                                                  \@resetactivechars \global...
l.6 \end{document}
```

The problem seems to be that the line

`\let\document@default@language\m@ne`

which was added to the kernel on 2017-04-15, is not provided in latexrelease.sty.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\RequirePackage[2018/04/01]{latexrelease}
\documentclass{article}
\begin{document}
Some text.
\end{document}
```

## Log file (required) and possibly PDF file  

Unable to provide.

**Comment by FrankMittelbach** [comment]
automatic testing of roll forward is rather difficult, so that kind of issue may unfortunately happen once in a while.

**Comment by aminophen** [comment]
I guess similar issue can happen for `\l@nohyphenation`, which is used in \verb.
