### ISSUE TITLE
Typo in multicol environment PDF. \newcolumn feature suggestion.

### ISSUE THREAD

**Issue by vansnyder** [latex3/latex2e#682]

**Comment by vansnyder** [comment]
In the text between lines 197 and 198 of the code, as described on page 12 in multicol.pdf, "bahve" should be "behave".

The code for line 236 on page 14 is an overfull box.

**Comment by zauguin** [comment]
> In the text between lines 197 and 198 of the code, as described on page 12 in multicol.pdf, "bahve" should be "behave".

This has been fixed in https://github.com/latex3/latex2e/commit/198fa229.

Line 236 looks fine to me, but there are some pretty bad boxes especially on page 13

**Comment by FrankMittelbach** [comment]
Mr Snyder, I fear there are a lot of typos in that document, but that is not one of them or rather not any longer (since about 2 years). What is is the  feature suggestion that you mention in the title? There is a `\columnbreak` command which may be what you are looking for.

**Comment by vansnyder** [comment]
On Fri, 2021-10-01 at 16:23 -0700, Frank Mittelbach wrote:
> Mr Snyder, I fear there are a lot of typos in that document, but that
> is not one of them or rather not any longer (since about 2 years).
> What is is the feature suggestion that you mention in the title?
> There is a \columnbreak command which may be what you are looking
> for.

I tried \columnbreak but it behaved more like \newpage than \pagebreak:
It left white space at the bottom of the column, instead of balancing
the columns. And it doesn't accept a "priority" option (a digit in
square brackets). Maybe I just used it wrongly.

**Comment by FrankMittelbach** [comment]
It is actually more the other way around, it behaves like `\pagebreak` and there is no `\newcolumn` (which I might consider adding, though in vertical mode you should get it through `\vfill\columnbreak`). See the comments in #683.

**Comment by FrankMittelbach** [comment]
You might want to try out the following  and tell me if that is what you are looking for:

```
\usepackage{multicol}
\makeatletter
  \newcommand\newcolumn{%
        \ifnum\col@number<\tw@
        \PackageError{multicol}%
         {\noexpand\newcolumn outside multicols}%
         {This command can only be used within
          a multicols or multicols* environment.}%
       \else
         \ifvmode
          \nobreak\vfill\penalty -\@Mv\relax
        \else
          \@bsphack
          \vadjust{\nobreak\vfill\kern\z@\penalty -\@Mv\relax}%
          \@esphack
        \fi
       \fi}
  \renewcommand\columnbreak[1][4]{%
        \ifnum\col@number<\tw@
        \PackageError{multicol}%
         {\noexpand\newcolumn outside multicols}%
         {This command can only be used within
          a multicols or multicols* environment.}%
         \else
         \edef\mc@break@pen
             {-\ifcase#1\@m\or 3333\or 6666\or 9999\else\@Mv\fi\relax}%
         \ifvmode
          \penalty \mc@break@pen
        \else
          \@bsphack
          \vadjust{\penalty \mc@break@pen}%
          \@esphack
        \fi
       \fi}
\makeatother
```
