### ISSUE TITLE
latex.dtx doc references

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#685]
In classes.dtx I see the statement:
```
%    The pagestyles \pstyle{empty} and \pstyle{plain} are defined in
%    \file{latex.dtx}.
```

But in fact the definitions are in ltpage.dtx, and there is no latex.dtx, as far as I can see.

grep shows that latex.dtx, latex.tex, lplain.tex are used in a variety of places. I didn't check systematically, but looks like some need similar updates. FWIW ...

**Comment by car222222** [comment]
Thanks for pointing this out.  

So far I checked only source2e for these old references, I found just one that probably needs some kind of update: the start of "The Code" refers to two of these files.

**Comment by FrankMittelbach** [comment]
sigh :-) that comes from "historical software" being kept alive. I found a couple of places, but nothing for lplain that should be changed (references there in change entries that the file name was changed from lplain ...)
