### ISSUE TITLE
\verb* cannot produce visible space with XeLaTeX

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#69]
## Brief outline of the bug
As firstly posted in [tex.sc](https://tex.stackexchange.com/q/448734/79060), `\verb*` cannot produce visible space with XeLaTeX. Loading package `fontspec` will fix this problem.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass{minimal}
\begin{document}
\verb*|x x|
\end{document}
```

## Log file (required) and possibly PDF file  
[verbatim.log](https://github.com/latex3/latex2e/files/2342690/verbatim.log)
[verbatim.pdf](https://github.com/latex3/latex2e/files/2342691/verbatim.pdf)

**Comment by davidcarlisle** [comment]
Thanks for the report, we will do something, and report back here, there
are a few options for how to fix this internally, in addition to the method
fontspec uses.

David
