### ISSUE TITLE
Support multiple columns in `gather` and `gather*`

### ISSUE THREAD

**Issue by dimitriye98** [latex3/latex2e#690]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath}

\begin{document}

  \begin{gather}
    a = b & c = d\\
    e = f & g = h
  \end{gather}
  
\end{document}
```

Results in a compilation error (as columns are unsupported in gather).

## Minimal example showing the desired new behaviour

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{amsmath,mathtools}

\begin{document}

  \begin{align}
    \mathclap{a = b} && \mathclap{c = d}\\
    \mathclap{e = f} && \mathclap{g = h}
  \end{align}
  
\end{document}
```

This roughly emulates the behavior I'd like to see with the nonfunctional code above, though it doesn't gracefully handle overly wide columns as the align environment does.

Since `&` doesn't do anything in existing gather environments (indeed it results in a compilation error), I don't believe the feature would break existing code, and it'd be a useful tool. Further, it seems an intuitive extension. When I first came into an occasion where it'd be useful, I tried to use it without even thinking it might not be implemented, and only realized I'd have to work around its nonexistence when the code failed to compile.

**Comment by car222222** [comment]
Generalising somewhat: is it useful to view this as a special case of a more general math display that consists of just an array environment, but with each row of the array labelled using the style and counter used by "equation-numbering"?

**Comment by davidcarlisle** [comment]
@dimitriye98 we looked at this and while the desired layout is not unreasonable we don't think adding it to `gather` would be the right implementation, `gather` has always been documented as an unaligned display so adding alignment  now would be counter-intuitive.  As discussed above there are solutions using eqbox or IEEEtrantools so we will close here.
