### ISSUE TITLE
bm silently switches to poor man’s bold

### ISSUE THREAD

**Issue by oliviercailloux** [latex3/latex2e#71]
## Brief outline of the bug
When facing a character for which no bold equivalent is know, `bm` silently fails back to poor man’s bold (pmb) approach, as documented in the package.

This is at odd with LaTeX’s general approach of providing high quality output or warning the user when it can’t. I would rather expect to be at least provided with an option that I can use to be warned when `bm` switches to pmb, so that I can take corrective action.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
%\usepackage{mathrsfs}
\usepackage{bm}
\begin{document}
{\mathversion{bold}$\sum$}
\bm{$\sum$}
%$\bm{\mathscr{A}}$
\end{document}
```

## Log file
[min.log](https://github.com/latex3/latex2e/files/2372170/min.log)

## And beyond
A similar comment holds when `bm` fails to replace the character with a bold one altogether (see the code that is commented out). Note that the fact that this second example requires an external package is only because I use it to illustrate a case where `bm` seems to silently give up trying to produce a bold character. The limitation itself is intrinsic to `bm`.

**Comment by davidcarlisle** [comment]
yes we have more memory available now for informative messages than we did back then:-)

For the first could change line 66 of bm something like
```

   \ifx\@tempa\@tempb
       \PackageWarningNoLine{bm}{PMB ALERT! \expandafter\strip@prefix\meaning\@tempa}%
      \bm@define\m@ne
    \else
```

which would warn if the font set up made pmb possible (even if no use of `\bm` in the document took that path)  Alternatively could add the warning to the definition of  `\bm@pmb` so the warning was just if the poor mans bold was used, but in that case it would probably need some kind of global flag to only warn on first use?  Not sure which is best??

The mathrsfs one I'd need to look at more closely. I would have said that it was user error: bm should be loaded after any math fonts are set up, so it "knows" about them, but actually whichever order you load the bm and mathrsfs packages, it ends up doing `{\boldmath $\mathrsfs{A}$}` which is the normal weight A. I would have expected it to detect that the bold math version font was the same and choose the pmb route, but apparently not.

**Comment by FrankMittelbach** [comment]
I would think that whatever gets implemented should be implemented with some option to turn it off or or (or even into an error). After all, after visual verification the conclusion may be that all is fine ( or the best that is possible) and then you may want the warnings to be silenced. In the opposite direction you may want each time an error to have a clear stop at the point of the problem (maybe).

**Comment by davidcarlisle** [comment]
oh yes sorry I meant to say that, probably use \bm@info{..} rather than `\PackageWarning` and then options to make that do nothing or write to the log or write to the terminal etc... I just did the simplest thing for the initial test.

**Comment by oliviercailloux** [comment]
- What do you mean with “warn if the font set up made pmb possible (even if no use of \bm in the document took that path)”? Is there a way to avoid this? I mean that in my understanding, pmb will be used whenever some symbol has no equivalent in bold, and I suppose, considering the vast diversity of symbols available to a normal latex document, that there will always be at least one symbol with no proper bold equivalent. Am I mistaken?

- I had indeed observed that no bold mathscr occurred when loading `mathrsfs` before `bm`. My mistake, my example had an incorrect loading order (now corrected).

**Comment by davidcarlisle** [comment]
the number of symbols isn't so important, it is the number of fonts and tex can have at most 16 in any given math expression, bm interrogates these families in the normal and bold math version and matches up the corresponding fonts. At the place where I suggested adding the warning in the comment above, it is the point at which it has detected that the same font is assigned to both math versions, so it specifies poor mans bold for that slot as the bold math version doesn't have a corresponding bold font. The other place the warning could be used is if pmb is actually used. That is, if a symbol from one of the fonts assigned to poor mans bold is used in the document. I suspect that you wouldn't normally want to be warned about every use, so if that route is taken the command may need to redefine itself not to warn after the first time, I'll see what I can do.

**Comment by oliviercailloux** [comment]
Sorry if I misunderstood something, but I am still unsure the warning “possible fallback to pmb” would be useful, as I am unsure it is possible to avoid it. In my example that triggered this bug report, as I understand, the warning would be triggered, as $\sum$ in Computer Roman has no bold $\sum$ symbol, isn’t it? (At least I thought this is what is shown by `{\mathversion{bold}$\sum$}` not producing a bold `\sum`.) How could I modify this example to avoid being warned? AFAIK, there simply are no bold versions available (at least, within open source fonts) for fonts commonly used in LaTeX. But if I am wrong, I will be happy to learn it.

**Comment by davidcarlisle** [comment]
well I thought you wanted the package to warn. Whether or not there is a bold font that matches the existing document fonts or whether you need to change design or live with poor man's bold is not something it can really determine.

As it happens there is a bold extension font based on the cm sources on ctan, although it's not used by default.  Seems to be also available as type1 scalable font:

/usr/local/texlive/2018/texmf-dist/fonts/source/public/cm-mf-extra-bold/cmexb10.mf
/usr/local/texlive/2018/texmf-dist/fonts/tfm/public/cmexb/cmexb10.tfm
/usr/local/texlive/2018/texmf-dist/fonts/type1/public/cmexb/cmexb10.pfb

so with the warning added as suggested above the following document would give a warning without the declarations in the preamble, but with, the warning goes and you get a real bold summation

```

\documentclass{article}

\DeclareFontShape{OMX}{cmex}{bx}{n}{%
   <->sfixed*cmexb10%
   }{}
\SetSymbolFont{largesymbols}{bold}{OMX}{cmex}{bx}{n}
\usepackage{bm}
%\usepackage{mathrsfs}


\begin{document}
{\mathversion{bold}$\sum$}
$\sum \bm{\sum$}

%$\mathscr{A}\bm{\mathscr{A}}$
\end{document}
```

**Comment by oliviercailloux** [comment]
Yes, sure, I want the package to warn. What I had in mind originally was only one of your suggestion: warn when pmb is effectively used ([EFF]). I was just discussing another of your suggestions: warn if the set up is such that in principle pmb could be resorted to ([PRINC]). Now you have convinced me that both make sense. (Incidentally, thanks a lot for this information which I ignored and which generally [does not seem](https://tex.stackexchange.com/search?q=cmexb10) well known.)

I suggest by default a warn at first [EFF], and no warn for [PRINC].

Options should be available for configuring reaction to [PRINC] (warn / error / silence) and to [EFF] (warn each time / error each time / warn first time / error first time / silence).

Ideally, a special command “bm-but-ok-if-pmb” should be available for those cases where the author is okay for `bm` to use pmb at a specific place, but still wants to be warned about other uses, perhaps something like: `$\bm[allow-pmb]{\sum}$`.

**Comment by oliviercailloux** [comment]
Should I introduce a different bug report about `bm` not doing the right thing with `$\bm{\mathscr{A}}$` (together with `mathrsfs`)?

**Comment by oliviercailloux** [comment]
Dear bot,

I would prefer this not to be closed.

Hoping to receive your consideration.

**Comment by davidcarlisle** [comment]
@oliviercailloux  sorry about that. As you may see I removed the  stale label a while ago.  We are trialling the bot so last night many old issues got flagged. We had in fact disabled auto-closure but it went out with the default message initially.  Hard to get a new tool completely configured the first time out:-)

**Comment by oliviercailloux** [comment]
Sure, no worries. I thought it was a good opportunity for me to learn to argue with a bot (possibly a good skill to have in the world that comes).

**Comment by davidcarlisle** [comment]
I added a `[nopmb]` option so that you can suppress overprinting a warning is given on setup if the bold math and normal math font is the same , producing different text if pmb will be used. options `silent`, `info` and `warn` control whether the warnings are output to terninal and/or log.

default behaviour is to use pmb (as before) but have an info level warning to the log (new)

I think the behaviour with rsfs is as expected, math alphabets are not directly handled by bm they are always essentially handled by \boldmath (as the math fam assignments are dynamic) so you get essentially \boldsymbol{\mathrsfs{A}} which gives you the same A as the non bold.  

there is an oddidty here that the mathrsfs package sets the font up as as symbol font rather than a math alphabet which confuses the issue. Needs a bit more onvestigation. Also no user level documentatio in the package yet
