### ISSUE TITLE
provide xfp commands as part of the kernel and retire xfp

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#711]
## Minimal example showing the desired behaviour

Be able to use the expandable `\fpeval` and `\inteval` commands directly without the need to load this mini package.
Additionally maybe also offer `\dimeval` and `\skipeval` as alternate names for L3 programming layer functions `\dim_eval:n` and`\skip_eval:n`.

**Comment by car222222** [comment]
Not much can be done I guess, but "inteval" looks too much like a typo for "interval"
