### ISSUE TITLE
`amsmath`: `\shoveleft` triggers expansion and swallows extra stuff

### ISSUE THREAD

**Issue by RuixiZhang42** [latex3/latex2e#716]
## Brief outline of the bug

For some reasons `\shoveleft` decides to use `\hskip.5\wd\@ne \hskip-.5\wdz@`, when it should have been `\kern.5\wd\@ne \kern-.5\wdz@`. Otherwise, TeX continues expansion to search for keywords `plus` and `minus`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{amsmath}

\newcommand*\extrastuff{plus 5cm minus 2in }

\begin{document}
\begin{multline}
ABCDEFG\\
\shoveleft{plus 5cm minus 2in swallowed}\\
\shoveleft{\extrastuff expanded\ and\ swallowed}\\
=ABCDEFG
\end{multline}
\end{document}
```

**Comment by davidcarlisle** [comment]
Thanks for the report: a missing `\relax` is allowing the `\hskip` to absobe the glue specification.

```
        \def\shoveleft#1{%
            \setboxz@h{$\m@th\displaystyle{}#1$}%
            \setbox\@ne\hbox{$\m@th\displaystyle#1$}%
            \hfilneg
            \hskip\multlinegap
            \hskip.5\wd\@ne
            \hskip-.5\wdz@\relax
                                   %%%%%%
            #1%
        }
````

**Comment by RuixiZhang42** [comment]
@davidcarlisle 

> [A] missing `\relax` is allowing the `\hskip` to absorb the glue specification.

I&rsquo;ve seen `\hskip<dimen>` in various places (including the kernel). Are there any advantages in using `\hskip<dimen>` over `\kern<dimen>`?

In this case, we explicitly know the quantity following `\hskip` is a `<dimen>` not a `<glue>`; we also explicitly know we&rsquo;re already in horizontal/math mode. So `\kern<dimen>` feels more natural to me. Also, do you think the `\relax` would interfere with the spacing of `#1`? (probably not?)

**Comment by FrankMittelbach** [comment]
> I’ve seen `\hskip<dimen>` in various places (including the kernel). Are there any advantages in using `\hskip<dimen>` over `\kern<dimen>`?

there are places where LaTeX wants to remove a "glue" it always keeps kerns so that something like `\hspace*` can can do glue + zero kern to hide a dimen or a skip. In this particular case probably doesn't matter but applying this general rule is sound as that means that macros doing space manipulation have less to worry about. Otherwise such code would need to handle many more cases.

**Comment by RuixiZhang42** [comment]
@FrankMittelbach I see. Thanks for explaining.

@davidcarlisle This is the spacing issue I was talking about (but it seems like a separate bug? Let me know if I should open a separate issue):
```latex
\documentclass{article}
\usepackage{amsmath}

\medmuskip=10mu % exaggerate spacing

\begin{document}
\noindent
This is clearly wrong:
\begin{multline}
+ABCDEFG\quad\text{(that should be a unary plus!)}\\
\shoveleft{+ABCDEFG\quad\text{(binary plus? makes sense from breaking long expr.\ I guess)}}\\
=2ABCDEFG
\end{multline}
The following still seems a bit off:
\begin{multline}
{+}ABCDEFG\quad\text{(that should be a unary plus!)}\\
\shoveleft{+ABCDEFG\quad\text{(binary plus? makes sense from breaking long expr.\ I guess)}}\\
=2ABCDEFG
\end{multline}
\end{document}
```
