### ISSUE TITLE
Missing documentation for \DeclareEncodingSubset

### ISSUE THREAD

**Issue by dr-scsi** [latex3/latex2e#717]
## Brief outline of the bug

I can't find a description about `\DeclareEncodingSubset` in the doc's, only in ltnews33.  Should this be added to fntguide?  There is a section covering addition of `textcomp` to LaTeX kernel.

**Comment by FrankMittelbach** [comment]
might be useful. Would you be willing to make an update to fntguide and a pull request? Thanks.

**Comment by dr-scsi** [comment]
I knew you would ask 😃   Please see #720.

**Comment by FrankMittelbach** [comment]
> I knew you would ask 😃

well the day has only 24 hours and to improve on that granularity it does need help :-)  --- thanks

**Comment by FrankMittelbach** [comment]
well, I think I confused myself and my rewording was just making it worse (it was technically correct in lttextcomp) -- I hope it is now right :-(

**Comment by dr-scsi** [comment]
Thanks, LGTM now, glad that we have this sorted it out.  Since you've prettified `fntguide.tex`, I also have a suggestion.  Please consider merging PR #722.

**Comment by dr-scsi** [comment]
@FrankMittelbach - Sorry to bug you again, but I had a closer look and I want to double check.  Does this part
https://github.com/latex3/latex2e/blob/203dc2c2465e5c54f00675fd879ebf7b4117197e/base/doc/fntguide.tex#L2265-L2271

fit to this example?
https://github.com/latex3/latex2e/blob/203dc2c2465e5c54f00675fd879ebf7b4117197e/base/doc/fntguide.tex#L2273-L2280

Maybe it's only me confused (again), but the way I read the first block, with
```
\DeclareEncodingSubset{TS1}{foo}{5} 
```
the symbols in sub-encoding 5 are available.  Does this fit to your comment [here](https://github.com/latex3/latex2e/pull/720#discussion_r764922809_):

> that's the wrong way around \textflorin has encoding 6 which means it is available in 0-5

**Comment by FrankMittelbach** [comment]
yes your text in the example is wrong I just noticed that when I was trying to do somehting about the float positions. it should say "and the ones made unavailable in encodings 6-9  (tables -subst-...6 -9)" ... new version coming up soon :-(

**Comment by dr-scsi** [comment]
Thanks for the fix.  I admit it is still hard to grasp what's happening at the first sight when one reads:

> Thus, the symbols that are available in sub-encoding $x$ are the symbols
> in table~\ref{tab:ts1-subset-always} (always available) and the symbols
> that only become unavailable in sub-encodings $> x$.

But I think we have it now.

I think the next step would be to use the `caption` package and turn the table captions into top caption, maybe with the next wind

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Thanks for the fix. I admit it is still hard to grasp what's happening at the first sight when one reads:
> 
> > Thus, the symbols that are available in sub-encoding $x$ are the symbols
> > in table~\ref{tab:ts1-subset-always} (always available) and the symbols
> > that only become unavailable in sub-encodings $> x$.
> 
> But I think we have it now.

there are better representations possible, but I'm not trying to spend time on that. Basically you folled the implementation logic, which makes the tables difficult to parse. Easier would be (imho) to just have the single table I had originally and just mark for each command there where it is available, e.g.,
```
 \textflorin\textsuperscript{(0--5)}
```
or from which point onwards it is no longer available. But as I said not going to touch this now that it is (I think) finally correct again, even if somewhat difficult to read).

> I think the next step would be to use the `caption` package and turn the table captions into top caption, maybe with the next wind :-)

thank you no  not any time soon. This is cost me too much time already and it is of interest to only very very few people.

**Comment by dr-scsi** [comment]
@FrankMittelbach Reg. better representations:
> Easier would be (imho) to just have the single table I had originally and just mark for each command there where it is available, e.g.,  
` \textflorin\textsuperscript{(0--5)}`

I tried that in the first place but wasn't happy with it, so I took the other route.

> thank you no not any time soon. This has cost me too much time already and it is of interest to only very very few people.

No worries, it took me also a lot of time where I thought it would be done with couple of paragraphs.  But here we are.
