### ISSUE TITLE
color leak in new array m code

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#72]
## Brief outline of the bug

color leaks due to the box re-arrangement in teh new `m` code corrupting the color stack

https://tex.stackexchange.com/questions/450726/different-behaviour-of-color-in-tabular-m-and-tabular-p/450729#450729
[aa887.log](https://github.com/latex3/latex2e/files/2379731/aa887.log)

## Minimal example showing the bug

```latex
\RequirePackage{latexbug} 
\documentclass[10pt]{article}

\usepackage{color}
\usepackage{array}%[=2016-10-06]

\begin{document}
    \begin{tabular}{|*{3}{>{\centering}p{1cm}|}}
        \hline \leavevmode\color{red}A&B&C\tabularnewline \hline
    \end{tabular}

    \begin{tabular}{|*{3}{>{\centering}m{1cm}|}}
        \hline \leavevmode\color{blue}A&B&C\tabularnewline \hline
    \end{tabular}

    Some blablah...
\end{document}
```

**Comment by FrankMittelbach** [comment]
added a color group since `$\vcenter ...$` is no longer used
