### ISSUE TITLE
Support for Croatian Unicode digraph letters within (at least) T1

### ISSUE THREAD

**Issue by ivankokan** [latex3/latex2e#723]
## Brief outline of the enhancement

It started here: https://tex.stackexchange.com/questions/625565/which-mappings-are-used-if-glyphtounicode-pdfgentounicode-are-not-used.

Croatian Latin alphabet (aka Gaj's Latin alphabet) contains three digraph letters, here listed in all Unicode variants:
```
Ǆ ǅ ǆ Ǉ ǈ ǉ Ǌ ǋ ǌ
```

**Truly the letters, not ligatures.**

Historically speaking, they are commonly typed as two consecutive characters they "consist of" (since Croatian Latin keyboard layout does not have special slots for them, compared to the Serbian Cyrillic keyboard layout which does have their Cyrillic equivalents which are never typed nor typeset as two consecutive characters) but this has few shortcomings.

Let me present by comparing `injekcija` (injection) and `iǌe` (frost):
- there are nine letters within `injekcija`, separate for `n` and `j`; but there are three letters within `iǌe`
- hyphenation: as mentioned before, we have three digraph **letters**, hence any word having e.g. `ǌ` must not be hyphenated in between those two glyphs.

Strictly speaking, these digraph letters must not be typeset as two consecutive characters - but even if they are, hyphenation must be suppressed. No special kerning is required. It seems that having the commented lines within the MWE in the distro would suffice.

Since T1 is commonly used font encoding when typesetting Croatian, it would be great to have support within the `t1enc.dfu` for the above-listed nine variants (just as for the other special Unicode cases listed there). Currently, using them yields an error.

I am not sure whether the proposal should be considered for other encodings as well. Why not, actually? Based on:
https://codepoints.net/U+01C4
https://codepoints.net/U+01C5
https://codepoints.net/U+01C6
https://codepoints.net/U+01C7
https://codepoints.net/U+01C8
https://codepoints.net/U+01C9
https://codepoints.net/U+01CA
https://codepoints.net/U+01CB
https://codepoints.net/U+01CC
...it seems that these Unicode code points are South-Slavic-specifics only.

## Minimal example showing the current behaviour

Does not compile.

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

% \DeclareUnicodeCharacter{01C4}{D\nobreak Ž}   % Ǆ
% \DeclareUnicodeCharacter{01C5}{D\nobreak ž}   % ǅ
% \DeclareUnicodeCharacter{01C6}{d\nobreak ž}   % ǆ
% \DeclareUnicodeCharacter{01C7}{L\nobreak J}   % Ǉ
% \DeclareUnicodeCharacter{01C8}{L\nobreak j}   % ǈ
% \DeclareUnicodeCharacter{01C9}{l\nobreak j}   % ǉ
% \DeclareUnicodeCharacter{01CA}{N\nobreak J}   % Ǌ
% \DeclareUnicodeCharacter{01CB}{N\nobreak j}   % ǋ
% \DeclareUnicodeCharacter{01CC}{n\nobreak j}   % ǌ


\begin{document}

Ǆ ǅ ǆ Ǉ ǈ ǉ Ǌ ǋ ǌ

\end{document}
```

## Minimal example showing the desired new behaviour

The same as before, but compilable after uncommenting the nine `\DeclareUnicodeCharacter...` statements.

**Comment by davidcarlisle** [comment]
Thanks for the report, I think if we add these you wouldn't want the `\nobreak` as that would suppress hyphenation in the rest of the word, and prevent words using these to take part in `\hyphenation{...}` rules.

Compare 

    \showhyphens{fo\nobreak otball football}

which shows

    [] \OT1/cmr/m/n/10 football foot-ball


with no hyphenation in the first form with a `\nobreak` between the `oo`.

You should be able to rely on the existing Croation hyphenation patterns to prevent hyphenation at these points.



You comment about no kerning required.

I asked about that in the original stackexchange post. The reasom I asked was that I was looking at your sample code with my browser using Consolas monospace font: this sets these characters as single width (so they look very kerned) as can be shown in this lualatex output where Consolos output is setting these to a single character width but Noto Monospace sets them to a double character width.

![image](https://user-images.githubusercontent.com/1268738/145533952-b47e02e4-a11d-409c-bfc5-af345f6122c8.png)


```
% fontspec.... \RequirePackage{latexbug}
\documentclass{article}
\tracinglostchars=2
\parindent=0pt

\ifx\Uchar\undefined
% pdftex
\usepackage[T1]{fontenc}

\DeclareUnicodeCharacter{01C4}{DŽ}%   Ǆ
\DeclareUnicodeCharacter{01C5}{Dž}%   ǅ
\DeclareUnicodeCharacter{01C6}{dž}%   ǆ
\DeclareUnicodeCharacter{01C7}{LJ}%   Ǉ
\DeclareUnicodeCharacter{01C8}{Lj}%   ǈ
\DeclareUnicodeCharacter{01C9}{lj}%   ǉ
\DeclareUnicodeCharacter{01CA}{NJ}%   Ǌ
\DeclareUnicodeCharacter{01CB}{Nj}%   ǋ
\DeclareUnicodeCharacter{01CC}{nj}%   ǌ

\else
% luatex/xetex
\usepackage{fontspec}
\setmainfont{Noto Serif}
\setmonofont{Noto Sans Mono}
\newfontfamily\consolas{consolas}
\fi

\begin{document}


Ǆ ǅ ǆ Ǉ ǈ ǉ Ǌ ǋ ǌ

\begin{verbatim}

01234567890123456789
Ǆ ǅ ǆ Ǉ ǈ ǉ Ǌ ǋ ǌ
\end{verbatim}

\ifx\Uchar\undefined\else

{\consolas 01234567890123456789}\\
{\consolas  ǅ ǆ Ǉ ǈ ǉ Ǌ ǋ ǌ}

\fi

\end{document}
```

So the pdflatex output here more closely resmbles Noto Sans Mono than consolas,  it would be somewhat tricky to try to force that these were single width in monospace, but I assume from your comment that that is OK? 

The pdflatex output from the above is

![image](https://user-images.githubusercontent.com/1268738/145535049-a9ce7a6a-3cf8-4dd2-b4a6-fcfe2a06f0d7.png)

**Comment by josephwright** [comment]
Doesn't current Unicode say that these are two letters in NFC?

**Comment by davidcarlisle** [comment]
@josephwright ah I didn't check that. Yes it does. UnicodeData.txt has them as eg `<compat> 0044 017D` so really legacy encoding compatibility entries, although that doesn't necessarily mean we shouldn't accept them as input I think. It means setting them double width should be fine though (and Consolas is probably wrong as you wouldn't expect the width to double  on NFC normalisation)

**Comment by davidcarlisle** [comment]
@josephwright actually https://www.unicode.org/Public/UCD/latest/ucd/DerivedNormalizationProps.txt  says these have ` Expands_On_NFKC`  but don't list them as having ` Expands_On_NFC`

**Comment by ivankokan** [comment]
> Thanks for the report, I think if we add these you wouldn't want the `\nobreak` as that would suppress hyphenation in the rest of the word, and prevent words using these to take part in `\hyphenation{...}` rules.
> 
> Compare
> 
> ```
> \showhyphens{fo\nobreak otball football}
> ```
> 
> which shows
> 
> ```
> [] \OT1/cmr/m/n/10 football foot-ball
> ```
> 
> with no hyphenation in the first form with a `\nobreak` between the `oo`.
> 
> You should be able to rely on the existing Croation hyphenation patterns to prevent hyphenation at these points.

Hi @davidcarlisle,

The `\nobreak` has been thoroughly discussed within `polyglossia` issue https://github.com/reutenauer/polyglossia/issues/497. From your example, I see that `\nobreak` should not be used. But is there some other way to "glue characters" and not mess up the hyphenation?

https://ctan.org/pkg/hrhyph

> Note that these patterns are no longer used by distributions; a version of the patterns, encoded in UTF-8, are the location of current development.

Can you please tell me where the patterns are versioned nowadays?

More on kerning later...

**Comment by davidcarlisle** [comment]
@ivankokan  I am not involved in any way with maintaining hyphenation patterns, although I wouldn't have expected anything needed at the macro layer for "glueing characters together" line breaking will only happen at points allowed by the patterns so you should be able to arrange patterns to avoid splitting these I would have thought, and as for `ff`  ligatures, you could use specific markup such as babel's `"-`  if you want break the digraph for some special purposes.

**Comment by u-fischer** [comment]
> The \nobreak has been thoroughly discussed within polyglossia issue
I didn't read the whole thread, but from what I saw, Yannis said the same as David: the hyphenation patterns should be used. 

> Can you please tell me where the patterns are versioned nowadays?

There is an author mail in hyph-hr.tex (in C:\texlive\2021\texmf-dist\tex\generic\hyph-utf8\patterns\tex). Beside this hyphenation is discussed at the mailing list https://tug.org/pipermail/tex-hyphen/.

**Comment by davidcarlisle** [comment]
@ivankokan  \patterns and \hyphenation in classic tex can only have letters so there is no box or penalty combination that you can use that will not prevent the ord taking part in `\hyphenation`.  You should simply ensure that (say) hyphenation between n and j is not allowed by the patterns, even if this misses a few hyphenation points in words wheer nj is not semantically a digraph in practice this is not a problem. The default US English hyphenation patterns, as discussed in the texbook, also miss some hyphenation points where the same spelling coul dhave different meansings and it was felt better to just be on the safe side and not hyphenate badly even if that misses a good hyphenation point.

**Comment by davidcarlisle** [comment]
@ivankokan  I just checked /usr/local/texlive/2021/texmf-dist/tex/generic/hyph-utf8/patterns/tex/hyph-hr.tex and as far as I can see there are no odd pattern values between any of the relevant pairs of letters so hyphenation should never break one of these pairs.

**Comment by ivankokan** [comment]
Hi again.

Kerning... Nothing special is required since the common way of typesetting mentioned letters is simply using two separate glyphs they consist of. I know there are (Croatian) font designers who deliver some specialties in this context (e.g. Nikola Đerek https://www.typotheque.com/fonts/marlene/light/glyphs) - but again, these are advanced stuff we do not need to handle here.

**Comment by ivankokan** [comment]
Back to hyphenation...

From #658 I see that `\ij`-family for OT1 is still defined as:
```latex
\DeclareTextCommand{\ij}{OT1}{%
  \nobreak\hskip\z@skip i\kern-0.02em\nobreak\hskip\z@skip j}
\DeclareTextCommand{\IJ}{OT1}{%
  \nobreak\hskip\z@skip I\kern-0.02em\nobreak\hskip\z@skip J}
```

What's the difference between existing `\nobreak` between `i` and `j`, and not-recommended `\nobreak` between e.g. `n` and `j` in the context of this issue?

**Comment by davidcarlisle** [comment]
@ivankokan  OT1 is the legacy 7-bit encoding which has no pre-composed accented characters, so hyphenation is generally not specifiable, The code you quote makes `\ij` a word boundary so any word containing that code will be hyphenated in OT1 as three words, the letters before i, i on its own and the following letters starting with j.  No `\patterns` can apply to `\ij`  if OT1 is used.

Conversely in T1 ij and IJ are distinguished characters and can take full part in hyphenation. The patterns used for dutch in pdflatex assume T1 encoding.

So the difference here would be that adding `\nobreak` here would prevent hyphenation being specified for words containing these characters in the T1 encoding that is used for Croatian patterns in pdftex.

**Comment by ivankokan** [comment]
Hi, I wanted to reflect on the following rules in **Serbian** language (T1 for its Latin script):

Правопис српскога језика, Матица српска, 2010. (измењено и допуњено, четврто издање)
https://jelenaradomir.files.wordpress.com/2016/08/pravopis-ms_2010.pdf

<img width="1233" height="322" alt="Image" src="https://github.com/user-attachments/assets/59d2747f-d6dd-44f2-a320-dc999f94c7a7" />

При размакнутом (спационираном) писању сва слова се једнако раздвајају (L j u b l j a n a а не Lj u b lj a n a). Ако се натписи (нпр. MENJAČNICA) пишу одозго надоле, NJ, LJ односно DŽ не треба да остану састављени, него друго слово долази испод првог.

Google Translate (a bit improved):
1) With an increased letter spacing (separated characters), all glyphs are equally separated (L j u b l j a n a, not Lj u b lj a n a).
2) If the inscriptions (e.g. MENJAČNICA) are written from top to bottom, NJ, LJ or DŽ should not remain composed, but the second letter comes below the first instead.

Hence, it should be this way:
- "L j u b l j a n a" in Latin (9 "slots") vs "Љ у б љ а н а" in Cyrillic (7 "slots")
- "M / E / N / J / A / Č / N / I / C / A" in Latin (10 rows) vs "М / Е / Њ / А / Ч / Н / И / Ц / А" in Cyrillic (9 rows)

So, if I understand it correctly, using U+01C4-U+01CC would generate wrong output for both 1) and 2); and should not be used in such situations?

(There are no such rules in Croatian, as far as I know. Personally speaking, I would "keep them together" in both cases.)
