### ISSUE TITLE
[amsmath] Loading amsmath (unexpectedly?) resets math operator font

### ISSUE THREAD

**Issue by ckosowsky** [latex3/latex2e#734]
## Brief outline of the bug

Loading amsmath unexpectedly resets the font for math operators to its kernel definition of ```\symoperators``` (Computer Modern Roman, defined on line 59 of ```fontmath.ltx```). Specifically, line 90 of ```amsopn.sty``` is
```latex
\def\operator@font{\mathgroup\symoperators}
```
which is exactly the same as line 522 of ```fontmath.ltx```. Is this deliberate? It seems strange to me and prevents any changes to the operator font before loading amsmath. I would suggest removing this line from ```amsopn.sty```.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

%% The following is the definition of \operator@font
%% (the instruction to typeset math operators in the
%% operator font)
\makeatletter
\show\operator@font

%% Suppose we load another font. This code will load
%% Computer Modern Dunhill. (But we could use any font--
%% this is just for reference.)
\DeclareFontFamily{OT1}{Dunhill}{}
\DeclareFontShape{OT1}{Dunhill}{m}{n}{<-> cmdunh10}{}
\DeclareSymbolFont{newoperators}{OT1}{Dunhill}{m}{n}

%% If we did everything right, \symnewoperators will
%% be a \char command corresponding to the math family
%% number of the newoperators symbol font
\show\symnewoperators

%% Redefine \operator@font to be the new symbol font
\def\operator@font{\mathgroup\symnewoperators}

%% Loading amsmath resets the definition, so the operators
%% are no longer typeset in Computer Modern Dunhill
\usepackage{amsmath}
\show\operator@font



\begin{document}

The following should be in Computer Modern Dunhill. Instead it's in Computer Modern Roman:
\[
\log(x).
\]

\bigskip

\def\operator@font{\mathgroup\symnewoperators}

If we redefine \verb|\operator@font| a second time, the operator will be in Computer Modern Dunhill:
\[
\log(x).
\]

\end{document}

```

## Log file (required) and possibly PDF file  

Log file: [ams-operator.log](https://github.com/latex3/latex2e/files/7738538/ams-operator.log)
PDF output: [ams-operator.pdf](https://github.com/latex3/latex2e/files/7738540/ams-operator.pdf)

**Comment by FrankMittelbach** [comment]
> which is exactly the same as line 522 of `fontmath.ltx`. Is this deliberate? It seems strange to me and prevents any changes to the operator font before loading amsmath. I would suggest removing this line from `amsopn.sty`.

Without having checked, I'm fairly sure that the definition from amsopn was first and got ported to latex.ltx as some point. But given that it is there for more than 14 years minimum ...
