### ISSUE TITLE
cs versions of \NewCommandCopy and related

### ISSUE THREAD

**Issue by bdtc** [latex3/latex2e#735]
## Brief outline of the enhancement

Add `\csNewCommandCopycs`, `\NewEnvironmentCopy`, etc. similar to etoolbox's `\csletcs`.

## Minimal example showing the desired new behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

% Any preamble code goes here

\newcommand*{\csNewCommandCopycs}[2]{%
    \expandafter\NewCommandCopy\csname#1\expandafter\endcsname%
        \csname#2\endcsname%
}

\newcommand*{\NewEnvironmentCopy}[2]{%
    \csNewCommandCopycs{#1}{#2}%
    \csNewCommandCopycs{end#1}{end#2}%
}

\csNewCommandCopycs{mytextit}{textit}

\NewEnvironmentCopy{mycenter}{center}


\begin{document}

% Demonstration of issue here

First.

\begin{mycenter}
\mytextit{Some centered italic text.}
\end{mycenter}

Last.
  
\end{document}
```

**Comment by FrankMittelbach** [comment]
We decided to provide a somewhat more general interface but offering a few CamelCase commands such `\ExpandNcc` for such cases that can then be used without introducing zillions of individual commands are each and every case.

What still needs a decision is if we want/should provide  `\NewEnvironmentCopy`.
