### ISSUE TITLE
Documentation for \NewCommandCopy, etc.

### ISSUE THREAD

**Issue by bdtc** [latex3/latex2e#736]
Consider adding user-level documentation for `\NewCommandCopy`, etc. to usrguide3: New LaTeX methods for authors.

**Comment by FrankMittelbach** [comment]
Brian, agreed, it should be documented there -- but we have limited resources so this will take time. However, I would be happy to receive a pull request  for  a suggested  documentation :-) which would certainly speed things up.

**Comment by PhelypeOleinik** [comment]
Isn't this already done in cdc831ca?

**Comment by FrankMittelbach** [comment]
> Isn't this already done in [cdc831c](https://github.com/latex3/latex2e/commit/cdc831ca47c09f59a0f2a43b785882c6fe010750)?

so it is, but that must have happened after -dev went to CTAN (it is not there if you do `texdoc usrguide3` which I guess both Brian and I did when checking. So this can get a fxied in label ... and closed next time around
