### ISSUE TITLE
Typo in `varioref`'s documentation

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#747]
https://github.com/latex3/latex2e/blob/c7ce5c12653100d7677362cabd27748cb3ab3de3/required/tools/varioref.dtx#L175-L176

Should be "It has" instead of "If has" (I wanted to pull a request but is discouraged by the team, and I fully understand why :)

**Comment by FrankMittelbach** [comment]
> Should be "It has" instead of "If has" (I wanted to pull a request but is discouraged by the team, and I fully understand why :)

So we do (for code changes). For simple and clear documentation fixes I'm happy to  take pull requests, provided
- they are against the development branch
- the package "date" but not the package "version" is changed alongside
In that case it would probably be helpful (in the future). I'll do this one now -- thanks

**Comment by FrankMittelbach** [comment]
did a spell check run and found many more (probably not all)

**Comment by dbitouze** [comment]
> For simple and clear documentation fixes I'm happy to take pull requests, provided
> 
>     * they are against the development branch
>     * the package "date" but not the package "version" is changed alongside
> 
> In that case it would probably be helpful (in the future). 

It is worth to mention this in the [CONTRIBUTING guide](https://github.com/latex3/latex2e/blob/develop/CONTRIBUTING.md): would have this be stipulated, I would have provided a pull request :smile:
