### ISSUE TITLE
extend \PassOptionsToPackage for rollback option?

### ISSUE THREAD

**Issue by schlcht** [latex3/latex2e#751]
## Brief outline of the enhancement

I wonder whether `\PassOptionsToPackage` and friends should be extended to accept a rollback option. For example, to load the old `doc` version in the dev branch, I now use this:

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\makeatletter
\AddToHook{package/doc/before}
 {\pkgcls@targetdate=1
  \def\pkgcls@targetlabel{v2}}
\makeatother
\documentclass{ltxdoc}
\stop
```

which seems rather clumsy. I would prefer something like

```latex
\PassOptionsToPackage[v2]{}{doc}
```

(or maybe the optional argument should go to the end?).

**Comment by FrankMittelbach** [comment]
We may need to provide something to help with such cases, but it isn't yet clear what the interface should be as it should be probably restricted to case like yours, ie where a class loads something and you want to see that rolled back. But it would probably be counterproductive if such an interface could be called from inside packages and then  basically resulting in a random situation in the preamble depending on which packages are loaded earlier. So I guess this needs some thoughts first.

**Comment by josephwright** [comment]
As @FrankMittelbach  says, the risk here is that if we provide an interface, we will see this 'stick'. Rollback is really intended for document authors, not within packages or classes. You have found a reasonable 'patch' approach for short-term fixes in the case of issues.
