### ISSUE TITLE
`\IfFileExists` returns incorrect result when a file is under a directory and its name contains non-BMP character.

### ISSUE THREAD

**Issue by JLHwung** [latex3/latex2e#753]
## Brief outline of the bug

`\IfFileExists` returns incorrect result when a file is under a directory and its name contains non-BMP character.

## Minimal example showing the bug

Create the following files:
```
mkdir a
touch a/$'\U10000'.tex
touch a/$'\U4e00'.tex
```

Compile with xelatex (I didn't test other TeX engines)
```latex
\RequirePackage{latexbug}
\documentclass{article}
\begin{document}
\IfFileExists{\detokenize{a/^^^^^^010000.tex}}{1}{0}
\IfFileExists{\detokenize{a/^^^^^^004e00.tex}}{1}{0}
\end{document}
```

## Log file (required) and possibly PDF file  

[bug.log](https://github.com/latex3/latex2e/files/7875602/bug.log)
[bug.pdf](https://github.com/latex3/latex2e/files/7875603/bug.pdf)

## Expected:

PDF shows `1 1`.

## Actual:

PDF shows `.tex” 0 1`.

## Other info
It works as expected when I place the files in the top level.

**Comment by u-fischer** [comment]
xetex can't input the file with the primitive \input either, so it is imho a problem of the binary.  With lualatex it works. pdflatex doesn't know the `^^^^^^`-notation, but `\IfFileExists{a/𐀀.tex}{1}{0}`  works.

**Comment by zauguin** [comment]
Technically XeTeX encodes filenames as [CESU-8](https://www.unicode.org/reports/tr26/) (UTF-8 but using surrogate pairs...) instead of UTF-8 (as assumed by basically all modern systems). CESU-8 and UTF-8 are compatible for BMP codepoints, but differ for other characters. Most likely this is a bug in XeTeX.

**Comment by JLHwung** [comment]
Thank you for triaging. I can confirm that it works as expected in LuaTeX.

I have reported this issue to XeTeX project: https://sourceforge.net/p/xetex/bugs/189/

Closing this issue as it can't be fixed on LaTeX side.
