### ISSUE TITLE
utf8.def sets some commands globally

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex2e#762]
## Brief outline of the bug

Unlike other encoding files utf8.def sets some commands globally. And this means that grouping `\inputencoding` (for example when using it the toc) doesn't work properly.

## Minimal example showing the bug

(the test file is ansinew encoded on my system, but one can also copy that into an utf8 encoded file, it only changes the actual message but shows the problem too). 

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{book}
\usepackage[latin9]{inputenc}

\begin{document}
\show ä
{\inputencoding{utf8}
 \inputencoding{latin9}
 \show ä
}
\show ä
\end{document}

```

The last `\show ä` then has still the utf8 definition:

~~~~
> ä=macro:
->\UTFviii@three@octets ä.
~~~~

## Log file (required) and possibly PDF file  

[test-ansi.log](https://github.com/latex3/latex2e/files/7950575/test-ansi.log)

**Comment by FrankMittelbach** [comment]
this should be fixed by now but I guess we should make a test file from the original problem
