### ISSUE TITLE
Provide a `\hfill*` (`\vfill*` ) macro which behaves as `\hspace*{\fill}` (`\vspace*{\fill}`)

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#763]
## Brief outline of the enhancement
It would be convenient (and natural?) to have a `\hfill*` (`\vfill*` ) macro which behaves as `\hspace*{\fill}` (`\vspace*{\fill}`).

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{document}
\hfill Foo\hfill

\hfill Bar\hspace*{\fill}
\newpage
\vfill Foo\vfill
\newpage
\vspace*{\fill}Bla\vfill
\end{document}
```

**Comment by FrankMittelbach** [comment]
Easy enough to do `\RenewDocumentCommand\hfill{s}{\IfBooleanTF#1{\hspace*}{\hspace}\fill}` in your document, but I don't think that we are going make kind of change so that `\hfill` and `\vfill` are no longer fast primitive operations.

**Comment by josephwright** [comment]
I was going to say `\hfill` isn't a LaTeX command, then I checked Lamport's book, and I see I'm wrong. He says

> The command `\hfill` is an abbreviation for `\hspace{\fill}`

which is an interesting if somewhat misleading take on it :)

**Comment by josephwright** [comment]
@dbitouze  Remember that the command isn't `\hspace*`, it's `\hspace` with a star after it, as `*` is not a letter.

**Comment by davidcarlisle** [comment]
On Fri, 28 Jan 2022 at 08:50, Denis Bitouzé ***@***.***>
wrote:

> I should have mentioned that I know it is possible (and, hopefully, now
> easy) for not so average document authors to do such a redefinition. But
> the point is, average users are often bitten by \hspace which "doesn't
> work" at line breaks and, once they are aware of \hspace*, they are often
> bitten by \hfill which "doesn't work" at line breaks; therefore,
> legitimately, try \hfill* and get very disappointed.
>
> I didn't mean to redefine \hfill and \vfill: I hoped it would have been
> possible to just define new \hfill* and \vfill*. Is it definitively
> impossible to define them without redefine \hfill and \vfill?
>

the input `\hfill*` is the same as `\hfill   *` like all `*`-forms it would
be implemented by `\hfill` looking ahead for a `*`.

**Comment by zauguin** [comment]
> so that `\hfill` and `\vfill` are no longer fast primitive operations.

Even ignoring the performance question I would expect that there are a number of documents around which have a * after \hfill and would therefore get broken by such a change. (E.g. the `reledmac` documentation)

**Comment by FrankMittelbach** [comment]
> > The command `\hfill` is an abbreviation for `\hspace{\fill}`
> 
> which is an interesting if somewhat misleading take on it :)

He says it is equivalent to that which is technically correct. He doesn't say how it is implemented.

Anyway, sorry Denis, but we aren't going to overwrite `\hfill` with a definition that I outlined above because a) performance and b) the problem of scanning ahead in mid-document where you might have `\hfill/vfill` followed by `*` to mean just that a star to be printed.
