### ISSUE TITLE
Single-line m cells don't align well with other cells when \arraystretch<1

### ISSUE THREAD

**Issue by lvjr** [latex3/latex2e#766]
## Brief outline of the bug

Single-line `m` cells don't align well with other cells when `\arraystretch<1`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{array}
\begin{document}

\def\arraystretch{2}
\begin{tabular}{|p{1cm}|m{1cm}|b{2cm}|}
\hline
Alpha & Beta & Gamma \\
\hline
\end{tabular} 2

\bigskip

\def\arraystretch{1}
\begin{tabular}{|p{1cm}|m{1cm}|b{2cm}|}
\hline
Alpha & Beta & Gamma \\
\hline
\end{tabular} 1

\bigskip

\def\arraystretch{0.5}
\begin{tabular}{|p{1cm}|m{1cm}|b{2cm}|}
\hline
Alpha & Beta & Gamma \\
\hline
\end{tabular} 0.5

\bigskip

\def\arraystretch{0}
\begin{tabular}{|p{1cm}|m{1cm}|b{2cm}|}
\hline
Alpha & Beta & Gamma \\
\hline
\end{tabular} 0

\end{document} 
```

![image](https://user-images.githubusercontent.com/4239949/151689728-0b74e999-6616-4886-9360-e6902c4bb91d.png)

**Comment by lvjr** [comment]
https://github.com/latex3/latex2e/blob/af41faa9ff60d338e585003001456c02bfa80d69/required/tools/array.dtx#L1728-L1738

If `\arraystretch<1`, is it better to compare `\ht\ar@mcellbox` with `\ht\strutbox`?

**Comment by FrankMittelbach** [comment]
keep open until released
