### ISSUE TITLE
Typos in the documentation of array package

### ISSUE THREAD

**Issue by lvjr** [latex3/latex2e#767]
In Table 2, I think `p-arg/t-arg/b-arg` should be  `m-arg/p-arg/b-arg` in the left column, and `p/t/b` should be `m/p/b` in the right column.

![image](https://user-images.githubusercontent.com/4239949/151692639-d907840c-59b6-4cee-8674-8ee49a7de2da.png)

**Comment by FrankMittelbach** [comment]
this must be wrong since the early nineties, thanks.
