### ISSUE TITLE
no font modifications allowed

### ISSUE THREAD

**Issue by lward77** [latex3/latex2e#77]
!! Please fill out all sections after reading CONTRIBUTING guidelines (and remove lines starting with !!)

## Brief outline of the bug
Just installed the latest PDFTeX and it no longer allows font changes in the LaTeX code window - even though the "source" "font" and "show fonts" tabs do their jobs, popping up a window showing the available fonts. But the window is inactive. I simply cannot change the font in the code window no matter what I try (e.g., edit fonts size, etc.). On my computer the default font is simply too small for comfort. But generally, why have such a menu command if it's not working?

## Minimal example showing the bug

no code example available because it is not a code issue - it is a gui issue.
[SCAIM talk.log](https://github.com/latex3/latex2e/files/2421819/SCAIM.talk.log)

## Log file (required) and possibly PDF file  

!! Use drag-and-drop  (remember: .log file is required) !!

**Comment by eg9** [comment]
At least you should have mentioned *what* GUI is involved.

However, this is out of the scope of the LaTeX team. Issues with GUI programs should be directed to their developers.
