### ISSUE TITLE
showkeys breaks with starred versions of \*ref{} macros (from hyperref)

### ISSUE THREAD

**Issue by Quoor8ee** [latex3/latex2e#771]
## Brief outline of the bug
The `showkeys` is intended to show the destination of `\ref{}` and friends, as in-place “flags” overlaid over the regular document, pinned at the position of the reference, and typeset in a verbatim style (tt font, insensitive to special characters in the label definition).

Now, `hyperref` brings starred version of the macros `\ref{}`, `\pageref{}`, `\autoref{}`, and `\autopageref{}`, which show up like the regular unstarred versions, but unlike these, they are not being linked by the hypertext magic of `hyperref`.

Apparently, `showkeys` does not handle these correctly: the “flag” appears, but it just contains the asterisk; the name of the label is just let in the token list and processed as if it were normal TeX text. This not only defeats the purpose of the reference, but also causes trouble (`! Missing $ inserted.`…) whenever the label name contains characters that are valid in a label name but not in LaTeX text (like underscores).

There is at least one case where the inclusion of `showkeys` breaks builds even without explicitly using the starred versions of the macros: `hyperref`'s definition of `\autopageref{}` already uses `\pageref*{}` internally. Hence just loading `showkeys` into an existing document that uses `\autopageref{}`, will bring up the issue.

**Expected behaviour:** `showkeys` should be aware of (i. e. check if) the reference macros are starred or not, and if they are, treat the actual label reference (not the `*`) as the cross-reference destination. Optional but recommended: replicate the intended starred-macro-means-no-link convention from `hyperref`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{hyperref}
\usepackage{showkeys}

\begin{document}
\section{Content}
Label with underscores in its name\label{existing_underscore_label}

\newpage
\section{References}
\verb$\ref{}$ works always: \ref{existing_underscore_label}

Explicit \verb$\ref*{}$ breaks with \verb$showkeys$: \ref*{existing_underscore_label}

Internal \verb$\pageref*{}$ within \verb$\autopageref{}$ breaks with \verb$showkeys$: \autopageref{existing_underscore_label}
\end{document}
```

## Log file (required) and possibly PDF file  
`pdflatex -interaction=nonstopmode mwe_showkeys_refstar`

texmf and binaries directly from TeX Live SVN repository revision 61733

[mwe_showkeys_refstar.log](https://github.com/latex3/latex2e/files/7978525/mwe_showkeys_refstar.log)
[mwe_showkeys_refstar.pdf](https://github.com/latex3/latex2e/files/7978527/mwe_showkeys_refstar.pdf)

**Comment by Quoor8ee** [comment]
Thanks! This is a viable workaround, at least for those who don't need `\autopageref{}` to display the target label, and only use `showkeys` for other purposes.

**Comment by FrankMittelbach** [comment]
Needs verification but the pull #803 shouldd resolve this problem once deployed.

**Comment by u-fischer** [comment]
The PR alone doesn't resolve everything (some of the starred refs get no flag). But together with the changes I added to hyperref it will work. 

![image](https://user-images.githubusercontent.com/4047173/163691427-72c30e43-0e87-4417-9e1f-620ce06d6851.png)

**Comment by FrankMittelbach** [comment]
> The PR alone doesn't resolve everything (some of the starred refs get no flag). But together with the changes I added to hyperref it will work.

true, but I was thinking of them as a union as they are bound to come both together.
