### ISSUE TITLE
\ProcessKeyOptions and \ProcessKeysOptions

### ISSUE THREAD

**Issue by lvjr** [latex3/latex2e#773]
`\ProcessKeyOptions` and `\ProcessKeysOptions`  look nearly the same, but have different argument types, which is a little weird and may confuse users. Is it possible to change the interfaces before the release? 

```latex
\IfFormatAtLeastTF { 2022-06-01 }
  { \ProcessKeyOptions [ siunitx ] }
  {
    \RequirePackage { l3keys2e }
    \ProcessKeysOptions { siunitx }
  }
```

**Comment by josephwright** [comment]
This is a deliberate decision. The new commands take the same approach as those for hooks, using `\@currname` if available. The team are still working on a few aspects, but I suspect this particular one will be staying as-is.

As the new commands also go with new non `expl3` key properties, I think it is likely that the code you've quoted is going to have only a short life: once the updated kernel is released, the easiest approach by far will be to simply require the new code.
