### ISSUE TITLE
[graphics] .tex file is found instead of graphics file if both are in `\input@path`

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/latex2e#776]
Reported [here](https://tex.stackexchange.com/q/630167/134574).

## Brief outline of the bug

If a call to `\includegraphics` asks for a file (say, `image`) without extension, and if both `folder-a/image.pdf` and `folder-b/image.tex` exist (both `folder-a` and `folder-b` in `\graphicspath`, but neither in a folder searched by kpse), then, because TeX implies `image.tex` from `image`, `folder-b/image.tex` is found at the time `\set@curr@path` is used to normalise the file name, and `folder-b` is fixed to the file name before `graphics` starts to search the known extensions, which is too early.

## Minimal example showing the bug

Given the following directory structure:

```none
.
├── folder-a
│   └── image.pdf
├── folder-b
│   └── image.tex
└── document.tex
```

and this `document.tex`:

```latex
\documentclass{article}
\usepackage{graphics}
\graphicspath{{./folder-a/}{./folder-b/}}
\begin{document}
\includegraphics{image}
\end{document}
```

results in the error

```none
! LaTeX Error: File `image' not found.
```

**Comment by u-fischer** [comment]
@PhelypeOleinik  the fix breaks the search for graphics without extensions in a folder for me. E.g. this here:

~~~~
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{figures/figure.pdf} %found

\includegraphics{figures/figure} % not found
\end{document}
~~~~

**Comment by FrankMittelbach** [comment]
I wonder if it wouldn't be better to keep the search simple and call that a feature and revert. If a '.tex' is found when no extension is given and both exist then you have to give the extension --- this is the odd case. That none are found if just a file with a graphics extension exists is certainly counter productive and I'm not sure it is worth supporting with some complicated mechanism.

**Comment by PhelypeOleinik** [comment]
Drat...

This could be fixed, for both cases, by using a non-searching version of `\set@curr@file` (which just clears `\input@path` before doing its thing).  I tested here and it seems to work.  Should I open a new issue, just push on top of this one, or completely revert?

**Comment by FrankMittelbach** [comment]
either or; ok to push on this one, and then merge again later, but I think we should only do it if it is not complicating the normal case --- otherwise I'm for calling it a feature. The file handling got quite slow already and by the end of the day it is an odd case which should not make every file reading slower.

**Comment by FrankMittelbach** [comment]
On the other hand if it takes some time, it would perhaps be nice to take it out of -dev (temporarily at least) as we use the repository  develp branch on the Companion Book and right now that fails to run.

**Comment by PhelypeOleinik** [comment]
I pushed a commit (99bd30c) that implements the proposed fix.  For some reason (probably because it's already merged) it doesn't show up in the PR page.

> but I think we should only do it if it is not complicating the normal case --- otherwise I'm for calling it a feature

Actually, in the worst case (`\graphicspath` not used), it performs exactly the same.  If `\graphicspath` is used, it is (a tiny tiny bit) faster than before.  Plus `\set@curr@path@nosearch` may be useful elsewhere (and further optimised, if needed).
