### ISSUE TITLE
background package needs firstaid

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#786]
Maybe the background package would be a candidate for firstaid? It doesn't work with
current latex, as far as I can tell. Output comes out starting in the footer, or something.

My searching did not turn up another way to do what it does so conveniently,
though I see there are related features of all kinds.

For what it's worth, I was wanting to do what's described here:
https://tex.stackexchange.com/questions/82206

## Minimal example showing the bug
Can't load latexbug since that refuses to run with a third-party package,
which is the point of my report.

```latex
\documentclass{article}
\usepackage{background}
\begin{document}
Hello.
\end{document}
```

## Transcript
```
Package everypage Warning: Functionality similar to this package has recently
(everypage)                been implemented in LaTeX. This package is now in
(everypage)                legacy status.
(everypage)                Please, don't use it in new documents and packages.
```

This gives me no clue as to how to not use it in my new document.

```
Package everypage Warning: You appear to be running a version of LaTeX
(everypage)                providing the new functionality.
(everypage)                Doing the best to deliver the original `everypage`
(everypage)                interface on top of it. Strict equivalence is
(everypage)                not possible, breakage may occur.
(everypage)                If truly needed, Use `everypage-1x` to force the
(everypage)                loading of an older code base.
```

After I copy background.sty to cwd and edit {everypage} to be {everypage-1x}, it runs without error (thanks for tht suggestion), but the output (of the example in the tex.sx item) starts the background in the middle of the text block and extending to the northeast corner of the paper (beyond the margins). 
Not usable.

Off to look for some other solution ...

**Comment by u-fischer** [comment]
I get the warning (a warning is not an error!) too but the example works fine for me in  a current (pretest) texlive.

Your descriptions sounds as if you didn't compile twice. That is necessary as the code is based on pdfsavepos.

**Comment by FrankMittelbach** [comment]
As to including something into firstaid: first aid is there to fix "broken" packages, it makes LaTeX for every user slower (regardless of whether or not that package is loaded). In this case background loads everypage and the developer of everypage has chosen to generate this warning if his package is used because the package is no longer needed. That doesn't qualify for us overwriting that decision in my opinion.

**Comment by kberry** [comment]
thanks for the info / sorry for the noise.
