### ISSUE TITLE
Typo in documentation of "Generic hooks provided by packages"

### ISSUE THREAD

**Issue by gusbrs** [latex3/latex2e#799]
Just a small documentation issue.

The `lthooks-doc` gives as example of use of package specific generic hooks `babel` mentioning hooks in the form `babel/afterextras/<language>`:

https://github.com/latex3/latex2e/blob/fd078baf51b68ca9b1045f8f9cfeae3125c6dcd4/base/lthooks.dtx#L1380-L1383

However, `babel` itself is using hooks in the form `babel/<language>/afterextras`:

https://github.com/latex3/babel/blob/bb69d2269a305ba3ae08b05b49575ea6dff155c9/babel.dtx#L7058

**Comment by FrankMittelbach** [comment]
thanks ... yes we changed our minds what the best order is ...
