### ISSUE TITLE
pdflatex produces invisibly broken pdf files.

### ISSUE THREAD

**Issue by Beiri22** [latex3/latex2e#800]
## Brief outline of the bug
I have tested with several pdf files produced by pdflatex (I am using the current version available in manjaro linux, testing branch, texlive-core 2021.62793-1, texlive-bin 2021.59745-2, more info on request). They seem ok and look ok in all viewer. But trying to convert the files to png (with imagemagick, which is using ghostscript) I got an error on the first page. I have submitted the error at ghostscript bug tracker.

They told me:
Essentially the PDF file is broken. The first page has a Group key (a form of transparency):
```
14 0 obj
<<
  /Type /Page
  /Contents 19 0 R
  /Resources 18 0 R
  /MediaBox [ 0 0 453.542999 255.117996 ]
  /Trans <<
    /S /R
  >>
  /Parent 26 0 R
  /Group 22 0 R
>>

endobj
```
However object 22 is defined in the xref table as a free entry, there is no object 22. Obviously at this point what happens depends on how PDF consumers implement error handling. The old PDF interpreter ignored the error and carried on, without so much as raising a warning. The new PDF interpreter tells you there's a problem, but doesn't carry on.

Please see / maybe discuss here: https://bugs.ghostscript.com/show_bug.cgi?id=705206

**Comment by josephwright** [comment]
If there is an engine issue, that would be 'not us' and the issue would be closed. However, I'm confident that's not generally the case. What I do wonder about is exactly what your input looks like: with for example
```latex
\documentclass{article}
\usepackage{expl3}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\begin{document}
Hello world
\end{document}
```
there is no `/Trans` entry in the PDF.

**Comment by Beiri22** [comment]
I will produce a minimum example. Give me some time.

**Comment by FrankMittelbach** [comment]
> I will produce a minimum example.
> The problem can be reproduced without beamer, too.

yes please produce an MWE and follow the guidelines in https://github.com/latex3/latex2e/blob/develop/CONTRIBUTING.md in particular checking your example with 
```
\RequirePackage{latexbug}    % <- first line
```
i.e., it should not load packages we do not maintain unless there is a very good reason to suspect that the package is needed but the fault is with core LaTeX.

**Comment by Beiri22** [comment]
```
\RequirePackage{latexbug}
\documentclass{article}
\usepackage{graphicx}

\begin{document}
	% Comment out the first includegraphics and the error is gone.
	% remove the clip and the error is gone
	% removing the trim does not affect the error
	\includegraphics[scale=0.01, trim={1pt 1pt 1pt 1pt}, clip]{pavel-neznanov-w95Fb7EEcjE-unsplash.jpg}
	% Comment out the first includegraphics and the error is gone.
	\includegraphics[scale=0.10, keepaspectratio]{titel_fg.pdf}
	
	%% RUNNING convert a.pdf a.png
	%% RESULTS IN Dereference of free object 7, next object number as offset failed, returning NULL object.	**** Error: Page drawing error occured.	Output may be incorrect.
\end{document}
```
Tex + images are in the example2.zip
[example2.zip](https://github.com/latex3/latex2e/files/8442197/example2.zip)

**Comment by josephwright** [comment]
@Beiri22  I've tried your example modified to include the line @FrankMittelbach mentions and to avoid PDF compression
```latex
\RequirePackage{latexbug}
\documentclass{article}
\ExplSyntaxOn
\sys_load_backend:n{}
\pdf_uncompress:
\ExplSyntaxOff
\usepackage{graphicx}
\listfiles
\begin{document}
	% Comment out the first includegraphics and the error is gone.
	% remove the clip and the error is gone
	% removing the trim does not affect the error
	\includegraphics[scale=0.01, trim={1pt 1pt 1pt 1pt}, clip]{pavel-neznanov-w95Fb7EEcjE-unsplash.jpg}
	% Comment out the first includegraphics and the error is gone.
	\includegraphics[scale=0.10, keepaspectratio]{titel_fg.pdf}
	
	%% RUNNING convert a.pdf a.png
	%% RESULTS IN Dereference of free object 7, next object number as offset failed, returning NULL object.	**** Error: Page drawing error occured.	Output may be incorrect.
	
\end{document}
```
I  don't see the `/Trans` issue in the PDF and I don't see an issue with GhostScript on my Mac. I do see a pdfTeX warning
```
pdfTeX warning: /usr/local/texlive/2022/bin/universal-darwin/pdflatex-dev (file
 ./titel_fg.pdf): PDF inclusion: multiple pdfs with page group included in a single page
```

Can you add `\listfiles` and include the `File list` you get?

**Comment by Beiri22** [comment]
I tried that, see attachment. The error is still there
[example3.zip](https://github.com/latex3/latex2e/files/8442258/example3.zip)
.

**Comment by josephwright** [comment]
@Beiri22  I'm not sure what you mean by 'the error is still there'. I've just tried your PDF with
```
gs -dNOPAUSE -dBATCH -sDEVICE=png16m -sOutputFile=a.png a.pdf
```
and no error is reported, and as I said there's no `/Trans` in the PDF.

**Comment by Beiri22** [comment]
What version of ghostscript do you use?

**Comment by josephwright** [comment]
@Beiri22 Ah, right: it's not the `/Trans` entry that's an issue, it's the `/Group` one. Right, well that clears things up in a sense: that's definitely not an issue arising from the macro layer as we don't have any control over that. So the issue will be closed here, I will try to get it down to a plain TeX version, and it will need to be reported to the pdfTeX maintainers.

**Comment by u-fischer** [comment]
@josephwright  I see the problem, but I think too that it is an engine problem.

**Comment by Beiri22** [comment]
Ok, then please help me on where to correctly report that

**Comment by josephwright** [comment]
@Beiri22 https://tug.org/mailman/listinfo/pdftex but the example will almost certainly need to be created in plain TeX, so showing exactly which primitives are in use. That might take a bit of effort here.

**Comment by zauguin** [comment]
> Obviously at this point what happens depends on how PDF consumers implement error handling. The old PDF interpreter ignored the error and carried on, without so much as raising a warning. The new PDF interpreter tells you there's a problem, but doesn't carry on.

I agree that it would be nicer if pdfTeX wouldn't generate entries like this, but the new PDF interpreters behavior is also incorrect. The PDF specification states (both in version 1.7 and 2.0):

> An indirect reference to an undefined object is not an error; it is simply treated as a reference to the `null` object

and

>  A dictionary entry whose value is `null` [...] is equivalent to an absent entry

So according to the specification the PDF file is not broken but just unusual. The `/Group` entry should just be ignored.

Therefore while IMO pdfTeX should be changed to not generate such references, GhostScript should also be fixed to accept such constructs.

**Comment by Beiri22** [comment]
@zauguin Can you tell, if the commit http://git.ghostscript.com/?p=ghostpdl.git;h=d6f88ef54434fcfc6dcefdcfe21bab1b1b77508b does fix this according to the pdf specification?

**Comment by FrankMittelbach** [comment]
> I agree that it would be nicer if pdfTeX wouldn't generate entries like this, but the new PDF interpreters behavior is also incorrect. The PDF specification states (both in version 1.7 and 2.0):

what does 1.5 say (if anything)?  because at least my setup generate PDF 1.5 (or claims to do so) not 1.7

**Comment by zauguin** [comment]
> what does 1.5 say (if anything)?

Effectively the same. I could trace equivalent statements back at least to PDF 1.3 (since I don't have access to earlier versions right now).

**Comment by zauguin** [comment]
> Can you tell, if the commit http://git.ghostscript.com/?p=ghostpdl.git;h=d6f88ef54434fcfc6dcefdcfe21bab1b1b77508b does fix this according to the pdf specification?

It's still considered an error which is non-conforming as far as I can tell. Also it seems very specific about the `/Group` object and I could imagine that the same thing appears for other objects too, but I haven't tested that.
