### ISSUE TITLE
Boldface for entire document fails on lemma, theorem, corollary, definition

### ISSUE THREAD

**Issue by Mogramu** [latex3/latex2e#807]
## Brief outline of the bug

I would like a document where everything is in boldface.  Have used `\boldmath` and `\renewcommand{\seriesdefault}{\bfdefault}`.  But the text within  lemma, theorem, corollary, and definition, are still being inserted with normal font weight, rather than using a bold typeface.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here

\usepackage{bm}                % makes bold arguments
\usepackage[x11names]{xcolor}  % loads 317 named rgb colours

\usepackage{amsmath}
\usepackage{amsthm}

\boldmath
\renewcommand{\seriesdefault}{\bfdefault}

\newtheorem{theorem}{Theorem}[section]
\newtheorem{corollary}{Corollary}[theorem]
\newtheorem{lemma}[theorem]{Lemma}

\theoremstyle{definition}
\newtheorem{definition}{Definition}[section]

\begin{document}

  % Demonstration of issue here
  
\begin{definition}[Convolution]
  Some definition
  \begin{equation}
    v(t) = u_1(t) * u_2(t) = \int_{D_t} u_1(t') u_2(t-t') dt'
  \end{equation}

  Some text

\end{definition}  

You can reference definitions

\begin{lemma}[Convolution]
  This is a lemma
  \begin{equation}
    v(t) = u_1(t) * u_2(t) = \int_{D_t} u_1(t') u_2(t-t') dt'
  \end{equation}

  Some text

\end{lemma}  

You can reference lemmas

\begin{theorem}[Convolution]
  This is a theorem
  \begin{equation}
    v(t) = u_1(t) * u_2(t) = \int_{D_t} u_1(t') u_2(t-t') dt'
  \end{equation}

  Some text

\end{theorem}  

You can reference lemmas

\begin{corollary}[Convolution]
  This is a corollary
  \begin{equation}
    v(t) = u_1(t) * u_2(t) = \int_{D_t} u_1(t') u_2(t-t') dt'
  \end{equation}

  Some text

\end{corollary}  

You can reference corollaries

\end{document}
```

## Log file (required) and possibly PDF file  

This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex 2021.10.8)  23 APR 2022 23:47
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**\input /home/hagbard/Opstk/bin/gungadin-1.0/docs/devguide/vulcan-kmpj/fredhol
m.tex
(/home/hagbard/Opstk/bin/gungadin-1.0/docs/devguide/vulcan-kmpj/fredholm.tex
(/usr/share/texlive/texmf-dist/tex/latex/base/book.cls
Document Class: book 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/bk10.clo
File: bk10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@chapter=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
Package: geometry 2010/09/12 v5.6 Page Geometry

(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty
Package: ifpdf 2017/03/15 v3.2 Provides the ifpdf switch
)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty
Package: ifvtex 2016/05/16 v1.6 Detect VTeX and its facilities (HO)
Package ifvtex Info: VTeX not detected.
)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty
Package: ifxetex 2010/09/12 v0.6 Provides ifxetex conditional
)
\Gm@cnth=\count88
\Gm@cntv=\count89
\c@Gm@tempcnt=\count90
\Gm@bindingoffset=\dimen103
\Gm@wd@mp=\dimen104
\Gm@odd@mp=\dimen105
\Gm@even@mp=\dimen106
\Gm@layoutwidth=\dimen107
\Gm@layoutheight=\dimen108
\Gm@layouthoffset=\dimen109
\Gm@layoutvoffset=\dimen110
\Gm@dimlist=\toks15
)
(/usr/share/texlive/texmf-dist/tex/latex/base/fix-cm.sty
Package: fix-cm 2015/01/14 v1.1t fixes to LaTeX

(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def
File: ts1enc.def 2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
))
(/usr/share/texlive/texmf-dist/tex/latex/tools/bm.sty
Package: bm 2017/01/16 v1.2c Bold Symbol Support (DPC/FMi)
\symboldoperators=\mathgroup4
\symboldletters=\mathgroup5
\symboldsymbols=\mathgroup6
LaTeX Font Info:    Redeclaring math alphabet \mathbf on input line 141.
LaTeX Info: Redefining \bm on input line 207.
)
(/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
Package: xcolor 2016/05/11 v2.12 LaTeX color extensions (UK)

(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: pdftex.def on input line 225.

(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def
File: pdftex.def 2018/01/08 v1.0l Graphics/color driver for pdftex
)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.
Package xcolor Info: Model `hsb' substituted by `rgb' on input line 1352.
Package xcolor Info: Model `RGB' extended on input line 1364.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1366.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1367.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1370.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1371.

(/usr/share/texlive/texmf-dist/tex/latex/xcolor/x11nam.def
File: x11nam.def 2016/05/11 v2.12 Predefined colors according to Unix/X11 (UK)
))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
Package: amsmath 2017/09/02 v2.17a AMS math features
\@mathmargin=\skip43

For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
Package: amstext 2000/06/29 v2.01 AMS text

(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty
File: amsgen.sty 1999/11/30 v2.0 generic functions
\@emptytoks=\toks16
\ex@=\dimen111
))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty
Package: amsbsy 1999/11/29 v1.2d Bold Symbols
LaTeX Info: Redefining \boldsymbol on input line 28.
\pmbraise@=\dimen112
)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty
Package: amsopn 2016/03/08 v2.02 operator names
)
\inf@bad=\count91
LaTeX Info: Redefining \frac on input line 213.
\uproot@=\count92
\leftroot@=\count93
LaTeX Info: Redefining \overline on input line 375.
\classnum@=\count94
\DOTSCASE@=\count95
LaTeX Info: Redefining \ldots on input line 472.
LaTeX Info: Redefining \dots on input line 475.
LaTeX Info: Redefining \cdots on input line 596.
\Mathstrutbox@=\box26
\strutbox@=\box27
\big@size=\dimen113
LaTeX Font Info:    Redeclaring font encoding OML on input line 712.
LaTeX Font Info:    Redeclaring font encoding OMS on input line 713.
\macc@depth=\count96
\c@MaxMatrixCols=\count97
\dotsspace@=\muskip10
\c@parentequation=\count98
\dspbrk@lvl=\count99
\tag@help=\toks17
\row@=\count100
\column@=\count101
\maxfields@=\count102
\andhelp@=\toks18
\eqnshift@=\dimen114
\alignsep@=\dimen115
\tagshift@=\dimen116
\tagwidth@=\dimen117
\totwidth@=\dimen118
\lineht@=\dimen119
\@envbody=\toks19
\multlinegap=\skip44
\multlinetaggap=\skip45
\mathdisplay@stack=\toks20
LaTeX Info: Redefining \[ on input line 2817.
LaTeX Info: Redefining \] on input line 2818.
)
(/usr/share/texlive/texmf-dist/tex/latex/amscls/amsthm.sty
Package: amsthm 2017/10/31 v2.20.4
\thm@style=\toks21
\thm@bodyfont=\toks22
\thm@headfont=\toks23
\thm@notefont=\toks24
\thm@headpunct=\toks25
\thm@preskip=\skip46
\thm@postskip=\skip47
\thm@headsep=\skip48
\dth@everypar=\toks26
)
(/home/hagbard/Opstk/bin/gungadin-1.0/docs/devguide/vulcan-kmpj/fredholm.aux)
\openout1 = `fredholm.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 29.
LaTeX Font Info:    ... okay on input line 29.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 29.
LaTeX Font Info:    ... okay on input line 29.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 29.
LaTeX Font Info:    ... okay on input line 29.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 29.
LaTeX Font Info:    ... okay on input line 29.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 29.
LaTeX Font Info:    ... okay on input line 29.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 29.
LaTeX Font Info:    ... okay on input line 29.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 29.
LaTeX Font Info:    ... okay on input line 29.

*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: custom
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: twoside 
* h-part:(L,W,R)=(22.76219pt, 551.98349pt, 22.76219pt)
* v-part:(T,H,B)=(59.75078pt, 478.00632pt, 59.75078pt)
* \paperwidth=597.50787pt
* \paperheight=597.50787pt
* \textwidth=551.98349pt
* \textheight=478.00632pt
* \oddsidemargin=-49.5078pt
* \evensidemargin=-49.5078pt
* \topmargin=-42.5867pt
* \headheight=12.0pt
* \headsep=18.06749pt
* \topskip=10.0pt
* \footskip=25.29494pt
* \marginparwidth=125.0pt
* \marginparsep=7.0pt
* \columnsep=10.0pt
* \skip\footins=9.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidetrue
* \@mparswitchtrue
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
\scratchcounter=\count103
\scratchdimen=\dimen120
\scratchbox=\box28
\nofMPsegments=\count104
\nofMParguments=\count105
\everyMPshowfont=\toks27
\MPscratchCnt=\count106
\MPscratchDim=\dimen121
\MPnumerator=\count107
\makeMPintoPDFobject=\count108
\everyMPtoPDFconversion=\toks28
)
\c@theorem=\count109
\c@corollary=\count110
\c@definition=\count111
 [1

{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
LaTeX Font Info:    Calculating math sizes for size <13> on input line 68.

LaTeX Font Warning: Font shape `OMX/cmex/m/n' in size <13> not available
(Font)              size <12> substituted on input line 68.

LaTeX Font Info:    Try loading font information for OMS+cmr on input line 68.
(/usr/share/texlive/texmf-dist/tex/latex/base/omscmr.fd
File: omscmr.fd 2014/09/29 v2.5h Standard LaTeX font definitions
)
LaTeX Font Info:    Font shape `OMS/cmr/m/n' in size <13> not available
(Font)              Font shape `OMS/cmsy/m/n' tried instead on input line 68.
 [2]
(/home/hagbard/Opstk/bin/gungadin-1.0/docs/devguide/vulcan-kmpj/fredholm.toc)
\tf@toc=\write3
\openout3 = `fredholm.toc'.

[3

] [4

]
Chapter 1.
[5] [6] [7]
(/home/hagbard/Opstk/bin/gungadin-1.0/docs/devguide/vulcan-kmpj/fredholm.aux)

LaTeX Font Warning: Size substitutions with differences
(Font)              up to 1.0pt have occurred.

 ) 
Here is how much of TeX's memory you used:
 3222 strings out of 492982
 45431 string characters out of 6134896
 121963 words of memory out of 5000000
 6781 multiletter control sequences out of 15000+600000
 10989 words of font info for 39 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 27i,16n,35p,293b,197s stack positions out of 5000i,500n,10000p,200000b,80000s
</usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmbsy10.pfb></u
sr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx12.pfb></usr/sha
re/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx9.pfb></usr/share/texl
ive/texmf-dist/fonts/type1/public/amsfonts/cm/cmbxsl10.pfb></usr/share/texlive/
texmf-dist/fonts/type1/public/amsfonts/cm/cmbxti10.pfb></usr/share/texlive/texm
f-dist/fonts/type1/public/amsfonts/cm/cmex10.pfb></usr/share/texlive/texmf-dist
/fonts/type1/public/amsfonts/cm/cmmib10.pfb></usr/share/texlive/texmf-dist/font
s/type1/public/amsfonts/cmextra/cmmib7.pfb></usr/share/texlive/texmf-dist/fonts
/type1/public/amsfonts/cm/cmr12.pfb></usr/share/texlive/texmf-dist/fonts/type1/
public/amsfonts/cm/cmsy10.pfb>
Output written on fredholm.pdf (7 pages, 115167 bytes).
PDF statistics:
 68 PDF objects out of 1000 (max. 8388607)
 48 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by zauguin** [comment]
The log file you provided does not correspond to the example code, especially it does use a different class and doesn't load `latexrelease`. If you had loaded `latexrelease` it would have told you that `amsthm` is maintained by the AMS and not by the LaTeX team, so if you think that there is something wrong with it you should report it to them.

Beside that I think that non-bold note fields are intended behavior for the default styles. The amsthm documentation shows you how you can define different styles if you want to change this.
