### ISSUE TITLE
\color at the beginning of a \parbox pushes text down

### ISSUE THREAD

**Issue by pietvo** [latex3/latex2e#811]
## Brief outline of the bug

When a `\parbox[t]` starts with a `\color` command, the text that follows is pushed a little bit down. It may be caused by some invisible space be placed above the text, thus causing the baseline of the box to be above the text (that's my guess, I haven't checked if that is really the case). It happens both with the `color` and the `xcolor` packages.

Thje problem disappears if there is any horizontal mode material, even invisible, before the `\color` command, such as `\leavevmode` or `\noindent`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{color} % or xcolor

\begin{document}

\parbox[t]{0.25\textwidth}{Normal text}
\parbox[t]{0.25\textwidth}{\color{red}Colored text}
\parbox[t]{0.25\textwidth}{Normal text}\\
\rule{\textwidth}{1pt}

\parbox[t]{0.25\textwidth}{Normal text}
\parbox[t]{0.25\textwidth}{\leavevmode\color{red}Colored text}
\parbox[t]{0.25\textwidth}{Normal text}\\
\rule{\textwidth}{1pt}

\parbox[t]{0.25\textwidth}{Normal text}
\parbox[t]{0.25\textwidth}{\noindent\color{red}Colored text}
\parbox[t]{0.25\textwidth}{Normal text}\\
\rule{\textwidth}{1pt}

\end{document}
```

## Log file (required) and possibly PDF file  

[alignparboxes.log](https://github.com/latex3/latex2e/files/8645162/alignparboxes.log)
[alignparboxes.pdf](https://github.com/latex3/latex2e/files/8645163/alignparboxes.pdf)

**Comment by u-fischer** [comment]
`\color` doesn't switch into horizontal mode (that is by design) but inserts a whatsits.  You get the same with other 
 whatsits, e.g. `\addtocontents` or a label:

~~~~
 \documentclass{book}
 \begin{document}
 \parbox[t]{0.2\textwidth}{Normal text}
 \parbox[t]{0.2\textwidth}{\addtocontents{toc}{blub}Normal text}
 \parbox[t]{0.2\textwidth}{\label{blub}Normal text}
 \end{document}
~~~~

`\leavevmode\color{red}` is the correct code.

**Comment by davidcarlisle** [comment]
This has been a documented feature from the start (foonote page 6 of grfguide) It's not ideal, but it is unfortunately just the way TeX is.
