### ISSUE TITLE
ltxdoc from latex-dev 2022-06-01 requires user to manually adjust hyperref loading due to option clash

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#822]
## Brief outline of the <s>bug</s> issue

```
Package: hypdoc 2021-11-15 v1.15 Hyper extensions for doc.sty (HO)


! LaTeX Error: Option clash for package hyperref.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.54 ]{hyperref}[2002/05/09]
                            %
```

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{ltxdoc}

  % Any preamble code goes here
\usepackage{hyperref}

\begin{document}

  % Demonstration of issue here
  
\end{document}
```

As an aside ltnews35 says:

```
if you run into issues with older documentation using doc
a simple and quick solution is to load the package
as follows: \usepackage{doc}[=v2]
```

but there seems no easy way to instruct `ltxdoc` to do that.  I see a cfg file is loaded but I am not sure if one can "pass requested release to package" to tell `doc` to load `v2` (sorry no time to check doc).

KOMA-script has this seemingly provisory code:

```
    \IfFileExists{doc-2021-06-01.sty}{%
      \RequirePackage{scrlfile}%
      \ReplaceInput{doc.sty}{doc-2021-06-01.sty}%
      \PassOptionsToClass{nocfg}{ltxdoc}%
    }{}
    \LoadClassWithOptions{ltxdoc}
    \@ifundefined{cs}{\DeclareRobustCommand\cs[1]{\texttt{\bslash #1}}}{}
```

but anyhow `scrdoc` in presence of `latex-dev` format wil not reach this and abort earlier using `koma-script-source-doc` (which caused my original problem as it defines a `\var` command which was also defined in my user source; this is altogether different thing but is where I came from to here).

## Log file (required) and possibly PDF file  
[testltxdoc.log](https://github.com/latex3/latex2e/files/8743505/testltxdoc.log)

Nota bene : removing `\usepackage{hyperref}` from preamble is not an option as I need to access `\hypersetup` in the preamble but `doc V3` delays loading of `hypdoc` to a hook executed immediately before at begin document.

**Comment by jfbu** [comment]
In my use case, where I am only aiming at full backwards compatibility, I could use 
```
\PassOptionsToPackage{hyperref=false}{doc}
```
before loading the class, and this prevents loading of `hypdoc`.  This allows my doc to compile whether with `latex` or `latex-dev`.

**Comment by FrankMittelbach** [comment]
If you need to load hyperref in the preamble, you could also load it explicitly with the necessary options,e.g.,
```
\usepackage[hyperindex=false,pdfusetitle,colorlinks,pdfpagelabels]{hyperref}
```
plus whatever options you want in addition.
Turning hyperref support off for doc elements is of course an option too, but that means you don't get the hyperref support for the doc elements which is kind of the purpose of the V3 release.

As to the need for using `\hypersetup`, you could delay that to the point at which hyperref is loaded using
```
\AddToHook{begindocument/before}{\hypersetup{...}}
```


Regardless of that, we can probably add a docv2 option to ltxdoc or something similar to support old docs using ltxdoc.

**Comment by jfbu** [comment]
About:

> Turning hyperref support off for doc elements is of course an option too, but that means you don't get the hyperref support for the doc elements which is kind of the purpose of the V3 release.

In my real life case I did try out the indexing provided by `doc` in the past, but finally decided to drop it. Among various reasons, the main ones were that I had already used dedicated mark-up using sectioning and suitable table of contents (and hyperref), that indices considerably enlarged the PDF size, and that PDF viewer search abilities always proved largely enough whenever I myself decide to search for something in the PDF (rather than in the sources).

Thus, indeed I use (in this specific case motivating me opening this ticket) but a very minor part of `doc.sty` capabilities,  I have my own custom mark-up for what I want.  For this reason and as I wanted to keep my sources compatible both with current and June LaTeX release I felt there was lacking some easy backwards compatibility feature of ltxdoc.

Now the ironic thing is that I finally decided to drop `ltxdoc` (or rather `scrdoc`), as I use very little of it and load directly  `doc.sty`.  Looking more into both `ltxdoc` and `scrdoc` which I had not done so far I noticed most of it is for things that I do not need, even a lot of it is especially for the process of the LaTeX project (or KOMA-script) own documentation.

**Comment by jfbu** [comment]
> Looking more into both `ltxdoc` and `scrdoc` which I had not done so far I noticed most of it is for things that I do not need, even a lot of it is especially for the process of the LaTeX project (or KOMA-script) own documentation.

I think now this issue should be considered invalid in so far as `ltxdoc` has large parts dedicated especially to production of `source2e.pdf`, so it does not seem to make sense to add overhead for people like myself using it somewhat accidentally for package documentation having its own custom mark-up methods using a fraction of `doc.sty`, and who for this reason prefer to stick to its `V2`.

**Comment by FrankMittelbach** [comment]
I forgot to close this: with 2022-06-01 release ltxdoc.cls got an option `doc2` which results in using version 2 of doc (and not the current one V3)

**Comment by hmenke** [comment]
None of these workarounds are obvious to me. Not even reading the release notes helps because the latest version is 34. The version 35 that explains the breaking behavior is not yet published.

I've asked @ho-tex to fix it: https://github.com/ho-tex/hypdoc/issues/1
