### ISSUE TITLE
\DocumentMetadata{testphase=phase-II} raises an error on (u)platex-dev

### ISSUE THREAD

**Issue by h20y6m** [latex3/latex2e#829]
## Brief outline of the bug

I try "latex-lab" on (u)platex-dev.

I add 

```latex
\DocumentMetadata{testphase=phase-II}
```

and an error raised.

```
! LaTeX3 Error: The key '__tag/setup/interwordspace' is unknown and is being
(LaTeX3)        ignored.

For immediate help type H <return>.
 ...

l.44 ...setup{activate,paratagging,interwordspace}
```

## Minimal example showing the bug

```latex
%#!platex-dev
\RequirePackage{latexbug}
\DocumentMetadata{testphase=phase-II}
\documentclass{article}
\begin{document}
This is p\LaTeX.
\end{document}
```

## Log file (required) and possibly PDF file  

[001.log](https://github.com/latex3/latex2e/files/8790952/001.log)

**Comment by u-fischer** [comment]
It is a tagpdf bug, I opened an issue there https://github.com/u-fischer/tagpdf/issues/54 and will close this one.

Side remark: I assume that platex like xelatex doesn't support real interword spaces, which means that it is not a good engine for tagging.
