### ISSUE TITLE
Please add the 3 math symbols in amsmath package

### ISSUE THREAD

**Issue by WangDongYao** [latex3/latex2e#834]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

## Minimal example showing the current behaviour

```latex
\RequirePackage{amsmath}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{document}

$\arcsec x$
$\arccot x$
$\arccsc x$
  
\end{document}
```
It will cause the error:  
Undefined control sequence.
<recently read> \arccot 

## Minimal example showing the desired new behaviour

```latex
\RequirePackage{amsmath}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

\DeclareMathOperator{\arcsec}{arcsec}
\DeclareMathOperator{\arccot}{arccot}
\DeclareMathOperator{\arccsc}{arccsc}

\begin{document}

$\arcsec x$
$\arccot x$
$\arccsc x$
  
\end{document}
```
It will correct and show:
```
acrsec x
arccot x
arccsc x
```

**Comment by eg9** [comment]
For more than 40 years, no flavor of TeX has provided `\arcsec`, `\arccsc` and `\arccot`. The reason might be that Knuth never uses them and so he didn't add them in `plain.tex`. And this is the first time I hear a complaint about it.

On the other hand, there's no “natural definition” for the arcsecant and the arccosecant, which might explain why they're not frequently used. For instance, Geogebra hasn't them; Desmos instead has them.

However, adding
```
\DeclareMathOperator{\arcsec}{arcsec}
```
to your document is not difficult.

**Comment by WangDongYao** [comment]
> For more than 40 years, no flavor of TeX has provided `\arcsec`, `\arccsc` and `\arccot`. The reason might be that Knuth never uses them and so he didn't add them in `plain.tex`. And this is the first time I hear a complaint about it.
> 
> On the other hand, there's no “natural definition” for the arcsecant and the arccosecant, which might explain why they're not frequently used. For instance, Geogebra hasn't them; Desmos instead has them.
> 
> However, adding
> 
> ```
> \DeclareMathOperator{\arcsec}{arcsec}
> ```
> 
> to your document is not difficult.

Thank you for your reply, I just find the full set of available trig functions in physics package.

**Comment by FrankMittelbach** [comment]
Personally, I would simply add the definitions to the document, but loading a package that provide them is certainly also possible.
