### ISSUE TITLE
Error with pre-release-4: "Package mark Error: Infinite shrinkage found in 'page'."

### ISSUE THREAD

**Issue by scottkosty** [latex3/latex2e#836]
## Brief outline of the bug

On pre-release-4, I get the following error:

    ! Package mark Error: Infinite shrinkage found in 'page'.

On the "stable" "pdflatex" in TeX Live 2022, I do not get an error when compiling.

## Minimal example showing the bug

Unfortunately I could not make the example too minimal. The example is about 400 lines. When I try to make it more minimal (e.g., removing the graphic), the error goes away. The original file is about 6,000 lines so at least I could narrow it down a bit. To make it more minimal, I made lots of edits so the content likely doesn't make sense or is actually wrong (e.g., I substituted other graphics with just this one graphic so that there is only one dependency).

(the extension is .txt since .tex is not allowed for GitHub uploads):
[complicated-example.txt](https://github.com/latex3/latex2e/files/8806103/complicated-example.txt)
Here is the included graphic:
[with_fntright.pdf](https://github.com/latex3/latex2e/files/8806109/with_fntright.pdf)

Please let me know if these type of non-MWE issues are more bothersome than helpful. This code is not mine (and I don't even understand some of the LaTeX in it). It is just part of a bunch of tests that I ran `pdflatex-dev` on to see if any issue.

## Log file (required) and possibly PDF file  

Here is the "good" log (i.e., with 'pdflatex'):
[good.log](https://github.com/latex3/latex2e/files/8806150/good.log)

Here is the "bad" log (i.e., with 'pdflatex-dev'):
[bad.log](https://github.com/latex3/latex2e/files/8806151/bad.log)

Thank you!

**Comment by scottkosty** [comment]
Thank you for taking the time to narrow it down, Ulrike! I confirm I reproduce the same behavior with your clean example. Let me know if you think we should edit my original post to save the time of future readers of this issue.

**Comment by u-fischer** [comment]
The example without marginnote is

~~~~
\documentclass{book}

\begin{document}\makeatletter

x 

\vspace{44\baselineskip}

\setbox\@tempboxa\vbox to \ht\strutbox{blub\vss}%
\box\@tempboxa\vskip-\baselineskip
blub \\zzz

\end{document}
~~~~

(with article it fails too if \flushbottom is set).

**Comment by FrankMittelbach** [comment]
Try this for a first aid workaround:
```
\ExplSyntaxOn

\cs_set_protected:Npn \__mark_update_structure:nn #1#2
  {
    \__mark_update_structure_alias:nn { previous-#1 } {#1}
    \group_begin:
      \dim_set_eq:NN \tex_splitmaxdepth:D \c_max_dim
      \int_set_eq:NN \tex_vbadness:D      \c_max_int
      \dim_set_eq:NN \tex_vfuzz:D         \c_max_dim
      \vbox_set_to_ht:Nnn \l__mark_box { -.5\c_max_dim }
        {
          #2
          \tex_unskip:D
          \box_gset_to_last:N \l__mark_box
% if the box is now empty we unbox last box if it is a vbox (assumption it is from enlargethispage)
% otherwise we don't as it is some document element.
% This is still only a heuristic, so it can fail if all that is on the page is a single box containing
% infinite negative glue.
          \int_compare:nNnT \tex_lastnodetype:D < 0
             {
              \box_if_vertical:NT \l__mark_box
                 { \vbox_unpack:N \l__mark_box }
              \tex_kern:D \c_zero_dim
             }
        }
      \int_compare:nNnTF \tex_badness:D > 0
        {
          \vbox_set_split_to_ht:NNn \l__mark_box \l__mark_box \c_max_dim
          \seq_map_inline:Nn \g__mark_classes_seq
            {
              \tl_gset_eq:Nc \g__mark_new_top_tl { g__mark_#1_last_##1_tl }
              \tl_gset_eq:cN { g__mark_#1_top_##1_tl } \g__mark_new_top_tl
              \tl_gset:No \g__mark_tmp_tl
                { \tex_splitbotmarks:D \use:c { c__mark_class_##1_mark } }
              \tl_if_empty:NTF \g__mark_tmp_tl
                {
                  \tl_gset_eq:cN { g__mark_#1_last_ ##1_tl }
                    \g__mark_new_top_tl
                  \tl_gset_eq:cN { g__mark_#1_first_##1_tl }
                    \g__mark_new_top_tl
                }
                {
                  \tl_gset_eq:cN { g__mark_#1_last_##1_tl } \g__mark_tmp_tl
                  \tl_gset:co { g__mark_#1_first_##1_tl }
                    {
                      \tex_splitfirstmarks:D
                        \use:c { c__mark_class_##1_mark }
                    }
                }
            }
        }
        {
          \msg_error:nnn { mark } { infinite-shrinkage } {#1}
          \seq_map_inline:Nn \g__mark_classes_seq
            {
              \tl_gset_eq:cc { g__mark_#1_top_  ##1_tl }
                             { g__mark_#1_last_ ##1_tl }
              \tl_gset_eq:cc { g__mark_#1_first_##1_tl }
                             { g__mark_#1_last_ ##1_tl }
            }
        }
    \group_end:
  }

\ExplSyntaxOff
```
Not quite the final solution I guess.

(by the way your test file contains a lot of obsolete  code, som of which may continue to work going forward --- but it picked up this bug/ oversimplification)

**Comment by scottkosty** [comment]
> cleaner test files are of course appreciated :-), i.e., if you can take on some of the work that is necessary to isolate the problem, that would be a huge help, but in that form it is still better than not being reported at all.

Thank you, and understood! I will try my best to whittle the example down more in the future. Thank you to you and to Ulrike for your patience and help.

**Comment by FrankMittelbach** [comment]
Scott, I didn't expect you to cut it down like Ulrike did, but the more you clean up first the easier is for others to get to the root of it rather than to do that work on top, it just helps us with the limited time we have to address many different issues or requests. Anyway, problem identified thanks to Ulrike and clearly something that needs to get addressed, so good that you reported it.

**Comment by scottkosty** [comment]
After a tlmgr update, the original use case of this issue works well!

I came across this error message with a different example though (even after the update which I think includes the fix). However, the new example uses what I think is an outdated .cls file. The .cls file appears to be from 2008. And I'm not sure the journal uses this .cls file anymore. I will give the example here, although I have no idea if it is useful to dig into it or not since I'm not sure if there is a current valid use case using the .cls file.

Here is the .cls file (and other files that I'm not sure are relevant):
[AGU-LaTeX_OBSOLETE.zip](https://github.com/latex3/latex2e/files/8936501/AGU-LaTeX_OBSOLETE.zip)

Here is the example:

```
\RequirePackage{latexbug}
\documentclass[jgrga]{agutex}

\begin{document}

hello

\end{document}
```

[example.log](https://github.com/latex3/latex2e/files/8936502/example.log)

**Comment by FrankMittelbach** [comment]
Well, the class is not even on CTAN and as you say it is rather old (with a lot of code for LaTeX2.09 and some claims that it contains stuff based on multicol by some "Mittlebach" :-)

Anyway, the offending bit is
```
\def\new@makecol{\setbox\@outputbox
     \vbox{\boxmaxdepth \maxdepth
\ifdim\ht\dbltopins<1pt\else\unvbox\dbltopins\fi
     \unvbox\@cclv
\ifdim\ht\dblbotins<1pt\else\unvbox\dblbotins\fi%
\ifvoid\footins\else\vskip\skip\footins\footnoterule\unvbox\footins\fi
%\vss  <--- wrong
}
```
that contains `\vss`. I haven't traced why it was added there or what the intention is, probably their footer adds to much material and they want to back up (easily), but that can be handled differently not with infinite glue on top level. I fyou want to follow it up with Amy, please go ahead.

**Comment by scottkosty** [comment]
Thanks for taking a look, Frank! (I don't plan to follow up with the cls author; I was just worried it was an unintended LaTeX2e issue but that doesn't seem to be the case)

**Comment by scottkosty** [comment]
Just a note that after a recent TeX Live update, it seems that this issue might have been fixed (not sure by where).

**Comment by FrankMittelbach** [comment]
It had been fixedd in 2024, see above, that's why this issue is closed :-)

**Comment by FrankMittelbach** [comment]
Correction: it got fixed in that other class due to the fact that we got some engine support which makes it possible to mask \vss becoming an error but just silently ignoe it (except for a log entry). But it was probably also fixed by the change I did in 2024 just in a different way (there I bypassed the error by temporarily changing to \batchmode when splitting the box for finding the marks).

**Comment by scottkosty** [comment]
Thanks for the explanation, Frank!! I was curious and now the mystery is solved :)
