### ISSUE TITLE
Error with pre-release-4: "Invalid UTF-8 byte sequence" with tufte-handout \smallcaps

### ISSUE THREAD

**Issue by scottkosty** [latex3/latex2e#838]
## Brief outline of the bug

On pre-release-4, I get the following error:

    ! LaTeX Error: Invalid UTF-8 byte sequence (ã¤l).

On the "stable" "pdflatex" in TeX Live 2022, I do not get an error when compiling, and the output looks correct to me (i.e., the non-ASCII character seems to appear correctly in the PDF).

## Minimal example showing the bug

```latex
\documentclass[ngerman]{tufte-handout}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\begin{document}
Wenn Text in ... oder \smallcaps{Kapitälchen} ausgezeichn
\end{document}
```

In case it is relevant, Vim tells me that fileencoding=utf-8 and 'file' gives the following output:

```
$ file -i mwe.tex 
mwe.tex: text/x-tex; charset=utf-8
```

## Log file (required) and possibly PDF file  

Here is the "good" log (i.e., with 'pdflatex'):
[good.log](https://github.com/latex3/latex2e/files/8818278/good.log)

Here is the "bad" log (i.e., with 'pdflatex-dev'):
[bad.log](https://github.com/latex3/latex2e/files/8818279/bad.log)

Thank you!

**Comment by davidcarlisle** [comment]
An example not using so many external packages

```
%\RequirePackage{latexbug}
\documentclass{article}
\usepackage{textcase}
\begin{document}
Wenn Text in ... oder \MakeTextLowercase{Kapitälch}  ausgezeichn
\end{document}
```

That still generates warnings from `latexbug` that you should contact the author of `textcase`, but .....

**Comment by scottkosty** [comment]
Thanks for taking a look, David!

> That still generates warnings from `latexbug` that you should contact the author of `textcase`

Sound good, I will do that.

> if you could confirm that works with your original file, that would be useful, thanks.

I can hopefully do that later tonight and report back.

**Comment by davidcarlisle** [comment]
> Sound good, I will do that

you just did:-)

**Comment by scottkosty** [comment]
> > Sound good, I will do that
> 
> you just did:-)

Ah, I (finally) got it :)

**Comment by josephwright** [comment]
@davidcarlisle  I think it's time to make `\MakeText...case` equivalent to just `\Make...case`: all that's needed to to provide `\NoChangeCase` or agree to add to the kernel

**Comment by davidcarlisle** [comment]
@josephwright  probably I'd add `\NoChangeCase` to the kernel and leave `textcase.sty` just making `\MakeText..` aliases.  I don't think the kernel needs to support the old names from contrib  package, but `\NoCaseChange`  is sill useful for one-off protection from case changing.

**Comment by FrankMittelbach** [comment]
Might as well do it for 2022-06-01. The only issue is that it should get a mentioning in ltnews35 and that has already gone through copy-editing for TUB.

**Comment by scottkosty** [comment]
Just a note that after a tlmgr update, my original use cases work now.

**Comment by josephwright** [comment]
Fixed by a release by @davidcarlisle
