### ISSUE TITLE
Error with pre-release-4: (expected?) "LaTeX hooks Error"

### ISSUE THREAD

**Issue by scottkosty** [latex3/latex2e#841]
## Brief outline of the bug

On pre-release-4, I get the following error with EuropeCV:

    ! LaTeX hooks Error: Sorting rule for 'begindocument' hook applied too late.
    (hooks)              Try setting this rule earlier.

I think this might be an expected (i.e., intended) error that is documented in ltnews35 under the section "Fixed bug when setting hook rules for one-time hooks".

europecv.cls uses `\RequirePackage{hyperref}` inside `\AtBeginDocument`, which is not recommended from what I understand.

I reported this issue to EuropeCV at https://github.com/gsilano/EuropeCV/issues/29. Since I'm not sure of the above diagnosis, I still report this issue here. If the above is correct, is it best to apply the label "bug (external package)" and close this issue?

## Minimal example showing the bug

Here is the minimal example that does not depend on EuropeCV:

```latex
\documentclass{article}
\AtBeginDocument{
  \RequirePackage{hyperref}
}
\begin{document}
hello
\end{document}
```

Here is the minimal example using EuropeCV:

```latex
\RequirePackage{latexbug}
\documentclass[nologo]{europecv}

\begin{document}

\begin{europecv}{}

\ecvpersonalinfo{}{}

\end{europecv}{}

\end{document}
```

## Log file (required) and possibly PDF file  

Below are the logs for the minimal example using EuropeCV:

Here is the "good" log (i.e., with 'pdflatex'): [good.log](https://github.com/latex3/latex2e/files/8832733/good.log)

Here is the "bad" log (i.e., with 'pdflatex-dev'): [bad.log](https://github.com/latex3/latex2e/files/8832735/bad.log)

**Comment by u-fischer** [comment]
Yes, don't load hyperref in begindocument. Use `\AddToHook{begindocument/before}`. Or alternatively load at least nameref earlier.

**Comment by FrankMittelbach** [comment]
The point is this: you can't have a rule declaration for a hook put into the hook itself and hope that it applies (because the code for the hook is already being executed when the rule is seen and thus there is no possibility to reorder the code). It therefore only applies the *next* time the hook is run and for one-time hooks that means it never applies, hence the error, because it is a coding issue (previously undedetect).

**Comment by FrankMittelbach** [comment]
Once you know that EuropeCV was updated, please code the pr here, for now I would leave it open. thanks.

**Comment by scottkosty** [comment]
Thanks for the explanations. That all sounds good. Thank you, Ulrike and Frank!
