### ISSUE TITLE
[Question] Spacing in amsmath environments

### ISSUE THREAD

**Issue by antshar** [latex3/latex2e#844]
How is the spacing between rows being calculated in `gather`, `align` etc. environments calculated?

I just want to figure out the dimension of row sep
![](https://i.stack.imgur.com/0GFzb.png)
```latex
\documentclass{article}
\usepackage{amsmath}
\setlength{\fboxsep}{0pt}
\setlength{\fboxrule}{.1pt}
\begin{document}

\begin{gather}
\fbox{$a=b$} \\
\fbox{$\dfrac22$}
\end{gather}

\end{document}
```

I tried to look up the docs, but it appears to be hidden somewhere so I couldn't find it myself.

**Comment by davidcarlisle** [comment]
I am sorry but this is not a general support forum but a form for reporting issues, please use comp.text.tex or tex.stackexchange.com or similar forums for general questions. (alhough look for `\spread@equation` in `amsmath.sty`)

**Comment by lvjr** [comment]
I noticed that https://github.com/latex3/latex2e/discussions is available. Could users ask general questions there?

**Comment by FrankMittelbach** [comment]
> Could users ask general questions there?

That wasn't really the intention, because we simply don't have the bandwidth to moderate and answer general user questions; for that sites like SX are a much better place, after all we are just a few folks and would then end up getting a lot of additional traffic that we can't handle (you can see this nicely for your package, but that is 1 package the much larger variety of core LaTeX).

**Comment by lvjr** [comment]
I know Discussions page is turned off by default. It seems some one manually turned it on. So I had the above question. Why not turn it off if it is not supported?

**Comment by FrankMittelbach** [comment]
We were thinking that it might be useful for discussions around possible features  that do not fit the simple issue/enhancement category, but not as a forum for user questions on general TeX topics. I agree that this may not be clear and we should probbly give some indication on what we intend to use it for or if that is not reasonably possible disable it again.

**Comment by lvjr** [comment]
Maybe it is a better solution to create a private `latex2e-dev` repository and use the Discussions in that repository?

**Comment by FrankMittelbach** [comment]
Not really, the idea was to discuss with others :-), but the idea may not have been thought through, we'll see --- all I can tell is that we do not intend to offer an alternative to SX or similar forums where such questions can be much better handled.

**Comment by antshar** [comment]
> we do not intend to offer an alternative to SX

It should be an alternative but rather more dedicated place to ask about the source code that a really small amount of people know well on SX, additionally they are not constantly monitor questions there, so my chances to get an answer to the question are really small. If you think that I haven't tried to ask on SX first, then you're wrong. I even started a bounty, but with no luck ([tex.stackexchange.com/q/646353/213149](https://tex.stackexchange.com/q/646353/213149))

On the other hand, here is much smaller traffic and the devs can receive emails, so the probability to get an answer related to the core is higher.

I actually spent more than a couple of hours trying to figure it out, but the dependencies in amsmath ridiculously complex and I couldn't figure out how exactly spacings are being placed.
It appears that even `\baseline` and `\lineskip` play role there, but even a text search in the sources couldn't find where those variables are used to produce the spacing.
