### ISSUE TITLE
white space handling in option code

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/latex2e#85]
LaTeX uses `\zap@space` to remove white space from package option lists. this was intended to make

`[a4paper , 12pt ]`

work like

`[a4paper,12pt]`

But it complicates processing of the option list by "keyval" handlers for example `bb= 0 0 100 100` gets passed to the package as `bb=00100100` with no way to recover, so for "complicated" options authors need to use a separate package-specific setup command such as `\foopkgsetup{bb=0 0 100 100}`.

It would be possible address this in several ways some of which are:

1.  keep the existing option handler as it is but save the "raw" lists in documented macros that could optionally be used by alternative option handlers.

2. Use a more careful space stripping code (as used by l3keys for example) that does not affect the space within option values.

3. remove all space stripping from core option list handler. Existing key-val option handlers already strip space around commas, the core `\ProcessOptions` handler would need to be extended to do this rather than rely on `\zap@space` having been applied by the package loading code.

**Comment by davidcarlisle** [comment]
A test file for the first suggestion above (saving separate lists for the raw options) might be


```

\makeatletter

\def\@fileswith@pti@ns#1[#2]#3[#4]{%
  \ifx#1\@clsextension
    \ifx\@classoptionslist\relax
      \xdef\@classoptionslist{\zap@space#2 \@empty}%
%% save raw class list
      \gdef\@raw@classoptionslist{#2}%
%% end change
      \def\reserved@a{%
        \@onefilewithoptions#3[{#2}][{#4}]#1%
        \@documentclasshook}%
    \else
      \def\reserved@a{%
        \@onefilewithoptions#3[{#2}][{#4}]#1}%
    \fi
  \else
    \def\reserved@b##1,{%
      \ifx\@nnil##1\relax\else
        \ifx\@nnil##1\@nnil\else
         \noexpand\@onefilewithoptions##1[{#2}][{#4}]%
         \noexpand\@pkgextension
        \fi
        \expandafter\reserved@b
      \fi}%
% this is zapping space from file list, possibly OK to leave
      \edef\reserved@a{\zap@space#3 \@empty}%
      \edef\reserved@a{\expandafter\reserved@b\reserved@a,\@nnil,}%
  \fi
  \reserved@a}
\let\@@fileswith@pti@ns\@fileswith@pti@ns


\def\@pass@ptions#1#2#3{%
  \expandafter\xdef\csname opt@#3.#1\endcsname{%
    \@ifundefined{opt@#3.#1}\@empty
      {\csname opt@#3.#1\endcsname,}%
    \zap@space#2 \@empty}%
% extend raw option list
    \@ifundefined{@raw@opt@#3.#1}%
      {\expandafter\gdef\csname @raw@opt@#3.#1\endcsname{#2}}%
      {\expandafter\g@addto@macro\csname @raw@opt@#3.#1\endcsname{,#2}}%
% end change
    }

\makeatother

\begin{filecontents}{zzz.sty}

\typeout{...PKG \expandafter\meaning\csname opt@zzz.sty\endcsname}
\typeout{...CLS \meaning\@classoptionslist}
\typeout{RAWPKG \expandafter\meaning\csname @raw@opt@zzz.sty\endcsname}
\typeout{RAWCLS \meaning\@raw@classoptionslist}

\@@end
\end{filecontents}


\documentclass[a b, x= x y ]{article} % no {} if \ProcessOptions is used!

\PassOptionsToPackage{a 1,b 2}{zzz}


\usepackage[bb=1 2 3 4, foo bar]{zzz}

\begin{document}

\end{document}

```

**Comment by davidcarlisle** [comment]
A sketch for idea 2. above using a more careful white space stripping in the package loaders could be the following (using the existing `expl3` trim code, but it could be back ported to 2e if we did not want to include `expl3`.)

```
\RequirePackage{expl3}
\ExplSyntaxOn
\cs_new_eq:cN { kernel@trim@spaces } \tl_trim_spaces:n
\ExplSyntaxOff
\makeatletter
\def\includeonly#1{%
   \@partswtrue
   \edef\@partlist{\kernel@trim@spaces{#1}}}
\def\@if@pti@ns#1#2{%
  \let\reserved@a\@firstoftwo
  \edef\reserved@b{\kernel@trim@spaces{#2}}%
  \@for\reserved@b:=\reserved@b\do{%
    \ifx\reserved@b\@empty
    \else
      \expandafter\in@\expandafter{\expandafter,\reserved@b,}{,#1,}%
      \ifin@
      \else
        \let\reserved@a\@secondoftwo
      \fi
    \fi
  }%
  \reserved@a}
\def\@pass@ptions#1#2#3{%
   \expandafter\xdef\csname opt@#3.#1\endcsname{%
     \@ifundefined{opt@#3.#1}\@empty
       {\csname opt@#3.#1\endcsname,}%
     \kernel@trim@spaces{#2}}}
\def\ExecuteOptions#1{%
   \edef\@fortmp{\kernel@trim@spaces{#1}}%
   \def\reserved@a##1\@nil{%
     \@for\CurrentOption:=\@fortmp\do
              {\csname ds@\CurrentOption\endcsname}%
     \edef\CurrentOption{##1}}%
   \expandafter\reserved@a\CurrentOption\@nil}
\def\@fileswith@pti@ns#1[#2]#3[#4]{%
   \ifx#1\@clsextension
     \ifx\@classoptionslist\relax
       \xdef\@classoptionslist{\kernel@trim@spaces{#2}}%
       \def\reserved@a{%
         \@onefilewithoptions#3[{#2}][{#4}]#1%
         \@documentclasshook}%
     \else
       \def\reserved@a{%
         \@onefilewithoptions#3[{#2}][{#4}]#1}%
     \fi
   \else
     \def\reserved@b##1,{%
       \ifx\@nnil##1\relax\else
         \ifx\@nnil##1\@nnil\else
          \noexpand\@onefilewithoptions##1[{#2}][{#4}]%
          \noexpand\@pkgextension
         \fi
         \expandafter\reserved@b
       \fi}%
       \edef\reserved@a{\kernel@trim@spaces{#3}}%
       \edef\reserved@a{\expandafter\reserved@b\reserved@a,\@nnil,}%
   \fi
   \reserved@a}
\makeatother

```

**Comment by komascript** [comment]
> Use a more careful space stripping code (as used by l3keys for example) that does not affect the space within option values.
…
> A sketch for idea 2. above using a more careful white space stripping in the package loaders could be the following (using the existing `expl3` trim code, but it could be back ported to 2e if we did not want to include `expl3`.)

This would break KOMA-Script's key=value options of KOMA-Script < 3.26, because the options parser relies on the IMHO documented removing of the spaces (e.g. before the `=`) by the LaTeX kernel.

After a note about this discussion (thanks to UF!), I've changed the option parser in KOMA-Script 3.26 (currently only crossing my fingers, that it will not break something else), however I'm not happy with the expectation that such fundamental things could be changed rapidly. And I would expect several bug reports of users with new LaTeX kernel but old KOMA-Script, if you really will do such a change.

**Comment by komascript** [comment]
>     3. remove all space stripping from core option list handler. Existing key-val option handlers already strip space around commas, the core `\ProcessOptions` handler would need to be extended to do this rather than rely on `\zap@space` having been applied by the package loading code.

Not every key=value option handler does this for class and package options. I've not tested what happens with the KOMA-Script option handler, if you would do this.

**Comment by josephwright** [comment]
With option 1 (the least invasive), we'd still I think want to consider the fact that braces can't currently be used in the option list. If we say 'you can use keyvals' then someone is bound to do what we are asked in https://github.com/latex3/latex3/issues/493:
```latex
foo = {bar, baz}
```
or similar.

Also, with a raw list, how do we handle removing options? They presumably need to be cleaned up from both lists ... I guess we'd want to provide a single kernel function for doing that (so we can check that we get space/brace handling right).

**Comment by josephwright** [comment]
@komascript There are multiple options outlined (in addition of course to 'do nothing') precisely because any change here has the potential to cause issues in a variety of places. We want to see what might be workable, and get a full set of tests, before anything is actually altered.

For example, @davidcarlisle's option 1 would leave existing code entirely unchanged, but allow keyval handlers to be updated to access the raw information *if they want it*. That is by far the least risky change (and one the team have pondered before). But there would still be some questions to cover about braces, option removal and so on, as I've said.

**Comment by davidcarlisle** [comment]
On Mon, 22 Oct 2018 at 07:16, komascript <notifications@github.com> wrote:

> 3. remove all space stripping from core option list handler. Existing key-val option handlers already strip space around commas, the core `\ProcessOptions` handler would need to be extended to do this rather than rely on `\zap@space` having been applied by the package loading code.
>
> Not every key=value option handler does this for class and package
> options. I've not tested what happens with the KOMA-Script option handler,
> if you would do this.
>

yes, actually I suspect that this option isn't feasible (note I didn't
suggest any code here) it sounds simple enough but would take extesnive
changes to \ProcessOptions to make it work and would be likely to to have
too many compatibility issues.

It may be that we don't change anything at all at this time, (that's why we
opened an issue rather than change the code) but in particular option 1
(just saving, but not using the unprocessed lists) should be compatible
with existing classes I'd hope as basically it's only changing the
"filewithoptions" code, which should be called before the class is loaded?

David

**Comment by FrankMittelbach** [comment]
Am 22.10.18 um 08:12 schrieb komascript:
> This would break KOMA-Script's key=value options of KOMA-Script < 3.26, 
> because the options parser relies on the IMHO documented removing of the 
> spaces (e.g. before the |=|) by the LaTeX kernel.

in what way would that suggestion back the key value parser of KOMA 
script? that suggestion was to not remove the spaces *inside* the option, eg

  foo = bar baz ,   -> key is 'foo' value is 'bar baz'

in contrast to  the current situation where the value becomes 'barbaz'
making it virtually useless


> however I'm not happy with the 
> expectation that such fundamental things could be changed rapidly.

why would changing them slowly be better? longer time with more breakage?

Change will always ever break something that then needs fixing, 
spreading change over a longer period just means several times breakage

my experience is that long time doesn't make anybody fix stuff up front 
despite telling people to do so, so it also doesn't really help in that 
respect.

> And I 
> would expect several bug reports of users with new LaTeX kernel but old 
> KOMA-Script, if you really will do such a change.

in what scenario do you expect users to have old KOMA but new kernel? 
I'm mean this is not impossible, but normally people only get a new 
kernel if they update their distribution and that normally means 
packages and classes are also updated.

**Comment by davidcarlisle** [comment]
On Mon, 22 Oct 2018 at 07:47, Joseph Wright <notifications@github.com>
wrote:

> With option 1 (the least invasive), we'd still I think want to consider
> the fact that braces can't currently be used in the option list. If we say
> 'you can use keyvals' then someone is bound to do what we are asked in
> latex3/latex3#493 <https://github.com/latex3/latex3/issues/493>:
>
> foo = {bar, baz}
>
> or similar.
>
> Also, with a raw list, how do we handle removing options? They presumably
> need to be cleaned up from both lists ... I guess we'd want to provide a
> single kernel function for doing that (so we can check that we get
> space/brace handling right).
>
>
>
Probably I'd just recommend that classes/packages offering an extended
option handler just leave
\@unusedoptionlist as \@empty
and effectively say they handle them all, the removing code is very fragile
and only used for the "unused global option" warning
so in practice I think doesn't do anything useful if packages are accepting
colorlinks=true   even though that avoids the error that pagesize={1in,1in}
has with braces.

**Comment by josephwright** [comment]
@davidcarlisle  Perhaps. I was thinking for an `l3keys`-based approach, at least, I'd use the 'set known' function, then take the unknown list, apply `\zap@space` and return the result as `\@unusedoptionlist` ...

**Comment by josephwright** [comment]
@FrankMittelbach  I think that @komascript means that currently one can assume (ConTeXt-like)
```latex
<key>=<value>,
```
with not spaces at all, so can use a simple
```
\def\handle@key#1=#2,
```
which breaks if there can be a space after `#1` or before `#2` ...

**Comment by komascript** [comment]
Am Montag, 22. Oktober 2018, 18:40:00 CEST schrieb Frank Mittelbach:
> in what way would that suggestion back the key value parser of KOMA
> script? that suggestion was to not remove the spaces *inside* the option, eg
> 
>   foo = bar baz ,   -> key is 'foo' value is 'bar baz'

As I've already wrote, KOMA-Script relies on removing the spaces, so in this 
case the key would be 'foo ' and won't be found as existing. Currently there 
wasn't any reason to remove spaces for options without spaces.

> why would changing them slowly be better?

Inspection, testing, changing and testing again needs time. KOMA-Script is a 
hobby not a job. So the time is very, very limited. OK, you could say, if I do 
not have the time to read all your discussions and to do necessary changes in 
KOMA-Script immediately I should not maintain such a large package. Sometimes 
I think, this is very true.

> in what scenario do you expect users to have old KOMA but new kernel?

Such things happen more often than you expected. E.g. packages in local TEXMF 
trees, as part of templates, because of making only an admin update with 
miktex but having KOMA-Script as user package etc.

> I'm mean this is not impossible, but normally people only get a new
> kernel if they update their distribution and that normally means
> packages and classes are also updated.

You are thinking about a perfect world …

**Comment by davidcarlisle** [comment]
On Mon, 22 Oct 2018 at 19:12, Joseph Wright <notifications@github.com>
wrote:

> @davidcarlisle <https://github.com/davidcarlisle> Perhaps. I was thinking
> for an l3keys-based approach, at least, I'd use the 'set known' function,
> then take the unknown list, apply \zap@space and return the result as
> \@unusedoptionlist ...
>
>
>
As long as it doesn't (as now) completely die if a value contains `{}` I'm
not too worried about the unused option list
so if an extended option handler disables it I don't think that is too bad

`\usepackage[a=b,c={1,2,3}]{hyperref}`

ought I think be logically the same as

`\usepackage{hyperref}`
`\hypersetup{ a=b,c={1,2,3}}`

but the latter form doesn't (shouldn't?)  modify the options lists.

Currently they are documented as being the same, except you have to use the
second form if the value contains spaces or {}, but if it had access to the
lists prior to space removal these could easily be made the same (just by
setting `\opt@hyperref.sty` to the original list, then using the current
code.

**Comment by wspr** [comment]
To work around issues with compatibility (both forward and backwards), what about adding a new document macro like \globaloptions to be used before \documentclass?

**Comment by davidcarlisle** [comment]
I added a checkin along the lines of the first proposal above

https://github.com/latex3/latex2e/commit/f2b99b6879170534c4a4ec9a69ea6767f45d06e4

As it leaves the original option lists unchanged (with spaces removed just as before) I do not think it should affect KOMA-script option handling (@komascript ) but we will do more testing before any release.

**Comment by davidcarlisle** [comment]
The change above was reverted at 163c9dc333010616a65e46963e7679bbaf97b2b1 however the basic issue still needed to be addressed to allow l3keys (at least) use in options, but in  a more compatible way than the first suggestion here.

**Comment by davidcarlisle** [comment]
Marking this as won't fix, we may look to adding a more comprehensive key-value interface at some point which would address white space issues, but current implementation is assumed by too many classes to make incremental changes.

**Comment by FrankMittelbach** [comment]
let's reconsider for 2021

**Comment by car222222** [comment]
Consider what?  I hope it means this:
 "a more comprehensive key-value interface"
as this will probably be needed as we further develop the CamelCase/design/package layer (above both 2e and l3 programming).
