### ISSUE TITLE
Apparent typos or occasional lacks of clarity found in usrguide

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#853]
On top of page 5
```
\ProvideDocumentCommand creates a new definition for ⟨function⟩
```
should presumably be
```
\ProvideDocumentCommand creates a new definition for ⟨cmd⟩
```
as there was never any `⟨function⟩` in the boxed display.

On page 9
```
For example, this command
     \NewDocumentCommand \foo { >{\TrimSpaces} e{_^} }
     { [#1](#2) }
applies \TrimSpaces to both arguments.
```
but the paragraph before mentions `E` not `e`.

on top of page 10
```
If only a single character ⟨token⟩ is used for the split, any category code 13 (active) character matching the ⟨token⟩ will be replaced before the split takes place.
```
What does "replaced" mean?

on page 10
```
the function \ProcessList is available to apply a ⟨function⟩ to every entry in a ⟨list⟩.
```
What is a "⟨function⟩"? This concept does not appear to be defined.
The example mentions `\SomeDocumentCommand`.  Is a DocumentCommand a "⟨function⟩"?
The first mention of "function" is
```
the parser does not simply need to know the number of arguments for a function
```
on page 2 but the "function" concept is never defined. For example the sentence
```
A command with a verbatim argument will produce an error when it appears within an argument of another function.
```
gives a hint to reader that "function" is synonymous to "command".  Maybe mentioning it explicitly could be envisioned if this is the case. I in fact feel that
```
The argument specification for the function is given by ⟨arg spec⟩, and the command uses the ⟨code⟩ with #1, #2, etc. replaced by the arguments found by the parser.
```
on page 4 is very confusing. Is  `⟨cmd⟩` what the text refers to  by "function" or is the "function" referred-to the LaTeX ` \NewDocumentCommand` in the box above (or variants)?

on page 13
```
A control sequence (or control character) token is characterized by is its name,
```
"is its" appears to be a typo.

```
The argument specifications for document commands and environments are
available for examination and use.
 \GetDocumentCommandArgSpec {⟨function⟩} 
\GetDocumentEnvironmentArgSpec {⟨environment⟩}
```
again the text mentions "commands" and the boxed stuff refers to "⟨function⟩"

Then "These functions transfer the current argument" conveys the idea that *functions*  are the LaTeX3 user level interface so one does not understand if a user also creates "functions" or "commands" via `\NewDocumentCommand` et al.

FInally in the chapter on `\fpeval` it seems one can use `sin` without parentheses (I confirmed by testing) but what about `abs(x)` as the `abs x` form is not displayed (testing shows it works).

Now when one starts playing:
```
*\message{\fpeval{sin cos 3}}
! Use of \??? doesn't match its definition.
<argument> \???  
                 ! LaTeX3 Error: Unknown fp word sincos.
<*> \message{\fpeval{sin cos 3}
                               }
? 
```
so it seems some explanations should be given about when one can drop parentheses in the input.

 (I of course recognize the interface3 or source3 text which has been there for ages...)

**Comment by josephwright** [comment]
I've corrected all of the stuff on document commands. I think the one about `\fpeval` likely needs to be considered elsewhere: I'm not sure you are supposed to be able to drop brackets!
