### ISSUE TITLE
latex-lab-footnotes: \footnote should be long

### ISSUE THREAD

**Issue by schlcht** [latex3/latex2e#863]
## Brief outline of the bug

In `latex-lab-footnotes`, `\footnote` (and `\footnotetext`) should be `\long`.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\makeatletter
\input latex-lab-footnotes.ltx
\begin{document}
A\footnote{B\par C}\footnotetext{D\par E}
\end{document}
```

## Log file (required) and possibly PDF file  
[test.log](https://github.com/latex3/latex2e/files/8934556/test.log)

--

All is fine with `\DeclareDocumentCommand\footnote {o+m} {\ETC.`

PS: Where is the argument spec `+` (and possibly others) actually documented? I've been looking through xparse.pdf and source2e, but had to resort to (gasp!) google to find out about it.

**Comment by Skillmon** [comment]
Regarding your PS: `xparse.pdf` page 3:

> First, `+` is used to make an argument long (to accept paragraph tokens). In contrast to
> LaTeX2e’s `\newcommand`, this applies on an argument-by-argument basis. So modifying
> the example to ‘`s o o +m O{default}`’ means that the mandatory argument is now
> `\long`, whereas the optional arguments are not.

**Comment by schlcht** [comment]
> Regarding your PS: `xparse.pdf` page 3:

Ah yes, thanks, I was suspecting some sort of blindness on my part.

**Comment by FrankMittelbach** [comment]
> ``
> 
> PS: Where is the argument spec `+` (and possibly others) actually documented? I've been looking through xparse.pdf and source2e, but had to resort to (gasp!) google to find out about it.

xparse and `usrguide3.pdf` (which is the usrguide after 2020 --- at some time we want to combine that  again with the relvant parts from the old usrguide but  ...)
