### ISSUE TITLE
Loading doc causes Unused global option(s) after 2022-06-01-PL1 update

### ISSUE THREAD

**Issue by heafnerj** [latex3/latex2e#864]
## Brief outline of the bug
I'm opening this issue per David Carlisle's request from the corresponding question I posted on TeX SE.

When loading the `doc` package, the following warning appears in the log. The warning does not appear if `doc` is not loaded.

```
LaTeX Warning: Unused global option(s):
    [10pt,letterpaper,10pt,letterpaper].
```

## Minimal example showing the bug

```latex
% !TEX program = lualatexmk
% !TEX encoding = UTF-8 Unicode

\RequirePackage{latexbug} 
\documentclass[10pt,letterpaper]{article}
\usepackage{doc}

\begin{document}

Hello, world.

\end{document}
```

## Log file (required)  

[joejoe.log](https://github.com/latex3/latex2e/files/8934592/joejoe.log)

**Comment by josephwright** [comment]
OK, so in `\@onefilewithoptions` it looks like rather than 
```latex
\@namedef{opt@\@currname.\@currext}{#2}%
```
we need
```latex
\expandafter\edef\csname opt@\@currname.\@currext\endcsname{\zap@space#2 \@empty}%
```
This will mean that we never touch the raw option list, but I'm not sure we can help that - thoughts?

**Comment by josephwright** [comment]
Will be addressed by https://github.com/latex3/latex2e/pull/866

**Comment by josephwright** [comment]
Fixed by 2022-06-01-PL2
