### ISSUE TITLE
Handle `\PassOptionsToPackage` in the new options mechanism

### ISSUE THREAD

**Issue by Skillmon** [latex3/latex2e#868]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

The new option mechanism handles later package/class calls by parsing their options as new options. But it doesn't handle `\PassOptionsToPackage`/`\PassOptionsToClass` calls which are used after the package/class got loaded, though this would only require running `\ProcessKeyOptions` again (plus maybe a bit of other handling that is usually done).

## Minimal example showing the current behaviour

```latex
\begin{filecontents*}{better.sty}
  \ProvidesPackage{better}[9999-12-31 shows things LaTeX should do better]
  \DeclareKeys{foo .code = \typeout{Foo was given: \detokenize{#1}}}
  \ProcessKeyOptions\relax
\end{filecontents*}

\RequirePackage{latexbug}

\RequirePackage[foo=bar]{better}\relax
\PassOptionsToPackage{foo=baz}{better}

\stop
```

## Minimal example showing the desired new behaviour

```latex
\begin{filecontents*}{better.sty}
  \ProvidesPackage{better}[9999-12-31 shows things LaTeX should do better]
  \DeclareKeys{foo .code = \typeout{Foo was given: \detokenize{#1}}}
  \ProcessKeyOptions\relax
\end{filecontents*}

\RequirePackage{latexbug}

\RequirePackage[foo=bar]{better}\relax

\begingroup
\makeatletter
\def\tmp#1%
  {%
    \endgroup
    \def\qd@stack{}% just a quick and dirty stack
    \def\qd@stack@##1{\def\noexpand##1{\unexpanded\expandafter{##1}}}
    \def\@pass@ptions##1##2##3%
      {%
        \@ifundefined{opt@fam@##3.##1}{#1}%
          {%
            \protected\edef\qd@stack
              {%
                \qd@stack@\@currname
                \qd@stack@\@currext
                \qd@stack@\qd@stack
              }%
            \def\@currname{##3}%
            \def\@currext {##1}%
            \expandafter\xdef\csname opt@##3.##1\endcsname
              {\zap@space##2 \@empty}%
            \expandafter\gdef\csname @raw@opt@##3.##1\endcsname{##2}%
            \expandafter\expandafter\expandafter\ProcessKeyOptions
              \expandafter\expandafter\expandafter
                [\csname opt@fam@##3.##1\endcsname]%
            \qd@stack
          }%
      }%
  }
\expandafter\tmp\expandafter{\@pass@ptions{#1}{#2}{#3}}

\PassOptionsToPackage{foo=baz}{better}\relax

\stop
```

Note that the above is only a minimal example showing the correct behaviour in this case, it is not meant as an implementation suggestion (it most likely doesn't handle everything correctly).

**Comment by davidcarlisle** [comment]
My initial thought is that the current behaviour is as expected.

If you Pass Options to a package then do not load it (even a suppressed second load) then the option is not used.

If I change your example to


```
\begin{filecontents*}{better.sty}
  \ProvidesPackage{better}[9999-12-31 shows things LaTeX should do better]
  \DeclareKeys{foo .code = \typeout{Foo was given: \detokenize{#1}}}
  \ProcessKeyOptions\relax
\end{filecontents*}

\RequirePackage{latexbug}

\RequirePackage[foo=bar]{better}\relax
\PassOptionsToPackage{foo=baz}{better}

\RequirePackage{better}
\stop
```

I get
```
(./better.sty
Foo was given: bar
)
Foo was given: baz
 )
```

showing that the PassOptionsToPackage does pass the option to the new handler, but you need to call the handler by loading ( the package

**Comment by josephwright** [comment]
I was imagining there was an issue with an example similar to @davidcarlisle's, but I see there is currently not - I think it's hard to argue for a hotfix here, even if there is a change - so I'm minded to release the current PL and see where we go with this in discussion.

**Comment by josephwright** [comment]
I see the point that with a keyval handler one can set options 'after the fact'. But that only works for keyval options, not for classical options, so it only works if you know the nature of the handler. At that point, one could use `\SetKeys` instead anyway.

**Comment by u-fischer** [comment]
I don't think that `\PassOptionsToPackage`  should start to execute perhaps complex option code. That would be quite a change of behaviour and we don't know in which context the command is used.

**Comment by Skillmon** [comment]
@josephwright no, that's not the case. Say we have a package A that wants to set options for package B, but not load it on its own. In the past this was only possible via `\PassOptionsToPackage` (and hoping that users would load in the correct order) or more elaborate tests. If we don't want load order to affect the document then I'd say that a `\PassOptionsToPackage` after a package was loaded means "use these options".

**Comment by davidcarlisle** [comment]
@Skillmon  I can't see that, sorry. The traditional  behaviour, and the name of the command, imply defered option specification for possible future use when/if the package is used with `\usepackage` (`\RequirePackage`). I can't see the need to make `\PassOptionsToPackage` change meaning after the first load. Its behaviour after the load would essentially be that of `\usepackage`.  The proposed behaviour:

> execute now if package loaded otherwise just specify options in case of possible load later

seems uncommon and  highly specialised and more natural to encode with a conditional, something like

```
\@ifpackageloaded{foo}
    {\SetKeys[foo]}
    {\PassOptionsToPackage{foo}}
         {a=b,c=d}
```

But almost always a simple

```
  \RequirePackage[a=b,c=d]{foo}
```

is going to do the right thing.

**Comment by FrankMittelbach** [comment]
If a package is known to use the new key/val options then a loading order independent behavior can be implemented via
```
\AddToHook{package/foo/after}{\SetKeys[foo]{a=b}}
```
and thus doesn't even need a conditional as the hook mechanism takes care of that. If the behavior on load is different to that of setting the key after the package was loaded then nothing works without explicit support by foo.sty, so imho the above is the best you can hope for and for now I don't think that needs additional sugar.

I don't think we should alter the legacy behavior of `\PassOptionToPackage`

**Comment by josephwright** [comment]
I think the team position here is agreed: no change.
