### ISSUE TITLE
Licensing of usrguide3

### ISSUE THREAD

**Issue by niruvt** [latex3/latex2e#871]
The following is an email exchange between me and the manager of TeX Live.

### My email

```
Hello Karl,

I am using TeX Live 2022.

I ran `texdoc usrguide3` on my machine and I was surprised
to see the first page of that document. It says:

  © Copyright 2020-2022, LATEX Project Team.
  All rights reserved.

How is this included in my TeX Live then? It becomes a
proprietary work, right? Please either remove the document
from the distribution or ask the maintainers to release it
with a free-culture-license.

PS: I also checked its source-code & weirdly enough it is
    LPPL-ed.

निरंजन
```

### His response

```
The words "All rights reserved" do not make a work nonfree when another
license is present, as is the case here.  The presence of the LPPL in
the source means the document is under the LPPL.

The situation would surely be clearer if the printed document also said
"released under the LPPL". Please file a report with the LaTeX people. -k
```

Kindly look into the matter.

PS: This bug-report does _not_ intend to say  "change the license and make it free". The work is the copyright of the team and it is completely their decision whether to make it free or not. I just want to have some clarity on what is the intention of the team with this regard as the members must be aware of the fact that the TeX Live doesn't distribute non-free packages.

**Comment by josephwright** [comment]
[I have transferred this issue to the LaTeX2e repository as it relates to a file here.]

**Comment by josephwright** [comment]
Note that whilst `usrguide3` has been 'selected' here, the statement has been used generally by the team  for many years on all of the documentation files.

**Comment by niruvt** [comment]
> [I have transferred this issue to the LaTeX2e repository as it relates to a file here.]

Sorry for reporting at a wrong place.

> Note that whilst usrguide3 has been 'selected' here, the statement has been used generally by the team for many years on all of the documentation files.

There was no intention of specifically targeting one work. It was just that I found this statement for the first time in the usrguide3. I didn't find it in `expl3.pdf`, `source2e.pdf`, `source3.pdf` etc.

**Comment by FrankMittelbach** [comment]
> (of course iff the team wants this to be called free).

sorry but this is nonsense. It may offend what you call free, but basically it is a statement of fact (ie copyright law). This work is copyrighted and all rights associated with that are reserved and this is true, whether stated or not (here it is stated). In US law I can give away those rights and make a work public domain, but in other countries you can't.  Having those rights allows me to grant you a license to do something with the work (but that doesn't take away the rights related to copyright) and the rights that I give tou you (as the owner of the copyright) are what counts towards with the result is free or not.

The license that is granted to you is LPPL 1.3c which is a free software license and if that is not good enough for you in terms of "free" I guess you should not use LaTeX (or TeX for that matter which as far more  stringent copyright clause).

But to bring that matter to a close, I don't mind adding a note that the work is distributed under LPPL (as suggested by Karl), but not because it is necessary but just to help people understand the difference between copyright and license.

**Comment by josephwright** [comment]
> But to bring that matter to a close, I don't mind adding a note that the work is distributed under LPPL (as suggested by Karl), but not because it is necessary but just to help people understand the difference between copyright and license.

Sounds good to me: I think we can live with a footnote on the relevant pages. Probably also an opportunity to standardise the cases noted as _not_ saying this, e.g. `expl3.dtx`.

**Comment by niruvt** [comment]
> sorry but this is nonsense.

Can I expect polite responses? Because I don't think this is how discussion works.

> It may offend what you call free, but basically it is a statement of fact (ie copyright law).

Please be a bit less judgemental and deterministic about what _I_ think and at least try to understand my point.

> This work is copyrighted and all rights associated with that are reserved and this is true, whether stated or not (here it is stated).

There are two parts of the copyright notice.

1. The first one where the owner of the copyright along with the copyrightable year is mentioned, i.e., in this case `© Copyright 2020-2022, LATEX Project Team.` (Note that conventionally it is written this way `Copyright © 2020-2022 LATEX Project Team`, but I am afraid that you will find this nonsense too.)
2. Where you explicitly state how this is supposed to be redistributed. "All rights reserved" was a way of saying that only the copyright-holder will control the distribution (which is not the case in any free-culture-work). As mentioned in the Wikipedia article cited by Ulrike:

    > The requirement to add the "all rights reserved" notice became essentially obsolete on August 23, 2000, when [Nicaragua](https://en.wikipedia.org/wiki/Nicaragua) became the final member of the Buenos Aires Convention to also become a signatory to the [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention).

but this only means that when one does not write this sentence, the distribution is still assumed to be under control of the copyright-holder (essentially non-free). Only for free-culture-works it is necessary to add the notice that says that the copyright-holder gives you the **free**dom to distribute this work which is what done by most of the free-culture-licenses, e.g., GPL, GFDL, CC-BY-SA.

> The license that is granted to you is LPPL 1.3c which is a free software license and if that is not good enough for you in terms of "free"

When did I say this? Why are you stereotyping me and my opinions? NOTHING of what you have said represents my ideas and opinions.

The scenario is currently like this:

You first say all rights of your work are reserved, then don't mention anything about it in your PDF about it being free and still expect the reader to **somehow** (I don't know how) assume that it is free. Also as described earlier, legally this implies that only the team has the control over its distribution and if I do it (which is what freedom in free-culture means) I can be sued by you. I find this work in a distribution which claims to only have free-culture-works. The distributor says as the source is LPPL-ed, it is still a free work and you should talk to the copyright-holders regarding mentioning it and (one of) the copyright-holder(s) finds this discussion nonsensical!

**Comment by FrankMittelbach** [comment]
Am 21.06.22 um 17:04 schrieb निरंजन:
>     sorry but this is nonsense.
> 
> Can I expect polite responses? Because I don't think this is how 
> discussion works.

sorry, out of bounds, agreed

(it should have been "I think X", but perhaps the statement you made 
that triggered it, shouldn't have been deterministic either perhaps?)

I still think you confuse copyright with license, the pr is about 
licensing usrguide3 but the text is about the copyright phrase.

The fact that the it is no longer needed to write "all rights reserved" 
is that even without they are reserved. This is why you need a license 
to be allowed to modify a work and the sources as well as the whole 
LaTeX distribution (which is a unit as far as the license is concerned 
(if unmodified)) is licensed under LPPL --- and that doesn't have to be 
stated on each and every piece of the work to the best of my knowledge, 
but as I said I have no issue with repeating that in a footnote to the 
pdf so can we bury that?

**Comment by josephwright** [comment]
> This is why you need a license to be allowed to modify a work and the sources as well as the whole LaTeX distribution (which is a unit as far as the license is concerned (if unmodified)) is licensed under LPPL --- and that doesn't have to be stated on each and every piece of the work to the best of my knowledge

I suspect this is the source-of-confusion. Some of the other 'documentation' licenses mentioned do have an expectation of a statement in every 'output', whereas the LPPL is more focussed on works-as-a-whole. The latter has a clear statement of being covered by the LPPL; as you say, there's no issue adding something to the PDFs.

**Comment by niruvt** [comment]
I am glad that the suggestion to include this note in the PDF is getting accepted. Thanks a lot.

> I still think you confuse copyright with license, the pr is about licensing usrguide3 but the text is about the copyright phrase.

Things indeed are confusing and the new format which excludes the concerned sentence only adds to this confusion. If we purely look at the meaning of that sentence it definitely isn't something which would be encouraged in the free-culture, but I also agree that conventionally it seems that people don't generally look at what it means.

Also if you plan to write "all rights reserved" first and then mention that this work is LPPL-ed it might sound logically inconsistent (again looking at the meaning). Because point number 2, 3, 4 from the 'CONDITIONS ON DISTRIBUTION AND MODIFICATION' section of the LPPL explicitly give users some freedoms which mostly is interpreted as only "some rights are reserved" and not "all". This is what I meant in one of my responses to Ulrike. So anyways a statement which only confuses the reader and even obsolete is better to be avoided in my opinion. I would suggest to drop "all rights reserved" entirely.

> This is why you need a license to be allowed to modify a work and the sources as well as the whole LaTeX distribution.

Sorry, but if you mean, e.g., TeX Live, by LaTeX distribution, please note that it does _not_ have one license. It explicitly says so here: https://www.tug.org/texlive/LICENSE.TL. Quoting the relevant part here.

> That said, TeX Live has neither a single copyright holder nor a single
> license covering its entire contents, since it is a collection of many
> independent packages.  Therefore, you may copy, modify, and/or
> redistribute software from TeX Live only if you comply with the
> requirements placed thereon by the owners of the respective packages.

Hence EVERY work included in the distribution must mention its own license is what they themselves recommend. Quoting from https://www.tug.org/texlive/pkgcontrib.html:

> a) First, the package must be free (as in freedom) software, available under, for example, the [LaTeX Project Public License](https://www.latex-project.org/lppl/) or [GNU General Public License](https://www.gnu.org/licenses/gpl.html). Please state the license explicitly in your package's source code, README, and/or other documentation. Those licenses (and others) contain instructions for how to apply them to your code.

If you are not referring to the TeX Live; feel free to correct me, but even in general don't you think it would be a good idea to make the reader aware of the fact that they really have the right to distribute this instead of scaring them by saying "all rights reserved"? I, being a user of LaTeX for a significant amount of time, know that it is a well known free software, but for a normal reader the `usrguide3.pdf` is also a single independent work. Hence adding the information regarding users freedom becomes important in each work.

> > > > (of course iff the team wants this to be called free).
> > > > 
> > > sorry but this is nonsense.
> > >
> > Can I expect polite responses? Because I don't think this is how discussion works.
> > 
> sorry, out of bounds, agreed
> 
> (it should have been "I think X", but perhaps the statement you made that triggered it, shouldn't have been deterministic either perhaps?)

Sorry if you felt like that. I was just trying to strongly say that this issue is not about "make it free!", it is the team's decision and whatever it is I respect it, but unfortunately things took a wrong turn.

**Comment by josephwright** [comment]
> > This is why you need a license to be allowed to modify a work and the sources as well as the whole LaTeX distribution.
> 
> Sorry, but if you mean, e.g., TeX Live, by LaTeX distribution, please note that it does _not_ have one license. 

The LaTeX distribution is the code that comes from _this_ repo (LaTeX itself plus the 'required' packages).

**Comment by josephwright** [comment]
> > a) First, the package must be free (as in freedom) software, available under, for example, the [LaTeX Project Public License](https://www.latex-project.org/lppl/) or [GNU General Public License](https://www.gnu.org/licenses/gpl.html). Please state the license explicitly in your package's source code, README, and/or other documentation. Those licenses (and others) contain instructions for how to apply them to your code.

The license is mentioned in all of the sources, as required by TeX Live, etc.

**Comment by niruvt** [comment]
> The LaTeX distribution is the code that comes from this repo (LaTeX itself plus the 'required' packages).

Thanks for the correction.

**Comment by josephwright** [comment]
@niruvt  Does the commit I've pushed today cover what you would like to see?

**Comment by niruvt** [comment]
Thanks @josephwright for making these changes.

Do they cover what I would like to see?

Definitely yes, but I would like to bring to your attention some part of my [earlier comment](https://github.com/latex3/latex2e/issues/871#issuecomment-1161975720) again.

> If you plan to write "all rights reserved" first and then mention that this work is LPPL-ed it might sound logically inconsistent (again looking at the meaning). Because point number 2, 3, 4 from the 'CONDITIONS ON DISTRIBUTION AND MODIFICATION' section of the LPPL explicitly give users some freedoms. This is interpreted as only "some rights of this work are reserved" and not "all". So anyways a statement (i.e., all rights reserved) which only confuses the reader and even is declared to be obsolete is better to be avoided in my opinion. Hence I would suggest to drop "all rights reserved".

**Comment by josephwright** [comment]
@niruvt  But that is true: as @FrankMittelbach observes, it's holding the copyright that allows a license to be granted in the first place

**Comment by niruvt** [comment]
As discussed earlier, this requirement used to exist earlier, but now isn't. It has been deprecated in 2000. See for example [this](https://lists.debian.org/debian-legal/2007/06/msg00252.html) and it's [earlier thread](https://lists.debian.org/debian-legal/2007/06/msg00251.html) (though the latter mentions GPL a lot of times, the points are very much valid for LPPL-ed works too).

**Comment by FrankMittelbach** [comment]
@niruvt thanks for the suggestions, but I guess we need to agree that we disagree on the interpretation of mails that voice opinions of individuals. We have no plans to change it further.
