### ISSUE TITLE
Should \@doendpe also reset \parshape?

### ISSUE THREAD

**Issue by kvafa** [latex3/latex2e#878]
## Brief outline of the bug
When an environment sets the boolean `\if@endpe` to true, then the macro `\@doendpe` is executed which has the effect that after the environment, there is no indent. An example of such environment is `trivilist` or `center` which uses `trivilist`. 

However, when you use `\parshape` before the environment, after the environment `\parshape` is not reset. I am not sure if this counts as a bug or you wanted `\@doendpe` to act this way so I am really opening this issue in case it might be a bug.

The behavior is inconsistent so Should `\@doendpe` also reset `\parshape`? 

````tex
\makeatletter
\def\@doendpe{\@endpetrue
     \def\par{\parshape\z@\@restorepar\everypar{}\par\@endpefalse}\everypar
               {{\setbox\z@\lastbox}\everypar{}\@endpefalse}}
\makeatother
````

## Minimal example showing the bug

```tex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\begin{document}
\section{With Parshape}
\parshape 1 1cm \dimexpr\linewidth-1cm\relax
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
\begin{center}
This text should be centered
\end{center}
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
\section{Without Parshape}
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
\begin{center}
This text should be centered
\end{center}
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
\end{document}
```

## Log file (required) and possibly PDF file  

[test-vafa.pdf](https://github.com/latex3/latex2e/files/8984579/test-vafa.pdf)

**Comment by kvafa** [comment]
This is tricky and perhaps it is not ok to reset `\parshape` everywhere as the following minimal example shows.
````tex
\documentclass{article}
\makeatletter
\def\@doendpe{\@endpetrue
     \def\par{\parshape\z@\@restorepar\everypar{}\par\@endpefalse}\everypar
               {{\setbox\z@\lastbox}\everypar{}\@endpefalse}}
\makeatother
\begin{document}
\begin{itemize}
\item
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
\begin{center}
This text should be centered
\end{center}
\item Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
\end{itemize}
\end{document}
````

**Comment by davidcarlisle** [comment]
> This is tricky and perhaps it is not ok to reset

Yes, thanks for your comments. While there are use cases where resetting would be preferable, changing such a core function after all this time has real risks of changing existing documents, almost all of which will call this somewhere.

It may be that you can find the new command or paragraph hook mechanisms a safer alternative to add code in your real use cases, rather than change this long standing implicit hook.

We have decided to close with no change.
