### ISSUE TITLE
Feature request: spaces in \bibliography

### ISSUE THREAD

**Issue by snugghash** [latex3/latex2e#88]
I'm not familiar with how LateX parses, but I've just spent some time figuring out why citations are broken when my bibliography command looks like `\bibliography{genreated, manual}`. As it turns out, there should be no spaces between the two filenames.

This isn't obvious at all - not from the error messages, not from the full log, not from looking at all the code for hours. To prevent a collective waste of time and much fallen hair, I request some user friendly features - at a minimum better error messages, better would be just trimming the thing when parsing - I can't imagine spaces being a non-special character. 

Most codebases and writing use `, ` instead of `,`. No one is going to be familiar with this, and it's not even obvious from reading documentation. Just bad UX.

I'm prepared to submit a pull request making these changes if anyone familiar with the codebase can tell me where this needs to be done, and how best to do it.

**Comment by josephwright** [comment]
This is a LaTeX2e issue: I've transferred.

**Comment by u-fischer** [comment]
Simply adding \zap@space should imho work. bibtex can't handle bib-files with spaces, so there should be no danger to get failures in existing document. 

~~~~
\documentclass{article}

\makeatletter
\def\bibliography#1{%
  \if@filesw
    \immediate\write\@auxout{\string\bibdata{\zap@space#1 \@empty}}%
  \fi
  \@input@{\jobname.bbl}}
\makeatother
\begin{document}
\cite{article-minimal, doody}
\bibliographystyle{plain}
\bibliography{xampl,  biblatex-examples}
\end{document}
~~~~

Btw: There is a quite clear error message from bibtex.  You only need to check the .blg (the log-file from bibtex) or its terminal output:

~~~~
This is BibTeX, Version 0.99d (TeX Live 2018/W32TeX)
The top-level auxiliary file: test-utf8.aux
The style file: plain.bst
White space in argument---line 5 of file test-utf8.aux
 : \bibdata{xampl,
 :                 biblatex-examples}
I'm skipping whatever remains of this command
Database file #1: xampl.bib
~~~~
