### ISSUE TITLE
[ltcmd] Provide macros checking if a cmd/an env exists

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#897]
## Brief outline of the enhancement

**LaTeX2e generally cannot add new features without an extreme amount of care to accommodate backwards compatibility. Please do not be offended if your request is closed for being infeasible.**

`\New...`, `\Renew...`, and `\Provide...` do different checks on the command or envname to be (re)defined. When package and/or class provides wrappers on `\NewDocumentCommand` and its friends, sometimes it's needed to do init settings either before or after the corresponding `\New...`. See T-F-S/tcolorbox#187.

Thus a checker like `\IfDocumentCommandExistTF` will be helpful in defining
```tex
\NewDocumentCommand{\MyPkgNewCmd}{ m +m +m }{%
  \IfDocumentCommandExistTF {#1}
    {<some error>}
    {<init setting>\DeclareDocumentCommand{#1}{#2}{#3}}%
}

\NewDocumentCommand{\MyPkgRenewCmd}{ m +m +m }{%
  \IfDocumentCommandExistTF {#1}
    {<init setting>\DeclareDocumentCommand{#1}{#2}{#3}}
    {<some error>}%
}
```

Similarly, `\IfDocumentEnvironmentExistTF` for environments. Just as an example, their l3 interfaces could be named `\cmd_if_cmd_exist:NTF` and `\cmd_if_env_exist:nTF`.

**Comment by eg9** [comment]
There is already `\cs_if_exist:NTF`; for an environment you can check `\cs_if_exist:cTF`.

**Comment by eg9** [comment]
After discussion with the team, I believe you're wanting a version of `\@ifundefined`, but anyway, I feel this is the wrong approach.

You might do
```
\cs_new_eq:NN \IfDocumentCommandExistTF \cs_if_exist:NTF
\cs_new_eq:NN \IfDocumentEnvironmentExistTF \cs_if_exist:cTF
```
but I don't see why defining something like `\MyPkgNewCmd`. Just do
```
\IfDocumentCommandExistTF{\foo}{%
  <some error or warning or…>%
}{%
  \NewDocumentCommand{\foo}{<args>}{<code>}%
}
```
If your package has several of these constructions, you might define your own wrappers, but in this case it would be quite useless a package, wouldn't it?

**Comment by muzimuzhi** [comment]
> There is already `\cs_if_exist:NTF`; for an environment you can check `\cs_if_exist:cTF`.

You're right.

After reviewing my comment in https://github.com/T-F-S/tcolorbox/issues/187#issuecomment-1187651245 and `ltcmd.dtx`, I realized my original request was unclear and immature. In some way, I wanted to have some public l3 interfaces
- to _declare_ document cmds and envs (for example `\cmd_declare_cmd:Nnn` and `\cmd_declare_env:nnnn`) and 
- to check if a document cmd or env is free to be defined (for example `\cmd_if_cmd_free:NTF` and `\cmd_if_env_free:nTF`). Here `\cmd_if_cmd_free:NTF` will be a combination of `\cs_if_exist:NTF` and part of `\_cmd_check_definable:nNT`.

So that a theorem package can provide a `\MyNewTheorem` defined by
```tex
\NewDocumentCommand \MyNewTheorem { O{} m O{} } {%
  \cmd_if_env_free:nTF {#2}
    {
      \keys_set_groups:nnn {mythm} {init-group} {#1, #3}
      \cmd_declare_env:nnnn {#2} { O{} }
        {
          \keys_set_groups:nnn {mythm} {remaining-group} {#1, #3}
          <begin code>
        }
        { <end code> }
    }
    { <throw an error> }
}
```
