### ISSUE TITLE
babel: Reversed numbers in \hbox in LTR paragraph with bidi=basic-r

### ISSUE THREAD

**Issue by dcpurton** [latex3/latex2e#9]
## Brief outline of the bug

If numbers appear in an `\hbox` in a LTR paragraph of a document with `bidi=basic-r`, the numbers are reversed. This might occur in the footnote mark of a LTR quote, for example. RTL paragraphs are fine.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[nil,bidi=basic-r]{babel}
\babelprovide[import=en-AU]{australian}
\begin{document}
A LTR paragraph reverses numbers in an \verb+\hbox+. e.g., \hbox{10}.
\end{document}
```

## Log file (required) and possibly PDF file  

[babel-bidi-number-hbox.log](https://github.com/latex3/latex2e/files/1629334/babel-bidi-number-hbox.log)

**Comment by jbezos** [comment]
basic-r was devised to deal with R text only. A basic model (for both R and multilingual L) is on the way, but I'd like to extend and improve (and fix) the new layout feature before.
