### ISSUE TITLE
\makesm@sh (and \mathsm@sh)  are not \long

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#913]
## Brief outline of the bug

One may envision legitimate occurrences of `\par` in `\smash`.  But this raises an error.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\begin{document}
\noindent\hspace{-1cm}\smash{\parbox[t]{1cm}{Some\par box\par here}}X

\end{document}
```

## Log file (required) and possibly PDF file  

[testsmash.log](https://github.com/latex3/latex2e/files/9468017/testsmash.log)

```
Runaway argument?
{\parbox [t]{1cm}{Some
! Paragraph ended before \makesm@sh was complete.
<to be read again> 
                   \par 
l.5 ...hspace{-1cm}\smash{\parbox[t]{1cm}{Some\par
                                                   box\par here}}X
? X
No pages of output.
Transcript written on testsmash.log.
```

**Comment by u-fischer** [comment]
I don't think that \smash should be long. Users who really want to smash a large box, can use `\raisebox{0pt}[0pt][0pt]{...}`.

**Comment by FrankMittelbach** [comment]
Agreed. It falls in the same category as `\emph`, `\textbf`, etc., that are all deliberately not made long.
