### ISSUE TITLE
Include graphics does not handle eps files with non origin bounding box properly

### ISSUE THREAD

**Issue by iandall** [latex3/latex2e#923]
## Brief outline of the bug
When including encapsulated postscript graphics, with bounding boxes with an offset origin, the space isn't calculated properly.

In the example, the caption overlaps the graphics.

This issue does not occur with `pdflatex`, because the driver converts the eps to a pdf file correctly. With `latex` the eps file it interpreted directly (and incorrectly).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{graphicx}
\setlength{\abovecaptionskip}{0pt}

\begin{document}
\begin{figure}
  \centering
  \includegraphics{rect-bb.eps}
  \caption{\fbox{\strut Text}}
\end{figure}
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/9593349/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/9593365/test.pdf)
[test.zip](https://github.com/latex3/latex2e/files/9593366/test.zip)

**Comment by davidcarlisle** [comment]
You didn't include `rect-bb.ps` and the included eps file has a bounding box starting 0 0.

The behaviour here is driver dependent but in general latex does not clip unless `\includegraphics*` or equivalently `\includgraphics[clip]` is used. See the examples on page 12 of grfguide (which use optional arguments to specify the bouding box, but essentially the same code path.

**Comment by iandall** [comment]
Sorry about the missing `rect-bb.eps`.

However, your suggestions don't work. \includegraphics[clip] does indeed clip, but the clipped region is not the region specified by the bounding box. Specifying the `bb = 10 10 176 103` option behaves exactly the same as as relying on the default values, which is what you would expect because those are the values in the `%%BoundingBox` comment in `rect-bb.eps`.

I've attached a slightly expanded `test.tex` which uses the `clip` option and two different esp files. The bounding box for both these files correctly matches the drawing area, which can be checked opening them with `gv` (or another postscript viewer). A third case includes `rect-bb.eps` but with the bounding box from `rect.eps`. This third case rends properly. 

I expect that `rect.eps` and `rect-bb.eps` should rend identically (expect in the third case where the bounding box has been overwritten by the wrong values).

I also expect that `pdflatex` and `latex/dvipdfm` should rend this file the same. 

[test.zip](https://github.com/latex3/latex2e/files/9593748/test.zip)
[test.pdf](https://github.com/latex3/latex2e/files/9593765/test.pdf)

**Comment by davidcarlisle** [comment]
> I also expect that pdflatex and latex/dvipdfm should rend this file the same.

latex/graphicx assumes dvips so if you get any output at all with dvipdfm that is not by design.

You need

`\usepackage[dvipdfm]{graphicx}`

but again without `clip` the behviour is driver specific, latex never reads  the PostScript, it just leaves space as specified by the options or BoundingBox and references the file name. pdflatex effectively sees a clip to bounding box as the external ghostscript call to convert to pdf interprets the bounding box that way and produces a pdf with a media box as specified by the original bounding box which is then included. dvips just includes the eps file verbatim and does not clip so you get over-printing unless you use `clip` in which case latex adds a dvips-syntax literal postscript clip path (which is not likely to be understood by other drivers) If you use `[dvipdfm]` option, specials for that driver are used.

**Comment by davidcarlisle** [comment]
Interpreting an EPS boundig box in a non-postscript environment is under specified and so very system specific ; for this reason and to avoid the cost of running the conversion more than once I'd always recommend converting an eps to pdf externally and then including the pdf into pdflatex or latex/dvipdfm

**Comment by iandall** [comment]
Well that is interesting. Use dvips and it rends as expected.

Thank you.

The graphics started life as pdf's but the journal insists on eps so not much I can do about that.

**Comment by davidcarlisle** [comment]
> The graphics started life as pdf's but the journal insists on eps so not much I can do about that.

if you just use `\includegraphics{foo}` with no extension, and have foo.eps and foo.pdf  available, dvips and your journal publisher can use the eps, and pdflatex and dvipdfm can use the pdf.
