### ISSUE TITLE
[xspace] support for \nobreakspace and maybe babel shorthands

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#925]
## Brief outline of the enhancement

+ add `\nobreakspace` as new exception
+ support `babel` shorthands

### `\nobreakspace`
I tend to use `\nobreakspace` rather than `~` in macro definitions and maybe others do as well. Therefore, adding this to the known exceptions would be feasible.

```latex
\RequirePackage{latexbug}
\documentclass{minimal}
\usepackage[T1]{fontenc}
\usepackage{xspace}
\begin{document}
\def\foo{Foo\xspace}

\foo~nobreakspace with tilde

\foo\nobreakspace nobreakspace with macro

\xspaceaddexceptions\nobreakspace
\foo\nobreakspace nobreakspace like suggested: \quad
\texttt{\string\xspaceaddexceptions\string\nobreakspace}

\end{document}
```

### shorthands
The second point is quite more complicated (and probably there are just a few use-cases). Depending on the language, using `babel`'s shorthands must maybe not preceded by a space but others do. So just adding the shorthand character like `"` to the exceptions is not sufficient and it could lead to wrong output if it is used as single character when typesetting. My first thought was to add `\babelhyphen` to the exceptions. This works only with manually defined shorthands and assuming, all occurrences of `\babelhyphen` should be ignored by `xspace`, which is obviously not the case for `\babelhyphen{soft}` and therefore not the best approach.

```latex
\RequirePackage{latexbug}
\documentclass{minimal}
\usepackage[T1]{fontenc}
\usepackage{xspace}
\usepackage{babel}
\useshorthands*{"}

\begin{document}
\def\foo{Foo\xspace}
\NewDocumentCommand\babelfoo{s}{%
\par
\foo"=hyphen hard%
\IfBooleanF{#1}{\quad(shorthand using \texttt{\string\babelhyphen\{hard\}})}
\par
\foo"-hyphen soft%
\IfBooleanF{#1}{\quad(shorthand using \texttt{\string\babelhyphen\{soft\}})}
\par
\foo"weird stuff"%
}

\bigskip\textbf{babel without shorthand}
\babelfoo*

\bigskip\textbf{babel with manual shorthand}
\defineshorthand{"=}{\babelhyphen{hard}}
\defineshorthand{"-}{\babelhyphen{soft}}
\babelfoo

\bigskip\textbf{babel with manual shorthand and added exception}
\xspaceaddexceptions{\babelhyphen}
\babelfoo
\end{document}
```

Even if there would be some workaround for this approach, most of the `*.ldf` files like `ngermanb.ldf` tend to use not commands by `babel` but more or less several [La]TeX macros. So in my eyes the only general solution would be `xspace` providing some interface to filer on specific `babel` shorthands.
```latex
%\RequirePackage{latexbug}% complains about *.ldf files
\documentclass{minimal}
\usepackage[T1]{fontenc}
\usepackage{xspace}
\usepackage[ngerman]{babel}

\begin{document}
\def\foo{Foo\xspace}
\NewDocumentCommand\babelfoo{s}{%
\par
\foo"=hyphen hard%
\IfBooleanF{#1}{\quad(shorthand using \texttt{\string\babelhyphen\{hard\}})}
\par
\foo"-hyphen soft%
\IfBooleanF{#1}{\quad(shorthand using \texttt{\string\babelhyphen\{soft\}})}
\par
\foo"weird stuff"%
}

\bigskip\textbf{babel with shorthand \texttt{ngerman}}
\babelfoo

\bigskip\textbf{babel with shorthand \texttt{ngerman} and added exception}
\xspaceaddexceptions{"}
\babelfoo
\end{document}
```
If this is a feature, which could easily be added, I would be glad to see it. But please don't waste your time on this minor issue, if adding support for `babel` shorthands would require considerable effort.

**Comment by mrpiggi** [comment]
Is there any reason, why at least

    \xspaceaddexceptions\nobreakspace

is not added?

**Comment by josephwright** [comment]
@davidcarlisle missed the team discussions on this - perhaps he has a view here!
