### ISSUE TITLE
The bounding box of \textcircled{…} is wrong

### ISSUE THREAD

**Issue by PeterMuellerr** [latex3/latex2e#926]
Feeding 
```
\documentclass{standalone}
\begin{document}%
\textcircled{0}% or encircle any other single symbol, e.g., A or a.
\end{document}
```
to pdflatex yields
![mwe](https://user-images.githubusercontent.com/87096025/192191319-ff6bad14-fa86-4187-affa-6e3f815bd188.png)
The upper and lower bounds are too small; the circle is cut from above and below. I consider this a bug; this should not happen. The left and right bounds might be too large (which may be a bug or by design).

**Comment by davidcarlisle** [comment]
Please note the issue template which says you should include `latexbug` and not include contributed code such as `standalone`.

`\textcircled` is a simple accent command and so the bounding box is not under LaTeX control, it is specified by the font metrics so the choice of the font designer.  It is not at all ucommon for characters to extend slightly beyond their nominal bounding box, so if you clip tightly you ca lose some of the character.  Here you could  use `\strut\textcircled{0}` or use the options to `standalone`  to add some padding inside the clip box,

**Comment by PeterMuellerr** [comment]
@davidcarlisle The problem with using `latexbug` and, consequently dropping `standalone` for the sake of `article`, is that you don't see the bounding box (or at least I don't know how to show it). Using `standalone` exposes the problem. I always thought that this is what `standalone` does, doesn't it?

As for clipping, notice that even 0 is clipped from above (not only the circle).

**Comment by PeterMuellerr** [comment]
@davidcarlisle @josephwright Thanks; post changed as suggested.
