### ISSUE TITLE
ltluatex can’t handle all LuaTeX callbacks

### ISSUE THREAD

**Issue by khaledhosny** [latex3/latex2e#93]
## Brief outline of the bug

When trying to register a function for `wrapup_run` callback (and possibly others), ltluatex stops with an error:
```
Module luatexbase Error: Unable to register callback:
(luatexbase)             valid callback name required on input line 4
```

## Minimal example showing the bug

```latex
\input ltluatex
\directlua {
  luatexbase.add_to_callback(wrapup_run, function() print("Bye, World!") end)
}
test
\bye
```

## Log file (required) and possibly PDF file  

[l.log](https://github.com/latex3/latex2e/files/2614236/l.log)

**Comment by khaledhosny** [comment]
This is especially limiting since ltluatex overrides `callback.register` function with one that always raises an error, leaving one with no way to register such callbacks if ltluatex is loaded even indirectly by another package.

**Comment by davidcarlisle** [comment]
Yes this is a new callback added so not yet in texlive (so not in the travis test harness we run) so we haven't added it yet.

The test

https://github.com/latex3/latex2e/blob/master/base/testfiles/tlb-callbacks-001.lvt

fails if the callbacks in ltluatex and in luatex don't match so we have traditionally waited until later to update this, but we should make a development version matching luatex 1.09 available.

**Comment by davidcarlisle** [comment]
Actually it occurs to me that we could consider using the mechanism used by that test to check if the callback exists and if so register it with a warning rather than error, @josephwright ?

**Comment by davidcarlisle** [comment]
There was a syntax error in the test file ( luatexbase version takes three arguments) but if I fix that then this modified version of  `add_to_callback` appears to work:

```

local function add_to_callback(name, func, description)
  if not name or name == "" then
    luatexbase_error("Unable to register callback:\n" ..
                     "valid callback name required")
  end
  -- added !!!
  if (not callbacktypes[name]) and (callback.list()[name] ~= nil) then
   luatexbase_warning('Registering unknown callback: ' .. name)
   callbacktypes[name]=simple
  end
  -- end of change !!!
  if not callbacktypes[name] or
    type(func) ~= "function" or
    not description or
    description == "" then
    luatexbase_error(
      "Unable to register callback.\n\n"
        .. "Correct usage:\n"
        .. "add_to_callback(<callback>, <function>, <description>)"
    )
  end
  local l = callbacklist[name]
  if l == nil then
    l = { }
    callbacklist[name] = l
    if user_callbacks_defaults[name] == nil then
      callback_register(name, handlers[callbacktypes[name]](name))
    end
  end
  local f = {
    func        = func,
    description = description,
  }
  local priority = #l + 1
  if callbacktypes[name] == exclusive then
    if #l == 1 then
      luatexbase_error(
        "Cannot add second callback to exclusive function\n`" ..
        name .. "'")
    end
  end
  table.insert(l, priority, f)
  luatexbase_log(
    "Inserting `" .. description .. "' at position "
      .. priority .. " in `" .. name .. "'."
  )
end
luatexbase.add_to_callback = add_to_callback
```
If I use a locally modified `ltluatex.lua` with that change then 

```
\input ltluatex
\directlua {
  luatexbase.add_to_callback('wrapup_run', function() print("Bye, World!") end,'test wrapup callback')
}
test
\bye
```

works with luatex 1.09, producing

```
$ luatex bb119
This is LuaTeX, Version 1.09.0 (TeX Live 2019/dev) 
 restricted system commands enabled.
(./bb119.tex (/home/davidc/texmf/tex/latex/base/ltluatex.tex)
Module luatexbase Warning: Registering unknown callback: wrapup_run on input li
ne 4
 [1{/usr/local/texlive/2018/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
)</usr/local/texlive/2018/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on bb119.pdf (1 page, 10467 bytes).
Transcript written on bb119.log.
Bye, World!
```

We will anyway update the "known" list for whatever version of luatex is stable for texlive 2019, but a change like this would allow use of test versions of luatex that have additional callbacks.

**Comment by khaledhosny** [comment]
Yes, I think something along these line is needed as long as `callback.register()` is overridden.

**Comment by davidcarlisle** [comment]
in the code suggestion above I had 

`callbacktypes[name]=simple`

but the "simple" callback handler discards any output I think for an unknown default it should be

` callbacktypes[name]=exclusive`

the "exclusive" handler basically just exposes the primitive callback registration and doesn't allow multiple functions to be registered and chained together, which, since the callback signature isn't known, seems to be the right thing to do.

For the example here,`wrapup_run`, there is no return value, so `simple` would be OK, but in general it may not be, I think.

**Comment by khaledhosny** [comment]
Makes sense.

**Comment by shreevatsa** [comment]
I see this issue marked as closed, but running into what seems to be the same issue, trying to use `luatexbase.add_to_callback("input_level_string", ...` in TeX Live 2021.

(The `input_level_string` callback is not well documented but *is* mentioned in the LuaTeX manual…)

It seems that from time to time LuaTeX will add new callbacks, and then lualatex will prevent those callbacks from being used in any way at all until they are added to the list in ltluatex… is some sort of workaround possible? Maybe changing the error to a warning, or exporting`luatexbase.callback_register_use_at_your_own_risk` or something, so that it can be used when needed?

**Comment by davidcarlisle** [comment]
@shreevatsa the test suite does have tests that warn if the list of callbacks has additions or deletions from the list in ltluatex, so normally we've managed to keep more or less in sync with changes

with lualatex you get

```
Module luatexbase Error: Unable to register callback.
```

with luatex-dev it is known and you get

```
Module luatexbase Error: Cannot add second callback to exclusive function
```

which isn't quite the outcome I expected, I'll investigate...

**Comment by PhelypeOleinik** [comment]
@shreevatsa As David said, with `lualatex-dev` the callback is registered (I added it to implement `\tracingstacklevels`), but it was added as an `exclusive` type of callback, so it doesn't accept a second `add_to_callback`, so you need to `luatexbase.remove_from_callback('input_level_string','tracingstacklevels')`, and then `luatexbase.add_to_callback("input_level_string",...}`.

**Comment by davidcarlisle** [comment]
@PhelypeOleinik  it seems all the exclusive ones have ended up pre-registered?

Probably the error message should give the description string from the existing callback as currently (unless you are the person who registed it:-) it is not so easy to find out the existing callback and decode whether or not to replace it.

**Comment by PhelypeOleinik** [comment]
Yeah, that seems reasonable.  I only knew what to remove because I added it a month ago ;-)

**Comment by davidcarlisle** [comment]
@PhelypeOleinik  

```
    if #l == 1 then
      luatexbase_error(
        "Cannot add second callback to exclusive function\n`" ..
        name .. "'\nexisting callback: '" .. l[1].description .. "'\n")
    end
```

would make the error


```
Module luatexbase Error: Cannot add second callback to exclusive function
(luatexbase)             `input_level_string'
(luatexbase)             existing callback: 'tracingstacklevels'
(luatexbase)             on input line 11

```

**Comment by shreevatsa** [comment]
Sorry for the noise: I hadn't paid attention to using `lualatex-dev` versus `lualatex`. Also, something was broken with my system (macOS just installed TL 2021 yesterday) I guess, as with both `lualatex` or `lualatex-dev`, I had been getting "Undefined control sequence" for `\tracingstacklevels` (it worked fine with `pdflatex`) and partly for that reason I was trying this (but `luatexbase.remove_from_callback('input_level_string', 'tracingstacklevels')` also didn't seem to work)…  but after `tlmgr update --all` etc, everything works as expected. Thanks!
