### ISSUE TITLE
Longtable with \rowcolor leads to "Undefined control sequence" if a savebox with a table is defined

### ISSUE THREAD

**Issue by richardtorres314** [latex3/latex2e#934]
## Brief outline of the bug
When used in conjunction with the `xcolor` package, the `longtable` package will lead to a failure in compiling when a `savebox` is defined that makes use of a `tabular` environment. No PDF is produced.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}

  % Any preamble code goes here
\usepackage{longtable}
\usepackage[table]{xcolor}
\newsavebox{\stopbox}
\savebox{\stopbox}{
  \begin{tabular}{ll}
    Hello & World
  \end{tabular}
}

\begin{document}

  % Demonstration of issue here
\begin{longtable}{lll}
  \rowcolor{red}
  \# & Name             & Grade \\
  1  & Maier, Hans      & 1.0   \\
  2  & Huber, Anna      & 2.3   \\
  3  & Weißbäck, Werner & 5.0   \\
  4  & Bauer, Maria     & 3.3
\end{longtable}
  
\end{document}
```

## Log file (required) and possibly PDF file  
[profiles.log](https://github.com/latex3/latex2e/files/9791151/profiles.log)

**Comment by davidcarlisle** [comment]
Please note your test file warning

```
(latexbug)                xcolor.sty  ->  Report at: 
(latexbug)                    https://github.com/latex3/xcolor/issues 
```

Although  undefined `\CT@cell@color ` is a `colortbl` package command which could be reported at

https://github.com/davidcarlisle/dpctex/issues

That said, while simple cases sometimes appear to work, typesetting in boxes in the preamble is not supported as many things are only set up at `\begin{document}`  If you save the box in the document it works without error. (You could use a hook to automatically run this after `\begin{document}` if you do not want it explicitly in the document)

```
\documentclass{article}

  % Any preamble code goes here
\usepackage{longtable}
\usepackage[table]{xcolor}
\newsavebox{\stopbox}


\begin{document}
\savebox{\stopbox}{%
  \begin{tabular}{ll}
    Hello & World
  \end{tabular}%
}
  % Demonstration of issue here
\begin{longtable}{lll}
  \rowcolor{red}
  \# & Name             & Grade \\
  1  & Maier, Hans      & 1.0   \\
  2  & Huber, Anna      & 2.3   \\
  3  & Weißbäck, Werner & 5.0   \\
  4  & Bauer, Maria     & 3.3
\end{longtable}
  
\end{document}
```
