### ISSUE TITLE
includegraphics throws error if filename is par

### ISSUE THREAD

**Issue by joernwilms** [latex3/latex2e#942]
## Brief outline of the bug
When attempting to \includegraphics a graphics file named par (with no suffix), latex crashes with

Runaway argument?
! Paragraph ended before @set@curr@file@aux was complete.

even if, e.g., par.jpg or par.pdf exists.

(bug found by Philipp Weber in our group).

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{graphicx}

\begin{document}

\includegraphics{par}
  
\end{document}
```

## Log file (required) and possibly PDF file  
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=latex 2022.5.7)  27 OCT 2022 16:37
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**bla
(./bla.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
(/usr/share/texlive/texmf-dist/tex/latex/latexbug/latexbug.sty
Package: latexbug 2021/09/25 v1.0l Bug-classification
)
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2021/10/04 v1.4n Standard LaTeX file (size option)
)
\c@part=\count185
\c@section=\count186
\c@subsection=\count187
\c@subsubsection=\count188
\c@paragraph=\count189
\c@subparagraph=\count190
\c@figure=\count191
\c@table=\count192
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
Package: graphicx 2021/09/16 v1.2d Enhanced LaTeX Graphics (DPC,SPQR)

(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks16
)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
Package: graphics 2021/03/04 v1.4d Standard LaTeX Graphics (DPC,SPQR)

(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty
Package: trig 2021/08/11 v1.11 sin cos tan (DPC)
)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg
File: graphics.cfg 2016/06/04 v1.11 sample graphics configuration
)
Package graphics Info: Driver file: dvips.def on input line 107.

(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/dvips.def
File: dvips.def 2017/06/20 v3.1d Graphics/color driver for dvips
))
\Gin@req@height=\dimen139
\Gin@req@width=\dimen140
)
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-dvips.def
File: l3backend-dvips.def 2022-01-12 L3 backend support: dvips
\l__pdf_internal_box=\box50
\g__pdf_backend_object_int=\count193
\l__pdf_backend_content_box=\box51
\l__pdf_backend_model_box=\box52
\g__pdf_backend_annotation_int=\count194
\g__pdf_backend_link_int=\count195
\g__pdf_backend_link_sf_int=\count196
)
(./bla.aux)
\openout1 = `bla.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 5.
LaTeX Font Info:    ... okay on input line 5.

Runaway argument?
! Paragraph ended before @set@curr@file@aux was complete.
<to be read again> 
                   par 
l.7 \includegraphics{par}
                         
? q
OK, entering batchmode...
! Missing endcsname inserted.
<to be read again> 
                   scan_stop: 
l.7 \includegraphics{par}
                         
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

! Use of ??? doesn't match its definition.
<argument> ???  
                ! LaTeX3 Error: scan_stop: invalid in file name. Lost: mode_...
l.7 \includegraphics{par}
                         
If you say, e.g., `\def\a1{...}', then you must always
put `1' after `\a', since control sequence names are
made up of letters only. The macro here has not been
followed by the required stuff, so I'm ignoring it.

! Missing endcsname inserted.
<to be read again> 
                   scan_stop: 
l.7 \includegraphics{par}
                         
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

! Use of ??? doesn't match its definition.
<argument> ???  
                ! LaTeX3 Error: scan_stop: invalid in file name. Lost: mode_...
l.7 \includegraphics{par}
                         
If you say, e.g., `\def\a1{...}', then you must always
put `1' after `\a', since control sequence names are
made up of letters only. The macro here has not been
followed by the required stuff, so I'm ignoring it.

! LaTeX Error: File `par' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 \includegraphics{par}
                         
I could not locate the file with any of these extensions:
.eps,.ps,.eps.gz,.ps.gz,.eps.Z,.mps
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

 [1

] (./bla.aux) ) 
Here is how much of TeX's memory you used:
 1429 strings out of 478288
 26951 string characters out of 5849316
 313120 words of memory out of 5000000
 19682 multiletter control sequences out of 15000+600000
 469259 words of font info for 28 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 55i,5n,62p,176b,554s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on bla.dvi (1 page, 272 bytes).

**Comment by davidcarlisle** [comment]
Thanks for this report, it's actually more general:

```
\documentclass{article}

\begin{document}

\input{par}

\end{document}
```

fails in the same way. We will fix this in the next release

**Comment by davidcarlisle** [comment]
This runs without error if you have `par.tex` and `par.png` locally

```
\documentclass{article}
\usepackage{graphicx}
\makeatletter
\long\def\@set@curr@file@aux#1{%
%%%%%
  \expandafter\ifx\csname\endcsname#1%
    .tex\else\string#1\fi}
\makeatother
\begin{document}

\input{par}

\includegraphics{par}

\end{document}
```
