### ISSUE TITLE
\input foo on command line omits latex format ident from log

### ISSUE THREAD

**Issue by kberry** [latex3/latex2e#944]
any input file, e.g., minimal.tex:
```
\documentclass{article}
\begin{document}
\end{document}
```

Run: `pdflatex '\input minimal.tex'`. Log file contains (no latex2e/l3 ident):
```
**\input minimal.tex
 (./minimal.tex
(/u/texlive/karl/Master/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
...
```
although the info appears on the terminal:
```
LaTeX2e <2022-06-01> patch level 5
L3 programming layer <2022-10-26> (./minimal.tex
(/u/texlive/karl/Master/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
```

Run: `pdflatex minimal.tex`. Log file now contains the ident info:
```
**minimal.tex
(./minimal.tex
LaTeX2e <2022-06-01> patch level 5
L3 programming layer <2022-10-26>
(/u/texlive/karl/Master/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
```

If it's possible to fix, that would be nice. I habitually have to run tex with \various\commands  before the \input on the cmdline. Clearly not crucially important though. --thanks, karl.

**Comment by car222222** [comment]
"If it's possible to fix, that would be nice."

But us this difference caused by something in LaTeX? 
Or is it just the way TeX works?

**Comment by josephwright** [comment]
What @car222222  said: isn't this just the way TeX treats `\everyjob`?

**Comment by davidcarlisle** [comment]
you would really need an `\everylog`  engine hook that ran when the log is opened, which wouldn't be a bad idea, along with normalising access to some parts of the banner  that the engine outputs at that point, like luatex's  `\luatexbanner`

**Comment by josephwright** [comment]
Indeed, the banner has lots of info we can't get otherwise, but is not uniformly available

**Comment by FrankMittelbach** [comment]
I guess David's idea of having an `\everylog` would be best in the long run.

I thought that would perhaps be possible to check the value of `\jobname` and if that is `texput` delay the message until seeing `\documentclas`. However jobname works like the Heisenberg principle ... if you look at it you seem to freeze it, so that is no go to determine if we haven't opened the log. So that doesn't seem to do the trick and I can't think of any other approach from the LaTeX level.

Always delaying is a bad idea in my opinion, because then it comes largely in essentially a random place  and not at the beginning.

**Comment by u-fischer** [comment]
Perhaps we could add an additional line at the end of the document? E.g. just before the file list, then it would nicely continue if \listfiles is used.

**Comment by josephwright** [comment]
@u-fischer  You remind me I keep thinking about extending `\listfiles` to optionally MD5 hash the files, for debugging when people have weird issues. One to track in a separate issue?

**Comment by FrankMittelbach** [comment]
I think repeating it at the very end might work nicely. 

@josephwright MD5 hashes should definitely be in a separate issue. Not sure you want this by default because it would most likely make the lines too wide and badly spoil the listing (I guess). Anyway, worth thinking about but elsewhere I would say.

**Comment by FrankMittelbach** [comment]
```
latex '\AddToHook{enddocument/afteraux}{\typeout{ ***********}\the\everyjob\typeout{ ***********}}\input{foo}'
```
comes out nice enough I think (if we remove the `\everyjob{}` in `\process@table`)

**Comment by josephwright** [comment]
@FrankMittelbach  Logged as a separate issue for discussion

**Comment by car222222** [comment]
As a coda to @kberry's original issue, here is an admonition and some advice;
LaTeX provides many facilities that obviate any need to use the **-prompt.  
For many reasons it would be wise to use these facilities so that the original issue becomes moot.

**Comment by FrankMittelbach** [comment]
I don't really think that there is a way to make this become moot in all cases. You need the command line if you are running documents with different  overall settings to be changed from the outside, e.g. TUGboat production, that is you don't want to touch the sources but pass, e.g. option "final" to each document (and that in a scripted environment).
For the Companion production some of my scripts do that too and then you end up with a line `pdflatex '<cmd> \input{...}'`

**Comment by car222222** [comment]
Yes I can see the need to do that kind of thing in scripts.
I did not realize that this is equivalent to using the **-prompt.
