### ISSUE TITLE
Provide a companion to \listfiles that can list MD5 hashs

### ISSUE THREAD

**Issue by josephwright** [latex3/latex2e#945]
As mentioned in https://github.com/latex3/latex2e/issues/944, there are times in debugging when it would be useful to rule out 'locally edited files' where a change isn't obvious in the `\listfiles` details. With MD5 primitives available in all engines, one could imagine a variant of the file list that includes this information.

Assuming that hashing would not always be active, this would have to activate hashing for files loaded _after_ the new command was given, as this is the only time we can be sure they have not been changed/written to. It would therefore only work for non-expandable usage.

With the file hook system in place, implementation should be straight-forward. Suggested name would be `\listfilehashes`.

**Comment by car222222** [comment]
How time-costly is calculating these hashes?

**Comment by FrankMittelbach** [comment]
Probably noticeable if you have many files, but given that it is only done for debugging when you explicitly put `\listfilehashes` in your document, that would probably not matter. It would be a different matter if we do it all the time, but by default nothing extra would happen unless explicitly requested.

**Comment by car222222** [comment]
Understood, and thanks for the extra details.

**Comment by josephwright** [comment]
I'm imagining that the kernel itself would save MD5 data during format-building, so this would be available to e.g. us when testing dev formats :)

**Comment by FrankMittelbach** [comment]
@josephwright how would you do anything in the kernel? other than recording the kernel file versions? I mean those could be tampered with too, so it is probably worth to record an MD5 of the format itself but usually the problems is with local versions is that people make changes to some package and do not reflact it in the version line and those we can only determine if we test each file used at the end of the run. Or am I missing something?

**Comment by josephwright** [comment]
@FrankMittelbach  I'm mainly thinking of local `expl3` installs for the team - but the main priority would be as you say local packages or similar

**Comment by FrankMittelbach** [comment]
ah, yes, save us from our own private versions :-) but in either case there would be no impact on the runtime, so I think this is a valid idea. Of course it would be valid to have  different checksums for the kernel if the kernel MD5 includes the cfg files. On the other hand, probably nobody is making changes ti them these days.

**Comment by josephwright** [comment]
I've now looked again at this. My suggestion is adding a keyval argument to `\listfiles`, something like
```latex
\listfiles[include-hashes, include-sizes]
```
yielding something like
```
 *File List*
 article.cls    2023/05/17 v1.4n Standard LaTeX document class
    (size: 20144, hash: FBCF51733730D8F1A62143512FF5B1FE)
  size10.clo    2023/05/17 v1.4n Standard LaTeX file (size option)
    (size: 8448, hash: 74078C4A887F2CDCD57C3EC111622740)
l3backend-luatex.def    2023-11-04 L3 backend support: PDF output (LuaTeX)
    (size: 30409, hash: 4F844A9024E5A9B01FC5871F268DC768)
  ts1cmr.fd    2023/04/13 v2.5m Standard LaTeX font definitions
    (size: 2430, hash: A2E8A746C2C6DDF1DF1FB6AD609D5F6A)
 ***********
```
Does that seem OK?

**Comment by FrankMittelbach** [comment]
I would just call the keys "hashes", "sizes" and also "title" (with title being true by default so giving you the same as right now)

**Comment by FrankMittelbach** [comment]
or rather "titles" if the others are plural

**Comment by muzimuzhi** [comment]
Maybe also "full-names" (using `\file_full_name:n`)? Currently full names (full file paths) scatter throughout the log.
