### ISSUE TITLE
Make `longtable` aware of `geometry`'s `\restoregeometry` happenning during long tables

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#949]
## Brief outline of the enhancement

It would be nice for the `longtable` package to be able to deal with the `geometry`'s `\restoregeometry` that could happen during the long tables. Currently, the geometry is restored only at the first page that follows the end of the long table, as shown by the following MCE.

## Minimal example showing the current behaviour

(The `geometry.sty` and `mwe.sty` files are needed to demonstrate the problem.)

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!
\documentclass{article}
\usepackage{longtable}
\usepackage[paperheight=7cm,showframe]{geometry}
\usepackage{afterpage}
\usepackage{mwe}

\begin{document}
\pagestyle{empty}
\newgeometry{top=2cm}
\afterpage{\aftergroup\restoregeometry}

\begin{longtable}{l}
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
  Foo \\
\end{longtable}

\lipsum[1-2]
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/200191247-0b09d3b2-3b77-4ee5-aa71-44b022f490e8.png)

**Comment by davidcarlisle** [comment]
`geometry` OK but please note any errors flagged by latxbug but

```
! Package latexbug Error: Third-party file(s)
(latexbug)                
(latexbug)                This test file uses third-party file(s)
(latexbug)                
(latexbug)                ==============
(latexbug)                mwe.sty
(latexbug)                ==============
```

We already allow `lipsum` package which would define `\lipsum` without error here, or (better for tracing) you can add text explicitly.

For the actual request, in general I'm not sure how this could work if you change layout mid-table while longtable is preserving column widths over pages. Your example has the  easier case of just adjusting the top margin, but `\restoregometry` can be much more intrusive, changing the width of the text bock.

**Comment by dbitouze** [comment]
Sorry for `mwe` instead of `lipsum`.

I see your point about `\restoregometry` which can be intrusive. So let say this feature request is just for the vertical margins :)

**Comment by davidcarlisle** [comment]
I don't think adding this to `longtable` is going to be feasible or clearly desirable.  As commented above, most changes of page geometry are going to conflict with longtable preserving column widths.  The most reasonable use case: adjusting the top margin of the first page, is often more simply addressed by adjusting `\LTpre` or adding `\vspace` somewhere.

Certainly the example given of  `\afterpage{\aftergroup\restoregeometry}` isn't supportable at all.  Quite where a token appears if you aftergroup out of an `\afterpage` insertion is not documented or documentable. It just does what it does. In particular it could appear somewhere completely different if the implementation changed in any way, as would be needed to add the requested feature. This shows the risks of making large structural changes, some existing uses always break, so the added feature has to be worth the cost, and here I'm not convinced it is, sorry.
