### ISSUE TITLE
Feature Request: Better error messages for non-ASCII symbols in labels.

### ISSUE THREAD

**Issue by Volker-Weissmann** [latex3/latex2e#95]
As you might know, labels can't contain non-ASCII symbols. So this:
\label{abcßdef}
won't compile. This isn't a problem, but an error message that is easier to understand would be nice. Currently the error message is:

```
(./main.out) (./main.out) [1] (./main.aux
! Missing \endcsname inserted.
<to be read again> 
                   \OT1\ss 
l.21 ...l{abc\IeC {\ss }def}{{}{1}{}{Doc-Start}{}}
```
An error message like "Only ASCII characters are allowed in labels" or "Label contains illegal symbols: 'ß'" would be nicer.

**Comment by Stone-Zeng** [comment]
It depends on engine. If you use XeTeX, for example, even Chinese characters can be used in `\label{...}`.

**Comment by FrankMittelbach** [comment]
You might want to play around with the following patch (not sure it is yet complete)

```
\documentclass{article}

\usepackage{textcomp}

\makeatletter

\def\IeC{%
 \ifincsname
   \expandafter\IeC@string
 \else
   \ifx\protect\@typeset@protect
     \expandafter\expandafter\@firstofone
   \else
      \noexpand\IeC
   \fi
 \fi
}

\def\IeC@string#1{\string#1}

\def\set@display@protect{\let\protect\string \let\IeC\IeC@string}


\makeatother

\begin{document}

\section{A}
\label{abß}
\label{öfoo}

\label{bar€}

Some refs: \ref{abß} and \ref{öfoo} and \ref{bar€}

\fontencoding{T1}\selectfont

Some refs: \ref{abß} and \ref{öfoo} and \ref{bar€}

\end{document}
```
One area where this will go wrong is when the UTF char is not set up for use with LaTeX. In that case the error message will create havoc (remove "textcomp" to see) but that would hard to catch if at all possible.

Not sure yet if this is robust enough to be included into any future release, but feedback with real documents would be appreciated.

**Comment by aminophen** [comment]
Hi LaTeX team,

According to https://github.com/latex3/latex2e/blob/develop/base/utf8ienc.dtx#L257, I noticed that utf8ienc.dtx is going to use \ifincsname.

However, originally it is a pdfTeX feature and is currently usable in pdfTeX/XeTeX/LuaTeX. It is still not implemented in e-pTeX/e-upTeX of TL2019. When the code is introduced, users of pLaTeX and upLaTeX will be unable to use utf8.def. (Same issue can happen for users of Lamed on Aleph, but maybe few.) Should we (texjp) implement \ifincsname for e-pTeX/e-upTeX for TL2020?

**Comment by FrankMittelbach** [comment]
> However, originally it is a pdfTeX feature and is currently usable in pdfTeX/XeTeX/LuaTeX. It is still not implemented in e-pTeX/e-upTeX of TL2019. When the code is introduced, users of pLaTeX and upLaTeX will be unable to use utf8.def. (Same issue can happen for users of Lamed on Aleph, but maybe few.) Should we (texjp) implement \ifincsname for e-pTeX/e-upTeX for TL2020?

yes please make sure that this primitive is available as soon as possible. The whole extended UTF8 handling for 8bit engines depends on having that primitive available. Sorry for not testing against your engine.

so we need to see what we can do in the meantime as we have planned (and still like to) make that update available sometime this year in fall. Maybe it is a simple as checking for the primitive and if unavailable using the old utf8.def (but probably we need more --- and of course without it the new features of being available to use UTF8 in labels file names and other places will not be available)

**Comment by aminophen** [comment]
> yes please make sure that this primitive is available as soon as possible.

OK, I raised an issue on https://github.com/texjporg/tex-jp-build/issues/83 and started working on it. 

> so we need to see what we can do in the meantime as we have planned (and still like to) make that update available sometime this year in fall.

Thanks.

**Comment by FrankMittelbach** [comment]
@aminophen   Would you have a possibility to check out an updated version from the development branch with e-pTeX/e-upTeX? I can make simple checks but real life documents would certainly better.

**Comment by aminophen** [comment]
@FrankMittelbach Yes, I'm glad to.  I will try the 'develop' branch for some time.

**Comment by FrankMittelbach** [comment]
well, right now it will not yet work because it requires \ifincsname

**Comment by aminophen** [comment]
> right now it will not yet work because it requires \ifincsname

```
\documentclass[a4paper]{article}
\begin{document}
[Æ]
\end{document}
```
```
! Undefined control sequence.
\UTFviii@two@octets ->\ifincsname 
                                  \expandafter \UTF@two@octets@string \else ...
l.3 [^^c3
         ^^86]
?
```

**Comment by FrankMittelbach** [comment]
@aminophen you can try the following (looks like it works here but I'm not yet ready to put it up):

At the top of utf8.def put

```
\ifx\ifincsname\@undefined  % old e-pTeX or e-upTeX engines
  \input utf8-2018.def
  \expandafter\@firstofone
\else
  \expandafter\@gobble
\fi
  \endinput
```

and copy the old utf8.def  as utf8-2018.def into the test tree.

**Comment by aminophen** [comment]
@FrankMittelbach 

> you can try the following

for simple test it seems working, thanks.

**Comment by FrankMittelbach** [comment]
@aminophen I'm currently packing up a new develeopment upload. It should then contain the "temp" fix. Once `\ifincsname` is available it should then go out again to make the new features also available to pTeX users

**Comment by FrankMittelbach** [comment]
@aminophen  development branch should now have the new code available

**Comment by aminophen** [comment]
H. Kitagawa added \ifincsname for e-pTeX/e-upTeX in [r51624](https://www.tug.org/svn/texlive?view=revision&revision=51624); will be available in TL2020.

**Comment by FrankMittelbach** [comment]
@aminophen cool, thanks. Does the code in development branch appear to work with current e-pTeX/e-upTeX? because that is roughly how it would appear in October (except that unrelated topics may be addressed by then.

**Comment by aminophen** [comment]
> Does the code in development branch appear to work with current e-pTeX/e-upTeX?

For me it seems fine on both TL2019 e-(u)pTeX and TL2020/dev, thanks.  Maybe I can ask some other people to test the development branch.

**Comment by josephwright** [comment]
Should be fixed in 2019-10-01 release.
