### ISSUE TITLE
Broken internal links in docstrip.pdf

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#951]
## Brief outline of the bug

internal hyperlinks from the index of `docstrip.pdf` appear to fail.

## Minimal example showing the bug

![Capture d’écran 2022-11-08 à 09 31 58](https://user-images.githubusercontent.com/2589111/200514721-a4069fb4-55bb-4c67-bdee-07f6f53cc01a.png)

Clicking on the  `1` brings back to front page.

Clicking on `13` leads to  page 13 which at bottom starts the Implementation section.  This may actually be correct.

## Log file (required) and possibly PDF file  

See `docstrip.pdf`.

By the way its front page says to report to https://latex-project.org/bugs.html category (latex) but I figured I should come here. Or am I wrong ?

## Context

I was trying, having 30mns of free time, to understand what "module" means under the legacy (pre-latex3 additions) docstrip/doc system.

By the way the reference in `doc.pdf` says:

```
[6] Frank Mittelbach, Denys Duchier and Johannes Braams. docstrip.dtx (to appear). The file is part of the DOC package.
```

Is the `(to appear)` still actual?  Anyway this is why I opened `docstrip.pdf`

**Comment by FrankMittelbach** [comment]
thanks for the suggestions.

> ## Brief outline of the bug
> 
> internal hyperlinks from the index of `docstrip.pdf` appear to fail.

Possibly appears so, but it is simply the result of where a `\changes` entry is placed. In the particular source most of the general entries are placed at the very beginning, some at the beginning of the code section (30 years of changes you know ...).

I added a paragraph in doc.dtx to explain that a bit:
```
% Note that in the history listing, the entry is shown with the page number
% that corresponds to its place in the source, e.g., general changes put at the
% very beginning of the file will show up with page number ``1'', change entries
% placed elsewhere might have different numbers (not necessarily always
% very useful unless you are careful).
%
```
but I have no plans to improve the output. If you think it is worthwhile, please reorder the change entries and produce a pull request against the development branch.


> 
> By the way its front page says to report to https://latex-project.org/bugs.html category (latex) but I figured I should come here. Or am I wrong ?

but this is "here" isnt it? The bug page points to the github issue tracker here. The category only means that it could be mentioned in the title (in other files it says "tools" or "graphics" or ...)

> 
> By the way the reference in `doc.pdf` says:
> 
> ```
> [6] Frank Mittelbach, Denys Duchier and Johannes Braams. docstrip.dtx (to appear). The file is part of the DOC package.
> ```
> 
> Is the `(to appear)` still actual? Anyway this is why I opened `docstrip.pdf`

yep, historical from 1989 or before. I changed it in the source.

**Comment by FrankMittelbach** [comment]
> > I added a paragraph in doc.dtx to explain that a bit:
> > ```
> > % Note that in the history listing, the entry is shown with the page number
> > % that corresponds to its place in the source, e.g., general changes put at the
> > % [cut lines]
> > ```
> 
> I had not seen that! But I had looked (today) only at PDF file... I would not have opened this ticket had I seen this explanation.

well, it is a note I added to the doc sources after I add seen your pr, so it is in result of it (and will appear next time doc is released).

**Comment by FrankMittelbach** [comment]
> ```
> 
> ```

it is a deliberate indirection. We have had to move the bug tracker in the past and we may have to move it again one day and we don't want to alter all kind of files, so that page tells you what to do and where to go.
