### ISSUE TITLE
rollback 2022-06-01 unfortunately broken (workaround available)

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/latex2e#955]
## Brief outline of the bug

Rollback to 2022-06-01 was unfortunately broken, because we missed silencing an error message that naturally occurs.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}       % <--should be always the first line (see CONTRIBUTING)!

\RequirePackage[2022-06-01]{latexrelease}

\documentclass{article}

\begin{document}

  Hello World
  
\end{document}
```

## Log file (required) and possibly PDF file  

this gives
```
L3 programming layer <2022-11-02>
(/usr/local/texlive/2022/texmf-dist/tex/latex/base/latexrelease.sty

/usr/local/texlive/2022/texmf-dist/tex/latex/base/latexrelease.sty:16818: LaTeX
 mark Error: Mark class '2e-left' already defined

For immediate help type H <return>.
 ...                                              
                                                  
l.16818 \NewMarkClass {2e-left}
                               
? 
```
plus 2 similar errors. You can just press return and the rest works correctly, but of course it is a nuisance.

**Comment by FrankMittelbach** [comment]
Workaround for the problem (until the next LaTeX release) is to add
```
\ExplSyntaxOn
\msg_redirect_name:nnn { mark } { class-already-defined }{ none } 
\ExplSyntaxOff
```
before loading the `latexrelease` package.

**Comment by mrpiggi** [comment]
I'm just curious, no elaborate answer required: shouldn't such issues be covered by the test suite? Is it because the errors were accidentally included in the `*.tlg` files? In that case, would there possibly be a way to automatically parse those files for such obvious inconsistencies as `LaTeX \w+ Error` on a commit?
