### ISSUE TITLE
[filecontents] configurable message level

### ISSUE THREAD

**Issue by mrpiggi** [latex3/latex2e#958]
## Brief outline of the enhancement

https://github.com/latex3/latex2e/blob/737ccf66dc8cc7bcb3d4357295ef5967657aaa19/base/ltclass.dtx#L2935-L2936

Would it be possible to make the info level---at least for option `force`---configurable as using a temporary file several times during one run, the periodic messages can get quite annoying.

BTW The message text could be changed to ``Overwriting file `\@currdir\@curr@file'``

## Minimal example showing the current behaviour

```latex
\RequirePackage{latexbug}
\documentclass{article}

\makeatletter
\newenvironment{fancystuff}
  {\@nameuse{filecontents*}[force]{\jobname-foo.tex}}
  {\@nameuse{endfilecontents*}}
% current workaround
\providecommand*\filec@ntents@silent{%
%  \let\@latex@warning@no@line\@latex@note@no@line%
  \let\@latex@warning@no@line\@gobble%
}
\newenvironment{fancystuff*}
  {\@nameuse{filecontents*}[force,silent]{\jobname-foo.tex}}
  {\@nameuse{endfilecontents*}}

\begin{document}
\begin{fancystuff}
some stuff
\end{fancystuff}
\begin{fancystuff}
some stuff
\end{fancystuff}
\begin{fancystuff}
some stuff
\end{fancystuff}

\begin{fancystuff*}
some stuff
\end{fancystuff*}
\begin{fancystuff*}
some stuff
\end{fancystuff*}
\begin{fancystuff*}
some stuff
\end{fancystuff*}

Done
\end{document}
```

**Comment by FrankMittelbach** [comment]
I don't think it should be silenced  via `\@gobble`;  in my opinion the overwriting attempt should get documented in the log, but I'm fine with writing it to the log only.

**Comment by FrankMittelbach** [comment]
> BTW The message text could be changed to `` Overwriting file `\@currdir\@curr@file' ``

that is actually not correct (I think). Point is TeX might find the file name somewhere on the kpathsea tree but in that case you would git get it written (and not overwritten) to your current directory.

**Comment by mrpiggi** [comment]
> that is actually not correct (I think). Point is TeX might find the file name somewhere on the kpathsea tree but in that case you would still get it written (and not overwritten) to your current directory.

You're right, I hadn't thought about that.
