### ISSUE TITLE
ltluatex’s add_to_callback doesn’t have apriority argument

### ISSUE THREAD

**Issue by khaledhosny** [latex3/latex2e#96]
luatexbase `add_to_callback()` had a `priority` argument which controls the order of inserted callbacks when there is more than one and that is really useful when one needs to run a callback before an already registered one (in my case overriding luaotfload’s `pre_linebreak_filter` by running before it and protecting the glyph ids). Since ltluatex aims to replace luatexbase (I believe), I think it should at least provide the same API.

**Comment by davidcarlisle** [comment]
unlike the original luatexbase implementation, the ltluatex version of remove_from_callback returns the removed function, this gives in fact more control than the old priority mechanism as you can completely remove all the callbacks and then reconstruct a list in whatever order.

there is an implementation of the old priority mechanism in the "new" luatexbase package as currently on ctan, which sits over the public ltluatex interface which could be used as an example.

(If this isn't enough for your needs do ping here again as there have not been many "real world"  tests of this mechanism to check it covers all use cases.

**Comment by khaledhosny** [comment]
Loading luatexbase is good enough for my needs right now. I’ll look into `remove_from_callback` later and see if I can do what I need with it.
