### ISSUE TITLE
Memoir class - Command \stockheight already defined

### ISSUE THREAD

**Issue by dpwilt** [latex3/latex2e#960]
## Brief outline of the bug

The memoir class seems to be broken - a recent upgrade of packages for MikTeX (not including memoir) causes it crash with the error message:
! LaTeX Error: Command \stockheight already defined.
               Or name \end... illegal, see p.192 of the manual.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{memoir}

\begin{document}
Hello.
\end{document}
```

## Log file (required) and possibly PDF file  

I'm sorry, I've looked through all the logs and the only entries in the logs are the
installation of the latexbug class.  I apologize for any difficulty.

Here is the list of package updates that seem to have broken things:
fancyhdr
hyperref
l3kernel
latex-graphics-dev
ltxbase
lua-uni-algos
pdflscape
ragged2e
xcharter-math

The output in the log window is below.

(C:\Users\dwilt\AppData\Local\Programs\MiKTeX\tex/latex/latexbug\latexbug.sty)
(C:\Users\dwilt\AppData\Local\Programs\MiKTeX\tex/latex/memoir\memoir.cls
Document Class: memoir 2022/07/29 v3.7r configurable book, report, article document class
(C:\Users\dwilt\AppData\Local\Programs\MiKTeX\tex/latex/etoolbox\etoolbox.sty)
(C:\Users\dwilt\AppData\Local\Programs\MiKTeX\tex/generic/iftex\iftex.sty)

! LaTeX Error: Command \stockheight already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.409 \newlength{\stockheight}
                              
?

**Comment by u-fischer** [comment]
miktex missed to update the firstaid package. There is already a bug report (https://github.com/MiKTeX/miktex/issues/1226) and the next update should repair this (the next memoir version will handle this too). In the meantime you can add the fix yourself like this:

~~~~
\makeatletter
\AddToHook{file/memoir.cls/before}[firstaid]{%
  \expandafter\def\expandafter\@tempa\string\dimen{}%
  \edef\kernel@stockheight{\expandafter\@tempa\meaning\stockheight}%
  \edef\kernel@stockwidth{\expandafter\@tempa\meaning\stockwidth}%
  \let\stockheight\@undefined
  \let\stockwidth\@undefined
}
\AddToHook{file/memoir.cls/after}[firstaid]{%
  \dimen\kernel@stockheight=\stockheight
  \dimen\kernel@stockwidth=\stockwidth
  \dimendef\stockheight=\kernel@stockheight
  \dimendef\stockwidth=\kernel@stockwidth
}
\makeatother
 
\documentclass{memoir}
~~~~

**Comment by FrankMittelbach** [comment]
nothing we can do (other than wait)

**Comment by u-fischer** [comment]
an easier work around is to use `pdflatex-dev` as `firstaid-dev` has been correctly updated.
