### ISSUE TITLE
`\NewEnvironmentCopy` just as `\NewCommandCopy`?

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex2e#963]
Sometimes, one considers on second though as sub-optimal the name originally given to a macro, and decides to give it a new name, the original one will be an alias to the new one in order to not break compatibility. For this, one can rely on `\NewCommandCopy`.

In similar cases for an environment, say `foo` to be renamed into `oof`, I guess one can just do:

```latex
\NewCommandCopy\oof\foo
\NewCommandCopy\endoof\endfoo
```

but maybe a `\NewEnvironmentCopy` command would be welcome.

**Comment by FrankMittelbach** [comment]
this is really a 2e enhancement so moved.
