### ISSUE TITLE
ltkeys is not documented in user docs

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#973]
Currently, (an abbreviated) documentation for `ltkeys` can only be found in `source2e.pdf`. It seems
- `\DeclareKeys`, `\DeclareUnknownKeyHandler`, and `\SetKeys` could be added to `usrguide` and
- `\ProcessKeyOptions` could be added to `clsguide`.

**Comment by FrankMittelbach** [comment]
Agreed. If you like to help I would certainly accept a pull request for a section documenting it in clsguide.
