### ISSUE TITLE
Documentation of l3keys2e and ProcessKeyOptions

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex2e#979]
## Brief outline of the bug

l3key2e documentation states that this package is now obsolete and that package authors should transition to the newly available ProcessKeyOptions. Unfortunately, there is no link to any other documentation nor any clue to find one about this new feature. Requests on the internet are not really helpful. Nothing found in source2e.pdf of November (search by content).
The l3key2e documentation should definitely give more info.

**Comment by josephwright** [comment]
Yes, we know this needs to be documented better :) It doesn't really belong in the `l3keys2e` docs, rather in `clsguide`.

**Comment by jlaurens** [comment]
So `l3keys2e` documentation should just mention `clsguide`.

**Comment by FrankMittelbach** [comment]
but only once it is there in full glory
