### ISSUE TITLE
tools v49390 incompatible with xcolor?

### ISSUE THREAD

**Issue by sbecuwe** [latex3/latex2e#98]
## Brief outline of the bug

After upgrading the tools package using tlmgr to v49390, it turned out that one of the packages I use had changed (array (2018/11/13 v2.4j)) and now results in an error.

After reducing the number of packages I need to reconstruct to problem (since the fragment is part of larger document), it seems that loading or not loading xcolor (2016/05/11 v2.12) makes the difference.

Is it possible that array introduced an incompatibility with xcolor?

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}

\usepackage{longtable}
\usepackage{array}
\usepackage[table,usenames,dvipsnames]{xcolor}
\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}

\begin{document}

\begin{longtable}{L{3cm}L{2cm}C{0.4cm}C{0.4cm}C{1cm}L{1.1cm}L{2.5cm}L{1.9cm}L{2.2cm}}
\hline
a & b & c & d & e & f & g & h & i \\ \hline
\end{longtable}
  
\end{document}

```

## Log file (required) and possibly PDF file  

[dummy-table.log](https://github.com/latex3/latex2e/files/2675750/dummy-table.log)

**Comment by davidcarlisle** [comment]
Sorry about that, colortbl has been updated to fix this, it went to CTAN yesterday so should be in distributions soon, the diff is

https://github.com/davidcarlisle/dpctex/commit/48d1d3d40eb09e887eb89151ae322db9c9c5323b

Your test file works with that update.
