### ISSUE TITLE
Add full release date to ltnews

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex2e#982]
## Brief outline of the enhancement

Since the introduction of new bug-fix/update policy in Jun 2015, the LaTeX2e kernel is developing fast, probably faster than ever before.  Adjacent kernel releases now contains more feature and bug-fix differences, which calls for a more convenient way to get the full release date.

One of the many possible proposals would be, just add release date to the title part of each LaTeX News issue. For example,
- before: `LaTeX News<newline>Issue 36, November 2022`
- after: `LaTeX News<newline>Issue 36, November 2022 (2022-11-01)`
![image](https://user-images.githubusercontent.com/6376638/212447637-768cf480-ebe1-4375-8820-e99bb2260e32.png)

This will help (third-party) package and class authors/maintainers when writing `\NeedsTeXFormat{LaTeX2e}[<date>]`, as well as  community contributors who want to add info of required release version/date for some features used in their answers.

I have had this idea several times before, and it's Frank's comment https://github.com/latex3/latex2e/pull/980#discussion_r1069554226 makes me feel maybe it's time to open an issue.

**Comment by muzimuzhi** [comment]
- #980

has added words to direct `clsguide` readers to `changes.txt` in https://github.com/latex3/latex2e/pull/980/commits/f580284febc64849f674bd4ab2f721529c82da37.

But I think `ltnews` is better:
- `ltnews` is typeset/formated with bookmarks and hyperlinks.
- `ltnews` is easy to open through `texdoc ltnews` and even `texdoc ltnews<n>`, while `doc/latex/base/changes.txt` is listed at 4th position (on my incomplete texlive distribution) by `texdoc`, check result of `texdoc -l changes.txt`. (Although `texdoc changes.txt` can be configured to open `doc/latex/base/changes.txt`.)

**Comment by car222222** [comment]
Putting tgus in ltnews seems good.

**Comment by car222222** [comment]
Oops, "this".

**Comment by FrankMittelbach** [comment]
@muzimuzhi I agree with you, this is a goood and convenient place (despite the fact that not all changes are recorded there), the major ones that are likely to be relevant for `\NeedsTeXFormat` are. Would you like to help and make  pull request against the development branch to include a necessary change into ltnews.cls and the corresponding data into all ltnewsXX files? maybe something like `\LaTeXreleasedate{2022-11-01}` which stores the argument and uses it in the title.

**Comment by muzimuzhi** [comment]
> Would you like to help and make pull request against the development branch [...]

My pleasure. I'll work on this maybe tomorrow (Sunday).

**Comment by muzimuzhi** [comment]
One problem just encountered:
- Before [2017-04-15](https://github.com/latex3/latex2e/releases/tag/2017-04-15), the only accepted date format is yyyy/mm/dd.
- Since 2017-04-15, both yyyy-mm-dd and yyyy/mm/dd are supported (added by https://github.com/latex3/latex2e/commit/3ac54c89c74c4ffa5086d89aded3339795d853fd, also see the first entry in ltnews27), and the former one is preferred according to the incoming change to `clsguild` in #980.

What's your opinions about which date format should be used in per issue ltnews (`ltnews<n>.tex`) prior to 2017-04-15 and equal to or after that release?

**Comment by FrankMittelbach** [comment]
Given that all newsletters are combined in ltnews.pdf it would probably look nicer if it is always yyyy-mm-dd (even if we keep it as is in changes.txt). By the way, probably ltnews.tex needs also updating as part of the PR

**Comment by muzimuzhi** [comment]
> Given that all newsletters are combined in ltnews.pdf it would probably look nicer if it is always yyyy-mm-dd (even if we keep it as is in changes.txt).

But this will also update `ltnews<n>.pdf` and replace the existing ones hosted on CTAN mirrors. Then, if someone using an old LaTeX2e downloads the updated `ltnews<n>.pdf`, the yyyy-mm-dd format may be not supported yet. Well, that's rare.

**Comment by FrankMittelbach** [comment]
true, but this means the LaTeX is at least 6 years old, too bad I would say, despite the fact that for this he or she would need to even see the updated files (which is unlikely too if they aren't on the site (and they are pretty difficult to find otherwise). So I think we can ignore the issue going forward.

**Comment by FrankMittelbach** [comment]
@muzimuzhi I'm currently writing a note in ltnews37 and would like to mention you by name not by @muzimuzhi if that is ok with you (if not that's ok too, of course) but I was unable to find it --- not that I looked hard.

**Comment by muzimuzhi** [comment]
It's Yukai Chou. I've added that to my github profile 😄  Sorry for the inconvenience before.

**Comment by muzimuzhi** [comment]
For my limited use experience with the new ltnews with #984 applied, it seems to me that adding full release date only to ltnews titles and the corresponding toc entries is not very useful or not useful enough, especially when I'm reading a specific section and want to know the corresponding release date right now right here, without any page turning if possible.

One way is to show full release date also in PDF bookmarks/outlines, and use PDF viewers' "Find current bookmark" (it's so called in Adobe Reader) utility. They read "Issue nn, yyyy/mm" now, so a change to "Issue nn, yyyy-mm-dd" would help.

Another way is to show full release date in either page header or footer, except for the title page of each LaTeX Issue.

What do you think?
