### ISSUE TITLE
Release 2022-11-01 patch level 1 breaks compilation of rsproca template

### ISSUE THREAD

**Issue by smueller48** [latex3/latex2e#988]
## Brief outline of the bug
When compiling the template for "Proceedings of the Royal Society A" with  LaTeX2e Release 2022-11-01 patch level 1, the PDF-output is formatted incorrectly. PDF output works with earlier release versions.

## Minimal example showing the bug
The template files can be obtained from 
[https://www.overleaf.com](https://www.overleaf.com/latex/templates/proceedings-of-the-royal-society-a-latex-template/rfbwzkqsqdmv)

## Log file (required) and possibly PDF file  
[sample.log](https://github.com/latex3/latex2e/files/10535655/sample.log)
[sample.pdf](https://github.com/latex3/latex2e/files/10535658/sample.pdf)

**Comment by u-fischer** [comment]
This has been reported to the crop package https://github.com/rrthomas/crop/issues/3.

There is a firstaid for it in develop, but it will only get active when we release firstaid again. In the mean time you can use

```
\AddToHook{package/crop/after}{\stockwidth\paperwidth \stockheight\paperheight}
\documentclass[openacc]{rsproca_new}
```
