### ISSUE TITLE
Strange hyperlinked left parentheses in LaTeX News Issue 29

### ISSUE THREAD

**Issue by jfbu** [latex3/latex2e#99]
Here is a snapshot:

![capture d ecran 2018-12-16 a 12 04 46](https://user-images.githubusercontent.com/2589111/50052851-fa3bfb80-012a-11e9-854c-f5430fb261ea.png)

See the left parenthesis.

**Comment by jfbu** [comment]
On further inspection (as PDF user) these left parentheses are hyperlinks hence the color (as one sees by moving pointer on top of them). Hence "color leak" is bad title.

**Comment by jfbu** [comment]
![capture d ecran 2018-12-16 a 12 09 17](https://user-images.githubusercontent.com/2589111/50052875-759dad00-012b-11e9-8b1b-3e1d63ae3026.png)

**Comment by FrankMittelbach** [comment]
guess that definition used there could be improved :-)

**Comment by FrankMittelbach** [comment]
That was clearly an eyesight problem ... the code said `\url(...)` not `{...}` and since locally we don't color links we didn't see the issue.

**Comment by jfbu** [comment]
Eyes of `xparse` LaTeX users are now trained to accept fancy delimiters `:)`
