### ISSUE TITLE
\leftmark and \rightmark are not calculated correctly

### ISSUE THREAD

**Issue by lasjak** [latex3/latex2e#991]
## Brief outline of the bug
\leftmark and \rightmark on page are not calculated correctly - page one has \leftmark equal to first entry on page two, and page's two \rightmark is the second entry on the page.

It might be clearer when you think of dictionary style headers which I am trying to use:

- page 1 header is:
  <first entry from page 1> - <first entry from page 2> // should be: <first entry from page 1> - <last entry from page 1>
- page 2 header is:
  <second entry from page 2> - <last entry from page 2> // should be: <first entry from page 2> - <last entry from page 2>

Screenshots of headers with entries (attached test.pdf contains \topmark, \leftmark, and \rightmark) can be found in my question on tex.stackexchange: https://tex.stackexchange.com/q/672962/289018

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass[twocolumn,10pt,a4paper,twoside]{book}

\usepackage{ifthen}

\newcommand\entry[3][]{\ifx {#1} \par\hangpara{1em}{1}\markboth{#2}{#2}\else\par\markboth{#1}{#1}\fi\textbf{#2} #3}

% NB: category code of '@' temporarily changed to 11
% to enable its use in command names
\catcode `@=11
% Let \@oddfoot and \evenfoot be equivalent to \@empty
% to make them blank (empty)
\let\@oddfoot\empty\let\evenfoot\empty
% Redefine \@oddhead and \@evenhead
\renewcommand{\@oddhead}{topmark=\topmark / leftmark=\leftmark / rightmark=\rightmark}
\renewcommand{\@evenhead}{topmark=\topmark / leftmark=\leftmark / rightmark=\rightmark}
\catcode `@=12

\begin{document}
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a1}{ - no alternative text}%
\entry[b2]{a2}{- b2 as alternative text}%
\entry[b3]{a3}{- b3 as alternative text}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\entry{a}{}%
\end{document}
```

## Log file (required) and possibly PDF file  

[test.log](https://github.com/latex3/latex2e/files/10551515/test.log)
[test.pdf](https://github.com/latex3/latex2e/files/10551516/test.pdf)

**Comment by u-fischer** [comment]
You are executing your \markboth in vmode, and so before the text and the page break is then after it. If you add \showoutput to your document you can see that the mark is on page 1: 

~~~~
......\marks1{b2}
......\marks2{b2}
......\marks3{b2}
......\mark{{b2}{b2}}
~~~~

Use `\leavevmode\markboth{#2}{#2}`  etc.

**Comment by FrankMittelbach** [comment]
Everything works correctly.

Your issue is wrong coding of your macros (see above) and the fact that you can't use  the primitive `\topmark` at all in LaTeX. Use `\TopMark` and perhaps your own mark class (in which case you set the marks with `\PutMark`). 

See `texdoc ltmarks-doc` for the interface description or the upcoming LaTeX Companion 3rd edition
 - https://www.informit.com/store/latex-companion-3e-part-i-9780134658940
 - https://www.informit.com/store/latex-companion-3e-part-ii-9780201363005  (to be released end of April)

**Comment by lasjak** [comment]
Thank you @u-fischer I was not aware of these commands. You were right that leaving vmode will help with producing expected output.
